Create resource definition for IAP Tunnel DestGroup
GoogleCloudPlatform/magic-modules pull request #10064
Opened 2024-02-27 18:04 UTC by micrictor

Add a new resource definition for IAP tunnel destination groups and related IAM policies.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/17417

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
Add a new Terraform resource for IAP tunnel destination groups and related IAM policies.
```

2024-03-01 00:21 UTC, micrictor commented
@rileykarson PTAL

2024-03-05 21:22 UTC, micrictor commented
/gcbrun

2024-03-05 22:15 UTC, NickElliot commented
/gcbrun

2024-03-05 23:04 UTC, trodge commented
/gcbrun

2024-03-05 23:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 2046 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 2046 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 458 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 115 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_iap_tunnel_dest_group` (13 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_iap_tunnel_dest_group" "primary" {
  fqdns      = # value needed
  group_name = # value needed
}

```

2024-03-05 23:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `85`
Passed tests: `57`
Skipped tests: `20`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>iap</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIapTunnelDestGroupIamBindingGenerated|TestAccIapTunnelDestGroupIamBindingGenerated_withCondition|TestAccIapTunnelDestGroupIamMemberGenerated|TestAccIapTunnelDestGroupIamMemberGenerated_withCondition|TestAccIapTunnelDestGroupIamPolicyGenerated|TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition|TestAccIapTunnelDestGroup_iapDestgroupExample|TestAccIapTunnelDestGroup_updates </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-05 23:20 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIapTunnelDestGroupIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamBindingGenerated.log)]
`TestAccIapTunnelDestGroupIamBindingGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamBindingGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamBindingGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamMemberGenerated.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamMemberGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamMemberGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamPolicyGenerated.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition.log)]
`TestAccIapTunnelDestGroup_iapDestgroupExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroup_iapDestgroupExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroup_iapDestgroupExample.log)]
`TestAccIapTunnelDestGroup_updates`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_build/TestAccIapTunnelDestGroup_updates_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording/TestAccIapTunnelDestGroup_updates.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/80303dd3-4abf-4eef-9b5d-0ad30ad5801e/recording) for each test

2024-03-06 01:18 UTC, micrictor commented
Updated tests to use random suffixes for resource names and test the appropriate fields.

2024-03-08 20:16 UTC, NickElliot commented
/gcbrun

2024-03-08 20:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 1984 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 1984 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 458 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 109 insertions(+))

2024-03-08 20:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 1984 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10064-old..auto-pr-10064) ( 10 files changed, 1984 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 458 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10064-old..auto-pr-10064) ( 4 files changed, 109 insertions(+))

2024-03-08 20:30 UTC, modular-magician commented
#### Tests analytics
Total tests: `85`
Passed tests: `57`
Skipped tests: `20`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>iap</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIapTunnelDestGroupIamBindingGenerated|TestAccIapTunnelDestGroupIamBindingGenerated_withCondition|TestAccIapTunnelDestGroupIamMemberGenerated|TestAccIapTunnelDestGroupIamMemberGenerated_withCondition|TestAccIapTunnelDestGroupIamPolicyGenerated|TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition|TestAccIapTunnelDestGroup_iapDestgroupExample|TestAccIapTunnelDestGroup_updates </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-08 20:32 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIapTunnelDestGroupIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamBindingGenerated.log)]
`TestAccIapTunnelDestGroupIamBindingGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamBindingGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamMemberGenerated.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamMemberGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamPolicyGenerated.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition.log)]
`TestAccIapTunnelDestGroup_iapDestgroupExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroup_iapDestgroupExample.log)]
`TestAccIapTunnelDestGroup_updates`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording/TestAccIapTunnelDestGroup_updates.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccIapTunnelDestGroupIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/build-log/replaying_build_after_recording/TestAccIapTunnelDestGroupIamPolicyGenerated_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/replaying_after_recording/TestAccIapTunnelDestGroupIamPolicyGenerated.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/9739691a-8265-4eb5-82e1-1e7feef465de/recording) for each test

2024-03-08 20:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `85`
Passed tests: `57`
Skipped tests: `20`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>iap</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIapTunnelDestGroupIamBindingGenerated|TestAccIapTunnelDestGroupIamBindingGenerated_withCondition|TestAccIapTunnelDestGroupIamMemberGenerated|TestAccIapTunnelDestGroupIamMemberGenerated_withCondition|TestAccIapTunnelDestGroupIamPolicyGenerated|TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition|TestAccIapTunnelDestGroup_iapDestgroupExample|TestAccIapTunnelDestGroup_updates </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-08 20:36 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIapTunnelDestGroupIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamBindingGenerated.log)]
`TestAccIapTunnelDestGroupIamBindingGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamBindingGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamMemberGenerated.log)]
`TestAccIapTunnelDestGroupIamMemberGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamMemberGenerated_withCondition.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamPolicyGenerated.log)]
`TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroupIamPolicyGenerated_withCondition.log)]
`TestAccIapTunnelDestGroup_iapDestgroupExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroup_iapDestgroupExample.log)]
`TestAccIapTunnelDestGroup_updates`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording/TestAccIapTunnelDestGroup_updates.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10064/artifacts/e33b99f3-970c-4c7f-a20f-01eae78583a4/recording) for each test

2024-03-08 20:49 UTC, NickElliot requested changes
LGTM! Just remove these double empty lines and I'll approve/merge

2024-03-08 20:49 UTC, NickElliot commented on mmv1/products/iap/TunnelDestGroup.yaml
> +
```suggestion
```

2024-03-08 20:49 UTC, NickElliot commented on mmv1/products/iap/TunnelDestGroup.yaml
> +
```suggestion
```

2024-03-08 22:02 UTC, NickElliot approved these changes

2024-03-08 22:02 UTC, merged