Draft: Fix/types for idempotence
GoogleCloudPlatform/magic-modules pull request #10118
Opened 2024-03-05 07:30 UTC by Maarc-D

# Description

Linked to https://github.com/hashicorp/terraform-provider-google/issues/9353

**Release Note Template for Downstream PRs (will be copied)**

```release-note:breaking-change
Fix(types for idempotence): transform advertised_routes to Set instead of List to keep idempotence on each plan when you have a dynamic block. But it will create a change displayed on plan for all user even the ones not using dynamic. this change should not have any impact as gcp side at the routes will remain the same
```
# ToDo

Need to test it to be sure their is no impacts with https://registry.terraform.io/providers/public-cloud-wl/google/5.17.4 from https://github.com/public-cloud-wl/terraform-provider-google/commit/1a4d7e6ecb001cf279c502512133edda167f6f4a

2024-03-05 10:53 UTC, SarahFrench commented
Just a heads up - this would be a breaking change for the field ([see our guidance on this here](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes/#field-level-breaking-changes)) and would need to be included in an upcoming major release. We [make exceptions if the 'breaking change' fixes something that is broken for all users](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/#in-minor-releases) but I don't think that is the case here.

2024-03-06 15:00 UTC, Maarc-D commented
@SarahFrench In fact I would need to update the label because I tested It is not breaking change if the refresh is on nor change detected if there is not dans if refresh is set to false it wil say that it wat to reoder everythin so 1change but on apply everything is fine, tested and approved on my side, I will use my fork in the meaning time this one can be merge

2024-04-29 12:15 UTC, Maarc-D commented
> @Maarc-D sorry for the delay, this PR slipped off my radar!
> 
> We'd need to double check what users will experience when upgrading from a previous version of the provider to a version including this change. Even if there's a new diff that's resolved with a single apply, navigating that diff might not work well for people with more complex configurations.
> 
> I'll trigger tests to run: /gcbrun

no problem I putted back as draft because we experienced few cases where this one does not resolve completely the idempotency issue :/ sometime still prompt more changes that it should. No working impact but it is on this cases still hard to make review before apply.

2024-04-29 12:48 UTC, LucaPrete commented
Hello @SarahFrench this seems a huge pain for many of our large Google customers. Is there anything we can do to speed up the development/review? Happy to help!

BTW should we start to "undraft" this? :)

Thanks!

2024-04-30 14:05 UTC, SarahFrench requested changes
Changing an Array to a Set is a breaking change and will need to be part of a major release. The 6.0.0 major release is being planned currently and this PRs changes could be included then. Should we choose this option?

Alternatively, you can return the field to being an Array/list and then implement a custom flattener function for the field that reorders the API response to match the users configuration and minimise unnecessary diffs. There is new guidance about [how to do this in our contribution guide](https://googlecloudplatform.github.io/magic-modules/develop/permadiff/#list-order) and this PR is an example of the new helper functions being used: https://github.com/GoogleCloudPlatform/magic-modules/pull/10429 . If you choose this option please mark the PR as ready for review once you want feedback!

2024-05-01 09:58 UTC, SarahFrench commented on mmv1/products/compute/Router.yaml
>          name: advertisedIpRanges
This is currently causing a build error - to specify a field as a Set in these yaml files you will need to revert it back to  `!ruby/object:Api::Type::Array` and then add the property `is_set: true` to that field. However if you do that please refer to my previous review where making the change to a Set can only be in a major version.

2024-05-01 10:00 UTC, SarahFrench commented
Hi @LucaPrete - My review comments above describes the two routes forward for this PR/the [original issue](https://github.com/hashicorp/terraform-provider-google/issues/9353). @Maarc-D hasn't had enough time to respond to the review yet, but if this PR was to become stale then someone could open another PR informed from the discussion here.

2024-05-01 11:32 UTC, LucaPrete commented
Thank you @SarahFrench ! It makes absolutely sense to me.

I'd proceed with both paths in parallel:

* I opened a [new PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10572) that uses the flatten function. Waiting for the tests to complete. I'll add you in cc.

* @Maarc-D can you please address the comments of @SarahFrench. We can then think to merge this once we cut a new major? @SarahFrench do we have timelines for it (assuming the PR will be complete)?

2024-05-23 16:53 UTC, SarahFrench commented
@Maarc-D The 6.0.0 major release is coming up later this year. Do you want to proceed with this PR for that release?

2024-05-31 14:19 UTC, closed without merging

2024-08-21 09:16 UTC, Maarc-D commented
> Thank you @SarahFrench ! It makes absolutely sense to me.
> 
> I'd proceed with both paths in parallel:
> 
> * I opened a [new PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10572) that uses the flatten function. Waiting for the tests to complete. I'll add you in cc.
> * @Maarc-D can you please address the comments of @SarahFrench. We can then think to merge this once we cut a new major? @SarahFrench do we have timelines for it (assuming the PR will be complete)?

I did not get time to deep dive on it with my day to day job stuffs increasing, I seen you've creating your own PR, great, hope it will fix.

But this problem is recurrent on multiple resources I have the same mess with `consumer_accept_lists` on `google_compute_service_attachment`

2024-08-21 12:23 UTC, SarahFrench commented
Hi @Maarc-D - please open new GH issue(s) for any problems you're experiencing so that they can go through the triage process. Thanks!