Add apphub.admin role for the organization in the test environment
GoogleCloudPlatform/magic-modules pull request #10152
Opened 2024-03-08 19:17 UTC by krishnangopal1810

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-03-08 20:06 UTC, roaks3 requested changes
LGTM except small typo.

I've already gone ahead and granted this permission for all 3 test runners in our test org

2024-03-08 20:06 UTC, roaks3 commented on .ci/infra/terraform/main.tf
> +  billing_account_id = data.google_organization.org.org_id
Should be `org_id`

2024-03-08 20:26 UTC, roaks3 approved these changes
Approved (and changes have been made to the test env), but I'm going to keep this unmerged until everyone is fully settled on this approach. It's possible we want to revisit this later and use project-level permissions in some way.

2024-03-19 15:26 UTC, roaks3 commented
@krishnangopal1810 circling back on this: do you see any reason to change the strategy here in the short-term. I believe we should probably go ahead and merge this unless we expect it to change soon.

2024-03-20 20:20 UTC, krishnangopal1810 commented
> @krishnangopal1810 circling back on this: do you see any reason to change the strategy here in the short-term. I believe we should probably go ahead and merge this unless we expect it to change soon.

I don't see a reason to change the strategy here. I agree we should merge this change.

2024-03-21 18:12 UTC, roaks3 approved these changes

2024-03-21 18:12 UTC, merged