Change load_balancer_type to optional in dns_record_set resource
GoogleCloudPlatform/magic-modules pull request #10190
Opened 2024-03-13 14:43 UTC by nbodepudi

`load_balancer_type` is becoming optional to align with upcoming API changes. This change will introduce support for internal regional network proxy load balancers, as well as any other GCP load balancer that can be health checked.

**b/290267743**

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dns: change `load_balancer_type` field from required to optional
```

2024-03-13 14:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 111 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 111 insertions(+), 2 deletions(-))

2024-03-13 14:59 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `39`
Skipped tests: `6`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dns</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDNSRecordSet_routingPolicy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-13 15:05 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDNSRecordSet_routingPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/6044e858-8401-4bc1-baea-e4cb6b60444d/build-log/recording_build/TestAccDNSRecordSet_routingPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/6044e858-8401-4bc1-baea-e4cb6b60444d/recording/TestAccDNSRecordSet_routingPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/6044e858-8401-4bc1-baea-e4cb6b60444d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/6044e858-8401-4bc1-baea-e4cb6b60444d/recording) for each test

2024-03-13 15:07 UTC, slevenick requested changes
Looks like the test is failing. Is not having a load balancer type actually valid?

2024-03-13 19:24 UTC, nbodepudi commented
Hey, API changes are not in prod yet so the test is failing. Will make this PR a draft and reopen once they have landed.

2024-08-02 13:23 UTC, modular-magician commented
#### Tests analytics
Total tests: 47
Passed tests: 45
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dns</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDNSRecordSet_routingPolicy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-02 13:29 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDNSRecordSet_routingPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/5b8f3e12-0438-4e1e-bffc-ff5d9ca94fda/build-log/recording_build/TestAccDNSRecordSet_routingPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/5b8f3e12-0438-4e1e-bffc-ff5d9ca94fda/recording/TestAccDNSRecordSet_routingPolicy.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/5b8f3e12-0438-4e1e-bffc-ff5d9ca94fda/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/5b8f3e12-0438-4e1e-bffc-ff5d9ca94fda/recording) for each test

2024-08-02 13:30 UTC, slevenick requested changes
Looks like the API sends back the value as "none" instead of what we expect which would be not sending the value back at all.

There's a couple ways to fix that, maybe we should copy the API's pattern and allow sending the value of "none" specifically?

2024-08-06 16:26 UTC, nbodepudi commented
Hi @slevenick, For some reason acceptance tests for GA provider are not running in my machine  and it is throwing a weird error. I added a diff suppress func to fix this. I ran acceptance tests in beta, they were successful.  Please take a look when you have time.

2024-08-06 16:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 47
Passed tests: 45
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dns</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDNSRecordSet_routingPolicy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-06 16:46 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDNSRecordSet_routingPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/ea440626-b7dd-4595-8940-eaa2592e2bd9/recording/TestAccDNSRecordSet_routingPolicy.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/ea440626-b7dd-4595-8940-eaa2592e2bd9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/ea440626-b7dd-4595-8940-eaa2592e2bd9/recording) for each test

2024-08-06 17:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 125 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 125 insertions(+), 5 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dns_record_set` (35 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dns_record_set" "primary" {
  routing_policy {
    primary_backup {
      backup_geo {
        health_checked_targets {
          internal_load_balancers {
            load_balancer_type = # value needed
          }
        }
      }
    }
  }
}


```

2024-08-06 17:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 47
Passed tests: 46
Skipped tests: 1
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dns</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/a97b6303-4892-4cbf-94d9-825fe7b624de/build-log/replaying_test.log)

2024-08-07 20:52 UTC, slevenick requested changes

2024-08-07 20:52 UTC, slevenick commented on mmv1/third_party/terraform/services/dns/resource_dns_record_set.go
> +	if k != "routing_policy.0.primary_backup.0.primary.0.internal_load_balancers.0.load_balancer_type" {
So, `internal_load_balancers` is a list, which means this diff suppress func will only function on the first element of that list. Can you add a test that specifies 2 `internal_load_balancers` that would need to use this diff suppress func?

2024-08-08 16:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 148 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10190-old..auto-pr-10190) ( 3 files changed, 148 insertions(+), 5 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dns_record_set` (35 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dns_record_set" "primary" {
  routing_policy {
    primary_backup {
      backup_geo {
        health_checked_targets {
          internal_load_balancers {
            load_balancer_type = # value needed
          }
        }
      }
    }
  }
}


```

2024-08-08 16:44 UTC, modular-magician commented
#### Tests analytics
Total tests: 47
Passed tests: 45
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dns</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDNSRecordSet_routingPolicy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-08 16:53 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDNSRecordSet_routingPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/309d4c67-e1ca-4aca-9561-d693b6bfb867/recording/TestAccDNSRecordSet_routingPolicy.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/309d4c67-e1ca-4aca-9561-d693b6bfb867/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10190/artifacts/309d4c67-e1ca-4aca-9561-d693b6bfb867/recording) for each test

2024-08-08 21:40 UTC, slevenick approved these changes

2024-08-08 21:41 UTC, merged