Modify issue labeler to skip linked issues
GoogleCloudPlatform/magic-modules pull request #10199
Opened 2024-03-14 17:20 UTC by roaks3

Context is in the comment: adding service labels to a linked issue creates ambiguity that is difficult for us to detect and address, so we decided it was better to skip them.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-03-14 17:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-03-14 18:28 UTC, melinath requested changes
could you add a test for this behavior?

2024-03-14 18:29 UTC, melinath commented
actually this seems like it should have caused the "add missing service labels even if already linked" to start failing... but apparently it didn't? Are we running these tests automatically?

2024-03-14 18:39 UTC, roaks3 commented
Ah yep, that thought crossed my mind here but I forgot to follow up. Let me look at added a test for this.

2024-03-14 18:50 UTC, roaks3 commented
Confirmed that the test was not run in CI, and it did fail when running locally. I've updated the test to reflect the change, but we should update them to run in PRs.

cc @trodge is this a known limitation, or perhaps we removed this behavior by accident?

2024-03-14 18:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-03-14 20:08 UTC, melinath approved these changes
LGTM. It would be great to also run tests on PRs as a GHA - but that doesn't need to happen in this PR.

2024-03-14 22:20 UTC, trodge commented
> Confirmed that the test was not run in CI, and it did fail when running locally. I've updated the test to reflect the change, but we should update them to run in PRs.
> 
> cc @trodge is this a known limitation, or perhaps we removed this behavior by accident?

I don't think we ever ran these tests as part of CI.

2024-03-14 22:20 UTC, trodge approved these changes

2024-03-15 14:59 UTC, roaks3 commented
Created https://github.com/hashicorp/terraform-provider-google/issues/17598

2024-03-15 14:59 UTC, merged