Add (regional) instance group manager resource manager tags support.
GoogleCloudPlatform/magic-modules pull request #10217
Opened 2024-03-18 13:35 UTC by pjotrekk

This PR enables passing input-only field `params` to Managed Instance Group and Regional Managed Instance Group. It has `resource_manager_tags` field that enables to set Resource Manager Tags to MIGs at creation time.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Added input-only `params` field that enables to create Managed Instance Group and Regional Managed Instance Group with Resource Manager Tags .
```

2024-03-18 13:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 5 files changed, 242 insertions(+), 18 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 280 insertions(+), 18 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `version` default value changed from <nil> to STU3 on `google_healthcare_fhir_store` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.


## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-03-18 14:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 232 insertions(+), 18 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 280 insertions(+), 18 deletions(-))

2024-03-18 16:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 232 insertions(+), 18 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 280 insertions(+), 18 deletions(-))

2024-03-18 17:17 UTC, modular-magician commented
#### Tests analytics
Total tests: `3528`
Passed tests: `3106`
Skipped tests: `359`
Affected tests: `63`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 63 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApphubWorkload_apphubWorkloadBasicExample|TestAccApphubWorkload_apphubWorkloadFullExample|TestAccApphubWorkload_apphubWorkloadUpdate|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate|TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample|TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendInternalManaged|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccComputeRegionPerInstanceConfig_statefulIps|TestAccComputeRegionPerInstanceConfig_update|TestAccDataSourceApphubDiscoveredWorkload_basic|TestAccDataSourceGoogleComputeInstanceGroupManager|TestAccDataSourceGoogleComputeInstanceGroup_fromIGM|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccRegionInstanceGroupManager_APISideListRecordering|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_versions </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-18 18:37 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccApphubWorkload_apphubWorkloadBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccApphubWorkload_apphubWorkloadBasicExample.log)]
`TestAccApphubWorkload_apphubWorkloadFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccApphubWorkload_apphubWorkloadFullExample.log)]
`TestAccApphubWorkload_apphubWorkloadUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccApphubWorkload_apphubWorkloadUpdate.log)]
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeBackendService_withBackend`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeBackendService_withBackend.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputeBackendService_withBackendAndMaxUtilization`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeBackendService_withBackendAndMaxUtilization.log)]
`TestAccComputeBackendService_withMaxConnections`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeBackendService_withMaxConnections.log)]
`TestAccComputeBackendService_withMaxConnectionsPerInstance`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeBackendService_withMaxConnectionsPerInstance.log)]
`TestAccComputeForwardingRule_forwardingRuleHttpLbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeForwardingRule_forwardingRuleHttpLbExample.log)]
`TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample.log)]
`TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate.log)]
`TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample.log)]
`TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample.log)]
`TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputePerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/ea53f554-a196-4197-b58c-3d95ba4eafce/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-102 [...]

2024-03-19 14:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 212 insertions(+), 18 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 260 insertions(+), 18 deletions(-))

2024-03-19 14:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 241 insertions(+), 19 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 8 files changed, 289 insertions(+), 19 deletions(-))

2024-03-19 15:54 UTC, modular-magician commented
#### Tests analytics
Total tests: `3529`
Passed tests: `3166`
Skipped tests: `359`
Affected tests: `4`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceGoogleServiceAccountJwt|TestAccInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_resourceManagerTags </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-19 15:58 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataSourceGoogleServiceAccountJwt`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/recording/TestAccDataSourceGoogleServiceAccountJwt.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/build-log/replaying_build_after_recording/TestAccInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/replaying_after_recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/build-log/replaying_build_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/replaying_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGoogleServiceAccountAccessToken_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/build-log/recording_build/TestAccDataSourceGoogleServiceAccountAccessToken_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/recording/TestAccDataSourceGoogleServiceAccountAccessToken_basic.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/bacf9aa6-1e09-45f8-9e5b-bcead893d055/recording) for each test

2024-03-20 10:22 UTC, modular-magician commented
#### Tests analytics
Total tests: `3532`
Passed tests: `3171`
Skipped tests: `359`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_resourceManagerTags </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-20 10:26 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/build-log/replaying_build_after_recording/TestAccInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/replaying_after_recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/build-log/replaying_build_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/replaying_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/072004ae-197b-4f71-ae11-024ac507f3bf/recording) for each test

2024-03-20 10:46 UTC, askubis commented
LGTM&Approval for resource logic

2024-03-20 10:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 241 insertions(+), 19 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 8 files changed, 289 insertions(+), 19 deletions(-))

2024-03-20 11:58 UTC, modular-magician commented
#### Tests analytics
Total tests: `3532`
Passed tests: `3171`
Skipped tests: `359`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_resourceManagerTags </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-20 12:02 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/build-log/replaying_build_after_recording/TestAccInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/replaying_after_recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/build-log/replaying_build_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/replaying_after_recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/21ddfd45-7bc0-4339-887c-aa763a7b06d4/recording) for each test

2024-03-20 14:14 UTC, modular-magician commented
#### Tests analytics
Total tests: `3532`
Passed tests: `3171`
Skipped tests: `359`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_resourceManagerTags </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-20 14:19 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/f094dd2d-536b-4a8f-af47-93c5b0b7d878/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/f094dd2d-536b-4a8f-af47-93c5b0b7d878/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/f094dd2d-536b-4a8f-af47-93c5b0b7d878/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/f094dd2d-536b-4a8f-af47-93c5b0b7d878/recording) for each test

2024-03-27 00:14 UTC, shuyama1 reviewed
Looks like a significant amount of tests are triggers for this change https://github.com/GoogleCloudPlatform/magic-modules/pull/10217#issuecomment-2004662343. I'll test it locally to make sure this change does not affect pre-existing configurations. Just want to be extra cautious since these fields are non-updatable. 

Meanwhile, @pjotrekk would you mind resolving the conflicts in go.mod and go.sum files? Thanks!

2024-04-02 04:16 UTC, shuyama1 commented
Tested locally and doesn't seem the change affects pre-existing configurations (wonder why multiple tests are triggered in recording though 🤷 ). Mostly LGTM. we'll still need to resolve the conflicts though. Thanks :)

2024-04-02 09:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 191 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 239 insertions(+), 1 deletion(-))

2024-04-02 09:42 UTC, modular-magician commented
#### Tests analytics
Total tests: `893`
Passed tests: `821`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/fcd2e2ac-f230-427f-b9c7-08fcc00e0d12/build-log/replaying_test.log)

2024-04-02 12:12 UTC, pjotrekk commented
> Tested locally and doesn't seem the change affects pre-existing configurations (wonder why multiple tests are triggered in recording though 🤷 ). Mostly LGTM. we'll still need to resolve the conflicts though. Thanks :)

Conflicts resolved. PTAL :)

2024-04-03 07:39 UTC, askubis approved these changes
LGTM!

2024-04-05 00:04 UTC, shuyama1 requested changes
Would you mind also rebasing your PR. Sorry we had some issues in our CI earlier. a rebase should pick up the latest fix. Thank you!

2024-04-10 11:28 UTC, pjotrekk commented on mmv1/third_party/terraform/services/compute/resource_compute_instance_group_manager_test.go.erb
> +func TestAccInstanceGroupManager_resourceManagerTags(t *testing.T) {
Not a problem, thanks for catching this! Added the version guard

2024-04-10 11:28 UTC, pjotrekk commented on mmv1/third_party/terraform/services/compute/resource_compute_region_instance_group_manager_test.go.erb
> +func TestAccRegionInstanceGroupManager_resourceManagerTags(t *testing.T) {
Done

2024-04-10 11:29 UTC, pjotrekk commented
@shuyama1 I rebased and added the guards. PTAL

2024-04-10 11:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 191 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 239 insertions(+), 1 deletion(-))

2024-04-10 11:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 4 files changed, 31 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 239 insertions(+), 1 deletion(-))

2024-04-10 11:54 UTC, modular-magician commented
#### Tests analytics
Total tests: `898`
Passed tests: `826`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10217/artifacts/c2bf1718-d9a3-4383-8b15-ec4fc96e021f/build-log/replaying_test.log)

2024-04-10 12:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10217-old..auto-pr-10217) ( 2 files changed, 29 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10217-old..auto-pr-10217) ( 6 files changed, 239 insertions(+), 1 deletion(-))

2024-04-11 23:27 UTC, shuyama1 approved these changes
LGTM. Thanks!

2024-04-11 23:28 UTC, merged