Remove relay_mode field support
GoogleCloudPlatform/magic-modules pull request #10274
Opened 2024-03-25 12:35 UTC by siwiutki

relay_mode field from AdvancedDatapathObservabilityConfig is superseded by enable_relay field and will be deprecated on the provider side in near future.

This is a breaking change according to TF docs and as such, should be release in the next major release. Deprecation of relay_mode field on TF side has already happened more than a month ago, foreshadowing this change through deprecation message.

This field is part of a provider feature that is still in Public Preview and yet to go GA.

```release-note:breaking-change
container: remove support for `relay_mode` field in `advanced_datapath_observability_config`, users are expected to use `enable_relay` field instead
```

```
Fixes b/325234971
```

2024-03-25 15:33 UTC, zli82016 commented
/gcbrun

2024-03-25 15:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` changed from optional to required on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-optional-to-required)
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` default value changed from false to <nil> on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)
- Field `monitoring_config.advanced_datapath_observability_config.relay_mode` within resource `google_container_cluster` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-03-25 15:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` changed from optional to required on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-optional-to-required)
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` default value changed from false to <nil> on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)
- Field `monitoring_config.advanced_datapath_observability_config.relay_mode` within resource `google_container_cluster` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-03-25 15:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `185`
Passed tests: `171`
Skipped tests: `12`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withMonitoringConfig|TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-25 15:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `185`
Passed tests: `171`
Skipped tests: `12`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withMonitoringConfig|TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-03-25 16:03 UTC, zli82016 commented
The breaking change should be put in the next major release 6.0. The target date for major release is Aug 2024. It is a little bit earlier to work on release 6.0 now. You can close this PR and then open a new PR later for release 6.0.

2024-03-25 16:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerCluster_withMonitoringConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/d61f0e6e-7f7a-4dda-8e9a-0f15a711aa06/recording/TestAccContainerCluster_withMonitoringConfig.log)]
`TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/d61f0e6e-7f7a-4dda-8e9a-0f15a711aa06/recording/TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/d61f0e6e-7f7a-4dda-8e9a-0f15a711aa06/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/d61f0e6e-7f7a-4dda-8e9a-0f15a711aa06/recording) for each test

2024-03-25 16:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerCluster_withMonitoringConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/5173a1f2-2b56-48a9-89a0-074efae3e2dc/recording/TestAccContainerCluster_withMonitoringConfig.log)]
`TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/5173a1f2-2b56-48a9-89a0-074efae3e2dc/recording/TestAccContainerCluster_withMonitoringConfigAdvancedDatapathObservabilityConfig.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/5173a1f2-2b56-48a9-89a0-074efae3e2dc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/5173a1f2-2b56-48a9-89a0-074efae3e2dc/recording) for each test

2024-05-01 17:56 UTC, zli82016 commented
The change needs to be made for 6.0 release.

2024-05-01 17:59 UTC, c2thorn commented
We can keep it open and move it to the eventual major release branch when it gets closer to time?

2024-05-01 18:00 UTC, zli82016 commented
Created a Github issue https://github.com/hashicorp/terraform-provider-google/issues/17997

2024-05-01 18:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10274-old..auto-pr-10274) ( 2 files changed, 7 insertions(+), 166 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` changed from optional to required on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-optional-to-required)
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` default value changed from false to <nil> on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)
- Field `monitoring_config.advanced_datapath_observability_config.relay_mode` within resource `google_container_cluster` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-05-01 18:39 UTC, modular-magician commented
#### Tests analytics
Total tests: `190`
Passed tests: `180`
Skipped tests: `10`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/cafa83e3-7abe-4d1a-8c74-c3b21401f460/build-log/replaying_test.log)

2024-07-09 18:41 UTC, zli82016 commented
@siwiutki , the window to contribute to the provider 6.0 release is open now. Feel free to move this PR to https://github.com/GoogleCloudPlatform/magic-modules/commits/FEATURE-BRANCH-major-release-6.0.0/

2024-07-10 09:26 UTC, siwiutki commented
@zli82016 I changed the target branch. Let me know if any more action is required from my side to push this forward.

2024-07-10 16:50 UTC, zli82016 commented
@siwiutki , thanks for making the change.

After checking the [guide](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/#in-the-600-major-release) to make change in 6.0 release branch, more changes are needed.
1. Add the deprecation message to `relay_mode` field in the doc `container_cluster.html.markdown` in [main](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown?plain=1#L631) branch in a separate PR.
[Example](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/#add-deprecations-and-warnings-to-the-main-branch-of-magic-modules) can be found in the guide.
2. Remove `relay_mode` field from the doc `container_cluster.html.markdown` in 6.0 release branch
3. Add the upgrade guide entries to [version_6_upgrade.html.markdown](https://github.com/GoogleCloudPlatform/magic-modules/blob/FEATURE-BRANCH-major-release-6.0.0/mmv1/third_party/terraform/website/docs/guides/version_6_upgrade.html.markdown).

2024-07-11 17:32 UTC, zli82016 requested changes
More changes are needed.

2024-07-25 10:03 UTC, siwiutki commented
> 1. Add the deprecation message to `relay_mode` field in the doc `container_cluster.html.markdown` in [main](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown?plain=1#L631) branch in a separate PR.

Since this requires a separate PR before we can handle this PR, let me mark this as draft for now so that reviewers won't be nagged or sth.

2024-07-25 10:26 UTC, siwiutki commented
@zli82016 Please let me know if there's anything more than https://github.com/GoogleCloudPlatform/magic-modules/pull/11254 that's required to handle your first requested point.

2024-07-25 17:47 UTC, zli82016 commented
> @zli82016 Please let me know if there's anything more than #11254 that's required to handle your first requested point.

That is it. Thanks for creating the PR #11254, which is merged to the main branch.

2024-07-29 13:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10274-old..auto-pr-10274) ( 4 files changed, 38 insertions(+), 171 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10274-old..auto-pr-10274) ( 4 files changed, 38 insertions(+), 171 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` changed from optional to required on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-optional-to-required)
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` default value changed from false to <nil> on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)
- Field `monitoring_config.advanced_datapath_observability_config.relay_mode` within resource `google_container_cluster` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-07-29 13:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 198
Passed tests: 187
Skipped tests: 10
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withMonitoringConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-29 13:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerCluster_withMonitoringConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/72190de3-f7ef-457b-b03f-1365c5010cb0/recording/TestAccContainerCluster_withMonitoringConfig.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/72190de3-f7ef-457b-b03f-1365c5010cb0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/72190de3-f7ef-457b-b03f-1365c5010cb0/recording) for each test

2024-07-30 16:48 UTC, zli82016 commented
LGTM. 

@c2thorn , does it need to wait for the [changes](https://github.com/GoogleCloudPlatform/magic-modules/pull/11254) in the main branch merged to 6.0 feature branch and then merge this PR? Thanks.

2024-07-30 17:21 UTC, c2thorn commented
> LGTM.
> 
> @c2thorn , does merging this PR need to wait for the [changes](https://github.com/GoogleCloudPlatform/magic-modules/pull/11254) in the main branch merged to 6.0 feature branch first? Thanks.

ideally, yes as it may lead to a merge conflict. Apologies on the delay of the sync, I'll get it started today.

2024-07-30 17:32 UTC, zli82016 commented
> ideally, yes as it may lead to a merge conflict. Apologies on the delay of the sync, I'll get it started today.

Thanks, just want to confirm. Sure, take your time.

2024-08-02 16:59 UTC, zli82016 approved these changes
LGTM

2024-08-05 17:07 UTC, c2thorn commented
The [sync](https://github.com/GoogleCloudPlatform/magic-modules/pull/11329) was merged, looks like there are merge conflicts now. Apologies and thanks for the wait.

2024-08-09 01:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10274-old..auto-pr-10274) ( 4 files changed, 40 insertions(+), 174 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10274-old..auto-pr-10274) ( 4 files changed, 40 insertions(+), 174 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` changed from optional to required on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-optional-to-required)
- Field `monitoring_config.advanced_datapath_observability_config.enable_relay` default value changed from false to <nil> on `google_container_cluster` - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#field-changing-default-value)
- Field `monitoring_config.advanced_datapath_observability_config.relay_mode` within resource `google_container_cluster` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-08-09 01:24 UTC, modular-magician commented
#### Tests analytics
Total tests: 200
Passed tests: 190
Skipped tests: 10
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10274/artifacts/376a00fb-f5b0-4fcd-abcd-c5215245a64a/build-log/replaying_test.log)

2024-08-09 08:36 UTC, siwiutki commented
Resolved merge conflicts, seems like it's mergable now.

2024-08-09 16:07 UTC, zli82016 approved these changes
LGTM. Thanks.

2024-08-09 16:07 UTC, merged