Replace terraform-plugin-sdk with terraform-plugin-testing
GoogleCloudPlatform/magic-modules pull request #10339
Opened 2024-04-01 21:48 UTC by trodge

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-04-01 22:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1011 files changed, 1342 insertions(+), 1336 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1172 files changed, 1553 insertions(+), 1547 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-01 22:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/b1c551b9-31bb-4310-9c91-63668739c0d5/build-log/replaying_test.log)

2024-04-02 20:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1032 files changed, 1516 insertions(+), 1510 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1194 files changed, 1728 insertions(+), 1722 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-02 21:03 UTC, modular-magician commented
#### Tests analytics
Total tests: `1511`
Passed tests: `1275`
Skipped tests: `158`
Affected tests: `78`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 78 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccApiGatewayApiConfigIamPolicyGenerated|TestAccApiGatewayApiIamPolicyGenerated|TestAccApiGatewayGatewayIamPolicyGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccArtifactRegistryRepositoryIamPolicyGenerated|TestAccBigQueryDataset_access|TestAccBigQueryTableIamPolicyGenerated|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated|TestAccBigqueryAnalyticsHubListingIamPolicyGenerated|TestAccBigqueryConnectionConnectionIamPolicyGenerated|TestAccBigqueryDatapolicyDataPolicyIamPolicyGenerated|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccCloudRunServiceIamPolicyGenerated|TestAccCloudRunV2JobIamPolicyGenerated|TestAccCloudRunV2ServiceIamPolicyGenerated|TestAccCloudRunV2Service_cloudrunv2ServiceGRPCProbesUpdate|TestAccCloudTasksQueueIamPolicyGenerated|TestAccCloudbuildv2ConnectionIamPolicyGenerated|TestAccCloudfunctions2functionIamPolicyGenerated|TestAccContainerAnalysisNoteIamPolicyGenerated|TestAccDataCatalogEntryGroupIamPolicyGenerated|TestAccDataCatalogPolicyTagIamPolicyGenerated|TestAccDataCatalogTagTemplateIamPolicyGenerated|TestAccDataCatalogTaxonomyIamPolicyGenerated|TestAccDataFusionInstanceIamPolicyGenerated|TestAccDataSourceGoogleArtifactRegistryRepositoryConfig|TestAccDataSourceGoogleBigqueryDataset_basic|TestAccDataSourceGoogleCloudFunctions2Function_basic|TestAccDataSourceGooglePubsubSubscription_basic|TestAccDataSourceGooglePubsubSubscription_optionalProject|TestAccDataSourceGooglePubsubTopic_basic|TestAccDataSourceGooglePubsubTopic_optionalProject|TestAccDataSourceGoogleSourceRepoRepository_basic|TestAccDataSourceIAMBetaWorkloadIdentityPoolProvider_basic|TestAccDataSourceIAMBetaWorkloadIdentityPool_basic|TestAccDataSourceSecretManagerSecret_basic|TestAccDataSourceVmwareEngineNetwork_basic|TestAccDataSourceVmwareengineNetworkPeering_basic|TestAccDataSourceVmwareengineNetworkPolicy_basic|TestAccDataformRepositoryIamPolicyGenerated|TestAccDataprocMetastoreServiceIamPolicyGenerated|TestAccDatasourceSecretManagerSecretVersion_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainCloudRunExample|TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainFullExample|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccGKEBackupBackupPlanIamPolicyGenerated|TestAccGKEBackupRestorePlanIamPolicyGenerated|TestAccIapAppEngineServiceIamPolicyGenerated|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccIapTunnelDestGroupIamPolicyGenerated|TestAccIapTunnelIamPolicyGenerated|TestAccIapTunnelInstanceIamPolicyGenerated|TestAccIapWebBackendServiceIamPolicyGenerated|TestAccIapWebIamPolicyGenerated|TestAccIapWebRegionBackendServiceIamPolicyGenerated|TestAccIapWebTypeAppEngineIamPolicyGenerated|TestAccIapWebTypeComputeIamPolicyGenerated|TestAccNotebooksInstanceIamPolicyGenerated|TestAccNotebooksInstance_create_gpu|TestAccNotebooksRuntimeIamPolicyGenerated|TestAccPubsubSchemaIamPolicyGenerated|TestAccPubsubSubscriptionIamPolicy|TestAccPubsubTopicIamPolicyGenerated|TestAccSecretManagerSecretIamPolicyGenerated|TestAccSecureSourceManagerInstanceIamPolicyGenerated|TestAccServiceDirectoryNamespaceIamPolicyGenerated|TestAccServiceDirectoryServiceIamPolicyGenerated|TestAccSourceRepoRepositoryIamPolicyGenerated|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate|TestAccWorkbenchInstanceIamPolicyGenerated|TestAccWorkstationsWorkstationConfigIamPolicyGenerated|TestAccWorkstationsWorkstationIamPolicyGenerated </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-02 22:56 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccApiGatewayApiConfigIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccApiGatewayApiConfigIamPolicyGenerated.log)]
`TestAccApiGatewayApiIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccApiGatewayApiIamPolicyGenerated.log)]
`TestAccApiGatewayGatewayIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccApiGatewayGatewayIamPolicyGenerated.log)]
`TestAccApigeeEnvironmentIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccApigeeEnvironmentIamPolicyGenerated.log)]
`TestAccArtifactRegistryRepositoryIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccArtifactRegistryRepositoryIamPolicyGenerated.log)]
`TestAccBigQueryTableIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBigQueryTableIamPolicyGenerated.log)]
`TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated.log)]
`TestAccBigqueryAnalyticsHubListingIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBigqueryAnalyticsHubListingIamPolicyGenerated.log)]
`TestAccBigqueryConnectionConnectionIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBigqueryConnectionConnectionIamPolicyGenerated.log)]
`TestAccBigqueryDatapolicyDataPolicyIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBigqueryDatapolicyDataPolicyIamPolicyGenerated.log)]
`TestAccBillingBudget_budgetFilterProjectsOrdering`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccBillingBudget_budgetFilterProjectsOrdering.log)]
`TestAccCloudRunServiceIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudRunServiceIamPolicyGenerated.log)]
`TestAccCloudRunV2JobIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudRunV2JobIamPolicyGenerated.log)]
`TestAccCloudRunV2ServiceIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudRunV2ServiceIamPolicyGenerated.log)]
`TestAccCloudRunV2Service_cloudrunv2ServiceGRPCProbesUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudRunV2Service_cloudrunv2ServiceGRPCProbesUpdate.log)]
`TestAccCloudTasksQueueIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudTasksQueueIamPolicyGenerated.log)]
`TestAccCloudbuildv2ConnectionIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudbuildv2ConnectionIamPolicyGenerated.log)]
`TestAccCloudfunctions2functionIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccCloudfunctions2functionIamPolicyGenerated.log)]
`TestAccContainerAnalysisNoteIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccContainerAnalysisNoteIamPolicyGenerated.log)]
`TestAccDataCatalogEntryGroupIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataCatalogEntryGroupIamPolicyGenerated.log)]
`TestAccDataCatalogPolicyTagIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataCatalogPolicyTagIamPolicyGenerated.log)]
`TestAccDataCatalogTagTemplateIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataCatalogTagTemplateIamPolicyGenerated.log)]
`TestAccDataCatalogTaxonomyIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataCatalogTaxonomyIamPolicyGenerated.log)]
`TestAccDataFusionInstanceIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataFusionInstanceIamPolicyGenerated.log)]
`TestAccDataSourceGoogleArtifactRegistryRepositoryConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGoogleArtifactRegistryRepositoryConfig.log)]
`TestAccDataSourceGoogleBigqueryDataset_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGoogleBigqueryDataset_basic.log)]
`TestAccDataSourceGoogleCloudFunctions2Function_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGoogleCloudFunctions2Function_basic.log)]
`TestAccDataSourceGooglePubsubSubscription_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGooglePubsubSubscription_basic.log)]
`TestAccDataSourceGooglePubsubSubscription_optionalProject`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGooglePubsubSubscription_optionalProject.log)]
`TestAccDataSourceGooglePubsubTopic_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGooglePubsubTopic_basic.log)]
`TestAccDataSourceGooglePubsubTopic_optionalProject`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGooglePubsubTopic_optionalProject.log)]
`TestAccDataSourceGoogleSourceRepoRepository_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/f1a54808-97a9-4cc0-9c39-ffcec72c6a20/recording/TestAccDataSourceGoogleSourceRepoRepository_basic.log)]
`TestAccData [...]

2024-04-02 23:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1033 files changed, 1585 insertions(+), 1579 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1195 files changed, 1810 insertions(+), 1804 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-02 23:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1025 files changed, 1626 insertions(+), 1620 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1187 files changed, 1851 insertions(+), 1845 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-02 23:27 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/7d6f5ebd-9531-4717-8641-ed8d3f06cb33/build-log/replaying_test.log)

2024-04-03 21:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1025 files changed, 1628 insertions(+), 1620 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1186 files changed, 1855 insertions(+), 1845 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-03 22:03 UTC, modular-magician commented
#### Tests analytics
Total tests: `3542`
Passed tests: `2974`
Skipped tests: `366`
Affected tests: `202`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 202 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationAttestorIamPolicyGenerated|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccCloudFunctionsCloudFunctionIamPolicyGenerated|TestAccClouddeployCustomTargetTypeIamPolicyGenerated|TestAccClouddeployDeliveryPipelineIamPolicyGenerated|TestAccClouddeployTargetIamPolicyGenerated|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironmentAirflow2_withRecoveryConfig|TestAccComposerEnvironmentAirflow2_withSoftwareConfig|TestAccComposerEnvironmentComposer1_private|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_basic|TestAccComposerEnvironmentComposer3_update|TestAccComposerEnvironmentComposer3_updateFromEmpty|TestAccComposerEnvironmentComposer3_updateToEmpty|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironmentComposer3_updateWithNetworkAttachment|TestAccComposerEnvironmentComposer3_upgrade_expectError|TestAccComposerEnvironmentComposer3_withNetworkAttachment|TestAccComposerEnvironment_ComposerV2|TestAccComposerEnvironment_ComposerV2HighResilience|TestAccComposerEnvironment_UpdateComposerV2|TestAccComposerEnvironment_UpdateComposerV2ResilienceMode|TestAccComposerEnvironment_UpdateComposerV2WithTriggerer|TestAccComposerEnvironment_basic|TestAccComposerEnvironment_composerV1MasterAuthNetworks|TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate|TestAccComposerEnvironment_composerV2MasterAuthNetworks|TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_customBucket|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_update|TestAccComposerEnvironment_withDatabaseConfig|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComposerEnvironment_withSoftwareConfig|TestAccComposerEnvironment_withUpdateOnCreate|TestAccComposerEnvironment_withWebServerConfig|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendBucketIamPolicyGenerated|TestAccComputeBackendServiceIamPolicyGenerated|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeDiskIamPolicyGenerated|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeImageIamPolicyGenerated|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceIamPolicyGenerated|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeMachineImageIamPolicyGenerated|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendServiceIamPolicyGenerated|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionDiskIamPolicyGenerated|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSnapshotIamPolicyGenerated|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeSubnetworkIamPolicyGenerated|TestAccComputeTargetPool_update|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_withNetworkPolicyEnabled|TestAccContainerCluster_withSandboxConfig|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZoneIamPolicyGenerated|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataKmsSecretCiphertext_basic|TestAccDataSourceComputeAddress|TestAccDataSourceComputeBackendBucket_basic|TestAccDataSourceComputeBackendService_basic|TestAccDataSourceComputeImageFilter|TestAccDataSourceComputeInstance_basic|TestAccDataSourceComputeInstance_networkAttachmentUsageExample|TestAccDataSourceComputeReservation|TestAccDataSourceGoogleCloudBuildTrigger_basic|TestAccDataSourceGoogleCloudFunctionsFunction_basic|TestAccDataSourceGoogleComputeDisk_basic|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceGoogleStorageBucket_avoidComputeAPI|TestAccDataSourceGoogleStorageBucket_basic|TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccDataSourceSqlDatabaseInstance_basic|TestAccDataformRepositoryIamPolicyGenerated|TestAccDataplexAssetIamPolicyGenerated|TestAccDataplexDatascanIamPolicyGenerated|TestAccDataplexLakeIamPolicyGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexZoneIamPolicyGenerated|TestAccDataprocAutoscalingPolicyIamPolicyGenerated|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccFolderIamPolicy_basic|TestAccGKEHub2ScopeIamPolicyGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccHealthcareConsentStoreIamPolicyGenerated|TestAcc [...]

2024-04-03 22:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1024 files changed, 1627 insertions(+), 1619 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1185 files changed, 1854 insertions(+), 1844 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 1 file changed, 1 insertion(+), 1 deletion(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-03 23:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1024 files changed, 1627 insertions(+), 1619 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1185 files changed, 1855 insertions(+), 1845 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-04 00:24 UTC, modular-magician commented
#### Tests analytics
Total tests: `3553`
Passed tests: `2982`
Skipped tests: `367`
Affected tests: `204`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 204 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationAttestorIamPolicyGenerated|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccCloudFunctionsCloudFunctionIamPolicyGenerated|TestAccClouddeployCustomTargetTypeIamPolicyGenerated|TestAccClouddeployDeliveryPipelineIamPolicyGenerated|TestAccClouddeployTargetIamPolicyGenerated|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironmentAirflow2_withRecoveryConfig|TestAccComposerEnvironmentAirflow2_withSoftwareConfig|TestAccComposerEnvironmentComposer1_private|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_basic|TestAccComposerEnvironmentComposer3_update|TestAccComposerEnvironmentComposer3_updateFromEmpty|TestAccComposerEnvironmentComposer3_updateToEmpty|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironmentComposer3_updateWithNetworkAttachment|TestAccComposerEnvironmentComposer3_upgrade_expectError|TestAccComposerEnvironmentComposer3_withNetworkAttachment|TestAccComposerEnvironment_ComposerV2|TestAccComposerEnvironment_ComposerV2HighResilience|TestAccComposerEnvironment_UpdateComposerV2|TestAccComposerEnvironment_UpdateComposerV2ResilienceMode|TestAccComposerEnvironment_UpdateComposerV2WithTriggerer|TestAccComposerEnvironment_basic|TestAccComposerEnvironment_composerV1MasterAuthNetworks|TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate|TestAccComposerEnvironment_composerV2MasterAuthNetworks|TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_customBucket|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_update|TestAccComposerEnvironment_withDatabaseConfig|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComposerEnvironment_withSoftwareConfig|TestAccComposerEnvironment_withUpdateOnCreate|TestAccComposerEnvironment_withWebServerConfig|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendBucketIamPolicyGenerated|TestAccComputeBackendServiceIamPolicyGenerated|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeDiskIamPolicyGenerated|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeImageIamPolicyGenerated|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceIamPolicyGenerated|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeMachineImageIamPolicyGenerated|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendServiceIamPolicyGenerated|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionDiskIamPolicyGenerated|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSnapshotIamPolicyGenerated|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeSubnetworkIamPolicyGenerated|TestAccComputeTargetPool_update|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_withNetworkPolicyEnabled|TestAccContainerCluster_withSandboxConfig|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZoneIamPolicyGenerated|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataKmsSecretCiphertext_basic|TestAccDataSourceComputeAddress|TestAccDataSourceComputeBackendBucket_basic|TestAccDataSourceComputeBackendService_basic|TestAccDataSourceComputeImageFilter|TestAccDataSourceComputeInstance_basic|TestAccDataSourceComputeInstance_networkAttachmentUsageExample|TestAccDataSourceComputeReservation|TestAccDataSourceGoogleCloudBuildTrigger_basic|TestAccDataSourceGoogleCloudFunctionsFunction_basic|TestAccDataSourceGoogleComputeDisk_basic|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceGoogleStorageBucket_avoidComputeAPI|TestAccDataSourceGoogleStorageBucket_basic|TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccDataSourceSqlDatabaseInstance_basic|TestAccDataformRepositoryIamPolicyGenerated|TestAccDataplexAssetIamPolicyGenerated|TestAccDataplexDatascanIamPolicyGenerated|TestAccDataplexLakeIamPolicyGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexZoneIamPolicyGenerated|TestAccDataprocAutoscalingPolicyIamPolicyGenerated|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccFolderIamPolicy_basic|TestAccGKEHub2ScopeIamPolicyGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccHealthcareConsentStoreIamPolicyGenerated|TestAcc [...]

2024-04-04 18:22 UTC, trodge commented
/gcbrun

2024-04-04 18:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1024 files changed, 1627 insertions(+), 1619 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1185 files changed, 1855 insertions(+), 1845 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed schema labels.

Other:
- Failed to update service labels

2024-04-11 17:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1026 files changed, 1630 insertions(+), 1622 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1186 files changed, 1857 insertions(+), 1847 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

2024-04-11 18:41 UTC, modular-magician commented
#### Tests analytics
Total tests: `2920`
Passed tests: `2478`
Skipped tests: `357`
Affected tests: `85`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 85 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceSqlDatabaseInstance_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_updateDifferentFlagOrder|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccSqlUser_postgresIAM|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-11 19:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1027 files changed, 1632 insertions(+), 1624 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1187 files changed, 1859 insertions(+), 1849 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

2024-04-11 19:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1028 files changed, 1634 insertions(+), 1626 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1189 files changed, 1862 insertions(+), 1852 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

2024-04-11 19:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1028 files changed, 1634 insertions(+), 1626 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1189 files changed, 1862 insertions(+), 1852 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 6 insertions(+), 6 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

2024-04-11 19:59 UTC, modular-magician commented
#### Tests analytics
Total tests: `3558`
Passed tests: `3071`
Skipped tests: `369`
Affected tests: `118`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 118 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceSqlDatabaseInstance_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_updateDifferentFlagOrder|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccSqlUser_postgresIAM|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-11 20:36 UTC, modular-magician commented
#### Tests analytics
Total tests: `3570`
Passed tests: `3082`
Skipped tests: `369`
Affected tests: `119`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 119 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceSqlDatabaseInstance_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccHealthcareDatasetIamPolicy|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_updateDifferentFlagOrder|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccSqlUser_postgresIAM|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-11 20:38 UTC, modular-magician commented
#### Tests analytics
Total tests: `3570`
Passed tests: `3083`
Skipped tests: `369`
Affected tests: `118`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 118 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_maintenanceWindowUpdate|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withMaintenanceWindow|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_basic|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccDataSourceSqlDatabaseInstance_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_updateDifferentFlagOrder|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccSqlUser_postgresIAM|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-11 22:31 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork.log)]
`TestAccComposerEnvironment_maintenanceWindowUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_maintenanceWindowUpdate.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComposerEnvironment_withMaintenanceWindow`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_withMaintenanceWindow.log)]
`TestAccContainerCluster_withDatabaseEncryption`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccContainerCluster_withDatabaseEncryption.log)]
`TestAccDataSourceSqlDatabaseInstance_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccDataSourceSqlDatabaseInstance_basic.log)]
`TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls.log)]
`TestAccSqlDatabaseInstance_updateDifferentFlagOrder`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccSqlDatabaseInstance_updateDifferentFlagOrder.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAccessApprovalSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccAccessApprovalSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccAccessApprovalSettings.log)]
`TestAccAccessContextManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccAccessContextManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccAccessContextManager.log)]
`TestAccBigQueryDataset_access`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccBigQueryDataset_access_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccBigQueryDataset_access.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval.log)]
`TestAccBinaryAuthorizationPolicy_full`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccBinaryAuthorizationPolicy_full_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccBinaryAuthorizationPolicy_full.log)]
`TestAccBinaryAuthorizationPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccBinaryAuthorizationPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccBinaryAuthorizationPolicy_update.log)]
`TestAccComposerEnvironmentComposer2_private`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccComposerEnvironmentComposer2_private_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironmentComposer2_private.log)]
`TestAccComposerEnvironment_composerV2PrivateServiceConnect`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccComposerEnvironment_composerV2PrivateServiceConnect_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_composerV2PrivateServiceConnect.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccComposerEnvironment_privateWithWebServerControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComputeAddress_instanceWithIpExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/build-log/recording_build/TestAccComputeAddress_instanceWithIpExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/afc7220c-3c79-4fc4-b32c-f1d85680fe98/recording/TestAccCom [...]

2024-04-11 23:05 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork.log)]
`TestAccComposerEnvironment_maintenanceWindowUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironment_maintenanceWindowUpdate.log)]
`TestAccComposerEnvironment_withMaintenanceWindow`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironment_withMaintenanceWindow.log)]
`TestAccComputeNetworkPeering_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComputeNetworkPeering_basic.log)]
`TestAccDataSourceSqlDatabaseInstance_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccDataSourceSqlDatabaseInstance_basic.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccHealthcareDatasetIamPolicy.log)]
`TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls.log)]
`TestAccSqlDatabaseInstance_updateDifferentFlagOrder`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccSqlDatabaseInstance_updateDifferentFlagOrder.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAccessApprovalSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccAccessApprovalSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccAccessApprovalSettings.log)]
`TestAccAccessContextManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccAccessContextManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccAccessContextManager.log)]
`TestAccBigQueryDataset_access`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccBigQueryDataset_access_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccBigQueryDataset_access.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval.log)]
`TestAccBinaryAuthorizationPolicy_full`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccBinaryAuthorizationPolicy_full_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccBinaryAuthorizationPolicy_full.log)]
`TestAccBinaryAuthorizationPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccBinaryAuthorizationPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccBinaryAuthorizationPolicy_update.log)]
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironmentComposer2_private`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccComposerEnvironmentComposer2_private_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironmentComposer2_private.log)]
`TestAccComposerEnvironment_composerV2PrivateServiceConnect`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccComposerEnvironment_composerV2PrivateServiceConnect_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironment_composerV2PrivateServiceConnect.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccComposerEnvironment_privateWithWebServerControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer1_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/15eb940d-c43c-47e4-b227-d1de485dc7d9/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccComposerEnvironment_ [...]

2024-04-12 20:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1016 files changed, 1675 insertions(+), 1661 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1176 files changed, 1913 insertions(+), 1897 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 1 insertion(+), 10 deletions(-))


## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-04-12 20:55 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/cea69f3b-6a5e-479a-a52c-41f16c5869b7/build-log/replaying_test.log)

2024-04-17 17:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1017 files changed, 1675 insertions(+), 1661 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1177 files changed, 1913 insertions(+), 1897 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 1 insertion(+), 10 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-17 17:07 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/49f2a085-1dce-47ec-a953-3ae42351cd7b/build-log/replaying_test.log)

2024-04-17 19:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1018 files changed, 1676 insertions(+), 1662 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1178 files changed, 1914 insertions(+), 1898 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 1 insertion(+), 10 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-17 19:30 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/7d450c5d-93a0-4c5b-82a6-4fa566e03d74/build-log/replaying_test.log)

2024-04-17 19:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1020 files changed, 1682 insertions(+), 1668 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1180 files changed, 1920 insertions(+), 1904 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 7 insertions(+), 12 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-17 20:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4f82f5a4-e687-42ff-9e12-18e6b33984b1/build-log/replaying_test.log)

2024-04-17 22:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1028 files changed, 1735 insertions(+), 1721 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1188 files changed, 1973 insertions(+), 1957 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 7 insertions(+), 12 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-17 22:57 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc2a77d4-d308-46be-a0c1-a192705e1faa/build-log/replaying_test.log)

2024-04-17 23:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1032 files changed, 1743 insertions(+), 1729 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1193 files changed, 1984 insertions(+), 1968 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 15 insertions(+), 15 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-18 00:18 UTC, modular-magician commented
#### Tests analytics
Total tests: `3600`
Passed tests: `3121`
Skipped tests: `364`
Affected tests: `115`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 115 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAppEngineFlexibleAppVersion_update|TestAccAppEngineStandardAppVersion_update|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccCloudRunV2Service_cloudrunv2ServiceMountNfsExample|TestAccComposerEnvironmentComposer2_private|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccHealthcareDatasetIamPolicy|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectIamMemberRemove_basic|TestAccProjectIamMemberRemove_memberInMultipleBindings|TestAccProjectIamMemberRemove_multipleMembersInBinding|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-18 02:27 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMountNfsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMountNfsExample.log)]
`TestAccComposerEnvironmentComposer2_private`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComposerEnvironmentComposer2_private.log)]
`TestAccComposerEnvironment_composerV2PrivateServiceConnect`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComposerEnvironment_composerV2PrivateServiceConnect.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComputeBackendService_withBackendAndMaxUtilization`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComputeBackendService_withBackendAndMaxUtilization.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccHealthcareDatasetIamPolicy.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAccessApprovalSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccAccessApprovalSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccAccessApprovalSettings.log)]
`TestAccAccessContextManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccAccessContextManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccAccessContextManager.log)]
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccBigQueryDataset_access`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccBigQueryDataset_access_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccBigQueryDataset_access.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval.log)]
`TestAccBinaryAuthorizationPolicy_full`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccBinaryAuthorizationPolicy_full_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccBinaryAuthorizationPolicy_full.log)]
`TestAccBinaryAuthorizationPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccBinaryAuthorizationPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccBinaryAuthorizationPolicy_update.log)]
`TestAccComputeAddress_instanceWithIpExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccComputeAddress_instanceWithIpExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComputeAddress_instanceWithIpExample.log)]
`TestAccComputeBackendService_backendServiceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccComputeBackendService_backendServiceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComputeBackendService_backendServiceBasicExample.log)]
`TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample.log)]
`TestAccComputeBackendService_backendServiceCacheExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/build-log/recording_build/TestAccComputeBackendService_backendServiceCacheExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e732a539-1dd3-4b1b-99d1-88b3b93c0061/recording/TestAccComputeBackendService_backendServiceCa [...]

2024-04-18 20:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1032 files changed, 1743 insertions(+), 1729 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1193 files changed, 1984 insertions(+), 1968 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10339-old..auto-pr-10339) ( 6 files changed, 15 insertions(+), 15 deletions(-))


## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-04-18 21:08 UTC, modular-magician commented
#### Tests analytics
Total tests: `3600`
Passed tests: `3129`
Skipped tests: `364`
Affected tests: `107`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

#### Action taken
<details> <summary>Found 107 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigQueryDataset_access|TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval|TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval|TestAccBinaryAuthorizationPolicy_full|TestAccBinaryAuthorizationPolicy_update|TestAccComputeAddress_instanceWithIpExample|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample|TestAccComputeBackendService_backendServiceCacheExample|TestAccComputeBackendService_backendServiceCacheSimpleExample|TestAccComputeBackendService_backendServiceExternalManagedExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_multiWriter|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeNetworkAttachment_networkAttachmentInstanceUsageExample|TestAccComputeNetworkEndpointGroup_internalEndpoint|TestAccComputeNetworkEndpointGroup_networkEndpointGroupNonGcpExample|TestAccComputeNetworkPeering_customRoutesUpdate|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_regionBackendServiceBasicExample|TestAccComputeRegionBackendService_regionBackendServiceCacheExample|TestAccComputeRegionBackendService_regionBackendServiceConnectionTrackingExample|TestAccComputeRegionBackendService_regionBackendServiceExternalExample|TestAccComputeRegionBackendService_regionBackendServiceExternalWeightedExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRingHashExample|TestAccComputeRegionBackendService_regionBackendServiceIlbRoundRobinExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionSslPolicy_update|TestAccComputeRegionSslPolicy_update_from_custom|TestAccComputeRegionSslPolicy_update_to_custom|TestAccComputeRegionUrlMap_advanced|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_withPrivateNatAndRules|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitNetworksExample|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeSslPolicy_update|TestAccComputeSslPolicy_update_from_custom|TestAccComputeSslPolicy_update_to_custom|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_threadsPerCore|TestAccContainerNodePool_withMultiNicNetworkConfig|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivateMultiprojectExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_dnsPolicyMultiprojectExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccFirebaseDatabaseInstance_firebaseDatabaseInstanceStateChange|TestAccFirestoreField_firestoreFieldUpdateAddIndexExample|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccKmsKeyRingImportJob_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamBinding_multiple|TestAccProjectIamMemberRemove_basic|TestAccProjectIamMemberRemove_memberInMultipleBindings|TestAccProjectIamMemberRemove_multipleMembersInBinding|TestAccProjectOrganizationPolicy|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful|TestAccSqlDatabaseInstance_encryptionKey|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccSqlDatabaseInstance_replica|TestAccSqlDatabaseInstance_slave|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccStorageBucket_SoftDeletePolicy|TestAccStorageBucket_basicWithAutoclass|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRulesNoAge|TestAccStorageBucket_update|TestAccStorageTransferJob_basic|TestAccStorageTransferJob_eventStream|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_objectConditions|TestAccStorageTransferJob_transferOptions|TestAccVmwareengineExternalAccessRule_vmwareEngineExternalAccessRuleUpdate|TestAccVmwareengineExternalAddress_vmwareEngineExternalAddressUpdate|TestAccVmwareengineSubnet_vmwareEngineUserDefinedSubnetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-18 23:06 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIapAppEngineVersionIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccIapAppEngineVersionIamPolicyGenerated.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAccessApprovalSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccAccessApprovalSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccAccessApprovalSettings.log)]
`TestAccAccessContextManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccAccessContextManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccAccessContextManager.log)]
`TestAccBigQueryDataset_access`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccBigQueryDataset_access_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccBigQueryDataset_access.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccBigQueryTable_TableReplicationInfo_WithReplicationInterval.log)]
`TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccBigQueryTable_TableReplicationInfo_WithoutReplicationInterval.log)]
`TestAccBinaryAuthorizationPolicy_full`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccBinaryAuthorizationPolicy_full_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccBinaryAuthorizationPolicy_full.log)]
`TestAccBinaryAuthorizationPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccBinaryAuthorizationPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccBinaryAuthorizationPolicy_update.log)]
`TestAccComputeAddress_instanceWithIpExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeAddress_instanceWithIpExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeAddress_instanceWithIpExample.log)]
`TestAccComputeBackendService_backendServiceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceBasicExample.log)]
`TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceCacheBypassCacheOnRequestHeadersExample.log)]
`TestAccComputeBackendService_backendServiceCacheExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceCacheExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceCacheExample.log)]
`TestAccComputeBackendService_backendServiceCacheSimpleExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceCacheSimpleExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceCacheSimpleExample.log)]
`TestAccComputeBackendService_backendServiceExternalManagedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceExternalManagedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceExternalManagedExample.log)]
`TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample.log)]
`TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/build-log/recording_build/TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/64f1f879-f57d-47bc-bdcb-c018b64cd661/recording/TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample.log)]
`TestAccCom [...]

2024-06-18 21:10 UTC, modular-magician commented
#### Tests analytics
Total tests: `36`
Passed tests: `36`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6b907fd6-b329-4271-88b1-8e0e2d192e75/build-log/replaying_test.log)

2024-06-18 21:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1028 files changed, 1617 insertions(+), 1609 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1196 files changed, 1852 insertions(+), 1844 deletions(-))

2024-06-18 21:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `36`
Passed tests: `36`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/7867f14a-f7bd-46fe-9965-a88a2af58d40/build-log/replaying_test.log)

2024-06-18 21:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1028 files changed, 1617 insertions(+), 1609 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1196 files changed, 1852 insertions(+), 1844 deletions(-))

2024-06-18 22:01 UTC, modular-magician commented
#### Tests analytics
Total tests: `36`
Passed tests: `36`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/12708702-7b7d-44db-959a-161c7b3d5c7b/build-log/replaying_test.log)

2024-06-18 22:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1023 files changed, 1614 insertions(+), 1606 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1191 files changed, 1849 insertions(+), 1841 deletions(-))

2024-06-18 22:15 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/dd6b89d3-cb03-4cb6-bf37-c2c5612b4ca6/build-log/replaying_test.log)

2024-06-24 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1052 files changed, 1672 insertions(+), 1664 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1219 files changed, 1905 insertions(+), 1897 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-24 21:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1052 files changed, 1671 insertions(+), 1663 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1219 files changed, 1904 insertions(+), 1896 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-26 20:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1052 files changed, 1670 insertions(+), 1662 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1219 files changed, 1903 insertions(+), 1895 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-27 21:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1054 files changed, 1671 insertions(+), 1665 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1221 files changed, 1904 insertions(+), 1898 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-27 21:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/9642ce2a-c782-49d9-bc71-42e53d400be4/build-log/replaying_test.log)

2024-06-27 22:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1055 files changed, 1719 insertions(+), 1704 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1222 files changed, 1952 insertions(+), 1937 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-27 22:07 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/5f26f5c0-a00b-4d93-952b-92e7d6d6c293/build-log/replaying_test.log)

2024-06-27 22:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1055 files changed, 1720 insertions(+), 1704 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1222 files changed, 1953 insertions(+), 1937 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-27 23:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 3695
Passed tests: 3232
Skipped tests: 366
Affected tests: 97

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 97 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessApprovalSettings</li>
<li>TestAccAccessContextManager</li>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccBillingBudget_budgetFilterProjectsOrdering</li>
<li>TestAccCloudRunV2JobIamPolicyGenerated</li>
<li>TestAccCloudfunctions2functionIamPolicyGenerated</li>
<li>TestAccComposer1Environment_withNodeConfig</li>
<li>TestAccComposer2Environment_withNodeConfig</li>
<li>TestAccComposerEnvironmentAirflow2_withRecoveryConfig</li>
<li>TestAccComposerEnvironmentAirflow2_withSoftwareConfig</li>
<li>TestAccComposerEnvironmentComposer1_private</li>
<li>TestAccComposerEnvironmentComposer2_private</li>
<li>TestAccComposerEnvironmentComposer3_basic</li>
<li>TestAccComposerEnvironmentComposer3_update</li>
<li>TestAccComposerEnvironmentComposer3_updateFromEmpty</li>
<li>TestAccComposerEnvironmentComposer3_updateToEmpty</li>
<li>TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork</li>
<li>TestAccComposerEnvironmentComposer3_updateWithNetworkAttachment</li>
<li>TestAccComposerEnvironmentComposer3_upgrade_expectError</li>
<li>TestAccComposerEnvironmentComposer3_withNetworkAttachment</li>
<li>TestAccComposerEnvironment_ComposerV2</li>
<li>TestAccComposerEnvironment_ComposerV2HighResilience</li>
<li>TestAccComposerEnvironment_UpdateComposerV2</li>
<li>TestAccComposerEnvironment_UpdateComposerV2ResilienceMode</li>
<li>TestAccComposerEnvironment_UpdateComposerV2WithTriggerer</li>
<li>TestAccComposerEnvironment_basic</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworks</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate</li>
<li>TestAccComposerEnvironment_composerV2MasterAuthNetworks</li>
<li>TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate</li>
<li>TestAccComposerEnvironment_composerV2PrivateServiceConnect</li>
<li>TestAccComposerEnvironment_customBucket</li>
<li>TestAccComposerEnvironment_maintenanceWindowUpdate</li>
<li>TestAccComposerEnvironment_privateWithWebServerControl</li>
<li>TestAccComposerEnvironment_update</li>
<li>TestAccComposerEnvironment_withDatabaseConfig</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer1</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer2</li>
<li>TestAccComposerEnvironment_withMaintenanceWindow</li>
<li>TestAccComposerEnvironment_withSoftwareConfig</li>
<li>TestAccComposerEnvironment_withUpdateOnCreate</li>
<li>TestAccComposerEnvironment_withWebServerConfig</li>
<li>TestAccComputeBackendService_withBackendAndMaxUtilization</li>
<li>TestAccComputeInstanceIamPolicyGenerated</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccComputeMachineImageIamPolicyGenerated</li>
<li>TestAccComputeSnapshotIamPolicyGenerated</li>
<li>TestAccComputeTargetPool_update</li>
<li>TestAccContainerCluster_nodeAutoprovisioningDefaults</li>
<li>TestAccContainerCluster_withDatabaseEncryption</li>
<li>TestAccContainerCluster_withSandboxConfig</li>
<li>TestAccDNSManagedZoneIamPolicyGenerated</li>
<li>TestAccDataKmsSecretCiphertext_basic</li>
<li>TestAccDataSourceComputeAddress</li>
<li>TestAccDataSourceComputeBackendBucket_basic</li>
<li>TestAccDataSourceComputeBackendService_basic</li>
<li>TestAccDataSourceComputeImageFilter</li>
<li>TestAccDataSourceComputeInstance_basic</li>
<li>TestAccDataSourceComputeInstance_networkAttachmentUsageExample</li>
<li>TestAccDataSourceGoogleArtifactRegistryRepositoryConfig</li>
<li>TestAccDataSourceGoogleBigqueryDataset_basic</li>
<li>TestAccDataSourceGoogleCloudBuildTrigger_basic</li>
<li>TestAccDataSourceGoogleCloudFunctions2Function_basic</li>
<li>TestAccDataSourceGoogleCloudFunctionsFunction_basic</li>
<li>TestAccDataSourceGooglePubsubSubscription_basic</li>
<li>TestAccDataSourceGooglePubsubSubscription_optionalProject</li>
<li>TestAccDataSourceGooglePubsubTopic_basic</li>
<li>TestAccDataSourceGooglePubsubTopic_optionalProject</li>
<li>TestAccDataSourceGoogleSourceRepoRepository_basic</li>
<li>TestAccDataSourceIAMBetaWorkloadIdentityPoolProvider_basic</li>
<li>TestAccDataSourceIAMBetaWorkloadIdentityPool_basic</li>
<li>TestAccDataSourceSecretManagerSecret_basic</li>
<li>TestAccDataSourceSqlDatabaseInstance_basic</li>
<li>TestAccDataSourceVmwareEngineNetwork_basic</li>
<li>TestAccDataSourceVmwareengineNetworkPeering_basic</li>
<li>TestAccDataSourceVmwareengineNetworkPolicy_basic</li>
<li>TestAccDataplexTaskIamPolicyGenerated</li>
<li>TestAccDatasourceSecretManagerSecretVersion_basic</li>
<li>TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainFullExample</li>
<li>TestAccHealthcareDatasetIamPolicy</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccIapAppEngineVersionIamPolicyGenerated</li>
<li>TestAccIapTunnelInstanceIamPolicyGenerated</li>
<li>TestAccOrganizationIamCustomRole_undelete</li>
<li>TestAccPrivatecaCertificateTemplateIamPolicyGenerated</li>
<li>TestAccProjectIamCustomRole_undelete</li>
<li>TestAccProjectIamPolicy_basic</li>
<li>TestAccPubsubSubscriptionIamPolicy</li>
<li>TestAccSecretManagerSecretIamPolicyGenerated</li>
<li>TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls</li>
<li>TestAccSqlDatabaseInstance_updateDifferentFlagOrder</li>
<li>TestAccVertexAIEndpointIamPolicy</li>
<li>TestAccWorkstationsWorkstationConfigIamBindingGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamMemberGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamPolicyGenerated</li>
<li>TestAccWorkstationsWorkstationConfig_update</li>
<li>TestAccWorkstationsWorkstationConfig_workstationConfigBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-27 23:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1056 files changed, 1721 insertions(+), 1705 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1223 files changed, 1954 insertions(+), 1938 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-27 23:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/2de0a605-301f-43e5-8bcd-5ef2fc654b69/build-log/replaying_test.log)

2024-06-28 02:05 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAccessContextManager`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccAccessContextManager.log)]
`TestAccBillingBudget_budgetFilterProjectsOrdering`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccBillingBudget_budgetFilterProjectsOrdering.log)]
`TestAccCloudRunV2JobIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccCloudRunV2JobIamPolicyGenerated.log)]
`TestAccCloudfunctions2functionIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccCloudfunctions2functionIamPolicyGenerated.log)]
`TestAccComposer2Environment_withNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccComposerEnvironmentAirflow2_withRecoveryConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentAirflow2_withRecoveryConfig.log)]
`TestAccComposerEnvironmentAirflow2_withSoftwareConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentAirflow2_withSoftwareConfig.log)]
`TestAccComposerEnvironmentComposer1_private`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer1_private.log)]
`TestAccComposerEnvironmentComposer3_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_basic.log)]
`TestAccComposerEnvironmentComposer3_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_update.log)]
`TestAccComposerEnvironmentComposer3_updateFromEmpty`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_updateFromEmpty.log)]
`TestAccComposerEnvironmentComposer3_updateToEmpty`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_updateToEmpty.log)]
`TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_updateWithNetworkAndSubnetwork.log)]
`TestAccComposerEnvironmentComposer3_updateWithNetworkAttachment`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_updateWithNetworkAttachment.log)]
`TestAccComposerEnvironmentComposer3_upgrade_expectError`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_upgrade_expectError.log)]
`TestAccComposerEnvironmentComposer3_withNetworkAttachment`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironmentComposer3_withNetworkAttachment.log)]
`TestAccComposerEnvironment_ComposerV2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_ComposerV2.log)]
`TestAccComposerEnvironment_ComposerV2HighResilience`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_ComposerV2HighResilience.log)]
`TestAccComposerEnvironment_UpdateComposerV2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_UpdateComposerV2.log)]
`TestAccComposerEnvironment_UpdateComposerV2ResilienceMode`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_UpdateComposerV2ResilienceMode.log)]
`TestAccComposerEnvironment_UpdateComposerV2WithTriggerer`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_UpdateComposerV2WithTriggerer.log)]
`TestAccComposerEnvironment_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_basic.log)]
`TestAccComposerEnvironment_composerV2MasterAuthNetworks`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_composerV2MasterAuthNetworks.log)]
`TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate.log)]
`TestAccComposerEnvironment_customBucket`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_customBucket.log)]
`TestAccComposerEnvironment_withSoftwareConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_withSoftwareConfig.log)]
`TestAccComposerEnvironment_withUpdateOnCreate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_withUpdateOnCreate.log)]
`TestAccComposerEnvironment_withWebServerConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComposerEnvironment_withWebServerConfig.log)]
`TestAccComputeBackendService_withBackendAndMaxUtilization`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComputeBackendService_withBackendAndMaxUtilization.log)]
`TestAccComputeInstanceIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComputeInstanceIamPolicyGenerated.log)]
`TestAccComputeMachineImageIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/TestAccComputeMachineImageIamPolicyGenerated.log)]
`TestAccComputeSnapshotIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35557d7-f61a-4e80-933d-867d52c5da6e/recording/Tes [...]

2024-06-28 22:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1060 files changed, 1770 insertions(+), 1756 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1227 files changed, 2004 insertions(+), 1990 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-28 22:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/58d4f086-ae6c-4940-9697-55e8f7cc2ef9/build-log/replaying_test.log)

2024-06-28 22:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1060 files changed, 1768 insertions(+), 1756 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1227 files changed, 2002 insertions(+), 1990 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-06-28 23:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 3819
Passed tests: 3418
Skipped tests: 378
Affected tests: 23

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 23 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccComposer1Environment_withNodeConfig</li>
<li>TestAccComposerEnvironmentComposer2_private</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworks</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate</li>
<li>TestAccComposerEnvironment_composerV2PrivateServiceConnect</li>
<li>TestAccComposerEnvironment_maintenanceWindowUpdate</li>
<li>TestAccComposerEnvironment_privateWithWebServerControl</li>
<li>TestAccComposerEnvironment_update</li>
<li>TestAccComposerEnvironment_withDatabaseConfig</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer1</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer2</li>
<li>TestAccComposerEnvironment_withMaintenanceWindow</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccDataSourceGoogleStorageBucket_avoidComputeAPI</li>
<li>TestAccDataSourceGoogleStorageBucket_basic</li>
<li>TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainCloudRunExample</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamBindingGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamMemberGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamPolicyGenerated</li>
<li>TestAccWorkstationsWorkstationConfig_update</li>
<li>TestAccWorkstationsWorkstationConfig_workstationConfigBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-29 00:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironment_maintenanceWindowUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_maintenanceWindowUpdate.log)]
`TestAccComposerEnvironment_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_update.log)]
`TestAccComposerEnvironment_withDatabaseConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_withDatabaseConfig.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComposerEnvironment_withMaintenanceWindow`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_withMaintenanceWindow.log)]
`TestAccDataSourceGoogleStorageBucket_avoidComputeAPI`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccDataSourceGoogleStorageBucket_avoidComputeAPI.log)]
`TestAccDataSourceGoogleStorageBucket_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccDataSourceGoogleStorageBucket_basic.log)]
`TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainCloudRunExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccFirebaseHostingCustomDomain_firebasehostingCustomdomainCloudRunExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironmentComposer2_private`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironmentComposer2_private_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironmentComposer2_private.log)]
`TestAccComposerEnvironment_composerV1MasterAuthNetworks`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironment_composerV1MasterAuthNetworks_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_composerV1MasterAuthNetworks.log)]
`TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate.log)]
`TestAccComposerEnvironment_composerV2PrivateServiceConnect`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironment_composerV2PrivateServiceConnect_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_composerV2PrivateServiceConnect.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironment_privateWithWebServerControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer1_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccWorkstationsWorkstationConfigIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccWorkstationsWorkstationConfigIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/recording/TestAccWorkstationsWorkstationConfigIamBindingGenerated.log)]
`TestAccWorkstationsWorkstationConfigIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4eff11b2-3790-4b09-8dcc-d6b2f33565c5/build-log/recording_build/TestAccWorkstationsWorkstationConfigIamMemberGenerated_recording_test.log) [...]

2024-07-01 17:35 UTC, trodge commented
/gcbrun

2024-07-01 17:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1060 files changed, 1768 insertions(+), 1756 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1227 files changed, 2002 insertions(+), 1990 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-01 18:53 UTC, modular-magician commented
#### Tests analytics
Total tests: 3837
Passed tests: 3448
Skipped tests: 378
Affected tests: 11

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 11 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccComposer1Environment_withNodeConfig</li>
<li>TestAccComposerEnvironmentComposer2_private</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworks</li>
<li>TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate</li>
<li>TestAccComposerEnvironment_composerV2PrivateServiceConnect</li>
<li>TestAccComposerEnvironment_privateWithWebServerControl</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer1</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccWorkstationsWorkstationConfigIamPolicyGenerated</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-01 19:45 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironmentComposer2_private`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironmentComposer2_private.log)]
`TestAccComposerEnvironment_composerV1MasterAuthNetworks`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironment_composerV1MasterAuthNetworks.log)]
`TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate.log)]
`TestAccComposerEnvironment_composerV2PrivateServiceConnect`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironment_composerV2PrivateServiceConnect.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccWorkstationsWorkstationConfigIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccWorkstationsWorkstationConfigIamPolicyGenerated.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_build/TestAccComposerEnvironment_privateWithWebServerControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/851fca73-800f-4428-b23d-08f1b36f36be/recording) for each test

2024-07-03 20:55 UTC, zli82016 requested changes

2024-07-03 20:55 UTC, zli82016 commented on mmv1/third_party/terraform/acctest/go/resource_test_utils.go
> +package acctest
This file is needed. `go` folder is for the converted files from .go.erb files. Sorry for the confusion.

2024-07-03 23:47 UTC, zli82016 commented on mmv1/third_party/terraform/acctest/go/resource_test_utils.go
> +package acctest
This file can be removed.

2024-07-10 20:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1062 files changed, 1771 insertions(+), 1759 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1227 files changed, 2002 insertions(+), 1990 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-10 21:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 3802
Passed tests: 3425
Skipped tests: 371
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComposer1Environment_withNodeConfig</li>
<li>TestAccComposerEnvironment_privateWithWebServerControl</li>
<li>TestAccComputeDisk_storagePoolSpecified</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-10 22:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1066 files changed, 1776 insertions(+), 1764 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1231 files changed, 2007 insertions(+), 1995 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-10 22:28 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComputeDisk_storagePoolSpecified`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccComputeDisk_storagePoolSpecified.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e35eeb4b-c4fb-4e59-bbc4-1ad44ff0a131/recording) for each test

2024-07-10 22:32 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_privateWithWebServerControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]
`TestAccComputeDisk_storagePoolSpecified`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccComputeDisk_storagePoolSpecified.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/414ce474-058a-4b4f-b576-42d6b88bb4ce/recording) for each test

2024-07-10 23:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 3849
Passed tests: 3463
Skipped tests: 381
Affected tests: 5

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComposer1Environment_withNodeConfig</li>
<li>TestAccComposerEnvironment_privateWithWebServerControl</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-11 00:05 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironment_privateWithWebServerControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording/TestAccComposerEnvironment_privateWithWebServerControl.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/272af3bd-bd50-4b29-a411-142c07d597b9/recording) for each test

2024-07-11 17:31 UTC, zli82016 commented
Do you mind resolving the conflicts, @trodge ? The changes LGTM.

2024-07-11 19:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1068 files changed, 1780 insertions(+), 1768 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1233 files changed, 2011 insertions(+), 1999 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-11 21:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 3853
Passed tests: 3469
Skipped tests: 381
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-11 21:25 UTC, zli82016 commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1068 files changed, 1780 insertions(+), 1768 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1233 files changed, 2011 insertions(+), 1999 deletions(-))
> 
> ## Errors
> `google` provider:
> 
> * The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
> * The diff processor crashed while computing changed resource schemas.
> 
> `google-beta` provider:
> 
> * The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
> * The missing test detector failed to run.
> * The diff processor crashed while computing changed resource schemas.

@trodge ，do you have an idea what caused the error?

2024-07-11 21:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/fa6f8606-b4d9-47ba-8918-1266ed590f47/recording) for each test

2024-07-11 22:59 UTC, trodge commented
> > Hi there, I'm the Modular magician. I've detected the following information about your changes:
> > ## Diff report
> > Your PR generated some diffs in downstreams - here they are.
> > `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1068 files changed, 1780 insertions(+), 1768 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1233 files changed, 2011 insertions(+), 1999 deletions(-))
> > ## Errors
> > `google` provider:
> > 
> > * The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
> > * The diff processor crashed while computing changed resource schemas.
> > 
> > `google-beta` provider:
> > 
> > * The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
> > * The missing test detector failed to run.
> > * The diff processor crashed while computing changed resource schemas.
> 
> @trodge ，do you have an idea what caused the error?

It's caused by importing `terraform-plugin-sdk/v2/helper/resource` alongside `terraform-plugin-testing/helper/resource`.

These are the only files that still import `terraform-plugin-testing/v2/helper/resource`:

```
mmv1/third_party/terraform/services/netapp/go/resource_netapp_storage_pool_test.go.tmpl
mmv1/third_party/terraform/acctest/go/framework_test_utils.go
```

Based on this, I think I need to keep the changes I reverted in the most recent commit.

2024-07-11 23:11 UTC, zli82016 commented
> Edit- after considering the logs further I've realized that the reason this happens is that the diff processor is building the old version of the provider which still uses `terraform-plugin-sdk` alongside the new version using `terraform-plugin-testing`.

Will it also cause error after merging this PR in the main branch?
I am so familiar with the diff processor. Added @roaks3 as a secondary reviewer.

2024-07-11 23:30 UTC, trodge commented
> > Edit- after considering the logs further I've realized that the reason this happens is that the diff processor is building the old version of the provider which still uses `terraform-plugin-sdk` alongside the new version using `terraform-plugin-testing`.
> 
> Will it also cause error after merging this PR to the main branch? I am so familiar with the diff processor. Added @roaks3 as a secondary reviewer.

It shouldn't cause any errors after it's merged, since the old version using `terraform-plugin-sdk` will be gone.

2024-07-12 16:07 UTC, zli82016 commented
> > > Edit- after considering the logs further I've realized that the reason this happens is that the diff processor is building the old version of the provider which still uses `terraform-plugin-sdk` alongside the new version using `terraform-plugin-testing`.
> > 
> > 
> > Will it also cause error after merging this PR to the main branch? I am so familiar with the diff processor. Added @roaks3 as a secondary reviewer.
> 
> It shouldn't cause any errors after it's merged, since the old version using `terraform-plugin-sdk` will be gone.

That makes sense. Thanks.

2024-07-12 16:09 UTC, zli82016 commented
LGTM. Waiting for confirmation from @roaks3

2024-07-12 17:28 UTC, roaks3 approved these changes
Yea, the logic makes sense to me regarding the diff processor failure. It would be nice if we could verify before merging, but I don't think it would be feasible for a case like this, so we should just be ready to revert if needed (and also not merge late on a Friday).

2024-07-12 17:37 UTC, zli82016 approved these changes
LGTM

2024-07-15 20:57 UTC, trodge commented
/gcbrun

2024-07-15 21:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1069 files changed, 1782 insertions(+), 1770 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1234 files changed, 2013 insertions(+), 2001 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-15 22:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 3840
Passed tests: 3454
Skipped tests: 383
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-15 22:29 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/ad9ed66a-ee84-45f0-9013-0a07964be3f1/recording) for each test

2024-07-15 22:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1070 files changed, 1783 insertions(+), 1771 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1235 files changed, 2014 insertions(+), 2002 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-15 23:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 3857
Passed tests: 3471
Skipped tests: 383
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-15 23:53 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/bc14c9d0-7035-46a7-a3a4-e26327895cdc/recording) for each test

2024-07-16 20:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1070 files changed, 1783 insertions(+), 1771 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1235 files changed, 2014 insertions(+), 2002 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-16 21:50 UTC, modular-magician commented
#### Tests analytics
Total tests: 3858
Passed tests: 3472
Skipped tests: 383
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-16 22:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/e357563f-f1de-4cf3-91d4-6f7074ca26d2/recording) for each test

2024-07-17 16:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1071 files changed, 1785 insertions(+), 1773 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1236 files changed, 2016 insertions(+), 2004 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-17 17:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 3857
Passed tests: 3453
Skipped tests: 384
Affected tests: 20

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 20 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvironmentIamPolicyGenerated</li>
<li>TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesBetaTestExample</li>
<li>TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample</li>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccAppEngineStandardAppVersion_update</li>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccDataSourceVmwareEngineNetwork_basic</li>
<li>TestAccDataSourceVmwareengineNetworkPeering_basic</li>
<li>TestAccDataSourceVmwareengineNetworkPolicy_basic</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated_withCondition</li>
<li>TestAccIapTunnelIamPolicyGenerated</li>
<li>TestAccIapWebIamPolicyGenerated</li>
<li>TestAccIapWebTypeAppEngineIamPolicyGenerated</li>
<li>TestAccIapWebTypeComputeIamPolicyGenerated</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-17 18:38 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccApigeeEnvironmentIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccApigeeEnvironmentIamPolicyGenerated.log)]
`TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesBetaTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesBetaTestExample.log)]
`TestAccDataSourceVmwareEngineNetwork_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccDataSourceVmwareEngineNetwork_basic.log)]
`TestAccDataSourceVmwareengineNetworkPeering_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccDataSourceVmwareengineNetworkPeering_basic.log)]
`TestAccDataSourceVmwareengineNetworkPolicy_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccDataSourceVmwareengineNetworkPolicy_basic.log)]
`TestAccIapTunnelIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapTunnelIamPolicyGenerated.log)]
`TestAccIapWebIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapWebIamPolicyGenerated.log)]
`TestAccIapWebTypeAppEngineIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapWebTypeAppEngineIamPolicyGenerated.log)]
`TestAccIapWebTypeComputeIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapWebTypeComputeIamPolicyGenerated.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample.log)]
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamBindingGenerated.log)]
`TestAccIapAppEngineServiceIamBindingGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamBindingGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamMemberGenerated.log)]
`TestAccIapAppEngineServiceIamMemberGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamMemberGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/6ef079a5-d955-4446-b6fa-b90e0854b05e/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://stor [...]

2024-07-17 20:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1072 files changed, 1786 insertions(+), 1774 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1238 files changed, 2019 insertions(+), 2007 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-17 21:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 3864
Passed tests: 3468
Skipped tests: 384
Affected tests: 12

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample</li>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccAppEngineStandardAppVersion_update</li>
<li>TestAccComputeInterconnectAttachment_interconnectAttachmentDedicatedExample</li>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated_withCondition</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-17 21:31 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInterconnectAttachment_interconnectAttachmentDedicatedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccComputeInterconnectAttachment_interconnectAttachmentDedicatedExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample.log)]
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamBindingGenerated.log)]
`TestAccIapAppEngineServiceIamBindingGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamBindingGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamMemberGenerated.log)]
`TestAccIapAppEngineServiceIamMemberGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamMemberGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/4388c60f-fb7e-4a82-b1b7-91a80e9afcf0/recording) for each test

2024-07-18 20:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10339-old..auto-pr-10339) ( 1072 files changed, 1786 insertions(+), 1774 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10339-old..auto-pr-10339) ( 1238 files changed, 2019 insertions(+), 2007 deletions(-))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-07-18 21:14 UTC, modular-magician commented
#### Tests analytics
Total tests: 3864
Passed tests: 3469
Skipped tests: 384
Affected tests: 11

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 11 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample</li>
<li>TestAccAppEngineFlexibleAppVersion_update</li>
<li>TestAccAppEngineStandardAppVersion_update</li>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated</li>
<li>TestAccIapAppEngineServiceIamBindingGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated</li>
<li>TestAccIapAppEngineServiceIamMemberGenerated_withCondition</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated</li>
<li>TestAccIapAppEngineServiceIamPolicyGenerated_withCondition</li>
<li>TestAccNetworkServicesLbRouteExtension_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-18 21:33 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccAppEngineFlexibleAppVersion_appEngineFlexibleAppVersionExample.log)]
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccAppEngineFlexibleAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]
`TestAccIapAppEngineServiceIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamBindingGenerated.log)]
`TestAccIapAppEngineServiceIamBindingGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamBindingGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamBindingGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamMemberGenerated.log)]
`TestAccIapAppEngineServiceIamMemberGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamMemberGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamMemberGenerated_withCondition.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamPolicyGenerated.log)]
`TestAccIapAppEngineServiceIamPolicyGenerated_withCondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccIapAppEngineServiceIamPolicyGenerated_withCondition.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_build/TestAccNetworkServicesLbRouteExtension_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording/TestAccNetworkServicesLbRouteExtension_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10339/artifacts/534d5465-b4a5-4a6a-ae78-db1dc26d3cff/recording) for each test

2024-07-18 21:58 UTC, merged