[Composer] Reveal Image Version Updates to GA.
GoogleCloudPlatform/magic-modules pull request #10454
Opened 2024-04-15 20:05 UTC by Khaledmohamedrefaat

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancment
composer: promoted `config.0.software_config.0.image_version` updates to GA in resource `google_composer_environment`
```

Fixes [17857](https://github.com/hashicorp/terraform-provider-google/issues/17857)

2024-04-15 20:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 120 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 105 insertions(+))

2024-04-15 20:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `43`
Passed tests: `42`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>composer</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposerEnvironment_UpdateComposerV2ImageVersion </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-15 20:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 120 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 105 insertions(+))

2024-04-15 20:28 UTC, modular-magician commented
#### Tests analytics
Total tests: `43`
Passed tests: `42`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>composer</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposerEnvironment_UpdateComposerV2ImageVersion </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-15 20:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `43`
Passed tests: `42`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>composer</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposerEnvironment_UpdateComposerV2ImageVersion </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-15 21:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironment_UpdateComposerV2ImageVersion`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/d2ee7828-c989-4452-aca2-ffe4ee18d718/recording/TestAccComposerEnvironment_UpdateComposerV2ImageVersion.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/d2ee7828-c989-4452-aca2-ffe4ee18d718/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/d2ee7828-c989-4452-aca2-ffe4ee18d718/recording) for each test

2024-04-15 21:08 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironment_UpdateComposerV2ImageVersion`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/9f4d6a21-fe2d-41bb-b760-a27b34324ee1/recording/TestAccComposerEnvironment_UpdateComposerV2ImageVersion.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/9f4d6a21-fe2d-41bb-b760-a27b34324ee1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/9f4d6a21-fe2d-41bb-b760-a27b34324ee1/recording) for each test

2024-04-15 21:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComposerEnvironment_UpdateComposerV2ImageVersion`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/f153c6b1-b667-432c-932b-80fa30f8f29f/recording/TestAccComposerEnvironment_UpdateComposerV2ImageVersion.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/f153c6b1-b667-432c-932b-80fa30f8f29f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/f153c6b1-b667-432c-932b-80fa30f8f29f/recording) for each test

2024-04-16 10:12 UTC, SarahFrench reviewed
Hi, thanks for your PR! This looks good to me, but I had a couple of comments.

The acceptance test currently doesn't assert that the resource is being updated instead of recreated, but unfortunately this is a problem that affects _all_ acceptance tests. I figured that because this PR is explicitly changing the behaviour from 'recreate' to 'update' it'd be good to identify any way the test could assert that behaviour change. But if there's not an obvious way to do that I'm happy to approve & merge

2024-04-17 09:22 UTC, Khaledmohamedrefaat commented on mmv1/third_party/terraform/services/composer/resource_composer_environment.go.erb
> +										ForceNew:         false,
Done.

2024-04-17 09:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 119 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10454-old..auto-pr-10454) ( 1 file changed, 104 insertions(+))

2024-04-17 09:39 UTC, modular-magician commented
#### Tests analytics
Total tests: `43`
Passed tests: `43`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>composer</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/3177a662-1102-4faa-bdaf-74d1a602cbe5/build-log/replaying_test.log)

2024-04-22 16:40 UTC, rileykarson commented
@shuyama1: Adding you as a replacement reviewer

2024-04-23 18:02 UTC, shuyama1 requested changes
The newly added

2024-04-23 18:02 UTC, shuyama1 commented on mmv1/third_party/terraform/services/composer/resource_composer_environment_test.go.erb
> +}
only nit - we use tabs instead of spaces for spacing here.

2024-04-24 08:57 UTC, Khaledmohamedrefaat commented
@shuyama1 Resolved requested changes, PTAL. Thanks!

2024-04-24 09:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 123 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10454-old..auto-pr-10454) ( 2 files changed, 106 insertions(+), 2 deletions(-))

2024-04-24 09:10 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `46`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>composer</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10454/artifacts/bf60574b-d876-404c-827d-afd6f51f05af/build-log/replaying_test.log)

2024-04-24 16:14 UTC, rileykarson commented
Note: We should address https://github.com/GoogleCloudPlatform/magic-modules/pull/10454#discussion_r1567096803 as well, from prior to the reviewer change

2024-04-25 09:11 UTC, Khaledmohamedrefaat commented
As mentioned in the other comment:

I've opened an internal ticket to keep the work track of adding validation of a creation timestamp to all of our Update test.but IMHO that will be a refactor change for **all** of our tests so it should be in different context than this PR.

2024-04-29 20:20 UTC, shuyama1 approved these changes
Checked the debug log of the tests running on TC and can confirm that the field is updated in-place instead being recreated.

2024-04-29 20:21 UTC, merged