Add autoscaling to DPMS terraform
GoogleCloudPlatform/magic-modules pull request #10522
Opened 2024-04-24 18:04 UTC by brandon-m-hansen

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-04-25 21:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 182 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 182 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_metastore_service` (22 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_metastore_service" "primary" {
  scaling_config {
    autoscaling_config {
      autoscaling_enabled = # value needed
      limit_config {
        max_scaling_factor = # value needed
        min_scaling_factor = # value needed
      }
    }
  }
}

```

2024-04-25 21:55 UTC, modular-magician commented
#### Tests analytics
Total tests: `16`
Passed tests: `14`
Skipped tests: `2`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/749417ec-b51b-48f6-b98a-bdbc4313f514/build-log/replaying_test.log)

2024-04-29 21:11 UTC, NickElliot requested changes

2024-05-01 20:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 28 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 181 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_metastore_service` (22 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_metastore_service" "primary" {
  scaling_config {
    autoscaling_config {
      autoscaling_enabled = # value needed
      limit_config {
        max_scaling_factor = # value needed
        min_scaling_factor = # value needed
      }
    }
  }
}

```

2024-05-01 20:15 UTC, modular-magician commented
#### Tests analytics
Total tests: `16`
Passed tests: `14`
Skipped tests: `2`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/99e2aa51-9740-4f5d-990a-cbc15f938aba/build-log/replaying_test.log)

2024-05-03 16:53 UTC, NickElliot requested changes
The examples need to be added to the block further up in the file, see [here](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-a-create-test) bullet #5

2024-05-03 16:53 UTC, NickElliot commented on mmv1/templates/terraform/examples/go/dataproc_metastore_service_autoscaling_min_scaling_factor.tf.tmpl
> +}
```suggestion
}

```

2024-05-03 16:53 UTC, NickElliot commented on mmv1/templates/terraform/examples/go/dataproc_metastore_service_autoscaling_no_limit_config.tf.tmpl
> +}
```suggestion
}

```

2024-05-03 16:53 UTC, NickElliot commented on mmv1/templates/terraform/examples/go/dataproc_metastore_service_autoscaling_min_and_max_scaling_factor.tf.tmpl
> +}
```suggestion
}

```

2024-05-03 16:53 UTC, NickElliot commented on mmv1/templates/terraform/examples/go/dataproc_metastore_service_autoscaling_max_scaling_factor.tf.tmpl
> +}
```suggestion
}

```

2024-05-08 22:19 UTC, NickElliot requested changes
Still need the examples added up [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/f0fb0ef6b220472123184a75787f151322bcca14/mmv1/products/metastore/Service.yaml#L58)! Thanks

2024-05-23 16:20 UTC, NickElliot requested changes
Could you add duplicates of the examples under the `mmv1/templates/terraform/examples` folder with the other .tf.erb files? The go folder is currently for some internal work and isnt used by all downstreams, so its causing an error when the tests you added "don't exist". Thanks!

2024-05-23 16:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 352 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 3 files changed, 505 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10522-old..auto-pr-10522) ( 16 files changed, 486 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_metastore_service` (22 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_metastore_service" "primary" {
  scaling_config {
    autoscaling_config {
      autoscaling_enabled = # value needed
      limit_config {
        max_scaling_factor = # value needed
        min_scaling_factor = # value needed
      }
    }
  }
}

```

2024-05-23 17:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `14`
Skipped tests: `2`
Affected tests: `4`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-23 17:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/dc91129f-774e-4d52-b86b-6b3dac131583/recording) for each test

2024-05-23 17:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 352 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 3 files changed, 505 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10522-old..auto-pr-10522) ( 16 files changed, 486 insertions(+))

2024-05-23 18:03 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `14`
Skipped tests: `2`
Affected tests: `4`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-23 18:16 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMaxScalingFactorExample.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinAndMaxScalingFactorExample.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingMinScalingFactorExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/898dd3f3-3baf-4bc5-8021-bed516d2d673/recording) for each test

2024-05-23 23:15 UTC, NickElliot requested changes

2024-05-23 23:15 UTC, NickElliot commented on mmv1/products/metastore/Service.yaml
> +            name: 'limitConfig'
Can you add a default_from_api to this nested object too?

2024-06-06 21:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 352 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 3 files changed, 506 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10522-old..auto-pr-10522) ( 16 files changed, 486 insertions(+))

2024-06-06 22:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `17`
Skipped tests: `2`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-06 22:12 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/feb2fa71-2c03-4eea-a268-d8eb6fe699ff/build-log/recording_build/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/feb2fa71-2c03-4eea-a268-d8eb6fe699ff/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/feb2fa71-2c03-4eea-a268-d8eb6fe699ff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/feb2fa71-2c03-4eea-a268-d8eb6fe699ff/recording) for each test

2024-06-11 15:50 UTC, brandon-m-hansen commented
@NickElliot the test failed due to an internal DPMS error, it seems to be caused by the network quota being exceeded in the metastore terraform test project, so it should be unrelated to the new terraform fields

2024-06-12 20:12 UTC, NickElliot commented
/gcbrun

2024-06-12 20:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10522-old..auto-pr-10522) ( 2 files changed, 352 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10522-old..auto-pr-10522) ( 3 files changed, 506 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10522-old..auto-pr-10522) ( 1 file changed, 71 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10522-old..auto-pr-10522) ( 16 files changed, 486 insertions(+))

2024-06-12 20:25 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `17`
Skipped tests: `2`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>dataprocmetastore</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-12 20:38 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/ad59910d-9bd2-4619-9857-6c88ec757438/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceAutoscalingNoLimitConfigExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/ad59910d-9bd2-4619-9857-6c88ec757438/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10522/artifacts/ad59910d-9bd2-4619-9857-6c88ec757438/recording) for each test

2024-06-12 21:34 UTC, NickElliot approved these changes
LGTM then!

2024-06-12 21:34 UTC, merged