add compute healthcheck tests
GoogleCloudPlatform/magic-modules pull request #10538
Opened 2024-04-26 13:41 UTC by kotarsky

adding new tests for compute.googleapis.com/HealthCheck

```release-note:none
compute: added testes field to `compute.googleapis.com/HealthCheck` resource
```

2024-04-26 15:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10538-old..auto-pr-10538) ( 4 files changed, 54 insertions(+))

2024-04-29 23:21 UTC, rileykarson requested changes
See feedback in https://github.com/GoogleCloudPlatform/magic-modules/pull/10540#pullrequestreview-2029564250, can we address that before moving forward with other PRs? Thanks!

2024-05-09 20:13 UTC, sushant00 commented
Let us update the title according to the recommended format like "Add support for google_compute_autoscaler to TGC"

2024-05-16 13:17 UTC, kotarsky commented
> Let us update the title according to the recommended format like "Add support for google_compute_autoscaler to TGC"

@rileykarson changes to title made

2024-05-16 16:48 UTC, rileykarson commented on mmv1/templates/tgc/resource_converters.go.erb
> +		"google_compute_health_check":           {compute.ResourceConverterComputeHealthCheck()},
nit: try to align these in future entries! We run `gofmt` on the output files, but the source should be as close as possible as well.

2024-05-16 16:48 UTC, merged