Add Asset Type run.googleapis.com/Job - b/336823687
GoogleCloudPlatform/magic-modules pull request #10548
Opened 2024-04-29 13:25 UTC by dvfons

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-04-29 22:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10548-old..auto-pr-10548) ( 11 files changed, 56 insertions(+), 2466 deletions(-))

2024-04-29 22:53 UTC, trodge approved these changes

2024-04-29 22:54 UTC, trodge requested changes
There seems to be an error in the TGC build. Is that related to this change?

2024-05-01 12:44 UTC, dvfons commented
> There seems to be an error in the TGC build. Is that related to this change?

i don't know let me check it

2024-05-01 20:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10548-old..auto-pr-10548) ( 11 files changed, 51 insertions(+), 2466 deletions(-))

2024-05-06 10:45 UTC, closed without merging