adding new tests for compute.googleapis.com/UrlMap
GoogleCloudPlatform/magic-modules pull request #10540
Opened 2024-04-26 17:14 UTC by kotarsky

adding new tests for compute.googleapis.com/UrlMap

```release-note:none
artifactregistry: added testes field to `compute.googleapis.com/UrlMap` resource
```

2024-04-29 20:27 UTC, rileykarson requested changes
There's a mismatch between the release note and PR title and the change you've made. Do you have a bug or issue you can link for context?

2024-04-30 11:15 UTC, kotarsky commented
> There's a mismatch between the release note and PR title and the change you've made. Do you have a bug or issue you can link for context?

You're right, just edited the release note and fixed it.
Actually, I'm just working on some tests related to some assets. You can expect more PRs from me in the next few days.
Thanks for the review!

2024-05-07 20:52 UTC, rileykarson requested changes
For this & other related PRs the title should cover the actual end result of the change- we're adding new resources to terraform-google-conversion, not adding new tests for that.

I'd ask that we title these as "Add support for {{resource}} to TGC" i.e. "Add support for google_compute_url_map to TGC".

Your changelog is typed none, which is correct, as this has no impact on provider users. We should blank them out as well, for clarity.

Running build to ensure we're running the new tests correctly.

2024-05-07 20:52 UTC, rileykarson requested changes
For this & other related PRs the title should cover the actual end result of the change- we're adding new resources to terraform-google-conversion, not adding new tests for that.

I'd ask that we title these as "Add support for {{resource}} to TGC" i.e. "Add support for google_compute_url_map to TGC".

Your changelog is typed none, which is correct, as this has no impact on provider users. We should blank them out as well, for clarity.

Running build to ensure we're running the new tests correctly.

2024-05-07 20:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10540-old..auto-pr-10540) ( 4 files changed, 75 insertions(+))

2024-05-14 01:47 UTC, dvfons commented
/gcbrun

2024-05-14 16:07 UTC, rileykarson commented
@dvfons: I'm seeing a CLA issue on your new commit, can you resolve that? Thanks! I've followed up with a link internally.

2024-05-14 16:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10540-old..auto-pr-10540) ( 4 files changed, 75 insertions(+))

2024-05-16 18:16 UTC, kotarsky commented
all tests fixed

2024-05-16 21:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10540-old..auto-pr-10540) ( 5 files changed, 78 insertions(+))

2024-05-21 11:01 UTC, kotarsky commented
@rileykarson Can you review it again?

2024-05-22 11:50 UTC, sushant00 approved these changes

2024-05-22 11:50 UTC, sushant00 commented on mmv1/third_party/tgc/tests/data/example_compute_url_map.json
> +            "discovery_document_uri": "https://www.googleapis.com/discovery/v1/apis/compute/beta/rest",
Can you check if you can update the autogenerated code to return "v1/rest" as the suffix instead of "beta/rest"

2024-05-22 13:01 UTC, sushant00 commented on mmv1/third_party/tgc/tests/data/example_compute_url_map.json
> +            "discovery_document_uri": "https://www.googleapis.com/discovery/v1/apis/compute/beta/rest",
Please ignore this for now, as discussed offline. We can figure out later how to resolve this specific issue.

2024-05-22 16:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10540-old..auto-pr-10540) ( 5 files changed, 78 insertions(+))

2024-05-29 20:32 UTC, merged