add gkehub feature tests
GoogleCloudPlatform/magic-modules pull request #10552
Opened 2024-04-29 16:49 UTC by kotarsky

adding new tests for gkehub.googleapis.com/Feature

```release-note:none
gkehub: added tests field to `gkehub.googleapis.com/Feature` resource
```

2024-04-29 23:21 UTC, rileykarson requested changes
See feedback in https://github.com/GoogleCloudPlatform/magic-modules/pull/10540#pullrequestreview-2029564250, can we address that before moving forward with other PRs? Thanks!

2024-05-16 16:50 UTC, rileykarson submitted a review, later dismissed

2024-05-16 16:50 UTC, rileykarson reviewed
Ah- still need to generate+test

2024-05-16 16:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10552-old..auto-pr-10552) ( 4 files changed, 41 insertions(+))

2024-05-20 11:28 UTC, kotarsky commented
@rileykarson Can you review it again?

2024-05-22 16:47 UTC, rileykarson approved these changes

2024-05-22 16:47 UTC, merged