bigqueryanalyticshub - add support for sharing settings to data exchange
GoogleCloudPlatform/magic-modules pull request #10570
Opened 2024-05-01 01:48 UTC by DrFaust92

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigqueryanalyticshub - add support for sharing_environment_config to google_bigquery_analytics_hub_data_exchange
```

2024-05-01 16:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10570-old..auto-pr-10570) ( 3 files changed, 277 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10570-old..auto-pr-10570) ( 3 files changed, 277 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10570-old..auto-pr-10570) ( 1 file changed, 67 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10570-old..auto-pr-10570) ( 8 files changed, 222 insertions(+))

2024-05-01 16:42 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `12`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>bigqueryanalyticshub</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigqueryAnalyticsHubDataExchangeIamBindingGenerated|TestAccBigqueryAnalyticsHubDataExchangeIamMemberGenerated|TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated|TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeBasicExample|TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingDcrExample|TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingExample|TestAccBigqueryAnalyticsHubListingIamBindingGenerated|TestAccBigqueryAnalyticsHubListingIamMemberGenerated|TestAccBigqueryAnalyticsHubListingIamPolicyGenerated|TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingBasicExample|TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingRestrictedExample|TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-01 16:43 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccBigqueryAnalyticsHubDataExchangeIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchangeIamBindingGenerated.log)]
`TestAccBigqueryAnalyticsHubDataExchangeIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchangeIamMemberGenerated.log)]
`TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchangeIamPolicyGenerated.log)]
`TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeBasicExample.log)]
`TestAccBigqueryAnalyticsHubListingIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListingIamBindingGenerated.log)]
`TestAccBigqueryAnalyticsHubListingIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListingIamMemberGenerated.log)]
`TestAccBigqueryAnalyticsHubListingIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListingIamPolicyGenerated.log)]
`TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingBasicExample.log)]
`TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingRestrictedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingRestrictedExample.log)]
`TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubListing_bigqueryAnalyticshubListingUpdate.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingDcrExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/build-log/recording_build/TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingDcrExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingDcrExample.log)]
`TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/build-log/recording_build/TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording/TestAccBigqueryAnalyticsHubDataExchange_bigqueryAnalyticshubDataExchangeSharingExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10570/artifacts/671d20d9-0b76-4d6e-95c1-40edb403fe12/recording) for each test

2024-05-01 18:51 UTC, zli82016 requested changes

2024-05-10 10:22 UTC, DrFaust92 commented
[zli82016](https://github.com/zli82016) Ill check comments, tests initially on the beta api and its a bit different.

2024-06-12 09:41 UTC, closed without merging