Add support for Managed zone resource of Integration Connectors.
GoogleCloudPlatform/magic-modules pull request #10580
Opened 2024-05-02 09:39 UTC by balanaguharsha

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
Adding support for managed zone resource of Integration connectors
```

2024-05-02 20:24 UTC, trodge commented
/gcbrun

2024-05-02 20:26 UTC, trodge commented on mmv1/products/integrationconnectors/ManagedZone.yaml
> +    name: "integration_connectors_connection_basic"
Should this be `integration_connectors_managed_zone`?

2024-05-03 05:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1072 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1072 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10580-old..auto-pr-10580) ( 4 files changed, 114 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 05:19 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 05:20 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8480790b-6763-420d-9c31-4ffd6bedde95/recording) for each test

2024-05-03 05:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1098 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1098 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 06:03 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 06:05 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/970eaec4-324a-4f56-b04f-6fcaf9cebbe2/recording) for each test

2024-05-03 06:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1136 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1136 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 07:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 07:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/8b51059f-7a52-44c5-a235-9d675aa6cc4f/recording) for each test

2024-05-03 07:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1205 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1205 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))


## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-03 07:11 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/888503a0-12a2-4623-a55f-96e7b249e3c5/build-log/replaying_test.log)

2024-05-03 09:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1205 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1205 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 09:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 09:35 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/29c0f2a4-da56-45f4-8ad7-f532188622e5/recording) for each test

2024-05-03 10:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1253 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1253 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 10:23 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/133bb707-c4b4-4b45-9f1b-28d23fb2fe03/recording) for each test

2024-05-03 10:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1209 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1209 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 10:56 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 10:57 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/7602e1c6-e9a9-4a00-a223-d3256d3327f0/recording) for each test

2024-05-03 11:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 11:45 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 11:50 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/419e27b6-a18b-4d52-b38b-beb9f2343435/recording) for each test

2024-05-03 12:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 12:54 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 13:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 13:12 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample|TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 13:17 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/build-log/replaying_build_after_recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/replaying_after_recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/2a1220ce-7736-4c3f-8c9c-38f822c5f4a4/recording) for each test

2024-05-03 13:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 13:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1249 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 14:01 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `11`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 14:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 14:04 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `11`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 14:05 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/1f33a874-ca94-4747-9725-c27250cbaf31/build-log/recording_build/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/1f33a874-ca94-4747-9725-c27250cbaf31/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/1f33a874-ca94-4747-9725-c27250cbaf31/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/1f33a874-ca94-4747-9725-c27250cbaf31/recording) for each test

2024-05-03 14:10 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `1`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-03 14:10 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/0c1fe282-bf8d-4bd7-9981-b51989684488/recording/TestAccIntegrationConnectorsManagedZone_integrationConnectorsManagedZoneExample_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/0c1fe282-bf8d-4bd7-9981-b51989684488/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/0c1fe282-bf8d-4bd7-9981-b51989684488/recording) for each test

2024-05-03 18:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1251 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1251 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_integration_connectors_managed_zone` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_integration_connectors_managed_zone" "primary" {
  project = # value needed
}

```

2024-05-03 18:05 UTC, balanaguharsha commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))
> 
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_integration_connectors_managed_zone` (3 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```terraform
> resource "google_integration_connectors_managed_zone" "primary" {
>   project = # value needed
> }
> ```

I am not sure how to solve this, please suggest, shouldn't project be from the context anyways, the resource doesn't have a field called project explicitly defined in the resource's yaml

2024-05-03 18:05 UTC, balanaguharsha commented
PTAL at convenience.

2024-05-03 18:07 UTC, modular-magician commented
#### Tests analytics
Total tests: `12`
Passed tests: `10`
Skipped tests: `2`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>integrationconnectors</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10580/artifacts/afcb4f8a-f79c-43cb-9d6e-774c8ee28642/build-log/replaying_test.log)

2024-05-03 20:17 UTC, trodge commented
> > Hi there, I'm the Modular magician. I've detected the following information about your changes:
> > ## Diff report
> > Your PR generated some diffs in downstreams - here they are.
> > `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10580-old..auto-pr-10580) ( 6 files changed, 1250 insertions(+), 2 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10580-old..auto-pr-10580) ( 1 file changed, 116 insertions(+))
> > ## Missing test report
> > Your PR includes resource fields which are not covered by any test.
> > Resource: `google_integration_connectors_managed_zone` (3 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> > ```terraform
> > resource "google_integration_connectors_managed_zone" "primary" {
> >   project = # value needed
> > }
> > ```
> 
> I am not sure how to solve this, please suggest, shouldn't project be from the context anyways, the resource doesn't have a field called project explicitly defined in the resource's yaml

This can be ignored.

2024-05-03 20:18 UTC, trodge commented on mmv1/products/integrationconnectors/ManagedZone.yaml
> +  - !ruby/object:Api::Type::Time
We usually omit create time and update time fields from new resources. Is there a reason to include them here?

2024-05-03 20:19 UTC, trodge requested changes
LGTM, just one nit.

2024-05-04 04:10 UTC, balanaguharsha commented
Have resolved your other comment.

2024-05-06 16:34 UTC, balanaguharsha commented
PTAL

2024-05-07 04:14 UTC, trodge approved these changes

2024-05-07 04:14 UTC, merged