Add Tests for Resoure Rotuer
GoogleCloudPlatform/magic-modules pull request #10585
Opened 2024-05-02 18:49 UTC by delimaneto

adding new tests for compute.googleapis.com/Router
```release-note:enhancement
router: added tests field to `compute.googleapis.com/Router` resource
```

2024-05-02 23:01 UTC, melinath reviewed
on hold pending discussions with service team

2024-05-09 20:33 UTC, sushant00 commented
@melinath can you please review this change now since internal discussion is closed.

2024-05-09 21:29 UTC, melinath commented
yes, thanks for flagging!

2024-05-09 21:30 UTC, melinath requested changes
@delimaneto please resolve the merge conflicts

2024-05-13 20:46 UTC, melinath requested changes
please resolve merge conflicts

2024-05-14 11:25 UTC, delimaneto commented
conflicts fixed

2024-05-15 22:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10585-old..auto-pr-10585) ( 4 files changed, 112 insertions(+), 1 deletion(-))

2024-05-16 17:33 UTC, melinath requested changes
LGTM apart from one stray change.

2024-05-16 18:21 UTC, delimaneto commented on mmv1/templates/tgc/resource_converters.go.erb
> +		"google_compute_node_template": 				           {compute.ResourceConverterComputeNodeTemplate()},
I  did the undo and aligned all the resources that was with tab space

2024-05-16 18:24 UTC, melinath approved these changes
okay - approving this with the whitespace changes

2024-05-16 18:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10585-old..auto-pr-10585) ( 4 files changed, 111 insertions(+))

2024-05-16 19:08 UTC, merged