Support ignore_read on nested fields
GoogleCloudPlatform/magic-modules pull request #10639
Opened 2024-05-08 23:35 UTC by SirGitsalot

This changes the compiler to handle generate a flattener for nested fields automatically in the form that resource authors have been writing manually, a la:

```
func flattenFooBar(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
    return d.Get("foo.0.bar")
}
```

This change also automatically adds nested `ignore_read` to `ImportStateVerifyIgnore`. This will generate a bunch of test diffs because `ImportStateVerifyIgnore` is reordered in some cases, and in others it's getting additional `ignore_read` fields (which presumably aren't necessary for the tests to pass, but the compiler doesn't know that).

It also updates `google_compute_backend_service` and `google_compute_region_backend_service` to verify that the same code is being generated with their no-longer-needed custom flatteners and `ignore_read_extra` configs.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/12410

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-05-08 23:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10639-old..auto-pr-10639) ( 48 files changed, 146 insertions(+), 139 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10639-old..auto-pr-10639) ( 57 files changed, 209 insertions(+), 199 deletions(-))

2024-05-08 23:52 UTC, rileykarson approved these changes
LGTM- Changes are test-only and I didn't see anything that looked off- but also didn't step through every delta piece-by-piece.

2024-05-08 23:52 UTC, rileykarson commented on mmv1/templates/terraform/examples/base_configs/test_file.go.erb
>      ignore_read = object.all_user_properties
nit: Could we add a sort in a separate PR and then rebase this change to include it? That'll capture the true delta from your change- it's hard to see what has/hasn't changed as-is! That'll guard against spurious diffs during other similar changes to the set in the future.

2024-05-09 00:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `1531`
Passed tests: `1410`
Skipped tests: `119`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>alloydb</li><li>apigee</li><li>looker</li><li>notebooks</li><li>spanner</li><li>healthcare</li><li>networksecurity</li><li>appengine</li><li>compute</li><li>firebaseappcheck</li><li>memcache</li><li>vpcaccess</li><li>apigateway</li><li>workbench</li><li>discoveryengine</li><li>dialogflowcx</li><li>redis</li><li>vertexai</li><li>workstations</li><li>certificatemanager</li><li>integrations</li><li>secretmanager</li><li>cloudbuildv2</li><li>firebasehosting</li><li>logging</li><li>netapp</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceVertexAIIndex_basic|TestAccVertexAIIndex_updated </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-09 00:52 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceVertexAIIndex_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/build-log/recording_build/TestAccDataSourceVertexAIIndex_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/recording/TestAccDataSourceVertexAIIndex_basic.log)]
`TestAccVertexAIIndex_updated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/build-log/recording_build/TestAccVertexAIIndex_updated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/recording/TestAccVertexAIIndex_updated.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/8e42d9cc-b4ec-4c7e-b769-9353a6d26e9f/recording) for each test

2024-05-09 18:18 UTC, rileykarson commented
/gcbrun, those seem like flakes

2024-05-09 18:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10639-old..auto-pr-10639) ( 48 files changed, 146 insertions(+), 139 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10639-old..auto-pr-10639) ( 57 files changed, 209 insertions(+), 199 deletions(-))

2024-05-09 19:37 UTC, modular-magician commented
#### Tests analytics
Total tests: `1532`
Passed tests: `1411`
Skipped tests: `119`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>healthcare</li><li>secretmanager</li><li>workstations</li><li>networksecurity</li><li>vertexai</li><li>discoveryengine</li><li>notebooks</li><li>redis</li><li>alloydb</li><li>compute</li><li>certificatemanager</li><li>firebaseappcheck</li><li>firebasehosting</li><li>integrations</li><li>vpcaccess</li><li>apigateway</li><li>apigee</li><li>dialogflowcx</li><li>memcache</li><li>appengine</li><li>cloudbuildv2</li><li>netapp</li><li>spanner</li><li>workbench</li><li>logging</li><li>looker</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceVertexAIIndex_basic|TestAccVertexAIIndex_updated </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-09 19:37 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceVertexAIIndex_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/build-log/recording_build/TestAccDataSourceVertexAIIndex_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/recording/TestAccDataSourceVertexAIIndex_basic.log)]
`TestAccVertexAIIndex_updated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/build-log/recording_build/TestAccVertexAIIndex_updated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/recording/TestAccVertexAIIndex_updated.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/e2d1d0e8-05c0-4b05-9434-eb2c7db5552e/recording) for each test

2024-05-09 19:43 UTC, rileykarson requested changes
Oh- I think that is actually a regression in the resource as it has changed!

2024-05-14 21:29 UTC, SirGitsalot commented
I merged https://github.com/GoogleCloudPlatform/magic-modules/pull/10648 so there should be fewer diffs.

The newly failing test is indeed seeing a diff; the previous flattener for `resource_vertex_ai_index`'s `metadata.0.config.0.feature_norm_type` was:

```
func flattenVertexAIIndexMetadataConfigFeatureNormType(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
    return v
}
```

And now it's:

```
func flattenVertexAIIndexMetadataConfigFeatureNormType(v interface{}, d *schema.ResourceData, config *transport_tpg.Config) interface{} {
    return d.Get("metadata.0.config.0.feature_norm_type")
}
```

The two failing tests are now getting a value where for that field that they didn't see before. I'm not sure what the correct fix is though - I could add a custom flattener to retain the previous behavior for this field (ironic for a PR whose purpose is to reduce the need for custom flatteners!).

2024-05-14 21:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10639-old..auto-pr-10639) ( 6 files changed, 39 insertions(+), 32 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10639-old..auto-pr-10639) ( 6 files changed, 54 insertions(+), 44 deletions(-))

2024-05-14 22:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `991`
Passed tests: `917`
Skipped tests: `72`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li><li>dialogflowcx</li><li>vertexai</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceVertexAIIndex_basic|TestAccVertexAIIndex_updated </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-14 22:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceVertexAIIndex_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/build-log/recording_build/TestAccDataSourceVertexAIIndex_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/recording/TestAccDataSourceVertexAIIndex_basic.log)]
`TestAccVertexAIIndex_updated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/build-log/recording_build/TestAccVertexAIIndex_updated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/recording/TestAccVertexAIIndex_updated.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/1b5d9761-473d-4f68-ba1b-126d6fb485d2/recording) for each test

2024-05-21 20:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10639-old..auto-pr-10639) ( 8 files changed, 44 insertions(+), 36 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10639-old..auto-pr-10639) ( 8 files changed, 59 insertions(+), 48 deletions(-))

2024-05-21 20:31 UTC, modular-magician commented
#### Tests analytics
Total tests: `1008`
Passed tests: `936`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li><li>dialogflowcx</li><li>vertexai</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10639/artifacts/edf3a464-0b2f-4824-8ad3-1a14f0a8f422/build-log/replaying_test.log)

2024-05-21 20:32 UTC, rileykarson approved these changes

2024-05-21 20:49 UTC, merged

2024-05-21 22:04 UTC, melinath commented
could you also update the contribution docs? https://googlecloudplatform.github.io/magic-modules/develop/field-reference/#ignore_read