Make downstream builder no-op when commit already built
GoogleCloudPlatform/magic-modules pull request #10647
Opened 2024-05-09 21:22 UTC by trodge

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-05-09 21:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-09 21:59 UTC, melinath requested changes
This is doing a bunch of things at once, which makes it feel significantly riskier. Could you split it out into a few stages:

- switch to Go for `sync` jobs
- switch to Go for `push` jobs
- (once both are using go) change behavior to no-op across the board if the commit was already handled

2024-06-06 20:16 UTC, rileykarson commented
Do we plan to move forward with this PR? @trodge can you assign yourself to https://github.com/hashicorp/terraform-provider-google/issues/12360 if so?

2024-06-11 22:45 UTC, melinath requested changes
one small thing; otherwise LGTM (though I will also want to take time to remind myself what the plan here was because it's been a while.)

2024-06-11 22:45 UTC, melinath commented on .ci/magician/cmd/generate_downstream.go
> +		os.Exit(0)
```suggestion
		return nil
```

2024-06-11 22:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-06-12 22:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-06-18 22:34 UTC, melinath commented
@shuyama1 could you take a look at this to make sure there are no issues in terms of the changes you made in https://github.com/GoogleCloudPlatform/magic-modules/pull/10939?

2024-06-18 23:30 UTC, shuyama1 commented
> @shuyama1 could you take a look at this to make sure there are no issues in terms of the changes you made in #10939?

If I read the code correctly, I'm not sure if this change will fix the issue that we'd like to resolve --  no manual cleanup of the sync branches is needed before clicking the `retry` button on the failed cloudbuild job. 

The actual failure of the build happens in the `sync` step or in `wait-for-commit` command to be clear (https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/magician/cmd/wait_for_commit.go#L50), which is the step before magician generates the actual commit and push it to the downstream. `sync-branch` command is used to push the given commit to the given sync branch, which happens after the actual push.

2024-06-20 16:35 UTC, melinath requested changes
+1 to Shuya's point - good catch! This also needs to update wait_for_commit to be a no-op.

2024-06-24 21:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-06-26 18:06 UTC, melinath commented
@trodge could you take a look at this today?

2024-06-26 18:13 UTC, trodge commented
> @trodge could you take a look at this today?

Were there more changes needed than the one I most recently pushed?

2024-06-26 18:34 UTC, melinath commented
I thought there might still be more you were planning to review since you hadn't re-requested review yet.

2024-06-26 22:40 UTC, melinath approved these changes

2024-06-27 20:59 UTC, merged