Go push jobs
GoogleCloudPlatform/magic-modules pull request #10659
Opened 2024-05-10 21:00 UTC by trodge

Merge after https://github.com/GoogleCloudPlatform/magic-modules/pull/10658

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-05-10 21:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-10 23:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-10 23:33 UTC, melinath approved these changes
LGTM apart from two small changes.

2024-05-10 23:33 UTC, melinath commented on .ci/magician/cmd/sync_branch.go
> +			os.Exit(1)
This should return an error instead of exiting

2024-05-10 23:33 UTC, melinath commented on .ci/magician/cmd/sync_branch.go
> +	}
Could you leave this out for now, so that the change that alters the behavior is clearer?

```suggestion
```

2024-05-15 21:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-15 21:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-15 21:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-16 21:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-17 15:04 UTC, melinath requested changes

2024-05-17 19:33 UTC, trodge commented on .ci/gcb-push-downstream.yml
> +    - name: 'gcr.io/graphite-docker-images/build-environment'
`go-plus` should be fine here.

2024-05-17 19:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-20 22:59 UTC, melinath approved these changes

2024-05-20 22:59 UTC, melinath commented on .ci/magician/cmd/sync_branch.go
> +* Copyright 2023 Google LLC. All Rights Reserved.
```suggestion
* Copyright 2024 Google LLC. All Rights Reserved.
```

2024-05-21 20:10 UTC, melinath approved these changes

2024-05-21 20:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-30 17:54 UTC, merged