Support behavioral changes to instance, instance template's max_run_duration feature on Beta
GoogleCloudPlatform/magic-modules pull request #10683
Opened 2024-05-13 17:52 UTC by arungantasala

Max run duration(MRD) feature support in terraform was added in https://github.com/GoogleCloudPlatform/magic-modules/pull/6812. There are behavioral changes in the feature which needs further changes.

1) max_run_duration is not a one time intent
2) Add STOP instance termination action with MRD
3) Support MRD on instances with attached local SSDs.

See SchedulingOnInstanceStopAction section in https://pkg.go.dev/google.golang.org/api/compute/v0.beta.

Fix for https://github.com/hashicorp/terraform-provider-google/issues/13005

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `on_instance_stop_action` field to `google_compute_instance` and `google_compute_instance_template` resource (beta)
```

2024-05-13 18:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 4 files changed, 136 insertions(+), 24 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 6 files changed, 412 insertions(+), 41 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 39 insertions(+), 3 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (267 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    instance_termination_action = # value needed
    maintenance_interval        = # value needed
    min_node_cpus               = # value needed
    on_host_maintenance         = # value needed
    on_instance_stop_action {
      discard_local_ssd = # value needed
    }
    preemptible        = # value needed
    provisioning_model = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    instance_termination_action = # value needed
    maintenance_interval        = # value needed
    min_node_cpus               = # value needed
    on_host_maintenance         = # value needed
    on_instance_stop_action {
      discard_local_ssd = # value needed
    }
    preemptible        = # value needed
    provisioning_model = # value needed
  }
}

```

2024-05-13 18:25 UTC, modular-magician commented
#### Tests analytics
Total tests: `923`
Passed tests: `844`
Skipped tests: `72`
Affected tests: `7`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction|TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction|TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction|TestAccComputeInstance_maxRunDuration_update|TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction|TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction|TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-13 18:32 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction.log)]
`TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction.log)]
`TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction.log)]
`TestAccComputeInstance_maxRunDuration_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstance_maxRunDuration_update.log)]
`TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction.log)]
`TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction.log)]
`TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording/TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/fc4fa7a3-d9b1-49fd-b00d-c3047a743115/recording) for each test

2024-05-15 14:21 UTC, SarahFrench requested changes
Thanks for your PR - the new tests look good and are passing but I want to make sure [this message](https://github.com/GoogleCloudPlatform/magic-modules/pull/10683#issuecomment-2108474157) about missing test coverage is acknowledged.

That message shows that the new `on_instance_stop_action` field is also being added to the `google_compute_instance_from_machine_image` resource. This is because schemas are re-used in the provider ([see here](https://github.com/hashicorp/terraform-provider-google-beta/blob/3d8fce747cf855191df3e92cc224121d90a4abcb/google-beta/services/compute/resource_compute_instance_from_machine_image.go#L37) for google_compute_instance_from_machine_image).

Firstly, could you please update the documentation for google_compute_instance_from_machine_image to include the new field?

And then, could you please add a basic acceptance test  that tests the new field/behaviour you've added to `google_compute_instance_from_machine_image`?

I'm happy for us to ignore [the message](https://github.com/GoogleCloudPlatform/magic-modules/pull/10683#issuecomment-2108474157)'s warnings about lack of test coverage on fields that your PR isn't adding.

2024-05-16 01:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 234 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 10 files changed, 721 insertions(+), 42 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 54 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    instance_termination_action = # value needed
    maintenance_interval        = # value needed
    min_node_cpus               = # value needed
    on_host_maintenance         = # value needed
    on_instance_stop_action {
      discard_local_ssd = # value needed
    }
    preemptible        = # value needed
    provisioning_model = # value needed
  }
}

```

2024-05-16 01:59 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `9`
Skipped tests: `37`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccComputeInstanceFromMachineImage_maxRunDuration
- TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_maxRunDuration_update
- TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction
- TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/e02477de-951b-4fe9-8875-5afe3ccadf0f/build-log/replaying_test.log)

2024-05-16 03:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 234 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 853 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 54 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-16 03:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `9`
Skipped tests: `37`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccComputeInstanceFromMachineImage_maxRunDuration
- TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_maxRunDuration_update
- TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction
- TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/b57414a6-56ee-4de1-a122-6693e8f1f4fb/build-log/replaying_test.log)

2024-05-16 03:37 UTC, arungantasala commented
/gcbrun

2024-05-16 03:45 UTC, arungantasala commented
1) `google_compute_instance_from_machine_image` [documentation](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_from_machine_image) mentions "In addition to these, most* arguments from `google_compute_instance` are supported as a way to override the properties in the machine image."  This includes the new argument `on_instance_stop_action`
2) Added acceptance tests for the new field at all the relavant places

2024-05-16 11:13 UTC, SarahFrench reviewed
The [problem reported here](https://github.com/GoogleCloudPlatform/magic-modules/pull/10683#issuecomment-2113963337) is a panic that occurs when running the `TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy/access_config_update_access_config` acceptance test:

```
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 68179 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute.hasMaxRunDurationChanged(...)
	/go/src/github.com/modular-magician/terraform-provider-google-beta/google-beta/services/compute/compute_instance_helpers.go:705
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute.schedulingHasChangeRequiringReboot(0xc001302ca8?)
	/go/src/github.com/modular-magician/terraform-provider-google-beta/google-beta/services/compute/compute_instance_helpers.go:658 +0x3ce
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute.resourceComputeInstanceUpdate(0xc001f3f680, {0x4613dc0?, 0xc000161000?})
	/go/src/github.com/modular-magician/terraform-provider-google-beta/google-beta/services/compute/resource_compute_instance.go:1890 +0x1437
```

The [line compute_instance_helpers.go:705 in the generated provider](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683#diff-67d4ccf0a83752cab376f26e348528f8712234a6ba2e4b7805b96f459283b665R705) is the beginning of hasMaxRunDurationChanged function where empty interfaces are converted to maps

2024-05-16 17:44 UTC, SarahFrench requested changes
Please address the panic described in https://github.com/GoogleCloudPlatform/magic-modules/pull/10683#pullrequestreview-2060426595

2024-05-16 17:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 234 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 853 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 54 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-16 17:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `9`
Skipped tests: `37`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccComputeInstanceFromMachineImage_maxRunDuration
- TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_maxRunDuration_update
- TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction
- TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/2e15d9eb-a6a2-430d-8eb0-33740431f2eb/build-log/replaying_test.log)

2024-05-16 17:53 UTC, arungantasala commented
Thanks Sarah for pointing this out. I was not able to reproduce the issue locally by running the test you pointed out. It is somehow failing on its own due to an unrelated issue. But, i have pushed a change to fix this. I will take another look if the panic shows up again.

2024-05-16 17:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 234 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 853 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 54 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-16 18:01 UTC, modular-magician commented
#### Tests analytics
Total tests: `46`
Passed tests: `9`
Skipped tests: `37`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccComputeInstanceFromMachineImage_maxRunDuration
- TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_maxRunDuration_update
- TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction
- TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/42d6dc38-59f5-47cf-9d92-2aa96fe46531/build-log/replaying_test.log)

2024-05-16 18:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 243 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 862 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 63 insertions(+), 4 deletions(-))


## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-16 18:52 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccComputeInstanceFromMachineImage_maxRunDuration
- TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction
- TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_localSsdVM_maxRunDuration_stopTerminationAction
- TestAccComputeInstance_maxRunDuration_update
- TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction
- TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction
- TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/362d67ea-cd4e-4b61-a1eb-bb1f99dcf5bd/build-log/replaying_test.log)

2024-05-16 19:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 244 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 863 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 64 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-16 19:30 UTC, modular-magician commented
#### Tests analytics
Total tests: `927`
Passed tests: `851`
Skipped tests: `72`
Affected tests: `4`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceFromMachineImage_maxRunDuration|TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction|TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction|TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-16 19:34 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceFromMachineImage_maxRunDuration`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/recording/TestAccComputeInstanceFromMachineImage_maxRunDuration.log)]
`TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/recording/TestAccComputeInstanceFromTemplate_maxRunDuration_onInstanceStopAction.log)]
`TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/recording/TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction.log)]
`TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/recording/TestAccComputeRegionInstanceTemplate_maxRunDuration_onInstanceStopAction.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/bb69de91-8405-404c-a974-5f455d0f029f/recording) for each test

2024-05-17 20:01 UTC, arungantasala commented
/gcbrun

2024-05-17 20:03 UTC, arungantasala commented
Hi Sarah,
The panic error is now fixed. Could you please trigger the checks again and review this PR? We are planning to make this available to the customers in the next release.
Thanks.

2024-05-20 07:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 7 files changed, 244 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 863 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 64 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-20 07:49 UTC, modular-magician commented
#### Tests analytics
Total tests: `932`
Passed tests: `860`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/81eb9759-1ea3-4642-aeda-0912f1eaf041/build-log/replaying_test.log)

2024-05-20 10:11 UTC, SarahFrench submitted a review, later dismissed
Looks good - the panic is addressed and there is test coverage for all the new fields added by this PR.

2024-05-20 10:16 UTC, SarahFrench commented on mmv1/third_party/terraform/services/compute/compute_instance_helpers.go.erb
> +	return hasNodeAffinitiesChanged(oScheduling, newScheduling) || hasMaxRunDurationChanged(oScheduling, newScheduling)
This suggested change should mean that the changes only appear in the Beta provider

```suggestion
<% unless version == 'ga' -%>
	return hasNodeAffinitiesChanged(oScheduling, newScheduling) || hasMaxRunDurationChanged(oScheduling, newScheduling)
<% else -%>
	return hasNodeAffinitiesChanged(oScheduling, newScheduling)
<% end -%>
```

2024-05-20 10:19 UTC, SarahFrench commented on mmv1/third_party/terraform/services/compute/resource_compute_instance.go.erb
> +			return fmt.Errorf("Changing the machine_type, min_cpu_platform, service_account, enable_display, shielded_instance_config, scheduling.node_affinities, scheduling.max_run_duration " +
```suggestion
<% unless version == 'ga' -%>
			return fmt.Errorf("Changing the machine_type, min_cpu_platform, service_account, enable_display, shielded_instance_config, scheduling.node_affinities, scheduling.max_run_duration " +
<% else -%>
			return fmt.Errorf("Changing the machine_type, min_cpu_platform, service_account, enable_display, shielded_instance_config, scheduling.node_affinities " +
<% end -%>
```

2024-05-20 15:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 6 files changed, 219 insertions(+), 24 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 862 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 63 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-20 15:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 6 files changed, 219 insertions(+), 24 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 862 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 63 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-20 15:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 5 files changed, 41 insertions(+), 25 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 862 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 63 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-20 16:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10683-old..auto-pr-10683) ( 4 files changed, 40 insertions(+), 24 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10683-old..auto-pr-10683) ( 11 files changed, 863 insertions(+), 43 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10683-old..auto-pr-10683) ( 1 file changed, 64 insertions(+), 4 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (271 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}

```
Resource: `google_compute_instance_from_machine_image` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```
Resource: `google_compute_instance_from_template` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    maintenance_interval = # value needed
    min_node_cpus        = # value needed
    on_host_maintenance  = # value needed
    preemptible          = # value needed
  }
}

```

2024-05-20 16:07 UTC, modular-magician commented
#### Tests analytics
Total tests: `932`
Passed tests: `860`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/57881a1d-1d99-4adf-8fb3-a7b0a1ec1118/build-log/replaying_test.log)

2024-05-20 16:12 UTC, modular-magician commented
#### Tests analytics
Total tests: `932`
Passed tests: `860`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/5f62051e-788b-4763-a28b-a8e40fbd93b9/build-log/replaying_test.log)

2024-05-20 16:19 UTC, modular-magician commented
#### Tests analytics
Total tests: `932`
Passed tests: `860`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/458b2883-23d9-4a89-a281-5ec78f97d0b1/build-log/replaying_test.log)

2024-05-20 16:28 UTC, modular-magician commented
#### Tests analytics
Total tests: `932`
Passed tests: `860`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10683/artifacts/29a9241f-4bbd-4ec9-8f00-2709f54b919e/build-log/replaying_test.log)

2024-05-20 16:53 UTC, arungantasala commented
Thanks Sarah for catching this. I have made changes as you suggested.

2024-05-20 18:00 UTC, SarahFrench approved these changes
Thanks for addressing the GA/Beta issue! I can see that the diffs for the GA provider still show changes in functions like `testAccComputeInstanceTemplate_spot_maxRunDuration`, however those functions are unused in the GA code base so _the code change isn't user-facing_. Because Go tolerates unused functions and those functions were already present in the GA code before this PR, I'm happy to merge this PR

2024-05-20 18:01 UTC, merged