Make lables on uptime check config computed
GoogleCloudPlatform/magic-modules pull request #10694
Opened 2024-05-14 11:56 UTC by VenelinMartinov

Fixes a permadiff on uptime check config which causes it to be recreated every time.

The labels property in the monitored_resource property should be Computed as it is set by the API.

fixes https://github.com/hashicorp/terraform-provider-google/issues/18038

**Release Note Template for Downstream PRs (will be copied)**

```
Fix a permadiff in monitoring_uptime_check_config

```

2024-05-14 20:44 UTC, c2thorn requested changes
Hi @VenelinMartinov, thanks for contributing this fix. Would you mind adding a test to https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/monitoring/resource_monitoring_uptime_check_config_test.go that shows the currently failing scenario? There are other examples there and we have documentation under the `handwritten` tab in https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-a-create-test

2024-05-14 20:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10694-old..auto-pr-10694) ( 1 file changed, 15 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10694-old..auto-pr-10694) ( 1 file changed, 15 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10694-old..auto-pr-10694) ( 1 file changed, 10 insertions(+))

2024-05-14 21:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `55`
Passed tests: `52`
Skipped tests: `3`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>monitoring</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10694/artifacts/ee7489d6-f30b-45b5-a527-3fd67eb8b6fa/build-log/replaying_test.log)

2024-05-15 11:53 UTC, VenelinMartinov commented
Hi @c2thorn, thanks for your review. I've added a test as suggested. I verified that it fails before my fix and is fixed after.

I've also verified that https://github.com/hashicorp/terraform-provider-google/issues/18038 no longer reproes with the fix.

LMK if there are any other issues here.

2024-05-16 14:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10694-old..auto-pr-10694) ( 2 files changed, 76 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10694-old..auto-pr-10694) ( 2 files changed, 76 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10694-old..auto-pr-10694) ( 1 file changed, 10 insertions(+))

2024-05-16 14:38 UTC, modular-magician commented
#### Tests analytics
Total tests: `56`
Passed tests: `52`
Skipped tests: `3`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>monitoring</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccMonitoringUptimeCheckConfig_noProjectId </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-16 14:39 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccMonitoringUptimeCheckConfig_noProjectId`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10694/artifacts/f3e4c361-43ec-401c-b606-bd0d487d80c9/recording/TestAccMonitoringUptimeCheckConfig_noProjectId.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10694/artifacts/f3e4c361-43ec-401c-b606-bd0d487d80c9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10694/artifacts/f3e4c361-43ec-401c-b606-bd0d487d80c9/recording) for each test

2024-05-16 22:43 UTC, c2thorn approved these changes
LGTM thank you!

2024-05-16 22:43 UTC, merged