Fixes LifecycleRules Conditions not being set issue.
GoogleCloudPlatform/magic-modules pull request #10717
Opened 2024-05-16 13:37 UTC by kautikdk

Fixes https://github.com/hashicorp/terraform-provider-google/issues/17990

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
storage: fixed a bug where `google_storage_bucket.lifecycle_rule.condition` block fields  `days_since_noncurrent_time` and `days_since_custom_time`  and `num_newer_versions` were not working for 0 value.
```

2024-05-16 13:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10717-old..auto-pr-10717) ( 2 files changed, 98 insertions(+), 15 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10717-old..auto-pr-10717) ( 2 files changed, 98 insertions(+), 15 deletions(-))

2024-05-16 13:57 UTC, kautikdk commented
For tests, We can not actually check value from the cloud infra because of the empty value limitation in go language. I have added all the virtual fields to cover no permadiff happing in any case and field modification is not causing state inconsistency.

2024-05-16 14:00 UTC, modular-magician commented
#### Tests analytics
Total tests: `93`
Passed tests: `86`
Skipped tests: `6`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>storage</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccStorageBucket_lifecycleRulesVirtualFields </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-16 14:01 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccStorageBucket_lifecycleRulesVirtualFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10717/artifacts/a40d6007-7799-49b7-8730-022b76319377/recording/TestAccStorageBucket_lifecycleRulesVirtualFields.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10717/artifacts/a40d6007-7799-49b7-8730-022b76319377/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10717/artifacts/a40d6007-7799-49b7-8730-022b76319377/recording) for each test

2024-05-21 22:33 UTC, NickElliot approved these changes
LGTM -- I'm not certain we should mark this as "fixing" the issue, as we still want to update the behavior for the `age` condition down the line during the major release. May be appropriate to open a new ticket for that seperately, or keep the current one open.

2024-05-22 04:33 UTC, kautikdk commented
Well, We can do it either ways. I think with this PR merged and with the `no_age` field, Users can set lifecycle rule conditions as they want without any problem. So we can mark this one as fixed and open new ticket for changing `age` behavior. That's my opinion on this but I am also okay with keeping this ticket open.

2024-05-23 16:50 UTC, NickElliot commented
sounds good to me!

2024-05-23 16:53 UTC, NickElliot requested changes
Ah sorry, these need to be included in the docs at `mmv1/third_party/terraform/website/docs/r/storage_bucket.html.markdown`

2024-05-23 17:17 UTC, kautikdk commented
Oops, I forgot to add these new fields in the markdown file. 
Added in the new commit.

2024-05-23 17:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10717-old..auto-pr-10717) ( 3 files changed, 107 insertions(+), 18 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10717-old..auto-pr-10717) ( 3 files changed, 107 insertions(+), 18 deletions(-))

2024-05-23 17:33 UTC, NickElliot approved these changes

2024-05-23 17:33 UTC, merged

2024-05-23 17:35 UTC, modular-magician commented
#### Tests analytics
Total tests: `94`
Passed tests: `88`
Skipped tests: `6`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>storage</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10717/artifacts/70ca0b53-ea35-4212-b70a-77d020f2e666/build-log/replaying_test.log)