Feat/service lb policy
GoogleCloudPlatform/magic-modules pull request #10730
Opened 2024-05-17 15:47 UTC by Samir-Cit

This PR adds the new resource **Service LB Policies** `google_network_services_service_lb_policies` to the providers.

- It's missing the API reference page because it still doesn’t exist.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_network_services_service_lb_policies`
```

2024-05-20 19:24 UTC, Samir-Cit commented
@c2thorn were you able to check this PR?

2024-05-22 22:23 UTC, c2thorn commented
> * Once the API reference page is provided by Google team this PR will be updated.

Apologies, getting to this now.

> Once the API reference page is provided by Google team this PR will be updated.

Is this new enough that it doesn't have a reference page? Is the feature publicly available?

2024-05-22 22:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10730-old..auto-pr-10730) ( 6 files changed, 1246 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10730-old..auto-pr-10730) ( 6 files changed, 1246 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10730-old..auto-pr-10730) ( 1 file changed, 154 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 224 insertions(+))

2024-05-22 22:38 UTC, modular-magician commented
#### Tests analytics
Total tests: `54`
Passed tests: `51`
Skipped tests: `0`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>networkservices</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccNetworkServicesLBPolicies_update|TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample|TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesBasicExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-22 22:39 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccNetworkServicesLBPolicies_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/recording/TestAccNetworkServicesLBPolicies_update.log)]
`TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/recording/TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesBasicExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/build-log/recording_build/TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/recording/TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/418121e5-acc2-47d5-8dd5-f357d72b9c2b/recording) for each test

2024-05-23 17:28 UTC, Samir-Cit commented
> > Once the API reference page is provided by Google team this PR will be updated.
> 
> Is this new enough that it doesn't have a reference page? Is the feature publicly available?

The resource have some documentation pages but the `API Discovery Doc` is not available yet. Apparently this doc was sent to review today.
For the development of the `Terraform resource` I used this doc regarding [set up advanced load balancing](https://cloud.google.com/service-mesh/docs/service-routing/set-up-advanced-load-balancing)

2024-05-27 18:35 UTC, Samir-Cit commented
Hello @c2thorn 
I updated the PR, can you do a round of review?

The updates were:
- Merge main
- Test fix
- New example/test with backend_service

2024-05-29 20:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 1281 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 1281 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10730-old..auto-pr-10730) ( 2 files changed, 164 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 232 insertions(+))

2024-05-29 20:46 UTC, modular-magician commented
#### Tests analytics
Total tests: `991`
Passed tests: `878`
Skipped tests: `72`
Affected tests: `41`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li><li>networkservices</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 41 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_versions|TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 21:12 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputeInstanceGroup_rename`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeInstanceGroup_rename.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputePerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeRegionAutoscaler_scaleDownControl.log)]
`TestAccComputeRegionAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeRegionAutoscaler_scaleInControl.log)]
`TestAccComputeRegionAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeRegionAutoscaler_scalingSchedule.log)]
`TestAccComputeRegionAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeRegionAutoscaler_update.log)]
`TestAccComputeTargetPool_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccComputeTargetPool_basic.log)]
`TestAccInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_autoHealingPolicies.log)]
`TestAccInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_basic.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccInstanceGroupManager_self_link_unique`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_self_link_unique.log)]
`TestAccInstanceGroupManager_stateful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_stateful.log)]
`TestAccInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_targetSizeZero.log)]
`TestAccInstanceGroupManager_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_update.log)]
`TestAccInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_versions.log)]
`TestAccInstanceGroupManager_waitForStatus`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccInstanceGroupManager_waitForStatus.log)]
`TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccNetworkServicesServiceLbPolicies_networkServicesServiceLbPoliciesAdvancedExample.log)]
`TestAccRegionInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccRegionInstanceGroupManager_autoHealingPolicies.log)]
`TestAccRegionInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccRegionInstanceGroupManager_basic.log)]
`TestAccRegionInstanceGroupManager_distributionPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/recording/TestAccRegionInstanceGroupManager_distributionPolicy.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/b3c0a195-42b7-457d-95da-636ae6b3713c/ [...]

2024-05-29 21:46 UTC, c2thorn requested changes

2024-05-30 02:23 UTC, Samir-Cit commented on mmv1/third_party/terraform/services/networkservices/resource_network_services_service_lb_policies_test.go
> +package networkservices_test
Sure thing.
I updated the test following the example you sent and changed to `.go.erb`.
I run locally and it's working fine.

2024-05-30 02:23 UTC, Samir-Cit commented on mmv1/products/networkservices/ServiceLBPolicies.yaml
> +base_url: 'projects/{{project}}/locations/{{location}}/serviceLbPolicies'
That totally makes sense.
I just added this `min_version: beta` on the provider and as soon as the official doc is released we can open other PR with the changes.

2024-05-30 13:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10730-old..auto-pr-10730) ( 4 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 1295 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10730-old..auto-pr-10730) ( 2 files changed, 164 insertions(+))

2024-05-30 13:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `994`
Passed tests: `886`
Skipped tests: `72`
Affected tests: `36`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>networkservices</li><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 36 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_versions </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-30 13:50 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_distributionPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccRegionInstanceGroupManager_distributionPolicy.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_stateful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccRegionInstanceGroupManager_stateful.log)]
`TestAccRegionInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccRegionInstanceGroupManager_targetSizeZero.log)]
`TestAccRegionInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccRegionInstanceGroupManager_versions.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_autoscalerSingleInstanceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_multicondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_scaleDownControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_scaleInControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_scaleInControlFixed_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeAutoscaler_scalingSchedule_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeBackendService_withBackendAndIAP_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputePerInstanceConfig_statefulIps_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputePerInstanceConfig_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputePerInstanceConfig_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/5b8209a1-b083-487d-a372-a855cdbc3966/build-log/recording_build/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/b [...]

2024-06-04 21:01 UTC, c2thorn commented
/gcbrun

2024-06-04 21:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10730-old..auto-pr-10730) ( 4 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10730-old..auto-pr-10730) ( 8 files changed, 1295 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10730-old..auto-pr-10730) ( 2 files changed, 164 insertions(+))

2024-06-04 21:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `1006`
Passed tests: `894`
Skipped tests: `74`
Affected tests: `38`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li><li>networkservices</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 38 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_versions </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-04 21:56 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputeInstanceGroup_rename`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeInstanceGroup_rename.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputePerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionAutoscaler_scaleDownControl.log)]
`TestAccComputeRegionAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionAutoscaler_scaleInControl.log)]
`TestAccComputeRegionAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionAutoscaler_scalingSchedule.log)]
`TestAccComputeRegionAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionAutoscaler_update.log)]
`TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey.log)]
`TestAccComputeTargetPool_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccComputeTargetPool_basic.log)]
`TestAccInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_autoHealingPolicies.log)]
`TestAccInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_basic.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccInstanceGroupManager_self_link_unique`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_self_link_unique.log)]
`TestAccInstanceGroupManager_stateful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_stateful.log)]
`TestAccInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_targetSizeZero.log)]
`TestAccInstanceGroupManager_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_update.log)]
`TestAccInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_versions.log)]
`TestAccInstanceGroupManager_waitForStatus`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccInstanceGroupManager_waitForStatus.log)]
`TestAccRegionInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccRegionInstanceGroupManager_autoHealingPolicies.log)]
`TestAccRegionInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccRegionInstanceGroupManager_basic.log)]
`TestAccRegionInstanceGroupManager_distributionPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccRegionInstanceGroupManager_distributionPolicy.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10730/artifacts/2b3007fe-f41d-43c7-bf18-af525a0733ac/recording/TestAccRegionInstanceGroupManager_resource [...]

2024-06-05 01:42 UTC, c2thorn approved these changes

2024-06-05 01:42 UTC, merged