Add executing job support for `google_cloud_run_v2_job` resource
GoogleCloudPlatform/magic-modules pull request #10734
Opened 2024-05-17 18:42 UTC by yanweiguo

For https://github.com/hashicorp/terraform-provider-google/issues/13390.

Adding field `start_execution_token` to resource `google_cloud_run_v2_job` to allow executing the job automatically once the job is created or updated. This is currently add to `terraform-provider-google-beta` provider only.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrunv2: added field `start_execution_token` to resource `google_cloud_run_v2_job` to allow executing the job automatically once the job is created or updated.
```

2024-05-17 18:56 UTC, modular-magician commented
#### Tests analytics
Total tests: `42`
Passed tests: `40`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2Job_cloudrunv2JobRunJobExample|TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-17 19:07 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Job_cloudrunv2JobRunJobExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/recording/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/recording/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/c0ecdebf-da07-4213-8038-7d5387acdf52/recording) for each test

2024-05-17 19:25 UTC, whaught approved these changes

2024-05-17 19:25 UTC, whaught commented on mmv1/products/cloudrunv2/Job.yaml
> +    name: start_execution_token
Do we want to include `run_execution_token` in the same PR? That might be the more common user scenario (they are oneof)

2024-05-17 19:25 UTC, whaught commented on mmv1/products/cloudrunv2/Job.yaml
> +    name: start_execution_token
okay it look like that one isn't visible for v2 yet, we'll do that in the future.

2024-05-17 21:19 UTC, paridhishah18 approved these changes

2024-05-19 16:13 UTC, whaught approved these changes

2024-05-21 22:37 UTC, NickElliot requested changes
Two issues from the test: 
* the supplied `launch_stage` is being ignored, and returned as "GA" even though the POST request had "BETA"
* `start_execution_token` is not being returned by the API, I'm not certain if this is expected, but the field may need an `ignore_read: true` tag on it

2024-05-30 22:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10734-old..auto-pr-10734) ( 2 files changed, 79 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 260 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10734-old..auto-pr-10734) ( 1 file changed, 30 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 113 insertions(+))


## Errors

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-05-30 22:07 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestAccCloudRunV2Job_cloudrunv2JobRunJobExample
- TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/a1e2a846-e92f-45f5-b446-02191bb06fab/build-log/replaying_test.log)

2024-05-30 23:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10734-old..auto-pr-10734) ( 2 files changed, 74 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 226 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10734-old..auto-pr-10734) ( 1 file changed, 20 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 113 insertions(+))

2024-05-30 23:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `42`
Passed tests: `24`
Skipped tests: `0`
Affected tests: `18`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 18 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2JobIamBindingGenerated|TestAccCloudRunV2JobIamMemberGenerated|TestAccCloudRunV2JobIamPolicyGenerated|TestAccCloudRunV2Job_cloudrunv2JobBasicExample|TestAccCloudRunV2Job_cloudrunv2JobDirectvpcExample|TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample|TestAccCloudRunV2Job_cloudrunv2JobFullUpdate|TestAccCloudRunV2Job_cloudrunv2JobLimitsExample|TestAccCloudRunV2Job_cloudrunv2JobRunJobExample|TestAccCloudRunV2Job_cloudrunv2JobSecretExample|TestAccCloudRunV2Job_cloudrunv2JobSqlExample|TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample|TestAccCloudRunV2Job_cloudrunv2JobWithDirectVPCUpdate|TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate|TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate|TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate|TestAccDataSourceGoogleCloudRunV2Job_basic|TestAccDataSourceGoogleCloudRunV2Job_bindIAMPermission </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 00:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2JobIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2JobIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2JobIamBindingGenerated.log)]
`TestAccCloudRunV2JobIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2JobIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2JobIamMemberGenerated.log)]
`TestAccCloudRunV2JobIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2JobIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2JobIamPolicyGenerated.log)]
`TestAccCloudRunV2Job_cloudrunv2JobBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobBasicExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobDirectvpcExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobDirectvpcExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobDirectvpcExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobFullUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobLimitsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobLimitsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobLimitsExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobRunJobExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSecretExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobSecretExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobSecretExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobSqlExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithDirectVPCUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithDirectVPCUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobWithDirectVPCUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/recording/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate.log)]
`TestAccDataSourceGoogleCloudRunV2Job_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/67360a76-cb2a-426d-9b18-e6ec78fd900a/build-log/recording_build/TestAccDataSourceGoogleCloudRunV2Job_basic_recor [...]

2024-05-31 17:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10734-old..auto-pr-10734) ( 2 files changed, 74 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 226 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10734-old..auto-pr-10734) ( 1 file changed, 20 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 113 insertions(+))

2024-05-31 17:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `42`
Passed tests: `40`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2Job_cloudrunv2JobRunJobExample|TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 17:44 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Job_cloudrunv2JobRunJobExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/recording/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/recording/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/411db3c7-346c-429d-a2a2-4454352be5a7/recording) for each test

2024-06-04 22:47 UTC, NickElliot requested changes
need to have camelcase for fieldnames in the yaml :)

2024-06-04 22:47 UTC, NickElliot commented on mmv1/products/cloudrunv2/Job.yaml
> +    name: run_execution_token
```suggestion
    name: runExecutionToken
```

2024-06-04 22:47 UTC, NickElliot commented on mmv1/products/cloudrunv2/Job.yaml
> +    name: start_execution_token
```suggestion
    name: startExecutionToken
```

2024-06-04 23:50 UTC, yanweiguo commented on mmv1/products/cloudrunv2/Job.yaml
> +    name: start_execution_token
Oops.

2024-06-05 00:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10734-old..auto-pr-10734) ( 2 files changed, 74 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 226 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10734-old..auto-pr-10734) ( 1 file changed, 20 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10734-old..auto-pr-10734) ( 4 files changed, 113 insertions(+))

2024-06-05 00:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `42`
Passed tests: `40`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2Job_cloudrunv2JobRunJobExample|TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 00:17 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Job_cloudrunv2JobRunJobExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/6b92161c-a0f0-4384-affa-b546e9c76c99/recording/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/6b92161c-a0f0-4384-affa-b546e9c76c99/build-log/recording_build/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/6b92161c-a0f0-4384-affa-b546e9c76c99/recording/TestAccCloudRunV2Job_cloudrunv2JobWithRunJobTokenUpdate.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/6b92161c-a0f0-4384-affa-b546e9c76c99/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/6b92161c-a0f0-4384-affa-b546e9c76c99/recording) for each test

2024-06-05 18:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10734-old..auto-pr-10734) ( 3 files changed, 90 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10734-old..auto-pr-10734) ( 5 files changed, 265 insertions(+), 17 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10734-old..auto-pr-10734) ( 1 file changed, 20 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-10734-old..auto-pr-10734) ( 9 files changed, 118 insertions(+), 5 deletions(-))

2024-06-05 18:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `43`
Passed tests: `31`
Skipped tests: `0`
Affected tests: `12`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrunv2</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2JobIamBindingGenerated|TestAccCloudRunV2JobIamMemberGenerated|TestAccCloudRunV2JobIamPolicyGenerated|TestAccCloudRunV2Job_cloudrunv2JobBasicExample|TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample|TestAccCloudRunV2Job_cloudrunv2JobLimitsExample|TestAccCloudRunV2Job_cloudrunv2JobRunJobExample|TestAccCloudRunV2Job_cloudrunv2JobSecretExample|TestAccCloudRunV2Job_cloudrunv2JobSqlExample|TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample|TestAccCloudRunV2Job_cloudrunv2JobWithRunExecutionTokenUpdate|TestAccCloudRunV2Job_cloudrunv2JobWithStartExecutionTokenUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 18:34 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2JobIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2JobIamBindingGenerated.log)]
`TestAccCloudRunV2JobIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2JobIamMemberGenerated.log)]
`TestAccCloudRunV2JobIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2JobIamPolicyGenerated.log)]
`TestAccCloudRunV2Job_cloudrunv2JobBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobBasicExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobEmptydirExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobLimitsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobLimitsExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobRunJobExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobRunJobExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSecretExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobSecretExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobSqlExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithRunExecutionTokenUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobWithRunExecutionTokenUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobWithStartExecutionTokenUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording/TestAccCloudRunV2Job_cloudrunv2JobWithStartExecutionTokenUpdate.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10734/artifacts/59bff9e9-2ec3-4ba3-930c-87d8d0701855/recording) for each test

2024-06-10 18:19 UTC, whaught approved these changes

2024-06-12 20:10 UTC, NickElliot approved these changes
LGTM!

2024-06-12 20:10 UTC, merged