`google_compute_instance` - add validation for `name`
GoogleCloudPlatform/magic-modules pull request #10775
Opened 2024-05-23 07:49 UTC by AlexPykavy

To fail during the plan phase if the name violates the following rules:
https://cloud.google.com/compute/docs/naming-resources#resource-name-format.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
`google_compute_instance` - add validation for `name`
```

2024-05-23 07:52 UTC, AlexPykavy commented
Initially I opened a PR to the https://github.com/hashicorp/terraform-provider-google/pull/18227 but then found that it has to be directed here.

In that PR I wanted to use some human-friendly error message, like `The name can be 1-63 characters in length. The first character must be a lowercase letter, and all the following characters must be hyphens, lowercase letters, or digits, except the last character, which cannot be a hyphen.`. As far as I can [see](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/provider/terraform/validation.rb) it's not possible with the current implementation of the magic-modules because `regex` attribute can't accept any inner arguments.  May we extend this logic to allow this?

2024-05-23 22:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-05-28 16:54 UTC, c2thorn requested changes
Hi @AlexPykavy 
There are a few things with this change:

1. Adding stricter validation is overall a breaking change: https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes/#making-validation-more-strict
This would need to be saved for the 6.0.0 major release and have a github issue created to track it.
1. Compute instance is a handwritten file so your changes would have to be made directly against the go code in https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/compute/resource_compute_instance.go.erb

2024-05-28 18:13 UTC, AlexPykavy commented
Hi @c2thorn ,

I will update the handwritten file then.

Also I am not sure that it's a breaking change as this validation has been already done by the Compute Engine API. The only thing I do is repeating the same validation during the plan phase. So let me know where you are ready to accept this change: in the current version or in the next major.

2024-05-28 20:33 UTC, c2thorn reviewed
Saving validation changes for major releases is a general rule, and I'd want to make sure we are careful when it comes to as important of a resource as `google_compute_instance` is. If you wouldn't mind creating a GH issue for it: https://github.com/hashicorp/terraform-provider-google/issues/new/choose

It would go to the triage team which would be able to make a decision on the time

2024-05-29 11:56 UTC, closed without merging