Add Managed Kafka Cluster resource and tests
GoogleCloudPlatform/magic-modules pull request #10773
Opened 2024-05-23 04:50 UTC by jessdejong

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-05-23 05:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 2 files changed, 322 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1569 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_managed_kafka_cluster` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_managed_kafka_cluster" "primary" {
  gcp_config {
    kms_key = # value needed
  }
}

```

2024-05-23 06:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `3701`
Passed tests: `3328`
Skipped tests: `371`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-23 06:07 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccManagedKafkaCluster_managedkafkaClusterBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/recording/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample.log)]
`TestAccManagedKafkaCluster_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/build-log/recording_build/TestAccManagedKafkaCluster_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/recording/TestAccManagedKafkaCluster_update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6efb426e-4b1c-4423-b52b-b7a6d23fc0fc/recording) for each test

2024-05-24 21:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 2 files changed, 274 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1703 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-24 22:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 2 files changed, 273 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1703 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-24 22:27 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2836`
Skipped tests: `373`
Affected tests: `511`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 511 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAlloydbBackup_alloydbBackupBasicTestExample|TestAccAlloydbBackup_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight|TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable|TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_alloydbClusterBasicExample|TestAccAlloydbCluster_alloydbClusterFullExample|TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample|TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable|TestAccAlloydbCluster_continuousBackup_enabledByDefault|TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved|TestAccAlloydbCluster_continuousBackup_update|TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet|TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_missingWeeklySchedule|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_secondaryClusterPromote|TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate|TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate|TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_update|TestAccAlloydbCluster_usingCMEK|TestAccAlloydbCluster_withMaintenanceWindows|TestAccAlloydbCluster_withNetworkConfig|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbInstance_alloydbInstanceBasicTestExample|TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample|TestAccAlloydbInstance_clientConnectionConfig|TestAccAlloydbInstance_networkConfig|TestAccAlloydbInstance_secondaryInstanceMaximumFields|TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag|TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig|TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig|TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance|TestAccAlloydbInstance_update|TestAccAlloydbUser_alloydbUserBuiltinTestExample|TestAccAlloydbUser_alloydbUserIamTestExample|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updateRoles_IAM|TestAccAppEngineFlexibleAppVersion_update|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerhubAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteMavenCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteNpmCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemotePythonCustomWithAuthExample|TestAccBigQueryDataset_cmek|TestAccBigQueryJob_bigqueryJobCopyExample|TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample|TestAccBigQueryTable_Kms|TestAccBigqueryConnectionConnection_bigqueryConnectionKmsExample|TestAccBigqueryDataTransferConfig|TestAccBillingBudget_billingBudgetBasicExample|TestAccBillingBudget_billingBudgetCustomperiodExample|TestAccBillingBudget_billingBudgetFilterExample|TestAccBillingBudget_billingBudgetLastperiodExample|TestAccBillingBudget_billingBudgetNotifyExample|TestAccBillingBudget_billingBudgetOptionalExample|TestAccBillingBudget_billingBudgetUpdate|TestAccBillingBudget_billingFilterSubaccounts|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccele [...]

2024-05-24 22:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 286 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1703 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-24 22:56 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2837`
Skipped tests: `373`
Affected tests: `510`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 510 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAlloydbBackup_alloydbBackupBasicTestExample|TestAccAlloydbBackup_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight|TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable|TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_alloydbClusterBasicExample|TestAccAlloydbCluster_alloydbClusterFullExample|TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample|TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable|TestAccAlloydbCluster_continuousBackup_enabledByDefault|TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved|TestAccAlloydbCluster_continuousBackup_update|TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet|TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_missingWeeklySchedule|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_secondaryClusterPromote|TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate|TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate|TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_update|TestAccAlloydbCluster_usingCMEK|TestAccAlloydbCluster_withMaintenanceWindows|TestAccAlloydbCluster_withNetworkConfig|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbInstance_alloydbInstanceBasicTestExample|TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample|TestAccAlloydbInstance_clientConnectionConfig|TestAccAlloydbInstance_networkConfig|TestAccAlloydbInstance_secondaryInstanceMaximumFields|TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag|TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig|TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig|TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance|TestAccAlloydbInstance_update|TestAccAlloydbUser_alloydbUserBuiltinTestExample|TestAccAlloydbUser_alloydbUserIamTestExample|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updateRoles_IAM|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerhubAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteMavenCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteNpmCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemotePythonCustomWithAuthExample|TestAccBigQueryDataset_cmek|TestAccBigQueryJob_bigqueryJobCopyExample|TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample|TestAccBigQueryTable_Kms|TestAccBigqueryDataTransferConfig|TestAccBillingBudget_billingBudgetBasicExample|TestAccBillingBudget_billingBudgetCustomperiodExample|TestAccBillingBudget_billingBudgetFilterExample|TestAccBillingBudget_billingBudgetLastperiodExample|TestAccBillingBudget_billingBudgetNotifyExample|TestAccBillingBudget_billingBudgetOptionalExample|TestAccBillingBudget_billingBudgetUpdate|TestAccBillingBudget_billingFilterSubaccounts|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccelerator|TestAccComputeInstanceTemplate_instanceResourcePolicies|TestAccComputeInstanceTemplate_localSsdRecove [...]

2024-05-24 23:47 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2836`
Skipped tests: `373`
Affected tests: `511`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 511 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAlloydbBackup_alloydbBackupBasicTestExample|TestAccAlloydbBackup_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight|TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable|TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_alloydbClusterBasicExample|TestAccAlloydbCluster_alloydbClusterFullExample|TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample|TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable|TestAccAlloydbCluster_continuousBackup_enabledByDefault|TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved|TestAccAlloydbCluster_continuousBackup_update|TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet|TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_missingWeeklySchedule|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_secondaryClusterPromote|TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate|TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate|TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_update|TestAccAlloydbCluster_usingCMEK|TestAccAlloydbCluster_withMaintenanceWindows|TestAccAlloydbCluster_withNetworkConfig|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbInstance_alloydbInstanceBasicTestExample|TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample|TestAccAlloydbInstance_clientConnectionConfig|TestAccAlloydbInstance_networkConfig|TestAccAlloydbInstance_secondaryInstanceMaximumFields|TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag|TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig|TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig|TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance|TestAccAlloydbInstance_update|TestAccAlloydbUser_alloydbUserBuiltinTestExample|TestAccAlloydbUser_alloydbUserIamTestExample|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updateRoles_IAM|TestAccAppEngineFlexibleAppVersion_update|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerhubAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteMavenCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteNpmCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemotePythonCustomWithAuthExample|TestAccBigQueryDataset_cmek|TestAccBigQueryJob_bigqueryJobCopyExample|TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample|TestAccBigQueryTable_Kms|TestAccBigqueryConnectionConnection_bigqueryConnectionKmsExample|TestAccBigqueryDataTransferConfig|TestAccBillingBudget_billingBudgetBasicExample|TestAccBillingBudget_billingBudgetCustomperiodExample|TestAccBillingBudget_billingBudgetFilterExample|TestAccBillingBudget_billingBudgetLastperiodExample|TestAccBillingBudget_billingBudgetNotifyExample|TestAccBillingBudget_billingBudgetOptionalExample|TestAccBillingBudget_billingBudgetUpdate|TestAccBillingBudget_billingFilterSubaccounts|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccele [...]

2024-05-26 22:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-26 23:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2836`
Skipped tests: `373`
Affected tests: `511`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 511 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAlloydbBackup_alloydbBackupBasicTestExample|TestAccAlloydbBackup_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight|TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable|TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_alloydbClusterBasicExample|TestAccAlloydbCluster_alloydbClusterFullExample|TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample|TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable|TestAccAlloydbCluster_continuousBackup_enabledByDefault|TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved|TestAccAlloydbCluster_continuousBackup_update|TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet|TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_missingWeeklySchedule|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_secondaryClusterPromote|TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate|TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate|TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_update|TestAccAlloydbCluster_usingCMEK|TestAccAlloydbCluster_withMaintenanceWindows|TestAccAlloydbCluster_withNetworkConfig|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbInstance_alloydbInstanceBasicTestExample|TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample|TestAccAlloydbInstance_clientConnectionConfig|TestAccAlloydbInstance_networkConfig|TestAccAlloydbInstance_secondaryInstanceMaximumFields|TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag|TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig|TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig|TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance|TestAccAlloydbInstance_update|TestAccAlloydbUser_alloydbUserBuiltinTestExample|TestAccAlloydbUser_alloydbUserIamTestExample|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updateRoles_IAM|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerhubAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteMavenCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteNpmCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemotePythonCustomWithAuthExample|TestAccBigQueryDataset_cmek|TestAccBigQueryJob_bigqueryJobCopyExample|TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample|TestAccBigQueryTable_Kms|TestAccBigqueryDataTransferConfig|TestAccBillingBudget_billingBudgetBasicExample|TestAccBillingBudget_billingBudgetCustomperiodExample|TestAccBillingBudget_billingBudgetFilterExample|TestAccBillingBudget_billingBudgetLastperiodExample|TestAccBillingBudget_billingBudgetNotifyExample|TestAccBillingBudget_billingBudgetOptionalExample|TestAccBillingBudget_billingBudgetUpdate|TestAccBillingBudget_billingFilterSubaccounts|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccelerator|TestAccComputeInstanceTemplate_instanceResourcePolicies|TestAccComputeInstanceTemplate_localSsdRecove [...]

2024-05-28 17:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-28 18:37 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2843`
Skipped tests: `373`
Affected tests: `504`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 504 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccAlloydbBackup_alloydbBackupBasicTestExample|TestAccAlloydbBackup_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight|TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable|TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_alloydbClusterBasicExample|TestAccAlloydbCluster_alloydbClusterFullExample|TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample|TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable|TestAccAlloydbCluster_continuousBackup_enabledByDefault|TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved|TestAccAlloydbCluster_continuousBackup_update|TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet|TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_missingWeeklySchedule|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_secondaryClusterPromote|TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser|TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary|TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy|TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate|TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate|TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_update|TestAccAlloydbCluster_usingCMEK|TestAccAlloydbCluster_withMaintenanceWindows|TestAccAlloydbCluster_withNetworkConfig|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbInstance_alloydbInstanceBasicTestExample|TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample|TestAccAlloydbInstance_clientConnectionConfig|TestAccAlloydbInstance_networkConfig|TestAccAlloydbInstance_secondaryInstanceMaximumFields|TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag|TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig|TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig|TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance|TestAccAlloydbInstance_update|TestAccAlloydbUser_alloydbUserBuiltinTestExample|TestAccAlloydbUser_alloydbUserIamTestExample|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updateRoles_IAM|TestAccAppEngineFlexibleAppVersion_update|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteDockerhubAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteMavenCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemoteNpmCustomWithAuthExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryRemotePythonCustomWithAuthExample|TestAccBigQueryDataset_cmek|TestAccBigQueryJob_bigqueryJobCopyExample|TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample|TestAccBigQueryTable_Kms|TestAccBigqueryDataTransferConfig|TestAccBillingBudget_billingBudgetBasicExample|TestAccBillingBudget_billingBudgetCustomperiodExample|TestAccBillingBudget_billingBudgetFilterExample|TestAccBillingBudget_billingBudgetLastperiodExample|TestAccBillingBudget_billingBudgetNotifyExample|TestAccBillingBudget_billingBudgetOptionalExample|TestAccBillingBudget_billingBudgetUpdate|TestAccBillingBudget_billingFilterSubaccounts|TestAccBillingBudget_budgetFilterProjectsOrdering|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccelerator|TestAccComputeInstanceTemplate_instanceResourcePolicies|Tes [...]

2024-05-28 20:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-28 21:48 UTC, modular-magician commented
#### Tests analytics
Total tests: `3720`
Passed tests: `2916`
Skipped tests: `373`
Affected tests: `431`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 431 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigqueryConnectionConnection_bigqueryConnectionKmsExample|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample|TestAccComputeDiskResourcePolicyAttachment_update|TestAccComputeDisk_cloneDisk|TestAccComputeDisk_deleteDetach|TestAccComputeDisk_encryptionKMS|TestAccComputeDisk_fromSnapshot|TestAccComputeDisk_fromTypeUrl|TestAccComputeDisk_multiWriter|TestAccComputeDisk_resourcePolicies|TestAccComputeDisk_update|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeImage_basedondisk|TestAccComputeImage_imageEncryptionKey|TestAccComputeImage_sourceImage|TestAccComputeImage_sourceSnapshot|TestAccComputeImage_withLicense|TestAccComputeInstanceGroup_basic|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_EncryptKMS|TestAccComputeInstanceTemplate_IP|TestAccComputeInstanceTemplate_IPv6|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_basic|TestAccComputeInstanceTemplate_diskIops|TestAccComputeInstanceTemplate_diskResourcePolicies|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_enableDisplay|TestAccComputeInstanceTemplate_guestAccelerator|TestAccComputeInstanceTemplate_instanceResourcePolicies|TestAccComputeInstanceTemplate_localSsdRecoveryTimeout|TestAccComputeInstanceTemplate_maintenance_interval|TestAccComputeInstanceTemplate_managedEnvoy|TestAccComputeInstanceTemplate_maxRunDuration_onInstanceStopAction|TestAccComputeInstanceTemplate_minCpuPlatform|TestAccComputeInstanceTemplate_networkIP|TestAccComputeInstanceTemplate_networkIPAddress|TestAccComputeInstanceTemplate_networkTier|TestAccComputeInstanceTemplate_preemptible|TestAccComputeInstanceTemplate_primaryAliasIpRange|TestAccComputeInstanceTemplate_regionDisks|TestAccComputeInstanceTemplate_reservationAffinities|TestAccComputeInstanceTemplate_secondaryAliasIpRange|TestAccComputeInstanceTemplate_shieldedVmConfig1|TestAccComputeInstanceTemplate_shieldedVmConfig2|TestAccComputeInstanceTemplate_soleTenantNodeAffinities|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstanceTemplate_sourceSnapshotEncryptionKey|TestAccComputeInstanceTemplate_spot|TestAccComputeInstanceTemplate_spot_maxRunDuration|TestAccComputeInstanceTemplate_spot_maxRunDuration_deleteTerminationAction|TestAccComputeInstanceTemplate_spot_maxRunDuration_stopTerminationAction|TestAccComputeInstanceTemplate_subnet_auto|TestAccComputeInstanceTemplate_subnet_custom|TestAccComputeInstanceTemplate_with18TbScratchDisk|TestAccComputeInstanceTemplate_withScratchDisk|TestAccComputeInstance_IPv6|TestAccComputeInstance_NetworkAttachmentUpdate|TestAccComputeInstance_NicStackTypeUpdate|TestAccComputeInstance_PTRRecord|TestAccComputeInstance_advancedMachineFeatures|TestAccComputeInstance_attachedDisk|TestAccComputeInstance_attachedDisk_modeRo|TestAccComputeInstance_attachedDisk_sourceUrl|TestAccComputeInstance_basic1|TestAccComputeInstance_bootDisk_mode|TestAccComputeInstance_bootDisk_source|TestAccComputeInstance_bootDisk_sourceUrl|TestAccComputeInstance_confidentialHyperDiskBootDisk|TestAccComputeInstance_deletionProtectionExplicitTrueAndUpdateFalse|TestAccComputeInstance_enableDisplay|TestAccComputeInstance_forceChangeMachineTypeManually|TestAccComputeInstance_guestAccelerator|TestAccComputeInstance_hostname|TestAccComputeInstance_hyperdiskBootDisk_provisioned_iops_throughput|TestAccComputeInstance_internalIPv6|TestAccComputeInstance_ipv6ExternalReservation|TestAccComputeInstance_kmsDiskEncryption|TestAccComputeInstance_localSsdRecoveryTimeout|TestAccComputeInstance_localSsdRecoveryTimeout_update|TestAccComputeInstance_maxRunDuration_update|TestAccComputeInstance_minCpuPlatform|TestAccComputeInstance_multiNic|TestAccComputeInstance_networkTier|TestAccComputeInstance_primaryAliasIpRange|TestAccComputeInstance_queueCount|TestAccComputeInstance_reservationAffinities|TestAccComputeInstance_resourcePolicyCollocate|TestAccComputeInstance_scheduling|TestAccComputeInstance_secondaryAliasIpRange|TestAccComputeInstance_serviceAccount|TestAccComputeInstance_serviceAccount_updated|TestAccComputeInstance_serviceAccount_updated0to1to0scopes|TestAccComputeInstance_shieldedVmConfig|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeInstance_spotVM|TestAccComputeInstance_spotVM_maxRunDuration_deleteTerminationAction|TestAccComputeInstance_spotVM_maxRunDuration_update|TestAccComputeInstance_spotVM_update|TestAccComputeInstance_standardVM_maxRunDuration_deleteTerminationAction|TestAccComputeInstance_standardVM_maxRunDuration_stopTerminationAction|TestAccComputeInstance_stopInstanceToUpdate|TestAccComputeInstance_subnet_auto|TestAccComputeInstance_subnet_custom|TestAccComputeInstance_subnetworkUpdate|TestAccComputeInstance_with375GbScratchDisk|TestAccComputeInterconnectAttachment_interconnectAttachmentDedicatedExample|TestAccComputeInterconnect_computeInterconnectBasicTestExample|TestAccComputeNodeTemplate_nodeTemplateServerBindingExample|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscale [...]

2024-05-29 02:14 UTC, jessdejong commented
/gcbrun

2024-05-29 02:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 03:46 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3142`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccAppEngineFlexibleAppVersion_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubsc [...]

2024-05-29 12:24 UTC, jessdejong commented
Note: Sam Levenick from the Google terraform team has said they will review this PR.

Also, [this PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/10783) also ran into the same issue where the # of affected tests > 500. Fixed when /gcbrun was run.

2024-05-29 12:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 12:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 12:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 12:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 13:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 296 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1723 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 13:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3142`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccAppEngineFlexibleAppVersion_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubsc [...]

2024-05-29 13:31 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3143`
Skipped tests: `373`
Affected tests: `206`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 206 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccRedisIns [...]

2024-05-29 13:31 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3143`
Skipped tests: `373`
Affected tests: `206`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 206 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccRedisIns [...]

2024-05-29 13:32 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3142`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccAppEngineFlexibleAppVersion_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubsc [...]

2024-05-29 13:41 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3142`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrappe [...]

2024-05-29 13:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3143`
Skipped tests: `373`
Affected tests: `206`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 206 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccRedisIns [...]

2024-05-29 13:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3143`
Skipped tests: `373`
Affected tests: `206`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 206 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccRedisIns [...]

2024-05-29 14:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `3722`
Passed tests: `3142`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccProjectIamPolicy_invalidMembers|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscrip [...]

2024-05-29 16:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 303 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1737 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 17:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `3727`
Passed tests: `3148`
Skipped tests: `373`
Affected tests: `206`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 206 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccRedisIns [...]

2024-05-29 17:33 UTC, modular-magician commented
#### Tests analytics
Total tests: `3727`
Passed tests: `3147`
Skipped tests: `373`
Affected tests: `207`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 207 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeSyncAuthorization_update|TestAccAppEngineFlexibleAppVersion_update|TestAccBinaryAuthorizationAttestor_kms|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccCloudAssetOrganizationFeed_cloudAssetOrganizationFeedExample|TestAccCloudAssetProjectFeed_cloudAssetProjectFeedExample|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_dockerRepository|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudFunctionsFunction_serviceAccountEmail|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudIdsEndpoint_basic|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccCloudSchedulerJob_schedulerJobOauthExample|TestAccCloudSchedulerJob_schedulerJobOidcExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey|TestAccComputeTargetPool_basic|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningNetworkTags|TestAccContainerCluster_resourceManagerTags|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withAddons|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withFQDNNetworkPolicy|TestAccContainerCluster_withGcpPublicCidrsAccessEnabledToggle|TestAccContainerCluster_withNodePoolCIA|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withVersion|TestAccContainerCluster_withWorkloadALTSConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_resourceManagerTags|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerNodePool_withReservationAffinitySpecific|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccDataFusionInstance_dataFusionInstanceCmekExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydb|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample|TestAccDatabaseMigrationServicePrivateConnection_databaseMigrationServicePrivateConnectionExample|TestAccDataplexTaskDataplexTask_update|TestAccDataplexTaskIamBindingGenerated|TestAccDataplexTaskIamMemberGenerated|TestAccDataplexTaskIamPolicyGenerated|TestAccDataplexTask_dataplexTaskBasicExample|TestAccDataplexTask_dataplexTaskNotebookExample|TestAccDataplexTask_dataplexTaskSparkExample|TestAccDialogflowCXWebhook_update|TestAccEdgecontainerCluster_edgecontainerClusterExample|TestAccEdgecontainerCluster_edgecontainerClusterWithMaintenanceWindowExample|TestAccEssentialContactsContact_essentialContactExample|TestAccEssentialContactsContact_update|TestAccEventarcChannel_basic|TestAccEventarcChannel_cryptoKeyUpdate|TestAccEventarcGoogleChannelConfig_cryptoKeyUpdate|TestAccEventarcTrigger_HttpDest|TestAccEventarcTrigger_channel|TestAccFirestoreDatabase_firestoreCmekDatabaseExample|TestAccFirestoreDatabase_firestoreCmekDatabaseInDatastoreModeExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccKMSEkmConnection_kmsEkmConnectionBasicExample_update|TestAccKmsCryptoKeyVersion_externalProtectionLevelOptions|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigOrganization_indexConfigs|TestAccLoggingOrganizationSettings_update|TestAccLoggingProjectSink_updatePreservesCustomWriter|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccMemcacheInstance_memcacheInstanceBasicTestExample|TestAccMemcacheInstance_update|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkSecurityGatewaySecurityPolicy_networkSecurityGatewaySecurityPolicyTlsInspectionBasicExample|TestAccNetworkSecurityServerTlsPolicy_networkSecurityServerTlsPolicyMtlsExample|TestAccNetworkSecurityTlsInspectionPolicy_networkSecurityTlsInspectionPolicyBasicExample|TestAccNetworkSecurityTlsInspectionPolicy_update|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccPubsubLiteReservation_pubsubLiteReservationBasicExample|TestAccPubsubLiteSubscription_pubsubLiteSubscriptionBasicExample|TestAccPubsubLiteTopic_pubsubLiteTopicBasicExample|TestAccPubsubSubscriptionBigQuery_update|TestAccPubsubSubscriptionCloudStorage_update|TestAccPubsubSubscription_pubsubSubscriptionPushBqExample|TestAccPubsubSubscription_pubsubSubscriptionPushBqTableSchemaExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageAvroExample|TestAccPubsubSubscription_pubsubSubscriptionPushCloudstorageExample|TestAccPubsubSubscription_push|TestAccPubsubSubscription_pushNoWrapper|TestAccPubsubSubsc [...]

2024-05-29 21:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 304 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1739 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-29 22:48 UTC, modular-magician commented
#### Tests analytics
Total tests: `3728`
Passed tests: `3335`
Skipped tests: `373`
Affected tests: `20`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 20 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withWorkloadALTSConfig|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccTPUNode_tpuNodeBasicExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIEndpointIamBinding|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 23:20 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccTPUNode_tpuNodeBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccTPUNode_tpuNodeBasicExample.log)]
`TestAccVertexAIEndpointIamBinding`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccVertexAIEndpointIamBinding.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposer2Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComposer2Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComposerEnvironment_fixPyPiPackages_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion.log)]
`TestAccContainerCluster_withSandboxConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccContainerCluster_withSandboxConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccContainerCluster_withSandboxConfig.log)]
`TestAccContainerCluster_withWorkloadALTSConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccContainerCluster_withWorkloadALTSConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccContainerCluster_withWorkloadALTSConfig.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccManagedKafkaCluster_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/58a88aa5-3524-484d-8e8d-6c3d8957d92a/build [...]

2024-05-30 03:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 302 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1735 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-30 04:16 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3321`
Skipped tests: `373`
Affected tests: `36`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 36 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApphubWorkload_apphubWorkloadBasicExample|TestAccApphubWorkload_apphubWorkloadFullExample|TestAccApphubWorkload_apphubWorkloadUpdate|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withWorkloadALTSConfig|TestAccDataSourceApphubDiscoveredWorkload_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_versions|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccNetworkServicesLbRouteExtension_networkServicesLbRouteExtensionBasicExample|TestAccNetworkServicesLbRouteExtension_update|TestAccNetworkServicesLbTrafficExtension_networkServicesLbTrafficExtensionBasicExample|TestAccNetworkServicesLbTrafficExtension_update|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_versions|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-30 05:07 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccApphubWorkload_apphubWorkloadBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccApphubWorkload_apphubWorkloadBasicExample.log)]
`TestAccApphubWorkload_apphubWorkloadFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccApphubWorkload_apphubWorkloadFullExample.log)]
`TestAccApphubWorkload_apphubWorkloadUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccApphubWorkload_apphubWorkloadUpdate.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputePerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccDataSourceApphubDiscoveredWorkload_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccDataSourceApphubDiscoveredWorkload_basic.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccInstanceGroupManager_targetSizeZero.log)]
`TestAccInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccInstanceGroupManager_versions.log)]
`TestAccNetworkServicesLbRouteExtension_networkServicesLbRouteExtensionBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccNetworkServicesLbRouteExtension_networkServicesLbRouteExtensionBasicExample.log)]
`TestAccNetworkServicesLbRouteExtension_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccNetworkServicesLbRouteExtension_update.log)]
`TestAccNetworkServicesLbTrafficExtension_networkServicesLbTrafficExtensionBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccNetworkServicesLbTrafficExtension_networkServicesLbTrafficExtensionBasicExample.log)]
`TestAccNetworkServicesLbTrafficExtension_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccNetworkServicesLbTrafficExtension_update.log)]
`TestAccRegionInstanceGroupManager_distributionPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccRegionInstanceGroupManager_distributionPolicy.log)]
`TestAccRegionInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccRegionInstanceGroupManager_resourceManagerTags.log)]
`TestAccRegionInstanceGroupManager_stateful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccRegionInstanceGroupManager_stateful.log)]
`TestAccRegionInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccRegionInstanceGroupManager_targetSizeZero.log)]
`TestAccRegionInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccRegionInstanceGroupManager_versions.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposer2Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComposer2Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComposerEnvironment_fixPyPiPackages_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/917b4a46-836f-458e-ac23-3b2e2879cf85/build-log/recording_build/TestAccComputePerInstanceConfig_removeInstanceOnDestroy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr [...]

2024-05-30 13:07 UTC, slevenick commented
/gcbrun hopefully tests are passing now

2024-05-30 13:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 302 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1735 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-30 14:23 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3339`
Skipped tests: `373`
Affected tests: `18`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 18 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withWorkloadALTSConfig|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccManagedKafkaCluster_update|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-30 15:20 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccManagedKafkaCluster_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccManagedKafkaCluster_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposer2Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComposer2Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComposerEnvironment_fixPyPiPackages_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccContainerCluster_withWorkloadALTSConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccContainerCluster_withWorkloadALTSConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccContainerCluster_withWorkloadALTSConfig.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1ca9c9c4-ca84-49e0-a81a-bc4cf0155d9e/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr- [...]

2024-05-30 18:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 302 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1738 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-30 19:45 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3341`
Skipped tests: `373`
Affected tests: `16`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 16 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeDisk_storagePoolSpecified|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withWorkloadALTSConfig|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterBasicExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-30 20:20 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeDisk_storagePoolSpecified`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComputeDisk_storagePoolSpecified.log)]
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccManagedKafkaCluster_managedkafkaClusterBasicExample.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/replaying_build_after_recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/replaying_after_recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposer2Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComposer2Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComposerEnvironment_fixPyPiPackages_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccContainerCluster_withWorkloadALTSConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccContainerCluster_withWorkloadALTSConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccContainerCluster_withWorkloadALTSConfig.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/5e880dd9-8505-47f1-be2d-027ee6cd9da5/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsO [...]

2024-05-30 21:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 303 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1740 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-30 22:17 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3343`
Skipped tests: `373`
Affected tests: `14`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 14 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccComposer1Environment_withNodeConfig|TestAccComposer2Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withWorkloadALTSConfig|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-30 23:15 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccComposer2Environment_withNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComposer2Environment_withNodeConfig.log)]
`TestAccContainerCluster_withWorkloadALTSConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccContainerCluster_withWorkloadALTSConfig.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/replaying_build_after_recording/TestAccAppEngineFlexibleAppVersion_update_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/replaying_after_recording/TestAccAppEngineFlexibleAppVersion_update.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccComposerEnvironment_fixPyPiPackages_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a67a5653-9df2-478f-8578-2af806ca8d9a/recording) for each test

2024-05-31 02:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 320 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1774 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-31 03:43 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3345`
Skipped tests: `373`
Affected tests: `12`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 03:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 321 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1776 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-31 04:45 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3345`
Skipped tests: `373`
Affected tests: `12`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccComposer1Environment_withNodeConfig|TestAccComposerEnvironment_fixPyPiPackages|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 04:51 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]


$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/replaying_build_after_recording/TestAccAppEngineFlexibleAppVersion_update_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/replaying_after_recording/TestAccAppEngineFlexibleAppVersion_update.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a58f2053-1fed-4585-94b3-bdf2ac0944d0/recording) for each test

2024-05-31 05:47 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccComposerEnvironment_fixPyPiPackages`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccComposerEnvironment_fixPyPiPackages.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/1c5018ac-ce9f-4c0b-bae3-398d39a98f38/recording) for each test

2024-05-31 11:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 321 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1776 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-31 12:53 UTC, modular-magician commented
#### Tests analytics
Total tests: `3730`
Passed tests: `3348`
Skipped tests: `373`
Affected tests: `9`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccComposer1Environment_withNodeConfig|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 13:44 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccAppEngineFlexibleAppVersion_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/6c35a3ac-6a11-4799-98b6-a708c7cfe25f/recording) for each test

2024-05-31 14:02 UTC, slevenick requested changes
CMEK test needs a role granted to the service account that uses the key

2024-05-31 15:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 322 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1778 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-05-31 16:43 UTC, modular-magician commented
#### Tests analytics
Total tests: `3731`
Passed tests: `3350`
Skipped tests: `373`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposer1Environment_withNodeConfig|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccManagedKafkaCluster_managedkafkaClusterCmekExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 17:35 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccManagedKafkaCluster_managedkafkaClusterCmekExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccManagedKafkaCluster_managedkafkaClusterCmekExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComposer1Environment_withNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccComposer1Environment_withNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccComposer1Environment_withNodeConfig.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/c97f06b2-6b59-4416-8c3c-7d4000615f3d/recording) for each test

2024-06-03 14:45 UTC, slevenick reviewed
Couple minor questions, overall looks fine

2024-06-03 14:45 UTC, slevenick commented on mmv1/products/managedkafka/Cluster.yaml
> +                  diff_suppress_func: 'tpgresource.ProjectNumberDiffSuppress'
Do we have an ETA on this being fixed server-side?

2024-06-03 14:45 UTC, slevenick commented on mmv1/templates/terraform/examples/managedkafka_cluster_cmek.tf.erb
> +#resource "google_service_account" "gmk_service_account" {
Remove this if it's not being used

2024-06-03 14:45 UTC, slevenick commented on mmv1/templates/terraform/examples/managedkafka_cluster_cmek.tf.erb
> +    # "serviceAccount:service-${data.google_project.project.number}@gcp-sa-staging-managedkafka.iam.gserviceaccount.com",
Remove if unused

2024-06-03 16:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 303 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1740 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-06-03 17:12 UTC, modular-magician commented
#### Tests analytics
Total tests: `3738`
Passed tests: `3345`
Skipped tests: `376`
Affected tests: `17`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 17 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_webhook_config|TestAccCloudFunctionsFunction_secretEnvVar|TestAccCloudFunctionsFunction_secretMount|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccCloudRunService_secretEnvironmentVariable|TestAccCloudRunService_secretVolume|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator|TestAccIntegrationConnectorsConnection|TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-03 17:50 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAppEngineFlexibleAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccAppEngineFlexibleAppVersion_update.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample.log)]
`TestAccCloudBuildTrigger_webhook_config`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudBuildTrigger_webhook_config.log)]
`TestAccCloudFunctionsFunction_secretEnvVar`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudFunctionsFunction_secretEnvVar.log)]
`TestAccCloudFunctionsFunction_secretMount`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudFunctionsFunction_secretMount.log)]
`TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample.log)]
`TestAccCloudRunService_cloudRunServiceSecretVolumesExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudRunService_cloudRunServiceSecretVolumesExample.log)]
`TestAccCloudRunService_secretEnvironmentVariable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudRunService_secretEnvironmentVariable.log)]
`TestAccCloudRunService_secretVolume`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccCloudRunService_secretVolume.log)]
`TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccIntegrationConnectorsEndpointAttachment_integrationConnectorsEndpointAttachmentExample_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccComputeInstance_guestAccelerator.log)]
`TestAccIntegrationConnectorsConnection`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccIntegrationConnectorsConnection_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccIntegrationConnectorsConnection.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/fc667d7b-4755-4b4f-8333-d1de244280f7/recording) for each test

2024-06-05 16:32 UTC, slevenick commented
/gcbrun hopefully some more of these tests will be fixed. They're unrelated so I'll merge without them all passing

2024-06-05 16:32 UTC, slevenick approved these changes
LGTM!

2024-06-05 16:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10773-old..auto-pr-10773) ( 4 files changed, 303 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10773-old..auto-pr-10773) ( 13 files changed, 1740 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10773-old..auto-pr-10773) ( 1 file changed, 226 insertions(+))

2024-06-05 17:43 UTC, modular-magician commented
#### Tests analytics
Total tests: `3753`
Passed tests: `3339`
Skipped tests: `378`
Affected tests: `36`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 36 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineFlexibleAppVersion_update|TestAccApphubWorkload_apphubWorkloadBasicExample|TestAccApphubWorkload_apphubWorkloadFullExample|TestAccApphubWorkload_apphubWorkloadUpdate|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceGroup_rename|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstanceTemplate_sourceImageEncryptionKey|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccDataSourceApphubDiscoveredWorkload_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_versions|TestAccIntegrationConnectorsConnection|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccNetworkServicesLbRouteExtension_networkServicesLbRouteExtensionBasicExample|TestAccNetworkServicesLbRouteExtension_update|TestAccNetworkServicesLbTrafficExtension_networkServicesLbTrafficExtensionBasicExample|TestAccNetworkServicesLbTrafficExtension_update|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_versions|TestAccTags|TestAccTagsLocationTagBinding_locationTagBindingzonal|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 23:10 UTC, modular-magician commented
#### Tests analytics
Total tests: `3755`
Passed tests: `3370`
Skipped tests: `379`
Affected tests: `6`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Action taken
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccLoggingBucketConfigOrganization_basic|TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample|TestAccTpuV2Vm_tpuV2VmFullExample|TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 23:41 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccLoggingBucketConfigOrganization_basic.log)]
`TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_build/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccLookerInstance_lookerInstanceEnterpriseFullTestExample.log)]
`TestAccTpuV2Vm_tpuV2VmFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_build/TestAccTpuV2Vm_tpuV2VmFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccTpuV2Vm_tpuV2VmFullExample.log)]
`TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_build/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording/TestAccVertexAIFeatureOnlineStore_vertexAiFeatureonlinestoreWithBetaFieldsOptimizedExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10773/artifacts/a989161f-295e-495b-85e1-8d9d2ab731c9/recording) for each test

2024-06-07 13:59 UTC, merged