Add SecretsDiscoveryTarget to DiscoveryConfig.yaml. Add messages for …
GoogleCloudPlatform/magic-modules pull request #10798
Opened 2024-05-25 06:55 UTC by patrickmoy

…single-resource mode to CloudSqlTarget and BigQueryTarget in DiscoveryConfig.yaml. Add update tests.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-05-25 06:59 UTC, patrickmoy commented
/gcbrun

2024-05-25 07:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-25 07:09 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-25 07:10 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d213ff93-9484-4ded-91df-913dbc1c7388/recording) for each test

2024-05-25 07:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 532 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-25 07:12 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:13 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bc7899c2-9f29-4c54-baff-151563e1078b/recording) for each test

2024-05-25 07:13 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:14 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/909bb902-aebf-4259-8360-216cb099042d/recording) for each test

2024-05-25 07:14 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:15 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7aad5dc9-5007-42f9-a339-368358253ae6/recording) for each test

2024-05-25 07:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-25 07:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-25 07:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `58`
Skipped tests: `0`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-25 07:30 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/51d5fbaf-7b47-4904-bd43-0ce59d6bc1b7/recording) for each test

2024-05-25 07:30 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigCloudSqlExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigFilterRegexesAndConditionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgFolderPausedExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/71077c35-dcbc-4a73-ac34-01712a1ec05d/recording) for each test

2024-05-26 00:56 UTC, patrickmoy commented
/gcbrun

2024-05-26 01:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 01:11 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `61`
Skipped tests: `0`
Affected tests: `5`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 01:13 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigBasicExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigConditionsCadenceExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7c48ac3c-842e-4885-a941-a4008871f2c5/recording) for each test

2024-05-26 05:04 UTC, patrickmoy commented
/gcbrun

2024-05-26 05:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 05:22 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `63`
Skipped tests: `0`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 05:24 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/77da4347-767f-4700-9499-3ff61f253d8a/recording) for each test

2024-05-26 05:32 UTC, patrickmoy commented
/gcbrun

2024-05-26 05:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 05:47 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `63`
Skipped tests: `0`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 05:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigOrgRunningExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/b46679df-5d7e-4a33-bb33-033e8fedc637/recording) for each test

2024-05-26 06:00 UTC, patrickmoy commented
/gcbrun

2024-05-26 06:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 06:18 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 06:20 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6fd877fc-8a5e-4d0c-bc9d-6241cc8f6ddb/recording) for each test

2024-05-26 06:21 UTC, patrickmoy commented
/gcbrun

2024-05-26 06:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 06:36 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 06:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/4b20a26d-5bef-418f-ae28-71bb85c837e2/recording) for each test

2024-05-26 06:40 UTC, patrickmoy commented
/gcbrun

2024-05-26 06:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 06:56 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 06:57 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/824a24f6-57d1-4bba-ba68-514165c23886/recording) for each test

2024-05-26 07:04 UTC, patrickmoy commented
/gcbrun

2024-05-26 07:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 07:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 07:23 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/c2d7b88b-58a7-401b-ae3e-38a378c7462c/recording) for each test

2024-05-26 09:23 UTC, patrickmoy commented
/gcbrun

2024-05-26 09:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-26 09:39 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-26 09:41 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5c7d5678-6370-46c3-b15e-5a69ad2f2430/recording) for each test

2024-05-27 02:17 UTC, patrickmoy commented
/gcbrun

2024-05-27 02:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-27 02:32 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-27 02:34 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/74570566-0704-4e96-bde7-da23ed79478f/recording) for each test

2024-05-28 11:15 UTC, patrickmoy commented
/gcbrun

2024-05-28 11:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 11:30 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 11:32 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb34f6e8-795d-4e20-95d1-d8246e84b1df/recording) for each test

2024-05-28 17:54 UTC, patrickmoy commented
/gcbrun

2024-05-28 18:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 530 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 18:10 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 18:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 18:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 18:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 508 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 18:12 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5d4de5f2-1d4e-49a1-aaab-01c0e99f51fd/recording) for each test

2024-05-28 18:15 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 18:15 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 18:16 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 18:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/0b0005ca-c392-40e2-9708-4ff57d3a3880/recording) for each test

2024-05-28 18:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9566744e-b6eb-4f91-8545-eff67434044c/recording) for each test

2024-05-28 18:17 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/bb44551c-053c-45e9-a8c5-d4a93d862358/recording) for each test

2024-05-28 18:37 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/89a07b1f-7c23-4d6d-87b2-c41bcd8d4c1c/recording) for each test

2024-05-28 19:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 511 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 511 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 19:07 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 19:09 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/753a9c19-5496-406b-8c6d-9cb4b4ebedd0/recording) for each test

2024-05-28 19:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 526 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 526 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 19:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 526 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 526 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 19:37 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 19:37 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 19:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/7a934cea-d629-4e2e-98e1-a22f6b3573fa/recording) for each test

2024-05-28 19:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/d0a96ea8-0be1-4f91-9e1a-54dd71254d12/recording) for each test

2024-05-28 19:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 19:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 19:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 19:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 19:45 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/5bfdd452-dd94-410a-a378-44fe487179af/recording) for each test

2024-05-28 19:46 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/cd6e978e-6aca-4528-9e4c-9db7f7286a6c/recording) for each test

2024-05-28 19:47 UTC, patrickmoy commented
/gcbrun

2024-05-28 19:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 3 files changed, 563 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 20:02 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `64`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update|TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 20:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/recording/TestAccDataLossPreventionDiscoveryConfig_dlpDiscoveryConfigActionsExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/880cfce1-72b1-4683-8267-29eb128e8bee/recording) for each test

2024-05-28 20:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 603 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 603 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 20:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 603 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 603 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 20:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/a46155b7-30ec-4530-9723-716e99838178/build-log/replaying_test.log)

2024-05-28 20:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/41e32a57-2914-4242-a451-20cccee579e9/build-log/replaying_test.log)

2024-05-28 20:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 359 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 359 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 20:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 359 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 359 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 20:49 UTC, modular-magician commented
#### Tests analytics
Total tests: `61`
Passed tests: `60`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 20:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `61`
Passed tests: `60`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 20:50 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6f04fba2-e743-454f-9b72-63968cad5eac/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6f04fba2-e743-454f-9b72-63968cad5eac/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6f04fba2-e743-454f-9b72-63968cad5eac/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/6f04fba2-e743-454f-9b72-63968cad5eac/recording) for each test

2024-05-28 20:51 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9eade25d-1831-4573-ad98-8bb14f791ecb/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9eade25d-1831-4573-ad98-8bb14f791ecb/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9eade25d-1831-4573-ad98-8bb14f791ecb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/9eade25d-1831-4573-ad98-8bb14f791ecb/recording) for each test

2024-05-28 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 21:15 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/addc6c1f-826d-4cfc-8d6b-a7d79e8ceb3c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/addc6c1f-826d-4cfc-8d6b-a7d79e8ceb3c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/addc6c1f-826d-4cfc-8d6b-a7d79e8ceb3c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/addc6c1f-826d-4cfc-8d6b-a7d79e8ceb3c/recording) for each test

2024-05-28 21:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ea98132d-27a1-4782-8304-bcc91c22fa91/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ea98132d-27a1-4782-8304-bcc91c22fa91/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ea98132d-27a1-4782-8304-bcc91c22fa91/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ea98132d-27a1-4782-8304-bcc91c22fa91/recording) for each test

2024-05-28 21:16 UTC, patrickmoy commented
/gcbrun

2024-05-28 21:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 21:32 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 21:33 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ce219bf3-bc16-43d3-a141-624474f0be16/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ce219bf3-bc16-43d3-a141-624474f0be16/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ce219bf3-bc16-43d3-a141-624474f0be16/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/ce219bf3-bc16-43d3-a141-624474f0be16/recording) for each test

2024-05-28 21:35 UTC, patrickmoy commented
/gcbrun

2024-05-28 21:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 21:53 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 21:55 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/69b8ac57-a4f5-4962-80e3-3d1f198f130f/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/69b8ac57-a4f5-4962-80e3-3d1f198f130f/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/69b8ac57-a4f5-4962-80e3-3d1f198f130f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/69b8ac57-a4f5-4962-80e3-3d1f198f130f/recording) for each test

2024-05-28 23:06 UTC, patrickmoy commented
/gcbrun

2024-05-28 23:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 23:22 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 23:24 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/55aed39a-1eda-4d0c-be37-337b9d81196c/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/55aed39a-1eda-4d0c-be37-337b9d81196c/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/55aed39a-1eda-4d0c-be37-337b9d81196c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/55aed39a-1eda-4d0c-be37-337b9d81196c/recording) for each test

2024-05-28 23:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-28 23:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-28 23:45 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/eac81e68-2855-4e30-829f-6e8821ba8f1a/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/eac81e68-2855-4e30-829f-6e8821ba8f1a/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/eac81e68-2855-4e30-829f-6e8821ba8f1a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/eac81e68-2855-4e30-829f-6e8821ba8f1a/recording) for each test

2024-05-29 00:16 UTC, patrickmoy commented
/gcbrun

2024-05-29 00:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 563 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-29 00:47 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/522c3d62-6c33-40f6-ba3d-877ecb350c7e/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/522c3d62-6c33-40f6-ba3d-877ecb350c7e/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/522c3d62-6c33-40f6-ba3d-877ecb350c7e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/522c3d62-6c33-40f6-ba3d-877ecb350c7e/recording) for each test

2024-05-29 01:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 570 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 570 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-29 01:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 01:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `59`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDiscoveryConfig_Update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 01:46 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/31265786-f901-458b-a421-583390aa6df5/build-log/recording_build/TestAccDataLossPreventionDiscoveryConfig_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/31265786-f901-458b-a421-583390aa6df5/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/31265786-f901-458b-a421-583390aa6df5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/31265786-f901-458b-a421-583390aa6df5/recording) for each test

2024-05-29 02:00 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/19d47c8e-96d9-49a4-b14d-3a4af03fef65/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/19d47c8e-96d9-49a4-b14d-3a4af03fef65/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/19d47c8e-96d9-49a4-b14d-3a4af03fef65/recording) for each test

2024-05-29 02:05 UTC, patrickmoy commented
Commits squashed into one; tests are passing now.

2024-05-29 02:10 UTC, patrickmoy commented
/gcbrun

2024-05-29 02:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 570 insertions(+), 468 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10798-old..auto-pr-10798) ( 4 files changed, 570 insertions(+), 468 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10798-old..auto-pr-10798) ( 1 file changed, 126 insertions(+))

2024-05-29 02:25 UTC, modular-magician commented
#### Tests analytics
Total tests: `60`
Passed tests: `60`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10798/artifacts/de6f941b-7aaa-4a37-b843-45fa6524b06e/build-log/replaying_test.log)

2024-05-29 22:01 UTC, NickElliot requested changes
LGTM for new changes -- but we need to have the old tests replicated on a non-parallel area for adequate coverage if that is causing problems with the new update tests. For example, the previous `dlp_discovery_config_actions` testing the `actions{}` block, a new test needs to exist so as to cover all of the scenarios covered within the previous examples (not necessarily a new handwritten test for all of them, but all fields need to be in a test).

2024-05-29 22:36 UTC, patrickmoy commented
I believe all of the example fields are covered in update tests, since when I originally wrote the first set of update tests, I based them off of examples (starting with a basic barebones config, and then updating to the example). 

Does that suffice?

2024-06-04 22:31 UTC, NickElliot approved these changes
Sorry about that, LGTM! Had some of the pages of diffs vs existing files mixed up.

2024-06-04 22:31 UTC, merged