Add support for preventDrift field in ConfigManagement Fleet-level default config
GoogleCloudPlatform/magic-modules pull request #10809
Opened 2024-05-28 16:59 UTC by rramkumar1

**Release Note Template for Downstream PRs (will be copied)**

```release-note:
gkehub: added `prevent_drift` field to ConfigManagement `fleet_default_member_config
```
](release-note:enhancement)

2024-05-28 18:09 UTC, melinath requested changes
Please add this field to tests: https://googlecloudplatform.github.io/magic-modules/develop/test/test/

2024-05-29 23:50 UTC, rramkumar1 commented
> Please add this field to tests: https://googlecloudplatform.github.io/magic-modules/develop/test/test/

Done

2024-05-30 22:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10809-old..auto-pr-10809) ( 3 files changed, 27 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10809-old..auto-pr-10809) ( 3 files changed, 27 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10809-old..auto-pr-10809) ( 1 file changed, 11 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (38 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        prevent_drift = # value needed
      }
    }
  }
}

```

2024-05-30 22:44 UTC, modular-magician commented
#### Tests analytics
Total tests: `23`
Passed tests: `13`
Skipped tests: `10`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>gkehub2</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10809/artifacts/96cb45b4-02a6-4f93-a051-16de3200c558/build-log/replaying_test.log)

2024-05-31 23:01 UTC, melinath requested changes
Note to self: I'll need to manually run the test for this after it's fixed since it skips VCR.

2024-05-31 23:01 UTC, melinath commented on mmv1/third_party/terraform/services/gkehub2/resource_gke_hub_feature_test.go.erb
>        config_sync {
This should be inside config_sync (which is why you're getting an alert about missing tests).

 ```suggestion
      config_sync {
        prevent_drift = true
```

2024-06-04 22:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10809-old..auto-pr-10809) ( 3 files changed, 28 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10809-old..auto-pr-10809) ( 3 files changed, 28 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10809-old..auto-pr-10809) ( 1 file changed, 11 insertions(+))

2024-06-04 22:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `23`
Passed tests: `13`
Skipped tests: `10`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>gkehub2</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10809/artifacts/59bb69c8-b0b1-4bb9-bbec-0b29e997aeb9/build-log/replaying_test.log)

2024-06-04 22:56 UTC, melinath commented
manual test run: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_BETA_MMUPSTREAMTESTS_GOOGLEBETA_PACKAGE_GKEHUB2/160266?hideProblemsFromDependencies=false&hideTestsFromDependencies=false

2024-06-05 15:45 UTC, melinath approved these changes
Manual tests passed - LGTM

2024-06-05 15:45 UTC, merged