Removed required tag on maxFindingsPerInfoType.infoType
GoogleCloudPlatform/magic-modules pull request #10818
Opened 2024-05-29 05:15 UTC by patrickmoy

```release-note:bug
dlp: fixed  `google_data_loss_prevention_inspect_template`  not allowing "default" per_info_type limit
```

2024-05-29 05:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))

2024-05-29 05:32 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `66`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/3e8600a8-f787-4b95-a3d5-2c2143be5be6/build-log/replaying_test.log)

2024-05-29 17:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))

2024-05-29 17:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `66`
Passed tests: `66`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/0a84352b-1b4f-481d-8c3c-580b02c49519/build-log/replaying_test.log)

2024-05-29 18:10 UTC, slevenick requested changes
Can you add a test that doesn't specify this field just so we can make sure it all works as expected?

2024-05-29 21:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 2 files changed, 7 insertions(+), 7 deletions(-))

2024-05-29 22:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))

2024-05-29 22:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))

2024-05-29 22:48 UTC, modular-magician commented
#### Tests analytics
Total tests: `67`
Passed tests: `66`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 22:49 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/228f8255-2d10-4273-a066-cb93c390ab9a/build-log/recording_build/TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/228f8255-2d10-4273-a066-cb93c390ab9a/recording/TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/228f8255-2d10-4273-a066-cb93c390ab9a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/228f8255-2d10-4273-a066-cb93c390ab9a/recording) for each test

2024-05-29 22:49 UTC, modular-magician commented
#### Tests analytics
Total tests: `67`
Passed tests: `66`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 22:49 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/cc8fa889-7794-4b81-b213-93d2f207d0cb/build-log/recording_build/TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/cc8fa889-7794-4b81-b213-93d2f207d0cb/recording/TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/cc8fa889-7794-4b81-b213-93d2f207d0cb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/cc8fa889-7794-4b81-b213-93d2f207d0cb/recording) for each test

2024-05-29 23:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))

2024-05-29 23:05 UTC, modular-magician commented
#### Tests analytics
Total tests: `67`
Passed tests: `66`
Skipped tests: `0`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-29 23:05 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/56518674-aa44-422c-84c1-c29c679a2e64/recording/TestAccDataLossPreventionInspectTemplate_dlpInspectTemplateMaxInfotypePerFindingDefaultExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/56518674-aa44-422c-84c1-c29c679a2e64/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/56518674-aa44-422c-84c1-c29c679a2e64/recording) for each test

2024-05-29 23:06 UTC, patrickmoy commented
/gcbrun

2024-05-29 23:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10818-old..auto-pr-10818) ( 3 files changed, 87 insertions(+), 7 deletions(-))

2024-05-29 23:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `67`
Passed tests: `67`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>datalossprevention</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10818/artifacts/abb3b8ed-bf96-40ba-be36-6337240575e5/build-log/replaying_test.log)

2024-05-30 21:05 UTC, patrickmoy commented
Added test that excludes the formerly required field

2024-05-31 14:04 UTC, slevenick approved these changes

2024-05-31 14:05 UTC, merged