Add support secret manager csi addon in beta
GoogleCloudPlatform/magic-modules pull request #10841
Opened 2024-05-31 04:30 UTC by dargudear-google

Added a new field `secret_manager_config` to `google_container_cluster` in resource for `terraform-provider-google-beta`

This field provides secret manager gke add on.

**Release Note Template for Downstream PRs (will be copied)**

```
container(beta): added `secret_manager_config` field to `google_container_cluster` resource
```

2024-05-31 04:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10841-old..auto-pr-10841) ( 2 files changed, 173 insertions(+))

2024-05-31 04:47 UTC, modular-magician commented
#### Tests analytics
Total tests: `198`
Passed tests: `185`
Skipped tests: `10`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withSecretManagerConfig|TestAccContainerCluster_withWorkloadALTSConfig </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 05:09 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerCluster_withWorkloadALTSConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/recording/TestAccContainerCluster_withWorkloadALTSConfig.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/build-log/recording_build/TestAccContainerCluster_withAutopilotResourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccContainerCluster_withSecretManagerConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/build-log/recording_build/TestAccContainerCluster_withSecretManagerConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/recording/TestAccContainerCluster_withSecretManagerConfig.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/a6a1b865-12da-4530-b5ea-8c9175a535dc/recording) for each test

2024-05-31 05:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10841-old..auto-pr-10841) ( 2 files changed, 174 insertions(+))

2024-05-31 05:36 UTC, modular-magician commented
#### Tests analytics
Total tests: `198`
Passed tests: `186`
Skipped tests: `10`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withAutopilotResourceManagerTags|TestAccContainerCluster_withSecretManagerConfig </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-31 06:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerCluster_withAutopilotResourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/c2cddb6f-d793-4432-ab56-5ac66d2366be/recording/TestAccContainerCluster_withAutopilotResourceManagerTags.log)]
`TestAccContainerCluster_withSecretManagerConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/c2cddb6f-d793-4432-ab56-5ac66d2366be/recording/TestAccContainerCluster_withSecretManagerConfig.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/c2cddb6f-d793-4432-ab56-5ac66d2366be/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/c2cddb6f-d793-4432-ab56-5ac66d2366be/recording) for each test

2024-06-03 13:40 UTC, c2thorn requested changes
looks good except needs documentation added https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

2024-06-03 13:57 UTC, dargudear-google commented
> looks good except needs documentation added https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

Thanks, Added the documentation.

2024-06-03 14:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10841-old..auto-pr-10841) ( 1 file changed, 8 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10841-old..auto-pr-10841) ( 3 files changed, 182 insertions(+))

2024-06-03 14:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10841-old..auto-pr-10841) ( 1 file changed, 8 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10841-old..auto-pr-10841) ( 3 files changed, 182 insertions(+))

2024-06-03 14:12 UTC, modular-magician commented
#### Tests analytics
Total tests: `198`
Passed tests: `188`
Skipped tests: `10`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/e242b4c0-b4e4-425b-875d-d7ca2deff479/build-log/replaying_test.log)

2024-06-03 14:18 UTC, modular-magician commented
#### Tests analytics
Total tests: `198`
Passed tests: `188`
Skipped tests: `10`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>container</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10841/artifacts/289a18b7-135a-46ea-93fe-f19528e96669/build-log/replaying_test.log)

2024-06-03 18:35 UTC, c2thorn approved these changes

2024-06-03 18:35 UTC, merged