Remove validation for guest OS feature types
GoogleCloudPlatform/magic-modules pull request #10856
Opened 2024-06-03 09:45 UTC by shruthi019

Remove validation for guest_os_features enum values and let the API handle it.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-06-04 13:24 UTC, slevenick requested changes
You'll also need to change the type of this field from:
        - !ruby/object:Api::Type::Enum
to
        - !ruby/object:Api::Type::String

2024-06-05 06:16 UTC, shruthi019 commented
Done.

2024-06-05 06:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10856-old..auto-pr-10856) ( 2 files changed, 4 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10856-old..auto-pr-10856) ( 2 files changed, 4 insertions(+), 7 deletions(-))

2024-06-05 06:41 UTC, modular-magician commented
#### Tests analytics
Total tests: `952`
Passed tests: `876`
Skipped tests: `74`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 07:12 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10856/artifacts/39d270d7-fd92-46ba-9f77-bd6a4b21a5b4/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10856/artifacts/39d270d7-fd92-46ba-9f77-bd6a4b21a5b4/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10856/artifacts/39d270d7-fd92-46ba-9f77-bd6a4b21a5b4/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10856/artifacts/39d270d7-fd92-46ba-9f77-bd6a4b21a5b4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10856/artifacts/39d270d7-fd92-46ba-9f77-bd6a4b21a5b4/recording) for each test

2024-06-05 16:17 UTC, slevenick approved these changes

2024-06-05 16:17 UTC, merged