Unset operation when reading instance_group_manager resource
GoogleCloudPlatform/magic-modules pull request #10859
Opened 2024-06-03 14:30 UTC by askubis

This is intended to fix #16043
It is reverting a change done by refactoring in https://github.com/hashicorp/terraform-provider-google-beta/commit/79e0a2e37e138ec8ade75ac726e3de4dc9adfc88#diff-1cf6fdb65a48539ac4730b8920d0366d3a173b7e824b08502d3c3da73456d8f8

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
fix issue when resource_compute_instance_group_manager with pending operation was removed due to operation not present in the backend anymore.
```

2024-06-03 14:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10859-old..auto-pr-10859) ( 1 file changed, 2 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10859-old..auto-pr-10859) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2024-06-03 14:57 UTC, modular-magician commented
#### Tests analytics
Total tests: `940`
Passed tests: `866`
Skipped tests: `72`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeInstance_guestAccelerator </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-03 15:29 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeInstance_guestAccelerator`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/build-log/recording_build/TestAccComputeInstance_guestAccelerator_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/recording/TestAccComputeInstance_guestAccelerator.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/2b2160f6-4051-44be-a17e-de0b56b61459/recording) for each test

2024-06-05 13:44 UTC, c2thorn requested changes
I cannot find the context for this change. Is there a better link? The current one links to a seemingly random commit that is very large.

Also, is this related to a Github issue in https://github.com/hashicorp/terraform-provider-google/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc ?

2024-06-05 14:25 UTC, askubis commented
> I cannot find the context for this change. Is there a better link? The current one links to a seemingly random commit that is very large.
> 
> Also, is this related to a Github issue in https://github.com/hashicorp/terraform-provider-google/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc ?

the context is https://github.com/hashicorp/terraform-provider-google/issues/16043

what the commit is mentioning is  google-beta/resource_compute_instance_group_manager.go
```
-               d.Set("operation", "")
+		if err := d.Set("operation", op.Name); err != nil {
+			return fmt.Errorf("Error setting operation: %s", err)
+		}
```

which seems to be a copy-paste error, as the previous change in the same file is correct:
```
-			d.Set("operation", op.Name)
+			if err := d.Set("operation", op.Name); err != nil {
+				return fmt.Errorf("Error setting operation: %s", err)
+			}
```

2024-06-05 14:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10859-old..auto-pr-10859) ( 1 file changed, 2 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10859-old..auto-pr-10859) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2024-06-05 14:59 UTC, modular-magician commented
#### Tests analytics
Total tests: `952`
Passed tests: `877`
Skipped tests: `74`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 15:31 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/cb5d6b89-a4db-461a-a3e0-210dc6137846/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/cb5d6b89-a4db-461a-a3e0-210dc6137846/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/cb5d6b89-a4db-461a-a3e0-210dc6137846/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10859/artifacts/cb5d6b89-a4db-461a-a3e0-210dc6137846/recording) for each test

2024-06-10 16:29 UTC, c2thorn commented
> hashicorp/terraform-provider-google#16043

I see, thank you.

2024-06-10 16:32 UTC, c2thorn approved these changes

2024-06-10 16:32 UTC, merged