Fix test for the NEG AppEngine
GoogleCloudPlatform/magic-modules pull request #10866
Opened 2024-06-04 08:59 UTC by Cheriit

Fix a TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample test
https://github.com/hashicorp/terraform-provider-google/issues/16170

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-06-04 09:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 139 insertions(+), 31 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 139 insertions(+), 31 deletions(-))

2024-06-04 09:25 UTC, modular-magician commented
#### Tests analytics
Total tests: `948`
Passed tests: `814`
Skipped tests: `72`
Affected tests: `62`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 62 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate|TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample|TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputePerInstanceConfig_removeInstanceOnDestroy|TestAccComputePerInstanceConfig_statefulIps|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendInternalManaged|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccComputeRegionPerInstanceConfig_statefulIps|TestAccComputeRegionPerInstanceConfig_update|TestAccDataSourceGoogleComputeInstanceGroupManager|TestAccDataSourceGoogleComputeInstanceGroup_fromIGM|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_resourceManagerTags|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_stoppedSuspendedTargetSize|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_APISideListRecordering|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_resourceManagerTags|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_stoppedSuspendedTargetSize|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_versions </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-04 09:57 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeBackendService_withBackend`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeBackendService_withBackend.log)]
`TestAccComputeBackendService_withBackendAndIAP`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeBackendService_withBackendAndIAP.log)]
`TestAccComputeBackendService_withBackendAndMaxUtilization`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeBackendService_withBackendAndMaxUtilization.log)]
`TestAccComputeBackendService_withMaxConnections`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeBackendService_withMaxConnections.log)]
`TestAccComputeBackendService_withMaxConnectionsPerInstance`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeBackendService_withMaxConnectionsPerInstance.log)]
`TestAccComputeForwardingRule_forwardingRuleHttpLbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeForwardingRule_forwardingRuleHttpLbExample.log)]
`TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample.log)]
`TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate.log)]
`TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample.log)]
`TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample.log)]
`TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeGlobalForwardingRule_globalInternalHttpLbWithMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccComputePerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputePerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputePerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputePerInstanceConfig_statefulIps.log)]
`TestAccComputePerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputePerInstanceConfig_update.log)]
`TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionBackendService_regionBackendServiceBalancingModeExample.log)]
`TestAccComputeRegionBackendService_withBackendInternal`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionBackendService_withBackendInternal.log)]
`TestAccComputeRegionBackendService_withBackendInternalManaged`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionBackendService_withBackendInternalManaged.log)]
`TestAccComputeRegionBackendService_withBackendMultiNic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionBackendService_withBackendMultiNic.log)]
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputeRegionPerInstanceConfig_statefulIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionPerInstanceConfig_statefulIps.log)]
`TestAccComputeRegionPerInstanceConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccComputeRegionPerInstanceConfig_update.log)]
`TestAccDataSourceGoogleComputeInstanceGroup_fromIGM`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccDataSourceGoogleComputeInstanceGroup_fromIGM.log)]
`TestAccInstanceGroupManager_resourceManagerTags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccInstanceGroupManager_resourceManagerTags.log)]
`TestAccInstanceGroupManager_stoppedSuspendedTargetSize`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccInstanceGroupManager_stoppedSuspendedTargetSize.log)]
`TestAccInstanceGroupManager_targetSizeZero`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876e2/recording/TestAccInstanceGroupManager_targetSizeZero.log)]
`TestAccInstanceGroupManager_versions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/3e88f905-b7c5-4c27-81a4-29d05a9876 [...]

2024-06-04 11:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 139 insertions(+), 31 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 139 insertions(+), 31 deletions(-))

2024-06-04 11:49 UTC, modular-magician commented
#### Tests analytics
Total tests: `948`
Passed tests: `850`
Skipped tests: `72`
Affected tests: `26`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 26 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccDataSourceGoogleComputeInstanceGroupManager|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-04 12:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 129 insertions(+), 31 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 129 insertions(+), 31 deletions(-))

2024-06-04 13:09 UTC, modular-magician commented
#### Tests analytics
Total tests: `948`
Passed tests: `851`
Skipped tests: `72`
Affected tests: `25`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 25 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccDataSourceGoogleComputeInstanceGroupManager|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-04 13:35 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_autoscalerBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_autoscalerSingleInstanceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_multicondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_scaleDownControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_scaleInControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_scaleInControlFixed_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_scalingSchedule_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeAutoscaler_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionAutoscaler_scaleDownControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionAutoscaler_scaleDownControl.log)]
`TestAccComputeRegionAutoscaler_scaleInControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionAutoscaler_scaleInControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionAutoscaler_scaleInControl.log)]
`TestAccComputeRegionAutoscaler_scalingSchedule`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionAutoscaler_scalingSchedule_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionAutoscaler_scalingSchedule.log)]
`TestAccComputeRegionAutoscaler_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionAutoscaler_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionAutoscaler_update.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]
`TestAccDataSourceGoogleComputeInstanceGroupManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recording_build/TestAccDataSourceGoogleComputeInstanceGroupManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/recording/TestAccDataSourceGoogleComputeInstanceGroupManager.log)]
`TestAccInstanceGroupManager_autoHealingPolicies`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/f20ef638-f128-429b-8a76-d4a4cda187af/build-log/recor [...]

2024-06-04 14:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 127 insertions(+), 31 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 127 insertions(+), 31 deletions(-))

2024-06-04 14:47 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_autoscalerBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_autoscalerSingleInstanceExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_multicondition_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_scaleDownControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_scaleInControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_scaleInControlFixed_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_scalingSchedule_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeAutoscaler_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionAutoscaler_scaleDownControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionAutoscaler_scaleDownControl.log)]
`TestAccComputeRegionAutoscaler_scaleInControl`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionAutoscaler_scaleInControl_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionAutoscaler_scaleInControl.log)]
`TestAccComputeRegionAutoscaler_scalingSchedule`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionAutoscaler_scalingSchedule_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionAutoscaler_scalingSchedule.log)]
`TestAccComputeRegionAutoscaler_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionAutoscaler_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionAutoscaler_update.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]
`TestAccDataSourceGoogleComputeInstanceGroupManager`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recording_build/TestAccDataSourceGoogleComputeInstanceGroupManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/recording/TestAccDataSourceGoogleComputeInstanceGroupManager.log)]
`TestAccInstanceGroupManager_autoHealingPolicies`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/5e284f23-a361-4962-8e47-3ca712765054/build-log/recor [...]

2024-06-04 15:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 125 insertions(+), 33 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 125 insertions(+), 33 deletions(-))

2024-06-04 15:21 UTC, modular-magician commented
#### Tests analytics
Total tests: `948`
Passed tests: `851`
Skipped tests: `72`
Affected tests: `25`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 25 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeAutoscaler_multicondition|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_scaleInControl|TestAccComputeAutoscaler_scaleInControlFixed|TestAccComputeAutoscaler_scalingSchedule|TestAccComputeAutoscaler_update|TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccDataSourceGoogleComputeInstanceGroupManager|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_self_link_unique|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_waitForStatus|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-04 15:51 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeAutoscaler_autoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_autoscalerBasicExample.log)]
`TestAccComputeAutoscaler_autoscalerSingleInstanceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_autoscalerSingleInstanceExample.log)]
`TestAccComputeAutoscaler_multicondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_multicondition.log)]
`TestAccComputeAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_scaleDownControl.log)]
`TestAccComputeAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_scaleInControl.log)]
`TestAccComputeAutoscaler_scaleInControlFixed`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_scaleInControlFixed.log)]
`TestAccComputeAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_scalingSchedule.log)]
`TestAccComputeAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeAutoscaler_update.log)]
`TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample.log)]
`TestAccComputeRegionAutoscaler_scaleDownControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionAutoscaler_scaleDownControl.log)]
`TestAccComputeRegionAutoscaler_scaleInControl`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionAutoscaler_scaleInControl.log)]
`TestAccComputeRegionAutoscaler_scalingSchedule`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionAutoscaler_scalingSchedule.log)]
`TestAccComputeRegionAutoscaler_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionAutoscaler_update.log)]
`TestAccDataSourceGoogleComputeInstanceGroupManager`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccDataSourceGoogleComputeInstanceGroupManager.log)]
`TestAccInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_autoHealingPolicies.log)]
`TestAccInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_basic.log)]
`TestAccInstanceGroupManager_self_link_unique`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_self_link_unique.log)]
`TestAccInstanceGroupManager_stateful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_stateful.log)]
`TestAccInstanceGroupManager_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_update.log)]
`TestAccInstanceGroupManager_waitForStatus`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccInstanceGroupManager_waitForStatus.log)]
`TestAccRegionInstanceGroupManager_autoHealingPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccRegionInstanceGroupManager_autoHealingPolicies.log)]
`TestAccRegionInstanceGroupManager_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccRegionInstanceGroupManager_basic.log)]
`TestAccRegionInstanceGroupManager_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccRegionInstanceGroupManager_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/8db0e409-c27d-4910-9d29-2550e3684d5c/recording) for each test

2024-06-05 07:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 133 insertions(+), 31 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 133 insertions(+), 31 deletions(-))

2024-06-05 07:42 UTC, modular-magician commented
#### Tests analytics
Total tests: `952`
Passed tests: `875`
Skipped tests: `74`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-05 08:10 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/09678269-db3b-4c49-bf44-5d83cb0a2039/recording) for each test

2024-06-06 21:48 UTC, NickElliot reviewed
The test is failing it seems due to the inability to delete the `google_app_engine_flexible_app_version` because it is the last instance of a `default` service, and I'm not sure there is a way around that due to the new version of this test creating a new project. Would it be possible to still use the default CI project for this testing?

2024-06-07 07:56 UTC, Cheriit commented
@NickElliot unfortunately, according to the `google_app_engine_application` documentation "App Engine applications cannot be deleted once they're created; you have to delete the entire project to delete the application. Terraform will report the application has been successfully deleted; this is a limitation of Terraform, and will go away in the future. Terraform is not able to delete App Engine applications."

To test this it looks like we have to create a separate project to clear it :(

Test previously failed because of the API change with the buckets, but after resolving this issue, the one with app engine has appeared. 

I'll try to add `delete_service_on_destroy` to the `google_app_engine_flexible_app_version`. Mabye it will work

2024-06-07 08:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 131 insertions(+), 29 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10866-old..auto-pr-10866) ( 2 files changed, 131 insertions(+), 29 deletions(-))

2024-06-07 08:29 UTC, modular-magician commented
#### Tests analytics
Total tests: `955`
Passed tests: `879`
Skipped tests: `74`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-07 08:58 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/7cbed1e8-f69c-4708-ab33-d29bae18884c/recording) for each test

2024-06-10 16:36 UTC, NickElliot commented
I'm thinking the approach will need to be adding a bootstrap function, so a separate app version with the same service is made in the new project agnostic of the ongoing test. I'll link some examples soon

2024-06-17 18:28 UTC, NickElliot requested changes
I looked into various things around this but this might be a simple fix

2024-06-17 18:28 UTC, NickElliot commented on mmv1/templates/terraform/examples/region_network_endpoint_group_appengine.tf.erb
>    delete_service_on_destroy = true
```suggestion
  delete_service_on_destroy = false
```
try setting this!

2024-06-18 08:33 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `884`
Skipped tests: `74`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-18 09:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10866/artifacts/e1d39cc3-73ff-4d70-bafd-d6cfef3a0c27/recording) for each test

2024-06-24 16:53 UTC, NickElliot requested changes
Ok, the following will need to be done:

1. Move the test to be handwritten
2. Add two bootstrap functions to the test:
*  one using [BootstrapProject](https://github.com/GoogleCloudPlatform/magic-modules/blob/def52fed28327b8f3e14c1894aeb21cba08da598/mmv1/third_party/terraform/acctest/bootstrap_test_utils.go#L625) 
* the other using a new bootstrap function you will need to implement for `google_app_engine_flexible_app_version` that will create a seperate version of the resource in the bootstrapped project. 
3. the test will need to be updated to then use a project data source that refers to the bootstrapped project.

Here's an example of a handwritten test using a bootstrap function: https://github.com/GoogleCloudPlatform/magic-modules/blob/70941b698762c42f979bcf5ab24c70e85dc1992e/mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go#L182

Let me know if you have any questions along the way!

2024-09-06 19:35 UTC, rileykarson commented
Hey! I'm closing this PR as a part of a cleanup of older inactive PRs, using a threshold of PRs in "Draft" last updated over a month ago. This doesn't represent rejection of the change, and feel free to comment for me to reopen it if you plan to pick it back up, or feel free to start a new PR with the same changes in the future.

2024-09-06 19:35 UTC, closed without merging