Breaking change - Add integration for subnetworks with internal ranges API
GoogleCloudPlatform/magic-modules pull request #10897
Opened 2024-06-06 18:13 UTC by daanheikens

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/17881

Second attempt, superseding: https://github.com/GoogleCloudPlatform/magic-modules/pull/10507

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added fields `reserved_internal_range` and `secondary_ip_ranges[].reserved_internal_range` to `google_compute_subnetwork` resource
```

2024-06-06 18:14 UTC, daanheikens commented
@trodge FYI! As discussed on: https://github.com/hashicorp/terraform-provider-google/issues/18300

@c2thorn +1 for visibility

2024-06-10 16:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10897-old..auto-pr-10897) ( 3 files changed, 189 insertions(+), 32 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10897-old..auto-pr-10897) ( 3 files changed, 319 insertions(+), 35 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10897-old..auto-pr-10897) ( 1 file changed, 21 insertions(+))

2024-06-10 16:33 UTC, modular-magician commented
#### Tests analytics
Total tests: `958`
Passed tests: `881`
Skipped tests: `74`
Affected tests: `3`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeSubnetwork_subnetworkReservedInternalRangeExample|TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-10 17:03 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/recording/TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccComputeSubnetwork_subnetworkReservedInternalRangeExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/build-log/recording_build/TestAccComputeSubnetwork_subnetworkReservedInternalRangeExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/recording/TestAccComputeSubnetwork_subnetworkReservedInternalRangeExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/5d6cc3b6-b5d2-4a0c-86a6-7a2c18a6d953/recording) for each test

2024-06-13 14:41 UTC, roaks3 commented
@trodge passing this one to you, since it looks like you did the initial review. I'm not adding `disable-review-reminders` since you may want to take a look first, but otherwise it seems like we could add it here to keep the notifications quiet.

2024-07-24 19:33 UTC, c2thorn commented
I've updated the base branch to point to the major release branch. This should be good to continue.

I've forgotten what the exact breaking change is here - but please follow the [steps here](https://github.com/GoogleCloudPlatform/magic-modules/pull/11237#issuecomment-2246331651) to edit the upgrade guide so User's know how to handle the breaking change.

@daanheikens @trodge

2024-07-26 06:35 UTC, daanheikens commented
> I've updated the base branch to point to the major release branch. This should be good to continue.
> 
> I've forgotten what the exact breaking change is here - but please follow the [steps here](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/make-a-breaking-change/#make-the-change-on-feature-branch-major-release-600) to edit the upgrade guide so User's know how to handle the breaking change.
> 
> @daanheikens @trodge

Thank you @c2thorn, the issue was that one of the fields was treated required while it was optional. See also: https://github.com/GoogleCloudPlatform/magic-modules/pull/10697

If I recall correctly, it was related to this issue:  https://github.com/hashicorp/terraform-provider-google/issues/18115 where @rileykarson explains the issue in detail. I am not sure if it's already fixed in this major release, if not, we indeed have to update the documentation and add more tests I think?

Happy to hear your advice.

2024-07-26 14:34 UTC, c2thorn commented
@daanheikens Thanks for the information. As I now understand, this is a breaking change due to the parent field having [schema_config_mode_attr](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/compute/Subnetwork.yaml#L210).

I planned on testing the effect of [removing schema_config_mode_attr](https://github.com/hashicorp/terraform-provider-google/issues/12824) as part of 6.0, but have not gotten to it yet.

With schema_config_mode_attr, adding this new field is a breaking change because it becomes required.
Without schema_config_mode_attr, this should not be a breaking change, but it is unclear if removing schema_config_mode_attr itself is a breaking change. If you are interested in testing this out yourself as part of this PR that would be helpful, but otherwise I will have to report back in a few weeks after I've had time to test.

Assuming schema_config_mode_attr is removed outside of this PR, this will no longer be a breaking change and not need the associated breaking change documentation.

2024-08-02 20:58 UTC, trodge commented
Removing `schema_config_mode_attr` would be a breaking change in that a config could produce this error:
```
  error=
  | exit status 1
  | 
  | Error: Unsupported argument
  | 
  |   on terraform_plugin_test.tf line 12, in resource "google_compute_subnetwork" "network-with-private-secondary-ip-ranges":
  |   12:   secondary_ip_range = []
  | 
  | An argument named "secondary_ip_range" is not expected here. Did you mean to
  | define a block of type "secondary_ip_range"?
  ```
  
  If the user is attempting to use the current recommended method of specifying an empty block in order to remove secondary ip ranges from their config. (This being the workaround Riley mentions in https://github.com/hashicorp/terraform-provider-google/issues/12824 )
  
 If we're no longer concerned about maintaining 0.12 -> 0.13 forwards compatibility in the 6.0 version of the provider, could we remove `schema_config_mode_attr` and all tests/docs mentioning the `[]` syntax?

2024-08-06 18:30 UTC, daanheikens commented
> Removing `schema_config_mode_attr` would be a breaking change in that a config could produce this error:
> 
> ```
>   error=
>   | exit status 1
>   | 
>   | Error: Unsupported argument
>   | 
>   |   on terraform_plugin_test.tf line 12, in resource "google_compute_subnetwork" "network-with-private-secondary-ip-ranges":
>   |   12:   secondary_ip_range = []
>   | 
>   | An argument named "secondary_ip_range" is not expected here. Did you mean to
>   | define a block of type "secondary_ip_range"?
> ```
> 
> If the user is attempting to use the current recommended method of specifying an empty block in order to remove secondary ip ranges from their config. (This being the workaround Riley mentions in [hashicorp/terraform-provider-google#12824](https://github.com/hashicorp/terraform-provider-google/issues/12824) )
> 
> If we're no longer concerned about maintaining 0.12 -> 0.13 forwards compatibility in the 6.0 version of the provider, could we remove `schema_config_mode_attr` and all tests/docs mentioning the `[]` syntax?

@trodge @c2thorn I can try some variations here and write some tests/examples with `schema_config_mode_attr` removed if you are OK with that? Could you please guide me a bit in where I can start? Let me know, happy to help.

2024-08-06 19:07 UTC, c2thorn commented
> @trodge @c2thorn I can try some variations here and write some tests/examples with `schema_config_mode_attr` removed if you are OK with that? Could you please guide me a bit in where I can start? Let me know, happy to help.

I plan to get to testing other fields this week, but if you have time to start with this field, that would be helpful. With removing  `schema_config_mode_attr`, we'd essentially just need to manually verify if it is possible to remove the field `secondary_ip_ranges` or not. I don't think there is a specific test that needs to be added to MMv1, what do you think @trodge

2024-08-06 21:10 UTC, trodge commented
> > @trodge @c2thorn I can try some variations here and write some tests/examples with `schema_config_mode_attr` removed if you are OK with that? Could you please guide me a bit in where I can start? Let me know, happy to help.
> 
> I plan to get to testing other fields this week, but if you have time to start with this field, that would be helpful. With removing `schema_config_mode_attr`, we'd essentially just need to manually verify if it is possible to remove the field `secondary_ip_ranges` or not. I don't think there is a specific test that needs to be added to MMv1, what do you think @trodge

We have a test already that removes secondary ip ranges using `secondary_ip_range = []` syntax. That would need to be updated to whatever the new syntax is along with the documentation.

2024-08-08 22:05 UTC, c2thorn commented
Just updating that I'm getting to this now and should hopefully have an update tomorrow on the effect of removing `schema_config_mode_attr` and how to handle emptying fields without it.

2024-08-09 11:36 UTC, c2thorn commented
After looking into this, this PR can be merged without removing `schema_config_mode_attr` from `secondaryIpRange`

I plan to remove `schema_config_mode_attr` separately after adding a 5.X workaround with https://github.com/GoogleCloudPlatform/magic-modules/pull/11410 

So once that's done this should not be a breaking change, but it does need to go into the 6.0 branch.

2024-08-09 15:10 UTC, daanheikens commented
> After looking into this, this PR can be merged without removing `schema_config_mode_attr` from `secondaryIpRange`
> 
> 
> 
> I plan to remove `schema_config_mode_attr` separately after adding a 5.X workaround with https://github.com/GoogleCloudPlatform/magic-modules/pull/11410 
> 
> 
> 
> So once that's done this should not be a breaking change, but it does need to go into the 6.0 branch.

Ah great news @c2thorn. I do see the VCR test is still failing, anything we need to do for that?

2024-08-09 16:46 UTC, c2thorn commented
> Ah great news @c2thorn. I do see the VCR test is still failing, anything we need to do for that?

yes it looks like the error for `TestAccComputeSubnetwork_subnetworkReservedInternalRangeExample` is real
```
        Error: "name" ("") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
        
          with google_compute_network.default,
          on terraform_plugin_test.tf line 12, in resource "google_compute_network" "default":
          12:   name                    = ""
```
@trodge

2024-08-12 14:57 UTC, trodge requested changes
This should fix the test error @c2thorn mentioned.

2024-08-12 14:57 UTC, trodge commented on mmv1/products/compute/Subnetwork.yaml
> +      subnetwork_name: 'subnetwork-reserved-internal-range'
```suggestion
      subnetwork_name: 'subnetwork-reserved-internal-range'
      network_name: 'network-reserved-internal-range'
```

2024-08-13 11:59 UTC, daanheikens commented
> This should fix the test error @c2thorn mentioned.

Applied the suggestions!

2024-08-13 16:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10897-old..auto-pr-10897) ( 3 files changed, 189 insertions(+), 32 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10897-old..auto-pr-10897) ( 3 files changed, 319 insertions(+), 35 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10897-old..auto-pr-10897) ( 1 file changed, 21 insertions(+))

2024-08-13 17:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 981
Passed tests: 909
Skipped tests: 72
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10897/artifacts/1aed8190-897d-4dfb-9fcb-9cb7f21953b1/build-log/replaying_test.log)

2024-08-15 20:11 UTC, trodge approved these changes

2024-08-15 20:12 UTC, merged