feat(billingbudget): support project level recicipients on budgets
GoogleCloudPlatform/magic-modules pull request #10926
Opened 2024-06-10 12:26 UTC by renescheepers

Support for setting the project level recipients: https://cloud.google.com/billing/docs/reference/budget/rest/v1beta1/billingAccounts.budgets#allupdatesrule. 

FIXES https://github.com/hashicorp/terraform-provider-google/issues/18182

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Support setting project level recicipients on billing budgets
```

2024-06-11 19:39 UTC, c2thorn requested changes

2024-06-11 19:39 UTC, c2thorn commented on mmv1/products/billingbudget/Budget.yaml
> +      - 'notificationsRule.enableProjectLevelRecipients'
Can you add a test (or add to an existing test) where the new field updates? https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/billing/resource_billing_budget_test.go

2024-06-11 19:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10926-old..auto-pr-10926) ( 2 files changed, 36 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10926-old..auto-pr-10926) ( 2 files changed, 36 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10926-old..auto-pr-10926) ( 1 file changed, 11 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_billing_budget` (16 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_billing_budget" "primary" {
  all_updates_rule {
    enable_project_level_recipients = # value needed
  }
}


```

2024-06-11 19:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `15`
Passed tests: `13`
Skipped tests: `1`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>billing</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBillingBudget_billingBudgetUpdate </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-11 19:53 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccBillingBudget_billingBudgetUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/dc91bb5e-be78-4aab-b06c-124fb0667a0a/recording/TestAccBillingBudget_billingBudgetUpdate.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/dc91bb5e-be78-4aab-b06c-124fb0667a0a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/dc91bb5e-be78-4aab-b06c-124fb0667a0a/recording) for each test

2024-06-12 16:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10926-old..auto-pr-10926) ( 3 files changed, 124 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10926-old..auto-pr-10926) ( 3 files changed, 124 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10926-old..auto-pr-10926) ( 1 file changed, 11 insertions(+))

2024-06-12 16:15 UTC, modular-magician commented
#### Tests analytics
Total tests: `16`
Passed tests: `14`
Skipped tests: `1`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>billing</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-12 16:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/2619d2dd-23cf-4f9c-bb7f-60f56f3653cf/build-log/recording_build/TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/2619d2dd-23cf-4f9c-bb7f-60f56f3653cf/recording/TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/2619d2dd-23cf-4f9c-bb7f-60f56f3653cf/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/2619d2dd-23cf-4f9c-bb7f-60f56f3653cf/recording) for each test

2024-06-12 16:51 UTC, c2thorn requested changes
```
    vcr_utils.go:152: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: Missing required argument
        
          with google_billing_budget.budget,
          on terraform_plugin_test.tf line 24, in resource "google_billing_budget" "budget":
          24:   all_updates_rule {
        
        "all_updates_rule.0.monitoring_notification_channels": one of
        `all_updates_rule.0.monitoring_notification_channels,all_updates_rule.0.pubsub_topic`
        must be specified
        
        Error: Missing required argument
        
          with google_billing_budget.budget,
          on terraform_plugin_test.tf line 24, in resource "google_billing_budget" "budget":
          24:   all_updates_rule {
        
        "all_updates_rule.0.pubsub_topic": one of
        `all_updates_rule.0.monitoring_notification_channels,all_updates_rule.0.pubsub_topic`
        must be specified
```

2024-06-13 14:28 UTC, renescheepers commented
I can't properly test this on my personal account and don't really want to run these tests against a real billing account. \

<img width="528" alt="image" src="https://github.com/GoogleCloudPlatform/magic-modules/assets/38879286/848e7f23-d495-414a-9bd1-505e65f3ce5d">

When running a test I haven't touched:
<img width="457" alt="image" src="https://github.com/GoogleCloudPlatform/magic-modules/assets/38879286/4fc66db5-2105-4f78-a519-33ab9d2639ee">

2024-06-13 17:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10926-old..auto-pr-10926) ( 3 files changed, 126 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10926-old..auto-pr-10926) ( 3 files changed, 126 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10926-old..auto-pr-10926) ( 1 file changed, 11 insertions(+))

2024-06-13 17:36 UTC, modular-magician commented
#### Tests analytics
Total tests: `16`
Passed tests: `14`
Skipped tests: `1`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>billing</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-13 17:37 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/6e2b625c-3e7f-43e6-83aa-28cba0c49f9f/recording/TestAccBillingBudget_billingBudgetNotifyProjectRecipientExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/6e2b625c-3e7f-43e6-83aa-28cba0c49f9f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10926/artifacts/6e2b625c-3e7f-43e6-83aa-28cba0c49f9f/recording) for each test

2024-06-13 18:28 UTC, c2thorn approved these changes
LGTM, thank you for the contribution

2024-06-13 18:28 UTC, merged