add redis self service update support
GoogleCloudPlatform/magic-modules pull request #10922
Opened 2024-06-07 23:43 UTC by yangspirit

add redis self service update support

**Release Note Template for Downstream PRs (will be copied)**

```release-note:
add redis self service update support
```

2024-06-10 15:54 UTC, slevenick requested changes
Can you add a test that sets and then updates this field?

2024-06-12 05:13 UTC, yangspirit reviewed
Add selfservice update test

2024-06-12 15:11 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `18`
Skipped tests: `0`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>redis</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccRedisInstance_selfServiceUpdate|TestAccRedisInstance_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-12 15:33 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccRedisInstance_selfServiceUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10922/artifacts/783b3da3-16de-4894-8918-3056fb6c3fe3/recording/TestAccRedisInstance_selfServiceUpdate.log)]
`TestAccRedisInstance_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10922/artifacts/783b3da3-16de-4894-8918-3056fb6c3fe3/recording/TestAccRedisInstance_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10922/artifacts/783b3da3-16de-4894-8918-3056fb6c3fe3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10922/artifacts/783b3da3-16de-4894-8918-3056fb6c3fe3/recording) for each test

2024-06-12 15:50 UTC, slevenick requested changes
Lint is failling with:
gofmt needs running on the following files:
./google-beta/services/redis/resource_redis_instance_test.go
You can use the command: `make fmt` to reformat code.

You'll need to get those changes into the magic-modules repo as you can't run the make fmt command there

2024-06-12 19:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10922-old..auto-pr-10922) ( 3 files changed, 91 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10922-old..auto-pr-10922) ( 3 files changed, 91 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10922-old..auto-pr-10922) ( 1 file changed, 10 insertions(+))

2024-06-12 19:03 UTC, modular-magician commented
#### Tests analytics
Total tests: `20`
Passed tests: `20`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>redis</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10922/artifacts/21d132fa-0eb7-42db-b298-1d0e03aea363/build-log/replaying_test.log)

2024-06-12 21:13 UTC, slevenick approved these changes

2024-06-12 21:14 UTC, merged