Add tlsEarlyData support to TargetHttpsProxy.
GoogleCloudPlatform/magic-modules pull request #10954
Opened 2024-06-12 20:05 UTC by wu-bin

Fixes https://github.com/hashicorp/terraform-provider-google/issues/18421

Tests that I run:
```
make testacc TEST=./google/services/compute TESTARGS='-run=TestAccComputeTargetHttpsProxy_'
```

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `tlsEarlyData` field to `google_compute_target_https_proxy ` resource.
```

2024-06-12 20:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10954-old..auto-pr-10954) ( 1 file changed, 10 insertions(+))

2024-06-12 20:34 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `878`
Skipped tests: `74`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample|TestAccComputeTargetHttpsProxy_certificateMap|TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample|TestAccComputeTargetHttpsProxy_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-12 20:59 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample.log)]
`TestAccComputeTargetHttpsProxy_certificateMap`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_certificateMap.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeTargetHttpsProxy_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/d43669bd-4ed5-4193-b7fa-6491766971db/recording) for each test

2024-06-12 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10954-old..auto-pr-10954) ( 2 files changed, 11 insertions(+))

2024-06-12 21:26 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `885`
Skipped tests: `74`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-12 21:51 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/c4cca4c4-d2f8-4813-84e7-e1420fd71fc2/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/c4cca4c4-d2f8-4813-84e7-e1420fd71fc2/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/c4cca4c4-d2f8-4813-84e7-e1420fd71fc2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/c4cca4c4-d2f8-4813-84e7-e1420fd71fc2/recording) for each test

2024-06-17 16:24 UTC, NickElliot commented
/gcbrun

2024-06-17 16:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 38 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10954-old..auto-pr-10954) ( 2 files changed, 11 insertions(+))

2024-06-17 16:51 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `885`
Skipped tests: `74`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-17 21:27 UTC, NickElliot approved these changes
test failure is unrelated and persistent in nightly -- LGTM

2024-06-17 21:32 UTC, NickElliot requested changes
wait realized one thing, sorry about that

2024-06-19 12:00 UTC, Yashpandey4 commented on mmv1/products/compute/TargetHttpsProxy.yaml
> +    default_value: :DISABLED
Ack, I can confirm that the server side default is automatically set to DISABLED. Using `default_from_api: true` makes sense here

2024-06-20 14:26 UTC, wu-bin commented on mmv1/products/compute/TargetHttpsProxy.yaml
> +    default_value: :DISABLED
Thank you both! Changed to `default_from_api: true`.

2024-06-20 14:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 37 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 37 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10954-old..auto-pr-10954) ( 2 files changed, 11 insertions(+))

2024-06-20 14:53 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `878`
Skipped tests: `74`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample|TestAccComputeTargetHttpsProxy_certificateMap|TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample|TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample|TestAccComputeTargetHttpsProxy_update </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-20 15:26 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample.log)]
`TestAccComputeTargetHttpsProxy_certificateMap`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_certificateMap.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyBasicExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyCertificateManagerCertificateExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyMtlsExample.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeTargetHttpsProxy_update.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/2062e1c3-c3a8-4e94-ba08-0395cc89aa8a/recording) for each test

2024-06-21 14:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 37 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10954-old..auto-pr-10954) ( 3 files changed, 37 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10954-old..auto-pr-10954) ( 1 file changed, 10 insertions(+))

2024-06-21 14:22 UTC, modular-magician commented
#### Tests analytics
Total tests: `960`
Passed tests: `886`
Skipped tests: `73`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>


#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-21 14:50 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/68e6bd39-0a44-4afe-8d3b-40328f6817ae/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/68e6bd39-0a44-4afe-8d3b-40328f6817ae/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/68e6bd39-0a44-4afe-8d3b-40328f6817ae/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-10954/artifacts/68e6bd39-0a44-4afe-8d3b-40328f6817ae/recording) for each test

2024-06-21 18:14 UTC, NickElliot approved these changes
LGTM :)

2024-06-21 18:14 UTC, merged

2024-06-21 18:16 UTC, wu-bin commented
Thank you, @NickElliot !