Add  Custom Error Responses support to UrlMap
GoogleCloudPlatform/magic-modules pull request #10985
Opened 2024-06-17 19:26 UTC by pradeepcrao

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-06-21 18:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-10985-old..auto-pr-10985) ( 1 file changed, 146 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-10985-old..auto-pr-10985) ( 2 files changed, 984 insertions(+), 25 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-10985-old..auto-pr-10985) ( 1 file changed, 339 insertions(+))



## Errors

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-21 18:27 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-10985/artifacts/dc611775-cf4f-44cf-9eb9-25e74f0f1f05/build-log/replaying_test.log)

2024-06-24 21:25 UTC, NickElliot requested changes
Can you rename the fields with duplicate names and use the `api_name` attribute to provide their actual names? e.g. 
```
properties:
      - !ruby/object:Api::Type::Array
        name: 'defaultCustomErrorResponseRules'
        description: Specifies the rules to match the error response. Rules defined
          for specific HTTP error status codes have higher precedence over rules defined
          for HTTP status code classes.
        required: true
        item_type: !ruby/object:Api::Type::NestedObject
        api_name: errorResponseRules
```

2024-06-28 13:00 UTC, pradeepcrao commented
This PR is now obsolete as the required changes were merged in #10787

2024-06-28 13:00 UTC, closed without merging