move multi-network to GA
GoogleCloudPlatform/magic-modules pull request #11062
Opened 2024-06-26 23:27 UTC by kkuchima

This PR is to add terraform support for Multi-network GA on GKE cluster.

The Multi-network in Terraform beta was added to the magic module in the PR #8385.  
This PR basically moves the `enable_multi_networking` field in `google_container_cluster` and `additional_node_network_configs` `additional_pod_network_configs` fields in `google_container_node_pool` to GA.  

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
container: added multi-NIC network for GKE cluster and node pool.
```

2024-07-01 20:54 UTC, NickElliot requested changes
could you resolve the conflicts? thanks!

2024-07-01 23:33 UTC, kkuchima commented
@NickElliot Thanks, resolved the conflicts.

2024-07-02 16:58 UTC, NickElliot commented
/gcbrun

2024-07-02 20:14 UTC, NickElliot commented
/gcbrun

2024-07-08 16:28 UTC, NickElliot requested changes
The error is an unexpected `<% end %>` tag, make sure you remove all the corresponding ends for each removed `unless` tag!

2024-07-09 01:56 UTC, marblejenka commented on mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.erb
> -<% end -%>
Should this line be deleted? The following log suggests that the `end` matching is not correct.

```
2024-07-03 05:20:27.234 JST
Step #11 - "tpgb-head": I, [2024-07-02T20:20:18.269515 #170] INFO -- : Compiling common files for terraform
2024-07-03 05:20:27.234 JST
Step #11 - "tpgb-head": #<Thread:0x00007f01c81a7590 /mm-terraform-beta-head/mmv1/provider/terraform.rb:189 run> terminated with exception (report_on_exception is true):
2024-07-03 05:20:27.234 JST
Step #11 - "tpgb-head": /usr/local/lib/ruby/3.1.0/erb.rb:905:in `eval': (erb):11083: syntax error, unexpected end-of-input, expecting `end' (SyntaxError)

2024-07-23 21:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11062-old..auto-pr-11062) ( 6 files changed, 361 insertions(+), 9 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11062-old..auto-pr-11062) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2024-07-24 21:35 UTC, NickElliot approved these changes
LGTM!

2024-07-24 21:35 UTC, merged

2024-07-25 00:57 UTC, kkuchima commented
@NickElliot @marblejenka Thanks for your help!