Bigtable: add data_boost_isolation_read_only support for the Data Boost feature.
GoogleCloudPlatform/magic-modules pull request #11138
Opened 2024-07-10 21:54 UTC by djyau

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-07-10 22:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 211 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 211 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-10 22:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 0
Skipped tests: 45
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/dd4e6048-83b4-465b-81f5-7059d354ef69/build-log/replaying_test.log)

2024-07-11 15:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 225 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 225 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-11 15:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 0
Skipped tests: 45
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/27b809d9-ab9e-42a9-bce6-9a76f04287dc/build-log/replaying_test.log)

2024-07-11 18:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 259 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 259 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-11 19:01 UTC, modular-magician commented
#### Tests analytics
Total tests: 46
Passed tests: 0
Skipped tests: 46
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateDataBoostToStandardIsolation
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/dbcc1d05-ac10-4d4a-aff4-1f41576de4ba/build-log/replaying_test.log)

2024-07-11 19:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 259 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 259 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-11 19:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 46
Passed tests: 0
Skipped tests: 46
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateDataBoostToStandardIsolation
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/11991d6c-ce20-4464-9337-eadb98debc7f/build-log/replaying_test.log)

2024-07-12 14:31 UTC, djyau commented on mmv1/templates/terraform/pre_update/bigtable_app_profile.go.erb
> +if hasStandardIsolation && hasDataBoostIsolationReadOnly {
I think it makes sense. IE: If the user specifies Data Boost, we go with Data Boost.

Both will be present if first the user previously did NOT specify either, in which case the API returns `standardIsolation` and stores that in state. Second, the user must then try to update to `dataBoostIsolationReadOnly`. In this case, it makes sense to go with Data Boost.

Both will be present also if first the user explicitly DID set `standardIsolation`, and then later tried to update to `dataBoostIsolationReadOnly`, in which case I think it still makes sense to go with Data Boost.

Do you have other thoughts?

2024-07-12 14:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 234 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 234 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-12 14:44 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 0
Skipped tests: 45
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/fcb7de8e-7a91-403f-b6ad-7d337f71ac2b/build-log/replaying_test.log)

2024-07-12 14:46 UTC, ron-gal approved these changes

2024-07-17 19:44 UTC, NickElliot requested changes
need snake case for these!

2024-07-17 19:44 UTC, NickElliot commented on mmv1/products/bigtable/AppProfile.yaml
> +      - standardIsolation
```suggestion
      - standard_isolation
```

2024-07-17 19:44 UTC, NickElliot commented on mmv1/products/bigtable/AppProfile.yaml
> +      - dataBoostIsolationReadOnly
```suggestion
      - data_boost_isolation_read_only
```

2024-07-18 14:26 UTC, djyau commented on mmv1/products/bigtable/AppProfile.yaml
> +      - standardIsolation
Done!

2024-07-18 14:27 UTC, djyau commented on mmv1/products/bigtable/AppProfile.yaml
> +      - dataBoostIsolationReadOnly
Done!

2024-07-18 14:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 234 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11138-old..auto-pr-11138) ( 3 files changed, 234 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11138-old..auto-pr-11138) ( 1 file changed, 29 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigtable_app_profile` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigtable_app_profile" "primary" {
  data_boost_isolation_read_only {
    compute_billing_owner = # value needed
  }
}


```

2024-07-18 14:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 0
Skipped tests: 45
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigtable</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccBigtableAppProfile_updateStandardIsolationToDataBoost
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11138/artifacts/9d5a10a6-85d7-4e5d-95d3-78cc27bfc631/build-log/replaying_test.log)

2024-07-19 20:25 UTC, NickElliot reviewed
Can you send me a test debug log of running `TestAccBigtableAppProfile_updateStandardIsolationToDataBoost` locally? I want to verify these conflicts/priority behavior are functioning as expected.

2024-07-22 15:07 UTC, djyau commented
> Can you send me a test debug log of running `TestAccBigtableAppProfile_updateStandardIsolationToDataBoost` locally? I want to verify these conflicts/priority behavior are functioning as expected.

Here you are:

https://paste.googleplex.com/6216190261460992

2024-07-23 20:36 UTC, NickElliot approved these changes
LGTM!

2024-07-23 20:36 UTC, merged