Terraform Support for Secret Manager CSI addon GA Version
GoogleCloudPlatform/magic-modules pull request #11142
Opened 2024-07-11 09:22 UTC by riddhi-google

Added a new field ```secret_manager_config``` to ```google_container_cluster``` in resource for ```terraform-provider-google```

**Release Note Template for Downstream PRs (will be copied)**

```release-note:
container: added `secret_manager_config` field to `google_container_cluster` resource (GA).

```

2024-07-16 03:39 UTC, riddhi-google commented
@NickElliot please review this, thanks

2024-07-18 17:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11142-old..auto-pr-11142) ( 3 files changed, 180 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11142-old..auto-pr-11142) ( 2 files changed, 7 insertions(+), 5 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-07-18 17:37 UTC, NickElliot requested changes
The build is failing due to not having syntax errors resolved. Please locally build and test the resource to resolve these. Thanks!

2024-07-18 17:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 198
Passed tests: 188
Skipped tests: 10
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccContainerCluster_withSecretManagerConfig
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11142/artifacts/4ad131be-fdcd-4b3f-a34b-d9a9950bef27/build-log/replaying_test.log)

2024-08-29 09:41 UTC, closed without merging