Use the correct custom import for fields.
GoogleCloudPlatform/magic-modules pull request #11173
Opened 2024-07-16 04:30 UTC by pcostell

Use the correct custom import for fields.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/17313.

Verified with a local `terraform import` followed by `terraform plan`.

```release-note:bug
firestore: fixed missing import of `field` for `google_firestore_field`.
```

2024-07-16 04:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11173-old..auto-pr-11173) ( 1 file changed, 19 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11173-old..auto-pr-11173) ( 1 file changed, 19 insertions(+), 16 deletions(-))

2024-07-16 04:46 UTC, modular-magician commented
#### Tests analytics
Total tests: 20
Passed tests: 20
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>firestore</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11173/artifacts/b3538306-3a56-40d9-a22a-3446c02c3685/build-log/replaying_test.log)

2024-07-16 15:50 UTC, roaks3 requested changes
My main concern is just that this wasn't caught with the tests, and it looks like we are using `ImportStateVerifyIgnore` to ignore fields like `field`. Would you mind removing the `ImportStateVerifyIgnore` line from the handwritten tests, so that this case is covered? Since you set these fields during import, we don't need to ignore them.

2024-07-18 03:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11173-old..auto-pr-11173) ( 2 files changed, 28 insertions(+), 28 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11173-old..auto-pr-11173) ( 2 files changed, 28 insertions(+), 28 deletions(-))

2024-07-18 03:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 20
Passed tests: 20
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>firestore</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11173/artifacts/3c6e2238-b97a-4c8e-a669-6c8832edab9a/build-log/replaying_test.log)

2024-07-18 16:02 UTC, pcostell commented
ImportVerify sections removed, thanks @roaks3 for pointing those out!

2024-07-18 17:23 UTC, merged