Allow server_tls_policy property of compute_target_https_proxy to use update verb
GoogleCloudPlatform/magic-modules pull request #11198
Opened 2024-07-18 17:36 UTC by aanogueira

This PR updates the `compute_target_https_proxy` resource to allow the `server_tls_policy` property to use the `PATCH` verb for updates. This change is necessary to enable more flexible and efficient updates to the `server_tls_policy` configuration without needing to replace the entire resource.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
The `google_compute_target_https_proxy` resource now supports using the `PATCH` verb for updates to the `server_tls_policy` property. This allows for more efficient updates without needing to replace the entire resource.
```

2024-07-18 20:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11198-old..auto-pr-11198) ( 1 file changed, 50 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11198-old..auto-pr-11198) ( 1 file changed, 50 insertions(+), 1 deletion(-))

2024-07-18 20:27 UTC, modular-magician commented
#### Tests analytics
Total tests: 971
Passed tests: 897
Skipped tests: 74
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/1803d870-8c29-47d0-8d68-2bbea7b10933/build-log/replaying_test.log)

2024-07-19 21:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11198-old..auto-pr-11198) ( 1 file changed, 50 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11198-old..auto-pr-11198) ( 1 file changed, 50 insertions(+), 1 deletion(-))

2024-07-19 21:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 971
Passed tests: 896
Skipped tests: 74
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeDisk_storagePoolSpecified</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-19 21:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeDisk_storagePoolSpecified`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/a94712ce-6a45-4a47-8225-f0a1dba76a07/recording/TestAccComputeDisk_storagePoolSpecified.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/a94712ce-6a45-4a47-8225-f0a1dba76a07/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/a94712ce-6a45-4a47-8225-f0a1dba76a07/recording) for each test

2024-07-22 22:19 UTC, trodge requested changes
Could you also add this field to the update test in mmv1/third_party/terraform/services/compute/resource_compute_target_https_proxy_test.go.erb ?

2024-07-23 17:18 UTC, aanogueira commented
I've added the test for the `TestAccComputeTargetHttpsProxy_update`.

2024-07-23 19:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11198-old..auto-pr-11198) ( 2 files changed, 100 insertions(+), 17 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11198-old..auto-pr-11198) ( 2 files changed, 100 insertions(+), 17 deletions(-))

2024-07-23 19:24 UTC, modular-magician commented
#### Tests analytics
Total tests: 974
Passed tests: 898
Skipped tests: 74
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstance_bootDisk_storagePoolSpecified</li>
<li>TestAccComputeTargetHttpsProxy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-23 19:28 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_bootDisk_storagePoolSpecified`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/1515abfc-febf-44f5-a685-04676c3a299c/recording/TestAccComputeInstance_bootDisk_storagePoolSpecified.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/1515abfc-febf-44f5-a685-04676c3a299c/recording/TestAccComputeTargetHttpsProxy_update.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/1515abfc-febf-44f5-a685-04676c3a299c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11198/artifacts/1515abfc-febf-44f5-a685-04676c3a299c/recording) for each test

2024-08-05 23:54 UTC, trodge approved these changes

2024-08-05 23:54 UTC, merged