Add Sql Server Timezone Update Support
GoogleCloudPlatform/magic-modules pull request #11202
Opened 2024-07-18 21:14 UTC by stameishiGoogle

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-07-25 16:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 69 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 69 insertions(+))

2024-07-25 16:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 95
Passed tests: 80
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlDatabaseInstance_SqlServerTimezone</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-25 16:48 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccSqlDatabaseInstance_SqlServerTimezone`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/5386a8c4-7c0c-478d-b482-d3de19ad9d0c/recording/TestAccSqlDatabaseInstance_SqlServerTimezone.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/5386a8c4-7c0c-478d-b482-d3de19ad9d0c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/5386a8c4-7c0c-478d-b482-d3de19ad9d0c/recording) for each test

2024-07-25 20:13 UTC, shuyama1 requested changes

2024-07-25 20:13 UTC, shuyama1 commented on mmv1/third_party/terraform/services/sql/resource_sql_database_instance.go.erb
> +        // Check if timezone is updated.
We'll need to remove `ForceNew: true` from `time_zone`, otherwise, Terraform will always delete/recreate the resource if `time_zone` is changed.

2024-07-25 20:13 UTC, shuyama1 commented on mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go
> +func TestAccSqlDatabaseInstance_SqlServerTimezone(t *testing.T) {
This test only checks the creation/deletion of the resource. https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test should cover more details on update tests. Please let me know if you have any questions adding the tests

2024-07-30 19:55 UTC, shuyama1 requested changes
Thanks for the update. Would you mind rebasing your PR to resolve the merge conflicts and add an update test for the field? See https://github.com/GoogleCloudPlatform/magic-modules/pull/11202#discussion_r1692060444 for update test details. Thank you!

2024-07-31 00:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 106 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 106 insertions(+), 1 deletion(-))

2024-07-31 00:55 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccSqlDatabaseInstance_SqlServerTimezone`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/8b800f06-1f78-4e85-8399-a714e05ee6a2/recording/TestAccSqlDatabaseInstance_SqlServerTimezone.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccSqlServerTimezone_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/8b800f06-1f78-4e85-8399-a714e05ee6a2/build-log/recording_build/TestAccSqlServerTimezone_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/8b800f06-1f78-4e85-8399-a714e05ee6a2/recording/TestAccSqlServerTimezone_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/8b800f06-1f78-4e85-8399-a714e05ee6a2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/8b800f06-1f78-4e85-8399-a714e05ee6a2/recording) for each test

2024-07-31 15:55 UTC, shuyama1 reviewed
The VCR test failed with error:
```
 vcr_utils.go:152: Step 3/4 error: Error running apply: exit status 1
        
        Error: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Time zone cannot be changed after an instance is created., invalid
        
          with google_sql_database_instance.instance,
          on terraform_plugin_test.tf line 2, in resource "google_sql_database_instance" "instance":
           2: resource "google_sql_database_instance" "instance" {
```
Do you happen to know if in-place update is fully supported for the `time_zone` now?

The unit tests failed at lint checks. Details at https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/10171954004/job/28133790678?pr=11202

Please let me know if you need help with debugging the issues.

2024-07-31 16:19 UTC, shuyama1 commented
@stameishiGoogle from you GH account name, I assume that you're a googler. If so, you can follow the [internal instruction](http://go/terraform-contribution-guide#before-you-begin) to get your account registered so that the tests will get triggered automatically for your PR for faster feedback.

2024-08-06 18:38 UTC, stameishiGoogle commented
Followed the internal instructions to register my account with the Google organization - Also ran gofmt on resource_sql_database_instance_test.go

In place update is not yet fully supported. These changes are currently being worked on

2024-08-06 18:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))

2024-08-06 18:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 98
Passed tests: 83
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlServerTimezone_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-06 18:58 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccSqlServerTimezone_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/a342cb09-acdf-4799-8d8d-18e74841ed12/build-log/recording_build/TestAccSqlServerTimezone_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/a342cb09-acdf-4799-8d8d-18e74841ed12/recording/TestAccSqlServerTimezone_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/a342cb09-acdf-4799-8d8d-18e74841ed12/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/a342cb09-acdf-4799-8d8d-18e74841ed12/recording) for each test

2024-08-09 07:14 UTC, shuyama1 reviewed
Thanks @stameishiGoogle for the update. LGTM overall. We'll need to wait until the feature's fully supported to get the test passed and then get the PR merged after. Please ping me when the feature is released. Thank you!

2024-08-28 19:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))

2024-08-28 19:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 98
Passed tests: 82
Skipped tests: 14
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlDatabaseInstance_SqlServerTimezone</li>
<li>TestAccSqlServerTimezone_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 19:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccSqlDatabaseInstance_SqlServerTimezone`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/c917a18e-effc-4c8e-9bcf-7b765c017ed6/recording/TestAccSqlDatabaseInstance_SqlServerTimezone.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccSqlServerTimezone_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/c917a18e-effc-4c8e-9bcf-7b765c017ed6/build-log/recording_build/TestAccSqlServerTimezone_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/c917a18e-effc-4c8e-9bcf-7b765c017ed6/recording/TestAccSqlServerTimezone_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/c917a18e-effc-4c8e-9bcf-7b765c017ed6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/c917a18e-effc-4c8e-9bcf-7b765c017ed6/recording) for each test

2024-09-02 04:42 UTC, shuyama1 reviewed
adding `disable-review-reminders` as the feature is not fully rolled out yet

2024-09-24 21:21 UTC, c2thorn commented
Hi @stameishiGoogle 

Tomorrow, the Magic Modules repository is scheduled to undergo a language migration from Ruby to Go. You can view more details about this in our announcement here: https://github.com/hashicorp/terraform-provider-google/issues/19583 (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)

This open pull request may become incompatible due to most YAML and .erb files converting to Go-compatible files.

Our team (Magic Modules repository maintainers) has tooling to automatically convert changes to the new language, and we can prepare a new commit for this pull request that is compatible with the migration.

In order to push the new changes to your pull request, we would need to <ins>force push the commit to your fork's branch</ins>. Our tooling saves a backup branch before converting, so we could rollback or open a new pull request if needed. We would also work with you and the PR reviewer in the event additional changes are needed.

You also have the option to update the pull request yourself after the migration. You can view a [preview branch](https://github.com/GoogleCloudPlatform/magic-modules/tree/FEATURE-BRANCH-rewrite-switchover-preview) and [updated documentation](https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/) related to the migration changes.

We will take no action until we have your explicit permission to push changes to your fork's branch used for this pull request. Let me or your reviewer know if you have any further questions!

2024-09-24 22:23 UTC, stameishiGoogle commented
> Hi @stameishiGoogle
> 
> Tomorrow, the Magic Modules repository is scheduled to undergo a language migration from Ruby to Go. You can view more details about this in our announcement here: [hashicorp/terraform-provider-google#19583](https://github.com/hashicorp/terraform-provider-google/issues/19583) (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)
> 
> This open pull request may become incompatible due to most YAML and .erb files converting to Go-compatible files.
> 
> Our team (Magic Modules repository maintainers) has tooling to automatically convert changes to the new language, and we can prepare a new commit for this pull request that is compatible with the migration.
> 
> In order to push the new changes to your pull request, we would need to force push the commit to your fork's branch. Our tooling saves a backup branch before converting, so we could rollback or open a new pull request if needed. We would also work with you and the PR reviewer in the event additional changes are needed.
> 
> You also have the option to update the pull request yourself after the migration. You can view a [preview branch](https://github.com/GoogleCloudPlatform/magic-modules/tree/FEATURE-BRANCH-rewrite-switchover-preview) and [updated documentation](https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/) related to the migration changes.
> 
> We will take no action until we have your explicit permission to push changes to your fork's branch used for this pull request. Let me or your reviewer know if you have any further questions!

You have my explicit permission to push changes to my fork's branch used for this pull request

2024-09-25 23:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 104 insertions(+), 1 deletion(-))

2024-09-25 23:33 UTC, modular-magician commented
#### Tests analytics
Total tests: 98
Passed tests: 83
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlServerTimezone_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-25 23:39 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccSqlServerTimezone_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/074381ee-8ad6-4e0e-9268-52b2da87ba3f/build-log/recording_build/TestAccSqlServerTimezone_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/074381ee-8ad6-4e0e-9268-52b2da87ba3f/recording/TestAccSqlServerTimezone_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/074381ee-8ad6-4e0e-9268-52b2da87ba3f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/074381ee-8ad6-4e0e-9268-52b2da87ba3f/recording) for each test

2024-09-26 20:41 UTC, stameishiGoogle commented
As of this morning, the feature should be fully rolled out! @shuyama1

2024-09-26 21:09 UTC, shuyama1 commented
/gcbrun

2024-09-26 21:11 UTC, shuyama1 requested changes

2024-09-26 21:11 UTC, shuyama1 commented on mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go
> +func TestAccSqlServerTimezone_update(t *testing.T) {
```suggestion
func TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate(t *testing.T) {
```

2024-09-26 21:11 UTC, shuyama1 commented on mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go
> +func TestAccSqlDatabaseInstance_SqlServerTimezone(t *testing.T) {
We can remove `TestAccSqlDatabaseInstance_SqlServerTimezone` given it's covered in the update test `TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate`

2024-09-26 21:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 79 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 79 insertions(+), 1 deletion(-))

2024-09-26 21:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 79 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11202-old..auto-pr-11202) ( 2 files changed, 79 insertions(+), 1 deletion(-))

2024-09-26 21:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 97
Passed tests: 82
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-26 21:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 97
Passed tests: 82
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-26 21:50 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/23ef0d59-cb18-4960-a9f8-7237271a7920/recording/TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/23ef0d59-cb18-4960-a9f8-7237271a7920/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/23ef0d59-cb18-4960-a9f8-7237271a7920/recording) for each test

2024-09-26 21:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/d4b03194-4dc8-4f6f-a254-35784b53c64b/recording/TestAccSqlDatabaseInstance_SqlServerTimezoneUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/d4b03194-4dc8-4f6f-a254-35784b53c64b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11202/artifacts/d4b03194-4dc8-4f6f-a254-35784b53c64b/recording) for each test

2024-09-26 21:58 UTC, shuyama1 approved these changes

2024-09-26 21:59 UTC, merged