Add artifact registry locations support
GoogleCloudPlatform/magic-modules pull request #11208
Opened 2024-07-19 06:48 UTC by attwad

Add data source for artifact registry locations.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/18785

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
artifact_registry: added `google_artifact_registry_locations` data source
```

2024-07-19 06:58 UTC, attwad commented
Hi @NickElliot, this is my first contribution to terraform / magic-modules. I'm following https://googlecloudplatform.github.io/magic-modules/get-started/contribution-process/#contribute-code but the 3rd step (generate the providers) that I run with `make provider VERSION=beta OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta" PRODUCT=artifactregistry` writes the changes in a different repo, I'm not sure how I am supposed to make this PR and that command work together, please advise, thank you!

2024-07-19 20:28 UTC, NickElliot reviewed
Hi, the idea is that when you run that command, it generates the changes into a TPG repo (via the same process that this repo leads to https://github.com/hashicorp/terraform-provider-google-beta downstream.

what you can then do is follow the following instructions to use your local version of TPG to run terraform https://googlecloudplatform.github.io/magic-modules/develop/test/run-tests/#optional-test-manually

Please let me know if you have any other questions!

2024-07-19 20:29 UTC, NickElliot commented
/gcbrun

2024-07-19 20:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 219 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 219 insertions(+))

2024-07-19 20:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>artifactregistry</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleArtifactRegistryLocations_basic
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/84831b3e-6cab-4fa5-990d-4fe7c26b8317/build-log/replaying_test.log)

2024-07-19 23:43 UTC, attwad commented
Thanks for the explanation! I see some tests are failing (they passed locally even after I ran the provider make command which is weird) so I'll investigate.

2024-07-23 20:27 UTC, NickElliot requested changes
Problem is its failing lint :)

> gofmt needs running on the following files:
./google-beta/services/artifactregistry/data_source_artifact_registry_locations.go
./google-beta/services/artifactregistry/data_source_artifact_registry_locations_test.go
You can use the command: `make fmt` to reformat code.

2024-07-24 00:38 UTC, attwad commented
Yup, I'm on vacation until August I'll fix that when I'm back, thanks!

2024-07-24 21:36 UTC, NickElliot reviewed
pending update

2024-07-27 05:22 UTC, attwad commented
> Problem is its failing lint :)
> 
> > gofmt needs running on the following files:
> > ./google-beta/services/artifactregistry/data_source_artifact_registry_locations.go
> > ./google-beta/services/artifactregistry/data_source_artifact_registry_locations_test.go
> > You can use the command: `make fmt` to reformat code.

Formatted the code correctly now

2024-07-29 21:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 217 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 217 insertions(+))

2024-07-29 21:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>artifactregistry</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleArtifactRegistryLocations_basic
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/ce57ce8c-271a-41ef-8c86-80309de088c4/build-log/replaying_test.log)

2024-07-29 21:16 UTC, NickElliot requested changes
try making this change thanks!

2024-07-29 21:16 UTC, NickElliot commented on mmv1/third_party/terraform/services/artifactregistry/data_source_artifact_registry_locations_test.go
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
```suggestion
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
```

2024-07-29 23:41 UTC, attwad commented
> try making this change thanks!

done but fmt reimported terraform, I've copied the imports from other tests as they looked different indeed, should be ok now

2024-07-31 20:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))

2024-07-31 20:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>artifactregistry</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleArtifactRegistryLocations_basic
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/d424f369-d77a-479f-be6d-474a3e1eb37d/build-log/replaying_test.log)

2024-07-31 21:32 UTC, NickElliot requested changes
same error is still present
> google-beta/services/artifactregistry/data_source_artifact_registry_locations_test.go:19:21: cannot use resource.TestCase{…} (value of type "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource".TestCase) as "github.com/hashicorp/terraform-plugin-testing/helper/resource".TestCase value in argument to acctest.VcrTest

For this kind of issue it helps a lot if you can debug and run the test locally, as it costly in both our CI project, review time, and dramatically slows speed of PR merges to wait for the reviewer to manually be rerunning these tests, when basic build or syntax errors can often be caught really quickly locally. Thanks!

2024-08-01 08:21 UTC, attwad commented
> same error is still present
> 
> > google-beta/services/artifactregistry/data_source_artifact_registry_locations_test.go:19:21: cannot use resource.TestCase{…} (value of type "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource".TestCase) as "github.com/hashicorp/terraform-plugin-testing/helper/resource".TestCase value in argument to acctest.VcrTest
> 
> For this kind of issue it helps a lot if you can debug and run the test locally, as it costly in both our CI project, review time, and dramatically slows speed of PR merges to wait for the reviewer to manually be rerunning these tests, when basic build or syntax errors can often be caught really quickly locally. Thanks!

Well yes I've been running them, but the thing is they pass locally... :(

```
make provider VERSION=beta OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta" PRODUCT=artifactregistry
cd "$GOPATH/src/github.com/hashicorp/terraform-provider-google-beta"
~/go/src/github.com/hashicorp/terraform-provider-google-beta$ go test google-beta/services/artifactregistry/data_source_artifact_registry_locations_test.go 
ok      command-line-arguments  0.126s
```

I'll keep looking, thanks

2024-08-01 10:58 UTC, attwad commented
Even the tests requiring a gcloud project work:

GA:
```
~/go/src/github.com/hashicorp/terraform-provider-google$ make testacc TEST=./google/services/artifactregistry TESTARGS='-run=TestAccDataSourceGoogleArtifactRegistryLocations_basic'
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google/services/artifactregistry -v -run=TestAccDataSourceGoogleArtifactRegistryLocations_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceGoogleArtifactRegistryLocations_basic
=== PAUSE TestAccDataSourceGoogleArtifactRegistryLocations_basic
=== CONT  TestAccDataSourceGoogleArtifactRegistryLocations_basic
--- PASS: TestAccDataSourceGoogleArtifactRegistryLocations_basic (6.15s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google/services/artifactregistry 6.274s
```

beta:
```
~/go/src/github.com/hashicorp/terraform-provider-google-beta$ make testacc TEST=./google-beta/services/artifactregistry TESTARGS='-run=TestAccDataSourceGoogleArtifactRegistryLocations_basic'
==> Checking that code complies with gofmt requirements...
go vet
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta/services/artifactregistry -v -run=TestAccDataSourceGoogleArtifactRegistryLocations_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceGoogleArtifactRegistryLocations_basic
=== PAUSE TestAccDataSourceGoogleArtifactRegistryLocations_basic
=== CONT  TestAccDataSourceGoogleArtifactRegistryLocations_basic
--- PASS: TestAccDataSourceGoogleArtifactRegistryLocations_basic (6.69s)
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta/services/artifactregistry       6.815s
```

2024-08-01 11:17 UTC, attwad commented
ok! I have no idea what was happening but I deleted the provider forks and restarted from scratch, I could reproduce the error and finally got all lints/build/tests pass locally.

2024-08-06 19:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))

2024-08-06 19:50 UTC, modular-magician commented
#### Tests analytics
Total tests: 25
Passed tests: 24
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>artifactregistry</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-06 19:50 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/e2ee5a91-a948-4ff1-8f5f-ec2844956aff/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/e2ee5a91-a948-4ff1-8f5f-ec2844956aff/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/e2ee5a91-a948-4ff1-8f5f-ec2844956aff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/e2ee5a91-a948-4ff1-8f5f-ec2844956aff/recording) for each test

2024-08-06 19:55 UTC, NickElliot commented
/gcbrun

2024-08-06 20:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11208-old..auto-pr-11208) ( 4 files changed, 216 insertions(+))

2024-08-06 20:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 25
Passed tests: 24
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>artifactregistry</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceArtifactRegistryDockerImage</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-06 20:09 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceArtifactRegistryDockerImage`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/602d16b8-5379-48ef-bf16-6702c46af613/build-log/recording_build/TestAccDataSourceArtifactRegistryDockerImage_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/602d16b8-5379-48ef-bf16-6702c46af613/recording/TestAccDataSourceArtifactRegistryDockerImage.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/602d16b8-5379-48ef-bf16-6702c46af613/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11208/artifacts/602d16b8-5379-48ef-bf16-6702c46af613/recording) for each test

2024-08-07 08:39 UTC, attwad commented
The VCR test that's failing seems to be unrelated to this PR (it's about the docker image data source, not the locations data source), is this good to go?

2024-08-08 20:02 UTC, NickElliot approved these changes
verified error is part of seperate issue https://github.com/hashicorp/terraform-provider-google/issues/18955

LGTM!

2024-08-08 20:03 UTC, merged