X509 federation
GoogleCloudPlatform/magic-modules pull request #11253
Opened 2024-07-24 21:02 UTC by EZIOJQ

This PR adds support for X.509 federation support on workload identity pool. It fixes https://github.com/hashicorp/terraform-provider-google/issues/18812. 

For more details about how this feature works, check out the public doc here https://cloud.google.com/iam/docs/workload-identity-federation-with-x509-certificates

```release-note:enhancement
added `x509` field to `google_iambeta_workload_identity_provider` resource
```

2024-07-24 21:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 3 files changed, 464 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 4 files changed, 556 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-07-24 21:17 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 15
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample</li>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_x509</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-24 21:17 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample.log)]
`TestAccIAMBetaWorkloadIdentityPoolProvider_x509`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_x509_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_x509.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/61aca408-5545-4143-bb35-762a3eec4449/recording) for each test

2024-08-05 19:01 UTC, EZIOJQ commented
/gcbrun

2024-08-05 20:16 UTC, EZIOJQ commented
I don't know how to re-trigger the VCR test, I fixed some visibility issues and manual test run has succeeded

2024-08-06 19:36 UTC, NickElliot commented
/gcbrun

2024-08-06 19:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 3 files changed, 464 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 4 files changed, 556 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-06 19:51 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 15
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample</li>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_x509</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-06 19:53 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/c9b63bb5-cd67-4e32-8dde-2e4d9b0f69af/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/c9b63bb5-cd67-4e32-8dde-2e4d9b0f69af/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample.log)]
`TestAccIAMBetaWorkloadIdentityPoolProvider_x509`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/c9b63bb5-cd67-4e32-8dde-2e4d9b0f69af/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_x509.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/c9b63bb5-cd67-4e32-8dde-2e4d9b0f69af/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/c9b63bb5-cd67-4e32-8dde-2e4d9b0f69af/recording) for each test

2024-08-08 20:00 UTC, NickElliot requested changes
mostly LGTM -- just want to get one thing changed around. could you add the pem_certificates as files in `mmv1/third_party/terraform/services/iambeta/test-fixtures`?

can see examples [here](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/compute/test-fixtures)

thanks!

2024-08-13 00:32 UTC, EZIOJQ commented on mmv1/templates/terraform/examples/iam_workload_identity_pool_provider_x509_basic.tf.erb
> +            pem_certificate = "-----BEGIN CERTIFICATE-----\nMIIDtjCCAp6gAwIBAgIIMu9pvsFWIUcwDQYJKoZIhvcNAQELBQAwXDEXMBUGA1UE\nChMOR29vZ2xlIFRFU1RJTkcxHDAaBgNVBAsTE0dvb2dsZSBURVNUSU5HIHVuaXQx\nIzAhBgN
Done in the new update

2024-08-13 00:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 5 files changed, 466 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 6 files changed, 558 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-13 00:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 17
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-13 00:43 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/31f31b59-73c1-44b0-beac-0d7a65918982/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/31f31b59-73c1-44b0-beac-0d7a65918982/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/31f31b59-73c1-44b0-beac-0d7a65918982/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/31f31b59-73c1-44b0-beac-0d7a65918982/recording) for each test

2024-08-13 00:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 5 files changed, 466 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 6 files changed, 558 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-13 00:46 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 17
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-13 00:46 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/e7121a70-6e51-45d6-85fe-6718c6f89471/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/e7121a70-6e51-45d6-85fe-6718c6f89471/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/e7121a70-6e51-45d6-85fe-6718c6f89471/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/e7121a70-6e51-45d6-85fe-6718c6f89471/recording) for each test

2024-08-15 21:11 UTC, NickElliot requested changes
> Error: Error creating WorkloadIdentityPoolProvider: googleapi: Error 400: Certificate is not in PEM format. Please make sure to include the suffix, prefix and the new line characters.

make sure to format the files correctly!

2024-08-15 22:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 5 files changed, 466 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 6 files changed, 558 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-15 22:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 17
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-15 22:22 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/ef59879f-7816-44ad-9aaf-1189475eafe8/build-log/recording_build/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/ef59879f-7816-44ad-9aaf-1189475eafe8/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/ef59879f-7816-44ad-9aaf-1189475eafe8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/ef59879f-7816-44ad-9aaf-1189475eafe8/recording) for each test

2024-08-15 22:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 5 files changed, 470 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 6 files changed, 562 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-15 22:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 16
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample</li>
<li>TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-15 22:47 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/1b2a5a2c-8f5b-4a20-abad-cbdf5974168d/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509BasicExample.log)]
`TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/1b2a5a2c-8f5b-4a20-abad-cbdf5974168d/recording/TestAccIAMBetaWorkloadIdentityPoolProvider_iamWorkloadIdentityPoolProviderX509FullExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/1b2a5a2c-8f5b-4a20-abad-cbdf5974168d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/1b2a5a2c-8f5b-4a20-abad-cbdf5974168d/recording) for each test

2024-08-15 22:58 UTC, EZIOJQ commented
@NickElliot I've changed the file format, PTAL, thanks!

2024-08-19 21:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11253-old..auto-pr-11253) ( 5 files changed, 470 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11253-old..auto-pr-11253) ( 6 files changed, 562 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11253-old..auto-pr-11253) ( 1 file changed, 103 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11253-old..auto-pr-11253) ( 8 files changed, 244 insertions(+))

2024-08-19 21:04 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 18
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>iambeta</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11253/artifacts/119e2d5d-6fe4-4766-ad3e-4fcd2a97e39e/build-log/replaying_test.log)

2024-08-19 21:13 UTC, closed without merging

2024-08-19 21:18 UTC, EZIOJQ commented
I closed this as my repo was messed up with unrelated changes. Created a new pull request here https://github.com/GoogleCloudPlatform/magic-modules/pull/11493