Support
GoogleCloudPlatform/magic-modules pull request #11276
Opened 2024-07-29 05:00 UTC by chentaozgoogle

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `boot_disk.interface`  and `attached_disk.interface` field to `google_compute_instance` resource)
```

2024-07-29 05:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 131 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 131 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (288 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_machine_image` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (13 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-07-29 05:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 130 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (288 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_machine_image` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (13 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-07-29 05:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 977
Passed tests: 899
Skipped tests: 74
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstance_attachedDiskUpdate</li>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeInstance_forceChangeMachineTypeManually</li>
<li>TestAccComputeRegionDisk_deleteDetach</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-29 05:35 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_attachedDiskUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/recording/TestAccComputeInstance_attachedDiskUpdate.log)]
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]
`TestAccComputeInstance_forceChangeMachineTypeManually`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/recording/TestAccComputeInstance_forceChangeMachineTypeManually.log)]
`TestAccComputeRegionDisk_deleteDetach`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/recording/TestAccComputeRegionDisk_deleteDetach.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/57a1ebfc-cb18-4974-93b4-1097161ebc41/recording) for each test

2024-07-29 05:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 977
Passed tests: 900
Skipped tests: 74
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstance_attachedDiskUpdate</li>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeRegionDisk_deleteDetach</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-29 05:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_attachedDiskUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e9b000da-6834-4a78-9bbf-2c51204fb1b4/recording/TestAccComputeInstance_attachedDiskUpdate.log)]
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e9b000da-6834-4a78-9bbf-2c51204fb1b4/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]
`TestAccComputeRegionDisk_deleteDetach`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e9b000da-6834-4a78-9bbf-2c51204fb1b4/recording/TestAccComputeRegionDisk_deleteDetach.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e9b000da-6834-4a78-9bbf-2c51204fb1b4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e9b000da-6834-4a78-9bbf-2c51204fb1b4/recording) for each test

2024-07-29 19:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 107 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 3 files changed, 107 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (13 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-07-29 19:55 UTC, modular-magician commented
#### Tests analytics
Total tests: 977
Passed tests: 901
Skipped tests: 74
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeInstance_forceChangeMachineTypeManually</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-29 20:01 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/3417d246-b442-43c0-8ce4-0a008af9e3cd/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]
`TestAccComputeInstance_forceChangeMachineTypeManually`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/3417d246-b442-43c0-8ce4-0a008af9e3cd/recording/TestAccComputeInstance_forceChangeMachineTypeManually.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/3417d246-b442-43c0-8ce4-0a008af9e3cd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/3417d246-b442-43c0-8ce4-0a008af9e3cd/recording) for each test

2024-07-30 04:17 UTC, chentaozgoogle commented
hey @NickElliot , I have fixed all missing coverage shown in the Missing test report  beside the one for google_compute_instance_from_machine_image , which doesn't seem to be valid report.  The reason is that the `attached_disk` and `boot_disk`, where the  `interface` resides, cannot be configured in google_compute_instance_from_machine_image.  So please review . thanks!

2024-07-30 04:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 188 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 188 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-07-30 04:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 978
Passed tests: 903
Skipped tests: 74
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceFromTemplateWithOverride_interface</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-30 04:44 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceFromTemplateWithOverride_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/eb89b905-ffd6-4185-8345-251f06cfd8fc/recording/TestAccComputeInstanceFromTemplateWithOverride_interface.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/eb89b905-ffd6-4185-8345-251f06cfd8fc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/eb89b905-ffd6-4185-8345-251f06cfd8fc/recording) for each test

2024-07-31 21:40 UTC, NickElliot submitted a review, later dismissed
LGTM!

2024-07-31 21:43 UTC, NickElliot reviewed
Hi, TGC validation is having an issue due to not expecting the interface data. Looking into how that can be resolved but here is the error details for the time being:

```--- FAIL: TestFakeResourceData_getOkTypeObject (0.00s)
    fake_resource_data_test.go:242: 
        	Error Trace:	/home/runner/work/magic-modules/magic-modules/tfplan2cai/tfdata/fake_resource_data_test.go:242
        	Error:      	Not equal: 
        	            	expected: map[string]interface {}{"device_name":"test-device_name", "disk_encryption_key_raw":"", "disk_encryption_key_sha256":"", "kms_key_self_link":"test-kms_key_self_link", "mode":"READ_ONLY", "source":"test-source"}
        	            	actual  : map[string]interface {}{"device_name":"test-device_name", "disk_encryption_key_raw":"", "disk_encryption_key_sha256":"", "interface":"", "kms_key_self_link":"test-kms_key_self_link", "mode":"READ_ONLY", "source":"test-source"}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(map[string]interface {}) (len=6) {
        	            	+(map[string]interface {}) (len=7) {
        	            	  (string) (len=11) "device_name": (string) (len=16) "test-device_name",
        	            	@@ -4,2 +4,3 @@
        	            	  (string) (len=26) "disk_encryption_key_sha256": (string) "",
        	            	+ (string) (len=9) "interface": (string) "",
        	            	  (string) (len=17) "kms_key_self_link": (string) (len=22) "test-kms_key_self_link",
        	Test:       	TestFakeResourceData_getOkTypeObject
--- FAIL: TestFakeResourceData_getOknsetTypeObject (0.00s)
    fake_resource_data_test.go:317: 
        	Error Trace:	/home/runner/work/magic-modules/magic-modules/tfplan2cai/tfdata/fake_resource_data_test.go:317
        	Error:      	Not equal: 
        	            	expected: map[string]interface {}{"device_name":"", "disk_encryption_key_raw":"", "disk_encryption_key_sha256":"", "kms_key_self_link":"", "mode":"", "source":""}
        	            	actual  : map[string]interface {}{"device_name":"", "disk_encryption_key_raw":"", "disk_encryption_key_sha256":"", "interface":"", "kms_key_self_link":"", "mode":"", "source":""}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-(map[string]interface {}) (len=6) {
        	            	+(map[string]interface {}) (len=7) {
        	            	  (string) (len=11) "device_name": (string) "",
        	            	@@ -4,2 +4,3 @@
        	            	  (string) (len=26) "disk_encryption_key_sha256": (string) "",
        	            	+ (string) (len=9) "interface": (string) "",
        	            	  (string) (len=17) "kms_key_self_link": (string) "",
        	Test:       	TestFakeResourceData_getOknsetTypeObject
FAIL
FAIL	github.com/GoogleCloudPlatform/terraform-google-conversion/v5/tfplan2cai/tfdata	0.044s
ok  	github.com/GoogleCloudPlatform/terraform-google-conversion/v5/tfplan2cai/tfplan	(cached)
FAIL
make: *** [Makefile:11: test] Error 1
Error: Process completed with exit code 2.```

2024-08-25 03:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 5 files changed, 238 insertions(+), 36 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 5 files changed, 239 insertions(+), 45 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-25 03:54 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
- TestAccComputeInstance_bootAndAttachedDisk_interface
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/0ca8eb4c-2484-4ad5-b918-73f8842c8d5f/build-log/replaying_test.log)

2024-08-25 03:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 203 insertions(+), 9 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 210 insertions(+), 18 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-25 03:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
- TestAccComputeInstance_bootAndAttachedDisk_interface
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/3857ed01-4d91-4d28-9f92-7002f8fef4d8/build-log/replaying_test.log)

2024-08-25 04:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 189 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 189 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-25 04:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 987
Passed tests: 904
Skipped tests: 77
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeDiskAsyncReplication</li>
<li>TestAccComputeInstanceFromTemplateWithOverride_interface</li>
<li>TestAccComputeInstance_attachedDiskUpdate</li>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeInstance_forceChangeMachineTypeManually</li>
<li>TestAccComputeRegionDisk_deleteDetach</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-25 04:39 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceFromTemplateWithOverride_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeInstanceFromTemplateWithOverride_interface.log)]
`TestAccComputeInstance_attachedDiskUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeInstance_attachedDiskUpdate.log)]
`TestAccComputeInstance_forceChangeMachineTypeManually`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeInstance_forceChangeMachineTypeManually.log)]
`TestAccComputeRegionDisk_deleteDetach`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeRegionDisk_deleteDetach.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeDiskAsyncReplication`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/build-log/recording_build/TestAccComputeDiskAsyncReplication_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeDiskAsyncReplication.log)]
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/build-log/recording_build/TestAccComputeInstance_bootAndAttachedDisk_interface_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/7c2dec23-60b9-4ae8-94c4-fd88f418af9b/recording) for each test

2024-08-25 06:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-25 06:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-25 06:33 UTC, modular-magician commented
#### Tests analytics
Total tests: 473
Passed tests: 406
Skipped tests: 65
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeRegionDisk_deleteDetach</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-25 06:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 927
Passed tests: 846
Skipped tests: 77
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeDiskAsyncReplication</li>
<li>TestAccComputeInstance_attachedDiskUpdate</li>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeRegionDisk_deleteDetach</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-25 06:40 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/945c1b5c-fb33-4a72-b9e4-330dca1120ef/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]
`TestAccComputeRegionDisk_deleteDetach`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/945c1b5c-fb33-4a72-b9e4-330dca1120ef/recording/TestAccComputeRegionDisk_deleteDetach.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/945c1b5c-fb33-4a72-b9e4-330dca1120ef/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/945c1b5c-fb33-4a72-b9e4-330dca1120ef/recording) for each test

2024-08-25 06:44 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_attachedDiskUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/recording/TestAccComputeInstance_attachedDiskUpdate.log)]
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]
`TestAccComputeRegionDisk_deleteDetach`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/recording/TestAccComputeRegionDisk_deleteDetach.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeDiskAsyncReplication`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/build-log/recording_build/TestAccComputeDiskAsyncReplication_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/recording/TestAccComputeDiskAsyncReplication.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/dd65fb91-c851-456d-9e89-31a70c82ac7b/recording) for each test

2024-08-26 21:05 UTC, NickElliot requested changes
the new fields need to be added to `convertBootDisk` and `convertAttachedDisk` in `mmv1/third_party/cai2hcl/services/compute/compute_instance.go`

2024-08-27 18:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 199 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-27 18:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 821
Passed tests: 744
Skipped tests: 76
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-27 18:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/26008a17-e02e-4e92-8979-056977858f94/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/26008a17-e02e-4e92-8979-056977858f94/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/26008a17-e02e-4e92-8979-056977858f94/recording) for each test

2024-08-28 04:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 208 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 208 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    interface = # value needed
  }
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-28 04:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 932
Passed tests: 852
Skipped tests: 77
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>
<li>TestAccComputeInstance_bootAndAttachedDisk_interface</li>
<li>TestAccComputeTargetHttpsProxy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 04:53 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/recording/TestAccComputeTargetHttpsProxy_update.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstance_bootAndAttachedDisk_interface`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/build-log/recording_build/TestAccComputeInstance_bootAndAttachedDisk_interface_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/recording/TestAccComputeInstance_bootAndAttachedDisk_interface.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/13c829ad-203d-462c-8ff5-8a673daf7393/recording) for each test

2024-08-28 05:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 182 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 182 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-28 05:34 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
- TestAccComputeInstance_bootAndAttachedDisk_interface
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/607880e8-f280-49c0-8603-5ca8d3437b9d/build-log/replaying_test.log)

2024-08-28 05:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 180 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 180 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-28 05:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
- TestAccComputeInstance_bootAndAttachedDisk_interface
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/fa72b975-be43-4cda-a0d2-425ebb6cbb69/build-log/replaying_test.log)

2024-08-28 06:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-28 06:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 867
Passed tests: 789
Skipped tests: 77
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 06:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e532b462-91c0-49d2-8120-d55d4131ef2f/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e532b462-91c0-49d2-8120-d55d4131ef2f/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e532b462-91c0-49d2-8120-d55d4131ef2f/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e532b462-91c0-49d2-8120-d55d4131ef2f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/e532b462-91c0-49d2-8120-d55d4131ef2f/recording) for each test

2024-08-28 06:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-28 06:47 UTC, modular-magician commented
#### Tests analytics
Total tests: 849
Passed tests: 772
Skipped tests: 76
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 06:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/bb5d4d12-0b8a-4bae-bac2-7e14df5ec2b2/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/bb5d4d12-0b8a-4bae-bac2-7e14df5ec2b2/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/bb5d4d12-0b8a-4bae-bac2-7e14df5ec2b2/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/bb5d4d12-0b8a-4bae-bac2-7e14df5ec2b2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/bb5d4d12-0b8a-4bae-bac2-7e14df5ec2b2/recording) for each test

2024-08-29 14:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 178 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-29 14:57 UTC, modular-magician commented
#### Tests analytics
Total tests: 808
Passed tests: 731
Skipped tests: 76
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 14:59 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/d9457bab-d8fe-473c-ab97-c22ae20c91d5/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/d9457bab-d8fe-473c-ab97-c22ae20c91d5/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/d9457bab-d8fe-473c-ab97-c22ae20c91d5/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/d9457bab-d8fe-473c-ab97-c22ae20c91d5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/d9457bab-d8fe-473c-ab97-c22ae20c91d5/recording) for each test

2024-08-29 17:38 UTC, NickElliot requested changes
last changes!

2024-08-29 17:38 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/resource_compute_instance.go.erb
> +							ForceNew:     false,
```suggestion
```
These are default values, dont need to be explicitly declared

2024-08-29 17:38 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/resource_compute_instance.go.erb
> +							Description:  `The disk interface used for attaching this disk. One of SCSI or NVME. (This field is only used for specific cases, please don't specify this field without advice from Google.)`,
```suggestion
							Description:  `The disk interface used for attaching this disk. One of SCSI or NVME. (This field is shared with `attached_disk` and only used for specific cases, please don't specify this field without advice from Google.)`,
```
Explicitly mention this value is shared with Attached_disk

2024-08-29 17:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 176 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 176 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-29 18:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 176 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11276-old..auto-pr-11276) ( 4 files changed, 176 insertions(+), 1 deletion(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  boot_disk {
    interface = # value needed
  }
}


```

2024-08-29 18:07 UTC, modular-magician commented
#### Tests analytics
Total tests: 440
Passed tests: 376
Skipped tests: 64
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccComputeInstanceFromTemplateWithOverride_interface
- TestAccComputeInstance_bootAndAttachedDisk_interface
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/8c866055-f0eb-4273-8e3f-fa40702bf002/build-log/replaying_test.log)

2024-08-29 18:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 945
Passed tests: 867
Skipped tests: 77
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 18:17 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/9634a74d-dcd8-4e88-87e6-a729a4a62b5c/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/9634a74d-dcd8-4e88-87e6-a729a4a62b5c/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/9634a74d-dcd8-4e88-87e6-a729a4a62b5c/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/9634a74d-dcd8-4e88-87e6-a729a4a62b5c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11276/artifacts/9634a74d-dcd8-4e88-87e6-a729a4a62b5c/recording) for each test

2024-08-29 21:46 UTC, NickElliot approved these changes
verified test failure is unrelated and original TGC failure is resolved -- LGTM!

2024-08-29 21:47 UTC, merged