functions2 align storage object generation to other storage source attributes
GoogleCloudPlatform/magic-modules pull request #11287
Opened 2024-07-30 07:40 UTC by gleichda

Currently Cloud Functions v2 has a permanent state drift for storage generation due to different implementation between other strings in the storage source and generation.  This aligns generations between all storage source attributes and allows using the generation as a trigger for redeployment

Tests for cloudfunctions2 were already successfully executed locally

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
cloudfunctions2: Use generation from input storage source if provided as input
```

Fixes hashicorp/terraform-provider-google/issues/15405

2024-07-30 07:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 18 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 18 insertions(+), 8 deletions(-))

2024-07-30 07:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 16
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudfunctions2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudFunctions2Function_updateAbiuFull</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-30 08:00 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudFunctions2Function_updateAbiuFull`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/eac42481-4840-47d3-8977-750da867519f/recording/TestAccCloudFunctions2Function_updateAbiuFull.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/eac42481-4840-47d3-8977-750da867519f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/eac42481-4840-47d3-8977-750da867519f/recording) for each test

2024-07-30 19:41 UTC, slevenick requested changes
Can you add a test that fails on the existing provider but will pass with this change?

2024-07-30 19:41 UTC, slevenick commented on mmv1/products/cloudfunctions2/Function.yaml
> +                custom_flatten: 'templates/terraform/custom_flatten/cloudfunctions2_function_source_generation.go.erb'
Can we add ignore_read: true to this field instead? From looking at the custom flatten function it seems to just read from state, which is pretty similar to just adding ignore_read

2024-07-30 19:41 UTC, slevenick commented on mmv1/templates/terraform/custom_flatten/cloudfunctions2_function_source_generation.go.erb
> +	if ObjVal, ok := d.GetOk("build_config.0.source.0.storage_source.0.generation"); ok {
```suggestion
	if objVal, ok := d.GetOk("build_config.0.source.0.storage_source.0.generation"); ok {
```

2024-07-30 19:41 UTC, slevenick commented on mmv1/templates/terraform/custom_flatten/cloudfunctions2_function_source_generation.go.erb
> +		v = ObjVal
What happens if this value is not set in state? We end up using the `v` passed into the function which doesn't actually work?

2024-07-31 09:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 18 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 18 insertions(+), 8 deletions(-))

2024-07-31 09:27 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 16
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudfunctions2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudFunctions2Function_updateAbiuFull</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-07-31 09:31 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudFunctions2Function_updateAbiuFull`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/837a4d38-e676-4349-90ec-b571765c1a36/recording/TestAccCloudFunctions2Function_updateAbiuFull.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/837a4d38-e676-4349-90ec-b571765c1a36/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/837a4d38-e676-4349-90ec-b571765c1a36/recording) for each test

2024-07-31 18:53 UTC, slevenick reviewed
Can you add a test that fails on the existing provider but will pass with this change?

2024-08-01 13:31 UTC, gleichda commented
> Can you add a test that fails on the existing provider but will pass with this change?

Sorry oversaw that comment...

Testing is currently not possible due to hashicorp/terraform-provider-google/issues/14117 I'm unable to retrieve the generation for a GCS object via Terraform that I could use in the test case.

2024-08-02 11:56 UTC, gleichda commented
Nevermind. I talked to @prauc and he opened #11335 so I'll update the test once his PR is merged

2024-08-05 20:19 UTC, modular-magician commented
#### Tests analytics
Total tests: 19
Passed tests: 17
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudfunctions2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudFunctions2Function_generation</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-05 20:21 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudFunctions2Function_generation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/3c93d2f0-dc03-46b6-80bc-2e3e9f2034b9/recording/TestAccCloudFunctions2Function_generation.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/3c93d2f0-dc03-46b6-80bc-2e3e9f2034b9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/3c93d2f0-dc03-46b6-80bc-2e3e9f2034b9/recording) for each test

2024-08-05 20:28 UTC, slevenick approved these changes

2024-08-05 20:29 UTC, slevenick requested changes
Sorry, there's a lint error on resource_cloudfunctions2_function_test

Can you fix that? Other than that this looks good

2024-08-05 21:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 88 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11287-old..auto-pr-11287) ( 2 files changed, 88 insertions(+), 8 deletions(-))

2024-08-05 21:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 19
Passed tests: 18
Skipped tests: 1
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudfunctions2</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11287/artifacts/f59313c8-278a-4b52-a57d-bbdd7b0cf7d8/build-log/replaying_test.log)

2024-08-07 19:14 UTC, slevenick approved these changes

2024-08-07 19:14 UTC, merged