Move google_compute_firewall_policy resource from DCL to MMv1
GoogleCloudPlatform/magic-modules pull request #11357
Opened 2024-08-05 19:46 UTC by Samir-Cit

Hello folks.
This PR is to move the Compute Firewall Policy (`google_compute_firewall_policy`) resource from DCL to MMv1. And this PR includes:
- Creation of the resource on MMv1.
- Creation of the examples and tests.
- Remove references to DCL resource.

_**Note:** This PR doesn't include the deletion of the DCL resource. This change will be done on the [Delarative Resource Client Library](https://github.com/GoogleCloudPlatform/declarative-resource-client-library/tree/main) repository._

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Moved `google_compute_firewall_policy` from DCL to MMv1
```

2024-08-09 22:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 6 files changed, 524 insertions(+), 188 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 6 files changed, 524 insertions(+), 188 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `firewall_policy_id` within resource `google_compute_firewall_policy` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-09 22:49 UTC, modular-magician commented
#### Tests analytics
Total tests: 980
Passed tests: 901
Skipped tests: 72
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten</li>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeFirewallPolicyRule_update</li>
<li>TestAccComputeFirewallPolicy_firewallPolicyExample</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-09 22:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeFirewallPolicy_firewallPolicyExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicy_firewallPolicyExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyAssociation_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicyAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicyRule_securityProfileGroup_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicyRule_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccComputeFirewallPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_build/TestAccComputeFirewallPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording/TestAccComputeFirewallPolicy_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/8fa29951-2638-427d-b805-730495b2ad93/recording) for each test

2024-08-14 18:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 554 insertions(+), 272 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 554 insertions(+), 272 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-14 18:50 UTC, modular-magician commented
#### Tests analytics
Total tests: 982
Passed tests: 904
Skipped tests: 72
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten</li>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeFirewallPolicyRule_update</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-14 18:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyAssociation_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccComputeFirewallPolicy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicy_update.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/fb4e9479-42ca-428f-80f6-9c5348310b8c/recording) for each test

2024-08-22 20:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 554 insertions(+), 204 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 554 insertions(+), 204 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-22 20:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 986
Passed tests: 903
Skipped tests: 77
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten</li>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeFirewallPolicyRule_update</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-22 21:03 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyAssociation_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicyRule_update.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/build-log/recording_build/TestAccComputeFirewallPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording/TestAccComputeFirewallPolicy_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/061c2f9b-218e-45e9-ab64-de8aad3d375d/recording) for each test

2024-08-26 16:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 559 insertions(+), 207 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 559 insertions(+), 207 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-26 16:23 UTC, modular-magician commented
#### Tests analytics
Total tests: 986
Passed tests: 907
Skipped tests: 77
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-26 16:28 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeFirewallPolicyRule_multipleRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/ee3a4908-08c0-4902-8b27-1504bec9c287/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/ee3a4908-08c0-4902-8b27-1504bec9c287/recording/TestAccComputeFirewallPolicy_update.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/ee3a4908-08c0-4902-8b27-1504bec9c287/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/ee3a4908-08c0-4902-8b27-1504bec9c287/recording) for each test

2024-09-17 16:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 8 files changed, 77 insertions(+), 399 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 561 insertions(+), 207 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Resource `google_compute_firewall_policy` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes#resource-map-resource-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-09-17 16:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 1005
Passed tests: 930
Skipped tests: 74
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicy_firewallPolicyExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-17 16:59 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeFirewallPolicy_firewallPolicyExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/d0b871a8-1180-4305-ac6e-ca9ed14a0ec2/build-log/recording_build/TestAccComputeFirewallPolicy_firewallPolicyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/d0b871a8-1180-4305-ac6e-ca9ed14a0ec2/recording/TestAccComputeFirewallPolicy_firewallPolicyExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/d0b871a8-1180-4305-ac6e-ca9ed14a0ec2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/d0b871a8-1180-4305-ac6e-ca9ed14a0ec2/recording) for each test

2024-10-01 16:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 6 files changed, 81 insertions(+), 61 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 567 insertions(+), 212 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2024-10-01 16:34 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeFirewallPolicy_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/e9184d5e-b55c-418b-bcf1-a8c38d066fc1/build-log/recording_build/TestAccComputeFirewallPolicy_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/e9184d5e-b55c-418b-bcf1-a8c38d066fc1/recording/TestAccComputeFirewallPolicy_update.log)]


🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/e9184d5e-b55c-418b-bcf1-a8c38d066fc1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/e9184d5e-b55c-418b-bcf1-a8c38d066fc1/recording) for each test

2024-10-24 18:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 9 files changed, 325 insertions(+), 64 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 11 files changed, 587 insertions(+), 210 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Field `firewall_policy_id` within resource `google_compute_firewall_policy` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes#resource-schema-field-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-10-24 18:34 UTC, modular-magician commented
#### Tests analytics
Total tests: 1040
Passed tests: 960
Skipped tests: 73
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten</li>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeFirewallPolicyRule_update</li>
<li>TestAccComputeFirewallPolicy_firewallPolicyExample</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-24 18:40 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeFirewallPolicyAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccComputeFirewallPolicy_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicy_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccComputeFirewallPolicy_firewallPolicyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/build-log/recording_build/TestAccComputeFirewallPolicy_firewallPolicyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording/TestAccComputeFirewallPolicy_firewallPolicyExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/65d0be55-f643-4846-816b-164868884198/recording) for each test

2024-10-29 17:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 8 files changed, 186 insertions(+), 64 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 10 files changed, 470 insertions(+), 204 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2024-10-29 17:50 UTC, trodge requested changes
I'm worried that these test changes might be concealing bugs.

2024-10-29 17:50 UTC, trodge commented on mmv1/third_party/terraform/services/compute/resource_compute_firewall_policy_association_test.go
Do these test changes need to be included in this PR? They seem to be tests for a different resource.

2024-10-29 17:50 UTC, trodge commented on mmv1/third_party/terraform/services/compute/resource_compute_firewall_policy_rule_test.go.tmpl
Why are there changes to these firewall policy rule tests when this PR is for migrating the firewall policy resource?

2024-10-29 17:50 UTC, trodge commented on mmv1/third_party/terraform/services/compute/resource_compute_firewall_policy_test.go.tmpl
> +  parent      = "%s"
Why is the parent of this resource changing from the folder to the org?

2024-10-29 18:13 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeFirewallPolicyAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccComputeFirewallPolicy_firewallPolicyExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicy_firewallPolicyExample.log)]
`TestAccComputeFirewallPolicy_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeFirewallPolicy_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccComputeInstanceConfidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/build-log/recording_build/TestAccComputeInstanceConfidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeInstanceConfidentialInstanceConfigMain.log)]
`TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/build-log/recording_build/TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording/TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/930f4bfd-ae9c-44d2-81e4-2e80cb6c82ae/recording) for each test

2024-11-04 19:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 5 files changed, 170 insertions(+), 37 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 7 files changed, 454 insertions(+), 177 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2024-11-04 19:34 UTC, modular-magician commented
#### Tests analytics
Total tests: 1060
Passed tests: 980
Skipped tests: 73
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyRule_basic</li>
<li>TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample</li>
<li>TestAccComputeFirewallPolicyRule_multipleRules</li>
<li>TestAccComputeFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeFirewallPolicyRule_update</li>
<li>TestAccComputeFirewallPolicy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 19:37 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeFirewallPolicyAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyRule_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyRule_basic.log)]
`TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample.log)]
`TestAccComputeFirewallPolicyRule_multipleRules` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccComputeFirewallPolicyRule_securityProfileGroup_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeFirewallPolicyRule_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccComputeFirewallPolicy_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording/TestAccComputeFirewallPolicy_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/545c09a2-9ca4-4478-a2f2-6cbdc5921c3c/recording) for each test

2024-11-05 19:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 2 files changed, 56 insertions(+), 33 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 7 files changed, 454 insertions(+), 175 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2024-11-05 19:25 UTC, modular-magician commented
#### Tests analytics
Total tests: 1060
Passed tests: 986
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeFirewallPolicy_firewallPolicyExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-05 19:25 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeFirewallPolicy_firewallPolicyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/96e4318f-d05a-4b7d-b45d-a378b42c1aa3/build-log/recording_build/TestAccComputeFirewallPolicy_firewallPolicyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/96e4318f-d05a-4b7d-b45d-a378b42c1aa3/recording/TestAccComputeFirewallPolicy_firewallPolicyExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/96e4318f-d05a-4b7d-b45d-a378b42c1aa3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/96e4318f-d05a-4b7d-b45d-a378b42c1aa3/recording) for each test

2024-11-05 21:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 2 files changed, 58 insertions(+), 33 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 7 files changed, 458 insertions(+), 175 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2024-11-05 22:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 1060
Passed tests: 987
Skipped tests: 73
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/7be8f7ee-f274-4c45-b1a8-ab7ae47a9633/build-log/replaying_test.log)

2024-12-19 14:29 UTC, Samir-Cit commented
@shuyama1, @trodge and @slevenick 
Can you do the Code Review in this Pull Request?

This is the last one regading move the Firewall Policy resources from DCL to MMv1.

Thanks.

2025-01-08 22:22 UTC, trodge commented on mmv1/products/compute/FirewallPolicy.yaml
> +update_verb: 'PATCH'
Should this resource be using `legacy_long_form_project`?

2025-01-08 22:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 2 files changed, 58 insertions(+), 33 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 8 files changed, 458 insertions(+), 200 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2025-01-08 23:46 UTC, modular-magician commented
#### Tests analytics
Total tests: 4412
Passed tests: 3976
Skipped tests: 429
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeDeveloper_apigeeDeveloperUpdateTest</li>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccComputeFirewallPolicyAssociation_basic</li>
<li>TestAccComputeFirewallPolicyAssociation_organization</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccStorageTransferReplicationJob_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-09 00:36 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccApigeeDeveloper_apigeeDeveloperUpdateTest` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccApigeeDeveloper_apigeeDeveloperUpdateTest.log)]
`TestAccComputeFirewallPolicyAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicyAssociation_organization` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccComputeFirewallPolicyAssociation_organization.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccStorageTransferReplicationJob_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/build-log/replaying_build_after_recording/TestAccStorageTransferReplicationJob_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/replaying_after_recording/TestAccStorageTransferReplicationJob_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording/TestAccEphemeralServiceAccountKey_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/03b34abd-7f7d-4fee-b600-d42f5849ba5e/recording) for each test

2025-01-09 13:45 UTC, Samir-Cit commented on mmv1/products/compute/FirewallPolicy.yaml
> +update_verb: 'PATCH'
This resource is not bind to the project.
I tryied to use this `legacy_long_form_project` and the resource fails to create because it remove the reference from the parent.

Eg.: You are using the parent as `organizations/<ORG_ID>`, the code removes the **organizations/** so it will try to use only the **<ORG_ID>** and then throws the following error
```
{
  "error": {
    "code": 404,
    "message": "The resource '<ORG_ID>' was not found",
    "errors": [
      {
        "message": "The resource '<ORG_ID>' was not found",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
```

2025-01-30 15:29 UTC, maxi-cit commented
Hello @trodge, I updated this PR could you run tests again please?

2025-01-30 18:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11357-old..auto-pr-11357) ( 2 files changed, 58 insertions(+), 33 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11357-old..auto-pr-11357) ( 8 files changed, 470 insertions(+), 200 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11357-old..auto-pr-11357) ( 1 file changed, 99 insertions(+))

2025-01-30 19:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 4531
Passed tests: 4093
Skipped tests: 430
Affected tests: 8

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccCloudbuildWorkerPool_basic</li>
<li>TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample</li>
<li>TestAccComputeFirewallPolicyRule_firewallPolicyRuleNetworkScopeExample</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample</li>
<li>TestAccStorageTransferReplicationJob_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-30 19:50 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccComputeFirewallPolicyRule_firewallPolicyRuleExample.log)]
`TestAccComputeFirewallPolicyRule_firewallPolicyRuleNetworkScopeExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccComputeFirewallPolicyRule_firewallPolicyRuleNetworkScopeExample.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccStorageTransferReplicationJob_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccCloudbuildWorkerPool_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/recording_build/TestAccCloudbuildWorkerPool_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccCloudbuildWorkerPool_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/recording_build/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11357/artifacts/c1c7dcc2-1765-4980-a01c-d76b57eda39a/recording) for each test

2025-02-04 21:24 UTC, trodge approved these changes

2025-02-04 21:25 UTC, merged