Example fix
GoogleCloudPlatform/magic-modules pull request #11407
Opened 2024-08-08 23:54 UTC by bcreddy-gcp

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-08-09 00:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))

2024-08-09 00:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 20
Passed tests: 20
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>workbench</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11407/artifacts/dc2c2c9c-9e26-4b09-b747-8f1e4aa17888/build-log/replaying_test.log)

2024-08-09 02:06 UTC, c2thorn requested changes
is there an associated github issue and/or bug? Is this scenario covered by tests / how was this tested?

2024-08-09 02:06 UTC, c2thorn commented on mmv1/templates/terraform/constants/workbench_instance.go
> +	"cos-update-strategy",
```suggestion
    "cos-update-strategy",
```

2024-08-09 02:06 UTC, c2thorn commented on mmv1/templates/terraform/constants/workbench_instance.go
> +	"google-logging-enabled",
```suggestion
    "google-logging-enabled",
```

2024-08-09 18:35 UTC, bcreddy-gcp commented
b/357693909
https://github.com/hashicorp/terraform-provider-google/issues/18827.

2024-08-09 18:36 UTC, bcreddy-gcp commented
Similar PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/10900

2024-08-09 18:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))

2024-08-09 18:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))

2024-08-09 18:51 UTC, modular-magician commented
#### Tests analytics
Total tests: 20
Passed tests: 20
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>workbench</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11407/artifacts/d091629a-a5fb-4dc1-8fd0-8acc9849d357/build-log/replaying_test.log)

2024-08-09 18:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 20
Passed tests: 20
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>workbench</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11407/artifacts/a9193ee8-ca5b-4402-ac63-1bfbe8a10170/build-log/replaying_test.log)

2024-08-13 18:03 UTC, c2thorn commented on mmv1/templates/terraform/constants/workbench_instance.go
> +	"service-account-mode",
```suggestion
    "service-account-mode",
```

2024-08-13 18:07 UTC, c2thorn approved these changes

2024-08-13 18:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11407-old..auto-pr-11407) ( 1 file changed, 3 insertions(+))

2024-08-13 20:09 UTC, c2thorn approved these changes

2024-08-13 20:09 UTC, merged