## draft
GoogleCloudPlatform/magic-modules pull request #11424
Opened 2024-08-12 12:46 UTC by abd-goog

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-08-12 13:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 50 insertions(+), 28 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 50 insertions(+), 28 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-12 13:04 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccFolder_tags
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/3eca64e8-90ee-4323-a58d-3a34529cc3a2/build-log/replaying_test.log)

2024-08-12 19:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 54 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 54 insertions(+), 1 deletion(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-12 19:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccFolder_tags
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/e16f8c3f-edb6-438b-9bae-c371b1baf686/build-log/replaying_test.log)

2024-08-12 19:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 52 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 52 insertions(+), 4 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-12 19:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 52 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 2 files changed, 52 insertions(+), 4 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-12 19:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccFolder_tags
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/0713d7da-f904-49a8-a171-68efc32cb12c/build-log/replaying_test.log)

2024-08-12 19:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccFolder_tags
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/b1a1ca5e-acdc-4443-91d2-74c2c62580e4/build-log/replaying_test.log)

2024-08-13 09:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 4 files changed, 95 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 4 files changed, 95 insertions(+), 4 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_folder` (135 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_folder" "primary" {
  tags = # value needed
}


```

2024-08-13 09:18 UTC, modular-magician commented
#### Tests analytics
Total tests: 145
Passed tests: 114
Skipped tests: 30
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFolder_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-13 09:18 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording/TestAccFolder_tags.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording) for each test

2024-08-13 09:36 UTC, abd-goog commented
Hi @slevenick @zli82016 , can we include this change in the major release? Or it needs to go in one of the regular releases later?

2024-08-13 09:40 UTC, abd-goog commented
> Tests failed during RECORDING mode: `TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording/TestAccFolder_tags.log)]
> 
> Errors occurred during RECORDING mode. Please fix them to complete your PR.
> 
> View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording) for each test

@zli82016 The test passes on local, but would need help from TF team to add the tags resource in the test organization and provide tag admin permission to VCR test user.
Or should I mark this test as skipped?

2024-08-13 15:55 UTC, zli82016 commented
> Hi @slevenick @zli82016 , can we include this change in the major release? Or it needs to go in one of the regular releases later?

@abd-goog , do you know how many resources `tags` need to be added?

2024-08-14 04:28 UTC, abd-goog commented
> > Hi @slevenick @zli82016 , can we include this change in the major release? Or it needs to go in one of the regular releases later?
> 
> @abd-goog , do you know how many resources `tags` need to be added?

@zli82016 right now only CRM projects and folders are eligible and CRM wants to go GA with Tagging at creation as soon as possible. 
There will be other resources in the coming months but for now we need to prioritize for Projects and Folders only.

2024-08-14 15:15 UTC, zli82016 commented
> > > Hi @slevenick @zli82016 , can we include this change in the major release? Or it needs to go in one of the regular releases later?
> > 
> > 
> > @abd-goog , do you know how many resources `tags` need to be added?
> 
> @zli82016 right now only CRM projects and folders are eligible and CRM wants to go GA with Tagging at creation as soon as possible. There will be other resources in the coming weeks but for now we need to prioritize for Projects and Folders only.

Either major release or later regular release is fine.

2024-08-14 15:23 UTC, abd-goog commented
> > > > Hi @slevenick @zli82016 , can we include this change in the major release? Or it needs to go in one of the regular releases later?
> > > 
> > > 
> > > @abd-goog , do you know how many resources `tags` need to be added?
> > 
> > 
> > @zli82016 right now only CRM projects and folders are eligible and CRM wants to go GA with Tagging at creation as soon as possible. There will be other resources in the coming weeks but for now we need to prioritize for Projects and Folders only.
> 
> Either major release or later regular release is fine.

Would be great to get it in the major release. FYI the PR for projects resource: https://github.com/GoogleCloudPlatform/magic-modules/pull/11440

2024-08-14 16:24 UTC, zli82016 commented
> > Tests failed during RECORDING mode: `TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording/TestAccFolder_tags.log)]
> > Errors occurred during RECORDING mode. Please fix them to complete your PR.
> > View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording) for each test
> 
> @zli82016 The test passes on local, but would need help from TF team to add the tags resource in the test organization and provide tag admin permission to VCR test user. Or should I mark this test as skipped?

What do you mean to add the tags resource in the test organization? 
This is the post request:
```

{
 "displayName": "tf-test-k7z9737heo",
 "parent": "organizations/529579013760",
 "tags": {
  "529579013760/env": "test"
 }
}

```
should the tag `"529579013760/env": "test"` exist before creating the new folder?

2024-08-14 18:14 UTC, zli82016 commented
> > Tests failed during RECORDING mode: `TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording/TestAccFolder_tags.log)]
> > Errors occurred during RECORDING mode. Please fix them to complete your PR.
> > View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording) for each test
> 
> @zli82016 The test passes on local, but would need help from TF team to add the tags resource in the test organization and provide tag admin permission to VCR test user. Or should I mark this test as skipped?



> > Tests failed during RECORDING mode: `TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording/TestAccFolder_tags.log)]
> > Errors occurred during RECORDING mode. Please fix them to complete your PR.
> > View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/2279332b-8113-4854-aeff-5cee4dfc49c3/recording) for each test
> 
> @zli82016 The test passes on local, but would need help from TF team to add the tags resource in the test organization and provide tag admin permission to VCR test user. Or should I mark this test as skipped?

You need to create the tags resource with Terraform configuration in the same test.

2024-08-14 21:40 UTC, zli82016 requested changes
Modify test to include tags creation.

2024-09-04 09:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_folder` (143 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_folder" "primary" {
  tags = # value needed
}


```

2024-09-04 09:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccFolder_tags
$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/a4462dce-a433-456c-ab77-0d4543402925/build-log/replaying_test.log)

2024-09-04 09:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_folder` (145 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_folder" "primary" {
  tags = # value needed
}


```

2024-09-04 10:00 UTC, modular-magician commented
#### Tests analytics
Total tests: 147
Passed tests: 116
Skipped tests: 30
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFolder_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-04 10:00 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/4988d63d-453e-44bd-a477-409c44337c66/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/4988d63d-453e-44bd-a477-409c44337c66/recording/TestAccFolder_tags.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/4988d63d-453e-44bd-a477-409c44337c66/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/4988d63d-453e-44bd-a477-409c44337c66/recording) for each test

2024-09-04 14:50 UTC, abd-goog commented
@zli82016 PTAL, have updated tests to use bootstrapping logic. Thanks!

2024-09-04 14:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_folder` (145 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_folder" "primary" {
  tags = # value needed
}


```

2024-09-04 15:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11424-old..auto-pr-11424) ( 3 files changed, 100 insertions(+), 4 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_folder` (145 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_folder" "primary" {
  tags = # value needed
}


```

2024-09-04 15:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 147
Passed tests: 116
Skipped tests: 30
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFolder_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-04 15:08 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccFolder_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/31a2f4cf-4d65-4142-b241-c9be1949806d/build-log/recording_build/TestAccFolder_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/31a2f4cf-4d65-4142-b241-c9be1949806d/recording/TestAccFolder_tags.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/31a2f4cf-4d65-4142-b241-c9be1949806d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/31a2f4cf-4d65-4142-b241-c9be1949806d/recording) for each test

2024-09-04 15:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 147
Passed tests: 116
Skipped tests: 30
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFolder_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-04 15:10 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccFolder_tags`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/b275bb09-8062-4fbc-970c-153bd124f12d/recording/TestAccFolder_tags.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/b275bb09-8062-4fbc-970c-153bd124f12d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11424/artifacts/b275bb09-8062-4fbc-970c-153bd124f12d/recording) for each test

2024-09-05 16:00 UTC, zli82016 approved these changes
LGTM

2024-09-05 16:00 UTC, merged