Add the source-regions examples to the HealthCheck yaml file.
GoogleCloudPlatform/magic-modules pull request #11459
Opened 2024-08-15 19:13 UTC by pournami-rajan

Add the source-regions examples to the HealthCheck yaml file which was missed during the google-beta changes in https://github.com/GoogleCloudPlatform/magic-modules/pull/10878.

```release-note:none

```

2024-08-15 19:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11459-old..auto-pr-11459) ( 2 files changed, 183 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11459-old..auto-pr-11459) ( 2 files changed, 183 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11459-old..auto-pr-11459) ( 12 files changed, 336 insertions(+))

2024-08-15 19:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 984
Passed tests: 908
Skipped tests: 72
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeHealthCheck_computeHealthCheckHttpSourceRegionsExample</li>
<li>TestAccComputeHealthCheck_computeHealthCheckHttpsSourceRegionsExample</li>
<li>TestAccComputeHealthCheck_computeHealthCheckTcpSourceRegionsExample</li>
<li>TestAccComputeInstance_bootDisk_storagePoolSpecified</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-15 19:42 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeHealthCheck_computeHealthCheckHttpSourceRegionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/recording/TestAccComputeHealthCheck_computeHealthCheckHttpSourceRegionsExample.log)]
`TestAccComputeHealthCheck_computeHealthCheckHttpsSourceRegionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/recording/TestAccComputeHealthCheck_computeHealthCheckHttpsSourceRegionsExample.log)]
`TestAccComputeHealthCheck_computeHealthCheckTcpSourceRegionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/recording/TestAccComputeHealthCheck_computeHealthCheckTcpSourceRegionsExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstance_bootDisk_storagePoolSpecified`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/build-log/recording_build/TestAccComputeInstance_bootDisk_storagePoolSpecified_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/recording/TestAccComputeInstance_bootDisk_storagePoolSpecified.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11459/artifacts/2c0c2ab8-10cd-4a7e-a3be-ca8554e9a8cf/recording) for each test

2024-08-21 20:44 UTC, NickElliot requested changes
can you add `min_version: beta` to the examples?

2024-08-21 20:48 UTC, pournami-rajan commented
> can you add `min_version: beta` to the examples?

Trying to understand, is this for better coverage? The GA changes were already in and was tested successfully.

2024-08-26 20:31 UTC, NickElliot approved these changes
I misunderstood with the linked PR being beta only -- LGTM

2024-08-26 20:32 UTC, merged