Add Private Service Connect to Looker
GoogleCloudPlatform/magic-modules pull request #11487
Opened 2024-08-19 14:27 UTC by efeelaiho

Adding Add Private Service Connect (PSC) connection to Looker instances 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Adding Add Private Service Connect (PSC) connection to Looker instances 
```

2024-08-19 14:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11487-old..auto-pr-11487) ( 1 file changed, 105 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  psc_config {
    allowed_vpcs = # value needed
    service_attachments {
      local_fqdn                    = # value needed
      target_service_attachment_uri = # value needed
    }
  }
  psc_enabled = # value needed
}


```

2024-08-19 14:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 5
Passed tests: 5
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/e929ac68-df40-4829-9b40-54e2a6b66ceb/build-log/replaying_test.log)

2024-08-21 15:38 UTC, efeelaiho commented
@c2thorn any thing I should do here to get this merged?

2024-08-21 15:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11487-old..auto-pr-11487) ( 1 file changed, 105 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  psc_config {
    allowed_vpcs = # value needed
    service_attachments {
      local_fqdn                    = # value needed
      target_service_attachment_uri = # value needed
    }
  }
  psc_enabled = # value needed
}


```

2024-08-21 15:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 5
Passed tests: 5
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/be4fe29d-b4bd-4c83-9721-e321ad83982a/build-log/replaying_test.log)

2024-08-27 20:01 UTC, c2thorn requested changes

2024-08-27 20:01 UTC, c2thorn commented on mmv1/templates/terraform/examples/looker_instance_psc.tf.erb
> +    // service_attachments: [{local_fqdn: "www.local-fqdn.com" target_service_attachment_uri: "projects/my-project/regions/us-east1/serviceAttachments/sa"}]
are these meant to be commented out? Terraform comments use "#"

But if you are trying to make an update test, that should be done in a handwritten file. I'm not sure if one already exists for looker, but you can see our documentation here: https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test

2024-08-27 20:01 UTC, c2thorn commented on mmv1/templates/terraform/examples/looker_instance_psc.tf.erb
> +resource "google_looker_instance" "<%= ctx[:primary_resource_id] %>" {
This file does not have a reference in the YAML so it is not doing anything

2024-08-28 16:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11487-old..auto-pr-11487) ( 2 files changed, 284 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11487-old..auto-pr-11487) ( 1 file changed, 105 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11487-old..auto-pr-11487) ( 4 files changed, 118 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  psc_config {
    allowed_vpcs = # value needed
    service_attachments {
      local_fqdn                    = # value needed
      target_service_attachment_uri = # value needed
    }
  }
  psc_enabled = # value needed
}


```

2024-08-28 16:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 5
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccLookerInstance_lookerInstancePscExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 16:52 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccLookerInstance_lookerInstancePscExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/cefeaeed-6950-4650-bf0d-605e16b14c26/build-log/recording_build/TestAccLookerInstance_lookerInstancePscExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/cefeaeed-6950-4650-bf0d-605e16b14c26/recording/TestAccLookerInstance_lookerInstancePscExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/cefeaeed-6950-4650-bf0d-605e16b14c26/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/cefeaeed-6950-4650-bf0d-605e16b14c26/recording) for each test

2024-08-28 16:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11487-old..auto-pr-11487) ( 3 files changed, 358 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11487-old..auto-pr-11487) ( 3 files changed, 358 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11487-old..auto-pr-11487) ( 1 file changed, 105 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11487-old..auto-pr-11487) ( 4 files changed, 118 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  psc_config {
    allowed_vpcs = # value needed
    service_attachments {
      local_fqdn                    = # value needed
      target_service_attachment_uri = # value needed
    }
  }
  psc_enabled = # value needed
}


```

2024-08-28 16:55 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccLookerInstance_lookerInstancePscExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/bf2b6ec5-027f-451f-a7bb-6a6fac26a507/build-log/recording_build/TestAccLookerInstance_lookerInstancePscExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/bf2b6ec5-027f-451f-a7bb-6a6fac26a507/recording/TestAccLookerInstance_lookerInstancePscExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/bf2b6ec5-027f-451f-a7bb-6a6fac26a507/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/bf2b6ec5-027f-451f-a7bb-6a6fac26a507/recording) for each test

2024-09-12 16:55 UTC, c2thorn requested changes
test is still failing with
```
        Error: Argument or block definition required
        
          on terraform_plugin_test.tf line 14, in resource "google_looker_instance" "looker-instance":
          14:     allowed_vpcs: ["projects/test-project/global/networks/test"]
        
        An argument or block definition is required here. To set an argument, use the
        equals sign "=" to introduce the argument value.
```

2024-09-18 18:39 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccLookerInstance_lookerInstancePscExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-18 19:36 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccLookerInstance_lookerInstancePscExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/657cb90a-e961-43c0-b6c4-bd6226157253/recording/TestAccLookerInstance_lookerInstancePscExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/657cb90a-e961-43c0-b6c4-bd6226157253/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11487/artifacts/657cb90a-e961-43c0-b6c4-bd6226157253/recording) for each test

2024-09-18 19:43 UTC, c2thorn commented on mmv1/products/looker/Instance.yaml
> +    name: pscEnabled
interesting... this is usually in the config field itself.

2024-09-18 19:44 UTC, c2thorn approved these changes

2024-09-18 19:44 UTC, merged