Add FIPS enablement option to Looker
GoogleCloudPlatform/magic-modules pull request #11488
Opened 2024-08-19 15:56 UTC by efeelaiho

Add FIPS enablement option to Looker 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Add FIPS enablement option to Looker 
```

2024-08-19 16:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11488-old..auto-pr-11488) ( 2 files changed, 36 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11488-old..auto-pr-11488) ( 2 files changed, 36 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11488-old..auto-pr-11488) ( 1 file changed, 10 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  fips_enabled = # value needed
}


```

2024-08-19 16:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 5
Passed tests: 5
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/45fb1789-7660-4d48-8cd5-e86a614c4459/build-log/replaying_test.log)

2024-08-19 16:30 UTC, ScottSuarez commented
Is this field GA? I don't see it documented at https://cloud.google.com/looker/docs/reference/rest/v1/projects.locations.instances

2024-08-19 16:41 UTC, efeelaiho commented
@ScottSuarez Hi, no it is not officially GA yet, it is behind a visibility label. However it is planned to be GA at the end of the month, with expectations to use the field immediately in Terraform once it GAs.

2024-08-19 16:56 UTC, ScottSuarez commented
Do you have a specific date? I want to make sure this field doesn't confuse customers as it won't be available at the time the release notes are published. In general I believe it might be okay in this instance as the delta between the next release and your feature release is potentially small.

2024-08-19 17:03 UTC, efeelaiho commented
So I do not have a specific date, but GA is immediately after our rollout which ends Sept 2/3

2024-08-19 17:23 UTC, ScottSuarez commented
From my team lead on merging changes before GA.
''
If they soft launch (i.e. launch API before the blog post / conference announcement) we can add it to the GA provider during the soft launch period

Otherwise we'd recommend EAP or beta depending on the situation, promoting to GA later. Beta if non-allowlisted and EAP otherwise.
''

2024-08-22 23:16 UTC, ScottSuarez reviewed
Waiting for GA

2024-09-12 15:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11488-old..auto-pr-11488) ( 3 files changed, 100 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11488-old..auto-pr-11488) ( 3 files changed, 100 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11488-old..auto-pr-11488) ( 1 file changed, 10 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11488-old..auto-pr-11488) ( 4 files changed, 113 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_looker_instance` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_looker_instance" "primary" {
  fips_enabled = # value needed
}


```

2024-09-12 15:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 5
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccLookerInstance_lookerInstanceFipsExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-12 15:43 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccLookerInstance_lookerInstanceFipsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/c6504a8a-ec80-4617-8b81-8a2ae8b0265c/build-log/recording_build/TestAccLookerInstance_lookerInstanceFipsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/c6504a8a-ec80-4617-8b81-8a2ae8b0265c/recording/TestAccLookerInstance_lookerInstanceFipsExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/c6504a8a-ec80-4617-8b81-8a2ae8b0265c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/c6504a8a-ec80-4617-8b81-8a2ae8b0265c/recording) for each test

2024-09-13 17:52 UTC, ScottSuarez requested changes

2024-09-13 17:52 UTC, ScottSuarez commented on mmv1/templates/terraform/examples/looker_instance_fips.tf.erb
> +  fips_enabled: true
```suggestion
  fips_enabled = true
```

2024-09-17 17:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11488-old..auto-pr-11488) ( 3 files changed, 98 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11488-old..auto-pr-11488) ( 3 files changed, 98 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11488-old..auto-pr-11488) ( 1 file changed, 10 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11488-old..auto-pr-11488) ( 4 files changed, 112 insertions(+))

2024-09-17 17:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 5
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>looker</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccLookerInstance_lookerInstanceFipsExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-17 18:09 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccLookerInstance_lookerInstanceFipsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/575eff32-f467-4da6-bfb4-aa36e83de95b/recording/TestAccLookerInstance_lookerInstanceFipsExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/575eff32-f467-4da6-bfb4-aa36e83de95b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11488/artifacts/575eff32-f467-4da6-bfb4-aa36e83de95b/recording) for each test

2024-09-17 20:59 UTC, ScottSuarez approved these changes

2024-09-17 20:59 UTC, merged