ResourceManager : Update error messages for resource `google_project_services` in google-beta
GoogleCloudPlatform/magic-modules pull request #11494
Opened 2024-08-19 22:17 UTC by shahmedhaCorp

release-note: b/331417946
Update error message while disabling service with usage 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
resourcemanager: Update error messages for resource `google_project_services` 

```

2024-08-19 22:19 UTC, shahmedhaCorp commented
Tested it 
previously the error message wasmentioning an internal flag replaces it with terraform supported flag.

Case where service has usage 

```
google_project_service.google-beta-instance: Destroying... [id=965486546155/compute.googleapis.com]
╷
│ Error: Error when reading or editing Project Service 965486546155/compute.googleapis.com: Error service "compute.googleapis.com" for project "965486546155": googleapi: Error 400: The service compute.googleapis.com has usage in the last 30 days. Please specify check_if_service_has_usage_on_destroy=false if you want to proceed with disabling the service.
│ Help Token: AQAb6BwxBc08KLeMfI9cDXFd9O9TPhuUIOVvhqiKlCsdaK-GP8CQHMylBVx8uD44HIeNAPeAskg1bx4VmzhUzZwDhoVZiAfaJsnVVxHGI8FwRKjm
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
│     "violations": [
│       {
│         "subject": "?error_code=100002\u0026service_name=compute.googleapis.com",
│         "type": "googleapis.com"
│       }
│     ]
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "serviceusage.googleapis.com",
│     "metadata": {
│       "service_name": "compute.googleapis.com"
│     },
│     "reason": "COMMON_SU_SERVICE_HAS_USAGE"
│   },
│   {
│     "@type": "type.googleapis.com/google.rpc.DebugInfo",
│     "detail": "[ORIGINAL ERROR] tenantmanager::100002: com.google.api.tenant.error.TenantManagerException: The service compute.googleapis.com has usage in the last 30 days. Please specify check_if_service_has_usage_on_destroy=false if you want to proceed with disabling the service. [google.rpc.error_details_ext] { code: 9 message: \"The service compute.googleapis.com has usage in the last 30 days. Please specify check_if_service_has_usage_on_destroy=false if you want to proceed with disabling the service.\\nHelp Token: AQAb6BwxBc08KLeMfI9cDXFd9O9TPhuUIOVvhqiKlCsdaK-GP8CQHMylBVx8uD44HIeNAPeAskg1bx4VmzhUzZwDhoVZiAfaJsnVVxHGI8FwRKjm\" details { [type.googleapis.com/google.rpc.PreconditionFailure] { violations { type: \"googleapis.com\" subject: \"?error_code=100002\u0026service_name=compute.googleapis.com\" } } } details { [type.googleapis.com/google.rpc.ErrorInfo] { reason: \"COMMON_SU_SERVICE_HAS_USAGE\" domain: \"serviceusage.googleapis.com\" metadata { key: \"service_name\" value: \"compute.googleapis.com\" } } } } 391798925 { 1: 100002 }"
│   }
│ ]
│ , failedPrecondition
│ 
│ 
```

2024-08-19 22:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 1 insertion(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 4 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-19 22:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 1 insertion(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 4 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-08-19 22:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/0a8a1069-cb23-4aa5-a94a-c613ef05ad60/build-log/replaying_test.log)

2024-08-19 22:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 4 insertions(+))

2024-08-19 22:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/ac846f65-33e2-4864-bde7-0581706ea7f9/build-log/replaying_test.log)

2024-08-19 22:50 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/cef45729-5efb-4e81-b9f9-9640e4723892/build-log/replaying_test.log)

2024-08-19 23:00 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/cd3bdd5b-7f47-46a2-baf2-a60e2fa807a9/build-log/replaying_test.log)

2024-08-19 23:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 4 insertions(+))

2024-08-19 23:12 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/18f5ac57-dea5-4ab2-b3f2-8c8ee0f81209/build-log/replaying_test.log)

2024-08-20 19:12 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/59cafebc-9383-45e8-b92f-cf102ca6c508/build-log/replaying_test.log)

2024-08-21 20:57 UTC, NickElliot requested changes
minor formatting tweaks, otherwise lgtm

2024-08-21 20:57 UTC, NickElliot commented on mmv1/third_party/terraform/services/resourcemanager/resource_google_project_service.go.erb
>  		return fmt.Errorf("Error disabling service %q for project %q: %v", service, project, err)
```suggestion
		<% unless version == 'ga' -%>
		if res, _ := regexp.MatchString("COMMON_SU_SERVICE_HAS_USAGE", err.Error()); res {
		return fmt.Errorf("Error disabling service %q for project %q: %v", service, project, strings.Replace(err.Error(), "check_if_service_has_usage=SKIP", "check_if_service_has_usage_on_destroy=false", -1))
		 }
		<% end -%>
		return fmt.Errorf("Error disabling service %q for project %q: %v", service, project, err)
```

2024-08-26 17:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11494-old..auto-pr-11494) ( 1 file changed, 4 insertions(+))

2024-08-26 17:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 144
Passed tests: 114
Skipped tests: 30
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>resourcemanager</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11494/artifacts/1ce85de5-9ff8-40e7-8137-6a6080f3e6f2/build-log/replaying_test.log)

2024-08-26 20:46 UTC, NickElliot approved these changes

2024-08-26 20:48 UTC, merged