feat: support nfs and gcs in cloudrun and cloudrunv2 GA provider
GoogleCloudPlatform/magic-modules pull request #11503
Opened 2024-08-20 20:49 UTC by bskaplan

Move nfs, and gcs/csi to GA provider in cloudrun and cloudrunv2

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement

cloudrun: support nfs and csi volumes (for cloud storage fuse) in GA provider
cloudrunv2: support nfs and gcs volumes in GA provider

```

2024-08-20 21:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 9 files changed, 830 insertions(+), 12 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 7 files changed, 77 insertions(+), 22 deletions(-))

2024-08-20 21:06 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 66
Skipped tests: 5
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrun</li>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunService_changeVolume</li>
<li>TestAccCloudRunService_csiVolume</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-20 21:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 9 files changed, 830 insertions(+), 12 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 7 files changed, 77 insertions(+), 22 deletions(-))

2024-08-20 21:08 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunService_csiVolume`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/24667a10-e3a9-4033-b4b5-229a1ac728bc/recording/TestAccCloudRunService_csiVolume.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunService_changeVolume`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/24667a10-e3a9-4033-b4b5-229a1ac728bc/build-log/recording_build/TestAccCloudRunService_changeVolume_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/24667a10-e3a9-4033-b4b5-229a1ac728bc/recording/TestAccCloudRunService_changeVolume.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/24667a10-e3a9-4033-b4b5-229a1ac728bc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/24667a10-e3a9-4033-b4b5-229a1ac728bc/recording) for each test

2024-08-20 21:14 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 67
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>
<li>cloudrun</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunService_changeVolume</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-20 21:15 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunService_changeVolume`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/f3ec7f2c-3100-420e-9d4c-2ebdcb2951fc/build-log/recording_build/TestAccCloudRunService_changeVolume_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/f3ec7f2c-3100-420e-9d4c-2ebdcb2951fc/recording/TestAccCloudRunService_changeVolume.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/f3ec7f2c-3100-420e-9d4c-2ebdcb2951fc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/f3ec7f2c-3100-420e-9d4c-2ebdcb2951fc/recording) for each test

2024-08-20 21:48 UTC, melinath commented
@bskaplan could you add the resource name to the release notes? Something like: `added x fields to the Y resource (ga)`

2024-08-20 21:55 UTC, melinath requested changes
It looks like the failing test is likely related. I think it might be because `testAccCloudRunService_cloudRunServiceWithEmptyDirVolume` sets `"run.googleapis.com/launch-stage" = "BETA"` in metadata.annotations but that was removed from `testAccCloudRunService_cloudRunServiceUpdateWithGcsVolume` in this PR. I'm a little unsure why it's showing up as a diff in `effective_annotations` though!

I'd recommend either adding a new function for the GA test or adding the annotation back to that function with a version guard around it.

2024-08-21 16:52 UTC, bskaplan commented
> It looks like the failing test is likely related. I think it might be because `testAccCloudRunService_cloudRunServiceWithEmptyDirVolume` sets `"run.googleapis.com/launch-stage" = "BETA"` in metadata.annotations but that was removed from `testAccCloudRunService_cloudRunServiceUpdateWithGcsVolume` in this PR. I'm a little unsure why it's showing up as a diff in `effective_annotations` though!
> 

I think this is caused by a bad interaction between the Cloud Run v1 provider and the effective_annotations feature, related to my change but not caused by it. When we switch from empty_dir (a beta feature in Cloud Run) to cloud storage (now a GA feature), Cloud Run removes the launch-stage annotation from the API response. Since the change to consider cloud storage a GA feature is on the server, I get the exact same error running the existing test against a clean copy of terraform-provider-google-beta.

2024-08-21 17:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 9 files changed, 791 insertions(+), 12 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 7 files changed, 80 insertions(+), 33 deletions(-))

2024-08-21 17:19 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunService_emptyDirVolume`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/2cc71aa9-f5b6-4596-9ca4-1cecec6cf1dc/recording/TestAccCloudRunService_emptyDirVolume.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/2cc71aa9-f5b6-4596-9ca4-1cecec6cf1dc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/2cc71aa9-f5b6-4596-9ca4-1cecec6cf1dc/recording) for each test

2024-08-21 17:30 UTC, bskaplan commented
Filed https://github.com/hashicorp/terraform-provider-google/issues/19206 to follow up on the effective_annotations issue.

2024-08-22 17:23 UTC, melinath commented
Running tests in GA to be safe:
- https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUN/222906
- https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUNV2/222907

2024-08-22 18:03 UTC, melinath requested changes

2024-08-22 18:03 UTC, melinath commented on mmv1/third_party/terraform/services/cloudrunv2/resource_cloud_run_v2_job_test.go.erb
>  func TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate(t *testing.T) {
TestAccCloudRunV2Service_cloudrunv2ServiceMountGcsExample, TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume, and TestAccCloudRunV2Service_cloudrunv2ServiceMountNfsExample also fail with similar diffs (but in the `google_cloud_run_v2_service` resource)

2024-08-22 20:39 UTC, melinath requested changes
it looks like there are some merge conflicts that need to be resolved

2024-08-22 21:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 809 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 93 insertions(+), 40 deletions(-))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11503-old..auto-pr-11503) ( 2 files changed, 1 insertion(+), 2 deletions(-))

2024-08-22 21:57 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 61
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>
<li>cloudrun</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunService_emptyDirVolume</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-22 21:58 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunService_emptyDirVolume`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/ceff7b3c-0993-4253-be92-06e676024ad1/recording/TestAccCloudRunService_emptyDirVolume.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/ceff7b3c-0993-4253-be92-06e676024ad1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/ceff7b3c-0993-4253-be92-06e676024ad1/recording) for each test

2024-08-22 22:33 UTC, bskaplan commented
Had some merge conflicts because it looks like the v6 changes were moved to main. It doesn't look like the current unit test failures are related to my change though, none of them are in Cloud Run tests.

2024-08-23 16:24 UTC, melinath commented
Running tests in GA again.

Cloudrun: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUN/223359?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true
Cloudrunv2: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUNV2/223360?hideTestsFromDependencies=false&hideProblemsFromDependencies=false

2024-08-23 17:13 UTC, melinath requested changes
It looks like the TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume is still failing in the GA provider with a diff on `~ launch_stage            = "GA" -> "BETA"`

2024-08-23 17:45 UTC, bskaplan commented
ok, got that one passing locally now.

2024-08-23 17:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 808 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 93 insertions(+), 41 deletions(-))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11503-old..auto-pr-11503) ( 2 files changed, 1 insertion(+), 2 deletions(-))

2024-08-23 18:00 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 62
Skipped tests: 11
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrun</li>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/07692a95-e3f9-4cbd-be6c-898bc51b0d76/build-log/replaying_test.log)

2024-08-28 17:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 808 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 93 insertions(+), 41 deletions(-))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11503-old..auto-pr-11503) ( 2 files changed, 1 insertion(+), 2 deletions(-))

2024-08-28 17:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 62
Skipped tests: 11
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrun</li>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/77397b92-2b91-4466-8711-5334d14debc4/build-log/replaying_test.log)

2024-08-28 22:20 UTC, melinath requested changes

2024-08-28 22:20 UTC, melinath commented on mmv1/third_party/terraform/services/cloudrun/resource_cloud_run_service_test.go.erb
> +  }
per https://github.com/hashicorp/terraform-provider-google/issues/19206#issuecomment-2315983310

```suggestion
```

2024-08-28 22:20 UTC, melinath commented on mmv1/third_party/terraform/services/cloudrun/resource_cloud_run_service_test.go.erb
>  `, name, project)
per https://github.com/hashicorp/terraform-provider-google/issues/19206#issuecomment-2315983310, also remove the lifecycle.ignore_changes directly above this line.

2024-08-28 23:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 803 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11503-old..auto-pr-11503) ( 10 files changed, 87 insertions(+), 45 deletions(-))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11503-old..auto-pr-11503) ( 2 files changed, 1 insertion(+), 2 deletions(-))

2024-08-28 23:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 73
Passed tests: 62
Skipped tests: 11
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrun</li>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests



Tests were added that are GA-only additions and require manual runs:
- TestAccCloudRunService_csiVolume
- TestAccCloudRunV2Job_cloudrunv2JobWithGcsUpdate
- TestAccCloudRunV2Job_cloudrunv2JobWithNfsUpdate
- TestAccCloudRunV2Service_cloudrunv2ServiceGcsVolume
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11503/artifacts/ffa237a3-68ca-4983-9889-6aeb7a06b2cd/build-log/replaying_test.log)

2024-08-29 15:18 UTC, melinath commented
GA tests:

CloudRun: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUN/226387?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true
CloudRunV2: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_CLOUDRUNV2/226388?hideTestsFromDependencies=false&hideProblemsFromDependencies=false

2024-09-03 23:03 UTC, melinath approved these changes

2024-09-03 23:04 UTC, merged