Add service mesh field to Cloud Run v2 Service
GoogleCloudPlatform/magic-modules pull request #11502
Opened 2024-08-20 19:25 UTC by ian-mi

Adds support for Cloud Service Mesh configuration in Cloud Run v2 Services.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrunv2: added `service_mesh` to `google_cloud_run_v2_service`.
```

2024-08-20 19:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 2 files changed, 118 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 181 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-20 19:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 2 files changed, 118 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 181 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-20 19:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 43
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-20 19:41 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f1067d3f-ec57-49bb-b44d-ea89f6614511/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f1067d3f-ec57-49bb-b44d-ea89f6614511/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f1067d3f-ec57-49bb-b44d-ea89f6614511/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f1067d3f-ec57-49bb-b44d-ea89f6614511/recording) for each test

2024-08-20 19:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 43
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-20 19:43 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/aa8293f3-931b-4d93-bc3f-221de6a1669f/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/aa8293f3-931b-4d93-bc3f-221de6a1669f/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/aa8293f3-931b-4d93-bc3f-221de6a1669f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/aa8293f3-931b-4d93-bc3f-221de6a1669f/recording) for each test

2024-08-20 20:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 43
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-20 20:49 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4cdd536b-02b9-4d1f-b62a-72c19a0ccc35/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4cdd536b-02b9-4d1f-b62a-72c19a0ccc35/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4cdd536b-02b9-4d1f-b62a-72c19a0ccc35/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4cdd536b-02b9-4d1f-b62a-72c19a0ccc35/recording) for each test

2024-08-22 17:16 UTC, zli82016 requested changes
Test is failed.

2024-08-29 15:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 42 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 157 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-29 15:51 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/e90d3b57-dc01-4eb0-816c-4f4a96204146/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/e90d3b57-dc01-4eb0-816c-4f4a96204146/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/e90d3b57-dc01-4eb0-816c-4f4a96204146/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/e90d3b57-dc01-4eb0-816c-4f4a96204146/recording) for each test

2024-08-29 16:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 49 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 174 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-29 16:20 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 38
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 16:22 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/d2cbdff6-d10f-4c51-b18e-2737ba1b732a/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/d2cbdff6-d10f-4c51-b18e-2737ba1b732a/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/d2cbdff6-d10f-4c51-b18e-2737ba1b732a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/d2cbdff6-d10f-4c51-b18e-2737ba1b732a/recording) for each test

2024-08-29 16:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 176 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-29 16:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 38
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 16:50 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4b617564-4a4b-4e60-ac73-5e5f71b1e9c3/build-log/recording_build/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4b617564-4a4b-4e60-ac73-5e5f71b1e9c3/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4b617564-4a4b-4e60-ac73-5e5f71b1e9c3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/4b617564-4a4b-4e60-ac73-5e5f71b1e9c3/recording) for each test

2024-08-29 17:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 176 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-29 17:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 38
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 17:17 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/a45e4a71-0151-45e9-8a5e-6f2f07ae11b1/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/a45e4a71-0151-45e9-8a5e-6f2f07ae11b1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/a45e4a71-0151-45e9-8a5e-6f2f07ae11b1/recording) for each test

2024-08-29 17:27 UTC, ian-mi commented
> Test `TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample` is failed.

Fixed by adding a 1 minute delay after mesh creation. Additional changes were also needed due to the recent deletion protection change.

2024-08-29 21:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 176 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-29 21:55 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 39
Skipped tests: 5
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/cf6d22fb-34ab-41a1-a854-f640e0bca2bd/build-log/replaying_test.log)

2024-08-30 19:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 176 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-30 19:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 39
Skipped tests: 5
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/99e1a816-6b0f-41a0-9d3a-08b64fe207cc/build-log/replaying_test.log)

2024-08-30 22:52 UTC, zli82016 commented
It looks like `service_mesh` is updatable. Can you please add an update test for the new field to this file https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/cloudrunv2/resource_cloud_run_v2_service_test.go.erb? 

Doc: https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test

Thanks.

2024-08-30 22:55 UTC, zli82016 requested changes

2024-08-30 22:55 UTC, zli82016 commented on mmv1/products/cloudrunv2/Service.yaml
> +      mesh_name: 'mesh'
```suggestion
      mesh_name: 'network-services-mesh'
```

The magic module will add `tf-test-` to the mesh_name with `-`. Resources with the prefix `tf-test-` will be recognized by the sweeper and removed.

2024-08-30 23:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 3 files changed, 176 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-30 23:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 38
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-30 23:24 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/dde577d5-a26a-4f60-a111-68eb86cf5424/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/dde577d5-a26a-4f60-a111-68eb86cf5424/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/dde577d5-a26a-4f60-a111-68eb86cf5424/recording) for each test

2024-08-30 23:29 UTC, zli82016 requested changes
Update test is needed for the new field.

2024-08-31 00:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 4 files changed, 295 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-31 00:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 4 files changed, 295 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-31 00:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 50 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11502-old..auto-pr-11502) ( 4 files changed, 295 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11502-old..auto-pr-11502) ( 1 file changed, 30 insertions(+))

2024-08-31 00:44 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 39
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-31 00:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 39
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-31 00:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 45
Passed tests: 39
Skipped tests: 5
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>cloudrunv2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-31 00:48 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/6e00ae13-a5d7-4a3c-a881-77b97296563f/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/6e00ae13-a5d7-4a3c-a881-77b97296563f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/6e00ae13-a5d7-4a3c-a881-77b97296563f/recording) for each test

2024-08-31 00:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f4ca72b7-7593-4847-84cf-9d9c79487d49/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f4ca72b7-7593-4847-84cf-9d9c79487d49/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/f4ca72b7-7593-4847-84cf-9d9c79487d49/recording) for each test

2024-08-31 00:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/954554bd-692f-4026-8a4c-518924c05487/recording/TestAccCloudRunV2Service_cloudrunv2ServiceMeshUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/954554bd-692f-4026-8a4c-518924c05487/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11502/artifacts/954554bd-692f-4026-8a4c-518924c05487/recording) for each test

2024-09-03 17:24 UTC, zli82016 approved these changes
LGTM. Thanks for adding the new field.

2024-09-03 17:25 UTC, zli82016 commented
@bskaplan, do you have any comments?

2024-09-03 21:24 UTC, merged