Add new compute-network-firewall-policy-with-rules resource
GoogleCloudPlatform/magic-modules pull request #11524
Opened 2024-08-22 09:50 UTC by mihhalj

Add a new resource to allow updating all rules in network firewall policy at once.

Fixes 
https://github.com/hashicorp/terraform-provider-google/issues/19195

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_compute_network_firewall_policy_with_rules`
```

2024-08-26 21:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11524-old..auto-pr-11524) ( 2 files changed, 608 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11524-old..auto-pr-11524) ( 6 files changed, 3167 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11524-old..auto-pr-11524) ( 1 file changed, 541 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_network_firewall_policy_with_rules` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_network_firewall_policy_with_rules" "primary" {
  rule {
    rule_name               = # value needed
    security_profile_group  = # value needed
    target_service_accounts = # value needed
    tls_inspect             = # value needed
  }
}


```

2024-08-26 21:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/build-log/recording_build/TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/recording/TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample.log)]
`TestAccComputeNetworkFirewallPolicyWithRules_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/build-log/recording_build/TestAccComputeNetworkFirewallPolicyWithRules_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/recording/TestAccComputeNetworkFirewallPolicyWithRules_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/465d285b-9cc9-42c4-8a00-6c65cb45f61e/recording) for each test

2024-08-27 22:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11524-old..auto-pr-11524) ( 2 files changed, 637 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11524-old..auto-pr-11524) ( 6 files changed, 3286 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11524-old..auto-pr-11524) ( 1 file changed, 541 insertions(+))

2024-08-27 22:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 991
Passed tests: 910
Skipped tests: 77
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>
<li>TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample</li>
<li>TestAccComputeNetworkFirewallPolicyWithRules_update</li>
<li>TestAccComputeTargetHttpsProxy_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-27 22:33 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
`TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/recording/TestAccComputeNetworkFirewallPolicyWithRules_computeNetworkFirewallPolicyWithRulesFullExample.log)]
`TestAccComputeNetworkFirewallPolicyWithRules_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/recording/TestAccComputeNetworkFirewallPolicyWithRules_update.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/recording/TestAccComputeTargetHttpsProxy_update.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/689e3334-db82-44f4-9e6c-7807139eecb4/recording) for each test

2024-08-29 05:28 UTC, mihhalj commented
Could I ask fro review?
I ran my tests locally and they pass - not sure why TestReadPlannedAssetsCoverage* tests and VCR-test are failing.

2024-08-29 21:56 UTC, NickElliot requested changes
hi, a couple formatting changes needed

could you link me some of the public documentation on the resource?

2024-08-29 21:56 UTC, NickElliot commented on mmv1/templates/terraform/constants/resource_compute_network_firewall_policy_with_rules.go.erb
> +func  networkFirewallPolicyWithRulesSplitPredefinedRules(allRules []interface{}) ([]interface{}, []interface{}, error) {
```suggestion
func networkFirewallPolicyWithRulesSplitPredefinedRules(allRules []interface{}) ([]interface{}, []interface{}, error) {
```

2024-08-29 21:56 UTC, NickElliot commented on mmv1/templates/terraform/decoders/resource_compute_network_firewall_policy_with_rules.go.erb
> +return res, nil
```suggestion
return res, nil

```

2024-08-29 21:56 UTC, NickElliot commented on mmv1/products/compute/NetworkFirewallPolicyWithRules.yaml
> +
```suggestion
```

2024-08-30 09:44 UTC, mihhalj commented
> hi, a couple formatting changes needed
> 
> could you link me some of the public documentation on the resource?

Docs:
https://cloud.google.com/firewall/docs/network-firewall-policies
https://cloud.google.com/compute/docs/reference/rest/v1/networkFirewallPolicies

For firewall policy there's a terraform resource (not possible to set rules):
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy

And the rules in firewall policy can be configured using:
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_network_firewall_policy_rule

The new google_compute_network_firewall_policy_with_rules would allow a user to configure firewall policy with all rules (it was suggested by [rileykarson](https://github.com/rileykarson) to create a new resource to handle it).

2024-09-04 20:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11524-old..auto-pr-11524) ( 2 files changed, 637 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11524-old..auto-pr-11524) ( 6 files changed, 3286 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11524-old..auto-pr-11524) ( 1 file changed, 541 insertions(+))

2024-09-04 20:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 868
Passed tests: 789
Skipped tests: 77
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>
<li>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-04 20:37 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11524/artifacts/d8e81e81-83a6-42d6-938b-831b010b979e/recording) for each test

2024-09-05 19:26 UTC, NickElliot approved these changes
LGTM

2024-09-05 19:26 UTC, merged

2024-11-08 19:29 UTC, joekohlsdorf commented
@mihhalj I have experimented with the new resource a little bit, it isn't great.

Adding a new rule between existing rules yields a plan which recreates all the rules following the new addition. The same happens when deleting a rule when multiple rules exist.
I haven't been able to verify it but when applying this it might even temporarily remove existing firewall while things are reshuffled rules causing outages.

2024-11-15 15:22 UTC, mihhalj commented
> @mihhalj I have experimented with the new resource a little bit, it isn't great.
> 
> Adding a new rule between existing rules yields a plan which recreates all the rules following the new addition. The same happens when deleting a rule when multiple rules exist. I haven't been able to verify it but when applying this it might even temporarily remove existing firewall while rules are reshuffled causing outages.

[joekohlsdorf](https://github.com/joekohlsdorf) Thanks for testing and You're right - using this resource when you update/remove/add even only one rule it results in updating all rules - the main goal for this resource is to be able to change many rules at once - it either succeeds and all the rules are updated or it fails and none of the rules are not updated - for example if one of the rule is invalid then the firewall policy won't be updated (there won't be a situation where valid rules are updated and invalid not).

Compare it to the case when you use [compute_network_firewall_policy_rule](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_network_firewall_policy_rule) resources for your rules - valid rules will be configured and the invalid not.