container - add hugepages config
GoogleCloudPlatform/magic-modules pull request #11541
Opened 2024-08-24 22:36 UTC by DrFaust92

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: add `hugepages_config` in `linux_node_config` in `google_container_node_pool` resource
```

2024-08-29 15:29 UTC, wyardley reviewed
Not from Google, but just pointing out one minor thing in the test.

Only other thought: if this is valid in `google_container_cluster.node_config` as well (which I think it is), that should probably have a separate update test; also, I noticed with #11272 at least, that updating the default nodepool when used in that context isn't always setup properly.

May be slightly different for this one, but I had to add some changes in [here](https://github.com/GoogleCloudPlatform/magic-modules/blob/b7538e9de350e770ddedc738e23094348746681b/mmv1/third_party/terraform/services/container/resource_container_cluster.go.erb#L3800-L3885) for that to work (assuming either the nodepool or the cluster needs to get updated there).

2024-08-29 22:39 UTC, melinath commented
Apologies for the delayed review - reassigning since I'll be OOO tomorrow.

2024-08-29 22:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 143 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 143 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (387 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      hugepages_config {
        hugepage_size_1g = # value needed
        hugepage_size_2m = # value needed
      }
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        hugepages_config {
          hugepage_size_1g = # value needed
          hugepage_size_2m = # value needed
        }
      }
    }
  }
}


```
Resource: `google_container_node_pool` (74 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_node_pool" "primary" {
  node_config {
    linux_node_config {
      hugepages_config {
        hugepage_size_1g = # value needed
      }
    }
  }
}


```

2024-08-29 23:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 205
Passed tests: 191
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerNodePool_withHugepageConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-29 23:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerNodePool_withHugepageConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/dadc17e7-5566-4165-b1e5-1899ab9e9dce/recording/TestAccContainerNodePool_withHugepageConfig.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/dadc17e7-5566-4165-b1e5-1899ab9e9dce/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/dadc17e7-5566-4165-b1e5-1899ab9e9dce/recording) for each test

2024-09-06 17:23 UTC, slevenick commented on mmv1/third_party/terraform/services/container/resource_container_node_pool_test.go.erb
> +				Config: testAccContainerNodePool_withHugepageConfig(cluster, np, networkName, subnetworkName, 1),
Yeah, this should be addressed

2024-09-06 17:23 UTC, slevenick requested changes
The update test doesn't seem to do anything. Please fix so that the config changes

2024-09-06 23:31 UTC, DrFaust92 commented
thanks [slevenick](https://github.com/slevenick), added + covered second param in that block as well

2024-09-09 13:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 144 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 144 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (387 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      hugepages_config {
        hugepage_size_1g = # value needed
        hugepage_size_2m = # value needed
      }
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        hugepages_config {
          hugepage_size_1g = # value needed
          hugepage_size_2m = # value needed
        }
      }
    }
  }
}


```

2024-09-09 14:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccContainerNodePool_withHugepageConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/5b414624-bd08-4d41-b621-10ee1423f09d/build-log/recording_build/TestAccContainerNodePool_withHugepageConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/5b414624-bd08-4d41-b621-10ee1423f09d/recording/TestAccContainerNodePool_withHugepageConfig.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/5b414624-bd08-4d41-b621-10ee1423f09d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/5b414624-bd08-4d41-b621-10ee1423f09d/recording) for each test

2024-09-09 14:03 UTC, slevenick requested changes
Failing with:
        Error: Invalid expression
        
          on terraform_plugin_test.tf line 26, in resource "google_container_node_pool" "np":
          26: 	    hugepage_size_1g = %!d(MISSING)

2024-09-17 14:41 UTC, DrFaust92 commented
thanks [slevenick](https://github.com/slevenick), fixed + tested properly

2024-09-18 14:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 145 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11541-old..auto-pr-11541) ( 3 files changed, 145 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (394 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      hugepages_config {
        hugepage_size_1g = # value needed
        hugepage_size_2m = # value needed
      }
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        hugepages_config {
          hugepage_size_1g = # value needed
          hugepage_size_2m = # value needed
        }
      }
    }
  }
}


```

2024-09-18 14:33 UTC, modular-magician commented
#### Tests analytics
Total tests: 211
Passed tests: 197
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerNodePool_withHugepageConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-18 14:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccContainerNodePool_withHugepageConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/0cbf3050-35af-4b12-b2ba-0357e36209d4/recording/TestAccContainerNodePool_withHugepageConfig.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/0cbf3050-35af-4b12-b2ba-0357e36209d4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11541/artifacts/0cbf3050-35af-4b12-b2ba-0357e36209d4/recording) for each test

2024-09-18 14:55 UTC, slevenick approved these changes
Thank you!

2024-09-18 14:56 UTC, merged