Memorystore
GoogleCloudPlatform/magic-modules pull request #11560
Opened 2024-08-28 02:04 UTC by himanikh

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-08-28 02:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11560-old..auto-pr-11560) ( 3 files changed, 491 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11560-old..auto-pr-11560) ( 13 files changed, 2971 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11560-old..auto-pr-11560) ( 1 file changed, 421 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_memorystore_instance` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_memorystore_instance" "primary" {
  persistence_config {
    aof_config {
      append_fsync = # value needed
    }
  }
}


```

2024-08-28 03:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 3934
Passed tests: 3511
Skipped tests: 411
Affected tests: 12

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceTemplate_withNamePrefix</li>
<li>TestAccComputeTargetHttpsProxy_update</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingAlloydbExample</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingMysqlExample</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingPostgresExample</li>
<li>TestAccMemorystoreInstance_memorystoreInstanceBasicExample</li>
<li>TestAccMemorystoreInstance_memorystoreInstanceFullExample</li>
<li>TestAccMemorystoreInstance_updateDeletionProtection</li>
<li>TestAccMemorystoreInstance_updatePersistence</li>
<li>TestAccMemorystoreInstance_updateRedisConfigs</li>
<li>TestAccMemorystoreInstance_updateReplicaCount</li>
<li>TestAccMemorystoreInstance_updateShardCount</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-08-28 03:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]
`TestAccComputeTargetHttpsProxy_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccComputeTargetHttpsProxy_update.log)]
`TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingAlloydbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingAlloydbExample.log)]
`TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingMysqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingMysqlExample.log)]
`TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingPostgresExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingPostgresExample.log)]
$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$
`TestAccComputeInstanceTemplate_withNamePrefix`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/build-log/replaying_build_after_recording/TestAccComputeInstanceTemplate_withNamePrefix_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/replaying_after_recording/TestAccComputeInstanceTemplate_withNamePrefix.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccMemorystoreInstance_memorystoreInstanceFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/build-log/recording_build/TestAccMemorystoreInstance_memorystoreInstanceFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccMemorystoreInstance_memorystoreInstanceFullExample.log)]
`TestAccMemorystoreInstance_updatePersistence`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/build-log/recording_build/TestAccMemorystoreInstance_updatePersistence_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording/TestAccMemorystoreInstance_updatePersistence.log)]

$\textcolor{red}{\textsf{Several tests got terminated during RECORDING mode.}}$
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11560/artifacts/610cc551-5fb9-4b75-8b1e-d1e61509ed8c/recording) for each test

2024-09-03 15:52 UTC, ScottSuarez requested changes
Waiting on testcases to be resolved. Let me know if you need help here.

2024-09-24 21:08 UTC, c2thorn commented
I believe this was completed in a separate pull request, hence the git conflicts. Closing.

2024-09-24 21:08 UTC, closed without merging