commit terraform-memcache-tags
GoogleCloudPlatform/magic-modules pull request #11576
Opened 2024-08-29 14:33 UTC by SamanthaMathews

This PR is to add tags field to Memcache Instance

release-note:enhancement

2024-08-29 15:07 UTC, SarahFrench reviewed
@SamanthaMathews Hi, thanks for opening a PR! Could you please sign the CLA and I can get started reviewing

2024-09-25 19:54 UTC, c2thorn commented
Discussing with @SamanthaMathews offline about this PR and the go rewrite migration

2024-09-27 18:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11576-old..auto-pr-11576) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_memcache_instance` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_memcache_instance" "primary" {
  tags = # value needed
}


```

2024-09-27 18:26 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>memcache</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccMemcacheInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-27 18:26 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccMemcacheInstance_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/0f948517-708f-47c3-885b-64272026309f/build-log/recording_build/TestAccMemcacheInstance_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/0f948517-708f-47c3-885b-64272026309f/recording/TestAccMemcacheInstance_tags.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/0f948517-708f-47c3-885b-64272026309f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/0f948517-708f-47c3-885b-64272026309f/recording) for each test

2024-09-28 13:32 UTC, abd-goog requested changes
Please fix breaking tests

2024-09-30 12:48 UTC, SamanthaMathews commented
@SarahFrench , could you please provide the approval for running automated test?

2024-09-30 15:56 UTC, SarahFrench commented
I just approved the tests to run. Also, please take a look at the CLA issue!

2024-09-30 16:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11576-old..auto-pr-11576) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_memcache_instance` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_memcache_instance" "primary" {
  tags = # value needed
}


```

2024-09-30 16:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>memcache</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccMemcacheInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-30 16:08 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccMemcacheInstance_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/f0102402-b5f5-44d4-ac30-33e705540f51/build-log/recording_build/TestAccMemcacheInstance_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/f0102402-b5f5-44d4-ac30-33e705540f51/recording/TestAccMemcacheInstance_tags.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/f0102402-b5f5-44d4-ac30-33e705540f51/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/f0102402-b5f5-44d4-ac30-33e705540f51/recording) for each test

2024-10-01 07:32 UTC, SamanthaMathews commented
Hi @SarahFrench , could you please provide the approval for running automated test again?
Also is there any way to retrigger this test without adding any random commits?

2024-10-01 11:50 UTC, SarahFrench commented
@SamanthaMathews I believe that the tests run automatically on push for Googlers who show on their profiles that they're a member of a Google-owned GitHub org (this is how our automation detects Googlers). To trigger the tests to run without pushing a new commit you can comment `/gcbrun` on the PR. I'll double check internally about the Googler stuff

2024-10-01 11:57 UTC, SarahFrench commented
Ah, I believe you need to be a member of https://github.com/googlers

2024-10-01 14:05 UTC, SarahFrench commented
Further to what I said above
- membership of the Googlers orgs needs to be public
- take a look at: go/terraform-contribution-guide#before-you-begin

2024-10-01 14:50 UTC, SamanthaMathews commented
Thanks @SarahFrench 
I am waiting for confirmation on something. Meanwhile do you mind triggering the test again?

2024-10-01 15:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11576-old..auto-pr-11576) ( 4 files changed, 90 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11576-old..auto-pr-11576) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_memcache_instance` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_memcache_instance" "primary" {
  tags = # value needed
}


```

2024-10-01 15:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>memcache</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccMemcacheInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-01 15:03 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccMemcacheInstance_tags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/b46db4cf-e98d-421f-80e2-eed2e74e6943/build-log/recording_build/TestAccMemcacheInstance_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/b46db4cf-e98d-421f-80e2-eed2e74e6943/recording/TestAccMemcacheInstance_tags.log)]


🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/b46db4cf-e98d-421f-80e2-eed2e74e6943/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11576/artifacts/b46db4cf-e98d-421f-80e2-eed2e74e6943/recording) for each test

2024-10-29 07:46 UTC, SamanthaMathews commented
@SarahFrench , the automated tests are failing. Could you please suggest a way to fix this?

2024-10-29 18:48 UTC, SarahFrench commented
Hi @SamanthaMathews, we can mark this PR as ready for review to work through the test failure, but first please address the failing CLA check.

2024-11-22 18:35 UTC, SarahFrench commented
@modular-magician reassign-reviewer

2025-02-18 07:52 UTC, SamanthaMathews commented
The contents of this code are entirely owned by Google LLC in accordance with the agreement between Google LLC and the third party submitting this code into Google's open source repository

2025-02-18 22:36 UTC, hao-nan-li reviewed
Not sure what happened as the logs are expired.

Could you sign the CLA?

2025-05-20 20:56 UTC, rileykarson commented
@SamanthaMathews I'm going to close this PR and get you to open a new one for your new changes- sorry for the hassle! I'd like to reduce the attention set  (i.e. the original reviewer is no longer on the project) and/or refresh some signals like the CLA in case that's changed.

2025-05-20 20:56 UTC, closed without merging