Making network field optional in Backupdr MS
GoogleCloudPlatform/magic-modules pull request #11575
Opened 2024-08-29 11:07 UTC by niharika-98

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-08-29 11:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 17 insertions(+), 17 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 2 files changed, 19 insertions(+), 19 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_management_server` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_management_server" "primary" {
  networks {
    network = # value needed
  }
}


```

2024-08-29 11:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 1
Passed tests: 1
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/7dc27865-d992-4119-8596-718679c25c18/build-log/replaying_test.log)

2024-08-29 15:09 UTC, roaks3 requested changes
Apologies if there's a limitation I've missed, but could you add a test (or probably better to modify an existing test) to not include these fields? This will help verify that they are in fact not required.

2024-09-02 06:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 17 insertions(+), 43 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 2 files changed, 19 insertions(+), 45 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_management_server` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_management_server" "primary" {
  networks {
    network = # value needed
  }
}


```

2024-09-02 06:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupVault_fullUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-02 06:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccBackupDRBackupVault_fullUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/09c958f7-cdc9-4c3c-abd1-f944b8ef269b/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/09c958f7-cdc9-4c3c-abd1-f944b8ef269b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/09c958f7-cdc9-4c3c-abd1-f944b8ef269b/recording) for each test

2024-09-02 06:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 17 insertions(+), 43 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 3 files changed, 19 insertions(+), 49 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_management_server` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_management_server" "primary" {
  networks {
    network = # value needed
  }
}


```

2024-09-02 06:36 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRManagementServer_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-02 06:36 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGoogleBackupDRManagementServer_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/b499bbc7-20f3-4574-8827-1e6a8617b3cb/build-log/recording_build/TestAccDataSourceGoogleBackupDRManagementServer_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/b499bbc7-20f3-4574-8827-1e6a8617b3cb/recording/TestAccDataSourceGoogleBackupDRManagementServer_basic.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/b499bbc7-20f3-4574-8827-1e6a8617b3cb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/b499bbc7-20f3-4574-8827-1e6a8617b3cb/recording) for each test

2024-09-02 06:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 17 insertions(+), 43 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 3 files changed, 19 insertions(+), 49 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_management_server` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_management_server" "primary" {
  networks {
    network = # value needed
  }
}


```

2024-09-02 06:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRManagementServer_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-02 06:42 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGoogleBackupDRManagementServer_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/0885c620-7482-48a3-bcd0-3873045989d8/build-log/recording_build/TestAccDataSourceGoogleBackupDRManagementServer_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/0885c620-7482-48a3-bcd0-3873045989d8/recording/TestAccDataSourceGoogleBackupDRManagementServer_basic.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/0885c620-7482-48a3-bcd0-3873045989d8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/0885c620-7482-48a3-bcd0-3873045989d8/recording) for each test

2024-09-02 09:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 17 insertions(+), 43 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 3 files changed, 19 insertions(+), 49 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_management_server` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_management_server" "primary" {
  networks {
    network = # value needed
  }
}


```

2024-09-02 09:06 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRManagementServer_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-02 09:06 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGoogleBackupDRManagementServer_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/c69bcf40-bc81-49ba-bd64-ac6450696d2e/build-log/recording_build/TestAccDataSourceGoogleBackupDRManagementServer_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/c69bcf40-bc81-49ba-bd64-ac6450696d2e/recording/TestAccDataSourceGoogleBackupDRManagementServer_basic.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/c69bcf40-bc81-49ba-bd64-ac6450696d2e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/c69bcf40-bc81-49ba-bd64-ac6450696d2e/recording) for each test

2024-09-04 21:18 UTC, roaks3 reviewed
It looks like there is still a test failure, potentially for another test. But to be clear, I don't think every existing test should be changed (unless you are doing that for another reason, like performance?). I expected there to be one test with this field removed, to prove it is not required.

2024-09-24 21:13 UTC, c2thorn commented
@niharika-98 

Tomorrow, the Magic Modules repository is scheduled to undergo a language migration from Ruby to Go. You can view more details about this in our announcement here: https://github.com/hashicorp/terraform-provider-google/issues/19583 (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)

This open pull request may become incompatible due to most YAML and .erb files converting to Go-compatible files.

However, the changes seem minor enough that editing the converted files should not be too difficult. The main difficulty will be rebasing after the migration, but I suggest simply opening a new pull request. That should be easier overall.

Let us know if you have any questions or issues.

2024-10-07 08:59 UTC, closed without merging

2024-10-07 09:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11575-old..auto-pr-11575) ( 3 files changed, 255 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11575-old..auto-pr-11575) ( 3 files changed, 255 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11575-old..auto-pr-11575) ( 1 file changed, 10 insertions(+))

2024-10-07 09:14 UTC, modular-magician commented
#### Tests analytics
Total tests: 55
Passed tests: 54
Skipped tests: 1
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>networkservices</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11575/artifacts/d572eb0d-79b1-43fa-977b-3d09965f332c/build-log/replaying_test.log)