continue sweeper run for other resources if no resource found
GoogleCloudPlatform/magic-modules pull request #11589
Opened 2024-08-30 06:36 UTC by Mehul3217

**Release Note Template for Downstream PRs (will be copied)**

```release-note:update
netapp: continue sweeper run for other locations if no resource found
```

2024-08-30 06:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 7 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 7 insertions(+), 7 deletions(-))

2024-08-30 07:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 18
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11589/artifacts/afcf2d40-a185-4c7e-9a64-43d084c03a74/build-log/replaying_test.log)

2024-09-03 23:06 UTC, melinath requested changes
All of the other `return nil` calls in all of these sweepers should also use `continue` instead

2024-09-09 05:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 7 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 7 insertions(+), 7 deletions(-))

2024-09-09 06:07 UTC, Mehul3217 commented
> All of the other `return nil` calls inside `for` loops in all of these sweepers should also use `continue` instead

Done

2024-09-09 06:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 35 insertions(+), 35 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11589-old..auto-pr-11589) ( 7 files changed, 35 insertions(+), 35 deletions(-))

2024-09-09 06:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 18
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11589/artifacts/15191971-ee74-4efe-a224-0ce1fac9b606/build-log/replaying_test.log)

2024-09-09 07:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 18
Passed tests: 18
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11589/artifacts/24f95584-e3e0-4fb2-99b5-0c99f9f6a0b5/build-log/replaying_test.log)

2024-09-09 15:40 UTC, merged