Adding data source "google_privileged_access_manger_entitlement"
GoogleCloudPlatform/magic-modules pull request #11588
Opened 2024-08-30 05:22 UTC by varsharmavs

```release-note:new-datasource
google_privileged_access_manager_entitlement
```

2024-09-03 15:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 2 files changed, 168 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 2 files changed, 168 insertions(+))

2024-09-03 15:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-03 15:48 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/a359efdc-63a4-4d53-acb6-fd6b7755143b/recording) for each test

2024-09-03 15:53 UTC, melinath requested changes

2024-09-03 15:53 UTC, melinath commented on mmv1/third_party/terraform/services/privilegedaccessmanager/data_source_privileged_access_manager_entitlement_test.go
> +	parent = "projects/%{project_name}"
`project_name` is missing from the context map in both of these test configurations. If the data source doesn't default to a project id for the parent, you'll need to use a `google_project` datasource to get the test project's project_id and interpolate it here. (Search for `data "google_project"` in the codebase for examples.)

2024-09-11 22:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 2 files changed, 169 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 2 files changed, 169 insertions(+))

2024-09-11 22:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-11 22:33 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/09657d4c-26cf-4080-8e4d-27de92eec315/recording) for each test

2024-09-11 22:42 UTC, melinath submitted a review, later dismissed

2024-09-11 22:42 UTC, melinath commented on mmv1/third_party/terraform/services/privilegedaccessmanager/data_source_privileged_access_manager_entitlement.go
> +func DataSourceGooglePrivilegedAccessManagerEntitlement() *schema.Resource {
you'll need to also add this to handwrittenDatasources in magic-modules/mmv1/third_party/terraform/provider/provider_mmv1_resources.go.erb - sorry for not catching this last time!

2024-09-11 22:42 UTC, melinath commented on mmv1/third_party/terraform/services/privilegedaccessmanager/data_source_privileged_access_manager_entitlement_test.go
> +	parent = "projects/${data.google_project.project.number}"
This is causing tests to fail with:

```
Error: Reference to undeclared resource
        
          on terraform_plugin_test.tf line 6, in resource "google_privileged_access_manager_entitlement" "tfentitlement":
           6: 	parent = "projects/${data.google_project.project.number}"
```

Possibly the dependencies are order-sensitive, and the datasource needs to go at the top of the test config?

2024-09-16 16:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))

2024-09-16 16:18 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-16 16:18 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/e5b347f3-e1a6-44d8-8d4a-5acca28b2b55/recording) for each test

2024-09-18 21:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))

2024-09-18 21:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-18 21:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/88cf9d29-789b-4598-a6da-fdddf30a9c6c/recording) for each test

2024-09-20 19:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 172 insertions(+))

2024-09-20 19:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-20 19:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/build-log/recording_build/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/ecac1be0-1b8b-49b0-9303-ee37dbd66e9b/recording) for each test

2024-09-23 20:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 175 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11588-old..auto-pr-11588) ( 3 files changed, 175 insertions(+))

2024-09-23 20:20 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privilegedaccessmanager</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic</li>
<li>TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-23 20:21 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/95377f2e-a2a4-4346-9c89-dfb24833f9f1/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_basic.log)]
`TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/95377f2e-a2a4-4346-9c89-dfb24833f9f1/recording/TestAccDataSourceGooglePrivilegedAccessManagerEntitlement_optionalProject.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/95377f2e-a2a4-4346-9c89-dfb24833f9f1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11588/artifacts/95377f2e-a2a4-4346-9c89-dfb24833f9f1/recording) for each test

2024-09-23 20:36 UTC, NickElliot approved these changes
Aligns with the PAM Entitlement resource implemented previously and tests are good, LGTM! One comment for formatting that I'll commit in myself so this can be merged before go conversion.

2024-09-23 20:36 UTC, NickElliot commented on mmv1/third_party/terraform/provider/provider_mmv1_resources.go.erb
> +	"google_privileged_access_manager_entitlement":		privilegedaccessmanager.DataSourceGooglePrivilegedAccessManagerEntitlement(),
```suggestion
	"google_privateca_certificate_authority":           privateca.DataSourcePrivatecaCertificateAuthority(),
	"google_privileged_access_manager_entitlement":     privilegedaccessmanager.DataSourceGooglePrivilegedAccessManagerEntitlement(),
```

2024-09-23 20:37 UTC, merged