Add a new resource for creating DataMapper Workspaces
GoogleCloudPlatform/magic-modules pull request #11603
Opened 2024-09-02 05:22 UTC by sana-google

Add a new resource for creating DataMapper Workspaces

Link: https://cloud.google.com/healthcare-api/healthcare-data-engine/docs/manage-workspaces
Fixes https://github.com/hashicorp/terraform-provider-google/issues/19222

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_healthcare_workspace`
```

2024-09-03 20:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 716 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 716 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11603-old..auto-pr-11603) ( 1 file changed, 115 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 114 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_healthcare_workspace` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_healthcare_workspace" "primary" {
  labels = # value needed
}


```

2024-09-03 20:33 UTC, modular-magician commented
#### Tests analytics
Total tests: 39
Passed tests: 38
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>healthcare</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-03 20:34 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/c665780d-26a8-492b-b29e-cfbdeb4366b3/build-log/recording_build/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/c665780d-26a8-492b-b29e-cfbdeb4366b3/recording/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/c665780d-26a8-492b-b29e-cfbdeb4366b3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/c665780d-26a8-492b-b29e-cfbdeb4366b3/recording) for each test

2024-09-05 22:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 726 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 726 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11603-old..auto-pr-11603) ( 1 file changed, 115 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 119 insertions(+))

2024-09-05 22:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 39
Passed tests: 38
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>healthcare</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-05 22:41 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/34e3e197-215e-40b0-9e34-5e548d03ef6b/build-log/recording_build/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/34e3e197-215e-40b0-9e34-5e548d03ef6b/recording/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/34e3e197-215e-40b0-9e34-5e548d03ef6b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/34e3e197-215e-40b0-9e34-5e548d03ef6b/recording) for each test

2024-09-06 16:40 UTC, ScottSuarez requested changes
Can you also add an update test.

See https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test

2024-09-09 16:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 726 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 726 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11603-old..auto-pr-11603) ( 1 file changed, 115 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 119 insertions(+))

2024-09-09 16:27 UTC, modular-magician commented
#### Tests analytics
Total tests: 39
Passed tests: 38
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>healthcare</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-09 16:27 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/ba1c807b-5ff9-48f6-a641-2aa1e8d13cb3/build-log/recording_build/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/ba1c807b-5ff9-48f6-a641-2aa1e8d13cb3/recording/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/ba1c807b-5ff9-48f6-a641-2aa1e8d13cb3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/ba1c807b-5ff9-48f6-a641-2aa1e8d13cb3/recording) for each test

2024-09-11 05:20 UTC, sana-google commented on mmv1/products/healthcare/Workspace.yaml
> +skip_sweeper: true
Yes, it will only exist within a dataset.

2024-09-11 05:22 UTC, sana-google commented
> Can you also add an update test.
> 
> See https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test

Added update test.

2024-09-13 18:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11603-old..auto-pr-11603) ( 5 files changed, 813 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11603-old..auto-pr-11603) ( 5 files changed, 813 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11603-old..auto-pr-11603) ( 1 file changed, 115 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11603-old..auto-pr-11603) ( 4 files changed, 119 insertions(+))

2024-09-13 18:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 40
Passed tests: 38
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>healthcare</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample</li>
<li>TestAccHealthcareWorkspace_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-13 18:23 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/61cd3357-3df4-40a0-936a-36e4bf26c95c/recording/TestAccHealthcareWorkspace_healthcareWorkspaceBasicExample.log)]
`TestAccHealthcareWorkspace_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/61cd3357-3df4-40a0-936a-36e4bf26c95c/recording/TestAccHealthcareWorkspace_update.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/61cd3357-3df4-40a0-936a-36e4bf26c95c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11603/artifacts/61cd3357-3df4-40a0-936a-36e4bf26c95c/recording) for each test

2024-09-13 20:47 UTC, ScottSuarez approved these changes

2024-09-13 20:47 UTC, merged