[Composer] Reveal cloud_data_lineage_integration to GA.
GoogleCloudPlatform/magic-modules pull request #11619
Opened 2024-09-03 11:54 UTC by ahidalgob

Google Cloud Composer has promoted Data Lineage integration to GA.
Fixes https://github.com/hashicorp/terraform-provider-google/issues/19345

    - release-note:new-resource

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
composer: promoted `config.0.workloads_config.0.cloud_data_lineage_integration` to GA in resource `google_composer_environment`
```

2024-09-03 11:58 UTC, ahidalgob commented
```
make testacc TEST=./google/services/composer/ TESTARGS='-run=TestAccComposerEnvironment_ComposerV2'
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google/services/composer/ -v -run=TestAccComposerEnvironment_ComposerV2 -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccComposerEnvironment_ComposerV2
=== PAUSE TestAccComposerEnvironment_ComposerV2
=== RUN   TestAccComposerEnvironment_ComposerV2HighResilience
=== PAUSE TestAccComposerEnvironment_ComposerV2HighResilience
=== CONT  TestAccComposerEnvironment_ComposerV2
=== CONT  TestAccComposerEnvironment_ComposerV2HighResilience
--- PASS: TestAccComposerEnvironment_ComposerV2 (1269.27s)
--- PASS: TestAccComposerEnvironment_ComposerV2HighResilience (1289.29s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google/services/composer 1289.711s
```

2024-09-03 12:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11619-old..auto-pr-11619) ( 3 files changed, 73 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11619-old..auto-pr-11619) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2024-09-09 21:26 UTC, NickElliot requested changes
minor docs edits needed but otherwise seems good

2024-09-09 21:26 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/r/composer_environment.html.markdown
>    Cloud Composer environments in versions composer-2.1.2-airflow-*.*.* and newer)
```suggestion
  (Optional) Cloud Composer environments in versions composer-2.1.2-airflow-*.*.* and newer)
```

2024-09-09 21:26 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/r/composer_environment.html.markdown
>    Cloud Composer environments in versions composer-2.1.2-airflow-*.*.* and later)
```suggestion
  (Optional) Cloud Composer environments in versions composer-2.1.2-airflow-*.*.* and later)
```

2024-09-10 15:04 UTC, ahidalgob commented on mmv1/third_party/terraform/website/docs/r/composer_environment.html.markdown
>    Cloud Composer environments in versions composer-2.1.2-airflow-*.*.* and later)
same as previous

2024-09-10 15:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11619-old..auto-pr-11619) ( 3 files changed, 73 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11619-old..auto-pr-11619) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2024-09-10 15:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11619-old..auto-pr-11619) ( 3 files changed, 73 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11619-old..auto-pr-11619) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2024-09-10 15:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11619-old..auto-pr-11619) ( 3 files changed, 73 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11619-old..auto-pr-11619) ( 1 file changed, 2 insertions(+), 4 deletions(-))

2024-09-12 21:29 UTC, NickElliot approved these changes
LGTM!

2024-09-24 20:27 UTC, merged