FixDoc google_vpc_access_connector [max,min]_throughput
GoogleCloudPlatform/magic-modules pull request #11612
Opened 2024-09-03 05:26 UTC by 0Delta

A change was made to check for duplicates for the following four items, but the documentation was not modified.
https://github.com/hashicorp/terraform-provider-google/commit/a2176b1bf08b4dca9c744a798c458efcb2d64903#diff-c3b7f8261da0f41a69f379fbef4757ab26a958b8a247ecce16ce09612d69bd1d
- `google_vpc_access_connector.max_throughput`
- `google_vpc_access_connector.min_throughput`
- `google_vpc_access_connector.max_instances`
- `google_vpc_access_connector.min_instances`

This PR clarifies that the values ​​are mutually exclusive and that `throughput` is deprecated.

release-note:none

2024-09-03 05:55 UTC, 0Delta commented
Sorry, the correct word is `discouraged`, not `deprecated`. I'll correct that.

In my native language, Japanese, it resolves to the same word :-[

2024-09-05 19:37 UTC, NickElliot requested changes
rewording the sentences a bit, don't worry about the term mixup here. Thanks for catching it!

2024-09-05 19:37 UTC, NickElliot commented on mmv1/products/vpcaccess/Connector.yaml
> +      min_throughput and min_instances cannot both be specified. Use min_instances instead. Use of min_throughput is now discouraged.
```suggestion
      Value must be a multiple of 100 from 200 through 900. Must be lower than the value specified by max_throughput.
      Only one of `min_throughput` and `min_instances` can be specified. The use of min_throughput is discouraged in favor of min_instances.
```

2024-09-05 19:37 UTC, NickElliot commented on mmv1/products/vpcaccess/Connector.yaml
> +      min_throughput. max_throughput and max_instances cannot both be specified. Use max_instances instead. Use of max_throughput is now discouraged.
```suggestion
      min_throughput. Only one of `max_throughput` and `max_instances` can be specified. The use of max_throughput is discouraged in favor of max_instances.
```

2024-09-05 19:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11612-old..auto-pr-11612) ( 2 files changed, 6 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11612-old..auto-pr-11612) ( 2 files changed, 6 insertions(+), 8 deletions(-))

2024-09-05 19:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 5
Skipped tests: 1
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>vpcaccess</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11612/artifacts/6ba7cbe7-3277-41dd-a6bd-95ebb6a9f67f/build-log/replaying_test.log)

2024-09-06 05:08 UTC, 0Delta commented on mmv1/products/vpcaccess/Connector.yaml
> +      min_throughput. max_throughput and max_instances cannot both be specified. Use max_instances instead. Use of max_throughput is now discouraged.
LGTM
this word included cbb4d94

2024-09-06 05:08 UTC, 0Delta commented on mmv1/products/vpcaccess/Connector.yaml
> +      min_throughput and min_instances cannot both be specified. Use min_instances instead. Use of min_throughput is now discouraged.
LGTM
this word included cbb4d94

2024-09-09 21:13 UTC, NickElliot approved these changes
LGTM! Thanks!

2024-09-09 21:13 UTC, merged