Add `host_error_timeout_seconds` field to `compute_instance` on beta provider
GoogleCloudPlatform/magic-modules pull request #11652
Opened 2024-09-06 09:14 UTC by karolgorc

-Added field to `google_compute_instance` and `google_compute_instance_template`
-Added tests
-Added doc changes
-Added data_source support

Do you want me to introduce plan-time validation of this field or should the API handle errors on this field?

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `host_error_timeout_seconds` to `google_compute_instance` on beta provider
```

2024-09-09 21:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11652-old..auto-pr-11652) ( 6 files changed, 13 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11652-old..auto-pr-11652) ( 12 files changed, 192 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11652-old..auto-pr-11652) ( 1 file changed, 11 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (310 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
    maintenance_interval       = # value needed
    min_node_cpus              = # value needed
    preemptible                = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
    maintenance_interval       = # value needed
    min_node_cpus              = # value needed
    on_host_maintenance        = # value needed
    preemptible                = # value needed
  }
}


```
Resource: `google_compute_region_instance_template` (60 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_region_instance_template" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
  }
}


```

2024-09-09 21:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstanceTemplate_hostErrorTimeoutSeconds`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11652/artifacts/1f97bffe-9475-4220-810c-31c80caabdac/recording/TestAccComputeInstanceTemplate_hostErrorTimeoutSeconds.log)]
`TestAccComputeInstance_hostErrorTimeoutSecconds`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11652/artifacts/1f97bffe-9475-4220-810c-31c80caabdac/recording/TestAccComputeInstance_hostErrorTimeoutSecconds.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---




$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11652/artifacts/1f97bffe-9475-4220-810c-31c80caabdac/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11652/artifacts/1f97bffe-9475-4220-810c-31c80caabdac/recording) for each test

2024-09-10 20:08 UTC, NickElliot approved these changes
if the API receiving an improper value aborts the entire operation, then it should be fine to allow the API to handle it. The concern with Terraform validation would be adding a maintenance cost should the values involved change. The reason to have it handled in Terraform is if the error could result in a potential permadiff or mismatch in state between local and remote.

2024-09-10 20:08 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/d/compute_instance.html.markdown
> +* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection
```suggestion
* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection.
```

2024-09-10 20:08 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/d/compute_instance_template.html.markdown
> +* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection
```suggestion
* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection.
```

2024-09-10 20:08 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/d/compute_region_instance_template.html.markdown
> +* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection
```suggestion
* `host_error_timeout_seconds` - [Beta](https://terraform.io/docs/providers/google/guides/provider_versions.html) Time in seconds for host error detection.
```

2024-09-10 20:09 UTC, NickElliot requested changes
misclick

2024-09-16 09:07 UTC, karolgorc commented
Just to clarify. Yes the error-handling is fully supported on the API side. Any incorrect input will fail the apply so there is no risk of having a permadiff.

2024-09-17 20:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11652-old..auto-pr-11652) ( 6 files changed, 13 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11652-old..auto-pr-11652) ( 12 files changed, 192 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11652-old..auto-pr-11652) ( 1 file changed, 11 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (308 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  scheduling {
    maintenance_interval = # value needed
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
    maintenance_interval       = # value needed
    min_node_cpus              = # value needed
    preemptible                = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
    maintenance_interval       = # value needed
    min_node_cpus              = # value needed
    on_host_maintenance        = # value needed
    preemptible                = # value needed
  }
}


```
Resource: `google_compute_region_instance_template` (60 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_region_instance_template" "primary" {
  scheduling {
    host_error_timeout_seconds = # value needed
  }
}


```

2024-09-17 20:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 1007
Passed tests: 933
Skipped tests: 74
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11652/artifacts/da3fa58c-61ab-48f0-a924-172147f31570/build-log/replaying_test.log)

2024-09-20 18:55 UTC, NickElliot reviewed
Need to ask one last question: for the "default behavior" is `host_error_timeout_seconds` still being returned in GET requests, or is the field not returned at all?

2024-09-23 11:02 UTC, karolgorc commented
While testing your question i found a bug that probably has something to do with the additional function for Diff on `scheduling` block. When removing the `host_error_timeout_seconds` field, terraform doesn't see a change in the config. Will work on a fix for this and write additional test

2024-09-23 20:28 UTC, NickElliot approved these changes
Given it's part of behavior for the full block I think it's fine to approve as is, and introduce a new PR for fixing the wider bug. Thanks for the contribution!

2024-09-23 20:28 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/resource_compute_instance_template_test.go.erb
> +<% unless version == "ga" -%>
```suggestion
<% unless version == 'ga' -%>
```

2024-09-23 20:29 UTC, merged