Ensure oneOf condition is honored when expanding the job configs.
GoogleCloudPlatform/magic-modules pull request #11682
Opened 2024-09-11 10:27 UTC by ahzaz

Ensure oneOf condition is honored when expanding the job configuration for Hive, Pig, Spark-sql, and Presto.

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/13278

**Release Note Template for Downstream PRs (will be copied)**

```dataproc: Ensure oneOf condition is honored when expanding the job configuration for Hive, Pig, Spark-sql, and Presto.

```

2024-09-11 10:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11682-old..auto-pr-11682) ( 1 file changed, 4 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11682-old..auto-pr-11682) ( 1 file changed, 4 insertions(+), 8 deletions(-))

2024-09-11 10:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 57
Passed tests: 47
Skipped tests: 6
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dataproc</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataprocJob_Hive</li>
<li>TestAccDataprocJob_Pig</li>
<li>TestAccDataprocJob_Presto</li>
<li>TestAccDataprocJob_SparkSql</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-09-11 11:16 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataprocJob_Hive`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/build-log/recording_build/TestAccDataprocJob_Hive_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/recording/TestAccDataprocJob_Hive.log)]
`TestAccDataprocJob_Pig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/build-log/recording_build/TestAccDataprocJob_Pig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/recording/TestAccDataprocJob_Pig.log)]
`TestAccDataprocJob_Presto`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/build-log/recording_build/TestAccDataprocJob_Presto_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/recording/TestAccDataprocJob_Presto.log)]
`TestAccDataprocJob_SparkSql`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/build-log/recording_build/TestAccDataprocJob_SparkSql_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/recording/TestAccDataprocJob_SparkSql.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11682/artifacts/14447c35-d443-4206-a515-e6aedd843a8e/recording) for each test

2024-09-12 05:12 UTC, ahzaz commented
Tests failing related to https://github.com/hashicorp/terraform-provider-google/issues/19424
```
Error waiting for creating Dataproc cluster: Error code 4, message: Timeout waiting for instance {cluster-name}-m to report in.
```

Presto Tests failing as 2.2 image does not have Presto (it has Trino).
```
Error creating Dataproc cluster: googleapi: Error 400: Feature 'Component: PRESTO' not available on cluster 'dproc-job-test-314f9ty0x6'
```

2024-09-13 16:54 UTC, ScottSuarez requested changes
Why not just check len(querylist) > 0 instead of else if. Confirming that these cannot be set together correct? Have you tried to see the behavior?

Can you also add a testcase for this scenario?

2024-09-24 20:20 UTC, c2thorn commented
Hi @ahzaz 

Tomorrow, the Magic Modules repository is scheduled to undergo a language migration from Ruby to Go. You can view more details about this in our announcement here: https://github.com/hashicorp/terraform-provider-google/issues/19583 (or [go/mm-migration-announcement](go/mm-migration-announcement) if you are a Googler)

This open pull request may become incompatible due to most YAML and .erb files converting to Go-compatible files.

Our team (Magic Modules repository maintainers) has tooling to automatically convert changes to the new language, and we can prepare a new commit for this pull request that is compatible with the migration.

In order to push the new changes to your pull request, we would need to <ins>force push the commit to your fork's branch</ins>. Our tooling saves a backup branch before converting, so we could rollback or open a new pull request if needed. We would also work with you and the PR reviewer in the event additional changes are needed.

You also have the option to update the pull request yourself after the migration. You can view a [preview branch](https://github.com/GoogleCloudPlatform/magic-modules/tree/FEATURE-BRANCH-rewrite-switchover-preview) and [updated documentation](https://googlecloudplatform.github.io/magic-modules/reference/ruby-go-changes/) related to the migration changes.

We will take no action until we have your explicit permission to push changes to your fork's branch used for this pull request. Let me or your reviewer know if you have any further questions!

2024-10-14 20:49 UTC, closed without merging