Add deletion_protection field to Metastore Service
GoogleCloudPlatform/magic-modules pull request #11689
Opened 2024-09-12 15:19 UTC by SamanthaMathews

Add deletion_protection field to make deletion actions require an explicit intent
Part of b/366197455

Part of https://github.com/hashicorp/terraform-provider-google/issues/18854

**Release Note Template for Downstream PRs (will be copied)**
```
Metastore: added `deletion_protection` field to `dataproc_metastore_service` to make deleting them require an explicit intent. `google_active_directory_domain` resources now cannot be destroyed unless `deletion_protection = false` is set for the resource.
```

2024-09-25 19:54 UTC, c2thorn commented
Discussing with @SamanthaMathews offline about this PR and the go rewrite migration

2024-10-01 09:00 UTC, abd-goog requested changes

2024-10-01 09:00 UTC, abd-goog commented on mmv1/third_party/terraform/services/dataprocmetastore/go/resource_dataproc_metastore_service_test.go
> +                                Config: testAccDataprocMetastoreService_updateAndImport(name, tier[1]),
Should be tier[0] I believe to match step 1 resource.

2024-10-01 09:17 UTC, SamanthaMathews commented on mmv1/products/metastore/Service.yaml
> +      Whether Terraform will be prevented from destroying the service. Defaults to false.
default value is false

2024-10-01 09:17 UTC, SamanthaMathews commented on mmv1/products/metastore/Service.yaml
> +      or `terraform destroy` that would delete the service will fail.
default value is false

2024-10-01 09:19 UTC, abd-goog approved these changes

2024-10-14 20:43 UTC, c2thorn commented
Hi Samantha, please recreate this PR per our conversation earlier this month.

2024-10-14 20:43 UTC, closed without merging