Add tags field to Datafusion Instances for TagsR2401
GoogleCloudPlatform/magic-modules pull request #11681
Opened 2024-09-11 10:16 UTC by SamanthaMathews

Add tags field to instance resource to allow setting tags on instance resources at creation time.
Part of b/337048265

Release Note Template for Downstream PRs (will be copied)
```
datafusion: added `tags` field to `datafusion_instance` to allow setting tags for instances at creation time
```

2024-09-25 05:31 UTC, abd-goog approved these changes

2024-09-25 19:55 UTC, c2thorn commented
Discussing with @SamanthaMathews offline about this PR and the go rewrite migration

2025-02-18 07:51 UTC, SamanthaMathews commented
The contents of this code are entirely owned by Google LLC in accordance with the agreement between Google LLC and the third party submitting this code into Google's open source repository

2025-02-18 16:04 UTC, slevenick requested changes
Needs CLA signing before I can run the build

2025-03-05 16:52 UTC, slevenick requested changes
CLA still seems to be failing. If you believe you've signed it please reach out to me and I can see if I can resolve

2025-04-23 09:43 UTC, closed without merging