feat(apigee): Add support for NatAddress activation
GoogleCloudPlatform/magic-modules pull request #11698
Opened 2024-09-13 06:27 UTC by entertvl

- fix https://github.com/hashicorp/terraform-provider-google/issues/13914

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
apigee: Add support for NAT Address activation in `google_apigee_nat_address`.
```

2024-09-14 06:08 UTC, entertvl commented
> Is it possible to do what you need to do in the read method?

Resolved using encoder/decoder. Thanks.

PR is ready for review. Could you take a look?

2024-09-16 21:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11698-old..auto-pr-11698) ( 1 file changed, 43 insertions(+))

2024-09-16 21:18 UTC, modular-magician commented
#### Tests analytics
Total tests: 43
Passed tests: 14
Skipped tests: 29
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccApigeeNatAddress_apigeeNatAddressUpdateTest
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11698/artifacts/c9d4f2ca-f610-4dbd-8930-574b89c04c19/build-log/replaying_test.log)

2024-09-19 01:54 UTC, entertvl commented
What reason of failed to terraform-google-conversion-test-integration step?
I don't know how the next.

2024-09-20 23:20 UTC, trodge commented
/gcbrun

2024-09-20 23:21 UTC, trodge commented
My apologies, that test has been a bit flakey since the 6.0.0 changes. I'm trying re-running the tests. If that fails, rebasing this PR may fix it.

2024-09-20 23:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11698-old..auto-pr-11698) ( 1 file changed, 43 insertions(+))

2024-09-20 23:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 43
Passed tests: 14
Skipped tests: 29
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccApigeeNatAddress_apigeeNatAddressUpdateTest
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11698/artifacts/899d383c-fae5-4028-bae5-3293f1002afd/build-log/replaying_test.log)

2024-09-21 11:33 UTC, entertvl commented
Rebased and checked that the re-run tests passed locally.

```
--- PASS: TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample (2463.60s)
--- PASS: TestAccApigeeNatAddress_apigeeNatAddressUpdateTest (2579.36s)
```

2024-09-23 17:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11698-old..auto-pr-11698) ( 1 file changed, 43 insertions(+))

2024-09-23 17:36 UTC, modular-magician commented
#### Tests analytics
Total tests: 43
Passed tests: 14
Skipped tests: 29
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccApigeeNatAddress_apigeeNatAddressUpdateTest
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11698/artifacts/67c22d4c-937d-4df9-af48-7b051d02b475/build-log/replaying_test.log)

2024-09-23 20:37 UTC, trodge requested changes

2024-09-23 20:37 UTC, trodge commented on mmv1/templates/terraform/constants/apigee_nat_address.go.erb
> +}
Here's a fix for the TGC build/unit test that's failing.
```suggestion
<% unless compiler == "terraformgoogleconversion-codegen" -%>
// waitForNatAddressReady waits for an NatAddress to leave the
// "CREATING" state and become "RESERVED", to indicate that it's ready.
func waitForNatAddressReserved(d *schema.ResourceData, config *transport_tpg.Config, timeout time.Duration) error {
	return retry.Retry(timeout, func() *retry.RetryError {
		if err := resourceApigeeNatAddressRead(d, config); err != nil {
			return retry.NonRetryableError(err)
		}

		id := d.Id()
		state := d.Get("state").(string)
		if state == "CREATING" {
			return retry.RetryableError(fmt.Errorf("NatAddress %q has state %q.", id, state))
		} else if state == "RESERVED" {
			log.Printf("[DEBUG] NatAddress %q has state %q.", id, state)
			return nil
		} else {
			return retry.NonRetryableError(fmt.Errorf("NatAddress %q has state %q.", id, state))
		}
	})
}
<% end -%>
```

2024-09-24 00:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11698-old..auto-pr-11698) ( 5 files changed, 387 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11698-old..auto-pr-11698) ( 1 file changed, 16 insertions(+))

2024-09-24 00:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 43
Passed tests: 14
Skipped tests: 29
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestAccApigeeNatAddress_apigeeNatAddressUpdateTest
$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11698/artifacts/da5b6d37-5015-46e7-ac8c-3394bfcf6274/build-log/replaying_test.log)

2024-09-24 00:51 UTC, trodge approved these changes

2024-09-24 00:51 UTC, merged