Clarifying documentation for google_compute_region_backend_service locality_lb_policy
GoogleCloudPlatform/magic-modules pull request #11708
Opened 2024-09-13 19:59 UTC by brokenthumbs

- Updating the documentation to more clearly indicate that the footer note for `locality_lb_policy` refers to the field `locality_lb_policy`, and not `WEIGHTED_MAGLEV`.
- Replacing the pronoun `This field` with explicit noun of `locality_lb_policy`.
- Also adds clarifying statement that `WEIGHTED_MAGLEV` is only applicable to loadBalancingScheme EXTERNAL.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-09-13 20:06 UTC, slevenick requested changes
Let me know when you've signed the CLA

2024-09-13 20:26 UTC, brokenthumbs commented
> Let me know when you've signed the CLA

Signed the CLA from https://cla.developers.google.com/ .

2024-09-13 20:27 UTC, brokenthumbs commented
> Let me know when you've signed the CLA

@slevenick 

I just completed signing the CLA from https://cla.developers.google.com/ .

2024-09-13 20:30 UTC, slevenick commented
/gcbrun

2024-09-13 20:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-09-13 21:09 UTC, slevenick requested changes
This hasn't generated any diffs. You'll need to make the same changes to the RegionBackendService.yaml that is side-by-side with the file you edited. Keep these edits too

2024-09-14 01:44 UTC, brokenthumbs commented
> RegionBackendService.yaml



> This hasn't generated any diffs. You'll need to make the same changes to the RegionBackendService.yaml that is side-by-side with the file you edited. Keep these edits too

@slevenick 

Updated `RegionBackendService.yaml`, thanks for letting me know.

2024-09-16 14:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 1004
Passed tests: 929
Skipped tests: 75
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

$\textcolor{green}{\textsf{All tests passed!}}$

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11708/artifacts/e61905b4-8ad7-4645-aafc-27aa02cb6a05/build-log/replaying_test.log)

2024-09-16 15:02 UTC, slevenick approved these changes

2024-09-16 15:02 UTC, merged