Convert database resource from automated to handwritten resource
GoogleCloudPlatform/magic-modules pull request #11829
Opened 2024-09-26 11:39 UTC by jharshika

This pull request addresses issue [hashicorp/terraform-provider-google#7810](https://github.com/hashicorp/terraform-provider-google/issues/7810) by migrating the database resource from an autogenerated model to a handwritten implementation. This change allows us to enhance error handling and implement more flexible execution conditions.

Migration to Handwritten Implementation: The database resource, previously autogenerated, has been refactored to a handwritten version. This change enables us to:
- Implement custom logic to handle error messages effectively.
- Introduce conditions during execution that were not feasible with the autogenerated version.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
sql: google_sql_database_instance can break refresh when activation_policy is set to NEVER
```

2024-09-26 13:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11829-old..auto-pr-11829) ( 4 files changed, 3 insertions(+), 359 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11829-old..auto-pr-11829) ( 4 files changed, 2 insertions(+), 358 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11829-old..auto-pr-11829) ( 1 file changed, 99 deletions(-))

## Breaking Change(s) Detected

The following breaking change(s) were detected within your pull request.
- Resource `google_sql_database` was either removed or renamed - [reference](https://googlecloudplatform.github.io/magic-modules/develop/breaking-changes/breaking-changes#resource-map-resource-removal-or-rename)

If you believe this detection to be incorrect please raise the concern with your reviewer.
If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window.
An `override-breaking-change` label can be added to allow merging.

2024-09-26 13:36 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccDataSourceSqlDatabase_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_build/TestAccDataSourceSqlDatabase_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording/TestAccDataSourceSqlDatabase_basic.log)]
`TestAccDataSourceSqlDatabases_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_build/TestAccDataSourceSqlDatabases_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording/TestAccDataSourceSqlDatabases_basic.log)]
`TestAccSqlDatabaseInstance_multipleOperations`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_build/TestAccSqlDatabaseInstance_multipleOperations_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording/TestAccSqlDatabaseInstance_multipleOperations.log)]
`TestAccSqlDatabase_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_build/TestAccSqlDatabase_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording/TestAccSqlDatabase_basic.log)]
`TestAccSqlDatabase_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_build/TestAccSqlDatabase_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording/TestAccSqlDatabase_update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11829/artifacts/a8fd9e1b-0d5e-44af-b3bd-38bb74465888/recording) for each test

2024-09-26 13:36 UTC, SarahFrench requested changes
Hi @jharshika - Thanks for your PR!

To be upfront, I don't think we'll accept this resource no longer being generated. If there are code changes needed in the resource we should use the code generator's features that allow custom code to be inserted into generated code. If that isn't sufficient we'd then think about next steps, potentially adding more flexibility to the code generator.

Could you please push some commits with the code changes you'd like to see added to the resource to address the issue you linked? Currently I can see (from the [diff links in this message](https://github.com/GoogleCloudPlatform/magic-modules/pull/11829#issuecomment-2376990049)) that the contents of the new services/sql/resource_sql_database.go file in this PR doesn't differ from the existing file in the google/google-beta repos.

Once I can see what code change you want to make I can suggest how to achieve them via the generator. For now, here is the page in our contribution guide about adding custom code: https://googlecloudplatform.github.io/magic-modules/develop/custom-code/

2024-09-28 08:47 UTC, jharshika commented
Hi @SarahFrench thanks for the explanation. Closing this PR and creating a new one with suggested changes

2024-09-28 08:47 UTC, closed without merging