Enable update in apigee reference
GoogleCloudPlatform/magic-modules pull request #11865
Opened 2024-09-28 01:27 UTC by george-peng

Add update capability to allow the reference to be updated without needing to recreate the entire resource.

Update API : https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.references/update

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
apigee: enable update in `google_apigee_env_references`
```

2024-09-30 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))

2024-09-30 21:27 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/72d9bd0e-d2a8-4dc0-ba82-feb0a7c420fa/build-log/recording_build/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/72d9bd0e-d2a8-4dc0-ba82-feb0a7c420fa/recording/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/72d9bd0e-d2a8-4dc0-ba82-feb0a7c420fa/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/72d9bd0e-d2a8-4dc0-ba82-feb0a7c420fa/recording) for each test

2024-10-01 20:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))

2024-10-01 20:31 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 14
Skipped tests: 29
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-01 20:45 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/6bcb408e-8ca4-4db2-8ea2-0896fe1bcac8/build-log/recording_build/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/6bcb408e-8ca4-4db2-8ea2-0896fe1bcac8/recording/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update.log)]


🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/6bcb408e-8ca4-4db2-8ea2-0896fe1bcac8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/6bcb408e-8ca4-4db2-8ea2-0896fe1bcac8/recording) for each test

2024-10-03 21:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 277 insertions(+), 1 deletion(-))

2024-10-03 21:30 UTC, modular-magician commented
#### Tests analytics
Total tests: 44
Passed tests: 14
Skipped tests: 29
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-03 21:41 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/7534ec26-6fbc-4537-9356-64291a163789/build-log/recording_build/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/7534ec26-6fbc-4537-9356-64291a163789/recording/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update.log)]


🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/7534ec26-6fbc-4537-9356-64291a163789/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/7534ec26-6fbc-4537-9356-64291a163789/recording) for each test

2024-10-04 00:01 UTC, george-peng commented
@NickElliot what's the error in TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update? I don't have access to log.

2024-10-10 19:07 UTC, NickElliot requested changes
Sorry for the delays
```
{
  "error": {
    "code": 400,
    "message": "generic::failed_precondition: keystore \"organizations/tf-testrr2t3aojrz/environments/tf-testrr2t3aojrz/keystores/tf-test-keystorerr2t3aojrz\" is referred to by reference \"organizations/tf-testrr2t3aojrz/environments/tf-testrr2t3aojrz/references/tf-test-referencerr2t3aojrz\"",
    "status": "FAILED_PRECONDITION",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.RequestInfo",
        "requestId": "5975689308291936023"
      }
    ]
  }
}
```

The issue appears to be due to updating the dependent resource at the same time as the deletion -- the swap in dependency from `apigee_environment_keystore_1` to `apigee_environment_keystore_2`seems to be the cause. Create both of the keystores in the step 1, then update the reference to `apigee_environment_keystore_2` in step 2 (rather than comboing deletions/updates).

2024-10-18 19:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 291 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 291 insertions(+), 1 deletion(-))

2024-10-18 19:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 48
Passed tests: 14
Skipped tests: 33
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-21 21:33 UTC, NickElliot requested changes
need these back!

2024-10-21 21:33 UTC, NickElliot commented on mmv1/third_party/terraform/services/apigee/resource_apigee_env_references_test.go
> +  name           = "tf-test-reference"
readd the random suffix

2024-10-21 21:33 UTC, NickElliot commented on mmv1/third_party/terraform/services/apigee/resource_apigee_env_references_test.go
> +  name           = "tf-test-reference"
readd the random suffix

2024-10-21 22:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 291 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 291 insertions(+), 1 deletion(-))

2024-10-21 22:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 48
Passed tests: 14
Skipped tests: 33
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-21 23:06 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/fb15fab5-aa14-4422-a08b-b8c34705eb7e/build-log/recording_build/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/fb15fab5-aa14-4422-a08b-b8c34705eb7e/recording/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/fb15fab5-aa14-4422-a08b-b8c34705eb7e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/fb15fab5-aa14-4422-a08b-b8c34705eb7e/recording) for each test

2024-10-25 22:39 UTC, NickElliot requested changes

2024-10-25 22:39 UTC, NickElliot commented on mmv1/third_party/terraform/services/apigee/resource_apigee_env_references_test.go
> +  billing_account = "%{billing_account}"
need to set deletion_policy to false in the test steps for this resource!

2024-11-04 17:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 293 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11865-old..auto-pr-11865) ( 3 files changed, 293 insertions(+), 1 deletion(-))

2024-11-04 17:31 UTC, modular-magician commented
#### Tests analytics
Total tests: 49
Passed tests: 14
Skipped tests: 34
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>apigee</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 17:46 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/bfbcbe45-2876-4f0c-8fb3-bdb11a1e7bd0/recording/TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/bfbcbe45-2876-4f0c-8fb3-bdb11a1e7bd0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11865/artifacts/bfbcbe45-2876-4f0c-8fb3-bdb11a1e7bd0/recording) for each test

2024-11-04 21:01 UTC, NickElliot approved these changes
LGTM

2024-11-04 21:01 UTC, merged