tests: add a acc test for CAS instance creation.
GoogleCloudPlatform/magic-modules pull request #11931
Opened 2024-10-04 23:51 UTC by feng-zhe

Add a acc test for CAS instance creation.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-10-05 00:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11931-old..auto-pr-11931) ( 1 file changed, 44 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11931-old..auto-pr-11931) ( 1 file changed, 44 insertions(+))

2024-10-05 00:06 UTC, modular-magician commented
#### Tests analytics
Total tests: 98
Passed tests: 83
Skipped tests: 14
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccSqlDatabaseInstance_useCasBasedServerCa</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-05 00:19 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccSqlDatabaseInstance_useCasBasedServerCa`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11931/artifacts/e50c4fc4-6d34-4496-be25-957ae6949a22/recording/TestAccSqlDatabaseInstance_useCasBasedServerCa.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---




🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11931/artifacts/e50c4fc4-6d34-4496-be25-957ae6949a22/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11931/artifacts/e50c4fc4-6d34-4496-be25-957ae6949a22/recording) for each test

2024-10-07 16:30 UTC, zli82016 requested changes
Can you please fix the `terraform-provider-google-build-and-unit-tests`? Thanks.

`terraform-provider-google-build-and-unit-tests` fails because gofmt needs on the following file `mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go`

2024-10-07 17:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11931-old..auto-pr-11931) ( 1 file changed, 44 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11931-old..auto-pr-11931) ( 1 file changed, 44 insertions(+))

2024-10-07 17:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 98
Passed tests: 84
Skipped tests: 14
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>sql</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11931/artifacts/cb9252db-e6d0-45e2-8663-209a9fdd95b8/build-log/replaying_test.log)

2024-10-07 17:53 UTC, feng-zhe commented
> Can you please fix the `terraform-provider-google-build-and-unit-tests`? Thanks.
> 
> `terraform-provider-google-build-and-unit-tests` fails because gofmt needs on the following file `mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go`

Thanks. Ran the gofmt on the file and the test is passing now.

2024-10-07 17:58 UTC, zli82016 approved these changes
LGTM

2024-10-07 17:58 UTC, merged