NCC Producer VPC Spoke resource added
GoogleCloudPlatform/magic-modules pull request #11934
Opened 2024-10-07 13:43 UTC by amanMahendroo

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-10-09 14:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11934-old..auto-pr-11934) ( 3 files changed, 336 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11934-old..auto-pr-11934) ( 3 files changed, 336 insertions(+), 4 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11934-old..auto-pr-11934) ( 1 file changed, 73 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11934-old..auto-pr-11934) ( 4 files changed, 151 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_connectivity_spoke` (15 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_connectivity_spoke" "primary" {
  linked_producer_vpc_network {
    include_export_ranges = # value needed
  }
}


```

2024-10-09 14:27 UTC, modular-magician commented
#### Tests analytics
Total tests: 26
Passed tests: 24
Skipped tests: 1
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>networkconnectivity</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetworkConnectivitySpoke_networkConnectivitySpokeLinkedProducerVpcNetworkBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-09 14:31 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetworkConnectivitySpoke_networkConnectivitySpokeLinkedProducerVpcNetworkBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11934/artifacts/b718de98-fdc2-4c4c-a72b-e88ac51dcece/recording/TestAccNetworkConnectivitySpoke_networkConnectivitySpokeLinkedProducerVpcNetworkBasicExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---




🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11934/artifacts/b718de98-fdc2-4c4c-a72b-e88ac51dcece/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11934/artifacts/b718de98-fdc2-4c4c-a72b-e88ac51dcece/recording) for each test

2024-10-09 14:39 UTC, slevenick requested changes
Just need a description on one field. Otherwise looks good to go

2024-10-09 14:39 UTC, slevenick commented on mmv1/products/networkconnectivity/Spoke.yaml
> +        description: ga
This needs a real description

2024-10-10 02:31 UTC, amanMahendroo commented on mmv1/products/networkconnectivity/Spoke.yaml
> +        description: ga
Done

2024-10-10 15:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11934-old..auto-pr-11934) ( 3 files changed, 336 insertions(+), 4 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11934-old..auto-pr-11934) ( 3 files changed, 336 insertions(+), 4 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11934-old..auto-pr-11934) ( 1 file changed, 73 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-11934-old..auto-pr-11934) ( 4 files changed, 151 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_connectivity_spoke` (15 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_connectivity_spoke" "primary" {
  linked_producer_vpc_network {
    include_export_ranges = # value needed
  }
}


```

2024-10-10 15:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 26
Passed tests: 25
Skipped tests: 1
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>networkconnectivity</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11934/artifacts/0995ba77-5100-422b-a5e4-944cbb71acb9/build-log/replaying_test.log)

2024-10-10 15:10 UTC, slevenick approved these changes

2024-10-10 15:10 UTC, merged