add iamcredentialsbasepath support for plugin framework
GoogleCloudPlatform/magic-modules pull request #11947
Opened 2024-10-08 18:35 UTC by BBBmau

This is temporary and will be resolved once the muxing issues are addressed.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-10-08 21:27 UTC, SarahFrench requested changes
Here's some initial feedback - I'll check the code locally on my next pass!

Currently there's an issue with generating the beta provider:

```
error parsing framework_config.go.tmpl for filepath /go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/fwtransport/framework_config.go template: framework_config.go.tmpl:526: function "version" not defined
```

2024-10-08 21:27 UTC, SarahFrench commented on mmv1/third_party/terraform/fwtransport/framework_config.go.tmpl
> +
Please move this into fwtransport/framework_provider_clients.go alongside `func (p *FrameworkProviderConfig) NewDnsClient`!

2024-10-08 21:27 UTC, SarahFrench commented on mmv1/third_party/terraform/fwtransport/framework_config.go.tmpl
> +func RemoveBasePathVersion(url string) string {
Could we just import RemoveBasePathVersion from google/transport/config.go?

2024-10-23 17:03 UTC, BBBmau commented
Latest changes allow you to build successfully on both ga and beta providers.

The rebase from `upstream/main` was necessary in order to address some compute errors when attempting to build the provider:
```hcl
└─(09:25:40 on main ✹ ✭)──> devbuild                                                                                                                                                          1 ↵ ──(Wed,Oct23)─┘
# github.com/hashicorp/terraform-provider-google/google/services/compute
google/services/compute/data_source_compute_secutity_policy.go:14:6: DataSourceGoogleComputeSecurityPolicy redeclared in this block
        google/services/compute/data_source_compute_security_policy.go:14:6: other declaration of DataSourceGoogleComputeSecurityPolicy
```

Wasn't sure if to rebase on the feature-branch or not so i just decided to do it on here. Let me know if that's fine, i can also rebase on the feature branch itself.

I also tried to manually test `IAMCredentialsBasePath` by testing with the [poc ephemeral resource](https://github.com/BBBmau/magic-modules/blob/44839ef426db9ed84fd03efc13560e5c713a05c1/mmv1/third_party/terraform/ephemerals/ephemeral_service_account_access_token.go) that uses it.

Unfortunately was running into the following error despite it being configured correctly. I can create the PR that includes the code that would add `ephemeral google_service_account_access_token`

![image](https://github.com/user-attachments/assets/cc9608d7-0e78-4f72-9159-7d28bdcdf9b5)

2024-10-23 23:38 UTC, BBBmau commented
resolved the previous comment. It was due to only running `go get github.com/hashicorp/terraform-plugin-framework/ephemeral@627a49bf3060aa8d1c681847ff3c682681ea3cd2` which just focuses on the single framework/ephemeral package and not on the entire plugin-framework. 

Currently running into issues where the `p.providerConfig.UserAgent` returns us `""` which causes errors. Currently investigating how the `userAgent` is set on SDK and how we could replicate this on `plugin-framework`. A reproduction can be seen https://github.com/BBBmau/terraform-provider-google/tree/ephemeral-iamcredentialspath-test

2024-10-24 21:24 UTC, SarahFrench requested changes
Please rebase this PR so it's based on the feature branch.

[The PR that caused the problem you're seeing](https://github.com/GoogleCloudPlatform/magic-modules/pull/11867) was merged to main only 3 days ago, whereas the last sync into the feature branch included only commits from Sept 26th and earlier, so shouldn't affect us? I believe the problem is with your local environment as described here: https://github.com/GoogleCloudPlatform/magic-modules/pull/11947#issuecomment-2436357182

2024-10-24 21:36 UTC, BBBmau commented
> Please rebase this PR so it's based on the feature branch.
> 
> [The PR that caused the problem you're seeing](https://github.com/GoogleCloudPlatform/magic-modules/pull/11867) was merged to main only 3 days ago, whereas the last sync into the feature branch included only commits from Sept 26th and earlier, so shouldn't affect us? I believe the problem is with your local environment as described here: [#11947 (comment)](https://github.com/GoogleCloudPlatform/magic-modules/pull/11947#issuecomment-2436357182)

rebased back to `FEATURE-BRANCH`-ephemeral-resource`

2024-10-24 21:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11947-old..auto-pr-11947) ( 2 files changed, 18 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11947-old..auto-pr-11947) ( 2 files changed, 18 insertions(+))

2024-10-24 22:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 4100
Passed tests: 3455
Skipped tests: 413
Affected tests: 232

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 232 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAssuredWorkloadsWorkload_BasicHandWritten</li>
<li>TestAccBigQueryJob_bigqueryJobCopyExample</li>
<li>TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample</li>
<li>TestAccBigqueryDatasetIamMember</li>
<li>TestAccBigqueryDatasetIamMember_afterDatasetCreation</li>
<li>TestAccBigqueryDatasetIamMember_iamMember</li>
<li>TestAccBigqueryDatasetIamMember_serviceAccount</li>
<li>TestAccCloudRunService_cloudRunServiceSqlExample</li>
<li>TestAccCloudRunV2Job_cloudrunv2JobSqlExample</li>
<li>TestAccCloudRunV2Service_cloudrunv2ServiceSqlExample</li>
<li>TestAccComposerEnvironment_withEncryptionConfigComposer1</li>
<li>TestAccComputeImageIamBindingGenerated</li>
<li>TestAccComputeImageIamBindingGenerated_withCondition</li>
<li>TestAccComputeImageIamMemberGenerated</li>
<li>TestAccComputeImageIamMemberGenerated_withCondition</li>
<li>TestAccComputeImageIamPolicyGenerated</li>
<li>TestAccComputeImageIamPolicyGenerated_withCondition</li>
<li>TestAccComputeImage_imageBasicExample</li>
<li>TestAccComputeImage_imageBasicStorageLocationExample</li>
<li>TestAccComputeImage_imageGuestOsExample</li>
<li>TestAccComputeImage_update</li>
<li>TestAccComputeInstanceTemplate_imageShorthand</li>
<li>TestAccComputeInstanceTemplate_nictype_update</li>
<li>TestAccComputeInstance_nictype_update</li>
<li>TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten</li>
<li>TestAccComputeNetworkFirewallPolicyRule_securityProfileGroup_update</li>
<li>TestAccComputeNetworkFirewallPolicyRule_update</li>
<li>TestAccComputeProjectMetadataItem_basic</li>
<li>TestAccComputeProjectMetadataItem_basicUpdate</li>
<li>TestAccComputeProjectMetadataItem_basicWithEmptyVal</li>
<li>TestAccComputeProjectMetadataItem_exists</li>
<li>TestAccComputeProjectMetadata_basic</li>
<li>TestAccComputeProjectMetadata_modify_1</li>
<li>TestAccComputeProjectMetadata_modify_2</li>
<li>TestAccComputeRegionInstanceTemplate_imageShorthand</li>
<li>TestAccComputeRegionInstanceTemplate_nictype_update</li>
<li>TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample</li>
<li>TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten</li>
<li>TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample</li>
<li>TestAccContainerAttachedCluster_containerAttachedClusterFullExample</li>
<li>TestAccContainerAttachedCluster_update</li>
<li>TestAccContainerCluster_autopilot_net_admin</li>
<li>TestAccContainerCluster_enableCiliumPolicies</li>
<li>TestAccContainerCluster_withLoggingConfig</li>
<li>TestAccContainerCluster_with_PodCIDROverprovisionDisabled</li>
<li>TestAccContainerNodePool_totalSize</li>
<li>TestAccContainerNodePool_withEnablePrivateNodesToggle</li>
<li>TestAccDataLossPreventionDiscoveryConfig_Update</li>
<li>TestAccDataSourceGooglePubsubSubscription_basic</li>
<li>TestAccDataSourceGooglePubsubSubscription_optionalProject</li>
<li>TestAccDataSourceGoogleSQLCaCerts_basic</li>
<li>TestAccDataSourceSecretManagerSecrets_basic</li>
<li>TestAccDataSourceSecretManagerSecrets_filter</li>
<li>TestAccDataSourceSqlDatabaseInstanceLatestRecoveryTime_basic</li>
<li>TestAccDataSourceSqlDatabaseInstance_basic</li>
<li>TestAccDataSourceSqlDatabaseInstances_basic</li>
<li>TestAccDataSourceSqlDatabaseInstances_databaseVersionFilter</li>
<li>TestAccDataSourceSqlDatabaseInstances_regionFilter</li>
<li>TestAccDataSourceSqlDatabaseInstances_tierFilter</li>
<li>TestAccDataSourceSqlDatabase_basic</li>
<li>TestAccDataSourceSqlDatabases_basic</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileCloudsqlExample</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingMysqlExample</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileExistingPostgresExample</li>
<li>TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfilePostgresExample</li>
<li>TestAccDatabaseMigrationServiceMigrationJob_databaseMigrationServiceMigrationJobMysqlToMysqlExample</li>
<li>TestAccDatabaseMigrationServiceMigrationJob_databaseMigrationServiceMigrationJobPostgresToAlloydbExample</li>
<li>TestAccDatabaseMigrationServiceMigrationJob_databaseMigrationServiceMigrationJobPostgresToPostgresExample</li>
<li>TestAccDatabaseMigrationServiceMigrationJob_update</li>
<li>TestAccDataprocAutoscalingPolicyIamBindingGenerated</li>
<li>TestAccDataprocAutoscalingPolicyIamMemberGenerated</li>
<li>TestAccDataprocAutoscalingPolicyIamPolicyGenerated</li>
<li>TestAccDataprocAutoscalingPolicy_dataprocAutoscalingPolicyBasicExample</li>
<li>TestAccDataprocAutoscalingPolicy_dataprocAutoscalingPolicyExample</li>
<li>TestAccDataprocClusterIamBinding</li>
<li>TestAccDataprocClusterIamMember</li>
<li>TestAccDataprocClusterIamPolicy</li>
<li>TestAccDataprocCluster_KMS</li>
<li>TestAccDataprocCluster_nonPreemptibleSecondary</li>
<li>TestAccDataprocCluster_singleNodeCluster</li>
<li>TestAccDataprocCluster_spotSecondary</li>
<li>TestAccDataprocCluster_withAccelerators</li>
<li>TestAccDataprocCluster_withAutoscalingPolicy</li>
<li>TestAccDataprocCluster_withConfigOverrides</li>
<li>TestAccDataprocCluster_withDataprocMetricConfig</li>
<li>TestAccDataprocCluster_withEndpointConfig</li>
<li>TestAccDataprocCluster_withImageVersion</li>
<li>TestAccDataprocCluster_withInitAction</li>
<li>TestAccDataprocCluster_withKerberos</li>
<li>TestAccDataprocCluster_withLabels</li>
<li>TestAccDataprocCluster_withLifecycleConfigIdleDeleteTtl</li>
<li>TestAccDataprocCluster_withMetadataAndTags</li>
<li>TestAccDataprocCluster_withMinNumInstances</li>
<li>TestAccDataprocCluster_withNodeGroupAffinity</li>
<li>TestAccDataprocCluster_withOptionalComponents</li>
<li>TestAccDataprocCluster_withReservationAffinity</li>
<li>TestAccDataprocCluster_withServiceAcc</li>
<li>TestAccDataprocCluster_withStagingBucket</li>
<li>TestAccDataprocCluster_withTempBucket</li>
<li>TestAccDataprocJobIamBinding</li>
<li>TestAccDataprocJobIamMember</li>
<li>TestAccDataprocJobIamPolicy</li>
<li>TestAccDataprocJob_Hadoop</li>
<li>TestAccDataprocJob_Hive</li>
<li>TestAccDataprocJob_Pig</li>
<li>TestAccDataprocJob_Presto</li>
<li>TestAccDataprocJob_PySpark</li>
<li>TestAccDataprocJob_Spark</li>
<li>TestAccDataprocJob_SparkSql</li>
<li>TestAccDataprocJob_updatable</li>
<li>TestAccDataprocWorkflowTemplate_basic</li>
<li>TestAccDataprocWorkflowTemplate_withShieldedVMs</li>
<li>TestAccDialogflowCXAgent_dialogflowcxAgentFullExample</li>
<li>TestAccDialogflowCXAgent_update</li>
<li>TestAccDialogflowCXFlow_dialogflowcxFlowFullExample</li>
<li>TestAccDialogflowCXFlow_update</li>
<li>TestAccDiscoveryEngineChatEngine_discoveryengineChatengine_update</li>
<li>TestAccMemorystoreInstance_memorystoreInstanceFullExample</li>
<li>TestAccMonitoringAlertPolicy</li>
<li>TestAccNetappBackupPolicy_NetappBackupPolicyFullExample_update</li>
<li>TestAccNetappBackupVault_NetappBackupVaultExample_update</li>
<li>TestAccNetappBackup_NetappBackupFull_update</li>
<li>TestAccNetappVolume_NetappVolumeBasicExample_update</li>
<li>TestAccNetappVolume_autoTieredNetappVolume_update</li>
<li>TestAccNetworkServicesGateway_updateSwp</li>
<li>TestAccPubsubSubscriptionBigQuery_serviceAccount</li>
<li>TestAccPubsubSubscriptionBigQuery_update</li>
<li>TestAccPubsubSubscriptionCloudStorage_serviceAccount</li>
<li>TestAccPubsubSubscriptionCloudStorage_updateAvro</li>
<li>TestAccPubsubSubscriptionCloudStorage_updateText</li>
<li>TestAccPubsubSubscriptionIamBinding</li>
<li>TestAccPubsubSubscriptionIamMember</li>
<li>Test [...]

2024-10-25 05:45 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccAssuredWorkloadsWorkload_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccAssuredWorkloadsWorkload_BasicHandWritten.log)]
`TestAccBigQueryJob_bigqueryJobCopyExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigQueryJob_bigqueryJobCopyExample.log)]
`TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigQueryJob_bigqueryJobCopyTableReferenceExample.log)]
`TestAccBigqueryDatasetIamMember`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigqueryDatasetIamMember.log)]
`TestAccBigqueryDatasetIamMember_afterDatasetCreation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigqueryDatasetIamMember_afterDatasetCreation.log)]
`TestAccBigqueryDatasetIamMember_iamMember`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigqueryDatasetIamMember_iamMember.log)]
`TestAccBigqueryDatasetIamMember_serviceAccount`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccBigqueryDatasetIamMember_serviceAccount.log)]
`TestAccCloudRunService_cloudRunServiceSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccCloudRunService_cloudRunServiceSqlExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccCloudRunV2Job_cloudrunv2JobSqlExample.log)]
`TestAccCloudRunV2Service_cloudrunv2ServiceSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccCloudRunV2Service_cloudrunv2ServiceSqlExample.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten.log)]
`TestAccComputeNetworkFirewallPolicyRule_securityProfileGroup_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeNetworkFirewallPolicyRule_securityProfileGroup_update.log)]
`TestAccComputeNetworkFirewallPolicyRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeNetworkFirewallPolicyRule_update.log)]
`TestAccComputeProjectMetadataItem_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadataItem_basic.log)]
`TestAccComputeProjectMetadataItem_basicUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadataItem_basicUpdate.log)]
`TestAccComputeProjectMetadataItem_basicWithEmptyVal`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadataItem_basicWithEmptyVal.log)]
`TestAccComputeProjectMetadataItem_exists`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadataItem_exists.log)]
`TestAccComputeProjectMetadata_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadata_basic.log)]
`TestAccComputeProjectMetadata_modify_1`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadata_modify_1.log)]
`TestAccComputeProjectMetadata_modify_2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeProjectMetadata_modify_2.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample.log)]
`TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten.log)]
`TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccComputeSubnetwork_subnetworkReservedSecondaryRangeExample.log)]
`TestAccContainerCluster_enableCiliumPolicies`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccContainerCluster_enableCiliumPolicies.log)]
`TestAccContainerCluster_withLoggingConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccContainerCluster_withLoggingConfig.log)]
`TestAccDataLossPreventionDiscoveryConfig_Update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccDataLossPreventionDiscoveryConfig_Update.log)]
`TestAccDataSourceGooglePubsubSubscription_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccDataSourceGooglePubsubSubscription_basic.log)]
`TestAccDataSourceGooglePubsubSubscription_optionalProject`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccDataSourceGooglePubsubSubscription_optionalProject.log)]
`TestAccDataSourceGoogleSQLCaCerts_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccDataSourceGoogleSQLCaCerts_basic.log)]
`TestAccDataSourceSecretManagerSecrets_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-427d-b3dc-9cc9c720f23b/recording/TestAccDataSourceSecretManagerSecrets_basic.log)]
`TestAccDataSourceSecretManagerSecrets_filter`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11947/artifacts/3d198660-2b19-42 [...]

2024-10-25 18:46 UTC, SarahFrench commented
Thanks this makes review a lot easier!

In future what you can do is checkout `FEATURE-BRANCH-ephemeral-resource` in your local copy of the `terraform-provider-google` repo and then make magic-modules generated to that repo (i.e. set [OUTPUT_PATH](https://github.com/GoogleCloudPlatform/magic-modules/blob/34dd74df5c9291629ca1b215636294ca56aaa6ee/GNUmakefile#L64) from the makefile to the terraform-provider-google where the downstream feature branch is checked out).

2024-10-25 18:59 UTC, SarahFrench commented
> Currently running into issues where the p.providerConfig.UserAgent returns us "" which causes errors. Currently investigating how the userAgent is set on SDK and how we could replicate this on plugin-framework

[This is where the User-Agent should get a value set during configuration of the PF-implemented provider](https://github.com/hashicorp/terraform-provider-google/blob/5bdb0d346a8b19da16ca021babb3059bfd33ab36/google/fwtransport/framework_config.go#L204-L210):

```
	// Handle User Agent string
	p.UserAgent = CompileUserAgentString(ctx, "terraform-provider-google", tfVersion, providerversion)
	// opt in extension for adding to the User-Agent header
	if ext := os.Getenv("GOOGLE_TERRAFORM_USERAGENT_EXTENSION"); ext != "" {
		ua := p.UserAgent
		p.UserAgent = fmt.Sprintf("%s %s", ua, ext)
	}
```

I'm confused why you'd see that problem, so maybe for now we should review this PR and then tackle any bugs in a subsequent PR where we have an ephemeral resource implemented + some acceptance tests. We should be able to write acc tests and run them locally now that there's an alpha TF binary with the necessary stuff.

2024-10-25 19:23 UTC, SarahFrench commented
I used some of your reproduction info and I think there's a problem with provider configuration (i.e. the meta) being passed to the ephemeral resources, I'll follow up with you in Slack. I think that is a problem 'downstream' of this PR though so isn't a blocker for merging this

2024-10-25 20:16 UTC, SarahFrench approved these changes
Approved - after we worked out what made our PoC demo not work I could see the new function was usable and didn't cause any obvious problems.

2024-10-25 21:25 UTC, merged