Added support for IPv6 addresses with the google_compute_external_vpn_gateway terraform resource
GoogleCloudPlatform/magic-modules pull request #11982
Opened 2024-10-11 06:50 UTC by abhijeetkjha-google

```release-note:enhancement
compute: added `ipv6-address` field in `google_compute_external_vpn_gateway` resource to  add support for Ipv6 addresses
```

As per the design doc, [go/arcus-outer-vpn-ipv6](https://goto.google.com/arcus-outer-vpn-ipv6). The support for IPv6 is present for Outer HA VPN, and support for IPV6 address is present in the api implementation and gcloud for external_vpn_gateway. I see the field, ipv6_address which is the IPv6 address of the interface in the external VPN gateway, Is missing in the terraform implementation for external vpn gateway. Analyzing this further and will update with any findings.

2024-10-11 06:57 UTC, abhijeetkjha-google commented
Tested locally on the unit and lint tests.

2024-10-14 22:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11982-old..auto-pr-11982) ( 1 file changed, 11 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_external_vpn_gateway` (30 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_external_vpn_gateway" "primary" {
  interface {
    ipv6_address = # value needed
  }
}


```

2024-10-14 22:39 UTC, modular-magician commented
#### Tests analytics
Total tests: 1029
Passed tests: 954
Skipped tests: 74
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeExternalVPNGateway_insertIpv6Address</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-14 22:39 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeExternalVPNGateway_insertIpv6Address`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/89143314-459e-4d8b-94d2-a370b4735a0b/build-log/recording_build/TestAccComputeExternalVPNGateway_insertIpv6Address_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/89143314-459e-4d8b-94d2-a370b4735a0b/recording/TestAccComputeExternalVPNGateway_insertIpv6Address.log)]


🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/89143314-459e-4d8b-94d2-a370b4735a0b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/89143314-459e-4d8b-94d2-a370b4735a0b/recording) for each test

2024-10-15 21:20 UTC, NickElliot requested changes
minor edit for syntax on the test otherwise lgtm

2024-10-15 21:20 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/resource_compute_external_vpn_gateway_test.go
> +  }]
```suggestion
  interface {
    id         = 0
    ipv6_address = "%s"
  }
```

2024-10-17 08:48 UTC, abhijeetkjha-google commented on mmv1/third_party/terraform/services/compute/resource_compute_external_vpn_gateway_test.go
> +  }]
Done. Thanks.

2024-10-17 08:51 UTC, abhijeetkjha-google commented
> minor edit for syntax on the test otherwise lgtm

Fixed.

2024-10-18 19:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11982-old..auto-pr-11982) ( 1 file changed, 11 insertions(+))

2024-10-18 19:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 1037
Passed tests: 963
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeExternalVPNGateway_insertIpv6Address</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-18 19:59 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeExternalVPNGateway_insertIpv6Address` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/929b6c7b-1026-40cd-b98a-ee6eab5d433a/build-log/recording_build/TestAccComputeExternalVPNGateway_insertIpv6Address_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/929b6c7b-1026-40cd-b98a-ee6eab5d433a/recording/TestAccComputeExternalVPNGateway_insertIpv6Address.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/929b6c7b-1026-40cd-b98a-ee6eab5d433a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/929b6c7b-1026-40cd-b98a-ee6eab5d433a/recording) for each test

2024-10-21 22:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11982-old..auto-pr-11982) ( 1 file changed, 11 insertions(+))

2024-10-21 23:06 UTC, modular-magician commented
#### Tests analytics
Total tests: 1037
Passed tests: 963
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeExternalVPNGateway_insertIpv6Address</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-21 23:06 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeExternalVPNGateway_insertIpv6Address` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/8042ffbb-9e78-4026-8d02-63deae31049a/build-log/recording_build/TestAccComputeExternalVPNGateway_insertIpv6Address_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/8042ffbb-9e78-4026-8d02-63deae31049a/recording/TestAccComputeExternalVPNGateway_insertIpv6Address.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/8042ffbb-9e78-4026-8d02-63deae31049a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/8042ffbb-9e78-4026-8d02-63deae31049a/recording) for each test

2024-10-22 10:51 UTC, abhijeetkjha-google reviewed
Added the requested change.

2024-10-25 22:12 UTC, NickElliot commented
/gcbrun

2024-10-25 22:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11982-old..auto-pr-11982) ( 3 files changed, 77 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-11982-old..auto-pr-11982) ( 1 file changed, 11 insertions(+))

2024-10-25 23:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 1041
Passed tests: 965
Skipped tests: 73
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeExternalVPNGateway_insertIpv6Address</li>
<li>TestAccComputeInstanceConfidentialInstanceConfigMain</li>
<li>TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-25 23:25 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeExternalVPNGateway_insertIpv6Address` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/recording/TestAccComputeExternalVPNGateway_insertIpv6Address.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccComputeInstanceConfidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/build-log/recording_build/TestAccComputeInstanceConfidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/recording/TestAccComputeInstanceConfidentialInstanceConfigMain.log)]
`TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/build-log/recording_build/TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/recording/TestAccComputeInstanceFromMachineImage_confidentialInstanceConfigMain.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-11982/artifacts/a8162f9c-542e-4d65-adae-cb3ee40fd642/recording) for each test

2024-10-29 20:53 UTC, NickElliot approved these changes
unrelated failure, LGTM!

2024-10-29 20:53 UTC, merged