Fixes https://github.com/hashicorp/terraform-provider-google/issues/11124
GoogleCloudPlatform/magic-modules pull request #11995
Opened 2024-10-15 01:54 UTC by ttewari

Fixes https://github.com/hashicorp/terraform-provider-google/issues/11124

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
Essential Contacts : fixed import to include required parent field when contact is imported

```

2024-10-15 02:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11995-old..auto-pr-11995) ( 1 file changed, 7 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11995-old..auto-pr-11995) ( 1 file changed, 7 insertions(+))

2024-10-15 02:10 UTC, modular-magician commented
#### Tests analytics
Total tests: 2
Passed tests: 2
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>essentialcontacts</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11995/artifacts/97ef37e6-3057-4942-af07-d43154f21152/build-log/replaying_test.log)

2024-10-15 12:50 UTC, slevenick requested changes
Can you add a test that uses this import format?

2024-10-16 09:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 7 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 13 insertions(+), 8 deletions(-))

2024-10-16 09:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 7 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 13 insertions(+), 8 deletions(-))

2024-10-16 09:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 2
Passed tests: 2
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>essentialcontacts</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11995/artifacts/fca4dd4e-5185-407b-8837-bb9bb9274ef8/build-log/replaying_test.log)

2024-10-16 09:17 UTC, modular-magician commented
#### Tests analytics
Total tests: 2
Passed tests: 2
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>essentialcontacts</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11995/artifacts/c2bb3efb-9ad8-43ee-9f4f-45641e862818/build-log/replaying_test.log)

2024-10-16 09:17 UTC, ttewari commented
> Can you add a test that uses this import format?

Updated the tests to not ignore the parent attribute while verifying import state.

2024-10-16 10:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 13 insertions(+), 8 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-11995-old..auto-pr-11995) ( 2 files changed, 13 insertions(+), 8 deletions(-))

2024-10-16 10:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 2
Passed tests: 2
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>essentialcontacts</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-11995/artifacts/a372e827-0584-4015-9cfa-547342e75aec/build-log/replaying_test.log)

2024-10-16 13:50 UTC, slevenick approved these changes
Thanks!

2024-10-16 13:50 UTC, merged