GKE: Support Control Plane Authority / UserManagedKeysConfig
GoogleCloudPlatform/magic-modules pull request #12013
Opened 2024-10-15 21:54 UTC by ahmedtd

Support configuring Control Plane Authority (`UserManagedKeysConfig`) on GKE clusters.  Note that using these fields requires an organization / folder / project to be internally allowlisted.

b/327251060

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added `user_managed_keys_config` field to `google_container_cluster` resource.
```

2024-10-15 21:55 UTC, ahmedtd commented
This PR is adapted from https://github.com/GoogleCloudPlatform/magic-modules/pull/11733 since @tonyzhc is on vacation.

2024-10-16 20:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 236 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 236 insertions(+), 1 deletion(-))

2024-10-16 20:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/5d982297-ea44-4d1a-930a-18834c61c990/build-log/replaying_test.log)

2024-10-16 22:47 UTC, ScottSuarez requested changes
There is a compilation crash. You'll need to update both go.mod and [go.sum](https://github.com/GoogleCloudPlatform/magic-modules/blob/862a4608eae0216ab1a5300af9638d51e0b12ae4/mmv1/third_party/terraform/go.sum#L14)

2024-10-22 01:23 UTC, ahmedtd commented
OK , I updated both using `go get -v -u google.golang.org/api@v0.201.0`

2024-10-22 16:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 4 files changed, 276 insertions(+), 17 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 4 files changed, 276 insertions(+), 17 deletions(-))

2024-10-22 16:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/3db683e7-7fbb-4bdc-832e-f933a76e74e1/build-log/replaying_test.log)

2024-10-22 16:54 UTC, ScottSuarez commented
Looks like it's still crashing downstream
https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/11464698109/job/31901478012?pr=12013

2024-10-22 17:13 UTC, ScottSuarez commented
Could you try following the instructions at https://googlecloudplatform.github.io/magic-modules/develop/update-dependencies/#update-provider-dependencies

2024-10-23 20:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 235 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 235 insertions(+))

2024-10-23 20:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 213
Passed tests: 188
Skipped tests: 13
Affected tests: 12

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>
<li>TestAccContainerCluster_autopilot_net_admin</li>
<li>TestAccContainerCluster_storagePoolsWithNodeConfig</li>
<li>TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledDefaultsUpdates</li>
<li>TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodePool</li>
<li>TestAccContainerCluster_withLoggingVariantUpdates</li>
<li>TestAccContainerCluster_withNodeConfigKubeletConfigSettingsUpdates</li>
<li>TestAccContainerCluster_withNodePoolDefaults</li>
<li>TestAccContainerCluster_with_PodCIDROverprovisionDisabled</li>
<li>TestAccContainerNodePool_storagePools</li>
<li>TestAccContainerNodePool_withEnablePrivateNodesToggle</li>
<li>TestAccContainerNodePool_withMachineDiskStoragePoolsUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-23 21:43 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccContainerCluster_autopilot_net_admin` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_autopilot_net_admin.log)]
`TestAccContainerCluster_storagePoolsWithNodeConfig` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_storagePoolsWithNodeConfig.log)]
`TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledDefaultsUpdates` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledDefaultsUpdates.log)]
`TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodePool` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_withInsecureKubeletReadonlyPortEnabledInNodePool.log)]
`TestAccContainerCluster_withLoggingVariantUpdates` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_withLoggingVariantUpdates.log)]
`TestAccContainerCluster_withNodeConfigKubeletConfigSettingsUpdates` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_withNodeConfigKubeletConfigSettingsUpdates.log)]
`TestAccContainerNodePool_withEnablePrivateNodesToggle` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerNodePool_withEnablePrivateNodesToggle.log)]
`TestAccContainerNodePool_withMachineDiskStoragePoolsUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerNodePool_withMachineDiskStoragePoolsUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_WithCPAFeatures.log)]
`TestAccContainerCluster_withNodePoolDefaults` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/build-log/recording_build/TestAccContainerCluster_withNodePoolDefaults_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_withNodePoolDefaults.log)]
`TestAccContainerCluster_with_PodCIDROverprovisionDisabled` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/build-log/recording_build/TestAccContainerCluster_with_PodCIDROverprovisionDisabled_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerCluster_with_PodCIDROverprovisionDisabled.log)]
`TestAccContainerNodePool_storagePools` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/build-log/recording_build/TestAccContainerNodePool_storagePools_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording/TestAccContainerNodePool_storagePools.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/33a7dc7a-d8b7-44f5-8cea-458236156ad7/recording) for each test

2024-10-24 16:01 UTC, ScottSuarez commented
Looks like the tests are failing because the API returns these fields when they are empty

```
        
              - user_managed_keys_config {
                  - service_account_signing_keys      = [] -> null
                  - service_account_verification_keys = [] -> null
                    # (6 unchanged attributes hidden)
                }

```

In you're flattener you'll need to make sure to not set `service_account_signing_keys` and `service_account_verification_keys` if they are empty arrays. Terraform is detecting this as a diff.

2024-10-24 16:01 UTC, ScottSuarez requested changes
Waiting on test fix

2024-10-27 21:10 UTC, ahmedtd commented
> Waiting on test fix

Uploaded, let's see if it passes now.

2024-10-28 18:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 647 insertions(+), 363 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 665 insertions(+), 421 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-10-28 18:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/d9d2e86f-d1c1-43d6-92d5-4936945c9d4a/build-log/replaying_test.log)

2024-10-28 19:16 UTC, roaks3 commented
```
sh -c "'/home/runner/work/magic-modules/magic-modules/scripts/gofmtcheck.sh'"
==> Checking that code complies with gofmt requirements...
Error: ./google/services/container/resource_container_cluster.go:6056:2: expected operand, found 'if'
go vet
# github.com/hashicorp/terraform-provider-google/google/services/container
Error: google/services/container/resource_container_cluster.go:6056:2: syntax error: unexpected if, expected expression
make: *** [GNUmakefile:2[9](https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/11560492484/job/32177451980#step:9:10): vet] Error 1
Error: Process completed with exit code 2.
```

@ahmedtd in case you weren't already aware, go/terraform-contribution-guide#before-you-begin has instructions that will allow you to avoid needing to wait for someone to manually approve the build and test runs.

2024-10-28 21:24 UTC, ahmedtd commented
> ```
> sh -c "'/home/runner/work/magic-modules/magic-modules/scripts/gofmtcheck.sh'"
> ==> Checking that code complies with gofmt requirements...
> Error: ./google/services/container/resource_container_cluster.go:6056:2: expected operand, found 'if'
> go vet
> # github.com/hashicorp/terraform-provider-google/google/services/container
> Error: google/services/container/resource_container_cluster.go:6056:2: syntax error: unexpected if, expected expression
> make: *** [GNUmakefile:2[9](https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/11560492484/job/32177451980#step:9:10): vet] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> @ahmedtd in case you weren't already aware, go/terraform-contribution-guide#before-you-begin has instructions that will allow you to avoid needing to wait for someone to manually approve the build and test runs.

I just saw that earlier today.  I've followed the steps, so hopefully the tests will trigger automatically this time.

2024-10-28 21:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/77741706-b390-4477-b340-8730f8c12240/build-log/replaying_test.log)

2024-10-28 21:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-10-28 21:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/e9ba729d-3463-4be5-b2a0-bb0d3489c6ce/build-log/replaying_test.log)

2024-10-28 23:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-10-28 23:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/24faead0-0eaa-4c20-a2fb-3fd51ef418b4/build-log/replaying_test.log)

2024-10-28 23:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-10-28 23:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs//refs/heads/auto-pr-12013/artifacts/45027003-73c0-4976-856a-fe7c8741ea2d/build-log/replaying_test.log)

2024-10-29 00:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 238 insertions(+))

2024-10-29 00:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 196
Skipped tests: 13
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>
<li>TestAccContainerCluster_resourceManagerTags</li>
<li>TestAccContainerCluster_withNodePoolDefaults</li>
<li>TestAccContainerCluster_withWorkloadMetadataConfig</li>
<li>TestAccContainerCluster_with_PodCIDROverprovisionDisabled</li>
<li>TestAccContainerNodePool_storagePools</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 00:26 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccContainerCluster_resourceManagerTags` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerCluster_resourceManagerTags.log)]
`TestAccContainerCluster_withNodePoolDefaults` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerCluster_withNodePoolDefaults.log)]
`TestAccContainerCluster_withWorkloadMetadataConfig` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerCluster_withWorkloadMetadataConfig.log)]
`TestAccContainerCluster_with_PodCIDROverprovisionDisabled` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerCluster_with_PodCIDROverprovisionDisabled.log)]
`TestAccContainerNodePool_storagePools` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerNodePool_storagePools.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccContainerCluster_resourceManagerTags` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/build-log/replaying_build_after_recording/TestAccContainerCluster_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/replaying_after_recording/TestAccContainerCluster_resourceManagerTags.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/61df131d-38d5-4970-942d-0e16d26bfec7/recording) for each test

2024-10-29 01:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 225 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 225 insertions(+))

2024-10-29 01:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 201
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 01:36 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/399c3769-662f-4fad-bdf9-0943b7087f63/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/399c3769-662f-4fad-bdf9-0943b7087f63/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/399c3769-662f-4fad-bdf9-0943b7087f63/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/399c3769-662f-4fad-bdf9-0943b7087f63/recording) for each test

2024-10-29 02:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 229 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 229 insertions(+))

2024-10-29 02:31 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 201
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 02:31 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/78a6e362-a657-4870-972c-5d384b6c54ee/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/78a6e362-a657-4870-972c-5d384b6c54ee/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/78a6e362-a657-4870-972c-5d384b6c54ee/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/78a6e362-a657-4870-972c-5d384b6c54ee/recording) for each test

2024-10-29 17:08 UTC, ScottSuarez requested changes
Waiting on test fix.. Let me know if you need anything :)

```
        Error: Invalid reference
        
          on terraform_plugin_test.tf line 5, in resource "google_privateca_ca_pool" "cluster_ca":
           5:   tier = DEVOPS
        
        A reference to a resource type must be followed by at least one attribute
        access, specifying the resource name.
```

2024-10-29 17:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 229 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 229 insertions(+))

2024-10-29 17:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 201
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 17:40 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/4b7d3713-2148-4e8c-b4d2-44c71f7f7d91/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/4b7d3713-2148-4e8c-b4d2-44c71f7f7d91/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/4b7d3713-2148-4e8c-b4d2-44c71f7f7d91/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/4b7d3713-2148-4e8c-b4d2-44c71f7f7d91/recording) for each test

2024-10-29 18:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 236 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 236 insertions(+))

2024-10-29 18:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 201
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 18:22 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/adfbaf71-9ed3-4316-b24b-f8c5dfcc4f83/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/adfbaf71-9ed3-4316-b24b-f8c5dfcc4f83/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/adfbaf71-9ed3-4316-b24b-f8c5dfcc4f83/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/adfbaf71-9ed3-4316-b24b-f8c5dfcc4f83/recording) for each test

2024-10-29 20:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 240 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 2 files changed, 240 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (417 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  user_managed_keys_config {
    service_account_signing_keys      = # value needed
    service_account_verification_keys = # value needed
  }
}


```

2024-10-29 20:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 215
Passed tests: 201
Skipped tests: 13
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 20:28 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/f691d8ec-03a1-4331-9a0c-f76a5af64d3f/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/f691d8ec-03a1-4331-9a0c-f76a5af64d3f/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/f691d8ec-03a1-4331-9a0c-f76a5af64d3f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/f691d8ec-03a1-4331-9a0c-f76a5af64d3f/recording) for each test

2024-10-29 20:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 255 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 255 insertions(+), 2 deletions(-))

2024-10-29 20:53 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/bb05123a-14ae-4093-95a3-9a38b4675d07/build-log/replaying_test.log)

2024-10-29 20:56 UTC, ScottSuarez commented
Looks like compilation error.. Are you able to compile this locally? It might help shorten the loop for you here.

https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/11582185604/job/32244617738?pr=12013

You could checkout the built branch and see the failures there locally.
https://github.com/modular-magician/terraform-provider-google-beta/tree/auto-pr-12013

```
git add remote mm https://github.com/modular-magician/terraform-provider-google-beta
git fetch mm
git checkout auto-pr-12013
```

2024-10-29 21:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 256 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 256 insertions(+), 2 deletions(-))

2024-10-29 21:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 257 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 257 insertions(+), 2 deletions(-))

2024-10-29 22:25 UTC, modular-magician commented
#### Tests analytics
Total tests: 4011
Passed tests: 3604
Skipped tests: 407
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccContainerCluster_WithCPAFeatures
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/675a8c2f-5d50-4907-a82e-36be43311f73/build-log/replaying_test.log)

2024-10-29 22:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 434 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 434 insertions(+), 2 deletions(-))

2024-10-29 22:53 UTC, modular-magician commented
#### Tests analytics
Total tests: 4226
Passed tests: 3805
Skipped tests: 420
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 22:55 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/97860e67-a079-4a31-a493-44226b077ada/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/97860e67-a079-4a31-a493-44226b077ada/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/97860e67-a079-4a31-a493-44226b077ada/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/97860e67-a079-4a31-a493-44226b077ada/recording) for each test

2024-10-29 23:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 437 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 437 insertions(+), 2 deletions(-))

2024-10-29 23:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 438 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 438 insertions(+), 2 deletions(-))

2024-10-29 23:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 4229
Passed tests: 3808
Skipped tests: 420
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-30 00:00 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/3fb99109-91fe-4712-9048-593561474870/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/3fb99109-91fe-4712-9048-593561474870/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/3fb99109-91fe-4712-9048-593561474870/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/3fb99109-91fe-4712-9048-593561474870/recording) for each test

2024-10-30 00:44 UTC, modular-magician commented
#### Tests analytics
Total tests: 4229
Passed tests: 3808
Skipped tests: 420
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-30 00:45 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/c6328218-36e4-4ebe-b8f5-8b964faa61a2/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/c6328218-36e4-4ebe-b8f5-8b964faa61a2/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/c6328218-36e4-4ebe-b8f5-8b964faa61a2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/c6328218-36e4-4ebe-b8f5-8b964faa61a2/recording) for each test

2024-10-30 00:54 UTC, modular-magician commented
#### Tests analytics
Total tests: 4229
Passed tests: 3808
Skipped tests: 420
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_WithCPAFeatures</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-30 00:55 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_WithCPAFeatures` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/9a5d6c33-b4a3-48b4-963e-09ba53a96e19/build-log/recording_build/TestAccContainerCluster_WithCPAFeatures_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/9a5d6c33-b4a3-48b4-963e-09ba53a96e19/recording/TestAccContainerCluster_WithCPAFeatures.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/9a5d6c33-b4a3-48b4-963e-09ba53a96e19/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/9a5d6c33-b4a3-48b4-963e-09ba53a96e19/recording) for each test

2024-10-30 01:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 440 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12013-old..auto-pr-12013) ( 3 files changed, 440 insertions(+), 2 deletions(-))

2024-10-30 02:43 UTC, modular-magician commented
#### Tests analytics
Total tests: 4229
Passed tests: 3806
Skipped tests: 420
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccContainerCluster_WithCPAFeatures</li>
<li>TestAccContainerCluster_resourceManagerTags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-30 02:59 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/recording/TestAccBackupDRBackupVault_fullUpdate.log)]
`TestAccContainerCluster_WithCPAFeatures` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/recording/TestAccContainerCluster_WithCPAFeatures.log)]
`TestAccContainerCluster_resourceManagerTags` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/recording/TestAccContainerCluster_resourceManagerTags.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccContainerCluster_resourceManagerTags` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/build-log/replaying_build_after_recording/TestAccContainerCluster_resourceManagerTags_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/replaying_after_recording/TestAccContainerCluster_resourceManagerTags.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12013/artifacts/2ed0925a-62c6-4fce-b036-3d2774469b9e/recording) for each test

2024-10-30 04:07 UTC, ahmedtd commented
OK, looks like we have passing tests.  `TestAccContainerCluster_resourceManagerTags` failed transiently because it had to add an IAM rolebinding.

2024-10-30 17:23 UTC, ScottSuarez approved these changes

2024-10-30 17:24 UTC, merged

2024-10-30 17:25 UTC, ScottSuarez commented
Thanks for the work !!