Autogen tool in Go
GoogleCloudPlatform/magic-modules pull request #12038
Opened 2024-10-17 19:10 UTC by slevenick

Adds autogen tool with Go, may not have full parity with ruby version, but it works for some products

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-10-17 20:31 UTC, c2thorn requested changes
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/openapi_generate/parser.go#L165-L169 needs to be deleted

2024-10-18 21:04 UTC, slevenick commented
> https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/openapi_generate/parser.go#L165-L169 needs to be deleted

Done, also added copyright header writing, version stripping and updated our YAML lint to allow the spacing used by Go YAML marshaling

2024-10-18 21:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-10-18 21:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-10-18 21:17 UTC, c2thorn approved these changes

2024-10-18 22:23 UTC, merged