Add VPC Flow Logs Config API to terraform-provider-google-beta.
GoogleCloudPlatform/magic-modules pull request #12103
Opened 2024-10-23 12:36 UTC by alkobi-google

Add VPC Flow Logs Config API to terraform-provider-google-beta.
The API YAML was created using terraform-autogen.

2024-10-23 15:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12103-old..auto-pr-12103) ( 5 files changed, 1180 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12103-old..auto-pr-12103) ( 8 files changed, 1502 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12103-old..auto-pr-12103) ( 2 files changed, 168 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_management_vpc_flow_logs_config` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_management_vpc_flow_logs_config" "primary" {
  aggregation_interval    = # value needed
  description             = # value needed
  filter_expr             = # value needed
  flow_sampling           = # value needed
  interconnect_attachment = # value needed
  labels                  = # value needed
  metadata                = # value needed
  metadata_fields         = # value needed
  state                   = # value needed
}


```

2024-10-23 17:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 4209
Passed tests: 3783
Skipped tests: 420
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample</li>
<li>TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample</li>
<li>TestAccNetworkManagementConnectivityTest_update</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnExample</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_update</li>
<li>TestAccSqlDatabaseInstance_Edition_Downgrade</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-23 17:27 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample.log)]
`TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample.log)]
`TestAccNetworkManagementConnectivityTest_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccNetworkManagementConnectivityTest_update.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnExample.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccNetworkManagementVpcFlowLogsConfig_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccSqlDatabaseInstance_Edition_Downgrade` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/build-log/recording_build/TestAccSqlDatabaseInstance_Edition_Downgrade_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording/TestAccSqlDatabaseInstance_Edition_Downgrade.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/2c046f5b-5811-470c-ac7d-c8ff2fccb8ab/recording) for each test

2024-10-23 22:00 UTC, hao-nan-li requested changes
Looks like there's some fields missing in the tests. Could you please add them in?

2024-10-24 21:32 UTC, alkobi-google commented
> Looks like there's some fields missing in the tests. Could you please add them in?

I added almost all of the missing fields in the new commit.
The ones currently missing are
* metadata-fields - which are absent because I set metadata to "exclude" and not "custom"
* interconnect-attachment - because the VPC Flow Logs Config applies to one of [interconnect attachment, VPN gateway], and this tests only the VPN gateway (and updates it's fields accordingly)

2024-10-24 23:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12103-old..auto-pr-12103) ( 5 files changed, 1180 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12103-old..auto-pr-12103) ( 8 files changed, 1506 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12103-old..auto-pr-12103) ( 2 files changed, 168 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_management_vpc_flow_logs_config` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_management_vpc_flow_logs_config" "primary" {
  aggregation_interval    = # value needed
  description             = # value needed
  filter_expr             = # value needed
  flow_sampling           = # value needed
  interconnect_attachment = # value needed
  labels                  = # value needed
  metadata                = # value needed
  metadata_fields         = # value needed
  state                   = # value needed
}


```

2024-10-25 00:23 UTC, modular-magician commented
#### Tests analytics
Total tests: 4214
Passed tests: 3792
Skipped tests: 420
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetworkManagementVpcFlowLogsConfig_update</li>
<li>TestAccSqlDatabaseInstance_Edition_Downgrade</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-25 00:35 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetworkManagementVpcFlowLogsConfig_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/d7fa014d-4cc9-4543-9545-7379b61001e2/recording/TestAccNetworkManagementVpcFlowLogsConfig_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccSqlDatabaseInstance_Edition_Downgrade` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/d7fa014d-4cc9-4543-9545-7379b61001e2/build-log/recording_build/TestAccSqlDatabaseInstance_Edition_Downgrade_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/d7fa014d-4cc9-4543-9545-7379b61001e2/recording/TestAccSqlDatabaseInstance_Edition_Downgrade.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/d7fa014d-4cc9-4543-9545-7379b61001e2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12103/artifacts/d7fa014d-4cc9-4543-9545-7379b61001e2/recording) for each test

2024-10-28 14:29 UTC, closed without merging