Adding BackupplanAssociation TF resource
GoogleCloudPlatform/magic-modules pull request #12159
Opened 2024-10-28 01:03 UTC by niharika-98

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-resource
`google_backup_dr_backup_plan_association`
```

2024-10-28 01:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 6 files changed, 1149 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-10-28 01:17 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-28 01:20 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f1ee05-465b-4df5-b34c-615375f11b86/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f1ee05-465b-4df5-b34c-615375f11b86/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f1ee05-465b-4df5-b34c-615375f11b86/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f1ee05-465b-4df5-b34c-615375f11b86/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f1ee05-465b-4df5-b34c-615375f11b86/recording) for each test

2024-10-28 05:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 6 files changed, 1154 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-10-28 05:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 3
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-28 05:22 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6d9e6ced-6250-4586-9e91-79cbe48a5e20/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6d9e6ced-6250-4586-9e91-79cbe48a5e20/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6d9e6ced-6250-4586-9e91-79cbe48a5e20/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6d9e6ced-6250-4586-9e91-79cbe48a5e20/recording) for each test

2024-10-28 06:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 6 files changed, 1154 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-10-28 06:02 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 3
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-28 06:02 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/2bfa9e56-9f3b-4d38-80f0-ead7980e70c7/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/2bfa9e56-9f3b-4d38-80f0-ead7980e70c7/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/2bfa9e56-9f3b-4d38-80f0-ead7980e70c7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/2bfa9e56-9f3b-4d38-80f0-ead7980e70c7/recording) for each test

2024-10-28 18:06 UTC, SarahFrench commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +func TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic(t *testing.T) {
[The test failure](https://github.com/GoogleCloudPlatform/magic-modules/pull/12159#issuecomment-2440624535) here is: 

```
        Error: Invalid resource type
        
          on terraform_plugin_test.tf line 55, in resource "google_backup_dr_backup_plan" "foo":
          55: resource "google_backup_dr_backup_plan" "foo" { 
        
        The provider hashicorp/google does not support resource type
        "google_backup_dr_backup_plan".
```

When I look at the `provider_mmv1_resources.go` file that is [generated in the google-beta provider from this PR](https://github.com/modular-magician/terraform-provider-google-beta/blob/auto-pr-12159/google-beta/provider/provider_mmv1_resources.go) I cannot see `google_backup_dr_backup_plan` listed there. Have you already had a PR accepted for adding that resource? If so you may need to pull those changes into your branch.

2024-11-01 19:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 7 files changed, 1159 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-11-01 19:18 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 4
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-01 19:21 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/1fbb270a-7e40-41e7-93fa-846a9996db9e/recording/TestAccBackupDRBackupVault_fullUpdate.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/1fbb270a-7e40-41e7-93fa-846a9996db9e/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/1fbb270a-7e40-41e7-93fa-846a9996db9e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/1fbb270a-7e40-41e7-93fa-846a9996db9e/recording) for each test

2024-11-01 19:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 7 files changed, 1159 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-11-01 19:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 3 files changed, 215 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 7 files changed, 1159 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-11-01 19:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 6
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/679a2647-273e-495b-8df6-a9c28d96ac58/build-log/replaying_test.log)

2024-11-01 19:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 6
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/7a27fecf-35c1-4e09-ade9-ff0f4f374f02/build-log/replaying_test.log)

2024-11-04 04:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 249 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 8 files changed, 1193 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 163 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_backup_dr_backup_plan_association` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_backup_dr_backup_plan_association" "primary" {
  rules_config_info {
    last_backup_error {
      code    = # value needed
      message = # value needed
    }
    last_backup_state = # value needed
  }
}


```

2024-11-04 04:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 5
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupVault_fullUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 04:30 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f8c155-05a9-41af-bce0-39b21a0affa8/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f8c155-05a9-41af-bce0-39b21a0affa8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c6f8c155-05a9-41af-bce0-39b21a0affa8/recording) for each test

2024-11-04 04:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 246 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 8 files changed, 1097 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 79 insertions(+))

2024-11-04 04:36 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 0
Skipped tests: 0
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample</li>
<li>TestAccBackupDRBackupVault_backupDrBackupVaultFullExample</li>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlan_basic</li>
<li>TestAccDataSourceGoogleBackupDRManagementServer_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 04:36 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample.log)]
`TestAccBackupDRBackupVault_backupDrBackupVaultFullExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccBackupDRBackupVault_backupDrBackupVaultFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccBackupDRBackupVault_backupDrBackupVaultFullExample.log)]
`TestAccBackupDRBackupVault_fullUpdate` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccBackupDRBackupVault_fullUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccBackupDRBackupVault_fullUpdate.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]
`TestAccDataSourceGoogleBackupDRBackupPlan_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlan_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccDataSourceGoogleBackupDRBackupPlan_basic.log)]
`TestAccDataSourceGoogleBackupDRManagementServer_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_build/TestAccDataSourceGoogleBackupDRManagementServer_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording/TestAccDataSourceGoogleBackupDRManagementServer_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6ee6193b-a69f-4e41-ac2f-8513408a6508/recording) for each test

2024-11-04 04:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 270 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1293 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 79 insertions(+))

2024-11-04 04:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccBackupDRBackupPlanAssociation_backupDrBpaExample
- TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/4fd2dde8-99af-4974-acc7-298cb22683f6/build-log/replaying_test.log)

2024-11-04 05:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 270 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1254 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 79 insertions(+))

2024-11-04 05:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccBackupDRBackupPlanAssociation_backupDrBpaExample
- TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c10eb1a6-95a4-4d42-b24d-986721b86b22/build-log/replaying_test.log)

2024-11-04 05:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 272 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1264 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 05:34 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 0
Skipped tests: 0
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample</li>
<li>TestAccBackupDRBackupVault_backupDrBackupVaultFullExample</li>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlan_basic</li>
<li>TestAccDataSourceGoogleBackupDRManagementServer_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 05:35 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccBackupDRBackupPlan_backupDrBackupPlanSimpleExample.log)]
`TestAccBackupDRBackupVault_backupDrBackupVaultFullExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccBackupDRBackupVault_backupDrBackupVaultFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccBackupDRBackupVault_backupDrBackupVaultFullExample.log)]
`TestAccBackupDRBackupVault_fullUpdate` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccBackupDRBackupVault_fullUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccBackupDRBackupVault_fullUpdate.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]
`TestAccDataSourceGoogleBackupDRBackupPlan_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlan_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccDataSourceGoogleBackupDRBackupPlan_basic.log)]
`TestAccDataSourceGoogleBackupDRManagementServer_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_build/TestAccDataSourceGoogleBackupDRManagementServer_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording/TestAccDataSourceGoogleBackupDRManagementServer_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/e091ed29-c55f-4983-b483-f680d2177304/recording) for each test

2024-11-04 05:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 274 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1267 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 05:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 5
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 05:59 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fd227370-270f-45e6-8916-ab5962d9a4c8/recording) for each test

2024-11-04 06:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 274 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1273 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 96 insertions(+))



## Errors

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-11-04 06:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccBackupDRBackupPlanAssociation_backupDrBpaExample
- TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6f542b7f-8b8d-4cc0-b024-54b7ceedafaa/build-log/replaying_test.log)

2024-11-04 06:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 274 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1272 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 96 insertions(+))

2024-11-04 06:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 4
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 07:01 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/8f6c5004-0ac2-409c-9000-2eef2fe8ad3e/recording) for each test

2024-11-04 07:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 277 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1275 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 07:23 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 5
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 07:26 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/ab48e044-bf6e-4ec6-9e0f-51812f78c0fa/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/ab48e044-bf6e-4ec6-9e0f-51812f78c0fa/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/ab48e044-bf6e-4ec6-9e0f-51812f78c0fa/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/ab48e044-bf6e-4ec6-9e0f-51812f78c0fa/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/ab48e044-bf6e-4ec6-9e0f-51812f78c0fa/recording) for each test

2024-11-04 07:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1277 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 07:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 07:50 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/f32ca02b-7d2b-4a60-857d-a58ddd16800f/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/f32ca02b-7d2b-4a60-857d-a58ddd16800f/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/f32ca02b-7d2b-4a60-857d-a58ddd16800f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/f32ca02b-7d2b-4a60-857d-a58ddd16800f/recording) for each test

2024-11-04 08:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1277 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 08:06 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 08:09 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d893596b-3571-4c33-b941-c0983c9eabef/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d893596b-3571-4c33-b941-c0983c9eabef/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d893596b-3571-4c33-b941-c0983c9eabef/recording) for each test

2024-11-04 08:13 UTC, niharika-98 commented
Hi @SarahFrench , Addressed all comments and acceptance tests are included and passing. We are looking at providing TF support for this resource in Nov 11 rollout as product is GA. Can you pls prioritize reviewing this.

2024-11-04 09:42 UTC, SarahFrench commented
Hi @niharika-98, thanks for your email about this PR. I am on PTO today but I’ll ask our partner team in Google if anyone can take over as reviewer to meet your timeline.

2024-11-04 17:49 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> + depends_on= [ google_backup_dr_backup_vault.my-backup-vault ]
weird indentation

2024-11-04 17:49 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +	}
weird indentation

2024-11-04 17:49 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +  backup_plan_association_id = "bpa-test-%{random_suffix}"
```suggestion
  backup_plan_association_id = "tf-test-bpa-test-%{random_suffix}"
```

2024-11-04 17:49 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +  backup_plan_association_id="bpa-test-%{random_suffix}"
```suggestion
  backup_plan_association_id="tf-test-bpa-test-%{random_suffix}"
```

2024-11-04 17:50 UTC, zli82016 commented on mmv1/third_party/terraform/website/docs/d/backup_dr_backup_plan_association.html.markdown
> +  }
weird indentation

2024-11-04 17:51 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
```suggestion
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
```

2024-11-04 19:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1277 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 19:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1277 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 19:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 4
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccBackupDRBackupVault_fullUpdate</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 19:11 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/d0c4707e-d490-4430-a510-4326054a5484/recording) for each test

2024-11-04 19:11 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/3d4de170-ffec-4580-b508-cbf5bab31488/recording) for each test

2024-11-04 19:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 19:19 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 5
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 19:22 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/61d3e8c3-b7f5-4733-9df8-f4edb83ec5e6/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/61d3e8c3-b7f5-4733-9df8-f4edb83ec5e6/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/61d3e8c3-b7f5-4733-9df8-f4edb83ec5e6/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/61d3e8c3-b7f5-4733-9df8-f4edb83ec5e6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/61d3e8c3-b7f5-4733-9df8-f4edb83ec5e6/recording) for each test

2024-11-04 20:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-04 20:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 5
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-04 20:16 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fdaeaa84-d5e5-46aa-88c2-9cf85c20f31d/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fdaeaa84-d5e5-46aa-88c2-9cf85c20f31d/build-log/recording_build/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fdaeaa84-d5e5-46aa-88c2-9cf85c20f31d/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fdaeaa84-d5e5-46aa-88c2-9cf85c20f31d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/fdaeaa84-d5e5-46aa-88c2-9cf85c20f31d/recording) for each test

2024-11-04 20:18 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
Besides this change, `provider = google-beta` is needed for each resource in the configuration.

2024-11-04 20:50 UTC, zli82016 commented on mmv1/templates/terraform/examples/backup_dr_bpa.tf.tmpl
> +  account_id   = "{{index $.Vars "account_idaccount_idaccount_id"}}"
```suggestion
  account_id   = "{{index $.Vars "account_id"}}"
```

2024-11-04 20:50 UTC, zli82016 requested changes
Fix failed test

2024-11-05 02:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 02:26 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 5
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBackupDRBackupPlanAssociation_backupDrBpaExample</li>
<li>TestAccBackupDRBackupVault_fullUpdate</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-05 02:29 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBackupDRBackupPlanAssociation_backupDrBpaExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/eb3bf50a-a64c-4124-a6ec-1c78673db9c6/recording/TestAccBackupDRBackupPlanAssociation_backupDrBpaExample.log)]
`TestAccBackupDRBackupVault_fullUpdate` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/eb3bf50a-a64c-4124-a6ec-1c78673db9c6/recording/TestAccBackupDRBackupVault_fullUpdate.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/eb3bf50a-a64c-4124-a6ec-1c78673db9c6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/eb3bf50a-a64c-4124-a6ec-1c78673db9c6/recording) for each test

2024-11-05 11:09 UTC, SarahFrench reviewed
Thanks for helping with review @zli82016!

@niharika-98 I can see that these open review comments are yet to be addressed:

- [Query about whether ignore_changes is needed](https://github.com/GoogleCloudPlatform/magic-modules/pull/12159/files#r1828134440)
- [Request to change the acceptance test to use the Beta provider factory](https://github.com/GoogleCloudPlatform/magic-modules/pull/12159/files#r1828147163)
- Various requests to update resource names in acceptance test configuration, to make those resources identifiable as deletable if the test cannot delete those resources successfully itself:
    1) https://github.com/GoogleCloudPlatform/magic-modules/pull/12159/files#r1828141638
     2) https://github.com/GoogleCloudPlatform/magic-modules/pull/12159/files#r1828141872
    3) https://github.com/GoogleCloudPlatform/magic-modules/pull/12159/files#r1828142105

2024-11-05 12:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 12:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 12:59 UTC, niharika-98 commented
Addressed comments on PR

When we pass compute instance, project/projectname/locations/location/instances/instance-name as it is returned in id field of compute. But api returns projects/projectid/locations/locationid/instances/instanceid after creation completion in response. Hence there is mismatch so ignoring it. Compute instance name is parameter which is input to create BPA resource

VCR-test is giving error. Can't find exact string but it is similar to "Changes we present even after applying step 1/1. Terraform forces replacement"


Other comments are all addressed.

2024-11-05 13:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 13:02 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-05 13:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 278 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1280 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 13:05 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c14a4220-a49f-4d18-9718-f542e2675140/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c14a4220-a49f-4d18-9718-f542e2675140/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/c14a4220-a49f-4d18-9718-f542e2675140/recording) for each test

2024-11-05 13:05 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/7b755c19-44db-4db6-b28e-5196f4232cdb/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/7b755c19-44db-4db6-b28e-5196f4232cdb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/7b755c19-44db-4db6-b28e-5196f4232cdb/recording) for each test

2024-11-05 13:06 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/426d8be3-ef9e-4221-9a11-55c8d31ddcde/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/426d8be3-ef9e-4221-9a11-55c8d31ddcde/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/426d8be3-ef9e-4221-9a11-55c8d31ddcde/recording) for each test

2024-11-05 13:07 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 7
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/b1e5e480-fea1-4783-a2fd-a8e4239d8092/build-log/replaying_test.log)

2024-11-05 17:21 UTC, zli82016 commented
> When we pass compute instance, project/projectname/locations/location/instances/instance-name as it is returned in id field of compute. But api returns projects/projectid/locations/locationid/instances/instanceid after creation completion in response. Hence there is mismatch so ignoring it. Compute instance name is parameter which is input to create BPA resource

@niharika-98 , thanks for addressing the comments. Instead of adding `ignore_changes` to the tests, can you please add `ignore_read: true` to the `resource` field to address this issue?

2024-11-05 17:22 UTC, zli82016 requested changes

2024-11-05 17:22 UTC, zli82016 commented on mmv1/products/backupdr/BackupPlanAssociation.yaml
> +  - name: 'resource'
Can you add `ignore_read: true` to address the perma-diff issue?

2024-11-05 17:22 UTC, zli82016 commented on mmv1/third_party/terraform/services/backupdr/data_source_backup_dr_backup_plan_association_test.go.tmpl
> +  }
`add ignore_read: true` is not needed here.

2024-11-05 17:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 275 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1264 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 17:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-05 17:40 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/cb6c862c-f60e-413f-85d8-7bb9e0fed444/build-log/recording_build/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/cb6c862c-f60e-413f-85d8-7bb9e0fed444/recording/TestAccDataSourceGoogleBackupDRBackupPlanAssociation_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/cb6c862c-f60e-413f-85d8-7bb9e0fed444/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/cb6c862c-f60e-413f-85d8-7bb9e0fed444/recording) for each test

2024-11-05 18:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12159-old..auto-pr-12159) ( 4 files changed, 275 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12159-old..auto-pr-12159) ( 9 files changed, 1267 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12159-old..auto-pr-12159) ( 1 file changed, 89 insertions(+))

2024-11-05 18:07 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 7
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>backupdr</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12159/artifacts/6c97e39f-8dbe-4460-b839-7258b294eab1/build-log/replaying_test.log)

2024-11-05 18:12 UTC, zli82016 approved these changes
LGTM

2024-11-05 18:13 UTC, merged