Add VPC Flow Logs Config Terraform API
GoogleCloudPlatform/magic-modules pull request #12161
Opened 2024-10-28 14:27 UTC by alkobi-google

Add VPC Flow Logs Config Terraform API.
The API Yaml created using the terraform-autogen tool.
VPC Flow Logs support either Interconnect or VPN Gateways, so I created a basic, full and update tests for each.

2024-10-29 21:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12161-old..auto-pr-12161) ( 5 files changed, 1363 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12161-old..auto-pr-12161) ( 8 files changed, 2049 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12161-old..auto-pr-12161) ( 2 files changed, 168 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_management_vpc_flow_logs_config` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_management_vpc_flow_logs_config" "primary" {
  filter_expr     = # value needed
  labels          = # value needed
  metadata_fields = # value needed
}


```

2024-10-29 22:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 4231
Passed tests: 3802
Skipped tests: 420
Affected tests: 9

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample</li>
<li>TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample</li>
<li>TestAccNetworkManagementConnectivityTest_update</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectBasicExample</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectFullExample</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnBasicExample</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnFullExample</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_updateInterconnect</li>
<li>TestAccNetworkManagementVpcFlowLogsConfig_updateVpn</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-10-29 22:44 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample.log)]
`TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample.log)]
`TestAccNetworkManagementConnectivityTest_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementConnectivityTest_update.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectBasicExample.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectFullExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigInterconnectFullExample.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnBasicExample.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnFullExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_networkManagementVpcFlowLogsConfigVpnFullExample.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_updateInterconnect` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_updateInterconnect.log)]
`TestAccNetworkManagementVpcFlowLogsConfig_updateVpn` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording/TestAccNetworkManagementVpcFlowLogsConfig_updateVpn.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/a4830ff3-61d6-4ad0-bef3-8141d57f1d72/recording) for each test

2024-10-30 07:43 UTC, alkobi-google commented
Updated the change log message to fulfill changelog-checker requirements

2024-10-30 21:17 UTC, NickElliot requested changes
minor change -- additionally, is this resource intended to be beta only? if so it needs a `min_version: 'beta'` flag

2024-10-30 21:17 UTC, NickElliot commented on mmv1/products/networkmanagement/VpcFlowLogsConfig.yaml
> +  Flow Logs for VPC, Interconnect attachments or VPN Tunnels."
```suggestion
description: |
  VPC Flow Logs Config is a resource that lets you configure
  Flow Logs for VPC, Interconnect attachments or VPN Tunnels.
```

2024-10-31 11:37 UTC, alkobi-google commented on mmv1/products/networkmanagement/VpcFlowLogsConfig.yaml
> +  Flow Logs for VPC, Interconnect attachments or VPN Tunnels."
Done.

2024-10-31 11:45 UTC, alkobi-google commented
> minor change -- additionally, is this resource intended to be beta only? if so it needs a `min_version: 'beta'` flag

This resource is intended for GA by the end of Q1 2025, currently only supported in beta.
The tests (examples) contain the `min_version: 'beta'` flag

2024-11-01 08:55 UTC, alkobi-google reviewed
Updated the VpcFlowLogsConfig.yaml description.
Also, the examples in VpcFlowLogsConfig.yaml contain the 'min_version: beta` flag.
This API is currently intended for beta but will be enabled for GA as well in the future (current ETA is Q1 2025)

2024-11-01 22:49 UTC, NickElliot requested changes
even if support is planned Soon, it needs to be flagged as a beta only resource if the provider is releasing it as such

2024-11-01 22:49 UTC, NickElliot commented on mmv1/products/networkmanagement/VpcFlowLogsConfig.yaml
> +  Flow Logs for VPC, Interconnect attachments or VPN Tunnels.
```suggestion
  Flow Logs for VPC, Interconnect attachments or VPN Tunnels.
min_version: beta
```

2024-11-02 14:20 UTC, alkobi-google reviewed
Updated VpcFlowLogsConfig to state it's beta only by adding min_version: beta

2024-11-02 14:20 UTC, alkobi-google commented on mmv1/products/networkmanagement/VpcFlowLogsConfig.yaml
> +  Flow Logs for VPC, Interconnect attachments or VPN Tunnels.
Done.

2024-11-04 17:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12161-old..auto-pr-12161) ( 2 files changed, 436 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12161-old..auto-pr-12161) ( 10 files changed, 2057 insertions(+), 6 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12161-old..auto-pr-12161) ( 2 files changed, 168 insertions(+), 2 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_network_management_vpc_flow_logs_config` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_network_management_vpc_flow_logs_config" "primary" {
  filter_expr     = # value needed
  labels          = # value needed
  metadata_fields = # value needed
}


```

2024-11-04 18:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 4260
Passed tests: 3843
Skipped tests: 417
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12161/artifacts/527f5ebd-4174-4129-815c-6e4390139828/build-log/replaying_test.log)

2024-11-04 21:01 UTC, NickElliot approved these changes
LGTM!

2024-11-04 21:19 UTC, merged