Add missing documentation for custom learned routes
GoogleCloudPlatform/magic-modules pull request #12211
Opened 2024-10-31 21:02 UTC by gorge511

Add missing documentation for fields related to custom learned routes added in #11118.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:note
compute: added documentation for `custom_learned_ip_ranges` and `custom_learned_route_priority`
```

2024-11-01 21:08 UTC, zli82016 requested changes
Conflicts need to be resolved.

2024-11-02 04:37 UTC, gorge511 commented
> Conflicts need to be resolved.

Conflict with #12208 has been resolved.

2024-11-04 17:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12211-old..auto-pr-12211) ( 2 files changed, 22 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12211-old..auto-pr-12211) ( 2 files changed, 22 insertions(+), 3 deletions(-))

2024-11-04 17:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 1058
Passed tests: 985
Skipped tests: 73
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12211/artifacts/1fa87e43-2321-4ad7-b031-05e8b67fc85b/build-log/replaying_test.log)

2024-11-04 17:57 UTC, zli82016 approved these changes
LGTM

2024-11-04 17:57 UTC, merged