Added support for additional values KCP_HPA in `google_container_clus…
GoogleCloudPlatform/magic-modules pull request #12221
Opened 2024-11-01 16:04 UTC by MalusGreen

…ter.logging_config

 Adds terraform support for new HPA Observability logs.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:REPLACEME
container: added additional value KCP_HPA for `google_container_cluster.logging_config`
```

2024-11-05 11:50 UTC, SarahFrench commented
Note: the `mmv1-check-templates / version-guard-check (pull_request)` check isn't a blocker for this PR, and the check was updated in https://github.com/GoogleCloudPlatform/magic-modules/pull/12208.

I'll return to this PR once it's marked as ready for review

2024-11-22 16:59 UTC, SarahFrench commented
@modular-magician reassign-reviewer

2025-01-14 16:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-01-14 17:24 UTC, modular-magician commented
#### Tests analytics
Total tests: 219
Passed tests: 206
Skipped tests: 12
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-14 17:53 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/a3d15e18-9882-4403-a78a-23daaed356a4/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/a3d15e18-9882-4403-a78a-23daaed356a4/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/a3d15e18-9882-4403-a78a-23daaed356a4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/a3d15e18-9882-4403-a78a-23daaed356a4/recording) for each test

2025-01-15 00:22 UTC, hao-nan-li reviewed
I'm not sure if the test failure is caused by the change.

Have you tried to run the failed test locally?

2025-01-15 17:38 UTC, hao-nan-li commented
/gcbrun

2025-01-15 17:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-01-15 18:47 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/6ae7d78a-94ef-4d55-a0ea-090be6df467f/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/6ae7d78a-94ef-4d55-a0ea-090be6df467f/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/6ae7d78a-94ef-4d55-a0ea-090be6df467f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/6ae7d78a-94ef-4d55-a0ea-090be6df467f/recording) for each test

2025-01-16 17:45 UTC, MalusGreen commented
The cl passed all presubmits before the current sync. I don't believe the current error is caused by the PR. I'll sync and reun the CI.

2025-01-16 17:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-01-16 18:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 219
Passed tests: 206
Skipped tests: 12
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-16 18:55 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/5602f35b-517a-4977-9d0e-fbc16c554617/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/5602f35b-517a-4977-9d0e-fbc16c554617/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/5602f35b-517a-4977-9d0e-fbc16c554617/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/5602f35b-517a-4977-9d0e-fbc16c554617/recording) for each test

2025-01-16 21:10 UTC, hao-nan-li commented
Are you able to run this test locally and see if it works?

2025-01-30 17:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-01-30 17:34 UTC, modular-magician commented
#### Tests analytics
Total tests: 225
Passed tests: 213
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-30 18:06 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/3e1c349e-24ea-4a5b-b2c5-35b22bac3614/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/3e1c349e-24ea-4a5b-b2c5-35b22bac3614/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/3e1c349e-24ea-4a5b-b2c5-35b22bac3614/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/3e1c349e-24ea-4a5b-b2c5-35b22bac3614/recording) for each test

2025-01-30 20:53 UTC, MalusGreen commented
> Are you able to run this test locally and see if it works?

This change runs. The problem is our api change has not propagated and is being blocked internally. Will reopen at a later time.

2025-02-25 15:36 UTC, MalusGreen commented
@modular-magician reassign-reviewer

2025-02-25 23:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-02-25 23:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 225
Passed tests: 213
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-26 00:01 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/88fecf59-45d1-4e32-b7a3-4e6918e98da8/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/88fecf59-45d1-4e32-b7a3-4e6918e98da8/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/88fecf59-45d1-4e32-b7a3-4e6918e98da8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/88fecf59-45d1-4e32-b7a3-4e6918e98da8/recording) for each test

2025-02-26 19:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 5 insertions(+), 5 deletions(-))

2025-02-26 19:27 UTC, modular-magician commented
#### Tests analytics
Total tests: 225
Passed tests: 213
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-26 19:57 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/73d4b025-8b7f-4f35-b695-9a05c16ab86e/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/73d4b025-8b7f-4f35-b695-9a05c16ab86e/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/73d4b025-8b7f-4f35-b695-9a05c16ab86e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/73d4b025-8b7f-4f35-b695-9a05c16ab86e/recording) for each test

2025-02-27 16:33 UTC, roaks3 requested changes
The change here is simple enough, but from the test failures, it looks like it still isn't shipped.

Please review go/terraform-launch-stages if you haven't already, but assuming this is an option we can support in the GA `google` provider, is there something else that needs to be changed for the feature to work? The error message mentions the GKE version being too old.

2025-03-04 19:03 UTC, MalusGreen commented
> The change here is simple enough, but from the test failures, it looks like it still isn't shipped.
> 
> Please review go/terraform-launch-stages if you haven't already, but assuming this is an option we can support in the GA `google` provider, is there something else that needs to be changed for the feature to work? The error message mentions the GKE version being too old.

The change has been launched to prod but requires, as seen in the error, a higher GKE version than the current default: https://screenshot.googleplex.com/7pkLmTfJjtc36SF

What would be the fastest way to update this default for the VCR tests?

2025-03-05 20:10 UTC, roaks3 commented
I think you got it! Let me run tests and see if that resolves.

2025-03-05 20:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 6 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 6 insertions(+), 5 deletions(-))

2025-03-05 20:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 226
Passed tests: 214
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-03-05 21:27 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0963a0e1-a1ba-4137-8469-afa44d27db2d/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0963a0e1-a1ba-4137-8469-afa44d27db2d/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0963a0e1-a1ba-4137-8469-afa44d27db2d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0963a0e1-a1ba-4137-8469-afa44d27db2d/recording) for each test

2025-03-05 21:35 UTC, roaks3 commented
I think the problem is that the field only sets the version on initial creation (I think?). If that's the case, you probably need to specify that version in each of the configs used for that test, ie.
* testAccContainerCluster_basic
* testAccContainerCluster_withLoggingConfigEnabled
* testAccContainerCluster_withLoggingConfigDisabled
* testAccContainerCluster_withLoggingConfigUpdated

2025-03-06 22:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 9 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 9 insertions(+), 5 deletions(-))

2025-03-06 23:12 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_basic.log)]
`TestAccContainerCluster_withAuthenticatorGroupsConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withAuthenticatorGroupsConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withAuthenticatorGroupsConfig.log)]
`TestAccContainerCluster_withDNSConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withDNSConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withDNSConfig.log)]
`TestAccContainerCluster_withDatabaseEncryption` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withDatabaseEncryption_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withDatabaseEncryption.log)]
`TestAccContainerCluster_withIdentityServiceConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withIdentityServiceConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withIdentityServiceConfig.log)]
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withLoggingConfig.log)]
`TestAccContainerCluster_withMonitoringConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withMonitoringConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withMonitoringConfig.log)]
`TestAccContainerCluster_withNodePoolDefaults` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_build/TestAccContainerCluster_withNodePoolDefaults_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording/TestAccContainerCluster_withNodePoolDefaults.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/285e5fc2-4867-4790-8982-f6cb300f7bf4/recording) for each test

2025-03-07 18:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 35 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 35 insertions(+), 16 deletions(-))

2025-03-07 18:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 226
Passed tests: 214
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-03-10 16:39 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0b053989-554a-4083-877c-a2f365a6c5b0/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0b053989-554a-4083-877c-a2f365a6c5b0/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0b053989-554a-4083-877c-a2f365a6c5b0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/0b053989-554a-4083-877c-a2f365a6c5b0/recording) for each test

2025-03-11 18:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 35 insertions(+), 16 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 35 insertions(+), 16 deletions(-))

2025-03-11 19:28 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/21a9665a-0312-456e-bb96-13ffddd85a77/build-log/recording_build/TestAccContainerCluster_withLoggingConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/21a9665a-0312-456e-bb96-13ffddd85a77/recording/TestAccContainerCluster_withLoggingConfig.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/21a9665a-0312-456e-bb96-13ffddd85a77/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/21a9665a-0312-456e-bb96-13ffddd85a77/recording) for each test

2025-03-11 21:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 40 insertions(+), 21 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12221-old..auto-pr-12221) ( 3 files changed, 40 insertions(+), 21 deletions(-))

2025-03-11 22:02 UTC, modular-magician commented
#### Tests analytics
Total tests: 226
Passed tests: 214
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_withLoggingConfig</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-03-11 22:42 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccContainerCluster_withLoggingConfig` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/33620552-04f5-4d5f-b8f6-e88fb7e473ed/recording/TestAccContainerCluster_withLoggingConfig.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/33620552-04f5-4d5f-b8f6-e88fb7e473ed/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12221/artifacts/33620552-04f5-4d5f-b8f6-e88fb7e473ed/recording) for each test

2025-03-12 00:44 UTC, roaks3 approved these changes

2025-03-12 13:35 UTC, merged