This PR adds support for the Dataproc on GDC SparkApplication resourc…
GoogleCloudPlatform/magic-modules pull request #12237
Opened 2024-11-04 18:00 UTC by JerryLeiDing

…e to the provider.

```release-note:new-resource
`google_dataproc_gdc_spark_application`
```

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:REPLACEME

```

2024-11-04 18:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-11-05 17:34 UTC, zli82016 requested changes

2024-11-05 17:34 UTC, zli82016 commented
Also, can you add update tests for the mutable fields by following the [doc](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test) ? Thanks.

2024-11-05 17:35 UTC, zli82016 commented
Is there a Github issue for this PR? If yes, you can link the Github issue in the `description` section of this PR.

2024-11-05 18:01 UTC, JerryLeiDing commented on mmv1/openapi_generate/SparkApplication.yaml
> +name: SparkApplication
Done

2024-11-05 18:02 UTC, JerryLeiDing commented
> Also, can you add update tests for the mutable fields by following the [doc](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test) ? Thanks.

The resource does not support update currently.

2024-11-05 18:08 UTC, zli82016 commented
> > Also, can you add update tests for the mutable fields by following the [doc](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test) ? Thanks.
> 
> The resource does not support update currently.
In this case, can you add `immutable: true` to the resource?

2024-11-05 18:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2357 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2357 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 488 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 20 files changed, 596 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_gdc_spark_application` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_gdc_spark_application" "primary" {
  dependency_images = # value needed
  requested_state   = # value needed
  spark_sql_application_config {
    query_file_uri = # value needed
  }
}


```

2024-11-05 18:52 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationExample.log)]
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationPysparkExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationPysparkExample.log)]
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparkrExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparkrExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/build-log/recording_build/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationBasicExample.log)]
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/build-log/recording_build/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/c4236599-cf46-4147-a7e3-e9a0f026731b/recording) for each test

2024-11-05 18:57 UTC, JerryLeiDing commented
> > > Also, can you add update tests for the mutable fields by following the [doc](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-an-update-test) ? Thanks.
> > 
> > 
> > The resource does not support update currently.
> 
> In this case, can you add `immutable: true` to the resource?

Done

2024-11-05 20:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2318 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2318 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 478 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 20 files changed, 597 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_gdc_spark_application` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_gdc_spark_application" "primary" {
  spark_sql_application_config {
    query_file_uri = # value needed
  }
}


```

2024-11-05 20:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 9
Passed tests: 6
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dataprocgdc</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationBasicExample</li>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationPysparkExample</li>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-07 02:01 UTC, JerryLeiDing commented
@zli82016 are there any other changes you would like to see on this PR?

2024-11-07 17:19 UTC, zli82016 requested changes

2024-11-07 17:19 UTC, zli82016 commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2318 insertions(+), 2 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2318 insertions(+), 2 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 478 insertions(+)) Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 20 files changed, 597 insertions(+))
> 
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_dataproc_gdc_spark_application` (5 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```hcl
> resource "google_dataproc_gdc_spark_application" "primary" {
>   spark_sql_application_config {
>     query_file_uri = # value needed
>   }
> }
> ```

Can you add the test for this field `query_file_uri`? Thanks.

2024-11-07 20:44 UTC, JerryLeiDing commented on mmv1/products/dataprocgdc/SparkApplication.yaml
> +update_mask: true
Done

2024-11-07 20:44 UTC, JerryLeiDing commented
> Can you add the test for this field `query_file_uri`? Thanks.

Done

2024-11-07 20:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 478 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 24 files changed, 713 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_gdc_spark_application` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_gdc_spark_application" "primary" {
  spark_sql_application_config {
    query_file_uri = # value needed
  }
}


```

2024-11-07 20:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 478 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 24 files changed, 713 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_dataproc_gdc_spark_application` (6 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataproc_gdc_spark_application" "primary" {
  spark_sql_application_config {
    query_file_uri = # value needed
  }
}


```

2024-11-07 20:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 10
Passed tests: 9
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dataprocgdc</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-07 20:56 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/241275e7-fcbc-4dae-935e-5de302036c38/build-log/recording_build/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/241275e7-fcbc-4dae-935e-5de302036c38/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/241275e7-fcbc-4dae-935e-5de302036c38/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/241275e7-fcbc-4dae-935e-5de302036c38/recording) for each test

2024-11-07 20:57 UTC, modular-magician commented
#### Tests analytics
Total tests: 10
Passed tests: 9
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dataprocgdc</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-07 20:58 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/54b8c6b7-9fbe-4313-9efc-b7bb4d542b8e/build-log/recording_build/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/54b8c6b7-9fbe-4313-9efc-b7bb4d542b8e/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/54b8c6b7-9fbe-4313-9efc-b7bb4d542b8e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/54b8c6b7-9fbe-4313-9efc-b7bb4d542b8e/recording) for each test

2024-11-07 22:28 UTC, zli82016 commented on mmv1/templates/terraform/examples/dataprocgdc_sparkapplication_sparksql_query_file.tf.tmpl
> +    main_r_file_uri = "gs://some-bucket/something.sql"
```suggestion
    query_file_uri = "gs://some-bucket/something.sql"
```

2024-11-08 00:20 UTC, JerryLeiDing commented on mmv1/templates/terraform/examples/dataprocgdc_sparkapplication_sparksql_query_file.tf.tmpl
> +    main_r_file_uri = "gs://some-bucket/something.sql"
Done

2024-11-08 00:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12237-old..auto-pr-12237) ( 6 files changed, 2393 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12237-old..auto-pr-12237) ( 1 file changed, 478 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12237-old..auto-pr-12237) ( 24 files changed, 713 insertions(+))

2024-11-08 00:31 UTC, modular-magician commented
#### Tests analytics
Total tests: 10
Passed tests: 9
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>dataprocgdc</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-08 00:32 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/9640d9ef-5ae2-43a1-9b2b-22c6dce9d672/recording/TestAccDataprocGdcSparkApplication_dataprocgdcSparkapplicationSparksqlQueryFileExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/9640d9ef-5ae2-43a1-9b2b-22c6dce9d672/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12237/artifacts/9640d9ef-5ae2-43a1-9b2b-22c6dce9d672/recording) for each test

2024-11-08 18:52 UTC, zli82016 approved these changes
LGTM

2024-11-08 18:52 UTC, merged