privateca: update certificate authority samples with more realistic values
GoogleCloudPlatform/magic-modules pull request #12259
Opened 2024-11-06 16:35 UTC by hoexter

Some of the properties configured here are either wrong or at least not very sensible on root certificates / subordinates.
A similar set of fixes got applied to terraform documentation samples in https://github.com/terraform-google-modules/terraform-docs-samples/pull/631

What is left out here is placing the subordinate CA in it's own pool. I could not figure out what is required here to prepare the test infrastructure to provision another pool dedicated to the sub-ca. Technically those two certificates should not reside in the same pool.

2024-11-06 18:26 UTC, melinath requested changes
Part of the reason these samples are structured in this way is to ensure that every field is covered in a [create test](https://googlecloudplatform.github.io/magic-modules/develop/test/test/#add-a-create-test) - this is important to make sure the resources work as expected. Given the number of fields removed here, I'm guessing the coverage is no longer complete.

You can use `exclude_docs` on a complete (but impractical) example to have it be used only for test generation, and have the examples being used in docs be less complete.

2024-11-06 18:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12259-old..auto-pr-12259) ( 2 files changed, 33 insertions(+), 101 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12259-old..auto-pr-12259) ( 2 files changed, 33 insertions(+), 101 deletions(-))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12259-old..auto-pr-12259) ( 2 files changed, 15 insertions(+), 41 deletions(-))

2024-11-06 18:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 39
Passed tests: 31
Skipped tests: 7
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>privateca</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-06 18:36 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12259/artifacts/3202f9f0-8878-4e86-97c6-40463cdb5440/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12259/artifacts/3202f9f0-8878-4e86-97c6-40463cdb5440/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12259/artifacts/3202f9f0-8878-4e86-97c6-40463cdb5440/recording) for each test

2024-11-06 19:55 UTC, melinath approved these changes
Never mind, the fields are all still covered!

2024-11-07 00:16 UTC, gfxcc commented
LGTM

2024-11-07 16:46 UTC, merged