support skip_test option in yaml file
GoogleCloudPlatform/magic-modules pull request #12273
Opened 2024-11-07 19:26 UTC by iyabchen

https://github.com/hashicorp/terraform-provider-google/issues/13623

Support a skip_test option in the yaml file, similar to skip_vcr. 
If skip_test var is not an empty string, then the test is generated with a t.Skip("xxx"). 

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:none

```

2024-11-08 18:15 UTC, ScottSuarez commented
Reassigning to @melinath to ensure this is the way to go. Not sure if there are additional documentation needed around this.

2024-11-08 19:58 UTC, melinath approved these changes
This seems reasonable to me. I don't think we have an obvious place for docs about this to live at the moment but we can add that separately / later.

cc @shuyama1

2024-11-08 19:58 UTC, melinath commented on mmv1/api/resource/examples.go
> +	// The reason to skip a test. Only when this is not empty then the test is skipped.
```suggestion
	// The reason to skip a test. For example, a link to a ticket explaining the issue that needs to be resolved before 
	// unskipping the test. If this is not empty, the test will be skipped.
```

2024-11-08 20:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-11-08 20:13 UTC, melinath requested changes
looks like gofmt is failing

2024-11-12 02:05 UTC, iyabchen commented
> looks like gofmt is failing

Done, seems some trailing whitespace on the comment line.

2024-11-12 02:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-11-13 20:53 UTC, melinath approved these changes

2024-11-13 20:53 UTC, merged