fix: derive the project attribute from resource or compute api or fallback to provider
GoogleCloudPlatform/magic-modules pull request #12305
Opened 2024-11-12 10:46 UTC by gurusai-voleti

Fixes https://github.com/hashicorp/terraform-provider-google/issues/17165

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:bug
storage: derive the project attribute from resource or compute api or fallback to provider in `resource_storage_bucket`
```

2024-11-12 10:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12305-old..auto-pr-12305) ( 1 file changed, 7 insertions(+), 9 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12305-old..auto-pr-12305) ( 1 file changed, 7 insertions(+), 9 deletions(-))

2024-11-12 11:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 109
Passed tests: 100
Skipped tests: 9
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>storage</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12305/artifacts/ba59a128-90e7-4d23-ae6a-23adaf38ec01/build-log/replaying_test.log)

2024-11-14 21:12 UTC, SirGitsalot requested changes
LGTM for the code change, but please update the docs too:

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/d/storage_bucket.html.markdown

The "If no value is supplied in the configuration *or through provider defaults* then the data source will use the Compute API..." is not accurate anymore

2024-11-15 09:39 UTC, gurusai-voleti commented
> LGTM for the code change, but please update the docs too:
> 
> https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/d/storage_bucket.html.markdown
> 
> The "If no value is supplied in the configuration _or through provider defaults_ then the data source will use the Compute API..." is not accurate anymore

Updated documentation

2024-11-15 23:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12305-old..auto-pr-12305) ( 2 files changed, 8 insertions(+), 10 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12305-old..auto-pr-12305) ( 2 files changed, 8 insertions(+), 10 deletions(-))

2024-11-15 23:22 UTC, modular-magician commented
#### Tests analytics
Total tests: 109
Passed tests: 100
Skipped tests: 9
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>storage</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12305/artifacts/d2e45a53-8f2c-4feb-9e85-684247c648ac/build-log/replaying_test.log)

2024-11-15 23:37 UTC, SirGitsalot approved these changes

2024-11-15 23:37 UTC, merged