Add support for diffing field sets
GoogleCloudPlatform/magic-modules pull request #12330
Opened 2024-11-14 18:21 UTC by trodge

This is a less complicated approach to diffing conflict sets, which can be used to detect breaking changes in `ExactlyOneOf` or `AtLeastOneOf`.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:none

```

2024-11-14 18:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-12-26 21:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2025-01-10 18:04 UTC, melinath requested changes
It looks like the unit tests are failing: https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/12508694806/job/34897154818?pr=12330#step:5:472

2025-01-10 18:04 UTC, melinath commented on tools/diff-processor/diff/sets.go
> +func setToSortedSlice(set map[string]struct{}) []string {
nit: I'm not sure it makes sense to split this out into a separate function since it's only used once. Not a blocker though.

2025-01-28 21:57 UTC, trodge commented on tools/diff-processor/diff/sets.go
> +func removeZeroPadding(zeroPadded string) string {
Done

2025-01-28 22:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2025-01-28 22:22 UTC, melinath approved these changes

2025-01-29 21:24 UTC, merged