Add support for shielded instance initial state
GoogleCloudPlatform/magic-modules pull request #12369
Opened 2024-11-20 13:20 UTC by NotTheEvilOne

This PR provides support to use UEFI secure boot with `terraform-provider-google`. The requirement originates from enabling UEFI secure boot with custom config and keys. See https://github.com/gardenlinux/gardenlinux/issues/2473

Fixes https://github.com/hashicorp/terraform-provider-google/issues/20303

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added `shieldedInstanceInitialState` structure to `google_compute_image` resource
```

2024-11-22 19:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 2 files changed, 497 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 2 files changed, 497 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_image` (567 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_image" "primary" {
  shielded_instance_initial_state {
    dbs {
      content   = # value needed
      file_type = # value needed
    }
    dbxs {
      content   = # value needed
      file_type = # value needed
    }
    keks {
      content   = # value needed
      file_type = # value needed
    }
    pk {
      content   = # value needed
      file_type = # value needed
    }
  }
}


```

2024-11-22 19:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 1064
Passed tests: 989
Skipped tests: 73
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain</li>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-22 20:06 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_build/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain.log)]
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording) for each test

2024-11-24 09:19 UTC, NotTheEvilOne commented
> 🔴 Tests failed during RECORDING mode: `TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_build/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain.log)] `TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
> 
> 🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.
> 
> View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/f5b456c3-56cc-465d-ac07-c8fb7978e5ba/recording) for each test

The error message `[...] does not have storage.objects.list access to the Google Cloud Storage bucket. Permission 'storage.objects.list' denied on resource (or it may not exist). ` alternatively to `403 Forbidden` is not helpful in finding out what error occurred.

2024-12-18 19:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 2 files changed, 497 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 2 files changed, 497 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_image` (581 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_image" "primary" {
  shielded_instance_initial_state {
    dbs {
      content   = # value needed
      file_type = # value needed
    }
    dbxs {
      content   = # value needed
      file_type = # value needed
    }
    keks {
      content   = # value needed
      file_type = # value needed
    }
    pk {
      content   = # value needed
      file_type = # value needed
    }
  }
}


```

2024-12-18 20:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 1076
Passed tests: 1002
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-18 20:13 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/41912502-6569-4fe6-91c5-6cf98970de23/build-log/recording_build/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/41912502-6569-4fe6-91c5-6cf98970de23/recording/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/41912502-6569-4fe6-91c5-6cf98970de23/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/41912502-6569-4fe6-91c5-6cf98970de23/recording) for each test

2024-12-18 20:43 UTC, BBBmau commented on mmv1/products/compute/Image.yaml
> +  - name: 'shieldedInstanceInitialState'
although you've added the fields it's still required to include example tests as well as tests that test the update functionality. More can be found here: https://googlecloudplatform.github.io/magic-modules/test/test/#add-an-update-test

2025-01-09 15:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 3 files changed, 566 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 3 files changed, 566 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))

2025-01-09 16:08 UTC, modular-magician commented
#### Tests analytics
Total tests: 1081
Passed tests: 1005
Skipped tests: 73
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeImage_shieldedInstanceInitialState</li>
<li>TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain</li>
<li>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-09 16:18 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccComputeImage_shieldedInstanceInitialState` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/build-log/recording_build/TestAccComputeImage_shieldedInstanceInitialState_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/recording/TestAccComputeImage_shieldedInstanceInitialState.log)]
`TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/build-log/recording_build/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/recording/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/a53807d7-4f7d-405b-a9a9-cc67cf2560f4/recording) for each test

2025-01-09 16:24 UTC, BBBmau commented on mmv1/products/compute/Image.yaml
> +            - name: 'content'
There seems to be a diff happening for `shielded_instance_initial_state.dbxs.content` in the tests causing the test to fail due to a `force replacement`. Could you take a look at this? 
```hcl
resource_compute_image_test.go:119: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # google_compute_image.foobar must be replaced
        -/+ resource "google_compute_image" "foobar" {
              ~ archive_size_bytes = 675924992 -> (known after apply)
              ~ creation_timestamp = "2025-01-09T08:08:42.344-08:00" -> (known after apply)
              ~ disk_size_gb       = 10 -> (known after apply)
              ~ id                 = "projects/ci-test-project-188019/global/images/tf-test-ugt40aiafp" -> (known after apply)
              ~ label_fingerprint  = "vezUS-42LLM=" -> (known after apply)
              ~ licenses           = [
                  - "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/licenses/debian-11-bullseye",
                ] -> (known after apply)
                name               = "tf-test-ugt40aiafp"
              ~ self_link          = "https://www.googleapis.com/compute/v1/projects/ci-test-project-188019/global/images/tf-test-ugt40aiafp" -> (known after apply)
              ~ source_image       = "https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/debian-11-bullseye-v20241210" -> "https://www.googleapis.com/compute/beta/projects/debian-cloud/global/images/debian-11-bullseye-v20241210"
              ~ storage_locations  = [
                  - "us",
                ] -> (known after apply)
                # (7 unchanged attributes hidden)
        
              ~ guest_os_features (known after apply)
              - guest_os_features {
                  - type = "GVNIC" -> null
                }
              - guest_os_features {
                  - type = "UEFI_COMPATIBLE" -> null
                }
              - guest_os_features {
                  - type = "VIRTIO_SCSI_MULTIQUEUE" -> null
                }
        
              ~ shielded_instance_initial_state {
                  ~ dbxs {
                      ~ content   = "2gcDBhMRFQAAAAAAAAAAAPYMAAAAAvEOndKvSt9o7kmKqTR9N1ZlpzCCDNoCAQExDzANBglghkgBZQMEAgEFADALBgkqhkiG9w0BBwGgggrtMIIE_TCCA-WgAwIBAgITMwAAACWW0gxcUxIAQwAAAAAAJTANBgkqhkiG9w0BAQsFADCBgDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEqMCgGA1UEAxMhTWljcm9zb2Z0IENvcnBvcmF0aW9uIEtFSyBDQSAyMDExMB4XDTIxMDkwMjE4MjQzMVoXDTIyMDkwMTE4MjQzMVowgYYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMDAuBgNVBAMTJ01pY3Jvc29mdCBXaW5kb3dzIFVFRkkgS2V5IEV4Y2hhbmdlIEtleTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMq-iu-bD4aSVG22jmbhWF8U6-vm7tInyPoyNnSyLiTvuvoWnnpfpMLm8lIHarJFpPjPNY0NnGGMr66K0YB81QwZI6dBo1JaTjLnjSG4OwY1FwM0neVjXneyrD5QL7cjHFnj88l3E57rZeRDJPbPBHAf1ZYpldD1cwEnae6iCUKnvsH35n1LLm7YqVipjkBDqm9iC2dr7OurRH9uy_F0_aNDuhDL_B4FwtZS06E5Ym9KGOf4vz-kEvY_wTrzMgQASdKybqJwxc-RT1ZmHeDVTOO8M5ngHgFhkKA9yIJqh7Ay4BUm2t12fvB8C6cpU9AhEV-HJkvyHGy42-bH8GcIfLcCAwEAAaOCAWYwggFiMBQGA1UdJQQNMAsGCSsGAQQBgjdPATAdBgNVHQ4EFgQUdT2cqzJltzyvzCL5sWuh443PjWEwRQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEWMBQGA1UEBRMNMjI5OTYxKzQ2NzU5MzAfBgNVHSMEGDAWgBRi_EPNoD6ky2cS0lvZVax7zLaKXzBTBgNVHR8ETDBKMEigRqBEhkJodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb3JLRUtDQTIwMTFfMjAxMS0wNi0yNC5jcmwwYAYIKwYBBQUHAQEEVDBSMFAGCCsGAQUFBzAChkRodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY0NvcktFS0NBMjAxMV8yMDExLTA2LTI0LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQBpZiumZLMOf0fjMI6cvw9sElC9juzSJ8iiI8XO0EGjW--diqQaMc7udXFjoV1P3JIVGNqhcIc5IuhTJKbSp8KnS0g6SI9-8CYjJFaNY5FKnWaRXun2pMHA8HWSaJwWgzqHAGzg9lCxUxSw9PO7Cz1iPbd6TVJujcHZNY8qOmp2ZhpBZ39NAKKXnoST4nEG47VBTRHckdDA2-g-o7GIlZtIiJNQKTZpyL-TFbNNKq4PZLeONgUcNBzefXfsBqpHxqo18L9vNkVfvBfEMbYEi8IAPIi0jwSzUtoPvvkAovICYthnpU1N2EFgXh1LACTUb2x5zU_Vs8AiEHrJIe1x4IpZMIIF6DCCA9CgAwIBAgIKYQrRiAAAAAAAAzANBgkqhkiG9w0BAQsFADCBkTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjE7MDkGA1UEAxMyTWljcm9zb2Z0IENvcnBvcmF0aW9uIFRoaXJkIFBhcnR5IE1hcmtldHBsYWNlIFJvb3QwHhcNMTEwNjI0MjA0MTI5WhcNMjYwNjI0MjA1MTI5WjCBgDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEqMCgGA1UEAxMhTWljcm9zb2Z0IENvcnBvcmF0aW9uIEtFSyBDQSAyMDExMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxOi1ir-tVyawJsPq5_tXekQCXQcN2krldCrmsA_sbevsf7njWmMyfBEXTw7jC6c4FZOOxvXghLGamyzn9beR1gnh4sAEqKwwHN9I8wZQmmSnUX_IhU-PIIbO_i_hn_-CwO3pzc70U2piOgtDueIl_f4F-dTEFKsR4iOJjXC3pB1N7K7lnPoWwtfBy9ToxC_lme4kiwPsjfKL6sNK-0MREgt-tUeSbNzmBInr9TME6xABKnHl-YMTPP8lCS9odkb_uk--3K1xKliq-w7SeT3km2U7zCkqn_xyWaLrrpLv9jUTgMYC7ORfzJ12ze9jksGveUCEeYd_41Ko6J17B2mPFQIDAQABo4IBTzCCAUswEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFGL8Q82gPqTLZxLSW9lVrHvMtopfMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH_MB8GA1UdIwQYMBaAFEVmUkPhflgRv9ZOniNVCDs6ImqoMFwGA1UdHwRVMFMwUaBPoE2GS2h0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3RzL01pY0NvclRoaVBhck1hclJvb18yMDEwLTEwLTA1LmNybDBgBggrBgEFBQcBAQRUMFIwUAYIKwYBBQUHMAKGRGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljQ29yVGhpUGFyTWFyUm9vXzIwMTAtMTAtMDUuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQDUhIj1FJQYAsoqPPsqkhwM16DR8ehSZqjuorV1epAAqi2kdlrqebe5N2pRexBk9uFk8gJnvveoG3i9us6IWGQM1lfIGaNfBdbbxtBpzkhLMrfrXdIw9cD1uLp4B6Mr_pvbNFaE7ILKrkElcJxr6f6QD9eWH-XnlB-yKgyNS_8oKRB799d8pdF2uQXIee0PkJKcwv7fb35sD3vUwUXdNFGWOQ_lXlbYGAWW9AemQrOgd_0IGfJxVsyfhiOkh8um_Vh-1GlnFZF-gfJ_E-UNi4o8h4Tr4869Q-WtLYSTjmorWnxE-lKqgcgtHLvgUt8AEfiaPcFgsOEztaOI0WUZChrnrHykwYKHTjixLw3FFIdv_Y0uvDm25-bD4OTNJ4TvlELvKYuQRkE7gRtn2PlDWWXLDbz9AJJP9HU7p6kk_FBBQHngLU8Kaid2blLtlml7rw_3hwXQRcKtUxSBH_swBKo3NmHaSmkbNNho7dYCz2yUDNPPbCJ5rbHwvAOiRmCpxAfCIYLx_fLoeTJgv9ispSIUS8rB2EvrfT9XNbLmT3W0sGADIlOukXkd1ptBHxWGVHCy3g01D3ywNHK6l2A78HnrorIcXaIWuIfF6Rv2tZclbzif45H6inmYw2kOt6McIAWX-MoUrgDXxPPAFBB1azSgG7WZYPNcsMVXTjbSMoS_njGCAcQwggHAAgEBMIGYMIGAMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSowKAYDVQQDEyFNaWNyb3NvZnQgQ29ycG9yYXRpb24gS0VLIENBIDIwMTECEzMAAAAlltIMXFMSAEMAAAAAACUwDQYJYIZIAWUDBAIBBQAwDQYJKoZIhvcNAQEBBQAEggEAAvz20_scPnryv_OgKLDS3azlGenTv56szAuJ5punguQqa3tyPLyn-TEwt5BT21H1yeMLBgfLYUQXCh4gU7oe3RVTxEz2lMCU5ZTpBNNB0Vd4ms678ye1KpAnETGVQDYlpHE33I13lBTTz0NNAHfWHeOTqWDxUlu7jJC225_6F2O__FDp-JozyKWPw69qYXTRjuQrYLMu0O3wFBJODLZZQ7VztyucNrg3tobxAmh0QoxrYctv7DBf1R3eU7MurXV12Km43kB51kdrFtt9GwKa1Z92oe17Uy0F5Qhw64c82GyEOxmp4q5BKtDxx2iAJiYJjcjhUTUp5sfgYoAeHufaoCYWxMFMUJJArKlB-TaTQyjMKAAAAAAAADAAAAC9mvp3WQMyTb1gKPTnj3hLgLTZaTG_DQL9kaYeGdFPHaRS5m2yQIyoYE1BH5Jlnwq9mvp3WQMyTb1gKPTnj3hL9S-Do_qc-9aSD3IoJNvkA0U00luFByRrO5V9rG4bznq9mvp3WQMyTb1gKPTnj3hLxdnYoYbiyC0Jr6oqb38uc4cNPmT3LE4I72d5aoQPD729mvp3WQMyTb1gKPTnj3hLGuyEuEtsZaUSIKm-cYGWUjAhDWLW0zxImZxrKVorCga9mvp3WQMyTb1gKPTnj3hLw6maRg2kZKBXw1htg8719K4ItxA5ee2JMnQt8O1TDGa9mvp3WQMyTb1gKPTnj3hLWPuUGu-VollDs_tfJRCg3z_kTFjJXgq4BIcpdWirl3G9mvp3WQMyTb1gKPTnj3hLU5HDovsRIQKmqh7cJa534Z9dbwnNCe6yUJkiv81Zkuq9mvp3WQMyTb1gKPTnj3hL1iYVfh1qcYvBJKuNony7ZQcsoDp7ayV9vcu9YPZe89G9mvp3WQMyTb1gKPTnj3hL0GPsKPZ-ulPxZC2_ff8zxqMq3YafYBP-Fi4sMvHL5W29mvp3WQMyTb1gKPTnj3hLKcbrUrQ8OqGLLNjtbqhgfO88-uG6_hFldVzy5hSESkS9mvp3WQMyTb1gKPTnj3hLkPvnDmnWM0CNPhcMaDLbstIJ4CclJ9-2PUnSlXKm9Ey9mvp3WQMyTb1gKPTnj3hLEG-s6s_s_U4wO3T0gKCAmOLQgCuTb47HdM4h8xaGaJy9mvp3WQMyTb1gKPTnj3hLF046C1tDxqYHu9NATwU0Hj3POWJnzpT4tQ4uI6nakgy9mvp3WQMyTb1gKPTnj3hLK5nPJkIukv42X79Lww0nCGye4Ut6b_9E-y9rkAFpmTm9mvp3WQMyTb1gKPTnj3hLLnCRZ4am93NRH6cYH6sPHXC1V8YyLqkjsqjTuStRr329mvp3WQMyTb1gKPTnj3hLP86bn98-8J1UUrD5XuSBwrfwbXQ6c3lxVY5wE2rOPnO9mvp3WQMyTb1 [...]

2025-01-24 19:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 4 files changed, 574 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 4 files changed, 574 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))

2025-01-24 20:24 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccComputeImage_shieldedInstanceInitialState` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/build-log/recording_build/TestAccComputeImage_shieldedInstanceInitialState_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/recording/TestAccComputeImage_shieldedInstanceInitialState.log)]
`TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/build-log/recording_build/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/recording/TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/90cfdaca-6f3d-4a8d-b761-00c01426095b/recording) for each test

2025-02-19 16:55 UTC, melinath commented
@modular-magician reassign-reviewer

2025-02-19 19:28 UTC, SirGitsalot requested changes
The problem is that the provider is sending a base64 string using standard encoding and getting back a base64 string in URL safe encoding. That's valid (the [proto JSON encoding standard](https://protobuf.dev/programming-guides/json/) says "JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted.") I'm actually surprised we haven't run into this before.

The fix is to assign a [diff_suppress_func](https://googlecloudplatform.github.io/magic-modules/reference/field/#diff_suppress_func) to `content` that does a standard encoding/URL encoding agnostic compare a la:

```
// Base64DiffSuppress compares two Base64 strings, ignoring differences
// between standard encoding and web safe URL encoding, padding, and 
// embedded line endings.
func Base64DiffSuppress(_, old, new string, _ *schema.ResourceData) bool {
	r := strings.NewReplacer("\r", "", "\n", "", "+", "-", "/", "_", "=", "")
	normalizedOld = r.Replace(old)
	normalizedNew = r.Replace(new)
	return normalizedOld == normalizedNew
}
```

I wrote this in the GitHub comment editor so it may be a little off. It should go in `mmv1/third_party/terraform/tpgresource/common_diff_suppress.go.tmpl` (along with an accompanying unit test in `mmv1/third_party/terraform/tpgresource/common_diff_suppress_test.go` please!)

2025-02-20 08:54 UTC, NotTheEvilOne commented
Interesting. I'll have a look at this implementation detail.

2025-02-24 18:10 UTC, yeoldegrove commented
@SirGitsalot I stepped in for @NotTheEvilOne and added `Base64DiffSuppress` and an additional test.

2025-02-24 23:41 UTC, SirGitsalot commented
/gcbrun

2025-02-25 00:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 772 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 772 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_image` (585 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_image" "primary" {
  raw_disk {
    sha1 = # value needed
  }
}


```

2025-02-25 02:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 4614
Passed tests: 4176
Skipped tests: 432
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccCloudbuildWorkerPool_basic</li>
<li>TestAccComputeImage_shieldedInstance_InitialState</li>
<li>TestAccComputeImage_shieldedInstance_UpdatedState</li>
<li>TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-25 21:03 UTC, SirGitsalot requested changes
The good news is that the diff suppress did fix the problem, the bad news is that there's a broken test elsewhere (but in more good news it's an easy fix - see the other comment)

2025-02-25 21:03 UTC, SirGitsalot commented on mmv1/products/compute/Image.yaml
> +  - name: 'shieldedInstanceInitialState'
It looks like `shieldedInstanceInitialState` needs `default_from_api: true` (documented [here](https://googlecloudplatform.github.io/magic-modules/reference/field/#default_from_api)).

[`TestAccComputeInstanceFromTemplate_confidentialInstanceConfigMain`](https://github.com/hashicorp/terraform-provider-google-beta/blob/f3e48ac118bcf39c752fbf7177228af83ee93b1c/google-beta/services/compute/resource_compute_instance_from_template_test.go#L1507) creates a new `google_compute_image` from an existing Ubuntu image, and that Ubuntu image has `shieldedInstanceInitialState` set, causing a plan mismatch (that is, if you create a new image from an existing image that has `shieldedInstanceInitialState` but don't specify your own `shieldedInstanceInitialState`, the API is returning the `shieldedInstanceInitialState` from the source image; Terraform is expecting there to be no `shieldedInstanceInitialState` on output since none was specified on input).

2025-02-27 13:48 UTC, yeoldegrove commented on mmv1/products/compute/Image.yaml
> +  - name: 'shieldedInstanceInitialState'
@SirGitsalot added `default_from_api: true`

2025-02-27 19:48 UTC, SirGitsalot commented
/gcbrun

2025-02-27 19:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 773 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 773 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_image` (585 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_image" "primary" {
  raw_disk {
    sha1 = # value needed
  }
}


```

2025-02-27 21:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 4645
Passed tests: 4202
Skipped tests: 436
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessContextManager</li>
<li>TestAccCloudbuildWorkerPool_basic</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample</li>
<li>TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample</li>
<li>TestAccSqlUser_password_wo</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-27 22:17 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccAccessContextManager` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccAccessContextManager.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccCloudbuildWorkerPool_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_build/TestAccCloudbuildWorkerPool_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccCloudbuildWorkerPool_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_build/TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample.log)]
`TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_build/TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample.log)]
`TestAccSqlUser_password_wo` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_build/TestAccSqlUser_password_wo_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording/TestAccSqlUser_password_wo.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/abc4cdca-43c5-403b-91c3-fae77a074f78/recording) for each test

2025-03-04 12:30 UTC, NotTheEvilOne commented
Thanks for jumping in @yeoldegrove. Could you share some insight what went wrong with the last test run @SirGitsalot?

2025-03-05 00:19 UTC, SirGitsalot commented
/gcbrun

2025-03-05 00:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 773 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12369-old..auto-pr-12369) ( 6 files changed, 773 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12369-old..auto-pr-12369) ( 1 file changed, 191 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_image` (585 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_image" "primary" {
  raw_disk {
    sha1 = # value needed
  }
}


```

2025-03-05 02:47 UTC, modular-magician commented
#### Tests analytics
Total tests: 4653
Passed tests: 4210
Skipped tests: 436
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessContextManager</li>
<li>TestAccCloudbuildWorkerPool_basic</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample</li>
<li>TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample</li>
<li>TestAccSqlUser_password_wo</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-03-05 03:05 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccAccessContextManager` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccAccessContextManager.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccAccessContextManager` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/replaying_build_after_recording/TestAccAccessContextManager_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/replaying_after_recording/TestAccAccessContextManager.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccCloudbuildWorkerPool_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_build/TestAccCloudbuildWorkerPool_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccCloudbuildWorkerPool_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_build/TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccSecretManagerSecretVersion_secretVersionBasicWriteOnlyExample.log)]
`TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_build/TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccSecretManagerSecretVersion_secretVersionWithBase64StringSecretDataWriteOnlyExample.log)]
`TestAccSqlUser_password_wo` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_build/TestAccSqlUser_password_wo_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording/TestAccSqlUser_password_wo.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12369/artifacts/8e842dff-412e-460a-b311-c54063114afc/recording) for each test

2025-03-13 00:16 UTC, SirGitsalot requested changes
The test failures are unrelated; just one last quick question

2025-03-13 00:16 UTC, SirGitsalot commented on mmv1/products/compute/Image.yaml
> +        diff_suppress_func: 'tpgresource.Base64DiffSuppress'
Is this newly necessary?

2025-03-17 06:57 UTC, NotTheEvilOne commented on mmv1/products/compute/Image.yaml
> +        diff_suppress_func: 'tpgresource.Base64DiffSuppress'
Hi @SirGitsalot,

We had an interesting side-effect with [base64-encoded strings [1]](https://github.com/GoogleCloudPlatform/magic-modules/pull/12369#pullrequestreview-2540385326). For that reason my colleague @yeoldegrove added [this function [2]](https://github.com/GoogleCloudPlatform/magic-modules/pull/12369/commits/7e02c79f194d0eb253c1edac21460b7e63e78ade).

[1] https://github.com/GoogleCloudPlatform/magic-modules/pull/12369#pullrequestreview-2540385326
[2] https://github.com/GoogleCloudPlatform/magic-modules/pull/12369/commits/7e02c79f194d0eb253c1edac21460b7e63e78ade

2025-03-19 18:35 UTC, SirGitsalot approved these changes

2025-03-19 18:51 UTC, merged