Add threshold_configs in Cloud Armor Adaptive Protection security policy
GoogleCloudPlatform/magic-modules pull request #12367
Opened 2024-11-20 02:48 UTC by translucens

Fixes https://github.com/hashicorp/terraform-provider-google/issues/18788

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note: enhancement
compute: added `threshold_configs` field to `google_compute_security_policy` resource
```

2024-11-22 15:17 UTC, maxi-cit commented
Hello @NickElliot, could you check this PR, please? So far it looks like it is right.

2024-11-25 22:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12367-old..auto-pr-12367) ( 3 files changed, 268 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12367-old..auto-pr-12367) ( 3 files changed, 268 insertions(+), 5 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_security_policy` (98 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_security_policy" "primary" {
  adaptive_protection_config {
    layer_7_ddos_defense_config {
      threshold_configs {
        traffic_granularity_configs {
          value = # value needed
        }
      }
    }
  }
}


```

2024-11-25 23:02 UTC, modular-magician commented
#### Tests analytics
Total tests: 1065
Passed tests: 991
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeSecurityPolicy_withAdaptiveProtection_withThresholdConfigs</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-25 23:03 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeSecurityPolicy_withAdaptiveProtection_withThresholdConfigs` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12367/artifacts/c3068e08-fa39-456f-89fb-31776c029dfd/recording/TestAccComputeSecurityPolicy_withAdaptiveProtection_withThresholdConfigs.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12367/artifacts/c3068e08-fa39-456f-89fb-31776c029dfd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12367/artifacts/c3068e08-fa39-456f-89fb-31776c029dfd/recording) for each test

2024-11-25 23:54 UTC, NickElliot requested changes
minor edit to the documentation but mostly LGTM! going to verify some of the testing locally to follow up the CI

2024-11-25 23:54 UTC, NickElliot commented on mmv1/third_party/terraform/website/docs/r/compute_security_policy.html.markdown
> +* `type` - a granular traffic unit can be one of the following:
```suggestion
* `type` - The type of this configuration, a granular traffic unit can be one of the following:
```

2024-12-02 22:30 UTC, NickElliot approved these changes
LGTM

2024-12-02 22:30 UTC, merged