Remove the tagHoldAdmin for TestAccContainerCluster_resourceManagerTags since we already have bootstrap it
GoogleCloudPlatform/magic-modules pull request #12376
Opened 2024-11-21 00:28 UTC by MaChenhao

Removed the tagHoldAdmin for TestAccContainerCluster_resourceManagerTags since we already have bootstrap it. Also added the tagAdmin IAM permission in order to update the tag.

Fix for https://github.com/hashicorp/terraform-provider-google/issues/20252.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
container: Removed the tagHoldAdmin for TestAccContainerCluster_resourceManagerTags since we already have bootstrap it. Also added the tagAdmin IAM permission in order to update the tag.
```

2024-11-21 14:03 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12376/artifacts/bde239e6-ae96-4ab8-8b4b-f88a1d39976b/build-log/replaying_test.log)

2024-11-21 15:46 UTC, c2thorn requested changes
```
# github.com/hashicorp/terraform-provider-google-beta/google-beta/services/container
google-beta/services/container/resource_container_cluster_test.go:75:3: expected operand, found '||'
```

2024-11-21 21:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12376-old..auto-pr-12376) ( 1 file changed, 2 insertions(+), 7 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12376-old..auto-pr-12376) ( 1 file changed, 2 insertions(+), 7 deletions(-))

2024-11-21 22:24 UTC, modular-magician commented
#### Tests analytics
Total tests: 216
Passed tests: 203
Skipped tests: 12
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>container</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccContainerCluster_resourceManagerTags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-11-21 22:24 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccContainerCluster_resourceManagerTags` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12376/artifacts/13e11c9b-82c4-4b69-9efc-2e812c7a673a/build-log/recording_build/TestAccContainerCluster_resourceManagerTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12376/artifacts/13e11c9b-82c4-4b69-9efc-2e812c7a673a/recording/TestAccContainerCluster_resourceManagerTags.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12376/artifacts/13e11c9b-82c4-4b69-9efc-2e812c7a673a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12376/artifacts/13e11c9b-82c4-4b69-9efc-2e812c7a673a/recording) for each test

2025-01-10 08:51 UTC, wyardley commented
```
    resource_container_cluster_test.go:79: Step 1/4 error: Error running pre-apply refresh: exit status 1
        
        Error: Reference to undeclared resource
        
          on terraform_plugin_test.tf line 12, in resource "google_project_iam_member" "tagUser1":
          12:   depends_on = [google_project_iam_member.tagHoldAdmin]
        
        A managed resource "google_project_iam_member" "tagHoldAdmin" has not been
        declared in the root module.
        
        Error: Reference to undeclared resource
        
          on terraform_plugin_test.tf line 20, in resource "google_project_iam_member" "tagUser2":
          20:   depends_on = [google_project_iam_member.tagHoldAdmin]
        
        A managed resource "google_project_iam_member" "tagHoldAdmin" has not been
        declared in the root module.
--- FAIL: TestAccContainerCluster_resourceManagerTags (4.16s)
```

I think there are still some deps on the removed resource. I can try and open a new PR if you don't want to fix it, especially since my PR may have introduced the issue @MaChenhao

Looks like`TestAccContainerCluster_withAutopilotResourceManagerTags` may also need to be updated.

2025-01-21 18:18 UTC, closed without merging