Make allowedPersistenceRegions optional in messageStoragePolicy for google_pubsub_topic.
GoogleCloudPlatform/magic-modules pull request #12403
Opened 2024-11-22 17:42 UTC by shunsuke-tsumori

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:REPLACEME

```

2024-11-25 19:07 UTC, c2thorn requested changes

2024-11-25 19:07 UTC, c2thorn commented on mmv1/products/pubsub/Topic.yaml
> -        required: true
I'm not seeing how this solves https://github.com/hashicorp/terraform-provider-google/issues/20431

The original debug log shows no required validation message for this field

2024-11-25 19:07 UTC, c2thorn commented on mmv1/third_party/terraform/services/pubsub/resource_pubsub_topic_test.go
> +  name = "topic-name"
this isn't actually testing the change on `allowedPersistenceRegions`, this is testing removing `message_storage_policy`

2024-12-01 14:55 UTC, shunsuke-tsumori commented
@c2thorn Thanks for taking the time to review. I apologize for misunderstanding the issue and not understanding the test. I will close the pull request as I have found that it does not resolve the issue.

2024-12-01 14:55 UTC, closed without merging