Add tags field to Filestore Instances for TagsR2401
GoogleCloudPlatform/magic-modules pull request #12441
Opened 2024-11-27 06:24 UTC by aniket-gupta

dd tags field to instance resource to allow setting tags on instance resources at creation time.
Part of b/364841739
release-note:none
```
filestore: added `tags` field to `filstore_instance` to allow setting tags for instances at creation time
```

```
The contents of this code are entirely owned by Google LLC in accordance with the agreement between Google LLC and the third party submitting this code into Google's open source repository
```

2024-11-27 06:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2024-11-27 06:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccFilestoreInstance_tags
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/d31248e6-f5a1-46b8-b9ee-4b7ecedb690d/build-log/replaying_test.log)

2024-11-27 10:10 UTC, SamanthaMathews commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))
> 
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_filestore_instance` (21 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```hcl
> resource "google_filestore_instance" "primary" {
>   tags = # value needed
> }
> ```

The acceptance test is added in the file mmv1/third_party/terraform/services/filestore/resource_filestore_instance_test.go
```
resource "google_filestore_instance" "instance" {
  name = "tf-instance-%s"
  zone = "us-central1-b"
  tier = "BASIC_HDD"
  file_shares {
    capacity_gb = 1024
    name        = "share1"
  }
  networks {
    network           = "default"
    modes             = ["MODE_IPV4"]
    reserved_ip_range = "172.19.31.8/29"
  }
tags = {`, name)

	l := ""
	for key, value := range tags {
		l += fmt.Sprintf("%q = %q\n", key, value)
	}

	l += fmt.Sprintf("}\n}")
	return r + l
}
```

2024-12-03 08:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2024-12-03 08:45 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccFilestoreInstance_tags
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/c5b7b3df-5aba-435c-ae95-c96913813ebf/build-log/replaying_test.log)

2024-12-03 08:59 UTC, abd-goog requested changes

2024-12-03 08:59 UTC, abd-goog commented on mmv1/products/filestore/Instance.yaml
> +      A map of resource manager tags_.
nit:typo, remove underscore

2024-12-19 12:15 UTC, aniket-gupta commented on mmv1/products/filestore/Instance.yaml
> +      A map of resource manager tags_.
sone

2024-12-19 12:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2024-12-19 12:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 88 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2024-12-19 12:25 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccFilestoreInstance_tags
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/5549a4f1-b85a-41fe-a6ff-75d315db758b/build-log/replaying_test.log)

2024-12-19 12:26 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccFilestoreInstance_tags
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/ed88520c-f12e-4d4a-b7ee-3782693cbe56/build-log/replaying_test.log)

2024-12-19 17:21 UTC, ScottSuarez requested changes
Hi @aniket-gupta, the code is failing to compile 

https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/12412529251/job/34652756250?pr=12441

2024-12-19 17:21 UTC, ScottSuarez commented on mmv1/third_party/terraform/services/filestore/resource_filestore_instance_test.go
> +	org := envvar.GetTestOrgFromEnv(t)
this package is not imported

2024-12-19 19:10 UTC, SamanthaMathews commented on mmv1/third_party/terraform/services/filestore/resource_filestore_instance_test.go
@aniket-gupta , could you please add the following import statement on line 11.
```
"github.com/hashicorp/terraform-provider-google/google/envvar"
```
This should resolve the existing issue

2024-12-20 04:23 UTC, aniket-gupta commented on mmv1/third_party/terraform/services/filestore/resource_filestore_instance_test.go
added

2024-12-20 04:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2024-12-20 04:35 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 14
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFilestoreInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-20 04:35 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccFilestoreInstance_tags` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/4cd629ce-92bd-4114-aed7-3a5301cf1e2e/build-log/recording_build/TestAccFilestoreInstance_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/4cd629ce-92bd-4114-aed7-3a5301cf1e2e/recording/TestAccFilestoreInstance_tags.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/4cd629ce-92bd-4114-aed7-3a5301cf1e2e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/4cd629ce-92bd-4114-aed7-3a5301cf1e2e/recording) for each test

2025-01-06 10:52 UTC, aniket-gupta commented
/gcbrun

2025-01-06 13:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2025-01-06 13:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 14
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFilestoreInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-06 13:10 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccFilestoreInstance_tags` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/3c665410-ebd6-448e-801d-1c74ab8eb750/build-log/recording_build/TestAccFilestoreInstance_tags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/3c665410-ebd6-448e-801d-1c74ab8eb750/recording/TestAccFilestoreInstance_tags.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/3c665410-ebd6-448e-801d-1c74ab8eb750/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/3c665410-ebd6-448e-801d-1c74ab8eb750/recording) for each test

2025-01-06 15:37 UTC, aniket-gupta commented
/gcbrun

2025-01-06 17:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2025-01-06 17:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 14
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFilestoreInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-06 17:14 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccFilestoreInstance_tags` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/c1d37d5d-f0e1-470f-92f5-95c98046e08f/recording/TestAccFilestoreInstance_tags.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/c1d37d5d-f0e1-470f-92f5-95c98046e08f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/c1d37d5d-f0e1-470f-92f5-95c98046e08f/recording) for each test

2025-01-06 18:52 UTC, zli82016 commented
Can you also add a note `It may take a while for the attached tag bindings to be deleted after the project is scheduled to be deleted.`  to the `[docs](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/filestore/Instance.yaml#L24)` of the resource ?

The note is added to the google_project resource [doc](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/google_project.html.markdown?plain=1#L23).

2025-01-06 18:53 UTC, zli82016 commented
The PR can't be merged unless the CLA issue is resolved.

2025-01-06 18:54 UTC, zli82016 requested changes

2025-01-08 05:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 90 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2025-01-08 05:47 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 14
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccFilestoreInstance_tags</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-08 05:53 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccFilestoreInstance_tags` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/5d536378-24b6-402a-a618-1047be29f8e7/recording/TestAccFilestoreInstance_tags.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/5d536378-24b6-402a-a618-1047be29f8e7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/5d536378-24b6-402a-a618-1047be29f8e7/recording) for each test

2025-01-08 06:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 100 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 100 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2025-01-08 06:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 100 insertions(+), 5 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12441-old..auto-pr-12441) ( 4 files changed, 100 insertions(+), 5 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12441-old..auto-pr-12441) ( 1 file changed, 17 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_filestore_instance` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_filestore_instance" "primary" {
  tags = # value needed
}


```

2025-01-08 06:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 15
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/c13fac94-863b-4eb0-b8e8-725a21353ac6/build-log/replaying_test.log)

2025-01-08 06:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 15
Passed tests: 15
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>filestore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12441/artifacts/7a926ed5-2abe-4c8e-89cb-b53a6fa50811/build-log/replaying_test.log)

2026-07-15 21:42 UTC, ScottSuarez commented
Is this PR Still valid or may I close it?

2026-07-17 18:30 UTC, closed without merging