Fixed recaptcha_options permadiff causing rules being recreated
GoogleCloudPlatform/magic-modules pull request #12458
Opened 2024-11-29 22:28 UTC by matheusaleixo-cit

Fixes a permadiff related to the `recaptcha_options` field in google_compute_security_policy.
Also code cleanup for the same fix previously applied to `preconfigured_waf_config` field;

Part of: https://github.com/hashicorp/terraform-provider-google/issues/16882, https://github.com/hashicorp/terraform-provider-google/issues/18596

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:bug
compute: fixed permadiff on the `recaptcha_options` field for `google_compute_security_policy` resource
```

2024-12-03 22:06 UTC, matheusaleixo-cit commented
I don't think this issue can be reproduced in a vcr test, (it's unclear what causes the API to return the empty values, plus we can't intentionally input these values in terraform since the resource is configured to not allow empty values for the recaptcha_options fields, and on rule update the resource uses the patchRule endpoint).

This issue can be tested manually:

- Create a `main.tf` file configuring the security policy resource and some rules and apply the changes;
- Manually update a rule setting the `recaptcha_options.action_token_site_keys` and `recaptcha_options.session_token_site_keys` fields with empty values using the [patch](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/patch) endpoint ([patchRule](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/patchRule) endpoint seems to ignore these fields when setting empty values).
- From here the permadiff can be observed by reapplying the terraform config;
- Configuring a [developer override](https://googlecloudplatform.github.io/magic-modules/develop/test/run-tests/#optional-test-manually) with the changes and running a apply again confirms that the permadiff is fixed;

2024-12-03 22:09 UTC, slevenick requested changes
Can you add a test that would have failed with the existing resource?

2024-12-03 22:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12458-old..auto-pr-12458) ( 1 file changed, 34 insertions(+), 20 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12458-old..auto-pr-12458) ( 1 file changed, 34 insertions(+), 20 deletions(-))

2024-12-03 22:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 1070
Passed tests: 997
Skipped tests: 73
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12458/artifacts/67fbef3a-1a8e-4124-b53f-6d93639d0cbd/build-log/replaying_test.log)

2024-12-05 18:43 UTC, matheusaleixo-cit commented
> Can you add a test that would have failed with the existing resource?

I could not find a way to reproduce the permadiff in a conventional test as there is no way to induce the API to return empty values via terraform config due to how the resource is configured.

I could maybe try to run a separate API request in a PreConfig function in a test step to patch these empty values but I don't know if this is a correct way of approaching this.



> I don't think this issue can be reproduced in a vcr test, (it's unclear what causes the API to return the empty values, plus we can't intentionally input these values in terraform since the resource is configured to not allow empty values for the recaptcha_options fields, and on rule update the resource uses the patchRule endpoint).
> 
> This issue can be tested manually:
> 
> * Create a `main.tf` file configuring the security policy resource and some rules and apply the changes;
> * Manually update a rule setting the `recaptcha_options.action_token_site_keys` and `recaptcha_options.session_token_site_keys` fields with empty values using the [patch](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/patch) endpoint ([patchRule](https://cloud.google.com/compute/docs/reference/rest/v1/securityPolicies/patchRule) endpoint seems to ignore these fields when setting empty values).
> * From here the permadiff can be observed by reapplying the terraform config;
> * Configuring a [developer override](https://googlecloudplatform.github.io/magic-modules/develop/test/run-tests/#optional-test-manually) with the changes and running a apply again confirms that the permadiff is fixed;

2024-12-06 19:46 UTC, slevenick approved these changes

2024-12-06 19:49 UTC, merged