Supporting gke hub feature data source
GoogleCloudPlatform/magic-modules pull request #12459
Opened 2024-11-29 22:31 UTC by YpNo

Fixes : https://github.com/hashicorp/terraform-provider-google/issues/20521

Supporting Data source for `google_gke_hub_feature` to know if a feature is enabled or not

```release-note:new-datasource
`google_gke_hub_feature `
```

2024-12-02 18:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 111 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 111 insertions(+))



## Errors

`google` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The diff processor crashed while computing changed resource schemas.

`google-beta` provider:
- The diff processor crashed while computing breaking changes. This is usually due to the downstream provider failing to compile.
- The missing test detector failed to run.
- The diff processor crashed while computing changed resource schemas.

2024-12-02 18:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gkehub2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleGKEHub2Feature_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/d887c7e5-9d3b-42d5-ad96-0a1a45623a05/build-log/replaying_test.log)

2024-12-03 18:05 UTC, hao-nan-li requested changes
Looks like there's some build error, could you try to build locally and see what's wrong?

2024-12-04 20:23 UTC, YpNo commented
I gonna check as soon as possible.
Thanks for your reply

2024-12-09 21:41 UTC, YpNo commented
Hi,
it should build. I've just got some trouble with the tests.
Like this error :
```
# github.com/hashicorp/terraform-provider-google/google/services/gkehub2_test [github.com/hashicorp/terraform-provider-google/google/services/gkehub2.test]
google/services/gkehub2/data_source_google_gke_hub_feature_test.go:22:17: undefined: testAccCheckGoogleGkeHubFeatureDestroyProducer
```
But I checked on the other ressource like `google_gke_hub_membership_binding` where `testAccCheckGKEHub2MembershipBindingDestroyProducer` is undefined as well. 
If you can explain to me.

2024-12-10 18:50 UTC, hao-nan-li commented
> Hi, it should build. I've just got some trouble with the tests. Like this error :
> 
> ```
> # github.com/hashicorp/terraform-provider-google/google/services/gkehub2_test [github.com/hashicorp/terraform-provider-google/google/services/gkehub2.test]
> google/services/gkehub2/data_source_google_gke_hub_feature_test.go:22:17: undefined: testAccCheckGoogleGkeHubFeatureDestroyProducer
> ```
> 
> But I checked on the other ressource like `google_gke_hub_membership_binding` where `testAccCheckGKEHub2MembershipBindingDestroyProducer` is undefined as well. If you can explain to me.

The quick solution is to find where that function is and copy/paste it in your test file. https://github.com/hashicorp/terraform-provider-google/blob/551d170ae23337092daefcb4c5a70a60121ad848/google/services/gkehub2/resource_gke_hub_membership_binding_generated_test.go#L108

2024-12-10 18:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 101 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 101 insertions(+))

2024-12-10 19:00 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gkehub2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleGkeHubFeature_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/0370bebc-abe3-407d-abc2-7406cb6e26e9/build-log/replaying_test.log)

2024-12-13 09:37 UTC, YpNo commented
> > Hi, it should build. I've just got some trouble with the tests. Like this error :
> > ```
> > # github.com/hashicorp/terraform-provider-google/google/services/gkehub2_test [github.com/hashicorp/terraform-provider-google/google/services/gkehub2.test]
> > google/services/gkehub2/data_source_google_gke_hub_feature_test.go:22:17: undefined: testAccCheckGoogleGkeHubFeatureDestroyProducer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I checked on the other ressource like `google_gke_hub_membership_binding` where `testAccCheckGKEHub2MembershipBindingDestroyProducer` is undefined as well. If you can explain to me.
> 
> The quick solution is to find where that function is and copy/paste it in your test file. https://github.com/hashicorp/terraform-provider-google/blob/551d170ae23337092daefcb4c5a70a60121ad848/google/services/gkehub2/resource_gke_hub_membership_binding_generated_test.go#L108

Thanks but it seems that there is not generated_test file for the google_gke_hub_feature resource after the "make provider". How the generated_test file is created ?

2024-12-13 17:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gkehub2</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccDataSourceGoogleGkeHubFeature_basic
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/363ef3c3-80b8-41e3-b0be-d0ef31491f74/build-log/replaying_test.log)

2024-12-14 13:44 UTC, YpNo commented
> * TestAccDataSourceGoogleGkeHubFeature_basic

Could I have access to the build log ?

2024-12-16 17:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))

2024-12-16 17:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 25
Passed tests: 13
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gkehub2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-16 17:56 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/96b5d329-99a4-4b41-b4c7-3dfa9516a62b/build-log/recording_build/TestAccDataSourceGoogleGkeHubFeature_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/96b5d329-99a4-4b41-b4c7-3dfa9516a62b/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/96b5d329-99a4-4b41-b4c7-3dfa9516a62b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/96b5d329-99a4-4b41-b4c7-3dfa9516a62b/recording) for each test

2024-12-16 20:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))

2024-12-16 20:56 UTC, modular-magician commented
#### Tests analytics
Total tests: 25
Passed tests: 13
Skipped tests: 11
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gkehub2</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-16 20:56 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/9ed7cee6-5777-4d7a-aafa-a18a6e04f620/build-log/recording_build/TestAccDataSourceGoogleGkeHubFeature_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/9ed7cee6-5777-4d7a-aafa-a18a6e04f620/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/9ed7cee6-5777-4d7a-aafa-a18a6e04f620/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/9ed7cee6-5777-4d7a-aafa-a18a6e04f620/recording) for each test

2024-12-17 18:30 UTC, hao-nan-li commented
/gcbrun

2024-12-17 18:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12459-old..auto-pr-12459) ( 3 files changed, 143 insertions(+))

2024-12-17 18:52 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/8da85e18-0062-4207-96b1-a7bab4100e48/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/8da85e18-0062-4207-96b1-a7bab4100e48/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/8da85e18-0062-4207-96b1-a7bab4100e48/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/8da85e18-0062-4207-96b1-a7bab4100e48/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12459/artifacts/8da85e18-0062-4207-96b1-a7bab4100e48/recording) for each test

2024-12-17 18:55 UTC, hao-nan-li approved these changes

2024-12-17 18:55 UTC, merged