Make `google_compute_instance_guest_attributes` return empty results when queried for nonexistent values
GoogleCloudPlatform/magic-modules pull request #12487
Opened 2024-12-04 12:46 UTC by karolgorc

closes https://github.com/hashicorp/terraform-provider-google/issues/20346

- Removed error thrown on Instances.GetGuestAttributes calls
- Added additional Instances.Get call to see if the instance exists at all

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:enhancement
compute: `google_compute_instance_guest_attributes` will return empty arrays and lists when queried values don't exist instead of throwing an error
```

2024-12-09 14:59 UTC, roaks3 reviewed
Could you add a test to confirm the behavior?

I'm also a little unsure about the solution here. It looks like this data source does not represent a list, so I would generally expect it to follow https://github.com/hashicorp/terraform-provider-google/issues/12873 and return an error. For example, I think that would be the expected behavior when `variable_key` is used.

However, this datasource has a `query_path` parameter that makes it a bit weird, and I'm not clear on what behavior we would want. The error the users sees now is obviously not clear, but it seems like technically we would still want an error returned. Could you share more about the use case, and why the user would be purposefully querying for infrastructure that doesn't exist?

2024-12-13 20:47 UTC, roaks3 requested changes
Oh I see, I misunderstood the `query_value` field. This does actually look more like a plural datasource, and I don't think a 404 would make sense when the list is empty.

Same comment as before though, we should be able to add a test with an instance that does not have any guest attributes. This would confirm the error with the old behavior, and that it is fixed with this change.

2024-12-16 08:55 UTC, karolgorc commented
Added test cases for `empty` and `nonexistent` scenarios

2024-12-19 20:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 1077
Passed tests: 1003
Skipped tests: 73
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceComputeInstanceGuestAttributes_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-19 20:35 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceComputeInstanceGuestAttributes_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12487/artifacts/70ac9221-72b9-43c0-a8ec-ca47c4845142/recording/TestAccDataSourceComputeInstanceGuestAttributes_basic.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12487/artifacts/70ac9221-72b9-43c0-a8ec-ca47c4845142/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12487/artifacts/70ac9221-72b9-43c0-a8ec-ca47c4845142/recording) for each test

2024-12-19 20:42 UTC, roaks3 approved these changes

2024-12-19 20:42 UTC, merged