Add nullFields logic to `guest_flush` on `resource_google_compute_resource_policy`
GoogleCloudPlatform/magic-modules pull request #12510
Opened 2024-12-06 09:29 UTC by karolgorc

closes https://github.com/hashicorp/terraform-provider-google/issues/20499

This field cannot be patched and is set to false automatically when the parent block is added into the configuration causing an error on every change to this block.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:enhancement
compute: Updating labels on `resource_google_compute_resource_policy` will no longer fail because of a Patch error with `guest_flush`
```

2024-12-06 18:38 UTC, modular-magician commented
#### Tests analytics
Total tests: 1071
Passed tests: 998
Skipped tests: 73
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12510/artifacts/765bd519-f6ea-417d-8379-a3e5ad09164b/build-log/replaying_test.log)

2024-12-06 18:39 UTC, ScottSuarez requested changes

2024-12-06 18:39 UTC, ScottSuarez commented on mmv1/products/compute/ResourcePolicy.yaml
> -            send_empty_value: true
Can you add a testcase for this ?

2024-12-09 07:40 UTC, karolgorc commented on mmv1/products/compute/ResourcePolicy.yaml
> -            send_empty_value: true
on it

2024-12-09 17:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12510-old..auto-pr-12510) ( 2 files changed, 69 insertions(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12510-old..auto-pr-12510) ( 2 files changed, 69 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12510-old..auto-pr-12510) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2024-12-09 17:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 1072
Passed tests: 997
Skipped tests: 73
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>compute</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy</li>
<li>TestAccComputeResourcePolicy_guestFlushEmptyValue</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-09 17:46 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12510/artifacts/d348cb82-1eb4-4d05-9582-21ce52d4e273/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputeResourcePolicy_guestFlushEmptyValue` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12510/artifacts/d348cb82-1eb4-4d05-9582-21ce52d4e273/recording/TestAccComputeResourcePolicy_guestFlushEmptyValue.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12510/artifacts/d348cb82-1eb4-4d05-9582-21ce52d4e273/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12510/artifacts/d348cb82-1eb4-4d05-9582-21ce52d4e273/recording) for each test

2024-12-09 19:27 UTC, ScottSuarez approved these changes

2024-12-09 19:27 UTC, merged