Add external catalog table options to google_bigquery_table beta
GoogleCloudPlatform/magic-modules pull request #12528
Opened 2024-12-09 23:00 UTC by wj-chen

Add external catalog table options to google_bigquery_table beta.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:improvement
bigquery: added `external_catalog_table_options` fields to `google_bigquery_table` resource (beta)
```

2024-12-09 23:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 72 insertions(+), 10 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 431 insertions(+), 7 deletions(-))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_bigquery_table` (146 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_bigquery_table" "primary" {
  external_catalog_table_options {
    connection_id = # value needed
  }
}


```

2024-12-09 23:15 UTC, modular-magician commented
#### Tests analytics
Total tests: 127
Passed tests: 116
Skipped tests: 10
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigquery</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBigQueryTable_externalCatalogTableOptions</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-09 23:28 UTC, zli82016 commented
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_bigquery_table` (146 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```hcl
> resource "google_bigquery_table" "primary" {
>   external_catalog_table_options {
>     connection_id = # value needed
>   }
> }
> ```

Is it possible to add the missing test for `connection_id`?

2024-12-10 19:06 UTC, zli82016 requested changes
add the missing test for connection_id

2024-12-16 21:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 72 insertions(+), 10 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 447 insertions(+), 7 deletions(-))

2024-12-16 22:00 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccBigQueryTable_externalCatalogTableOptions` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/dddf438e-356e-4d76-8697-51b07a6dd68a/build-log/recording_build/TestAccBigQueryTable_externalCatalogTableOptions_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/dddf438e-356e-4d76-8697-51b07a6dd68a/recording/TestAccBigQueryTable_externalCatalogTableOptions.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/dddf438e-356e-4d76-8697-51b07a6dd68a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/dddf438e-356e-4d76-8697-51b07a6dd68a/recording) for each test

2024-12-16 22:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 72 insertions(+), 10 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12528-old..auto-pr-12528) ( 3 files changed, 451 insertions(+), 7 deletions(-))

2024-12-16 22:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 128
Passed tests: 117
Skipped tests: 10
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>bigquery</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccBigQueryTable_externalCatalogTableOptions</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-16 22:29 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccBigQueryTable_externalCatalogTableOptions` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/ac5ccd5f-8169-4161-a37b-3be0c03da6db/recording/TestAccBigQueryTable_externalCatalogTableOptions.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/ac5ccd5f-8169-4161-a37b-3be0c03da6db/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12528/artifacts/ac5ccd5f-8169-4161-a37b-3be0c03da6db/recording) for each test

2024-12-16 22:53 UTC, wj-chen commented
> add the missing test for connection_id

Added `connection_id` as a field to the same new test

2024-12-17 18:11 UTC, zli82016 approved these changes
LGTM

2024-12-17 18:13 UTC, zli82016 commented
@obada-ab, can you review this PR when you have time? Thanks.

2024-12-17 18:13 UTC, zli82016 commented
@wj-chen, is there a Github issue for this PR?

2024-12-17 19:23 UTC, obada-ab approved these changes
LGTM

2024-12-18 16:25 UTC, merged