TF Support for NCC Star Topology
GoogleCloudPlatform/magic-modules pull request #12540
Opened 2024-12-11 07:25 UTC by akshat-jindal-nit

**Added the star topology support to hub and spoke-group connection in NCC  resource (b/377958926)**

- In this feature, we introduce two new fields inside a hub  preset_topology. 
- When a hub is created, two groups, center and edge, will be automatically created when  preset_topology=star. If preset_topology=mesh, only one group, default, is created.

- Currently, users cannot make a spoke to group connection by themselves from TF added support for it. 

```release-note:enhancement
compute: added `preset_topology ` field to `networkconnectivity.Hub` resource
```

```release-note:enhancement
compute: added `group ResourceRef ` field to `networkconnectivity.Spoke` resource
```

2024-12-16 21:35 UTC, slevenick requested changes
Please fix conflicts. 

No real concerns here, but can you update the release notes to match our typical format: https://googlecloudplatform.github.io/magic-modules/code-review/release-notes/

2024-12-17 13:18 UTC, akshat-jindal-nit commented
> Please fix conflicts.
> 
> No real concerns here, but can you update the release notes to match our typical format: https://googlecloudplatform.github.io/magic-modules/code-review/release-notes/

done

2024-12-17 17:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12540-old..auto-pr-12540) ( 5 files changed, 253 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12540-old..auto-pr-12540) ( 5 files changed, 253 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12540-old..auto-pr-12540) ( 1 file changed, 10 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12540-old..auto-pr-12540) ( 12 files changed, 354 insertions(+))

2024-12-17 17:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 34
Passed tests: 30
Skipped tests: 1
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>networkconnectivity</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetworkConnectivityHub_networkConnectivityHubMeshTopologyExample</li>
<li>TestAccNetworkConnectivityHub_networkConnectivityHubStarTopologyExample</li>
<li>TestAccNetworkConnectivitySpoke_networkConnectivitySpokeCenterGroupExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-17 17:35 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetworkConnectivityHub_networkConnectivityHubMeshTopologyExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12540/artifacts/8bb53062-bab9-46be-b180-a81c9e7ce802/recording/TestAccNetworkConnectivityHub_networkConnectivityHubMeshTopologyExample.log)]
`TestAccNetworkConnectivityHub_networkConnectivityHubStarTopologyExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12540/artifacts/8bb53062-bab9-46be-b180-a81c9e7ce802/recording/TestAccNetworkConnectivityHub_networkConnectivityHubStarTopologyExample.log)]
`TestAccNetworkConnectivitySpoke_networkConnectivitySpokeCenterGroupExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12540/artifacts/8bb53062-bab9-46be-b180-a81c9e7ce802/recording/TestAccNetworkConnectivitySpoke_networkConnectivitySpokeCenterGroupExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12540/artifacts/8bb53062-bab9-46be-b180-a81c9e7ce802/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12540/artifacts/8bb53062-bab9-46be-b180-a81c9e7ce802/recording) for each test

2024-12-17 18:05 UTC, slevenick approved these changes

2024-12-17 18:05 UTC, merged