Add support for source_workstation in workstations_workstation resource.
GoogleCloudPlatform/magic-modules pull request #12549
Opened 2024-12-12 03:45 UTC by esu

This adds support for workstation PD cloning using `source_workstation`. It can only be set during workstation resource creation and cannot be updated afterwards: https://cloud.google.com/workstations/docs/reference/rest/v1beta/projects.locations.workstationClusters.workstationConfigs.workstations#Workstation.FIELDS.source_workstation

The primary use case of this field is for recovery, so it doesn't seem possible to write an automated test for it. This is because a workstation must be started manually before it can be cloned, else its PD is not created. If there is a way to write a test that can send API calls outside of Terraform, please let me know.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/19730.

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:enhancement
workstations: add `source_workstation` field to `google_workstations_workstation` resource
```

2024-12-12 03:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12549-old..auto-pr-12549) ( 1 file changed, 5 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12549-old..auto-pr-12549) ( 2 files changed, 29 insertions(+))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12549-old..auto-pr-12549) ( 1 file changed, 10 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_workstations_workstation` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_workstations_workstation" "primary" {
  source_workstation = # value needed
}


```

2024-12-12 03:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 37
Passed tests: 37
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>workstations</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12549/artifacts/f126673a-86cc-40db-ab49-2078c88d1af9/build-log/replaying_test.log)

2024-12-12 18:32 UTC, ScottSuarez requested changes
Can you add tests for this field? Potentially an update and create test. 

You can extend existing ones where appropriate

2024-12-12 20:53 UTC, esu commented
It's difficult to write a create test for this field because it requires a manual human interaction on a dependency resource. A create test would have to:
1. Create a workstation
2. Start the workstation so that its PDs are initialized, else the API will reject the next step (and `StartWorkstation` is not possible through Terraform)
3. Create a second workstation specifying `source_workstation` to clone the first workstation's PDs

Is it possible to send GCP API calls without Terraform during a create test? Open to suggestions on how to implement this.
Lastly, if the field is immutable, does it need an update test?

2024-12-12 22:03 UTC, esu commented
I am not sure we can do that -- the initial workstation can be created using Terraform, but it's created in a `STOPPED` state in which it is not cloneable, even after the `CREATE` operation is reported as complete by the API.

In your example, creating a secondary workstation using `source_workstation` is "cloning" it, which the Workstations API will reject if the initial workstation is not manually started. Workstations are for human use and cannot be started using Terraform.

2024-12-17 21:04 UTC, ScottSuarez approved these changes

2024-12-17 21:04 UTC, merged

2024-12-17 21:04 UTC, ScottSuarez commented
tested locally