Adding deployment type to beta provider.
GoogleCloudPlatform/magic-modules pull request #12560
Opened 2024-12-12 19:46 UTC by unnatinadupalli

Adding deployment type to beta provider.

```release-note:enhancement
parallelstore: added `deployment_type` to `google_parallelstore_instance`
```

2024-12-12 19:50 UTC, c2thorn requested changes

2024-12-12 19:50 UTC, c2thorn commented on mmv1/templates/terraform/examples/parallelstore_instance_baic_beta.tf.tmpl
> +  provider = google-beta
Standard practice is to have the `provider = google-beta` line at the top of the resource (above the `name`) line. Do you mind making this change for all resources added in this PR?

2024-12-13 19:48 UTC, c2thorn commented
@unnatinadupalli I'd recommend following the initial steps here to get automatic build runs for any future pull requests: go/terraform-contribution-guide#before-you-begin

2024-12-13 19:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 60 insertions(+), 123 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 189 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-13 19:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/2ab7af64-afcd-4f6e-817f-4ad3eb4e0e2a/build-log/replaying_test.log)

2024-12-16 18:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 60 insertions(+), 123 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 174 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-16 18:32 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-16 18:50 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/8a098b02-c5ff-4e93-a955-9c75f89bd958/recording/TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/8a098b02-c5ff-4e93-a955-9c75f89bd958/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/8a098b02-c5ff-4e93-a955-9c75f89bd958/recording) for each test

2024-12-16 20:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 76 insertions(+), 13 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 258 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-16 20:13 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/02d9cd56-c885-4bc7-b7cd-87e578e24622/build-log/replaying_test.log)

2024-12-16 20:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 76 insertions(+), 13 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 258 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-16 20:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-16 20:48 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/4b7e70b7-b59e-4203-a34c-f6b4512cbb1d/build-log/recording_build/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/4b7e70b7-b59e-4203-a34c-f6b4512cbb1d/recording/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/4b7e70b7-b59e-4203-a34c-f6b4512cbb1d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/4b7e70b7-b59e-4203-a34c-f6b4512cbb1d/recording) for each test

2024-12-16 22:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 75 insertions(+), 12 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 214 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-16 22:10 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 3
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/2ecf2889-7037-4294-a786-9e4bb70401dd/build-log/replaying_test.log)

2024-12-16 22:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 76 insertions(+), 12 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 236 insertions(+), 1 deletion(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-16 22:29 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/37489c10-6afa-4fe7-9814-0e995571e2d2/build-log/replaying_test.log)

2024-12-17 18:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 79 insertions(+), 13 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 228 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 18:30 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccParallelstoreInstance_parallelstoreInstanceBasicBetaExample
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/4c04fe15-72cb-432e-a6f7-dba9e23dd3f5/build-log/replaying_test.log)

2024-12-17 19:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 79 insertions(+), 13 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 226 insertions(+), 3 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 19:04 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-17 19:05 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/6901d050-11c7-4945-b112-b301ae1e1449/build-log/recording_build/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/6901d050-11c7-4945-b112-b301ae1e1449/recording/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/6901d050-11c7-4945-b112-b301ae1e1449/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/6901d050-11c7-4945-b112-b301ae1e1449/recording) for each test

2024-12-17 19:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 82 insertions(+), 14 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 219 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 19:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-17 19:21 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/b9bf3a87-5124-456e-8dec-c12d2a0df832/build-log/recording_build/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/b9bf3a87-5124-456e-8dec-c12d2a0df832/recording/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/b9bf3a87-5124-456e-8dec-c12d2a0df832/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/b9bf3a87-5124-456e-8dec-c12d2a0df832/recording) for each test

2024-12-17 19:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 82 insertions(+), 14 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 219 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 19:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 2
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-17 19:58 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/9755f1b3-8fda-4813-974a-96a6e110f6d5/recording/TestAccParallelstoreInstance_parallelstoreInstanceBasicExample_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/9755f1b3-8fda-4813-974a-96a6e110f6d5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/9755f1b3-8fda-4813-974a-96a6e110f6d5/recording) for each test

2024-12-17 20:24 UTC, c2thorn approved these changes

2024-12-17 20:25 UTC, c2thorn requested changes
```
Error: google/services/parallelstore/resource_parallelstore_instance_test.go:155:1: expected declaration, found '}'
```

2024-12-17 20:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 63 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 217 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 20:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 3
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/0e58ae40-976f-4806-b160-777e17a0ab5a/build-log/replaying_test.log)

2024-12-17 21:05 UTC, unnatinadupalli commented
> ```
> Error: google/services/parallelstore/resource_parallelstore_instance_test.go:155:1: expected declaration, found '}'
> ```

Done

2024-12-17 21:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 63 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 217 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 21:19 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 3
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/3b1fe212-1682-4acd-8bb1-6b8d656d4066/build-log/replaying_test.log)

2024-12-17 21:58 UTC, c2thorn commented
/gcbrun

2024-12-17 22:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12560-old..auto-pr-12560) ( 2 files changed, 63 insertions(+), 3 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12560-old..auto-pr-12560) ( 4 files changed, 217 insertions(+), 13 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12560-old..auto-pr-12560) ( 1 file changed, 10 insertions(+))

2024-12-17 22:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 3
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>parallelstore</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12560/artifacts/d17a1d4f-8ba4-4bcb-baea-02581020a0d8/build-log/replaying_test.log)

2024-12-17 22:51 UTC, c2thorn approved these changes

2024-12-17 22:51 UTC, merged