CodeRepositoryIndex cascade deletion
GoogleCloudPlatform/magic-modules pull request #12601
Opened 2024-12-18 16:58 UTC by JumiDeluxe

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note: enhancement
gemini: added `force_destroy` field to resource `google_code_repository_index`, enabling deletion of the resource even when it has dependent RepositoryGroups
```

2024-12-18 17:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 2 files changed, 1 insertion(+), 143 deletions(-))

2024-12-18 17:11 UTC, modular-magician commented
#### Tests analytics
Total tests: 3
Passed tests: 3
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/5dd5913c-1a70-4b3d-8166-ff1537400118/build-log/replaying_test.log)

2024-12-19 15:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 2 files changed, 2 insertions(+), 143 deletions(-))

2024-12-19 15:47 UTC, modular-magician commented
#### Tests analytics
Total tests: 6
Passed tests: 4
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccGeminiCodeRepositoryIndex_update</li>
<li>TestAccGeminiRepositoryGroup_noBootstrap</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-19 16:28 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/9817f9c3-c99c-4fe0-ac96-9affe66dc4d2/recording/TestAccGeminiCodeRepositoryIndex_update.log)]
`TestAccGeminiRepositoryGroup_noBootstrap` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/9817f9c3-c99c-4fe0-ac96-9affe66dc4d2/recording/TestAccGeminiRepositoryGroup_noBootstrap.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/9817f9c3-c99c-4fe0-ac96-9affe66dc4d2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/9817f9c3-c99c-4fe0-ac96-9affe66dc4d2/recording) for each test

2024-12-19 23:00 UTC, frsv approved these changes

2024-12-23 20:47 UTC, NickElliot reviewed
Hi, code LGTM but could you clarify what the "cascade deletion" is doing here so I could make sure the release note wording is what we want to convey for Terraform users? thanks!

2024-12-23 21:46 UTC, JumiDeluxe commented
"Cascade deletion" means that we automatically remove children resources (Repository Groups) upon CRIs deletion.

2024-12-30 20:24 UTC, NickElliot requested changes
Got it, could you add a test case for this functionality?

2025-01-08 17:09 UTC, JumiDeluxe commented
> Got it, could you add a test case for this functionality?

Added to CRI tests, the new test tries to remove CRI without removing RG directly in Terraform.
All children resources should be deleted, so we're expecting a new plan.

2025-01-08 17:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 3 files changed, 128 insertions(+), 143 deletions(-))

2025-01-08 17:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccGeminiCodeRepositoryIndex_delete</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-08 17:49 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_delete` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/cd377ea1-6643-48be-9bc3-1bff421dd6a3/recording/TestAccGeminiCodeRepositoryIndex_delete.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/cd377ea1-6643-48be-9bc3-1bff421dd6a3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/cd377ea1-6643-48be-9bc3-1bff421dd6a3/recording) for each test

2025-01-09 18:36 UTC, NickElliot reviewed
thanks for the test! I wanted to make a suggestion though to fly by:

due to that test working the way it did, I realized we could make users make accidental changes to their states when currently they have a protective guard. Would it be preferable to add a virtual field "`force_delete`" that serves as a flag for sending the `obj["force"] = true` body?

If you have an opinion as the service team member that it shouldn't be an issue, let me know

2025-01-09 19:35 UTC, JumiDeluxe commented
Thanks for questions

> Would it be preferable to add a virtual field "`force_delete`" that serves as a flag for sending the `obj["force"] = true` body during DELETE?

Due to how Terraform tries to operate on multiple resources at the same time, and it by default doesn't know about resources dependencies, enforcing that this option is selected always is necessary.
In a case, where user correctly removes all children resources along with `CodeRepositoryIndex` from Terraform files, an error might occur when Terraform tries to delete `CodeRepositoryIndex` before all of `RepositoryGroup` resources owned by it finish deletion.

Of course, a user only needs to apply the changes again, but we don't want users to have to do it just because of how Terraform works.

However, I think we could add `deletion_protection` field, as it seems like it is recommended now: https://googlecloudplatform.github.io/magic-modules/best-practices/deletion-behaviors/

2025-01-10 00:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12601-old..auto-pr-12601) ( 1 file changed, 1 insertion(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 4 files changed, 157 insertions(+), 143 deletions(-))

2025-01-10 00:30 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 4
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccGeminiCodeRepositoryIndex_delete</li>
<li>TestAccGeminiCodeRepositoryIndex_update</li>
<li>TestAccGeminiRepositoryGroup_noBootstrap</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-10 00:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12601-old..auto-pr-12601) ( 1 file changed, 1 insertion(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 4 files changed, 157 insertions(+), 143 deletions(-))

2025-01-10 00:58 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 4
Skipped tests: 0
Affected tests: 3

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccGeminiCodeRepositoryIndex_delete</li>
<li>TestAccGeminiCodeRepositoryIndex_update</li>
<li>TestAccGeminiRepositoryGroup_noBootstrap</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-10 01:10 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/recording/TestAccGeminiCodeRepositoryIndex_update.log)]
`TestAccGeminiRepositoryGroup_noBootstrap` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/recording/TestAccGeminiRepositoryGroup_noBootstrap.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_delete` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/build-log/recording_build/TestAccGeminiCodeRepositoryIndex_delete_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/recording/TestAccGeminiCodeRepositoryIndex_delete.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/7c5a5c6a-6209-4777-95f0-7e7d90931a71/recording) for each test

2025-01-10 01:37 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccGeminiRepositoryGroup_noBootstrap` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/recording/TestAccGeminiRepositoryGroup_noBootstrap.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_delete` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/build-log/recording_build/TestAccGeminiCodeRepositoryIndex_delete_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/recording/TestAccGeminiCodeRepositoryIndex_delete.log)]
`TestAccGeminiCodeRepositoryIndex_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/build-log/recording_build/TestAccGeminiCodeRepositoryIndex_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/recording/TestAccGeminiCodeRepositoryIndex_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/d8b3184f-674b-4dd8-b8c8-4af746e90b9b/recording) for each test

2025-01-10 14:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12601-old..auto-pr-12601) ( 1 file changed, 1 insertion(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12601-old..auto-pr-12601) ( 4 files changed, 155 insertions(+), 143 deletions(-))

2025-01-10 14:41 UTC, modular-magician commented
#### Tests analytics
Total tests: 7
Passed tests: 6
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>gemini</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccGeminiCodeRepositoryIndex_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-10 15:08 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccGeminiCodeRepositoryIndex_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/f2b57bbb-127e-4c39-b8d5-223fb9f24a24/recording/TestAccGeminiCodeRepositoryIndex_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/f2b57bbb-127e-4c39-b8d5-223fb9f24a24/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12601/artifacts/f2b57bbb-127e-4c39-b8d5-223fb9f24a24/recording) for each test

2025-01-10 21:28 UTC, NickElliot commented on mmv1/products/gemini/CodeRepositoryIndex.yaml
> +      If set to true, any RepositoryGroups for this CodeRepositoryIndex will also be deleted.
```suggestion
      If set to true, will allow deletion of the CodeRepositoryIndex even if there are existing
      RepositoryGroups for the resource. These RepositoryGroups will also be deleted.
```

2025-01-10 21:29 UTC, NickElliot approved these changes
LGTM!

2025-01-10 21:30 UTC, merged

2025-01-10 21:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.