Add google_chronicle_data_access_label resource to chronicle
GoogleCloudPlatform/magic-modules pull request #12638
Opened 2024-12-23 10:01 UTC by ankitgoyal0301

Add terraform support for DataAccessLabels in Chronicle. 

Resource name: google_chronicle_data_access_label

2024-12-23 10:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 2 files changed, 154 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_chronicle_data_access_label` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_chronicle_data_access_label" "primary" {
  name = # value needed
}


```

2024-12-23 10:25 UTC, ankitgoyal0301 commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 2 files changed, 154 insertions(+)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))
> 
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_chronicle_data_access_label` (3 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```hcl
> resource "google_chronicle_data_access_label" "primary" {
>   name = # value needed
> }
> ```

Regarding the missing test report, the name is of the form projects/{{project}}/locations/{{location}}/instances/{{instance}}/dataAccessLabels/{{data_access_label_id}}, which is derived from project, instance and location and data_access_label_id passed seperately.

2024-12-23 10:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 2 files changed, 154 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_chronicle_data_access_label` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_chronicle_data_access_label" "primary" {
  name = # value needed
}


```

2024-12-23 11:49 UTC, modular-magician commented
#### Tests analytics
Total tests: 4383
Passed tests: 3948
Skipped tests: 429
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample</li>
<li>TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccDataSourceGoogleQuotaInfo_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-23 12:46 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample.log)]
`TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleQuotaInfo_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/build-log/recording_build/TestAccDataSourceGoogleQuotaInfo_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccDataSourceGoogleQuotaInfo_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/build-log/recording_build/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/48076d55-90c2-4a6b-9f2d-0371a348d812/recording) for each test

2024-12-23 14:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 3 files changed, 159 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_chronicle_data_access_label` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_chronicle_data_access_label" "primary" {
  name = # value needed
}


```

2024-12-23 15:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 4383
Passed tests: 3950
Skipped tests: 429
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccDataSourceGoogleQuotaInfo_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-23 16:33 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleQuotaInfo_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/build-log/recording_build/TestAccDataSourceGoogleQuotaInfo_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/recording/TestAccDataSourceGoogleQuotaInfo_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/build-log/recording_build/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/recording/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/73d3b504-dbb2-41b1-9e20-3118b586c687/recording) for each test

2024-12-24 04:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 4 files changed, 164 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_chronicle_data_access_label` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_chronicle_data_access_label" "primary" {
  name = # value needed
}


```

2024-12-24 05:16 UTC, modular-magician commented
#### Tests analytics
Total tests: 4383
Passed tests: 3950
Skipped tests: 429
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccDataSourceGoogleQuotaInfo_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-24 06:11 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleQuotaInfo_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccDataSourceGoogleQuotaInfo_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccDataSourceGoogleQuotaInfo_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording) for each test

2024-12-24 06:34 UTC, ankitgoyal0301 commented
> Regarding the missing test report, the name is of the form projects/{{project}}/locations/{{location}}/instances/{{instance}}/dataAccessLabels/{{data_access_label_id}}, which is derived from project, instance and location and data_access_label_id passed seperately.

Regarding the missing test report, the name is of the form projects/{{project}}/locations/{{location}}/instances/{{instance}}/dataAccessLabels/{{data_access_label_id}}, which is derived from project, instance and location and data_access_label_id passed seperately.

2024-12-24 06:35 UTC, ankitgoyal0301 commented
> Hi there, I'm the Modular magician. I've detected the following information about your changes:
> 
> ## Diff report
> Your PR generated some diffs in downstreams - here they are.
> 
> `google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 4 files changed, 164 insertions(+)) `google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 996 insertions(+), 2 deletions(-)) `terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 89 insertions(+))
> 
> ## Missing test report
> Your PR includes resource fields which are not covered by any test.
> 
> Resource: `google_chronicle_data_access_label` (3 total tests) Please add an acceptance test which includes these fields. The test should include the following:
> 
> ```hcl
> resource "google_chronicle_data_access_label" "primary" {
>   name = # value needed
> }
> ```

Regarding the missing test report, the name is of the form projects/{{project}}/locations/{{location}}/instances/{{instance}}/dataAccessLabels/{{data_access_label_id}}, which is derived from project, instance and location and data_access_label_id passed seperately.

2024-12-24 06:35 UTC, ankitgoyal0301 commented
> 🟢 Tests passed during RECORDING mode: `TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
> 
> 🔴 Tests failed when rerunning REPLAYING mode: `TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
> 
> Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.
> 
> Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.
> 
> 🔴 Tests failed during RECORDING mode: `TestAccDataSourceGoogleQuotaInfo_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccDataSourceGoogleQuotaInfo_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccDataSourceGoogleQuotaInfo_basic.log)] `TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccEphemeralServiceAccountKey_basic.log)] `TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_build/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording/TestAccSecureSourceManagerInstance_secureSourceManagerInstancePrivatePscBackendExample.log)]
> 
> 🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.
> 
> View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/b9678bba-5349-4f23-95e3-6fb84ae7524e/recording) for each test

The failing tests are not relevant to Chronicle.

2024-12-29 15:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 4 files changed, 161 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 12 files changed, 965 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 79 insertions(+))

2024-12-29 16:57 UTC, modular-magician commented
#### Tests analytics
Total tests: 4384
Passed tests: 3950
Skipped tests: 429
Affected tests: 5

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccDataSourceGoogleQuotaInfo_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccStorageTransferReplicationJob_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-29 17:05 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording/TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording/TestAccStorageTransferReplicationJob_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccDataSourceGoogleQuotaInfo_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/build-log/recording_build/TestAccDataSourceGoogleQuotaInfo_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording/TestAccDataSourceGoogleQuotaInfo_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording/TestAccEphemeralServiceAccountKey_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/a16b0de9-a475-40a5-a4f5-427dfc420f79/recording) for each test

2024-12-31 11:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 2 files changed, 151 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 7 files changed, 941 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 79 insertions(+))

2024-12-31 11:07 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 4
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>chronicle</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/fc8ce959-6ae0-4242-a7b2-3fe3c6f0a4e5/build-log/replaying_test.log)

2025-01-01 13:18 UTC, ronakgadia commented on mmv1/products/chronicle/DataAccessLabel.yaml
> +      only contain ASCII lowercase letters, numbers, and dashes; it must begin
The maximum number of characters should be 63. Regex pattern is as per AIP: https://google.aip.dev/122#resource-id-segments

2025-01-01 13:24 UTC, ronakgadia requested changes

2025-01-01 13:24 UTC, ronakgadia commented on mmv1/products/chronicle/DataAccessLabel.yaml
> +    description: Output only. The short name displayed for the label as it appears on event data.
nit: Let's mention that this is same as data_access_label_id

2025-01-01 13:24 UTC, ronakgadia commented on mmv1/templates/terraform/examples/chronicle_dataaccesslabel_basic.tf.tmpl
> +  data_access_label_id = "{{index $.Vars "name"}}"
Shouldn't this be `dataAccessLabelId`

2025-01-02 07:09 UTC, ankitgoyal0301 commented on mmv1/products/chronicle/DataAccessLabel.yaml
> +      only contain ASCII lowercase letters, numbers, and dashes; it must begin
The current description is as per the comment in the proto, do we need to change that too? Sharing the link to that in our chat.

2025-01-02 07:30 UTC, ankitgoyal0301 commented on mmv1/products/chronicle/DataAccessLabel.yaml
> +    description: Output only. The short name displayed for the label as it appears on event data.
Updated

2025-01-02 07:31 UTC, ankitgoyal0301 commented on mmv1/templates/terraform/examples/chronicle_dataaccesslabel_basic.tf.tmpl
> +  data_access_label_id = "{{index $.Vars "name"}}"
I just passed the ID from the YAML file with a variable `name`, hence caused confusion. Updated the variable `name` to `data_access_label_id` for more clarity.

2025-01-02 07:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12638-old..auto-pr-12638) ( 2 files changed, 151 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12638-old..auto-pr-12638) ( 7 files changed, 941 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12638-old..auto-pr-12638) ( 1 file changed, 79 insertions(+))

2025-01-02 07:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 4
Passed tests: 2
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>chronicle</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample</li>
<li>TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-02 07:43 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/3163db37-d7e4-48d0-bace-c1f6714ba36c/recording/TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample.log)]
`TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/3163db37-d7e4-48d0-bace-c1f6714ba36c/recording/TestAccChronicleDataAccessLabel_chronicleDataaccesslabelBasicExample_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/3163db37-d7e4-48d0-bace-c1f6714ba36c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12638/artifacts/3163db37-d7e4-48d0-bace-c1f6714ba36c/recording) for each test

2025-01-06 20:13 UTC, SirGitsalot approved these changes

2025-01-06 20:14 UTC, merged