Add support for resource google_vertex_ai_notebook_runtime_template
GoogleCloudPlatform/magic-modules pull request #12654
Opened 2024-12-26 13:43 UTC by JonasHogman

Fixes https://github.com/hashicorp/terraform-provider-google/issues/16865
**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-resource
`google_vertex_ai_notebook_runtime_template`
```

2025-01-06 16:35 UTC, ScottSuarez approved these changes

2025-01-06 16:35 UTC, ScottSuarez reviewed
sorry un-approving--- need to run test suites. Needed to approve the cloud build :P

2025-01-06 16:48 UTC, modular-magician commented
#### Tests analytics
Total tests: 64
Passed tests: 55
Skipped tests: 3
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>vertexai</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccVertexAINotebookRuntimeTemplateIamBindingGenerated</li>
<li>TestAccVertexAINotebookRuntimeTemplateIamMemberGenerated</li>
<li>TestAccVertexAINotebookRuntimeTemplateIamPolicyGenerated</li>
<li>TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateBasicExample</li>
<li>TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample</li>
<li>TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-06 16:50 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccVertexAINotebookRuntimeTemplateIamBindingGenerated` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplateIamBindingGenerated.log)]
`TestAccVertexAINotebookRuntimeTemplateIamMemberGenerated` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplateIamMemberGenerated.log)]
`TestAccVertexAINotebookRuntimeTemplateIamPolicyGenerated` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplateIamPolicyGenerated.log)]
`TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateBasicExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/build-log/recording_build/TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample.log)]
`TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/build-log/recording_build/TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording/TestAccVertexAINotebookRuntimeTemplate_vertexAiNotebookRuntimeTemplateFullExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12654/artifacts/cf5386c8-fc8a-420e-9f13-de7124a83f20/recording) for each test

2025-01-06 22:14 UTC, ScottSuarez requested changes
Looks like there are some test failures on the region creation location

2025-01-13 16:50 UTC, JonasHogman commented
I see that there is a duplicate PR https://github.com/GoogleCloudPlatform/magic-modules/pull/12706

This one can be closed in favour of that one as I currently have limited time to work on fixing the tests.

2025-01-14 18:07 UTC, closed without merging