Add new resource netapp volumes quotaRules
GoogleCloudPlatform/magic-modules pull request #12665
Opened 2024-12-28 13:32 UTC by Mehul3217

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:new-resource
google_netapp_volume_quota_rule
```

2024-12-28 13:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1091 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1091 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 96 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 128 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  description = # value needed
  labels      = # value needed
  target      = # value needed
}


```

2024-12-28 13:46 UTC, modular-magician commented
#### Tests analytics
Total tests: 0
Passed tests: 0
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample
- TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample
🔴 Errors occurred during REPLAYING mode. Please fix them to complete your PR.

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/9fd0d23b-b65c-44d9-9438-0a0fead0a50a/build-log/replaying_test.log)

2024-12-28 19:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  description = # value needed
  labels      = # value needed
  target      = # value needed
}


```

2024-12-28 19:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  description = # value needed
  labels      = # value needed
  target      = # value needed
}


```

2024-12-28 20:40 UTC, modular-magician commented
#### Tests analytics
Total tests: 22
Passed tests: 20
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-28 20:42 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4945fb9d-4859-4b7c-a46f-2cd2dec1f3eb/recording) for each test

2024-12-28 20:42 UTC, modular-magician commented
#### Tests analytics
Total tests: 22
Passed tests: 20
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-28 20:43 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/da5cd807-9278-4afd-8a6a-cd3ffe689019/recording) for each test

2024-12-28 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1176 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))

2024-12-28 21:59 UTC, modular-magician commented
#### Tests analytics
Total tests: 22
Passed tests: 20
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2024-12-28 22:21 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/c0896de3-9036-4436-b15a-24b55a32c212/recording) for each test

2025-01-20 10:38 UTC, okrause commented on mmv1/third_party/terraform/services/netapp/resource_netapp_volume_quotaRule_test.go
> +  disk_limit_mib = 50
Change the actual value too?

2025-01-20 10:38 UTC, okrause commented on mmv1/third_party/terraform/services/netapp/resource_netapp_volume_quotaRule_test.go
> +resource "google_netapp_volume_quota_rule" "test_quotaRule" {
Can we add test for all 4 types of quotas?

2025-01-22 09:17 UTC, Mehul3217 commented on mmv1/third_party/terraform/services/netapp/resource_netapp_volume_quotaRule_test.go
> +resource "google_netapp_volume_quota_rule" "test_quotaRule" {
Done

2025-01-22 09:17 UTC, Mehul3217 commented on mmv1/third_party/terraform/services/netapp/resource_netapp_volume_quotaRule_test.go
> +  disk_limit_mib = 50
Done

2025-01-22 10:17 UTC, modular-magician commented
#### Tests analytics
Total tests: 22
Passed tests: 20
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-22 10:19 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4f0d5471-1a33-48e4-a4cc-1430b05c47ae/recording) for each test

2025-01-28 08:42 UTC, Mehul3217 commented
/gcbrun

2025-01-30 09:48 UTC, okrause requested changes
Thank you! Looks pretty good. Suggested a few small changes. I learned that it pay to be explicit in descriptions.

2025-01-30 09:48 UTC, okrause commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> + <TO BE FILLED>
QuotaRule specifies the maximum capacity a user or group can use within a volume. They can be used for creating default and individual quota rules.

2025-01-30 09:48 UTC, okrause commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +    'Documentation': <TBD>
https://cloud.google.com/netapp/volumes/docs/configure-and-use/volumes/overview#volume_user_and_group_quotas

2025-01-30 09:48 UTC, okrause commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +  api: <TBD>
https://cloud.google.com/netapp/volumes/docs/reference/rest/v1/projects.locations.volumes.quotaRules

2025-01-30 09:48 UTC, okrause commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +      The quota rule applies to the specified user or group, identified by a Unix UID/GID, Windows SID, or null for default.
The quota rule applies to the specified user or group.
Valid targets for volumes with NFS protocol enabled:
- UNIX UID for individual user quota
- UNIX GID for individual group quota
Valid targets for volumes with SMB protocol enabled: 
- Windows SID for individual user quota

Leave empty for default quotas.

2025-01-30 09:48 UTC, okrause commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +      The maximum allowed disk space in MiB.
"disk space" is a somehow outdated term. I would prefer to use "capacity" instead. Unfortunately, the term disk space is encoded in the field parameter. Now the question is: use "disk space" in parameter and description, or change description to "capacity"?

2025-01-31 10:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  labels = # value needed
}


```

2025-01-31 11:12 UTC, modular-magician commented
#### Tests analytics
Total tests: 23
Passed tests: 21
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-31 11:13 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/612ea6ad-c22c-4c50-b7bb-6ce564a9b47e/recording) for each test

2025-02-01 14:52 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> + <TO BE FILLED>
Done

2025-02-01 14:52 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +    'Documentation': <TBD>
Done

2025-02-01 14:53 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +  api: <TBD>
Done

2025-02-01 14:53 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +      The quota rule applies to the specified user or group, identified by a Unix UID/GID, Windows SID, or null for default.
Done

2025-02-01 14:53 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +      The maximum allowed disk space in MiB.
done, changed to capacity

2025-02-02 17:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  labels = # value needed
}


```

2025-02-02 18:37 UTC, modular-magician commented
#### Tests analytics
Total tests: 23
Passed tests: 21
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-02 18:39 UTC, modular-magician commented
🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/4005d122-f2ee-4e61-ab8a-0718e0c08e5e/recording) for each test

2025-02-03 05:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1274 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  labels = # value needed
}


```

2025-02-03 06:18 UTC, modular-magician commented
#### Tests analytics
Total tests: 23
Passed tests: 21
Skipped tests: 0
Affected tests: 2

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample</li>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-03 06:21 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/48c8b856-58ab-42f9-a99d-9cf0d0f1efb3/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---


🔴 Tests failed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/48c8b856-58ab-42f9-a99d-9cf0d0f1efb3/build-log/recording_build/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/48c8b856-58ab-42f9-a99d-9cf0d0f1efb3/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/48c8b856-58ab-42f9-a99d-9cf0d0f1efb3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/48c8b856-58ab-42f9-a99d-9cf0d0f1efb3/recording) for each test

2025-02-03 07:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1310 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1310 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_netapp_volume_quota_rule` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_netapp_volume_quota_rule" "primary" {
  labels = # value needed
}


```

2025-02-03 08:24 UTC, modular-magician commented
#### Tests analytics
Total tests: 23
Passed tests: 22
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-04 04:16 UTC, Mehul3217 commented
@BBBmau a gentle reminder to review this PR please

2025-02-04 17:58 UTC, melinath commented
@modular-magician reassign-reviewer

2025-02-04 18:00 UTC, melinath commented
@SirGitsalot could you take a look at this today?

2025-02-04 20:17 UTC, SirGitsalot requested changes
One small comment, otherwise LGTM

2025-02-04 20:17 UTC, SirGitsalot commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +    required: true
Remove `required: true` here

While it's required by the API, making it required in the Terraform config prevents the [provider level default](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/getting_started#configuring-the-provider) from being applied.

2025-02-05 04:04 UTC, Mehul3217 commented on mmv1/products/netapp/VolumeQuotaRule.yaml
> +    required: true
Done

2025-02-05 04:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1319 insertions(+), 2 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12665-old..auto-pr-12665) ( 7 files changed, 1319 insertions(+), 2 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12665-old..auto-pr-12665) ( 1 file changed, 116 insertions(+))
Open in Cloud Shell: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-12665-old..auto-pr-12665) ( 4 files changed, 130 insertions(+))

2025-02-05 05:09 UTC, modular-magician commented
#### Tests analytics
Total tests: 23
Passed tests: 22
Skipped tests: 0
Affected tests: 1

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>netapp</li>

</ul>

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-05 05:14 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/9b8b20c7-2739-4776-9853-c88045b08c4d/recording/TestAccNetappVolumeQuotaRule_netappVolumeQuotaRuleBasicExample_update.log)]

🟢 No issues found for passed tests after REPLAYING rerun.

---






🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/9b8b20c7-2739-4776-9853-c88045b08c4d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12665/artifacts/9b8b20c7-2739-4776-9853-c88045b08c4d/recording) for each test

2025-02-06 21:49 UTC, SirGitsalot approved these changes

2025-02-06 21:50 UTC, merged