Fixes PermaDiff Issue
GoogleCloudPlatform/magic-modules pull request #12666
Opened 2024-12-30 10:07 UTC by kautikdk

Fixes permadiff issue in `google_storage_transfer_job` resource.  Ticket: b/386174536

Cause: It appears that the issue is happening because of `GetOkExists` used to obtain value of `aws_s3_data_source.aws_access_key` in the flattener. `GetOkExists` checks for the presence of the value regardless of zero value of the field. So here, In this case, we are always getting zero value of the field `aws_s3_data_source.aws_access_key` which empty list, `[]`, and true for it's existence even though it's not specified in the config. 

Solution: We can use `GetOk` to obtain value of the field from the config. `GetOk` treats zero value as absent which is use case here like other `TypeList` field.

Testing: Currently `storagetransfer` service lacks acceptance tests for third-party cloud providers so there is no way to add acceptance tests.

2024-12-30 10:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12666-old..auto-pr-12666) ( 1 file changed, 1 insertion(+), 1 deletion(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12666-old..auto-pr-12666) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2024-12-30 10:21 UTC, modular-magician commented
#### Tests analytics
Total tests: 13
Passed tests: 13
Skipped tests: 0
Affected tests: 0

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

<ul>
<li>storagetransfer</li>

</ul>

</blockquote>
</details>

🟢 All tests passed!

View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12666/artifacts/eed4aea2-12e3-4175-b408-1a1ae2d68515/build-log/replaying_test.log)

2025-01-02 18:31 UTC, zli82016 commented
@kautikdk , thanks for the fix. Do you mind adding a test case for this fix in this file https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/services/storagetransfer/resource_storage_transfer_job_test.go? Thanks.

2025-01-02 18:31 UTC, zli82016 requested changes
Add a test

2025-01-03 09:14 UTC, kautikdk commented
Actually we don't have tests for third party transfer service as it requires GCP setup for storing various 3p credentials. It's not done yet so the only option is manual testing as of now.

2025-01-08 12:21 UTC, kautikdk commented
Hi @zli82016, Shared testing logs internally.

2025-01-08 17:32 UTC, zli82016 approved these changes
LGTM. Thanks.

2025-01-08 17:35 UTC, merged