Adding missing fields to compute resources
GoogleCloudPlatform/magic-modules pull request #12672
Opened 2024-12-31 09:42 UTC by karolgorc

Hi this is a PR to fix feature gap between the API and the provider on disks and encryption. I'll look for any tickets that this fixes and update them later.

Tested this for basic breaking changes (created an instance on upstream provider and did a terraform apply on the custom provider) - no changes in configuration shown

Fields added:

- **google_compute_instance**
  - boot_disk.architecture
  - boot_disk.guest_os_features
  - boot_disk.disk_encryption_key_rsa
  - boot_disk.disk_encryption_service_account
  - boot_disk.initialize_params.source_image_encryption_key
    - boot_disk.initialize_params.source_image_encryption_key.raw_key
    - boot_disk.initialize_params.source_image_encryption_key.rsa_encrypted_key
    - boot_disk.initialize_params.source_image_encryption_key.kms_key_self_link
    - boot_disk.initialize_params.source_image_encryption_key.kms_key_service_account
    - boot_disk.initialize_params.source_image_encryption_key.sha256
  - boot_disk.initialize_params.snapshot
  - boot_disk.initialize_params.source_snapshot_encryption_key
    - boot_disk.initialize_params.source_snapshot_encryption_key.raw_key
    - boot_disk.initialize_params.source_snapshot_encryption_key.rsa_encrypted_key
    - boot_disk.initialize_params.source_snapshot_encryption_key.kms_key_self_link
    - boot_disk.initialize_params.source_snapshot_encryption_key.kms_key_service_account
    - boot_disk.initialize_params.source_snapshot_encryption_key.sha256
  - attached_disk.disk_encryption_key_rsa
  - attached_disk.disk_encryption_service_account
  - instance_encryption_key
    - instance_encryption_key.kms_key_self_link
    - instance_encryption_key.kms_key_service_account
    - instance_encryption_key.sha256

- **google_compute_image**
  - image_encryption_key.raw_key
  - image_encryption_key.rsa_encrypted_key

- **google_compute_snapshot**
  - snapshot_encryption_key.rsa_encrypted_key

- **google_compute_instance_template**
  - disk.architecture
  - disk.guest_os_features
  - source_image_encryption_key.raw_key
  - source_image_encryption_key,rsa_encrypted_key
  - source_snapshot_encryption_key.raw_key
  - source_snapshot_encryption_key.rsa_encrypted_key
  - disk_encryption_key.kms_key_service_account

- **google_compute_region_instance_template**
  - disk.architecture
  - disk.guest_os_features
  - source_image_encryption_key.raw_key
  - source_image_encryption_key,rsa_encrypted_key
  - source_snapshot_encryption_key.raw_key
  - source_snapshot_encryption_key.rsa_encrypted_key
  - disk_encryption_key.kms_key_service_account 

**Release Note Template for Downstream PRs (will be copied)**

See [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) for guidance.

```release-note:enhancement
compute: Add mising fields for kms and disks to compute resources
```

2025-01-03 20:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2095 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2095 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (355 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    disk_encryption_service_account = # value needed
  }
  boot_disk {
    device_name                     = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      source_image_encryption_key {
        kms_key_service_account = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_service_account = # value needed
      }
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      image        = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_template` (242 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_template" "primary" {
  disk {
    architecture = # value needed
  }
}


```
Resource: `google_compute_region_instance_template` (76 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_region_instance_template" "primary" {
  disk {
    architecture = # value needed
    disk_encryption_key {
      kms_key_self_link       = # value needed
      kms_key_service_account = # value needed
    }
  }
}


```

2025-01-03 20:28 UTC, modular-magician commented
#### Tests analytics
Total tests: 4399
Passed tests: 37
Skipped tests: 431
Affected tests: 3931

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3931 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessApprovalSettings</li>
<li>TestAccAccessContextManager</li>
<li>TestAccAlloydbBackup_alloydbBackupBasicTestExample</li>
<li>TestAccAlloydbBackup_alloydbBackupFullExample</li>
<li>TestAccAlloydbBackup_createBackupWithMandatoryFields</li>
<li>TestAccAlloydbBackup_update</li>
<li>TestAccAlloydbBackup_usingCMEK</li>
<li>TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight</li>
<li>TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable</li>
<li>TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_alloydbClusterBasicExample</li>
<li>TestAccAlloydbCluster_alloydbClusterFullExample</li>
<li>TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample</li>
<li>TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable</li>
<li>TestAccAlloydbCluster_continuousBackup_enabledByDefault</li>
<li>TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved</li>
<li>TestAccAlloydbCluster_continuousBackup_update</li>
<li>TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet</li>
<li>TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy</li>
<li>TestAccAlloydbCluster_mandatoryFields</li>
<li>TestAccAlloydbCluster_maximumFields</li>
<li>TestAccAlloydbCluster_missingWeeklySchedule</li>
<li>TestAccAlloydbCluster_restore</li>
<li>TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary</li>
<li>TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary</li>
<li>TestAccAlloydbCluster_secondaryClusterMandatoryFields</li>
<li>TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterPromote</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_secondaryClusterUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterUsingCMEK</li>
<li>TestAccAlloydbCluster_secondaryClusterWithNetworkConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_standardClusterUpdate</li>
<li>TestAccAlloydbCluster_standardClusterUpdateFailure</li>
<li>TestAccAlloydbCluster_trialClusterUpdate</li>
<li>TestAccAlloydbCluster_update</li>
<li>TestAccAlloydbCluster_usingCMEK</li>
<li>TestAccAlloydbCluster_withMaintenanceWindows</li>
<li>TestAccAlloydbCluster_withNetworkConfig</li>
<li>TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_withPrivateServiceConnect</li>
<li>TestAccAlloydbCluster_withSubscriptionTypeStandard</li>
<li>TestAccAlloydbCluster_withSubscriptionTypeTrial</li>
<li>TestAccAlloydbInstance_alloydbInstanceBasicTestExample</li>
<li>TestAccAlloydbInstance_alloydbInstancePscTestExample</li>
<li>TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample</li>
<li>TestAccAlloydbInstance_clientConnectionConfig</li>
<li>TestAccAlloydbInstance_createInstanceWithMandatoryFields</li>
<li>TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbInstance_createPrimaryAndReadPoolInstance</li>
<li>TestAccAlloydbInstance_networkConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceMaximumFields</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance</li>
<li>TestAccAlloydbInstance_update</li>
<li>TestAccAlloydbInstance_updatePscInstanceConfig</li>
<li>TestAccAlloydbUser_alloydbUserBuiltinTestExample</li>
<li>TestAccAlloydbUser_alloydbUserIamTestExample</li>
<li>TestAccAlloydbUser_updatePassword_BuiltIn</li>
<li>TestAccAlloydbUser_updateRoles_BuiltIn</li>
<li>TestAccAlloydbUser_updateRoles_IAM</li>
<li>TestAccApiGatewayApiConfigIamBindingGenerated</li>
<li>TestAccApiGatewayApiConfigIamMemberGenerated</li>
<li>TestAccApiGatewayApiConfigIamPolicyGenerated</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigBasicExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigBasicExampleUpdated</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigFullExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigGrpcExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigGrpcFullExample</li>
<li>TestAccApiGatewayApiIamBindingGenerated</li>
<li>TestAccApiGatewayApiIamMemberGenerated</li>
<li>TestAccApiGatewayApiIamPolicyGenerated</li>
<li>TestAccApiGatewayApi_apigatewayApiBasicExample</li>
<li>TestAccApiGatewayApi_apigatewayApiBasicExampleUpdated</li>
<li>TestAccApiGatewayApi_apigatewayApiFullExample</li>
<li>TestAccApiGatewayGatewayIamBindingGenerated</li>
<li>TestAccApiGatewayGatewayIamMemberGenerated</li>
<li>TestAccApiGatewayGatewayIamPolicyGenerated</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayBasicExample</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayFullExample</li>
<li>TestAccApigeeAddonsConfig_apigeeAddonsTestExample</li>
<li>TestAccApigeeDeveloper_apigeeDeveloperUpdateTest</li>
<li>TestAccApigeeEnvKeystore_apigeeEnvironmentKeystoreTestExample</li>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTestExample</li>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>
<li>TestAccApigeeEnvironmentIamBindingGenerated</li>
<li>TestAccApigeeEnvironmentIamMemberGenerated</li>
<li>TestAccApigeeEnvironmentIamPolicyGenerated</li>
<li>TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesBetaTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemaps_apigeeEnvironmentKeyvaluemapsBetaTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemaps_apigeeEnvironmentKeyvaluemapsTestExample</li>
<li>TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest</li>
<li>TestAccApigeeSyncAuthorization_apigeeSyncAuthorizationBasicTestExample</li>
<li>TestAccApigeeSyncAuthorization_update</li>
<li>TestAccApigeeTargetServer_apigeeTargetServerTestExample</li>
<li>TestAccApigeeTargetServer_apigeeTargetServerTest_update</li>
<li>TestAccApikeysKey_AndroidKey</li>
<li>TestAccApikeysKey_BasicKey</li>
<li>TestAccApikeysKey_IosKey</li>
<li>TestAccApikeysKey_MinimalKey</li>
<li>TestAccApikeysKey_ServerKey</li>
<li>TestAccAppEngineApplicationUrlDispatchRules_appEngineApplicationUrlDispatchRulesBasicExample</li>
<li>TestAccAppEngineApplication_basic</li>
<li>TestAccAppEngineApplication_withIAP</li>
<li>TestAccAppEngineDomainMapping_appEngineDomainMappingBasicExample</li>
<li>TestAccAppEngineDomainMapping_update</li>
<li>TestAccAppEngineFirewallRule_appEngineFirewallRuleBasicExample</li>
<li>TestAccAppEngineServiceNetworkSettings_appEngineServiceNetworkSettingsExample</li>
<li>TestAccAppEngineServiceNet [...]

2025-01-07 09:40 UTC, karolgorc commented
Need to remove `ConflictsWith` from the image/snapshot comparasion

2025-01-08 22:23 UTC, NickElliot requested changes
sorry for delay with review -- can you resolve the conflict so I cna run tests again? thanks!

2025-01-10 07:53 UTC, karolgorc commented
Some tests were added at the end of the file. Same as mine. Resolved

2025-01-10 21:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2091 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2091 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (357 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    disk_encryption_service_account = # value needed
  }
  boot_disk {
    device_name                     = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      source_image_encryption_key {
        kms_key_service_account = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_service_account = # value needed
      }
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_template` (242 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_template" "primary" {
  disk {
    architecture = # value needed
  }
}


```
Resource: `google_compute_region_instance_template` (76 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_region_instance_template" "primary" {
  disk {
    architecture = # value needed
    disk_encryption_key {
      kms_key_self_link       = # value needed
      kms_key_service_account = # value needed
    }
  }
}


```

2025-01-10 21:50 UTC, modular-magician commented
#### Tests analytics
Total tests: 4436
Passed tests: 37
Skipped tests: 429
Affected tests: 3970

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>

#### Action taken
<details>
<summary>Found 3970 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessApprovalSettings</li>
<li>TestAccAccessContextManager</li>
<li>TestAccAlloydbBackup_alloydbBackupBasicTestExample</li>
<li>TestAccAlloydbBackup_alloydbBackupFullExample</li>
<li>TestAccAlloydbBackup_createBackupWithMandatoryFields</li>
<li>TestAccAlloydbBackup_update</li>
<li>TestAccAlloydbBackup_usingCMEK</li>
<li>TestAccAlloydbCluster_AutomatedBackupPolicyHandlesMidnight</li>
<li>TestAccAlloydbCluster_CMEKInAutomatedBackupIsUpdatable</li>
<li>TestAccAlloydbCluster_addAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_alloydbClusterBasicExample</li>
<li>TestAccAlloydbCluster_alloydbClusterFullExample</li>
<li>TestAccAlloydbCluster_alloydbSecondaryClusterBasicTestExample</li>
<li>TestAccAlloydbCluster_continuousBackup_CMEKIsUpdatable</li>
<li>TestAccAlloydbCluster_continuousBackup_enabledByDefault</li>
<li>TestAccAlloydbCluster_continuousBackup_noChangeIfRemoved</li>
<li>TestAccAlloydbCluster_continuousBackup_update</li>
<li>TestAccAlloydbCluster_continuousBackup_update_noChangeIfDefaultsSet</li>
<li>TestAccAlloydbCluster_deleteAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_deleteTimeBasedRetentionPolicy</li>
<li>TestAccAlloydbCluster_mandatoryFields</li>
<li>TestAccAlloydbCluster_maximumFields</li>
<li>TestAccAlloydbCluster_missingWeeklySchedule</li>
<li>TestAccAlloydbCluster_restore</li>
<li>TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary</li>
<li>TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary</li>
<li>TestAccAlloydbCluster_secondaryClusterMandatoryFields</li>
<li>TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterPromote</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndAddAndDeleteAutomatedBackupPolicyAndInitialUser</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndAddContinuousBackupConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteOriginalPrimary</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndDeleteTimeBasedRetentionPolicy</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndSimultaneousUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteAndUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterPromoteWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_secondaryClusterUpdate</li>
<li>TestAccAlloydbCluster_secondaryClusterUsingCMEK</li>
<li>TestAccAlloydbCluster_secondaryClusterWithNetworkConfig</li>
<li>TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_secondaryInstanceWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_standardClusterUpdate</li>
<li>TestAccAlloydbCluster_standardClusterUpdateFailure</li>
<li>TestAccAlloydbCluster_trialClusterUpdate</li>
<li>TestAccAlloydbCluster_update</li>
<li>TestAccAlloydbCluster_usingCMEK</li>
<li>TestAccAlloydbCluster_withMaintenanceWindows</li>
<li>TestAccAlloydbCluster_withNetworkConfig</li>
<li>TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbCluster_withPrivateServiceConnect</li>
<li>TestAccAlloydbCluster_withSubscriptionTypeStandard</li>
<li>TestAccAlloydbCluster_withSubscriptionTypeTrial</li>
<li>TestAccAlloydbInstance_alloydbInstanceBasicTestExample</li>
<li>TestAccAlloydbInstance_alloydbInstancePscTestExample</li>
<li>TestAccAlloydbInstance_alloydbSecondaryInstanceBasicTestExample</li>
<li>TestAccAlloydbInstance_clientConnectionConfig</li>
<li>TestAccAlloydbInstance_createInstanceWithMandatoryFields</li>
<li>TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange</li>
<li>TestAccAlloydbInstance_createPrimaryAndReadPoolInstance</li>
<li>TestAccAlloydbInstance_networkConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceMaximumFields</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateDatabaseFlag</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateMachineConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceUpdateQueryInsightConfig</li>
<li>TestAccAlloydbInstance_secondaryInstanceWithReadPoolInstance</li>
<li>TestAccAlloydbInstance_update</li>
<li>TestAccAlloydbInstance_updatePscInstanceConfig</li>
<li>TestAccAlloydbUser_alloydbUserBuiltinTestExample</li>
<li>TestAccAlloydbUser_alloydbUserIamTestExample</li>
<li>TestAccAlloydbUser_updatePassword_BuiltIn</li>
<li>TestAccAlloydbUser_updateRoles_BuiltIn</li>
<li>TestAccAlloydbUser_updateRoles_IAM</li>
<li>TestAccApiGatewayApiConfigIamBindingGenerated</li>
<li>TestAccApiGatewayApiConfigIamMemberGenerated</li>
<li>TestAccApiGatewayApiConfigIamPolicyGenerated</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigBasicExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigBasicExampleUpdated</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigFullExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigGrpcExample</li>
<li>TestAccApiGatewayApiConfig_apigatewayApiConfigGrpcFullExample</li>
<li>TestAccApiGatewayApiIamBindingGenerated</li>
<li>TestAccApiGatewayApiIamMemberGenerated</li>
<li>TestAccApiGatewayApiIamPolicyGenerated</li>
<li>TestAccApiGatewayApi_apigatewayApiBasicExample</li>
<li>TestAccApiGatewayApi_apigatewayApiBasicExampleUpdated</li>
<li>TestAccApiGatewayApi_apigatewayApiFullExample</li>
<li>TestAccApiGatewayGatewayIamBindingGenerated</li>
<li>TestAccApiGatewayGatewayIamMemberGenerated</li>
<li>TestAccApiGatewayGatewayIamPolicyGenerated</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayBasicExample</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated</li>
<li>TestAccApiGatewayGateway_apigatewayGatewayFullExample</li>
<li>TestAccApigeeAddonsConfig_apigeeAddonsTestExample</li>
<li>TestAccApigeeDeveloper_apigeeDeveloperUpdateTest</li>
<li>TestAccApigeeEnvKeystore_apigeeEnvironmentKeystoreTestExample</li>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTestExample</li>
<li>TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTest_Update</li>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccApigeeEnvironmentIamBindingGenerated</li>
<li>TestAccApigeeEnvironmentIamMemberGenerated</li>
<li>TestAccApigeeEnvironmentIamPolicyGenerated</li>
<li>TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesBetaTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemapsEntries_apigeeEnvironmentKeyvaluemapsEntriesTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemaps_apigeeEnvironmentKeyvaluemapsBetaTestExample</li>
<li>TestAccApigeeEnvironmentKeyvaluemaps_apigeeEnvironmentKeyvaluemapsTestExample</li>
<li>TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest</li>
<li>TestAccApigeeSyncAuthorization_apigeeSyncAuthorizationBasicTestExample</li>
<li>TestAccApigeeSyncAuthorization_update</li>
<li>TestAccApigeeTargetServer_apigeeTargetServerTestExample</li>
<li>TestAccApigeeTargetServer_apigeeTargetServerTest_update</li>
<li>TestAccApikeysKey_AndroidKey</li>
<li>TestAccApikeysKey_BasicKey</li>
<li>TestAccApikeysKey_IosKey</li>
<li>TestAccApikeysKey_MinimalKey</li>
<li>TestAccApikeysKey_ServerKey</li>
<li>TestAccAppEngineApplicationUrlDispatchRules_appEngineApplicationUrlDispatchRulesBasicExample</li>
<li>TestAccAppEngineApplication_basic</li>
<li>TestAccAppEngineApplication_withIAP</li>
<li>TestAccAppEngineDomainMapping_appEngineDomainMappingBasicExample</li>
<li>TestAccAppEngineDomainMapping_update</li>
<li>TestAccAppEngineFirewallRule_appEngineFirewallRuleBasicExample</li>
<li>TestAccAppEngineServiceNetworkS [...]

2025-01-13 08:42 UTC, karolgorc commented
I'm seeing the internal validate fail on `ConflictsWith` again which is weird because it works locally for me. Will remove them all together for now and resolve this after we get this to build.

2025-01-16 18:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2085 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 17 files changed, 2085 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (357 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    disk_encryption_service_account = # value needed
  }
  boot_disk {
    device_name                     = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      source_image_encryption_key {
        kms_key_service_account = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_service_account = # value needed
      }
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_template` (242 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_template" "primary" {
  disk {
    architecture = # value needed
  }
}


```
Resource: `google_compute_region_instance_template` (76 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_region_instance_template" "primary" {
  disk {
    architecture = # value needed
    disk_encryption_key {
      kms_key_self_link       = # value needed
      kms_key_service_account = # value needed
    }
  }
}


```

2025-01-16 20:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 3654
Passed tests: 3235
Skipped tests: 412
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccComputeInstanceTemplate_GuestOsFeatures
- TestAccComputeInstance_guestOsFeatures
- TestAccComputeInstance_imageEncryption
- TestAccComputeInstance_instanceEncryption
- TestAccComputeInstance_snapshot
- TestAccComputeInstance_snapshotEncryption
- TestAccComputeRegionInstanceTemplate_GuestOsFeatures
#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest</li>
<li>TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey</li>
<li>TestAccComputeRegionInstanceTemplate_sourceSnapshotEncryptionKey</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccStorageTransferReplicationJob_basic</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-16 20:19 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccComputeRegionInstanceTemplate_sourceImageEncryptionKey.log)]
`TestAccComputeRegionInstanceTemplate_sourceSnapshotEncryptionKey` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccComputeRegionInstanceTemplate_sourceSnapshotEncryptionKey.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccStorageTransferReplicationJob_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccStorageTransferReplicationJob_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/replaying_build_after_recording/TestAccStorageTransferReplicationJob_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/replaying_after_recording/TestAccStorageTransferReplicationJob_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/recording_build/TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccApigeeEnvironment_apigeeEnvironmentUpdateTest.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording/TestAccEphemeralServiceAccountKey_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/209a3224-4420-4ad1-8e40-51848f40c2db/recording) for each test

2025-01-17 08:07 UTC, karolgorc commented
Could these be affected by the PR? I've looked through the configs and none of them contain any resources changed in this PR

2025-01-17 20:15 UTC, NickElliot reviewed
whats here LGTM, will pass over again when the missing tests are done!

2025-01-22 11:06 UTC, karolgorc commented
Do we want separate tests for these resources? This will be a copy-paste from the normal instance as they use the same functions
- google_compute_instance_from_machine_image
- google_compute_instance_from_template

2025-01-24 22:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2217 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2217 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (358 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  attached_disk {
    disk_encryption_service_account = # value needed
  }
  boot_disk {
    initialize_params {
      enable_confidential_compute = # value needed
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```

2025-01-24 23:25 UTC, modular-magician commented
#### Tests analytics
Total tests: 3889
Passed tests: 3465
Skipped tests: 417
Affected tests: 7

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccComputeInstanceTemplate_GuestOsFeatures
- TestAccComputeInstance_guestOsFeatures
- TestAccComputeInstance_imageEncryption
- TestAccComputeInstance_instanceEncryption
- TestAccComputeInstance_rsaBootDiskEncryption
- TestAccComputeInstance_snapshot
- TestAccComputeInstance_snapshotEncryption
#### Action taken
<details>
<summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccComputeRegionInstanceTemplate_GuestOsFeatures</li>
<li>TestAccComputeRegionInstanceTemplate_diskEncryptionKey</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample</li>
<li>TestAccTpuV2Vm_update</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-24 23:50 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccComputeRegionInstanceTemplate_GuestOsFeatures` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccComputeRegionInstanceTemplate_GuestOsFeatures.log)]
`TestAccComputeRegionInstanceTemplate_diskEncryptionKey` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccComputeRegionInstanceTemplate_diskEncryptionKey.log)]
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccTpuV2Vm_update` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccTpuV2Vm_update.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/build-log/recording_build/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/d4a24021-715c-4a0c-9d75-34abd94c67a4/recording) for each test

2025-01-27 18:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2222 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2222 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (358 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  boot_disk {
    initialize_params {
      enable_confidential_compute = # value needed
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```

2025-01-27 20:05 UTC, modular-magician commented
#### Tests analytics
Total tests: 3881
Passed tests: 3461
Skipped tests: 416
Affected tests: 4

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccComputeInstanceTemplate_GuestOsFeatures
- TestAccComputeInstance_guestOsFeatures
- TestAccComputeInstance_imageEncryption
- TestAccComputeInstance_instanceEncryption
- TestAccComputeInstance_rsaBootDiskEncryption
- TestAccComputeInstance_snapshot
- TestAccComputeInstance_snapshotEncryption
#### Action taken
<details>
<summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-01-27 20:17 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/recording/TestAccEphemeralServiceAccountKey_basic.log)]
`TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/build-log/recording_build/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/recording/TestAccNetworkSecurityAuthzPolicy_networkServicesAuthzPolicyAdvancedExample.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/e0a44b56-3e00-4d88-a2a5-ca4aa2c5a2de/recording) for each test

2025-01-28 11:43 UTC, karolgorc commented
In addition to the previous questions, why does this unit test fail? It's the first time i'm adding a field and seeing this. This test is not a part of the provider so no idea how should i update it to account for the new fields.

![image](https://github.com/user-attachments/assets/91f259c5-8011-46ba-bd22-bff5fe7686e2)

This also fails in here https://github.com/GoogleCloudPlatform/magic-modules/pull/12819

2025-01-30 21:56 UTC, NickElliot reviewed
sorry for the review delay, I thought I commented last week. it would be fine to not add extra tests for the `from_template` and similar clone resources. if they're tested in the main resource, all is well.

as for the TGC test, I've reached out to see how these can be updated in parallel, the failing tests are in the following file: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/main/tfplan2cai/tfdata/fake_resource_data_test.go , but we don't have a recent history of modifying it so I'm seeing what precedent is.

2025-02-11 23:07 UTC, melinath requested changes
Drive-by change request:

@karolgorc it looks like this has some conflicts that need to be resolved

Regarding TGC: We should make the file be managed by MM in this PR so that it can be modified at the same time. This would mean copying the files in that directory over to `mmv1/third_party/tgc/tfdata/*` and adding them to the list at https://github.com/GoogleCloudPlatform/magic-modules/blob/08e279e85de5fdbfd14c7f16462c390b6edd029c/mmv1/provider/terraform_tgc.go#L344

2025-02-11 23:42 UTC, melinath commented
Please disregard my previous message regarding TGC - talked with @NickElliot & that's being handled separately.

2025-02-11 23:45 UTC, NickElliot requested changes
Hi there, sorry for the delay here but we'll proceed with merging this PR despite the downstream failure and have that resolved with some other maintenance work.

Can you resolve the conflicts? Once that is done all should be good!

2025-02-13 22:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2218 insertions(+), 58 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-12672-old..auto-pr-12672) ( 19 files changed, 2218 insertions(+), 58 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-12672-old..auto-pr-12672) ( 3 files changed, 119 insertions(+))



## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance` (359 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance" "primary" {
  boot_disk {
    initialize_params {
      enable_confidential_compute = # value needed
    }
  }
}


```
Resource: `google_compute_instance_from_machine_image` (12 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture = # value needed
      snapshot     = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
    }
    kms_key_self_link = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```
Resource: `google_compute_instance_from_template` (20 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  attached_disk {
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    kms_key_self_link               = # value needed
  }
  boot_disk {
    auto_delete                     = # value needed
    device_name                     = # value needed
    disk_encryption_key_raw         = # value needed
    disk_encryption_key_rsa         = # value needed
    disk_encryption_service_account = # value needed
    guest_os_features               = # value needed
    initialize_params {
      architecture                = # value needed
      enable_confidential_compute = # value needed
      image                       = # value needed
      labels                      = # value needed
      provisioned_iops            = # value needed
      provisioned_throughput      = # value needed
      resource_manager_tags       = # value needed
      resource_policies           = # value needed
      size                        = # value needed
      snapshot                    = # value needed
      source_image_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      source_snapshot_encryption_key {
        kms_key_self_link       = # value needed
        kms_key_service_account = # value needed
        raw_key                 = # value needed
        rsa_encrypted_key       = # value needed
      }
      storage_pool = # value needed
      type         = # value needed
    }
    kms_key_self_link = # value needed
    mode              = # value needed
  }
  instance_encryption_key {
    kms_key_self_link       = # value needed
    kms_key_service_account = # value needed
  }
}


```

2025-02-13 23:49 UTC, modular-magician commented
#### Tests analytics
Total tests: 3801
Passed tests: 3384
Skipped tests: 411
Affected tests: 6

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

🔴 Tests were added that are skipped in VCR:
- TestAccComputeInstanceTemplate_GuestOsFeatures
- TestAccComputeInstance_guestOsFeatures
- TestAccComputeInstance_imageEncryption
- TestAccComputeInstance_instanceEncryption
- TestAccComputeInstance_rsaBootDiskEncryption
- TestAccComputeInstance_snapshot
- TestAccComputeInstance_snapshotEncryption
#### Action taken
<details>
<summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccAccessContextManager</li>
<li>TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample</li>
<li>TestAccCloudbuildWorkerPool_basic</li>
<li>TestAccDataSourceGoogleGkeHubFeature_basic</li>
<li>TestAccEphemeralServiceAccountKey_basic</li>
<li>TestAccSpannerInstance_spannerInstanceWithAutoscaling</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/develop/test/test/)

2025-02-14 00:02 UTC, modular-magician commented
🟢 Tests passed during RECORDING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccSpannerInstance_spannerInstanceWithAutoscaling` [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccSpannerInstance_spannerInstanceWithAutoscaling.log)]


🔴 Tests failed when rerunning REPLAYING mode:
`TestAccDataSourceGoogleGkeHubFeature_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/replaying_build_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/replaying_after_recording/TestAccDataSourceGoogleGkeHubFeature_basic.log)]
`TestAccSpannerInstance_spannerInstanceWithAutoscaling` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/replaying_build_after_recording/TestAccSpannerInstance_spannerInstanceWithAutoscaling_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/replaying_after_recording/TestAccSpannerInstance_spannerInstanceWithAutoscaling.log)]


Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.


---


🔴 Tests failed during RECORDING mode:
`TestAccAccessContextManager` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/recording_build/TestAccAccessContextManager_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccAccessContextManager.log)]
`TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/recording_build/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccApigeeEnvironmentAddonsConfig_apigeeEnvAddonsAnalyticsTestExample.log)]
`TestAccCloudbuildWorkerPool_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/recording_build/TestAccCloudbuildWorkerPool_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccCloudbuildWorkerPool_basic.log)]
`TestAccEphemeralServiceAccountKey_basic` [[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/recording_build/TestAccEphemeralServiceAccountKey_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording/TestAccEphemeralServiceAccountKey_basic.log)]



🔴 Errors occurred during RECORDING mode. Please fix them to complete your PR.



View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-12672/artifacts/6fb1c377-c631-4b29-9891-408a6059f100/recording) for each test

2025-02-14 00:24 UTC, NickElliot approved these changes
test failures verified unrelated to this PR, TGC test to be handled seperately.

LGTM!

2025-02-14 00:39 UTC, merged