Mark Workload Identity as GA fully.
GoogleCloudPlatform/magic-modules pull request #3941
Opened 2020-09-02 19:38 UTC by upodroid

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/5916

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: marked `workload_metadata_config` as GA in `google_container_node_pool`
```

2020-09-02 19:40 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@megan07, please review this PR or find an appropriate assignee.

2020-09-02 19:46 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3941-old..auto-pr-3941) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3941-old..auto-pr-3941) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2020-09-02 19:49 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3941-old..auto-pr-3941) ( 4 files changed, 173 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3941-old..auto-pr-3941) ( 2 files changed, 2 insertions(+), 1 deletion(-))

2020-09-03 16:32 UTC, megan07 requested changes
Hi @upodroid! Thank you for contributing! With the suggested changes I will run the tests in GA and we can get this merged. As you're making the changes, would you keep an eye out for excess white space and clean that up as well?  Thanks again!

2020-09-03 16:32 UTC, megan07 commented on third_party/terraform/resources/resource_container_node_pool.go.erb
> +
We can probably clean up the extra whitespace here.

2020-09-03 16:32 UTC, megan07 commented on third_party/terraform/utils/node_config.go.erb
>  func expandWorkloadMetadataConfig(v interface{}) *containerBeta.WorkloadMetadataConfig {
I think we need to address the flatten methods for `WorkloadMetadataConfig` as well.

2020-09-03 16:32 UTC, megan07 commented on third_party/terraform/website/docs/r/container_cluster.html.markdown
> +* `workload_identity_config` - (Optional)
Should we remove the `Beta` portion from `workload_metadata_config` as well?

2020-09-03 18:12 UTC, upodroid commented
I fixed the issues. Slow test

```
 REDACTED  MCW0CDP3YY  ~  go  …  github.com  hashicorp  terraform-provider-google   master  31⬇  7✎  USAGE  $    make testacc TEST=./google TESTARGS='-run=TestAccContainerNodePool_withWorkloadIdentityConfig'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccContainerNodePool_withWorkloadIdentityConfig -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccContainerNodePool_withWorkloadIdentityConfig
=== PAUSE TestAccContainerNodePool_withWorkloadIdentityConfig
=== CONT  TestAccContainerNodePool_withWorkloadIdentityConfig
--- PASS: TestAccContainerNodePool_withWorkloadIdentityConfig (1675.70s)
PASS
ok      github.com/hashicorp/terraform-provider-google/google   1677.993s
```

2020-09-03 18:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3941-old..auto-pr-3941) ( 4 files changed, 185 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3941-old..auto-pr-3941) ( 3 files changed, 3 insertions(+), 3 deletions(-))

2020-09-03 19:05 UTC, megan07 approved these changes
LGTM! Thank you!

2020-09-03 19:05 UTC, merged