[resource_container_cluster] - Add self-link property
GoogleCloudPlatform/magic-modules pull request #3942
Opened 2020-09-02 21:32 UTC by ScottSuarez

Add self link property to resource_container_cluster. 

Resolves [7120](https://github.com/hashicorp/terraform-provider-google/issues/7120)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Added self_link to google_container_cluster
```

2020-09-02 21:33 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@megan07, please review this PR or find an appropriate assignee.

2020-09-02 21:39 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3942-old..auto-pr-3942) ( 1 file changed, 75 insertions(+), 60 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3942-old..auto-pr-3942) ( 1 file changed, 101 insertions(+), 89 deletions(-))

2020-09-03 16:40 UTC, megan07 requested changes
Hi @ScottSuarez! Were you able to build this locally? If you need any help with that, feel free to reach out!

2020-09-03 16:40 UTC, megan07 commented on third_party/terraform/resources/resource_container_cluster.go.erb
> +			}
I think we want a comma after this here.

2020-09-03 17:10 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3942-old..auto-pr-3942) ( 1 file changed, 7 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3942-old..auto-pr-3942) ( 1 file changed, 7 insertions(+), 2 deletions(-))

2020-09-03 17:16 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3942-old..auto-pr-3942) ( 2 files changed, 13 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3942-old..auto-pr-3942) ( 2 files changed, 13 insertions(+), 6 deletions(-))

2020-09-03 17:37 UTC, megan07 approved these changes
Looks good! Thanks for cleaning up the whitespace. Do you think we should add a test in for this?

2020-09-03 18:52 UTC, ScottSuarez commented
> Looks good! Thanks for cleaning up the whitespace. Do you think we should add a test in for this?

It certainly couldn't hurt! I added the property validation to an existing basic test and ran it locally.

2020-09-03 18:58 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3942-old..auto-pr-3942) ( 3 files changed, 15 insertions(+), 7 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3942-old..auto-pr-3942) ( 3 files changed, 15 insertions(+), 7 deletions(-))

2020-09-03 19:04 UTC, merged