Added options & artifacts to google_cloudbuild_trigger
GoogleCloudPlatform/magic-modules pull request #3944
Opened 2020-09-02 22:29 UTC by edwardmedia

Fixes https://github.com/GoogleCloudPlatform/magic-modules/pull/3943

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Added options & artifacts to google_cloudbuild_trigger
```

2020-09-02 22:30 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@ndmckinley, please review this PR or find an appropriate assignee.

2020-09-02 22:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3944-old..auto-pr-3944) ( 3 files changed, 866 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3944-old..auto-pr-3944) ( 3 files changed, 865 insertions(+), 1 deletion(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-3944-old..auto-pr-3944) ( 2 files changed, 703 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 296 insertions(+))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-3944-old..auto-pr-3944) ( 8 files changed, 312 insertions(+))

2020-09-02 22:37 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=144151"

2020-09-02 23:01 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccContainerClusterDatasource_zonal|TestAccContainerClusterDatasource_regional|TestAccComputeDiskIamBindingGenerated|TestAccComputeDiskIamMemberGenerated|TestAccComputeImageIamBindingGenerated|TestAccComputeDiskIamPolicyGenerated|TestAccComputeImageIamMemberGenerated|TestAccComputeImageIamMemberGenerated_withCondition|TestAccComputeImageIamBindingGenerated_withCondition|TestAccComputeInstanceIamBindingGenerated|TestAccComputeInstanceIamMemberGenerated|TestAccComputeImageIamPolicyGenerated|TestAccComputeImageIamPolicyGenerated_withCondition|TestAccComputeInstanceIamBindingGenerated_withCondition|TestAccComputeInstanceIamMemberGenerated_withCondition|TestAccComputeRegionDiskIamMemberGenerated|TestAccComputeRegionDiskIamBindingGenerated|TestAccComputeInstanceIamPolicyGenerated|TestAccComputeSubnetworkIamBindingGenerated|TestAccComputeSubnetworkIamMemberGenerated|TestAccComputeSubnetworkIamBindingGenerated_withCondition|TestAccComputeInstanceIamPolicyGenerated_withCondition|TestAccComputeSubnetworkIamMemberGenerated_withCondition|TestAccComputeRegionDiskIamPolicyGenerated|TestAccComputeSubnetworkIamPolicyGenerated|TestAccComputeSubnetworkIamPolicyGenerated_withCondition|TestAccIapTunnelInstanceIamBindingGenerated|TestAccIapTunnelInstanceIamMemberGenerated|TestAccIapTunnelInstanceIamBindingGenerated_withCondition|TestAccIapTunnelInstanceIamMemberGenerated_withCondition|TestAccIapTunnelInstanceIamPolicyGenerated|TestAccIapWebBackendServiceIamBindingGenerated|TestAccIapWebBackendServiceIamMemberGenerated|TestAccIapTunnelInstanceIamPolicyGenerated_withCondition|TestAccIapWebBackendServiceIamBindingGenerated_withCondition|TestAccIapWebBackendServiceIamMemberGenerated_withCondition|TestAccIapWebBackendServiceIamPolicyGenerated|TestAccIapWebBackendServiceIamPolicyGenerated_withCondition|TestAccProviderBasePath_setBasePath|TestAccCloudBuildTrigger_basic|TestAccCloudBuildTrigger_disable|TestAccComposerEnvironment_basic|TestAccComposerEnvironment_private|TestAccComposerEnvironment_privateWithWebServerControl|TestAccComposerEnvironment_withDatabaseConfig|TestAccComposerEnvironment_update|TestAccComposerEnvironment_withWebServerConfig|TestAccComputeAddress_addressBasicExample|TestAccComputeAddress_addressWithSubnetworkExample|TestAccComputeAddress_addressWithGceEndpointExample|TestAccComposerEnvironment_withUpdateOnCreate|TestAccComposerEnvironment_withSoftwareConfig|TestAccCloudFunctionsFunction_vpcConnector|TestAccComputeAddress_addressWithSharedLoadbalancerVipExample|TestAccComputeAddress_networkTier|TestAccComputeAddress_instanceWithIpExample|TestAccComputeAddress_internal|TestAccComputeAttachedDisk_full|TestAccComputeAttachedDisk_region|TestAccComputeAttachedDisk_basic|TestAccComputeAttachedDisk_count|TestAccComputeAutoscaler_autoscalerBasicExample|TestAccComputeAutoscaler_autoscalerSingleInstanceExample|TestAccComputeBackendBucketSignedUrlKey_basic|TestAccComputeAutoscaler_update|TestAccComputeAutoscaler_scaleDownControl|TestAccComputeAutoscaler_multicondition|TestAccComputeBackendBucket_backendBucketBasicExample|TestAccComputeBackendBucket_basicModified|TestAccComputeBackendService_backendServiceBasicExample|TestAccComputeBackendService_backendServiceNetworkEndpointExample|TestAccComputeBackendService_updatePreservesOptionalParameters|TestAccComputeBackendBucket_withCdnPolicy|TestAccComputeBackendService_basic|TestAccComputeBackendService_backendServiceTrafficDirectorRoundRobinExample|TestAccComputeBackendService_backendServiceTrafficDirectorRingHashExample|TestAccComposerEnvironment_withNodeConfig|TestAccComputeBackendService_withConnectionDraining|TestAccComputeBackendServiceSignedUrlKey_basic|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withConnectionDrainingAndUpdate|TestAccComputeBackendService_withHttpsHealthCheck|TestAccComputeBackendService_withCdnPolicy|TestAccComputeBackendService_withSecurityPolicy|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withCDNEnabled|TestAccComputeBackendService_withAffinityCookieTtlSec|TestAccComputeBackendService_withSessionAffinity|TestAccComputeBackendService_withCustomHeaders|TestAccComputeBackendService_trafficDirectorUpdateBasic|TestAccComputeBackendService_withLogConfig|TestAccComputeBackendService_trafficDirectorUpdateFull|TestAccComputeDisk_diskBasicExample|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxRatePerEndpoint|TestAccComputeBackendService_withMaxConnectionsPerEndpoint|TestAccComputeDisk_VSSWindows|TestAccComputeBackendService_internalLoadBalancing|TestAccComputeDiskResourcePolicyAttachment_diskResourcePolicyAttachmentBasicExample You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=144153"

2020-09-02 23:47 UTC, danawillow requested changes

2020-09-02 23:47 UTC, danawillow commented on products/cloudbuild/api.yaml
> +                      (see Bucket Name Requirements).
I'd recommend either getting rid of this line or adding the place this links to. Right now standing alone it's not adding much value.

2020-09-02 23:47 UTC, danawillow commented on products/cloudbuild/api.yaml
> +                    description: |
Since this is output-only, it should be marked `output: true` (and its properties also should)

2020-09-02 23:47 UTC, danawillow commented on third_party/terraform/tests/resource_cloudbuild_trigger_test.go
> +        timing {
Isn't this field output-only? There's plenty of other fields that are settable that would be good to see in a test :)

2020-09-02 23:47 UTC, danawillow commented on third_party/terraform/tests/resource_cloudbuild_trigger_test.go
> +    artifacts {
In addition to this test, I'd recommend also adding these new fields to the cloudbuild_trigger_build.tf.erb example.

2020-09-03 17:44 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 909 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 908 insertions(+), 1 deletion(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-3944-old..auto-pr-3944) ( 2 files changed, 658 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 296 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 24 insertions(+))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-3944-old..auto-pr-3944) ( 8 files changed, 312 insertions(+))

2020-09-03 17:44 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=144392"

2020-09-03 18:13 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccCloudBuildTrigger_cloudbuildTriggerBuildExample|TestAccCloudBuildTrigger_basic|TestAccCloudBuildTrigger_disable|TestAccComposerEnvironment_private|TestAccComposerEnvironment_update|TestAccComposerEnvironment_withDatabaseConfig|TestAccComposerEnvironment_withWebServerConfig|TestAccComputeDisk_VSSWindows|TestAccComputeHttpHealthCheck_update|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_versions|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_stateful|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccDataprocCluster_withInternalIpOnlyTrue|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSManagedZone_privateUpdate|TestAccDNSManagedZone_dnsManagedZoneServiceDirectoryExample|TestAccDNSManagedZone_privateForwardingUpdate|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSManagedZone_reverseLookup|TestAccDNSPolicy_update|TestAccDNSRecordSet_basic|TestAccDNSRecordSet_modify|TestAccDNSRecordSet_changeType|TestAccDNSRecordSet_ns|TestAccDNSRecordSet_nestedNS|TestAccDNSRecordSet_quotedTXT|TestAccDNSRecordSet_uppercaseMX|TestAccSecurityScannerScanConfig_scanConfigUpdate|TestAccProject_deleteDefaultNetwork|TestAccMemcacheInstance_update|TestAccMemcacheInstance_memcacheInstanceBasicExample|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccNetworkManagementConnectivityTest_update|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccRedisInstance_redisInstancePrivateServiceExample|TestAccSecurityScannerScanConfig_scanConfigBasicExample|TestAccServiceNetworkingConnection_create|TestAccServiceNetworkingConnection_update|TestAccSqlDatabaseInstance_withPrivateNetwork You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=144393"

2020-09-03 20:43 UTC, danawillow commented on products/cloudbuild/api.yaml
> +                        name: 'startTime'
This and endTime also need to be marked output: true. You can see at https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3944-old..auto-pr-3944#diff-f0c51a3d504e195b74aeb122b2747c9eR302-R317 that it isn't automatic.

2020-09-04 15:39 UTC, edwardmedia commented on templates/terraform/examples/cloudbuild_trigger_build.tf.erb
> +      dynamic_substitutions = true
Updated as suggested. But this particular property only supports `false` to `true`, not `true` to `false` by design

2020-09-04 15:41 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 926 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 925 insertions(+), 1 deletion(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-3944-old..auto-pr-3944) ( 2 files changed, 658 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 296 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 24 insertions(+))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-3944-old..auto-pr-3944) ( 8 files changed, 312 insertions(+))

2020-09-04 15:41 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=144617"

2020-09-04 16:33 UTC, edwardmedia commented
`tpg-vcr-test` failed. Need to extend timeout again?

2020-09-07 13:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 926 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3944-old..auto-pr-3944) ( 4 files changed, 925 insertions(+), 1 deletion(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-3944-old..auto-pr-3944) ( 2 files changed, 658 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 296 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-3944-old..auto-pr-3944) ( 1 file changed, 24 insertions(+))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-3944-old..auto-pr-3944) ( 8 files changed, 312 insertions(+))

2020-09-07 13:22 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=145003"

2020-09-07 13:51 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccCloudBuildTrigger_basic|TestAccCloudBuildTrigger_disable|TestAccComposerEnvironment_update|TestAccComposerEnvironment_withDatabaseConfig|TestAccComputeDisk_VSSWindows|TestAccComputeSnapshot_encryptionCMEK You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=145005"

2020-09-09 23:27 UTC, danawillow commented on products/cloudbuild/api.yaml
> +                        name: 'startTime'
I'm not sure what you mean by that. I just tried setting `output: true` on them locally and it did exactly what I expected:
```
                  - !ruby/object:Api::Type::NestedObject
                    name: 'timing'
                    description: |
                      Output only. Stores timing information for pushing all artifact objects.
                    output: true
                    properties:
                      - !ruby/object:Api::Type::String
                        name: 'startTime'
                        output: true
                        description: |
                          Start of time span.

                          A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to
                          nine fractional digits. Examples: "2014-10-02T15:01:23Z" and "2014-10-02T15:01:23.045123456Z".
                      - !ruby/object:Api::Type::String
                        name: 'endTime'
                        output: true
                        description: |
                          End of time span.

                          A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to
                          nine fractional digits. Examples: "2014-10-02T15:01:23Z" and "2014-10-02T15:01:23.045123456Z".
```

2020-09-15 23:17 UTC, danawillow approved these changes

2020-09-15 23:31 UTC, merged