Allow updates to composer webserver and database.
GoogleCloudPlatform/magic-modules pull request #3953
Opened 2020-09-06 04:42 UTC by jmcarp

The composer api allows in-place updates to webserver and database machine types, and the provider implements those updates. But because both properties are marked `ForceNew`, the update code is unreachable. This patch drops the `ForceNew` flags for these properties.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:release-note:enhancement
composer: allow in-place updates to webserver and database machine type
```

2020-09-06 04:43 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@megan07, please review this PR or find an appropriate assignee.

2020-09-06 04:49 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3953-old..auto-pr-3953) ( 1 file changed, 2 deletions(-))

2020-09-06 04:52 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* release-note:enhancement

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2020-09-07 01:11 UTC, jmcarp commented
* The generated code made some changes I didn't expect and that broke tests. I manually updated the two lines that are supposed to change in the generated code, and `make test` passed.
* I haven't had a chance to run the acceptance tests.

2020-09-08 15:58 UTC, megan07 requested changes
Hi @jmcarp! Thanks for finding this and fixing it, we appreciate it! I think we'll want to do a little more here. I was surprised to see we have update code implemented for it (lines [676](https://github.com/GoogleCloudPlatform/magic-modules/blob/5c917e5a13eb7bf4bcf2950ad54a2fe6109409ef/third_party/terraform/resources/resource_composer_environment.go.erb#L676) & [688](https://github.com/GoogleCloudPlatform/magic-modules/blob/5c917e5a13eb7bf4bcf2950ad54a2fe6109409ef/third_party/terraform/resources/resource_composer_environment.go.erb#L688) in this file), but it never got to it because we had `ForceNew` there.
However, I also noticed that what we have implemented in those lines is incorrect - as you can see in the API, [`updateMask` only accepts a subset of values](https://cloud.google.com/composer/docs/reference/rest/v1beta1/projects.locations.environments/patch#query-parameters) and `config.databaseConfig` and `config.webServerConfig` need to include `machineType` at the end of their paths. I'd also include `machine_type` at the end of the `HasChange` paths as well. I think if you update those we should be good. Let me know if you have any questions, I'd be happy to help!
I'm also happy to run the acceptance tests for you! Thanks again!

2020-09-15 17:01 UTC, jmcarp commented
Thanks @megan07, I updated the masks and paths.

2020-09-15 17:07 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3953-old..auto-pr-3953) ( 1 file changed, 4 insertions(+), 6 deletions(-))

2020-09-15 17:16 UTC, megan07 commented
/gcbrun

2020-09-15 17:24 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3953-old..auto-pr-3953) ( 1 file changed, 4 insertions(+), 6 deletions(-))

2020-09-15 19:14 UTC, megan07 commented
Hi @jmcarp! Thank you! This looks good - in order to run the tests, could you please rebase off of master? We recently started a new process for testing things, and the changes we need are in master.  Sorry about that!

2020-09-15 19:45 UTC, megan07 commented
/gcbrun

2020-09-15 19:46 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=146602"

2020-09-15 19:47 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3953-old..auto-pr-3953) ( 1 file changed, 4 insertions(+), 6 deletions(-))

2020-09-15 19:52 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-3953-old..auto-pr-3953) ( 1 file changed, 4 insertions(+), 6 deletions(-))

2020-09-16 16:17 UTC, megan07 approved these changes
LGTM!  Thanks!

2020-09-16 16:18 UTC, merged