Promote Managed SSL to GA + Doc fixes
GoogleCloudPlatform/magic-modules pull request #4247
Opened 2020-11-17 23:51 UTC by upodroid

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7828
Fixes: https://github.com/hashicorp/terraform-provider-google/issues/7832

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: promoted `google_compute_managed_ssl_certificate` to GA
```

2020-11-17 23:52 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@c2thorn, please review this PR or find an appropriate assignee.

2020-11-18 17:26 UTC, c2thorn commented
/gcbrun

2020-11-18 17:26 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=158668"

2020-11-18 21:19 UTC, c2thorn commented
/gcbrun

2020-11-18 21:19 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=158685"

2020-11-18 22:11 UTC, c2thorn requested changes
Moving this to GA caused MM to try to generate this for Ansible. I believe it needs to be excluded here: 
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/compute/ansible.yaml#L327

2020-11-18 22:20 UTC, upodroid commented
Ah, that explains why generate-diffs was broken

2020-11-18 23:07 UTC, c2thorn commented
/gcbrun

2020-11-18 23:08 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=158690"

2020-11-18 23:30 UTC, c2thorn requested changes

2020-11-18 23:41 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4247-old..auto-pr-4247) ( 8 files changed, 830 insertions(+), 27 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4247-old..auto-pr-4247) ( 5 files changed, 22 insertions(+), 48 deletions(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-4247-old..auto-pr-4247) ( 2 files changed, 6 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 103 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-4247-old..auto-pr-4247) ( 3 files changed, 1 insertion(+), 21 deletions(-))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2020-11-18 23:49 UTC, upodroid commented on products/compute/ansible.yaml
> +  ManagedSslCertificate: !ruby/object:Overrides::Ansible::ResourceOverride
Oopsie, ficed

2020-11-19 16:34 UTC, c2thorn requested changes
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/third_party/terraform/utils/common_diff_suppress.go.erb#L140 needs to be made available for GA as well, the build is failing because of this

2020-11-23 15:23 UTC, upodroid commented
I fixed and tested it properly

2020-11-23 15:32 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4247-old..auto-pr-4247) ( 9 files changed, 833 insertions(+), 32 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4247-old..auto-pr-4247) ( 5 files changed, 22 insertions(+), 58 deletions(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-4247-old..auto-pr-4247) ( 2 files changed, 6 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 103 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-4247-old..auto-pr-4247) ( 3 files changed, 1 insertion(+), 26 deletions(-))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2020-12-01 19:15 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4247-old..auto-pr-4247) ( 9 files changed, 833 insertions(+), 32 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4247-old..auto-pr-4247) ( 5 files changed, 22 insertions(+), 58 deletions(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-4247-old..auto-pr-4247) ( 2 files changed, 6 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 103 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-4247-old..auto-pr-4247) ( 3 files changed, 1 insertion(+), 26 deletions(-))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2020-12-01 22:02 UTC, c2thorn commented
/gcbrun

2020-12-01 22:03 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=160869"

2020-12-01 22:04 UTC, c2thorn approved these changes

2020-12-01 22:11 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4247-old..auto-pr-4247) ( 9 files changed, 833 insertions(+), 32 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4247-old..auto-pr-4247) ( 5 files changed, 22 insertions(+), 58 deletions(-))
Ansible: [Diff](https://github.com/modular-magician/google.cloud/compare/auto-pr-4247-old..auto-pr-4247) ( 2 files changed, 6 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 103 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-4247-old..auto-pr-4247) ( 3 files changed, 1 insertion(+), 26 deletions(-))
Inspec: [Diff](https://github.com/modular-magician/inspec-gcp/compare/auto-pr-4247-old..auto-pr-4247) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2020-12-01 23:34 UTC, c2thorn commented
@upodroid thanks for your patience on this, but I think we are at a good point now.

2020-12-01 23:37 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataSourceComposerEnvironment_basic|TestAccDataSourceSpannerInstance_basic|TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample|TestAccBigqueryDataTransferConfig|TestAccCloudSchedulerJob_schedulerJobHttpExample|TestAccComposerEnvironment_withUpdateOnCreate|TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample|TestAccFilestoreInstance_filestoreInstanceBasicExample|TestAccFilestoreInstance_update|TestAccOSLoginSSHPublicKey_osLoginSshKeyExpiry You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=160874"

2020-12-01 23:37 UTC, merged