Add status to bigquery_job
GoogleCloudPlatform/magic-modules pull request #4455
Opened 2021-02-02 18:09 UTC by kanterov

Fixes https://github.com/hashicorp/terraform-provider-google/issues/8357

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2021-02-02 18:10 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@slevenick, please review this PR or find an appropriate assignee.

2021-02-02 18:12 UTC, kanterov commented on mmv1/products/bigquery/api.yaml
> +        output: true
Not sure if this is needed. Because of that terraform generator doesn't set `maxItems: 1`

2021-02-02 18:13 UTC, kanterov commented
@googlebot I signed it!

2021-02-02 18:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 138 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 138 insertions(+))

2021-02-02 18:20 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2021-02-02 20:45 UTC, slevenick reviewed
/gcbrun

Rerunning jobs as release note is fixed now

2021-02-02 20:46 UTC, slevenick commented
/gcbrun

Apparently review comments don't trigger this

2021-02-02 20:46 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170550"

2021-02-02 20:54 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 138 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 138 insertions(+))

2021-02-02 22:01 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample|TestAccBigQueryJob_bigqueryJobQueryTableReferenceExample|TestAccBigQueryJob_bigqueryJobQueryExample|TestAccBigQueryJob_bigqueryJobLoadExample|TestAccBigQueryJob_withLocation|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170552"

2021-02-02 22:24 UTC, kanterov commented
I fixed my setup so I can run tests locally and now I can see what's wrong. Fixing it now and going to update the code soon.

2021-02-02 22:26 UTC, slevenick requested changes
Looks like this causes a panic during the bigquery tests:

```
panic: status.0.error_result: '' expected type 'string', got unconvertible type 'map[string]interface {}'
```

Looks like the `errorResult` is this structure: https://cloud.google.com/bigquery/docs/reference/rest/v2/ErrorProto

rather than just a string

2021-02-02 22:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 197 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 197 insertions(+))

2021-02-02 22:41 UTC, kanterov commented
/gcbrun

2021-02-02 22:45 UTC, kanterov commented
@slevenick sorry, totally confused it. Now tests pass locally, is it possible to re-trigger GCB?

2021-02-02 23:02 UTC, slevenick commented
/gcbrun

2021-02-02 23:02 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170555"

2021-02-02 23:10 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 197 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 2 files changed, 197 insertions(+))

2021-02-03 00:13 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample|TestAccBigQueryJob_bigqueryJobLoadExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170640"

2021-02-03 08:44 UTC, kanterov commented
I can't reproduce the failure of `TestAccBigQueryJob_bigqueryJobLoadExample` locally, is there any way to see logs?

`TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample` and `TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample` seem to be failing in main branch as well.

2021-02-03 17:49 UTC, slevenick commented
> I can't reproduce the failure of `TestAccBigQueryJob_bigqueryJobLoadExample` locally, is there any way to see the logs?
> 
> `TestAccActiveDirectoryDomainTrust_activeDirectoryDomainTrustBasicExample` and `TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample` seem to be failing in the main branch as well.

Yeah, the other two tests are unrelated to your changes, ignore them.

I'm still seeing this failure for the bigquery job:
```
TestAccBigQueryJob_bigqueryJobLoadExample: provider_test.go:270: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) (len=1) {
(string) (len=14) "status.0.state": (string) (len=4) "DONE"
}
(map[string]string) (len=1) {
(string) (len=14) "status.0.state": (string) (len=7) "RUNNING"
}
```

it looks like the job status is changing between creating the job & the import step running. This may be flaky due to the time it takes the job to finish. We probably want to ignore the status when running the import step due to this, as it should never be set by the user. 

You can add `status.0.state` to the `ImportStateVerifyIgnore` for the bigquery job tests and it should fix this

2021-02-03 19:05 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 4 files changed, 206 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 5 files changed, 207 insertions(+), 10 deletions(-))

2021-02-03 19:15 UTC, kanterov commented
@slevenick thanks for the clarifications, I've updated tests, including auto-generated ones. Should we /gcbrun?

2021-02-03 19:53 UTC, slevenick commented
/gcbrun

2021-02-03 19:53 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170713"

2021-02-03 20:02 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4455-old..auto-pr-4455) ( 4 files changed, 206 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4455-old..auto-pr-4455) ( 5 files changed, 207 insertions(+), 10 deletions(-))

2021-02-03 21:02 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=170729"

2021-02-03 23:40 UTC, slevenick approved these changes
Looks good to me! Thanks

2021-02-03 23:41 UTC, merged

2021-02-04 10:03 UTC, kanterov commented
@slevenick thanks a lot for your support, I learned a lot!