Mark BQ's materialized view query as ForceNew
GoogleCloudPlatform/magic-modules pull request #4543
Opened 2021-03-01 10:16 UTC by tmshn

Currently updating query field of BQ materialized view is not supported. To address this, I marked `query` field as `ForceNew`.

This fixes https://github.com/hashicorp/terraform-provider-google/issues/8579

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
Mark BQ's materialized view query as ForceNew
```

2021-03-01 10:18 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@melinath, please review this PR or find an appropriate assignee.

2021-03-01 10:26 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4543-old..auto-pr-4543) ( 1 file changed, 1 insertion(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4543-old..auto-pr-4543) ( 1 file changed, 1 insertion(+))

2021-03-01 10:29 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2021-03-01 16:17 UTC, melinath requested changes
Thank you for the PR! It would be great if you could also add a test that would have caught this - similar to TestAccBigQueryTable_updateView.

2021-03-03 15:24 UTC, tmshn commented
I'll add test! Maybe on weekend

2021-03-06 11:49 UTC, tmshn commented
@melinath Modified acctest to cover the update case! Could you review it again?

2021-03-06 11:50 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4543-old..auto-pr-4543) ( 2 files changed, 18 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4543-old..auto-pr-4543) ( 4 files changed, 20 insertions(+), 3 deletions(-))

2021-03-06 11:51 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175921"

2021-03-06 13:07 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated|TestAccBigQueryTable_MaterializedView_DailyTimePartioning_Basic You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175922"

2021-03-06 13:22 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated Please fix these to complete your PR

2021-03-08 17:00 UTC, melinath approved these changes
thanks! LGTM

2021-03-08 17:01 UTC, merged

2021-03-09 15:17 UTC, alepuccetti commented
Related to: https://github.com/hashicorp/terraform-provider-google/issues/8310