Add customize diff for deprecated attribute on gc_policy
GoogleCloudPlatform/magic-modules pull request #4556
Opened 2021-03-03 03:53 UTC by ScottSuarez

Adding customize diff when `google_bigtable_gc_policy.max_age.days` is equivalent to `google_bigtable_gc_policy.max_age.duration`. 

resolves https://github.com/hashicorp/terraform-provider-google/issues/8416

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
bigtable: fixed bug where gc_policy would attempt to delete the resource if we switched off deprecated attribute but maintained same value underlying value
```

2021-03-03 04:02 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4556-old..auto-pr-4556) ( 2 files changed, 101 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4556-old..auto-pr-4556) ( 2 files changed, 101 insertions(+), 3 deletions(-))

2021-03-03 04:02 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175325"

2021-03-03 19:04 UTC, melinath approved these changes
This LGTM. Just to make sure I'm understanding, it doesn't look like this tests whether there's a diff, just whether the change succeeds (but without the diff suppression it wouldn't succeed) - correct?

2021-03-03 19:05 UTC, melinath requested changes
Looks like tests are failing:

```
Step #24 - "tpg-test": google/resource_bigtable_gc_policy.go:39:14: Error return value of `diff.Clear` is not checked (errcheck)
Step #24 - "tpg-test":      diff.Clear("max_age.0.days")
Step #24 - "tpg-test":                ^
Step #24 - "tpg-test": google/resource_bigtable_gc_policy.go:40:14: Error return value of `diff.Clear` is not checked (errcheck)
Step #24 - "tpg-test":      diff.Clear("max_age.0.duration")
Step #24 - "tpg-test":                ^
Step #23 - "tpgb-test": google-beta/resource_bigtable_gc_policy.go:39:14: Error return value of `diff.Clear` is not checked (errcheck)
Step #23 - "tpgb-test":       diff.Clear("max_age.0.days")
Step #23 - "tpgb-test":                 ^
Step #23 - "tpgb-test": google-beta/resource_bigtable_gc_policy.go:40:14: Error return value of `diff.Clear` is not checked (errcheck)
Step #23 - "tpgb-test":       diff.Clear("max_age.0.duration")
Step #23 - "tpgb-test":                 ^
```

2021-03-03 19:17 UTC, melinath commented
I like the idea of unit tests for the diff suppress func, similar to `TestDiskImageDiffSuppress` - would you be open to adding some of those?

2021-03-05 17:49 UTC, ScottSuarez commented on mmv1/compiler.rb
> +  Google::LOGGER.info "Using override directory '#{override_dir}'"
Yeah sort of a small improvement - although it is a side effect change so I understand if we want to omit

2021-03-05 17:49 UTC, ScottSuarez commented on mmv1/compiler.rb
> +  Google::LOGGER.info "Using override directory '#{override_dir}'"
yep ! just a small qol improvement for the build process. I can omit if we don't want to piggy back

2021-03-05 17:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4556-old..auto-pr-4556) ( 2 files changed, 107 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4556-old..auto-pr-4556) ( 2 files changed, 107 insertions(+), 3 deletions(-))

2021-03-05 17:57 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175733"

2021-03-05 18:16 UTC, melinath commented on mmv1/compiler.rb
> +  Google::LOGGER.info "Using override directory '#{override_dir}'"
I think it's fine, just wanted to make sure it wasn't an accident :-) improvements to logging are great

2021-03-05 18:17 UTC, melinath commented
auto-run failed. /gcbrun

2021-03-05 18:25 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4556-old..auto-pr-4556) ( 2 files changed, 107 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4556-old..auto-pr-4556) ( 3 files changed, 108 insertions(+), 4 deletions(-))

2021-03-05 18:26 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175737"

2021-03-05 18:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4556-old..auto-pr-4556) ( 3 files changed, 190 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4556-old..auto-pr-4556) ( 3 files changed, 190 insertions(+), 6 deletions(-))

2021-03-05 18:57 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=175744"

2021-03-09 18:23 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4556-old..auto-pr-4556) ( 3 files changed, 190 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4556-old..auto-pr-4556) ( 4 files changed, 191 insertions(+), 7 deletions(-))

2021-03-09 18:23 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=176357"

2021-03-09 19:39 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=176363"

2021-03-09 20:30 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccApiGatewayGateway_apigatewayGatewayBasicExampleUpdated Please fix these to complete your PR

2021-03-09 21:55 UTC, melinath approved these changes
LGTM - thanks for the tests!

2021-03-09 21:55 UTC, melinath commented on mmv1/third_party/terraform/utils/test_utils.go
> +	Cleared    map[string]interface{}
I'm surprised this wasn't used anywhere... Could this be `map[string]bool` instead?

2021-03-10 01:19 UTC, merged