Allow data lookup on google_active_folder without providing a parent
GoogleCloudPlatform/magic-modules pull request #4631
Opened 2021-03-29 20:54 UTC by rileykarson

Upstreams https://github.com/hashicorp/terraform-provider-google/pull/7509

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
resourcemanager: added support for parent-less lookups to `data.google_active_folder`
```

2021-03-29 20:55 UTC, rileykarson commented
No CLA needed, all changes are `third_party`

2021-03-29 21:03 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4631-old..auto-pr-4631) ( 3 files changed, 61 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4631-old..auto-pr-4631) ( 3 files changed, 61 insertions(+), 4 deletions(-))

2021-03-29 21:03 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=179580"

2021-03-30 16:31 UTC, melinath requested changes
It looks like tests are currently failing due to:

```
google/data_source_google_active_folder_test.go:135:6: `testAccDataSourceGoogleActiveFolderConfig_no_parent` is unused (deadcode)
func testAccDataSourceGoogleActiveFolderConfig_no_parent(parent string, displayName string) string {
     ^
```

2021-04-30 21:02 UTC, melinath commented
@rileykarson is this still an active PR?

2021-05-03 21:40 UTC, rileykarson commented
I mean to get back to this, but haven't yet!

2021-07-26 22:56 UTC, melinath commented
I'm going to remove myself as a reviewer for now; feel free to re-request review when you get back to it.

2021-07-26 22:56 UTC, melinath commented
lol I actually can't do that apparently 😂

2022-01-28 23:12 UTC, melinath commented
@rileykarson is this still in progress?

2023-02-07 22:52 UTC, closed without merging