set scopes to optional for compute instance
GoogleCloudPlatform/magic-modules pull request #4676
Opened 2021-04-08 15:35 UTC by edwardmedia

Fixes https://github.com/hashicorp/terraform-provider-google/issues/8871

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug

```

2021-04-08 15:37 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@melinath, please review this PR or find an appropriate assignee.

2021-04-08 15:45 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4676-old..auto-pr-4676) ( 2 files changed, 100 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4676-old..auto-pr-4676) ( 2 files changed, 100 insertions(+), 1 deletion(-))

2021-04-08 15:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4676-old..auto-pr-4676) ( 3 files changed, 101 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4676-old..auto-pr-4676) ( 4 files changed, 102 insertions(+), 3 deletions(-))

2021-04-08 15:49 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=181434"

2021-04-08 18:11 UTC, rileykarson approved these changes

2021-04-08 18:11 UTC, rileykarson commented on mmv1/third_party/terraform/tests/resource_compute_instance_test.go
> +					testAccCheckComputeInstanceExists(
An import check should supersede the exists check.

2021-04-08 18:11 UTC, rileykarson requested changes
Actually, I think we want to ensure that users are still able to set `scopes = []` explicitly. AFAIK it was a breaking change to add `MinItems`, so we'll want to revert it. Was there a permadiff before or something?

2021-04-08 19:57 UTC, edwardmedia commented
@rileykarson the use case in https://github.com/hashicorp/terraform-provider-google/issues/8792#issue-844300180 leads to crash. Set MinItems was intended to address that.

2021-04-08 20:13 UTC, rileykarson commented
I'm still not certain this is the right change, I think the actual problem is in Read- it reads like we're setting `service_account` to `nil` when we want to set it to an empty map. This change makes it possible to define the following block. Can you add a test doing so and ensure that that works as expected, provisioning an instance with no service account and no scopes?

```
service_account {}
```

As raised in #8871 I believe that the following definition should work, and removing the ability to specify it was a breaking change that we should revert.

```
  service_account {
    email  = "test-service-account@test-project.iam.gserviceaccount.com" # or some other SA
    scopes = []
  }
```

2021-04-08 22:31 UTC, edwardmedia commented
@rileykarson adding below block seems to be fine. Since `email` is optional, should we support the block without the `email`?
```
 service_account {
    email  = "test-service-account@test-project.iam.gserviceaccount.com" # or some other SA
    scopes = []
  }
```

2021-04-09 20:03 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4676-old..auto-pr-4676) ( 3 files changed, 162 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4676-old..auto-pr-4676) ( 5 files changed, 165 insertions(+), 4 deletions(-))

2021-04-09 20:03 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=181632"

2021-04-13 13:50 UTC, closed without merging