Add GCS Bucket Sweeper
GoogleCloudPlatform/magic-modules pull request #4721
Opened 2021-04-20 23:41 UTC by upodroid

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/8909

I haven't worked with sweepers before and the Terraform docs are very lacking on how to test them too. https://www.terraform.io/docs/extend/testing/acceptance-tests/sweepers.html

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2021-04-20 23:42 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@scottsuarez, please review this PR or find an appropriate assignee.

2021-04-20 23:50 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4721-old..auto-pr-4721) ( 5 files changed, 121 insertions(+), 11 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4721-old..auto-pr-4721) ( 5 files changed, 121 insertions(+), 11 deletions(-))

2021-04-20 23:50 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=183280"

2021-04-21 01:24 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccCloudRunDomainMapping_foregroundDeletion|TestAccComputeBackendService_internalLoadBalancing|TestAccStorageBucket_basic|TestAccStorageBucket_update|TestAccStorageBucket_lowercaseLocation|TestAccStorageBucket_requesterPays|TestAccStorageBucket_lifecycleRuleStateArchived|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_storageClass|TestAccStorageBucket_update_requesterPays|TestAccStorageBucket_website|TestAccStorageBucket_versioning|TestAccStorageBucket_logging|TestAccStorageBucket_cors|TestAccStorageBucket_bucketPolicyOnly|TestAccStorageBucket_defaultEventBasedHold|TestAccStorageBucket_uniformBucketAccessOnly|TestAccStorageBucket_labels|TestAccStorageBucket_retentionPolicy|TestAccStorageBucket_retentionPolicyLocked You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=183371"

2021-04-21 02:52 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccStorageBucket_basic|TestAccStorageBucket_update|TestAccStorageBucket_lifecycleRuleStateLive|TestAccStorageBucket_update_requesterPays|TestAccStorageBucket_requesterPays|TestAccStorageBucket_versioning|TestAccStorageBucket_lifecycleRuleStateAny|TestAccStorageBucket_storageClass|TestAccStorageBucket_lifecycleRuleStateArchived|TestAccStorageBucket_lowercaseLocation|TestAccStorageBucket_logging|TestAccStorageBucket_cors|TestAccStorageBucket_defaultEventBasedHold|TestAccStorageBucket_uniformBucketAccessOnly|TestAccStorageBucket_labels|TestAccStorageBucket_bucketPolicyOnly|TestAccStorageBucket_website|TestAccStorageBucket_retentionPolicy|TestAccStorageBucket_retentionPolicyLocked|TestAccCloudRunDomainMapping_foregroundDeletion Please fix these to complete your PR

2021-04-21 17:45 UTC, ScottSuarez commented
I haven't written a sweeper before @c2thorn could you help out on this one?

2021-04-21 18:05 UTC, c2thorn requested changes
Thanks for getting on this! Each test that had `force_destroy` added needs a 
```
				ImportStateVerifyIgnore: []string{"force_destroy"},
```
on the import step unfortunately.

2021-04-21 18:11 UTC, upodroid commented
I'll fix that, what about the sweeper?

2021-04-21 19:00 UTC, c2thorn requested changes

2021-04-21 19:00 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_storage_bucket_sweeper_test.go
> +		deleteUrl := servicesUrl + "/" + id
servicesUrl was modified by `addQueryParams`. Use a variable for the endpoint or do something like 
```suggestion
		deleteUrl := fmt.Sprintf("https://storage.googleapis.com/storage/v1/b/%s", id)
```

2021-04-21 19:00 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_storage_bucket_sweeper_test.go
> +// This will sweep GCE Disk resources
```suggestion
```

2021-04-21 22:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4721-old..auto-pr-4721) ( 5 files changed, 265 insertions(+), 120 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4721-old..auto-pr-4721) ( 6 files changed, 266 insertions(+), 121 deletions(-))

2021-04-21 22:49 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=183460"

2021-04-22 00:19 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccComputeBackendService_internalLoadBalancing|TestAccStorageBucket_website You can view the result here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=183553"

2021-04-22 16:28 UTC, c2thorn approved these changes

2021-04-22 16:28 UTC, merged

2021-04-22 18:21 UTC, ScottSuarez commented
hi @upodroid 

just a heads up, you might want to rebase your master to origin master.  It would help to avoid having redundant git commit chains on every pull request. In practice it's not an issue but it is slight noise. any, just an option.

<img width="867" alt="Screen Shot 2021-04-22 at 11 19 56 AM" src="https://user-images.githubusercontent.com/9483464/115766426-d32a1000-a35c-11eb-9373-454055fa8a8f.png">