Match preview versions in google_composer_environment regex
GoogleCloudPlatform/magic-modules pull request #4797
Opened 2021-05-19 20:03 UTC by rileykarson

Resolves a test error: `Error: "config.0.software_config.0.image_version" ("composer-1.17.0-preview.0-airflow-2.0.1") doesn't match regexp "composer-([0-9]+\\.[0-9]+\\.[0-9]+|latest)-airflow-([0-9]+\\.[0-9]+(\\.[0-9]+.*)?)"`

New string is `composer-1.17.0-preview.0-airflow-2.0.1`, we expected strings like `composer-1.4.1-airflow-1.10.0` and `composer-latest-airflow-1.10.0`.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
composer: fixed a check that did not allow for preview versions in `google_composer_environment`
```

2021-05-19 20:12 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4797-old..auto-pr-4797) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4797-old..auto-pr-4797) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2021-05-19 20:13 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=188265"

2021-05-19 21:33 UTC, melinath requested changes
It looks like unit tests are failing - could you also add a unit test for a value that would be expected to pass with the new regex but was previously failing?

2021-05-27 18:41 UTC, rileykarson commented
Done, pushed a change.

2021-05-27 18:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-4797-old..auto-pr-4797) ( 2 files changed, 5 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-4797-old..auto-pr-4797) ( 2 files changed, 5 insertions(+), 5 deletions(-))

2021-05-27 18:48 UTC, modular-magician commented
I have triggered VCR tests based on this PR's diffs. See the results here: "https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=189467"

2021-05-27 20:18 UTC, melinath approved these changes
LGTM

2021-05-27 22:53 UTC, merged