Adding Apigee NAT Address Resource
GoogleCloudPlatform/magic-modules pull request #5018
Opened 2021-07-30 13:47 UTC by danistrebel

Adding Apigee NAT addresses for Apigee Instances as per the [Apigee API](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.instances.natAddresses)

fixes https://github.com/hashicorp/terraform-provider-google/issues/9358

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know). => Unable to run the terraform-provider-google tests 😞 .
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_apigee_nat_address`
```

2021-07-30 13:48 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@rileykarson, please review this PR or find an appropriate assignee.

2021-07-30 13:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5018-old..auto-pr-5018) ( 7 files changed, 537 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5018-old..auto-pr-5018) ( 9 files changed, 539 insertions(+), 7 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 54 insertions(+))

2021-08-13 09:11 UTC, rileykarson commented
Sorry, lost email on my end. @melinath do you mind picking up this review, since you've looked at Apigee more extensively?

2021-08-13 21:52 UTC, melinath reviewed
This seems reasonable. I'll start a /gcbrun.

2021-08-13 21:52 UTC, melinath commented on mmv1/templates/terraform/examples/apigee_nat_address_basic.tf.erb
> +resource "google_apigee_nat_address" "apigee_nat_addres" {
typo: should be `apigee_nat_adress`

2021-08-13 21:53 UTC, melinath commented
/gcbrun

2021-09-28 17:41 UTC, melinath requested changes
It looks like this is failing due to issues in the ansible provider. If you merge master (or rebase your PR) that should address the issue. Could you clarify the issues you had running the acceptance tests for this change?

Sorry that this fell through the cracks. Please feel free to [re-request review](https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/) any time that you're ready for another review.

2021-09-29 12:18 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5018-old..auto-pr-5018) ( 7 files changed, 537 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5018-old..auto-pr-5018) ( 8 files changed, 539 insertions(+), 5 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))

2021-09-29 12:45 UTC, danistrebel commented
thanks @melinath rebased the branch and it looks like we need a /gcbrun again for the remaining check. Thanks

2021-09-29 15:17 UTC, melinath commented
/gcbrun

2021-09-29 15:29 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5018-old..auto-pr-5018) ( 7 files changed, 537 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5018-old..auto-pr-5018) ( 7 files changed, 537 insertions(+), 4 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))

2021-09-29 17:09 UTC, modular-magician commented
Tests were added that did not run in TeamCity:

- TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample

2021-09-29 17:09 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccTags You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=208280

2021-10-01 18:44 UTC, melinath commented
Doing a specific CI-run for the new test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/208683

2021-10-01 20:53 UTC, melinath commented
Hm. That failed with the following error:

```
------- Stdout: -------
=== RUN   TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample
=== PAUSE TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample
=== CONT  TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample
provider_test.go:278: Step 1/2 error: Error running apply: exit status 1
2021/10/01 18:48:31 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.13.0
Error: Error waiting to create Instance: Error waiting for Creating Instance: Error code 13, message: Unexpected error during operation. Try again later
on terraform_plugin_test.tf line 56, in resource "google_apigee_instance" "apigee_instance":
56: resource "google_apigee_instance" "apigee_instance" {
--- FAIL: TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample (2443.86s)
FAIL
```

Here's the full request/response:

```
---[ REQUEST ]---------------------------------------
GET /v1/organizations/tf-testvh9ifx91zu/operations/9f6ef1e2-28ba-42eb-b780-a72e4a0f485d?alt=json HTTP/1.1
Host: apigee.googleapis.com
User-Agent: Terraform/0.12.30 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google-beta/dev
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2021/10/01 19:26:43 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Fri, 01 Oct 2021 19:26:43 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "organizations/tf-testvh9ifx91zu/operations/9f6ef1e2-28ba-42eb-b780-a72e4a0f485d",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.apigee.v1.OperationMetadata",
    "operationType": "INSERT",
    "targetResourceName": "organizations/tf-testvh9ifx91zu/instances/tf-testvh9ifx91zu",
    "state": "FINISHED",
    "progress": {
      "description": "Succeeded",
      "percentDone": 100
    }
  },
  "done": true,
  "error": {
    "code": 13,
    "message": "Unexpected error during operation. Try again later"
  }
}

-----------------------------------------------------
```

Is this probably transient, or more likely flakey? (Starting another CI test run for just this test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/208699)

2021-10-08 15:12 UTC, melinath commented
(FWIW it looks like that last run failed with the same error.)

2021-12-16 10:44 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5018-old..auto-pr-5018) ( 8 files changed, 555 insertions(+), 22 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5018-old..auto-pr-5018) ( 8 files changed, 555 insertions(+), 22 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))

2021-12-16 12:31 UTC, danistrebel commented
@melinath Could you please re-run the cloud build again? I trust the Apigee instance provisioning has stabilized since we last tried. Thanks

2021-12-16 16:07 UTC, melinath commented
/gcbrun

2021-12-16 16:20 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5018-old..auto-pr-5018) ( 7 files changed, 537 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5018-old..auto-pr-5018) ( 8 files changed, 555 insertions(+), 22 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5018-old..auto-pr-5018) ( 1 file changed, 63 insertions(+))

2021-12-16 18:07 UTC, modular-magician commented
Tests were added that did not run in TeamCity:

- TestAccApigeeNatAddress_apigeeNatAddressBasicTestExample

2021-12-16 18:07 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudFunctionsFunction_vpcConnector|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccServiceNetworkingPeeredDNSDomain_basic You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=232708

2021-12-16 18:33 UTC, melinath commented
Running the new test in CI: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/232720

2021-12-22 21:21 UTC, melinath approved these changes
LGTM - test failure seems to be related to https://github.com/hashicorp/terraform-provider-google/issues/9988

2021-12-22 21:21 UTC, merged

2021-12-23 17:38 UTC, rileykarson commented
Given the basic test for this resource failed on its first nightly, can we revert and resolve the Apigee instance failure prior to merging?

2021-12-23 18:07 UTC, melinath commented
@rileykarson sure, if that's preferred.

2021-12-23 18:38 UTC, rileykarson commented
A fix-forward also works, I'd like to avoid merging a resource whose sole test is already failing out of the gate is all!

2021-12-23 19:03 UTC, melinath commented
given the holidays, I think a rollback is going to be safer / more useful than a fix-forward.