Fix TestAccStorageSignedUrl_accTest
GoogleCloudPlatform/magic-modules pull request #5200
Opened 2021-09-14 20:23 UTC by upodroid

Fix: https://github.com/hashicorp/terraform-provider-google/issues/9990

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2021-09-14 20:25 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@melinath, please review this PR or find an appropriate assignee.

2021-09-14 20:28 UTC, upodroid commented
I removed the header because:
- generation is serverside value, metageneration isn't but it is designed for metadata instead of the object
- not sure why this header is being tested.

https://cloud.google.com/storage/docs/json_api/v1/objects#resource
https://cloud.google.com/storage/docs/xml-api/reference-headers#xgoogifgenerationmatch

<details>

<summary> TestAccStorageSignedUrl_accTest Test Run </summary>

```
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccStorageSignedUrl_accTest -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccStorageSignedUrl_accTest
=== PAUSE TestAccStorageSignedUrl_accTest
=== CONT  TestAccStorageSignedUrl_accTest
2021/09/14 21:17:40 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:40 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:40 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:40 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:40 [DEBUG] Waiting for state to become: [success]
2021/09/14 21:17:41 [INFO] Terraform is using this identity: jenkins-sva@REDACTED.iam.gserviceaccount.com
2021/09/14 21:17:44 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:44 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:44 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:44 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:44 [DEBUG] Waiting for state to become: [success]
2021/09/14 21:17:44 [INFO] Terraform is using this identity: jenkins-sva@REDACTED.iam.gserviceaccount.com
2021/09/14 21:17:48 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:48 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:48 [INFO] Authenticating using DefaultClient...
2021/09/14 21:17:48 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloud-identity https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2021/09/14 21:17:48 [DEBUG] Waiting for state to become: [success]
2021/09/14 21:17:48 [INFO] Terraform is using this identity: jenkins-sva@REDACTED.iam.gserviceaccount.com
2021/09/14 21:17:48 [DEBUG] Waiting for state to become: [success]
2021/09/14 21:17:48 [INFO] Instantiating Google Storage client for path https://storage.googleapis.com/storage/v1/
2021/09/14 21:17:48 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/09/14 21:17:48 [DEBUG] Retry Transport: request attempt 0
2021/09/14 21:17:48 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
POST /storage/v1/b?alt=json&prettyPrint=false&project=REDACTED HTTP/1.1
Host: storage.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/0.14.11 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/acc
Content-Length: 178
Content-Type: application/json
X-Goog-Api-Client: gl-go/1.16.5 gdcl/20210606
Accept-Encoding: gzip

{
 "iamConfiguration": {
  "uniformBucketLevelAccess": {
   "enabled": false
  }
 },
 "lifecycle": {
  "rule": []
 },
 "location": "US",
 "name": "tf-test-bucket-2027338368125175627",
 "storageClass": "STANDARD"
}

-----------------------------------------------------
2021/09/14 21:17:50 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 557
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json; charset=UTF-8
Date: Tue, 14 Sep 2021 20:17:50 GMT
Etag: CAE=
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: UploadServer
Vary: Origin
Vary: X-Origin
X-Guploader-Uploadid: ADPycdsxLg4rqOHMYaPCV6QkS1EYBgPgwv03fUsWjh6ZIB5uCaLNepZZzHCCFKDEM4AM1DmXnd5RJpCONdJ5MOPtv8FJZUo78g

{
 "kind": "storage#bucket",
 "selfLink": "https://www.googleapis.com/storage/v1/b/tf-test-bucket-2027338368125175627",
 "id": "tf-test-bucket-2027338368125175627",
 "name": "tf-test-bucket-2027338368125175627",
 "projectNumber": "550924169191",
 "metageneration": "1",
 "location": "US",
 "storageClass": "STANDARD",
 "etag": "CAE=",
 "timeCreated": "2021-09-14T20:17:50.191Z",
 "updated": "2021-09-14T20:17:50.191Z",
 "iamConfiguration": {
  "bucketPolicyOnly": {
   "enabled": false
  },
  "uniformBucketLevelAccess": {
   "enabled": false
  },
  "publicAccessPrevention": "unspecified"
 },
 "locationType": "multi-region"
}
-----------------------------------------------------
2021/09/14 21:17:50 [DEBUG] Retry Transport: Stopping retries, last request was successful
2021/09/14 21:17:50 [DEBUG] Retry Transport: Returning after 1 attempts
2021/09/14 21:17:50 [DEBUG] Created bucket tf-test-bucket-2027338368125175627 at location https://www.googleapis.com/storage/v1/b/tf-test-bucket-2027338368125175627

2021/09/14 21:17:50 [INFO] Instantiating Google Storage client for path https://storage.googleapis.com/storage/v1/
2021/09/14 21:17:50 [DEBUG] Retry Transport: starting RoundTrip retry loop
2021/09/14 21:17:50 [DEBUG] Retry Transport: request attempt 0
2021/09/14 21:17:50 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /storage/v1/b/tf-test-bucket-2027338368125175627?alt=json&prettyPrint=false HTTP/1.1
Host: storage.googleapis.com
User-Agent: google-api-go-client/0.5 Terraform/0.14.11 (+https://www.terraform.io) Terraform-Plugin-SDK/2.5.0 terraform-provider-google/acc
X-Goog-Api-Client: gl-go/1.16.5 gdcl/20210606
Accept-Encoding: gzip


-----------------------------------------------------
2021/09/14 21:17:50 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Length: 557
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0, must-revalidate, no-transform
Content-Type: application/json; charset=UTF-8
Date: Tue, 14 Sep 2021 20:17:50 GMT
Etag: CAE=
Expires: Tue, 14 Sep 2021 20:17:50 GMT
Server: UploadServer
Vary: Origin
Vary: X-Origin
X-Guploader-Uploadid: ADPycdtC5dsYNlZjJcLOhnNQCLTOkZnVh4UTjgCt1BCO1AN0FPRn4G86T1NhwAsA [...]

2021-09-14 20:34 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 1 insertion(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5200-old..auto-pr-5200) ( 2 files changed, 2 insertions(+), 5 deletions(-))

2021-09-14 21:19 UTC, melinath requested changes
I agree that this looks like it probably never should have been passing, since the generation is server-generated. Maybe the API finally started validating this? Or maybe x-goog-test used to cause the generation to be 1 and no longer does?

I think there is value to making sure that the datasource is correctly passing headers to the API... but I don't think this test ever did that. Even if we were able to get the correct generation, that wouldn't prove that we were passing headers in, since we would get a successful result regardless of whether the header was getting passed.

Really, we should probably be testing that if we pass a generation match header that is incorrect (like, say, 1) we get a precondition failed error. That would let us verify that we're actually passing the headers correctly. Would you be down to switch the test around to check that instead?

2021-09-14 21:45 UTC, upodroid commented
If the idea is to test headers being set, then `x-goog-if-metageneration-match` can replace the one I deleted. It is always one for each generation of an object and there is only generation in the entire test.

2021-09-14 22:29 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2021-09-15 15:34 UTC, melinath requested changes
Okay, that's fine too. You'll need to update the `if-generation-match` on [line 128](https://github.com/GoogleCloudPlatform/magic-modules/pull/5200/files#diff-917aefc3765e346111db5a8227291c2c1aed5d60a82fc048f086d10e8c7f6e9bR128) to if-metageneration-match as well. (Currently if-generation-match)

2021-09-15 16:05 UTC, upodroid commented
my bad, fixed

2021-09-15 16:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 2 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2021-09-15 16:41 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 3 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5200-old..auto-pr-5200) ( 2 files changed, 4 insertions(+), 4 deletions(-))

2021-09-15 17:39 UTC, melinath commented
/gcbrun

2021-09-15 17:51 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 3 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5200-old..auto-pr-5200) ( 1 file changed, 3 insertions(+), 3 deletions(-))

2021-09-15 21:54 UTC, melinath commented
It looks like this test is skipped in VCR - running a special build to check it: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/205953

2021-09-15 22:02 UTC, melinath approved these changes

2021-09-15 22:02 UTC, merged