Add warning documenting behavior of the google_service_account_key resource for certain cases where the project cannot be inferred by terraform
GoogleCloudPlatform/magic-modules pull request #5301
Opened 2021-10-08 14:17 UTC by stangles

Resolves https://github.com/hashicorp/terraform-provider-google/issues/9617.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
iam: added warning regarding `google_service_account_key` behavior when the project cannot be inferred from the `service_account_id` field.
```

2022-01-28 19:42 UTC, melinath commented
@stangles are you still working on this PR?

2022-01-28 20:05 UTC, stangles commented
>It seems like the failure case is if just the first part of the email address is given?

Yes, that matches my understanding. When taking a look back at how I reproduced the unexpected behavior stated in the issue, I believe I had specified the SA unique ID, thus tripping the same error (and also demonstrating how the current `service_account_id` description isn't correct). Updated in d3ad7a4

>are you still working on this PR?

Yes, apologies for the delayed response.

2022-01-31 23:10 UTC, melinath requested changes
This looks a lot better but it seems like it should be possible to use `projects/{PROJECT_ID}/serviceAccounts/{UNIQUE_ID}` according to [these](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys/create) [docs](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts). Could you incorporate that information as well?

2022-02-01 19:30 UTC, stangles commented
>This looks a lot better but it seems like it should be possible to use projects/{PROJECT_ID}/serviceAccounts/{UNIQUE_ID} according to these docs. Could you incorporate that information as well?

Done in f34e0f1

>In case it's helpful here's the code the provider uses

That was quite helpful, thank you for the documentation and code references. Hopefully I've got it right this time around :smile:

2022-02-14 23:47 UTC, melinath requested changes
This looks a lot better - the one thing that seems to be missing is that I think it should be possible to use `projects/{PROJECT_ID}/serviceAccounts/{UNIQUE_ID}` - could you include that as an option?

2022-02-15 22:04 UTC, stangles commented
>I think it should be possible to use projects/{PROJECT_ID}/serviceAccounts/{UNIQUE_ID} - could you include that as an option?

Yep, added in [35423ff](https://github.com/GoogleCloudPlatform/magic-modules/pull/5301/commits/35423ff761b99f4d8a9190070e15d57b7f3fd1b8) which hopefully is unambiguous without being too wordy.

2022-02-16 17:57 UTC, melinath approved these changes
LGTM - thanks!

2022-02-16 17:57 UTC, melinath commented
Build failure is unrelated; this is docs only & will be fine after merge.

2022-02-16 17:57 UTC, merged