Add `mesh_certificates` field to `google_container_cluster` resource
GoogleCloudPlatform/magic-modules pull request #5361
Opened 2021-10-21 22:56 UTC by upodroid

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/9973

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added `mesh_certificates` field to `google_container_cluster` resource
```

2021-10-21 22:58 UTC, upodroid commented
Can you add the hacktoberfest-accepted label? Thanks

2021-10-21 23:09 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 16 insertions(+), 17 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 7 files changed, 123 insertions(+), 26 deletions(-))

2021-11-02 17:31 UTC, melinath requested changes
LGTM.

Could you move the changes to the provider_reference and provider_versions docs to a separate PR? They seem unrelated to the workload_certificates changes.

2021-11-02 17:31 UTC, melinath commented on mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown
> +* `enable_certificates` (Required) - Whether Workload Certificates is enabled.
Do you want to add the warning about forcenew somewhere in this file as well?

2021-11-02 17:31 UTC, melinath commented
/gcbrun

2021-11-02 17:42 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 16 insertions(+), 17 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 122 insertions(+), 21 deletions(-))

2022-01-28 19:43 UTC, melinath commented
@upodroid are you still working on this PR?

2022-01-28 19:49 UTC, upodroid commented
Yeah, I forgot about this. I'll have it ready for review soon

2022-01-31 16:08 UTC, upodroid commented
This is ready.

It was good that it go delayed as Google changed the field from `workload_certificates` to `mesh_certificates` when it got promoted to v1.

2022-01-31 16:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))

2022-01-31 22:18 UTC, melinath commented
It looks like there are some extraneous changes to files in `mmv1/third_party/terraform/website/docs/guides/` - could you remove those? This seems reasonable otherwise. /gcbrun

2022-01-31 22:23 UTC, upodroid commented
> It looks like there are some extraneous changes to files in `mmv1/third_party/terraform/website/docs/guides/` - could you remove those? This seems reasonable otherwise. /gcbrun

I do drive by doc updates on issues I come across. It is intentional.

2022-01-31 22:32 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))

2022-01-31 22:59 UTC, melinath commented
> > It looks like there are some extraneous changes to files in `mmv1/third_party/terraform/website/docs/guides/` - could you remove those? This seems reasonable otherwise. /gcbrun
> 
> I do drive by doc updates on issues I come across.

Gotcha. In general, our best practice for this repo is to keep PRs small and focused on a single logical grouping of changes, since that makes it easier to review PRs, easier to understand the commits after the fact, and prevents changes that are unrelated from getting blocked by each other. For example, the docs improvements to `mmv1/third_party/terraform/website/docs/guides/` have been blocked by the rest of this PR - they could've been merged a long time ago (assuming they pass review.)

Please move those changes to a separate PR, and try to create separate PRs for unrelated docs improvements in the future. Thanks!

2022-01-31 23:13 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 5 files changed, 117 insertions(+), 17 deletions(-))

2022-01-31 23:29 UTC, upodroid commented
Ok

2022-01-31 23:36 UTC, upodroid commented
It is done.

2022-01-31 23:51 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))

2022-02-15 21:57 UTC, melinath commented
Started a test run for just the new test: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/257220

Also, /gcbrun

2022-02-15 22:11 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-16 19:11 UTC, melinath commented
Trying /gcbrun again

2022-02-16 19:26 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5361-old..auto-pr-5361) ( 3 files changed, 108 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5361-old..auto-pr-5361) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-16 21:15 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudbuildWorkerPool_basic|TestAccContainerCluster_withMeshCertificates|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccServiceNetworkingPeeredDNSDomain_basic You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=257867

2022-02-17 00:00 UTC, melinath reviewed
It looks like this isn't causing any test issues.

2022-02-17 00:00 UTC, melinath commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +				ForceNew:    true,
It looks like this & enable_certificates should be updatable: https://cloud.google.com/traffic-director/docs/security-proxyless-setup#create-cluster - just want to double-check that they should be ForceNew?

2023-02-08 21:47 UTC, closed without merging