Treat a 403 in IAM as a 404 since they are indistinguishable.
GoogleCloudPlatform/magic-modules pull request #5497
Opened 2021-11-30 23:10 UTC by ndmckinley

Fixes https://github.com/GoogleCloudPlatform/terraform-validator/issues/393.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2021-11-30 23:21 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5497-old..auto-pr-5497) ( 1 file changed, 8 insertions(+), 2 deletions(-))

2021-12-01 00:11 UTC, melinath requested changes
Interesting to know that it's impossible to distinguish between 403 and 404 for IAM resources! Are you able to reproduce this behavior?

A couple things:

- It would be great to add a test for this change
- You'll need to add handling in converters/google/convert.go to handle this error being returned by `FetchFullResource`.

I'm not sure if ErrNoConversion is the right error either, since it essentially means "skip this resource"; we probably only want to skip asset fetch, similar to `ErrEmptyIdentityField` (which is what would normally prevent someone from ever hitting this case).

Maybe `ErrEmptyIdentityField` and `ErrLackingReadPermission` could be combined into a single error to capture the "does not exist" case? Though having a separate error for the IAM case would allow the converter to log an appropriate debug message.

2021-12-01 00:43 UTC, ndmckinley commented
> Are you able to reproduce this behavior?

Yep, you can just check the API explorer.

<img width="1264" alt="Screen Shot 2021-11-30 at 4 39 50 PM" src="https://user-images.githubusercontent.com/605324/144150911-d4a15104-d968-4ae8-8b7d-166bc3ad4122.png">

> Maybe ErrEmptyIdentityField and ErrLackingReadPermission could be combined into a single error to capture the "does not exist" case? Though having a separate error for the IAM case would allow the converter to log an appropriate debug message.

Fair enough.  I'm unlikely to find time for that in the medium term, the validator being very far afield of my day-to-day work and my onduty shift being timeboxed to last week.  Hopefully it helps for me to have pointed out what the problem is, I'll close this.

2021-12-01 00:43 UTC, closed without merging

2021-12-01 16:31 UTC, melinath commented
@ndmckinley super helpful, thank you!