Cloud Composer connection subnetwork [DO NOT MERGE]
GoogleCloudPlatform/magic-modules pull request #5523
Opened 2021-12-07 12:08 UTC by kubasieron

Add support for Private Service Connect by adding cloud_composer_connection_subnetwork field. 

This change shouldn't be merged before google go API is set to v0.61.0 (ie. until [that PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5517) is merged)

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/10550

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Added support for Private Service Connect by adding field cloud_composer_connection_subnetwork
```

2021-12-07 12:10 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@scottsuarez, please review this PR or find an appropriate assignee.

2021-12-09 15:27 UTC, kubasieron commented
Please review, all blockers are removed now

2021-12-09 15:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5523-old..auto-pr-5523) ( 3 files changed, 78 insertions(+), 84 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5523-old..auto-pr-5523) ( 3 files changed, 149 insertions(+), 68 deletions(-))

2021-12-09 17:35 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccCloudFunctionsFunction_vpcConnector|TestAccComposerEnvironment_ComposerV2|TestAccComposerEnvironment_composerV2PrivateServiceConnect|TestAccComputeForwardingRule_update|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupAppengineExample|TestAccContainerCluster_regionalWithNodePool|TestAccContainerCluster_withNodePoolResize|TestAccContainerCluster_withNodePoolAutoscaling|TestAccContainerCluster_errorAutopilotLocation|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccContainerNodePool_012_ConfigModeAttr|TestAccContainerNodePool_EmptyGuestAccelerator|TestAccContainerNodePool_ephemeralStorageConfig|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccPrivatecaCertificateTemplate_BasicCertificateTemplate|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=229911

2021-12-09 18:35 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_errorAutopilotLocation|TestAccCloudFunctionsFunction_vpcConnector|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccContainerNodePool_withInvalidUpgradeSettings Please fix these to complete your PR

2021-12-09 18:51 UTC, ScottSuarez approved these changes

2021-12-09 18:53 UTC, ScottSuarez requested changes

2021-12-09 18:53 UTC, ScottSuarez commented on mmv1/third_party/terraform/tests/resource_composer_environment_test.go.erb
> +
This test should only run in `beta` could you add the <% unless ga %> flags to gate the code accordingly

2021-12-09 18:53 UTC, ScottSuarez approved these changes

2021-12-09 18:53 UTC, ScottSuarez commented on mmv1/third_party/terraform/tests/resource_composer_environment_test.go.erb
> +
Nevermind, already gated

2021-12-09 18:53 UTC, merged