Add support for log alert
GoogleCloudPlatform/magic-modules pull request #5565
Opened 2021-12-17 06:47 UTC by chez-shanpu

Add support for log alert.

fixes https://github.com/hashicorp/terraform-provider-google/issues/9893

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
monitoring: added `conditionMatchedLog` and `alertStrategy` fields to `google_monitoring_alert_policy` resource
```

2021-12-17 06:48 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@shuyama1, please review this PR or find an appropriate assignee.

2021-12-17 06:51 UTC, chez-shanpu commented
Hi, repository manager :)
I signed CLA, could you rescan it?

2021-12-17 06:58 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 337 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 355 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2021-12-21 23:51 UTC, shuyama1 commented
/gcbrun

2021-12-22 00:05 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 337 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 355 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2021-12-22 01:54 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudFunctionsFunction_vpcConnector|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccMonitoringAlertPolicy You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=234605

2022-01-04 18:41 UTC, shuyama1 commented
/gcbrun

2022-01-04 18:55 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 337 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 359 insertions(+), 22 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2022-01-04 19:13 UTC, shuyama1 commented
Hey @chez-shanpu. Thank you so much for your contribution and apologize for the delay in reviewing it! Looks like the tests does not cover all the fields added (some nested subfields not been tested), I wonder if you've tested them locally. If you've not, not worries, I can working on testing them locally to make sure all added fields work.

2022-01-04 20:37 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic|TestAccApiGatewayApiConfigIamBindingGenerated|TestAccApigeeEnvironmentIamBindingGenerated|TestAccApiGatewayApiIamBindingGenerated|TestAccApiGatewayGatewayIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccArtifactRegistryRepositoryIamBindingGenerated|TestAccBigQueryTableIamBindingGenerated|TestAccBinaryAuthorizationAttestorIamBindingGenerated|TestAccCloudRunServiceIamBindingGenerated|TestAccCloudFunctionsCloudFunctionIamBindingGenerated|TestAccComputeDiskIamBindingGenerated|TestAccComputeImageIamBindingGenerated|TestAccComputeInstanceIamBindingGenerated|TestAccComputeMachineImageIamBindingGenerated|TestAccComputeRegionDiskIamBindingGenerated|TestAccComputeSubnetworkIamBindingGenerated|TestAccDataCatalogEntryGroupIamBindingGenerated|TestAccDataCatalogPolicyTagIamBindingGenerated|TestAccDataCatalogTagTemplateIamBindingGenerated|TestAccDataCatalogTaxonomyIamBindingGenerated|TestAccServiceManagementServiceIamBindingGenerated|TestAccHealthcareConsentStoreIamBindingGenerated|TestAccIapAppEngineVersionIamBindingGenerated|TestAccIapAppEngineServiceIamBindingGenerated|TestAccIapTunnelInstanceIamBindingGenerated|TestAccIapWebBackendServiceIamBindingGenerated|TestAccIapTunnelIamBindingGenerated|TestAccIapWebIamBindingGenerated|TestAccIapWebTypeAppEngineIamBindingGenerated|TestAccNotebooksInstanceIamBindingGenerated|TestAccNotebooksRuntimeIamBindingGenerated|TestAccPrivatecaCaPoolIamBindingGenerated|TestAccPubsubTopicIamBindingGenerated|TestAccRuntimeConfigConfigIamBindingGenerated|TestAccIapWebTypeComputeIamBindingGenerated|TestAccSecretManagerSecretIamBindingGenerated|TestAccServiceDirectoryNamespaceIamBindingGenerated|TestAccServiceDirectoryServiceIamBindingGenerated|TestAccSourceRepoRepositoryIamBindingGenerated|TestAccStorageBucketIamBindingGenerated|TestAccCloudFunctionsFunction_vpcConnector|TestAccComposerEnvironment_ComposerV2|TestAccComposerEnvironment_composerV1MasterAuthNetworks|TestAccComposerEnvironment_composerV2MasterAuthNetworks|TestAccComposerEnvironment_composerV1MasterAuthNetworksUpdate|TestAccComposerEnvironment_composerV2MasterAuthNetworksUpdate|TestAccComputeBackendService_withBackend|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeBackendService_withMaxConnections|TestAccComputeBackendService_withMaxConnectionsPerInstance|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeForwardingRule_update|TestAccInstanceGroupManager_targetSizeZero|TestAccInstanceGroupManager_basic|TestAccInstanceGroupManager_update|TestAccInstanceGroupManager_versions|TestAccInstanceGroupManager_stateful|TestAccInstanceGroupManager_autoHealingPolicies|TestAccInstanceGroupManager_waitForStatus|TestAccComputePerInstanceConfig_update|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionAutoscaler_scaleDownControl|TestAccComputeRegionAutoscaler_scalingSchedule|TestAccComputeRegionAutoscaler_scaleInControl|TestAccComputeRegionBackendService_withBackendInternal|TestAccComputeRegionBackendService_withBackendInternalManaged|TestAccComputeRegionBackendService_withBackendMultiNic|TestAccRegionInstanceGroupManager_basic|TestAccRegionInstanceGroupManager_targetSizeZero|TestAccRegionInstanceGroupManager_versions|TestAccRegionInstanceGroupManager_update|TestAccRegionInstanceGroupManager_autoHealingPolicies|TestAccRegionInstanceGroupManager_distributionPolicy|TestAccRegionInstanceGroupManager_stateful|TestAccComputeRegionPerInstanceConfig_update|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccFolderIamAuditConfig_basic|TestAccFolderIamAuditConfig_update|TestAccFolderIamAuditConfig_removeLastExemptMember|TestAccFolderIamAuditConfig_addFirstExemptMember|TestAccFolderIamBinding_update|TestAccProjectIamAuditConfig_basic|TestAccProjectIamAuditConfig_multiple|TestAccProjectIamAuditConfig_update|TestAccProjectIamAuditConfig_removeLastExemptMember|TestAccProjectIamAuditConfig_addFirstExemptMember|TestAccProjectIamBinding_multiple|TestAccProjectIamBinding_update|TestAccProjectIamPolicy_expanded|TestAccProjectIamPolicy_expandedAuditConfig|TestAccProjectIamPolicy_basicAuditConfig|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample|TestAccStorageBucketAcl_basic|TestAccStorageBucketAcl_upgrade|TestAccStorageBucketAcl_upgradeSingleUser|TestAccStorageBucketAcl_downgrade|TestAccStorageBucketAcl_unordered|TestAccStorageBucketAcl_RemoveOwner|TestAccStorageDefaultObjectAcl_basic|TestAccStorageDefaultObjectAcl_upgrade|TestAccStorageDefaultObjectAcl_unordered|TestAccStorageDefaultObjectAcl_downgrade|TestAccStorageObjectAcl_basic|TestAccStorageObjectAcl_upgrade|TestAccStorageObjectAcl_downgrade|TestAccStorageObjectAcl_explicitToPredefined|TestAccStorageObjectAcl_unordered|TestAccStorageObjectAcl_predefinedToExplicit|TestAccTags You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=239616

2022-01-06 00:17 UTC, chez-shanpu commented
Hi @shuyama1 ! Thank you for reviewing!
I've only checked it by the tests in `resource_monitoring_alert_policy_test.go`. I appreciate it if you work on.

2022-01-06 00:17 UTC, shuyama1 requested changes
All new fields added should be covered in at least one acceptance test. 
The rest of the code looks good to me!

2022-01-06 00:17 UTC, shuyama1 commented on mmv1/third_party/terraform/tests/resource_monitoring_alert_policy_test.go
> +    }
```suggestion
      label_extractors = {
        "test" = "EXTRACT(protoPayload.request)"
      }
    }
```

2022-01-06 00:21 UTC, shuyama1 commented
> Hi @shuyama1 ! Thank you for reviewing! I've only checked it by the tests in `resource_monitoring_alert_policy_test.go`. I appreciate it if you work on.

Just added my suggestions! It should be good after we cover everything in the tests. (I just tested them locally and it worked, but feel we'd better add them in the acceptance tests)

2022-01-06 00:27 UTC, shuyama1 commented
@chez-shanpu please re-request my review after you've done editing. You can simply accept the changes or feel free to add your own tests!

2022-01-06 00:38 UTC, chez-shanpu commented on mmv1/third_party/terraform/tests/resource_monitoring_alert_policy_test.go
> +  }
Thank you! I've fixed it :)

2022-01-06 00:39 UTC, chez-shanpu commented on mmv1/third_party/terraform/tests/resource_monitoring_alert_policy_test.go
> +    }
I fixed it too :)

2022-01-06 00:51 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 363 insertions(+), 22 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 359 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2022-01-06 01:08 UTC, shuyama1 approved these changes

2022-01-06 01:09 UTC, shuyama1 commented
/gcbrun

2022-01-06 01:21 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 381 insertions(+), 40 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 359 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2022-01-06 18:33 UTC, shuyama1 commented
@melinath @ScottSuarez  Could either of you help me figure out why TFV tests are failing here? Thanks a lot!

2022-01-06 18:52 UTC, ScottSuarez commented
/gcbrun
We just committed some changes to the test strategy. 

User might need to rebase... lets rerun and see.

2022-01-06 18:55 UTC, shuyama1 commented
> /gcbrun We just committed some changes to the test strategy.
> 
> User might need to rebase... lets rerun and see.

Thanks!

2022-01-06 19:05 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 341 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 341 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2022-01-06 19:05 UTC, ScottSuarez commented
ah looks like this failure is related to https://github.com/GoogleCloudPlatform/terraform-validator/issues/323

wdyt stephen?...

We will try to fix this soon to make the pipeline more stable

2022-01-06 19:05 UTC, ScottSuarez commented
@melinath

2022-01-06 19:09 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 363 insertions(+), 22 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 3 files changed, 341 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 1 file changed, 107 insertions(+))

2022-01-06 19:11 UTC, melinath commented
yes, I agree this seems to be an ordering issue - the new field isn't yet present in the provider. For now our workaround has been to temporarily disable the tests for that resource until the new fields have been added to the provider and the provider dependency can be upgraded. @shuyama1 You can do this by moving the relevant test files from [mmv1/third_party/validator/tests/data](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/validator/tests/data) to [mmv1/third_party/validator/tests/data-ignored](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/validator/tests/data-ignored)

2022-01-06 19:15 UTC, shuyama1 commented
Sure. will do that! Thanks @ScottSuarez and @melinath for the help!

2022-01-06 20:20 UTC, shuyama1 requested changes
Hey @chez-shanpu! Would you mind rebase to the top and move the three files `example_monitoring_alert_policy.json`, `example_monitoring_alert_policy.tf` and `example_monitoring_alert_policy.tfplan.json` from [mmv1/third_party/validator/tests/data](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/validator/tests/data) to [mmv1/third_party/validator/tests/data-ignored](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/mmv1/third_party/validator/tests/data-ignored), as currently the TFV tests are failing. Sorry for the extra work!

2022-01-06 20:53 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccMonitoringAlertPolicy|TestAccTags You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=240548

2022-01-07 02:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 359 insertions(+), 18 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5565-old..auto-pr-5565) ( 4 files changed, 381 insertions(+), 40 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5565-old..auto-pr-5565) ( 6 files changed, 107 insertions(+), 295 deletions(-))

2022-01-07 18:04 UTC, shuyama1 approved these changes
Looks good! Thank you so much for your contribution!

2022-01-07 18:07 UTC, merged