enable vpc access connector resource
GoogleCloudPlatform/magic-modules pull request #5592
Opened 2022-01-05 09:07 UTC by prateek2408

This change enabled magic modules to generate a resource for vpc access connector. This resource would then be used in Terraform Validator.

part of {https://github.com/hashicorp/terraform-provider-google/issues/10756}

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource

```

2022-01-05 09:08 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@scottsuarez, please review this PR or find an appropriate assignee.

2022-01-05 09:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 18 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 1 insertion(+))

2022-01-05 23:19 UTC, ScottSuarez commented
/gcbrun

2022-01-05 23:32 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 1 insertion(+))

2022-01-06 01:27 UTC, ScottSuarez commented
Are there relevant tests for this new resource?

Could you add one if not?

2022-01-06 01:34 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccContainerCluster_withBootDiskKmsKey|TestAccContainerNodePool_withInvalidUpgradeSettings|TestAccTags You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=240147

2022-01-06 10:49 UTC, prateek2408 commented
> 

@ScottSuarez - The test needs to be added for this resource in terraform validator repo right ?

2022-01-06 18:55 UTC, ScottSuarez commented
No no, can be added in this repo. We copy them over

Look at `mmv1/third_party/validator/tests/data`

2022-01-11 12:36 UTC, prateek2408 commented
@ScottSuarez - Thanks for the info. I am writing the test cases for this resource

2022-01-11 12:49 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 22 insertions(+), 22 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 1 insertion(+))

2022-01-14 07:42 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 18 insertions(+), 18 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 6 files changed, 131 insertions(+))

2022-01-14 10:10 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5592-old..auto-pr-5592) ( 1 file changed, 22 insertions(+), 22 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 6 files changed, 141 insertions(+))

2022-01-19 23:23 UTC, melinath requested changes
It looks like the conversion tests are failing due to this diff:

```diff
13c13
<     (string) (len=13) "maxThroughput": (float64) 1000,
---
>     (string) (len=13) "maxThroughput": (float64) 300,
```

This seems to be because max_throughput has a [default of 300 in the Terraform provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/vpc_access_connector#argument-reference), so you'd need to either update the expected value or add an explicit field to the TF config.

2022-01-19 23:23 UTC, melinath commented on mmv1/third_party/validator/tests/data/example_vpc_access_connector.json
> +                "maxThroughput": 1000,
```suggestion
                "maxThroughput": 300,
```

2022-01-19 23:23 UTC, melinath commented on mmv1/third_party/validator/tests/data/example_vpc_access_connector.tfplan.json
> +                    "max_throughput": 1000,
```suggestion
                    "max_throughput": 300,
```

2022-01-20 08:47 UTC, prateek2408 commented
@melinath - Thanks for pointing this out. I have made the necessary changes to the code.

2022-01-20 08:59 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5592-old..auto-pr-5592) ( 6 files changed, 141 insertions(+))

2022-01-20 16:24 UTC, melinath approved these changes
LGTM

2022-01-20 16:24 UTC, merged