Enable usage of gcp filestore csi driver
GoogleCloudPlatform/magic-modules pull request #5648
Opened 2022-01-26 12:06 UTC by grieshaber

This PR enables the usage of the FileStore CSI Driver addon for GKE clusters. 
It solves the issue https://github.com/hashicorp/terraform-provider-google/issues/10524 in the GA-Provider project.

@c2thorn asked me to create a PR in this repo instead directly in the provider repo.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added support for GCPFilestoreCSIDriver addon to `google_container_cluster` resource.
```

2022-01-26 12:07 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@rileykarson, please review this PR or find an appropriate assignee.

2022-01-26 12:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 82 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 82 insertions(+))

2022-01-26 19:13 UTC, c2thorn requested changes
Some changes in regard to testing

2022-01-26 19:13 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +	}
```suggestion
    }
    gcp_filestore_csi_driver_config {
      enabled = false
    }
```
spaces instead of tabs

2022-01-26 19:13 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +	}
```suggestion
    }
    gcp_filestore_csi_driver_config {
      enabled = false
    }
```
spaces instead of tabs

2022-01-26 19:13 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +	}
This may not be necessary if the Addon test above works fine

2022-01-26 19:13 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +				Config: testAccContainerCluster_withGcpFilestoreCsiDriverEnabled(pid, clusterName),
Just adding the field in the Addons and updateAddons configs should be fine. We could remove this to save some test time.

2022-01-26 19:13 UTC, c2thorn commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +func testAccContainerCluster_withGcpFilestoreCsiDriverEnabled(projectID string, clusterName string) string {
This could be removed, see above comment

2022-01-27 06:47 UTC, grieshaber commented
Thanks @c2thorn for your feedback. I applied your suggestions and removed the overhead test.

2022-01-27 06:59 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 82 insertions(+))

2022-01-27 17:58 UTC, c2thorn commented
Misclicked a button while scrolling....
I'll run the tests to ensure the feature works as intended.

2022-01-27 17:58 UTC, c2thorn commented
/gcbrun

2022-01-27 18:09 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))

2022-01-27 18:10 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))

2022-01-27 20:00 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic|TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudbuildWorkerPool_basic|TestAccComputeGlobalForwardingRule_externalCndLbWithBackendBucketExample|TestAccContainerCluster_withAddons You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=249195

2022-01-28 08:05 UTC, grieshaber commented
@c2thorn weird that the tests are failing, i checked the TestAccContainer-Test and it ran successfully. How can i access the test results (without a TeamCity login) to work on the issues?

2022-01-28 17:34 UTC, c2thorn commented
/gcbrun

2022-01-28 17:36 UTC, c2thorn commented
@grieshaber that last test run timed out due to unrelated reasons, so I would not worry about it. I believe your test did actually pass. Once this runs again, we should be good to go.

2022-01-28 17:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5648-old..auto-pr-5648) ( 3 files changed, 44 insertions(+))

2022-01-28 21:49 UTC, c2thorn approved these changes

2022-01-28 21:49 UTC, merged

2022-01-28 21:50 UTC, c2thorn commented
Test passed, so this is good. The change won't be a part of the next release, but the release after.