Add attribute reference to google_service_networking_connection
GoogleCloudPlatform/magic-modules pull request #5679
Opened 2022-02-04 14:41 UTC by carlpett

The `google_service_networking_connection` resource doesn't have an Attributes reference section. The resource currently exposes a `peering` field that should be documented.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

    - release-note:none

2022-02-04 14:41 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2022-02-04 14:42 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@c2thorn, please review this PR or find an appropriate assignee.

2022-02-04 14:55 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5679-old..auto-pr-5679) ( 1 file changed, 7 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5679-old..auto-pr-5679) ( 1 file changed, 7 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5679-old..auto-pr-5679) ( 1 file changed, 7 insertions(+))

2022-02-07 16:46 UTC, c2thorn requested changes
Thanks for getting started on this! I've copied the description of the field from the API exactly, we usually do something like that.

2022-02-07 16:46 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/r/service_networking_connection.html.markdown
> +    peering - (Computed) The name of the created peering.
```suggestion
* `peering` - (Computed) The name of the VPC Network Peering connection that was created by the service producer.
```

2022-02-07 16:47 UTC, c2thorn commented
/gcbrun

2022-02-07 17:00 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5679-old..auto-pr-5679) ( 1 file changed, 7 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5679-old..auto-pr-5679) ( 1 file changed, 7 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5679-old..auto-pr-5679) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-07 17:28 UTC, c2thorn approved these changes

2022-02-07 17:28 UTC, merged

2022-02-07 19:40 UTC, carlpett commented on mmv1/third_party/terraform/website/docs/r/service_networking_connection.html.markdown
> +    peering - (Computed) The name of the created peering.
Thanks! :+1: