add mutex for apigee_instance
GoogleCloudPlatform/magic-modules pull request #5701
Opened 2022-02-10 23:24 UTC by xuchenma

This PR adds a mutex for apigee_instance, so that multiple instances for the same org will be created in sequence.
Closing https://github.com/hashicorp/terraform-provider-google/issues/10525

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
apigee: fixed a bug where multiple `google_apigee_instance` could not be used on the same `google_apigee_organization`
```

2022-02-10 23:25 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@slevenick, please review this PR or find an appropriate assignee.

2022-02-10 23:38 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5701-old..auto-pr-5701) ( 1 file changed, 14 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5701-old..auto-pr-5701) ( 1 file changed, 14 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5701-old..auto-pr-5701) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-10 23:42 UTC, slevenick requested changes
I think we want to scope the lock to only Apigee Instances rather than the org in general. How about a mutex like "organizations/{{org_id}}/apigeeInstances"?

2022-02-15 01:03 UTC, slevenick commented
> Yes we want to lock only Apigee instances. I tried to change it to `"{{org_id}}/instances"`, but strangely, in my local testing, although it was able to create 2 instances in sequence, it failed to delete them, complaining `the resource is locked by another operation`. Could you explain more about what the syntax means? Or should I change it to exactly `organizations/{{org_id}}/apigeeInstances`?

I think that `organizations/{{org_id}}/apigeeInstances` should work, but I haven't tested it. That error message you saw, is that coming from the API or the Terraform provider? I haven't found anywhere in the provider that would produce that message, so maybe it's an API-side error about deletion?

2022-02-16 05:46 UTC, xuchenma commented
Thanks, I've changed it to `{{org_id}}/apigeeInstances` because {{org_id}} is in the form `organizations/xxx`(it contains the `organizations/` already). Local testing has also worked for me.

2022-02-16 05:59 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5701-old..auto-pr-5701) ( 1 file changed, 14 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5701-old..auto-pr-5701) ( 1 file changed, 14 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5701-old..auto-pr-5701) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-16 18:14 UTC, slevenick approved these changes

2022-02-16 18:14 UTC, merged