Add endpointAttachment in Apigee
GoogleCloudPlatform/magic-modules pull request #5717
Opened 2022-02-16 00:01 UTC by xuchenma

This PR adds a new resource EndpointAttachment in Apigee (https://github.com/hashicorp/terraform-provider-google/issues/11118)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
Add endpointAttachment in Apigee.
```

2022-02-16 00:03 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@c2thorn, please review this PR or find an appropriate assignee.

2022-02-16 00:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 645 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 645 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5717-old..auto-pr-5717) ( 3 files changed, 76 insertions(+), 3 deletions(-))

2022-02-16 01:22 UTC, xuchenma commented
I ran the Terraform test case locally, and it was able to CREATE, GET, DELETE this resource. However the test returns this error:
```
=== RUN   TestAccApigeeEndpointAttachment_apigeeEndpointAttachmentBasicTestExample
=== PAUSE TestAccApigeeEndpointAttachment_apigeeEndpointAttachmentBasicTestExample
=== CONT  TestAccApigeeEndpointAttachment_apigeeEndpointAttachmentBasicTestExample
    provider_test.go:278: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=4) {
         (string) (len=4) "host": (string) "",
         (string) (len=8) "location": (string) "",
         (string) (len=4) "name": (string) "",
         (string) (len=18) "service_attachment": (string) ""
        }
        
        
        (map[string]string) (len=4) {
         (string) (len=4) "host": (string) (len=7) "7.0.0.2",
         (string) (len=8) "location": (string) (len=8) "us-west2",
         (string) (len=4) "name": (string) (len=56) "organizations/apigee-tf-test-2/endpointAttachments/test1",
         (string) (len=18) "service_attachment": (string) (len=72) "projects/apigee-tf-test-2/regions/us-west2/serviceAttachments/my-psc-ilb"
        }
--- FAIL: TestAccApigeeEndpointAttachment_apigeeEndpointAttachmentBasicTestExample (645.56s)

```
I'm not sure what might go wrong here.

2022-02-17 19:58 UTC, c2thorn requested changes
I am still working on reproducing your issue, but running into difficulties with rate limiting in our testing environment.
While that is pending, I can immediately identify an issue: the resource names in your example file will need to be wrapped in ruby tags and referenced in the `terraform.yaml`.
This is for multiple reasons, but the primary one being so that we can append a random suffix to resource names to avoid collisions while testing our entire suite.

2022-02-17 19:58 UTC, c2thorn commented on mmv1/products/apigee/terraform.yaml
> +      test_env_vars:
will also need a `vars` block that defines variable names for each resource name. See https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/pubsublite/terraform.yaml#L51

2022-02-17 19:58 UTC, c2thorn commented on mmv1/templates/terraform/examples/apigee_endpoint_attachment_basic.tf.erb
> +  name = "apigee-network"
Each resource name should be wrapped in a ruby tag, see https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/templates/terraform/examples/pubsub_lite_subscription_basic.tf.erb

2022-02-18 06:26 UTC, xuchenma commented
That might not be needed for Apigee resources, because for Apigee, each test creates its own GCP project, run the test, and delete the project. So collisions won't happen. I see tests for other Apigee resources are all written this way (no ruby tags).

2022-02-21 19:49 UTC, xuchenma commented
I updated `mmv1/templates/terraform/custom_import/apigee_endpoint_attachment.go.erb` and it fixed the `ImportStateVerify` error; the tests are passing now.

2022-02-22 17:40 UTC, c2thorn commented
/gcbrun

2022-02-22 19:43 UTC, modular-magician commented
Tests were added that did not run in TeamCity:

- TestAccApigeeEndpointAttachment_apigeeEndpointAttachmentBasicTestExample

2022-02-22 19:43 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudbuildWorkerPool_basic|TestAccComputeInstanceTemplate_reservationAffinities|TestAccContainerCluster_withAuthenticatorGroupsConfig You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=260291

2022-02-22 20:46 UTC, c2thorn commented
VCR test passed from what is available, but apparently we need to skip VCR for the main test. Running the primary example test directly in our testing environment

2022-02-22 22:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 678 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 678 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5717-old..auto-pr-5717) ( 3 files changed, 76 insertions(+), 3 deletions(-))

2022-02-22 23:41 UTC, c2thorn approved these changes
Implementation LGTM, noting we still need to have a passing test, which is running now.

2022-02-23 20:06 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 681 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5717-old..auto-pr-5717) ( 5 files changed, 681 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5717-old..auto-pr-5717) ( 3 files changed, 76 insertions(+), 3 deletions(-))

2022-02-23 22:00 UTC, c2thorn commented
manual test succeeded!

2022-02-23 22:00 UTC, merged