prevent `google_container_cluster` from crashing if an empty `authenticator_groups_config` is supplied
GoogleCloudPlatform/magic-modules pull request #5740
Opened 2022-02-23 20:10 UTC by ScottSuarez

closes https://github.com/hashicorp/terraform-provider-google/issues/11144

prevent resource `container_cluster` from attempting to cast nil to `map[string]interface{}`

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
container: prevent `google_container_cluster` from crashing if an empty `authenticator_groups_config` block is supplied
```

2022-02-23 20:26 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5740-old..auto-pr-5740) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5740-old..auto-pr-5740) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5740-old..auto-pr-5740) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-02-23 23:11 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccCloudbuildWorkerPool_basic|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccEventarcTrigger_BasicHandWritten You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=261065

2022-02-24 19:43 UTC, ScottSuarez commented
Doesn't look like this block is defined in the tfv container cluster model
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/third_party/validator/container.go

2022-02-25 23:34 UTC, ScottSuarez commented
@melinath

2022-02-28 19:58 UTC, melinath requested changes
Would it be possible to make sure this is covered by a test?

2022-02-28 19:58 UTC, melinath commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +	if len(l) == 0 && l[0] != nil {
I'm a little confused by this - if `len(l) == 0` wouldn't `l[0]` not exist because `l` is empty? Should this be `||`?

2022-04-08 21:02 UTC, melinath commented
@ScottSuarez are you still working on this PR?

2022-04-08 21:19 UTC, ScottSuarez commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +	if len(l) == 0 && l[0] != nil {
```suggestion
	if len(l) == 0 || l[0] != nil {
```

2022-04-08 21:21 UTC, ScottSuarez commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +	if len(l) == 0 || l[0] != nil {
```suggestion
	if len(l) == 0 || l[0] == nil {
```

2022-04-08 21:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5740-old..auto-pr-5740) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5740-old..auto-pr-5740) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5740-old..auto-pr-5740) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-08 22:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1971` 
Passed tests `1732` 
Skipped tests: `238` 
Failed tests: `1` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic

2022-04-08 22:23 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5740/artifacts/2632846e-2cf3-43be-892c-8cd9e5941293/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5740/artifacts/2632846e-2cf3-43be-892c-8cd9e5941293/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5740/artifacts/2632846e-2cf3-43be-892c-8cd9e5941293/recording) for each test

2022-04-12 16:01 UTC, melinath requested changes
Could you make sure this case is covered by a test?

2023-02-08 21:51 UTC, closed without merging