Cloud SQL backup location samples for cgc
GoogleCloudPlatform/magic-modules pull request #5765
Opened 2022-03-01 02:07 UTC by betsy-lichtenberg

Planning to add these samples to this section:

https://cloud.google.com/sql/docs/sqlserver/backup-recovery/backing-up#locationbackups
https://cloud.google.com/sql/docs/mysql/backup-recovery/backing-up#locationbackups
https://cloud.google.com/sql/docs/postgres/backup-recovery/backing-up#locationbackups

```release-note:none
```

2022-03-01 02:21 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5765-old..auto-pr-5765) ( 1 file changed, 124 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5765-old..auto-pr-5765) ( 1 file changed, 124 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5765-old..auto-pr-5765) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-5765-old..auto-pr-5765) ( 3 files changed, 45 insertions(+))

2022-03-01 04:23 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample|TestAccCGCSnippet_sqlMysqlInstanceBackupLocationExample|TestAccCGCSnippet_sqlPostgresInstanceBackupLocationExample|TestAccContainerCluster_withAuthenticatorGroupsConfig You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=263096

2022-03-01 04:44 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccCGCSnippet_sqlMysqlInstanceBackupLocationExample|TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample|TestAccCGCSnippet_sqlPostgresInstanceBackupLocationExample Please fix these to complete your PR

2022-03-01 21:41 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5765-old..auto-pr-5765) ( 1 file changed, 125 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5765-old..auto-pr-5765) ( 1 file changed, 125 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5765-old..auto-pr-5765) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-5765-old..auto-pr-5765) ( 3 files changed, 46 insertions(+))

2022-03-03 18:30 UTC, melinath commented
It looks like this just adds new tests; they won't easily run in VCR right now so I'm running them manually here: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/264246.

2022-03-04 16:25 UTC, melinath requested changes
@betsy-lichtenberg could you resolve the merge conflict?

2022-03-04 17:08 UTC, betsy-lichtenberg commented
Starting over in a new PR

2022-03-04 17:08 UTC, closed without merging