Add support for aliases like composer-2 in Composer image version field
GoogleCloudPlatform/magic-modules pull request #5787
Opened 2022-03-04 16:02 UTC by swalkowski

This covers the new aliases for Composer major version ('composer-1', 'composer-2'), improved DiffSuppressFunc implementation for image version field, and updates to the related documentation.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
composer: Added support for `composer-1` and `composer-2` aliases in image version argument
```

2022-03-04 16:05 UTC, swalkowski commented
I prepared this draft PR but we shouldn't merge it now because Cloud Composer doesn't support the new aliases yet.

2022-03-04 16:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5787-old..auto-pr-5787) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-04 18:25 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataSourceSqlDatabaseInstance_basic|TestAccBigqueryReservationAssignment_BasicHandWritten|TestAccCGCSnippet_sqlSqlserverInstanceAuthorizedNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerFilenameExample|TestAccCloudBuildTrigger_cloudbuildTriggerBuildExample|TestAccCloudBuildTrigger_basic|TestAccCloudBuildTrigger_available_secrets_config|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_disable|TestAccCloudBuildTrigger_fullStep|TestAccContainerCluster_withAuthenticatorGroupsConfig You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=264759

2022-03-04 18:51 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_withAuthenticatorGroupsConfig Please fix these to complete your PR

2022-03-15 10:14 UTC, swalkowski commented
The new aliases are now available in Cloud Composer so the change can be merged. Please review, thanks!

2022-03-15 16:17 UTC, c2thorn commented
/gcbrun

2022-03-15 16:32 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5787-old..auto-pr-5787) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-16 09:27 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5787-old..auto-pr-5787) ( 4 files changed, 76 insertions(+), 40 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5787-old..auto-pr-5787) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-16 15:59 UTC, swalkowski commented
Today I synced my branch with upstream but `generate-diffs` failed again, with no clear message in Cloud Build log besides `context deadline exceeded` at the end. And I don't have access to https://ci-oss.hashicorp.engineering/ to check detailed results of the earlier VCR tests run.

2022-03-17 16:14 UTC, c2thorn requested changes
When a user specifies an alias, will the API return the non-aliased version? I assume yes because of the diff suppress, but just wanted to confirm.

~~Can we add an alias to one of the tests other than the DiffSuppress test? I want to ensure it is tested in something that actually deploys Composer resources.~~ Nevermind on this, the import verify step would fail because it doesn't apply diff suppresses.

2022-03-17 16:19 UTC, c2thorn commented
/gcbrun

2022-03-17 16:30 UTC, swalkowski commented
Yes, Composer API always returns a fully resolved image version for a created environment.

I thought about modifying one of the tests that create a Composer 2 environment to use the new alias. But we still need to set the Airflow major and minor versions, and these may change overtime for the most recent Composer 2 version.

2022-03-17 19:01 UTC, c2thorn commented
None of the failing tests are related to composer, merging.

2022-03-17 19:01 UTC, merged

2022-03-17 19:25 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_withAuthenticatorGroupsConfig Please fix these to complete your PR