Add support to enable read replicas on existing redis instances
GoogleCloudPlatform/magic-modules pull request #5793
Opened 2022-03-04 22:48 UTC by himanikh

Add ReadReplicasMode and secondaryIpRange support for Redis Update

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/master/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/master/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
redis:Added Multi read replica field `readReplicasMode` and `secondaryIpRange` in `google_redis_instance`
```

2022-03-04 22:49 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@rileykarson, please review this PR or find an appropriate assignee.

2022-03-04 22:53 UTC, himanikh commented
> Hello! I am a robot who works on Magic Modules PRs.
> 
> I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.
> 
> Thanks for your contribution! A human will be with you soon.
> 
> @rileykarson, please review this PR or find an appropriate assignee.

Stephen is already looking at this CL. https://github.com/GoogleCloudPlatform/magic-modules/pull/5724/files

2022-03-04 23:03 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 9 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5793-old..auto-pr-5793) ( 3 files changed, 38 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-05 01:25 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccRedisInstanceDatasource_basic|TestAccDataSourceSqlDatabaseInstance_basic|TestAccBigqueryReservationAssignment_BasicHandWritten|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample|TestAccCGCSnippet_sqlSqlserverInstanceAuthorizedNetworkExample|TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample|TestAccCloudBuildTrigger_cloudbuildTriggerFilenameExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_cloudbuildTriggerManualExample|TestAccCloudBuildTrigger_cloudbuildTriggerBuildExample|TestAccCloudBuildTrigger_basic|TestAccCloudBuildTrigger_available_secrets_config|TestAccCloudBuildTrigger_cloudbuildTriggerServiceAccountExample|TestAccCloudBuildTrigger_disable|TestAccCloudBuildTrigger_fullStep|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccRedisInstance_redisInstanceBasicExample|TestAccRedisInstance_update|TestAccRedisInstance_redisInstanceFullExample|TestAccRedisInstance_regionFromLocation|TestAccRedisInstance_redisInstanceAuthEnabled|TestAccRedisInstance_downgradeRedisVersion You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=264806

2022-03-05 01:52 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccRedisInstance_update Please fix these to complete your PR

2022-03-07 23:54 UTC, melinath commented
It looks like the only relevant test failure is TestAccRedisInstance_update. The failure is due to the following error:

```
Error: Instance cannot be destroyed
Resource google_redis_instance.test has lifecycle.prevent_destroy set, but the
plan calls for this resource to be destroyed. To avoid this error and continue
with the plan, either disable lifecycle.prevent_destroy or reduce the scope of
the plan using the -target flag.
```

Basically the problem is that the redis instance test [prevents deletion](https://github.com/GoogleCloudPlatform/magic-modules/blame/c2591b9b779b4d1563de576c73eeb322bcf163f6/mmv1/third_party/terraform/tests/resource_redis_instance_test.go#L218) so that it can verify that [updatable fields get updated](https://github.com/GoogleCloudPlatform/magic-modules/pull/4838#pullrequestreview-675597987). Adding these two input fields to the test config means that the instance would need to be deleted and recreated (which is disallowed).

The fix for this would probably be to add a new step to the update test [after the deletion prevention is removed](https://github.com/GoogleCloudPlatform/magic-modules/blame/c2591b9b779b4d1563de576c73eeb322bcf163f6/mmv1/third_party/terraform/tests/resource_redis_instance_test.go#L37) and add these fields only in that step.

2022-03-08 18:35 UTC, melinath requested changes
marking review requested to remove from review queue

2022-03-09 17:43 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 57 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5793-old..auto-pr-5793) ( 3 files changed, 86 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-15 11:53 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 70 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5793-old..auto-pr-5793) ( 3 files changed, 99 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-15 20:09 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccApikeysKey_AndroidKey|TestAccApikeysKey_BasicKey|TestAccApikeysKey_IosKey|TestAccApikeysKey_MinimalKey|TestAccApikeysKey_ServerKey|TestAccArtifactRegistryRepository_create_mvn_snapshot|TestAccArtifactRegistryRepository_create_mvn_release|TestAccCGCSnippet_sqlMysqlInstanceBackupExample|TestAccCGCSnippet_sqlPostgresInstanceBackupExample|TestAccCGCSnippet_sqlSqlserverInstanceBackupExample|TestAccCGCSnippet_sqlMysqlInstanceAuthorizedNetworkExample|TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample|TestAccCloudFunctionsFunction_secretEnvVar|TestAccContainerAwsCluster_BasicHandWritten|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccContainerNodePool_gvnic|TestAccDataprocCluster_nonPreemptibleSecondary|TestAccDataprocCluster_updatable|TestAccDataprocCluster_withConfigOverrides|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccNetworkServicesEdgeCacheOrigin_networkServicesEdgeCacheOriginAdvancedExample|TestAccNetworkServicesEdgeCacheOrigin_updateAndImport|TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceAdvancedExample|TestAccNetworkServicesEdgeCacheService_updateAndImport|TestAccRedisInstance_update|TestAccRedisInstance_updateReadReplicasMode You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=268604

2022-03-16 10:10 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 70 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5793-old..auto-pr-5793) ( 3 files changed, 99 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5793-old..auto-pr-5793) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-16 15:29 UTC, melinath commented
re-running the tests because they timed out yesterday /gcbrun

2022-03-16 19:09 UTC, modular-magician commented
Tests failed during RECORDING mode: TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccCGCSnippet_sqlMysqlInstanceBackupExample|TestAccRedisInstance_updateReadReplicasMode|TestAccNetworkServicesEdgeCacheService_updateAndImport|TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceAdvancedExample Please fix these to complete your PR

2022-04-01 20:58 UTC, melinath requested changes
This is blocked - please re-request review when it's ready. Marking as "changes requested" to remove from the review queue for now.

2022-04-20 17:16 UTC, closed without merging