Add missing ViewDefinition property 'query'
GoogleCloudPlatform/magic-modules pull request #5846
Opened 2022-03-23 16:58 UTC by cerih

Add missing BigQuery ViewDefinition 'query' string.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
bigquery: Add missing 'query' property to view definition
```

2022-03-23 17:03 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@melinath, please review this PR or find an appropriate assignee.

2022-03-25 18:12 UTC, melinath requested changes
Unfortunately it looks like this particular resource is [not actually generated from the api definition](https://github.com/GoogleCloudPlatform/magic-modules/blob/659a0c2c220d84de0b040c55cecff06ba6f06f61/mmv1/products/bigquery/terraform.yaml#L354) If you'd like to contribute this change, you'll need to modify the following handwritten files:

- Add field to the resource: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/resources/resource_bigquery_table.go
- Add this field to a test: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_bigquery_table_test.go
- Update the docs: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/bigquery_table.html.markdown

2022-03-26 08:11 UTC, cerih commented
Hi

My motivation has been Ansible support for the `query` field in view so I have not been considering Terraform to date.

My diff submitted reflects the missing `query` parameter as described here https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#ViewDefinition

It looks like the `query` field is already present in all the Terraform related files you have directed me to so am not sure now what further changes you would like me to address.

See https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/resources/resource_bigquery_table.go lines 646-660

			// View: [Optional] If specified, configures this table as a view.
			"view": {
				Type:        schema.TypeList,
				Optional:    true,
				MaxItems:    1,
				Description: `If specified, configures this table as a view.`,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						// Query: [Required] A query that BigQuery executes when the view is
						// referenced.
						"query": {
							Type:        schema.TypeString,
							Required:    true,
							Description: `A query that BigQuery executes when the view is referenced.`,
						},

in tests at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_bigquery_table_test.go   lines 1531-1534
  
```go
view {
    query          = "SELECT state FROM [lookerdata:cdc.project_tycho_reports]"
    use_legacy_sql = true
  }
```

and in the documentation https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/bigquery_table.html.markdown#nested_view

I am happy to make more changes as requested - but having followed your guidance it looks to me like the Terraform code is already ahead of the product file change I have submitted in this PR.

2022-03-28 15:59 UTC, melinath commented
Ah, the ansible provider is no longer generated from Magic Modules. You will need to contribute any changes directly to the ansible provider. Apologies for the confusion.

2022-03-28 15:59 UTC, closed without merging