Add mutex to `google_tags_tag_binding`
GoogleCloudPlatform/magic-modules pull request #5878
Opened 2022-03-31 18:26 UTC by ScottSuarez

closes: https://github.com/hashicorp/terraform-provider-google/issues/11381

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
tags: fixed issue where tags could not be applied sequentially to the same parent in `google_tags_tag_binding`
```

2022-03-31 18:40 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5878-old..auto-pr-5878) ( 1 file changed, 14 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5878-old..auto-pr-5878) ( 1 file changed, 14 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5878-old..auto-pr-5878) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-31 19:24 UTC, rileykarson commented
Drive-by comment: Is this mutex on the right parent? The error message suggests we need it on the resource, not the tag value: `Error: Error creating TagBinding: googleapi: Error 400: Resource '//cloudresourcemanager.googleapis.com/projects/XXXXXX' has another tag binding operation in progress.
with google_tags_tag_binding.bindings["fooo"],`

2022-04-01 21:37 UTC, melinath approved these changes
lgtm assuming tests pass and this should share with tagvalue

2022-04-01 21:45 UTC, melinath requested changes
Okay, tags are a little weird because the resources each have a parent key and it means a different thing for each one. For tagKey parent is the organization; for tagValue the parent is a tagKey; for tagBinding the parent is the resource the tag value is being applied to. So tagBinding and tagValue would never overlap in terms of their mutex.

2022-04-01 21:45 UTC, melinath commented on mmv1/products/tags/terraform.yaml
> +    mutex: tagValues/{{parent}}
```suggestion
    mutex: tagBindings/{{parent}}
```

2022-04-05 19:30 UTC, ScottSuarez commented on mmv1/products/tags/terraform.yaml
> +    mutex: tagValues/{{parent}}
Thanks for being so thorough !

2022-04-05 19:40 UTC, ScottSuarez commented
> Drive-by comment: Is this mutex on the right parent? The error message suggests we need it on the resource, not the tag value: `Error: Error creating TagBinding: googleapi: Error 400: Resource '//cloudresourcemanager.googleapis.com/projects/XXXXXX' has another tag binding operation in progress. with google_tags_tag_binding.bindings["fooo"],`

Should be the correct resource. This is done on the resource through the parent link supplied. Stopping sequential bindings on eq parent links should solve the issue afaik

2022-04-05 19:45 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5878-old..auto-pr-5878) ( 1 file changed, 14 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5878-old..auto-pr-5878) ( 1 file changed, 14 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5878-old..auto-pr-5878) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-05 19:54 UTC, rileykarson commented
> Should be the correct resource. This is done on the resource through the parent link supplied. Stopping sequential bindings on eq parent links should solve the issue afaik

Ah, I thought `parent` referred to the TagValue for some reason and not the linked resource. Should have double-checked. Thanks!

2022-04-05 20:10 UTC, melinath approved these changes
lgtm

2022-04-05 20:23 UTC, modular-magician commented
Tests count: 
Total tests: 1965 
Passed tests 1726 
Skipped tests: 237 
Failed tests: 2

2022-04-05 20:23 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccAccessContextManager|TestAccContainerCluster_withAuthenticatorGroupsConfig

2022-04-05 20:27 UTC, modular-magician commented
Tests failed during RECORDING mode:
 TestAccAccessContextManager
TestAccContainerCluster_withAuthenticatorGroupsConfig 

Please fix these to complete your PR
You can view the build log here: https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5878/artifacts/d2b05730-7e81-4cc9-885f-d4f86402a17a/build-log/recording_test.log and the debug log for each test here: https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5878/artifacts/d2b05730-7e81-4cc9-885f-d4f86402a17a/recording

2022-04-07 19:33 UTC, ScottSuarez commented
API team is working to add support for this, checking this code in while they work on it b/228352372

2022-04-07 19:33 UTC, merged