Dataproc metastore - add missing args
GoogleCloudPlatform/magic-modules pull request #5882
Opened 2022-03-31 21:41 UTC by DrFaust92

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
metastore: add `endpoint_protocol`,  `database_type`, `release_channel `, `network_config` arguments and `uid` attribute to `dataproc_metastore_service`
```

2022-03-31 21:55 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 46 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 293 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-03-31 22:29 UTC, Noremac201 commented
Thanks for doing this I was actually in the middle of adding PSC support, but I'll let you take over.

A minor nit is that some of these are preview only like `networkConfig`, can you add `min_version: beta` to that?

2022-03-31 22:30 UTC, Noremac201 commented on mmv1/products/metastore/api.yaml
> +        name: 'networkConfig'
Can you add `min_version: beta` here?

2022-03-31 22:32 UTC, Noremac201 requested changes

2022-03-31 22:36 UTC, nitikhadapkar commented on mmv1/products/metastore/api.yaml
> +              - !ruby/object:Api::Type::String
Network field is internal, theres no support for it and it should not be exposed.

2022-04-01 04:34 UTC, DrFaust92 commented on mmv1/products/metastore/api.yaml
> +        name: 'networkConfig'
Done, thanks!

2022-04-01 04:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 46 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 293 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-01 06:14 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 277 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-01 17:57 UTC, slevenick commented
Is this ready for review? It's marked draft still

2022-04-01 18:39 UTC, DrFaust92 commented
Basic test passes but I haven’t fully tested all new attributes yet. If
there are any comments meanwhile that’s great as well 😊

On Fri, 1 Apr 2022 at 20:57 Sam Levenick ***@***.***> wrote:

> Is this ready for review? It's marked draft still
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/5882#issuecomment-1086184605>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIA2W7UTI2H6A425LW6IFBLVC42JDANCNFSM5SGYYXIQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-12 06:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1980` 
Passed tests `1734` 
Skipped tests: `240` 
Failed tests: `6` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataprocCluster_withMetastoreConfig|TestAccDataprocMetastoreService_updateAndImport|TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample|TestAccDataprocMetastoreService_dataprocMetastoreServiceCmekTestExample|TestAccDataprocMetastoreServiceDatasource_basic|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-12 08:39 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataprocMetastoreServiceDatasource_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDataprocMetastoreServiceDatasource_basic.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceCmekTestExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceCmekTestExample.log)]
`TestAccDataprocMetastoreService_updateAndImport`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDataprocMetastoreService_updateAndImport.log)]
`TestAccDataprocCluster_withMetastoreConfig`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDataprocCluster_withMetastoreConfig.log)]
`TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDataprocMetastoreService_dataprocMetastoreServiceBasicExample.log)]
`TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/a3317677-4a32-4b2e-a76f-40b60a8f3f9e/recording) for each test

2022-04-12 18:13 UTC, slevenick requested changes
The changes look reasonable, but can you add a test that uses these settings? Especially the `consumers` block, but ideally all the new fields

2022-04-15 19:43 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 339 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-15 20:30 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1987` 
Passed tests `1744` 
Skipped tests: `240` 
Failed tests: `3` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccDataprocMetastoreService_networking|TestAccComputeForwardingRule_update

2022-04-15 20:46 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeForwardingRule_update`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/76201a8a-a5fc-4f51-b292-f2ae080f788b/recording/TestAccComputeForwardingRule_update.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/76201a8a-a5fc-4f51-b292-f2ae080f788b/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/76201a8a-a5fc-4f51-b292-f2ae080f788b/recording/TestAccDataprocMetastoreService_networking.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/76201a8a-a5fc-4f51-b292-f2ae080f788b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/76201a8a-a5fc-4f51-b292-f2ae080f788b/recording) for each test

2022-04-15 21:03 UTC, slevenick commented
Looks like the Dataproc Metastore test fails with:
`    provider_test.go:309: Step 1/2 error: Check failed: Check 1/1 error: google_dataproc_metastore_service.my_metastore: Attribute 'network_config.0.consumers.0.endpoint_uri' expected to be set`

Are you able to run this test successfully locally?

2022-04-15 21:15 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick) actually having trouble with this locally i gave it a shot here to check if its an issue on my env.

2022-04-15 21:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 339 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-15 22:09 UTC, DrFaust92 commented
Interesting error on server side when i run locally the metastore tries to create, times out and deletes itself.

when looking at GCP logs explorer i find this:

```
peration failed with error: 
generic::invalid_argument: terraform apply failed, error: exit status 1, stderr: 
2022/04/15 14:54:22 [DEBUG] Using modified User-Agent: Terraform/0.12.31 Cloud SSA

Error: Error waiting to create Connector: Error waiting for Creating Connector: Error code 13, message: An internal error occurred: VPC Access connector failed to get healthy. Please check GCE quotas, logs and org policies and recreate.

  on main.tf line 68, in resource "google_vpc_access_connector" "vpc_connector":
  68: resource "google_vpc_access_connector" "vpc_connector" {



, stdout: 
```

2022-04-15 22:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 339 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-15 23:01 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1987` 
Passed tests `1745` 
Skipped tests: `240` 
Failed tests: `2` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataprocMetastoreService_networking|TestAccFirebaserulesRelease_BasicRelease

2022-04-15 23:09 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/25cd1e86-e598-4e01-b784-bf718626cb42/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/25cd1e86-e598-4e01-b784-bf718626cb42/recording/TestAccDataprocMetastoreService_networking.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/25cd1e86-e598-4e01-b784-bf718626cb42/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/25cd1e86-e598-4e01-b784-bf718626cb42/recording) for each test

2022-04-15 23:22 UTC, slevenick commented
Hmmm now it's getting the internal error 13. Not sure why that is happening, maybe a transient error in the service?

2022-04-16 19:08 UTC, DrFaust92 commented
Ive opened an internal ticket to investigate this as either there is so pre-req missing or https://cloud.google.com/dataproc-metastore/docs/psc-ilb#gcloud is wrong.

2022-04-18 16:31 UTC, Noremac201 commented
I looked into it, seems to be a transient issue on our side, a retry should work

2022-04-18 16:42 UTC, slevenick commented
/gcbrun

2022-04-18 16:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 339 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-18 17:44 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1987` 
Passed tests `1745` 
Skipped tests: `240` 
Failed tests: `2` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccDataprocMetastoreService_networking

2022-04-18 18:56 UTC, modular-magician commented
I have triggered VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataprocMetastoreService_networking|TestAccFirebaserulesRelease_BasicRelease|TestAccServiceNetworkingPeeredDNSDomain_basic You can view the result here: https://ci-oss.hashicorp.engineering/viewQueued.html?itemId=280970

2022-04-18 19:02 UTC, slevenick commented
Yikes, this is worrying!

```
=== CONT  TestAccDataprocMetastoreService_networking
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 585 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta.flattenDataprocMetastoreServiceNetworkConfigConsumers(...)
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/resource_dataproc_metastore_service.go:885
```

2022-04-18 23:22 UTC, Noremac201 commented on mmv1/products/metastore/api.yaml
> +          - !ruby/object:Api::Type::NestedObject
This is a list of NestedObjects
```
- !ruby/object:Api::Type::Array
  name: 'consumers'
  item_type: !ruby/object:Api::Type::NestedObject
```

2022-04-19 08:27 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 345 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-19 08:28 UTC, DrFaust92 commented on mmv1/products/metastore/api.yaml
> +          - !ruby/object:Api::Type::NestedObject
Thanks, fixed!

2022-04-19 09:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1987` 
Passed tests `1744` 
Skipped tests: `240` 
Failed tests: `3` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccDataprocMetastoreService_networking|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-19 09:31 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/35b619d4-0f63-4517-a9b6-95b5b7e3e737/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/35b619d4-0f63-4517-a9b6-95b5b7e3e737/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/35b619d4-0f63-4517-a9b6-95b5b7e3e737/recording/TestAccDataprocMetastoreService_networking.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/35b619d4-0f63-4517-a9b6-95b5b7e3e737/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/35b619d4-0f63-4517-a9b6-95b5b7e3e737/recording) for each test

2022-04-19 16:39 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick) I couldn't test earlier because of the transient service error above. but i can replicate this error. from what i can gather the metastore creates an ip address implicitly (and also removes it that way)

I think we need to add some retry on the subnet. but i wonder if its a bit out of scope for this PR. I can look into that and add some best effort 1/2 min retry.

2022-04-19 16:51 UTC, slevenick commented on mmv1/third_party/terraform/tests/resource_dataproc_metastore_service_test.go.erb
> +      consumers {
Spacing here needs fixing

2022-04-19 16:53 UTC, slevenick commented
> [slevenick](https://github.com/slevenick) I couldn't test earlier because of the transient service error above. but i can replicate this error. from what i can gather the metastore creates an ip address implicitly (and also removes it that way)
> 
> I think we need to add some retry on the subnet deletion. but i wonder if its a bit out of scope for this PR. I can look into that and add some best effort 1/2 min retry.

I don't think the problem here is on the subnetwork side. It seems like metastore creates the ip address but doesn't completely remove it before considering itself deleted, which makes Terraform attempt to delete the subnetwork before the dependency is removed.

I believe this is a metastore bug, as it should fully clean up itself and any subresources before considering itself finished deleting

2022-04-19 19:24 UTC, DrFaust92 commented on mmv1/third_party/terraform/tests/resource_dataproc_metastore_service_test.go.erb
> +      consumers {
done

2022-04-19 19:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 345 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-19 20:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1989` 
Passed tests `1748` 
Skipped tests: `240` 
Failed tests: `1` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDataprocMetastoreService_networking

2022-04-19 20:36 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/e315377b-97c6-4465-819c-fd25d56eeba5/recording/TestAccDataprocMetastoreService_networking.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/e315377b-97c6-4465-819c-fd25d56eeba5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/e315377b-97c6-4465-819c-fd25d56eeba5/recording) for each test

2022-04-26 08:25 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick), any thing i can do from my side?

2022-04-28 16:08 UTC, slevenick commented
@Noremac201 do you have any insight on the above issue with cleaning up the metastore IP address?

2022-04-29 01:58 UTC, Noremac201 commented
As part of deletion, we "fast-delete" the service and there is a grace period where we'd re-use all existing infrastructure, so it _is_ cleaned up eventually (the address) but not in the timespan of this test.

Spinning up a new network, creating a metastore, and then removing all of them is kind of an edge case, I'll bring it to the team to see how we want to tackle this.

However, for now, this is unfortunately expected.

2022-05-13 05:21 UTC, DrFaust92 commented
Sorry [slevenick](https://github.com/slevenick), was a way for a bit. will try it now

2022-05-13 05:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 57 insertions(+), 10 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 6 files changed, 351 insertions(+), 9 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-05-13 06:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2019` 
Passed tests `1772` 
Skipped tests: `242` 
Failed tests: `5` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccFirebaserulesRelease_BasicRelease|TestAccDataprocMetastoreService_networking|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-05-13 06:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording/TestAccDataprocMetastoreService_networking.log)]
`TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording/TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5882/artifacts/83c1bea1-ca8b-42f6-946b-2eb7c6530301/recording) for each test

2022-05-13 12:57 UTC, DrFaust92 commented
@slevenick, so i tired splitting the test config into 2 as suggested. it did not help. ill see if a i can use some default subnet to at least appease tests. Any example of doing this in any other test config i can rely on?

2022-05-16 12:00 UTC, DrFaust92 commented
@slevenick how would you feel if i add something like this? https://github.com/hashicorp/terraform-provider-aws/blob/6e8fe78d5d52229122afc6748d6ff021c4409ab3/internal/service/secretsmanager/secrets_data_source_test.go#L21-L50

2022-05-26 06:22 UTC, DrFaust92 commented
[Noremac201](https://github.com/Noremac201) any thoughts on the above?

2022-06-25 10:47 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 345 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-06-25 11:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2055` 
Passed tests `1824` 
Skipped tests: `226` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccFirebaserulesRelease_BasicRelease|TestAccDataprocMetastoreService_networking|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withAddons|TestAccSqlUser_mysqlDisabled </details>

2022-06-25 12:16 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccSqlUser_mysqlDisabled`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording/TestAccSqlUser_mysqlDisabled.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording/TestAccContainerCluster_withAddons.log)]
`TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording/TestAccDataprocMetastoreService_networking.log)]
`TestAccContainerCluster_withConfidentialNodes`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording/TestAccContainerCluster_withConfidentialNodes.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/ab3f13d4-0a01-4fb0-8c08-445b356c9bd1/recording) for each test

2022-06-25 12:26 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick) / [Noremac201](https://github.com/Noremac201) Ive opted to use a datasource for default network, locally tests pass. i hope not it will pass in CI

2022-06-25 12:36 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5882-old..auto-pr-5882) ( 1 file changed, 47 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5882-old..auto-pr-5882) ( 3 files changed, 337 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5882-old..auto-pr-5882) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-06-25 13:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2055` 
Passed tests `1826` 
Skipped tests: `226` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccDataprocMetastoreService_networking|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withAddons </details>

2022-06-25 13:34 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/fd6873fa-256b-468c-bc28-ef8a6af8244f/recording/TestAccContainerCluster_withAddons.log)]
`TestAccDataprocMetastoreService_networking`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/fd6873fa-256b-468c-bc28-ef8a6af8244f/recording/TestAccDataprocMetastoreService_networking.log)]
`TestAccContainerCluster_withConfidentialNodes`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/fd6873fa-256b-468c-bc28-ef8a6af8244f/recording/TestAccContainerCluster_withConfidentialNodes.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/fd6873fa-256b-468c-bc28-ef8a6af8244f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-5882/artifacts/fd6873fa-256b-468c-bc28-ef8a6af8244f/recording) for each test

2022-07-06 15:51 UTC, closed without merging

2022-11-28 22:54 UTC, zli82016 commented
Hello, @DrFaust92 , do you have the plan to continue working on this PR? Thanks.

2022-11-28 23:09 UTC, DrFaust92 commented
These should be supported already

2022-11-28 23:24 UTC, zli82016 commented
Thanks for your response. I checked the code. Yes, only the field `network_config` is not supported. Is it because the corner case which caused the test failing?