dns: Support Routing Policy in DNS Record Set
GoogleCloudPlatform/magic-modules pull request #5909
Opened 2022-04-07 16:46 UTC by kanata2

## Description

This PR implements Routing Policy in Cloud DNS's Record Set.

fixes https://github.com/hashicorp/terraform-provider-google/issues/11038

### Status
Reviewable. If you have an opinion about the API design, please let me know.

---

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

---

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dns: added `routing_policy` to `google_dns_record_set` resource
```

2022-04-07 16:47 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@shuyama1, please review this PR or find an appropriate assignee.

2022-04-07 17:01 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 1 file changed, 241 insertions(+), 29 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 1 file changed, 241 insertions(+), 29 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-08 19:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-08 19:55 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1972` 
Passed tests `1728` 
Skipped tests: `238` 
Failed tests: `6` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccAccessContextManager|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample|TestAccDNSRecordSet_routingPolicy|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-08 20:11 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample.log)]
`TestAccContainerCluster_withAuthenticatorGroupsConfig`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccContainerCluster_withAuthenticatorGroupsConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccAccessContextManager`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccAccessContextManager.log)]
`TestAccDNSRecordSet_routingPolicy`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording/TestAccDNSRecordSet_routingPolicy.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bfa6c992-f678-4e0c-af40-cda815e85709/recording) for each test

2022-04-10 13:32 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-10 14:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1972` 
Passed tests `1730` 
Skipped tests: `238` 
Failed tests: `4` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccFirebaserulesRelease_BasicRelease|TestAccDNSRecordSet_routingPolicy|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-10 14:29 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccDNSRecordSet_routingPolicy`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/recording/TestAccDNSRecordSet_routingPolicy.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/e47be747-5e73-43c6-aa92-b53fd7571bc2/recording) for each test

2022-04-10 14:32 UTC, kanata2 commented
Hi, @shuyama1
This PR is now ready for review.
Could you please check when you are available?

2022-04-25 02:13 UTC, kanata2 commented
@shuyama1 Sorry to bother you again. I really need this feature, is there any plan to release it soon...? 😭

2022-04-25 06:13 UTC, polaru commented
My company is also waiting for this to go live. :)

2022-04-25 07:01 UTC, shuyama1 commented
@kanata2 So sorry for the delay on this. Working on reviewing it now and will post my comment asap!

2022-04-25 22:28 UTC, shuyama1 requested changes

2022-04-26 01:53 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-26 01:53 UTC, kanata2 commented on mmv1/third_party/terraform/resources/resource_dns_record_set.go
> +									"region": {
The actual value to be specified is region, so I named it region.(however I will change it to location.)

2022-04-26 01:58 UTC, kanata2 commented on mmv1/third_party/terraform/resources/resource_dns_record_set.go
> +									"region": {
renamed!

2022-04-26 02:12 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-26 02:52 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1989` 
Passed tests `1746` 
Skipped tests: `240` 
Failed tests: `3` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccFirebaserulesRelease_BasicRelease|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-26 03:02 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/d86951b9-c29d-4527-a2cf-6d97c8d7f064/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/d86951b9-c29d-4527-a2cf-6d97c8d7f064/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/d86951b9-c29d-4527-a2cf-6d97c8d7f064/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/d86951b9-c29d-4527-a2cf-6d97c8d7f064/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/d86951b9-c29d-4527-a2cf-6d97c8d7f064/recording) for each test

2022-04-26 07:02 UTC, kanata2 commented
@shuyama1 
Fixed.
The failure of `TestAccServiceNetworkingPeeredDNSDomain_basic` seems not to be releated with this PR 🤔

2022-04-27 19:38 UTC, shuyama1 commented
Looks like the failing test `TestAccServiceNetworkingPeeredDNSDomain_basic` is not related. Running some local tests now.

2022-04-28 17:37 UTC, shuyama1 commented
Running VCR for the last time and will merge it if no related tests fail 
/gcbrun

2022-04-28 17:51 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5909-old..auto-pr-5909) ( 3 files changed, 394 insertions(+), 34 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5909-old..auto-pr-5909) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-28 18:35 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1995` 
Passed tests `1752` 
Skipped tests: `241` 
Failed tests: `2` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccServiceNetworkingPeeredDNSDomain_basic

2022-04-28 18:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bac99596-7ee4-45f5-ad6a-8b496305b5bf/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bac99596-7ee4-45f5-ad6a-8b496305b5bf/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bac99596-7ee4-45f5-ad6a-8b496305b5bf/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5909/artifacts/bac99596-7ee4-45f5-ad6a-8b496305b5bf/recording) for each test

2022-04-28 18:44 UTC, shuyama1 approved these changes
Thank you so much for your contribution!

2022-04-28 18:46 UTC, merged