Fixed database version
GoogleCloudPlatform/magic-modules pull request #5927
Opened 2022-04-12 17:43 UTC by betsy-lichtenberg

Was asked by Cloud SQL tech writer to use certain DB versions in samples.
b/228328679

```release-note:none
```

2022-04-12 17:58 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5927-old..auto-pr-5927) ( 1 file changed, 3 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5927-old..auto-pr-5927) ( 1 file changed, 3 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5927-old..auto-pr-5927) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-5927-old..auto-pr-5927) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-12 18:04 UTC, slevenick requested changes
I don't think we want to move to a less recent version of MySQL unless there is a good reason to

2022-04-12 18:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1980` 
Passed tests `1737` 
Skipped tests: `240` 
Failed tests: `3` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccCGCSnippet_sqlDatabaseInstanceMySqlExample|TestAccCGCSnippet_sqlMysqlInstanceReplicaExample

2022-04-12 18:55 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccCGCSnippet_sqlDatabaseInstanceMySqlExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/0e5f4081-407d-4684-b135-4858131e9fbe/recording/TestAccCGCSnippet_sqlDatabaseInstanceMySqlExample.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/0e5f4081-407d-4684-b135-4858131e9fbe/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCGCSnippet_sqlMysqlInstanceReplicaExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/0e5f4081-407d-4684-b135-4858131e9fbe/recording/TestAccCGCSnippet_sqlMysqlInstanceReplicaExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/0e5f4081-407d-4684-b135-4858131e9fbe/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/0e5f4081-407d-4684-b135-4858131e9fbe/recording) for each test

2022-04-14 19:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5927-old..auto-pr-5927) ( 3 files changed, 8 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5927-old..auto-pr-5927) ( 3 files changed, 8 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5927-old..auto-pr-5927) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-5927-old..auto-pr-5927) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-5927-old..auto-pr-5927) ( 20 files changed, 21 insertions(+), 21 deletions(-))

2022-04-14 20:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1982` 
Passed tests `1734` 
Skipped tests: `240` 
Failed tests: `8` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccCGCSnippet_sqlSqlserverInstanceBackupRetentionExample|TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample|TestAccCGCSnippet_sqlSqlserverInstanceAuthorizedNetworkExample|TestAccCGCSnippet_sqlSqlserverInstancePrivateIpExample|TestAccCGCSnippet_sqlSqlserverInstanceBackupExample|TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample|TestAccSQLDatabase_sqlDatabaseBasicExample

2022-04-14 21:27 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlDatabaseInstanceSqlserverExample.log)]
`TestAccCGCSnippet_sqlSqlserverInstancePrivateIpExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlSqlserverInstancePrivateIpExample.log)]
`TestAccSQLDatabase_sqlDatabaseBasicExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccSQLDatabase_sqlDatabaseBasicExample.log)]
`TestAccServiceNetworkingPeeredDNSDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccServiceNetworkingPeeredDNSDomain_basic.log)]
`TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlSqlserverInstanceBackupLocationExample.log)]
`TestAccCGCSnippet_sqlSqlserverInstanceBackupRetentionExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlSqlserverInstanceBackupRetentionExample.log)]
`TestAccCGCSnippet_sqlSqlserverInstanceAuthorizedNetworkExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlSqlserverInstanceAuthorizedNetworkExample.log)]
`TestAccCGCSnippet_sqlSqlserverInstanceBackupExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording/TestAccCGCSnippet_sqlSqlserverInstanceBackupExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5927/artifacts/858019b4-562d-45aa-a92e-488755474346/recording) for each test

2022-04-19 16:49 UTC, betsy-lichtenberg commented
> I don't think we want to move to a less recent version of MySQL unless there is a good reason to

Agreed. Changed to 8_0.

2022-04-19 16:54 UTC, slevenick approved these changes
Thanks!

2022-04-19 16:54 UTC, merged