add gke_backup_agent_config to google_container_cluster
GoogleCloudPlatform/magic-modules pull request #5940
Opened 2022-04-13 17:04 UTC by miticojo

This PR fixes [10970](https://github.com/hashicorp/terraform-provider-google/issues/10970) and add support for [GKE Backup](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/concepts/backup-for-gke) Agent addon in google_container_cluster.

Usage:
```
resource "google_container_cluster" "gke" {
  provider = google-beta
  ...
  addons_config {
     gke_backup_agent_config {
      enabled = true
    }
  }
}
```
If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
add gke_backup_agent_config to google_container_cluster
```

2022-04-13 17:05 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I have detected that you are a community contributor, so your PR will be assigned to someone with a commit-bit on this repo for initial review.

Thanks for your contribution!  A human will be with you soon.

@scottsuarez, please review this PR or find an appropriate assignee.

2022-04-13 17:19 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5940-old..auto-pr-5940) ( 2 files changed, 37 insertions(+))

2022-04-13 17:51 UTC, ScottSuarez commented
Is this feature available? I don't see it within the public documentation for the rest api
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AddonsConfig

2022-04-13 18:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1985` 
Passed tests `1741` 
Skipped tests: `240` 
Failed tests: `4` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withAddons|TestAccComputeForwardingRule_update|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-13 18:15 UTC, miticojo commented
> Is this feature available? I don't see it within the public documentation for the rest api https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AddonsConfig

It's available in the v1beta1
https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.AddonsConfig

2022-04-13 18:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/recording/TestAccContainerCluster_withAddons.log)]
`TestAccComputeForwardingRule_update`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/recording/TestAccComputeForwardingRule_update.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/d1a1c34e-2e13-4deb-ac1b-655841ca69be/recording) for each test

2022-04-13 19:23 UTC, ScottSuarez requested changes
Could you also add documentation for this field to 
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

2022-04-13 19:30 UTC, miticojo commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +        "addons_config.0.gke_backup_agent_config",
Sure, thanks

2022-04-13 20:00 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5940-old..auto-pr-5940) ( 1 file changed, 3 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5940-old..auto-pr-5940) ( 3 files changed, 40 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5940-old..auto-pr-5940) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-13 20:33 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1982` 
Passed tests `1741` 
Skipped tests: `240` 
Failed tests: `1` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-13 20:39 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/6d364f70-e5df-4661-9df1-e0f2ce8f6202/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/6d364f70-e5df-4661-9df1-e0f2ce8f6202/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/6d364f70-e5df-4661-9df1-e0f2ce8f6202/recording) for each test

2022-04-14 17:37 UTC, ScottSuarez approved these changes
lgtm

2022-04-14 17:39 UTC, ScottSuarez commented
Could you update the release note to follow the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md?rgh-link-date=2022-04-13T17%3A04%3A16Z)?

2022-04-15 06:25 UTC, miticojo commented
> Could you update the release note to follow the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md?rgh-link-date=2022-04-13T17%3A04%3A16Z)?

Done!

2022-04-15 06:40 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5940-old..auto-pr-5940) ( 1 file changed, 3 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5940-old..auto-pr-5940) ( 3 files changed, 40 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5940-old..auto-pr-5940) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-04-15 07:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1986` 
Passed tests `1745` 
Skipped tests: `240` 
Failed tests: `1` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic

2022-04-15 07:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/b6f1f6bd-3752-4811-94bd-f31a611c3fbc/recording/TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/b6f1f6bd-3752-4811-94bd-f31a611c3fbc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5940/artifacts/b6f1f6bd-3752-4811-94bd-f31a611c3fbc/recording) for each test

2022-04-15 08:53 UTC, miticojo commented
Sorry I've closed the PR by mistake

2022-04-18 17:01 UTC, merged