Add support for checker_type in uptime_check_config
GoogleCloudPlatform/magic-modules pull request #5987
Opened 2022-04-27 11:34 UTC by jrbarnard

This PR adds in support for the [checker_type field](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.uptimeCheckConfigs#checkertype) on the google_monitoring_uptime_check_config resource.

fixes https://github.com/hashicorp/terraform-provider-google/issues/11537

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
monitoring: Added `checker_type` field to `google_monitoring_uptime_check_config` resource
```

2022-04-27 11:35 UTC, jrbarnard commented
Sorry for the PR spam, trying to get my CLA email working correctly. I have not been able to run the acceptance tests

2022-04-27 11:35 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-04-27 11:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5987-old..auto-pr-5987) ( 3 files changed, 44 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5987-old..auto-pr-5987) ( 3 files changed, 44 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5987-old..auto-pr-5987) ( 3 files changed, 13 insertions(+), 3 deletions(-))

2022-04-27 12:34 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1992` 
Passed tests `1746` 
Skipped tests: `241` 
Failed tests: `5` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_update|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample|TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample

2022-04-27 12:36 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording/TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample.log)]
`TestAccMonitoringUptimeCheckConfig_update`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording/TestAccMonitoringUptimeCheckConfig_update.log)]
`TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording/TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields.log)]
`TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording/TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample.log)]
`TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording/TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/251e015d-98ad-4315-8e95-31c8dd8ed817/recording) for each test

2022-05-05 18:12 UTC, shuyama1 requested changes
Sorry for the delay on reviewing this PR.

2022-05-05 18:12 UTC, shuyama1 commented on mmv1/products/monitoring/api.yaml
> +        - :CHECKER_TYPE_UNSPECIFIED
We probably want to remove this value.

2022-05-09 08:25 UTC, jrbarnard commented on mmv1/products/monitoring/api.yaml
> +      name: checkerType
I've tested this and if you changed the monitoredResource away from `servicedirectory_service` to say `uptime_url` to be able to use the `STATIC_IP_CHECKERS` checkerType the api returns a 400 as you can't change the host. So I think it's fine to be not updateable. I'll set it to input: true

2022-05-09 09:00 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-5987-old..auto-pr-5987) ( 6 files changed, 42 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-5987-old..auto-pr-5987) ( 6 files changed, 46 insertions(+), 12 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-5987-old..auto-pr-5987) ( 3 files changed, 13 insertions(+), 3 deletions(-))

2022-05-09 09:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2013` 
Passed tests `1766` 
Skipped tests: `242` 
Failed tests: `5` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample|TestAccMonitoringUptimeCheckConfig_update|TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample

2022-05-09 09:47 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccMonitoringUptimeCheckConfig_update`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording/TestAccMonitoringUptimeCheckConfig_update.log)]
`TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording/TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields.log)]
`TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording/TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample.log)]
`TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording/TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-5987/artifacts/07e9f7b3-7728-4b8c-8f0d-91d56c5c00d9/recording) for each test

2022-05-11 19:49 UTC, shuyama1 approved these changes
LGTM! Thank you!

2022-05-11 19:49 UTC, merged