Add DynamicPortAllocation for Cloud NAT
GoogleCloudPlatform/magic-modules pull request #6022
Opened 2022-05-10 15:20 UTC by ichbinfrog

Adds the `enable_dynamic_port_allocation` (see equivalent on `enableDynamicPortAllocation` field in the [respective API](https://cloud.google.com/compute/docs/reference/rest/v1/routers)) field for the `google_compute_router_nat` resource.

Solves this issue: https://github.com/hashicorp/terraform-provider-google/issues/11052

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
> For the google_compute_router_nat resource this does not seem to apply

- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: Added `enable_dynamic_port_allocation` to `google_compute_router_nat`
```

2022-05-10 15:34 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6022-old..auto-pr-6022) ( 4 files changed, 44 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6022-old..auto-pr-6022) ( 3 files changed, 50 insertions(+), 10 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6022-old..auto-pr-6022) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-05-10 16:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2013` 
Passed tests `1780` 
Skipped tests: `231` 
Failed tests: `2` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccFirebaserulesRelease_BasicRelease|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample

2022-05-13 17:38 UTC, c2thorn requested changes
Hi @ichbinfrog 
Can you add an example of of this field in use or add it to an existing example? That way it will be tested for functionality.

2022-05-15 11:12 UTC, ichbinfrog commented
Thanks for the review @c2thorn.

Sorry if it's not the correct method but I've added in the latest commit tests for the different port allocation methods in `mmv1/third_party/terraform/tests` because of the following comment: `These examples are not used to autogenerate tests`.

2022-05-15 11:24 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6022-old..auto-pr-6022) ( 5 files changed, 61 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6022-old..auto-pr-6022) ( 4 files changed, 57 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6022-old..auto-pr-6022) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-05-15 12:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2019` 
Passed tests `1786` 
Skipped tests: `231` 
Failed tests: `2` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccComputeRouterNat_withPortAllocationMethods|TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample

2022-05-15 12:11 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeRouterNat_withPortAllocationMethods`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-6022/artifacts/b3ca5b8d-1779-4268-8b31-0e95640997b4/recording/TestAccComputeRouterNat_withPortAllocationMethods.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample`[[view](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-6022/artifacts/b3ca5b8d-1779-4268-8b31-0e95640997b4/recording/TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/vcr-test-logs/beta/refs/heads/auto-pr-6022/artifacts/b3ca5b8d-1779-4268-8b31-0e95640997b4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/vcr-test-logs/beta/refs/heads/auto-pr-6022/artifacts/b3ca5b8d-1779-4268-8b31-0e95640997b4/recording) for each test

2022-05-16 17:06 UTC, c2thorn approved these changes

2022-05-16 17:06 UTC, merged