Implement low-touch tpgtools integration.
GoogleCloudPlatform/magic-modules pull request #6038
Opened 2022-05-16 23:18 UTC by trodge

Make it possible to implement new DCL resources in tpgtools without modifying mmv1.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-downstream-tools), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2022-05-16 23:19 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @scottsuarez, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-05-26 18:28 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 68 insertions(+), 108 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 83 insertions(+), 111 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-05-26 19:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2028` 
Passed tests `916` 
Skipped tests: `226` 
Failed tests: `886` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccComputeAddress_internal|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceFromTemplate_overrideMetadataDotStartupScript|TestAccComputeInstance_networkTier|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_withBackendAndIAP|TestAccComputeRoute_hopInstance|TestAccComputeSharedVpc_basic|TestAccComputeTargetSslProxy_update|TestAccMonitoringAlertPolicy|TestAccComputeResourceUsageExportBucket|TestAccTPUNode_tpuNodeFullExample|TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample|TestAccVPCAccessConnector_vpcAccessConnectorThroughput|TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample|TestAccIapWebBackendServiceIamPolicyGenerated_withCondition|TestAccIapWebBackendServiceIamMemberGenerated_withCondition|TestAccIapWebBackendServiceIamBindingGenerated_withCondition|TestAccIapWebBackendServiceIamMemberGenerated|TestAccIapWebBackendServiceIamPolicyGenerated|TestAccIapWebBackendServiceIamBindingGenerated|TestAccIapTunnelInstanceIamPolicyGenerated_withCondition|TestAccIapTunnelInstanceIamMemberGenerated_withCondition|TestAccIapTunnelInstanceIamBindingGenerated_withCondition|TestAccIapTunnelInstanceIamPolicyGenerated|TestAccIapTunnelInstanceIamMemberGenerated|TestAccIapTunnelInstanceIamBindingGenerated|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccPrivatecaCertificate_privatecaCertificateCsrExample|TestAccPrivatecaCertificate_privatecaCertificateConfigExample|TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample|TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate|TestAccPrivatecaCertificateAuthority_subordinateCaCreatedInAwaitingUserActivation|TestAccPrivatecaCertificateAuthority_rootCaCreatedInStaged|TestAccMonitoringGroup_monitoringGroupSubgroupExample|TestAccPrivatecaCertificateAuthority_rootCaIsEnabledByDefault|TestAccMonitoringGroup_monitoringGroupBasicExample|TestAccMonitoringDashboard_update|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccNetworkManagementConnectivityTest_update|TestAccLoggingFolderSink_described|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccPrivatecaCaPool_updateCaOption|TestAccMonitoringDashboard_rowLayout|TestAccPrivatecaCaPool_privatecaCapoolEmptyPublishingOptions|TestAccMonitoringDashboard_gridLayout|TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline|TestAccMonitoringDashboard_basic|TestAccLoggingFolderSink_basic|TestAccMonitoringService_monitoringServiceCustomExample|TestAccLoggingBucketConfigOrganization_basic|TestAccLoggingBucketConfigBillingAccount_basic|TestAccLoggingBucketConfigFolder_basic|TestAccLoggingProjectSink_loggingbucket|TestAccLoggingBillingAccountSink_heredoc|TestAccLoggingBillingAccountSink_updateBigquerySink|TestAccLoggingBillingAccountSink_disabled|TestAccLoggingProjectSink_disabled_update|TestAccLoggingProjectSink_heredoc|TestAccLoggingProjectSink_updateBigquerySink|TestAccLoggingBillingAccountSink_described|TestAccLoggingProjectSink_updatePreservesUniqueWriter|TestAccLoggingProjectSink_disabled|TestAccLoggingBillingAccountSink_update|TestAccLoggingProjectSink_described_update|TestAccLoggingBillingAccountSink_basic|TestAccLoggingProjectSink_described|TestAccLoggingProjectSink_basic|TestAccLoggingOrganizationSink_heredoc|TestAccLoggingOrganizationSink_updateBigquerySink|TestAccLoggingOrganizationSink_disabled|TestAccLoggingBucketConfig_CreateBuckets_withCustomId|TestAccLoggingOrganizationSink_described|TestAccLoggingMetric_descriptionUpdated|TestAccLoggingOrganizationSink_update|TestAccLoggingBucketConfigProject_basic|TestAccLoggingOrganizationSink_basic|TestAccLoggingMetric_explicitBucket|TestAccLoggingMetric_update|TestAccLoggingFolderExclusion|TestAccLoggingMetric_loggingMetricCounterBasicExample|TestAccLoggingMetric_loggingMetricCounterLabelsExample|TestAccLoggingMetric_loggingMetricBasicExample|TestAccLoggingLogView_BasicHandWritten|TestAccLoggingBillingAccountExclusion|TestAccLoggingOrganizationExclusion|TestAccLoggingFolderSink_heredoc|TestAccLoggingProjectExclusion|TestAccLoggingFolderSink_updateBigquerySink|TestAccLoggingFolderSink_update|TestAccLoggingFolderSink_folderAcceptsFullFolderPath|TestAccLoggingFolderSink_removeOptionals|TestAccLoggingFolderSink_disabled|TestAccNetworkConnectivitySpoke_RouterApplianceHandWritten|TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_update|TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample|TestAccComputeSubnetworkIamPolicyGenerated_withCondition|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample|TestAccComputeSubnetworkIamMemberGenerated_withCondition|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample|TestAccComputeSubnetworkIamBindingGenerated_withCondition|TestAccMonitoringSlo_windowBasedMetricSumRangeSlis|TestAccComputeSubnetworkIamPolicyGenerated|TestAccComputeSubnetworkIamMemberGenerated|TestAccMonitoringSlo_windowBasedMetricMeanRangeSlis|TestAccComputeSubnetworkIamBindingGenerated|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccMonitoringSlo_windowBased_updateSlis|TestAccComputeRegionDiskIamPolicyGenerated|TestAccComputeRegionDiskIamMemberGenerated|TestAccComputeRegionDiskIamBindingGenerated|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_requestBased|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccMonitoringSlo_basic|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccComputeRegionBackendServiceIamPolicyGenerated_withCondition|TestAccComputeRegionBackendServiceIamMemberGenerated_withCondition|TestAccMonitoringSlo_monitoringSloWindowsBasedRatioThresholdExample|TestAccComputeRegionBackendServiceIamBindingGenerated_withCondition|TestAccPrivatecaCaPoolIamMemberAllAuthenticatedUsersCasing|TestAccComputeRegionBackendServiceIamPolicyGenerated|TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample|TestAccComputeRegionBackendServiceIamMemberGenerated|TestAccMonitoringSlo_monitoringSloWindowsBasedMetricSumExample|TestAccPrivatecaCaPool_privatecaCapoolBasicExample|TestAccComputeRegionBackendServiceIamBindingGenerated|TestAccMonitoringSlo_monitoringSloWindowsBasedMetricMeanExample|TestAccComputeMachineImageIamMemberGenerated_withCondition|TestAccComputeMachineImageIamPolicyGenerated_withCondition|TestAccMonitoringSlo_monitoringSloWindowsBasedGoodBadMetricFilterExample|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccComputeMachineImageIamBindingGenerated_withCondition|TestAccMonitoringSlo_monitoringSloRequestBasedExample|TestAccComputeMachineImageIamPolicyGenerated|TestAccComputeMachineImageIamMemberGenerated|TestAccMonitoringNotificationChannel_updateSensitiveLabels|TestAccComputeMachineImageIamBindingGenerated|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccMonitoringNotificationChannel_update|TestAccComputeInstanceIamPolicyGenerated_withCondition|TestAccMonitoringNotificationChannel_notific [...]

2022-05-26 23:00 UTC, modular-magician commented
The provider crashed while running the VCR tests in RECORDING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/a84f8901-e211-4145-87c2-ee6504f80251/build-log/recording_test.log)

2022-05-27 18:02 UTC, trodge commented
/gcbrun

2022-05-27 18:14 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 68 insertions(+), 108 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 83 insertions(+), 111 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-05-27 18:52 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2028` 
Passed tests `920` 
Skipped tests: `226` 
Failed tests: `882` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccComputeAddress_internal|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceFromTemplate_overrideMetadataDotStartupScript|TestAccComputeInstance_networkTier|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_withBackendAndIAP|TestAccComputeRoute_hopInstance|TestAccComputeSharedVpc_basic|TestAccComputeTargetSslProxy_update|TestAccMonitoringAlertPolicy|TestAccComputeResourceUsageExportBucket|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccLoggingBillingAccountSink_basic|TestAccLoggingProjectSink_updatePreservesUniqueWriter|TestAccSecurityScannerScanConfig_scanConfigUpdate|TestAccDNSResponsePolicy_update|TestAccDNSResponsePolicyRule_dnsResponsePolicyRuleBasicExample|TestAccDNSResponsePolicyRule_update|TestAccDNSResponsePolicy_dnsResponsePolicyBasicExample|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccDNSPolicy_update|TestAccDNSManagedZone_privateForwardingUpdate|TestAccDNSManagedZone_reverseLookup|TestAccProject_deleteDefaultNetwork|TestAccDNSManagedZone_privateUpdate|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZoneServiceDirectoryExample|TestAccDNSManagedZone_dnsManagedZoneQuickstartExample|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig|TestAccComputeUrlMap_trafficDirectorUpdate|TestAccContainerNodePool_basicWithClusterId|TestAccContainerCluster_withMasterAuthorizedNetworksDisabled|TestAccContainerCluster_withDNSConfig|TestAccContainerNodePool_basic|TestAccContainerCluster_updateMaintenanceExclusionOptions|TestAccContainerCluster_withEnableKubernetesAlpha|TestAccContainerCluster_withMaintenanceExclusionOptions|TestAccContainerCluster_deleteMaintenanceExclusionOptions|TestAccContainerCluster_withMaintenanceExclusionWindow|TestAccContainerCluster_withRecurringMaintenanceWindow|TestAccContainerCluster_withResourceUsageExportConfig|TestAccContainerCluster_withAdvancedDatapath|TestAccContainerCluster_withMaintenanceWindow|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_withNodePoolNodeConfig|TestAccContainerCluster_withNodePoolMultiple|TestAccContainerNodePool_compactPlacement|TestAccContainerNodePool_gvnic|TestAccContainerCluster_withNodePoolAutoscaling|TestAccContainerNodePool_gcfsConfig|TestAccContainerNodePool_ephemeralStorageConfig|TestAccContainerCluster_withNodePoolResize|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_network|TestAccContainerNodePool_shieldedInstanceConfig|TestAccContainerCluster_backend|TestAccContainerCluster_withNodePoolBasic|TestAccContainerNodePool_EmptyGuestAccelerator|TestAccContainerCluster_withTpu|TestAccContainerNodePool_012_ConfigModeAttr|TestAccContainerCluster_withSandboxConfig|TestAccContainerNodePool_regionalClusters|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerNodePool_version|TestAccContainerNodePool_resize|TestAccContainerCluster_withPrivateClusterConfigMissingCidrBlock_withAutopilot|TestAccContainerCluster_errorCleanDanglingCluster|TestAccContainerCluster_withNodeConfigShieldedInstanceConfig|TestAccContainerCluster_withNodeConfig|TestAccContainerCluster_withPrivateClusterConfigMissingCidrBlock|TestAccContainerNodePool_autoscaling|TestAccContainerCluster_withNodeConfigScopeAlias|TestAccContainerCluster_withFlexiblePodCIDR|TestAccContainerNodePool_withNetworkConfig|TestAccContainerCluster_withIntraNodeVisibility|TestAccContainerNodePool_regionalAutoscaling|TestAccContainerCluster_updateVersion|TestAccContainerNodePool_withNodeConfigScopeAlias|TestAccContainerCluster_withPrivateClusterConfig|TestAccContainerNodePool_withManagement|TestAccContainerCluster_withVersion|TestAccContainerNodePool_withGPU|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerNodePool_withUpgradeSettings|TestAccContainerCluster_withBinaryAuthorization|TestAccContainerCluster_withSoleTenantGroup|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerCluster_withAutoscalingProfile|TestAccContainerNodePool_maxPodsPerNode|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerNodePool_withKubeletConfig|TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform|TestAccContainerNodePool_nodeLocations|TestAccContainerCluster_errorAutopilotLocation|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withLoggingConfig|TestAccContainerCluster_withIPAllocationPolicy_specificSizes|TestAccContainerCluster_withIdentityServiceConfig|TestAccContainerNodePool_withNodeConfig|TestAccContainerNodePool_withSandboxConfig|TestAccContainerCluster_regionalWithNodePool|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccContainerCluster_withTelemetryEnabled|TestAccContainerCluster_regional|TestAccContainerCluster_withIPAllocationPolicy_specificIPRanges|TestAccContainerCluster_withShieldedNodes|TestAccContainerCluster_withMasterAuthorizedNetworksConfig|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_withReleaseChannelEnabled|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withBootDiskKmsKey|TestAccContainerCluster_withIPAllocationPolicy_existingSecondaryRanges|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccContainerAzureNodePool_BetaBasicHandWritten|TestAccContainerAzureNodePool_BasicHandWritten|TestAccContainerAzureCluster_BetaBasicHandWritten|TestAccComputeVpnTunnel_defaultTrafficSelectors|TestAccComputeSubnetwork_subnetworkInternalL7lbExample|TestAccComputeVpnTunnel_router|TestAccComputeVpnTunnel_regionFromGateway|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccComputeVpnTunnel_vpnTunnelBetaExample|TestAccContainerAzureCluster_BasicHandWritten|TestAccComputeUrlMap_defaultUrlRedirect|TestAccContainerCluster_deleteExclusionWindow|TestAccContainerCluster_withMasterAuthConfig_NoCert|TestAccComputeVpnGateway_targetVpnGatewayBasicExample|TestAccContainerCluster_withILBSubsetting|TestAccContainerCluster_withConfidentialNodes|TestAccComputeUrlMap_trafficDirectorRemoveRouteRule|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerCluster_withNotificationConfig|TestAccComputeUrlMap_urlMapTrafficDirectorRoutePartialExample|TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccContainerAwsNodePool_BasicHandWritten|TestAccContainerCluster_withAddons|TestAccContainerAwsCluster_BasicHandWritten|TestAccContainerCluster_basic|TestAccContainerCluster_networkingModeRoutes|TestAccComputeTargetPool_basic|TestAccComputeUrlMap_urlMapTrafficDirectorRouteExample|TestAccComputeTargetInstance_targetInstanceCustomNetworkExample|TestAccComputeUrlMap_trafficDirectorPathUpdate|TestAccComputeTargetInstance_targetInstanceBasicExample|TestAccComputeTargetPool_update|TestAccComputeTargetTcpProxy_update|TestAccComputeTargetTcpProxy_targetTcpProxyBasicExample|TestAccComputeRegionHealthCheck_regionHealthCheckHttpsFullExample|TestAccComputeTargetSslProxy_targetSslProxyBasicExample|TestAccComputeUrlMap_defaultRouteActionTrafficDirectorUpdate|TestAccComputeRouter_update|TestAccComputeRouter_noRegion|TestAccComp [...]

2022-05-27 22:52 UTC, modular-magician commented
The provider crashed while running the VCR tests in RECORDING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/90b99aec-3f9b-4d6a-9aa2-6d2c8fd1ab12/build-log/recording_test.log)

2022-05-31 19:46 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 68 insertions(+), 108 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 83 insertions(+), 111 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-05-31 20:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2028` 
Passed tests `917` 
Skipped tests: `226` 
Failed tests: `885` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccComputeAddress_internal|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceFromTemplate_overrideMetadataDotStartupScript|TestAccComputeInstance_networkTier|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_withBackendAndIAP|TestAccComputeRoute_hopInstance|TestAccComputeSharedVpc_basic|TestAccComputeTargetSslProxy_update|TestAccMonitoringAlertPolicy|TestAccComputeResourceUsageExportBucket|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentDailyExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentDailyMidnightExample|TestAccLoggingMetric_descriptionUpdated|TestAccLoggingMetric_loggingMetricCounterLabelsExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentBasicExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesRecipesExample|TestAccLoggingMetric_explicitBucket|TestAccLoggingMetric_update|TestAccMonitoringSlo_windowBased_updateSlis|TestAccLoggingOrganizationSink_basic|TestAccServiceDirectoryEndpoint_serviceDirectoryEndpointWithNetworkExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccLoggingMetric_loggingMetricCounterBasicExample|TestAccSecurityScannerScanConfig_scanConfigBasicExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesPackagesExample|TestAccLoggingMetric_loggingMetricBasicExample|TestAccLoggingOrganizationExclusion|TestAccLoggingLogView_BasicHandWritten|TestAccLoggingFolderSink_heredoc|TestAccLoggingFolderSink_updateBigquerySink|TestAccLoggingFolderSink_update|TestAccLoggingFolderSink_folderAcceptsFullFolderPath|TestAccLoggingFolderSink_removeOptionals|TestAccLoggingFolderSink_disabled|TestAccLoggingFolderSink_described|TestAccLoggingFolderSink_basic|TestAccLoggingBucketConfigOrganization_basic|TestAccPrivatecaCertificate_privatecaCertificateUpdate|TestAccLoggingBucketConfigFolder_basic|TestAccLoggingBucketConfigBillingAccount_basic|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccPrivatecaCertificate_privatecaCertificateCsrExample|TestAccLoggingBucketConfig_CreateBuckets_withCustomId|TestAccLoggingBillingAccountSink_heredoc|TestAccLoggingFolderExclusion|TestAccRedisInstance_redisInstanceMrrExample|TestAccLoggingBillingAccountSink_updateBigquerySink|TestAccLoggingBillingAccountSink_disabled|TestAccLoggingBucketConfigProject_basic|TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample|TestAccRedisInstance_redisInstanceFullExample|TestAccLoggingBillingAccountSink_described|TestAccPrivatecaCertificate_privatecaCertificateConfigExample|TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate|TestAccPrivatecaCertificateAuthority_subordinateCaCreatedInAwaitingUserActivation|TestAccLoggingBillingAccountSink_update|TestAccPrivatecaCertificateAuthority_rootCaCreatedInStaged|TestAccLoggingBillingAccountSink_basic|TestAccPrivatecaCertificateAuthority_rootCaIsEnabledByDefault|TestAccNetworkManagementConnectivityTest_update|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccPrivatecaCaPool_updateCaOption|TestAccPrivatecaCaPool_privatecaCapoolEmptyPublishingOptions|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestAddressesExample|TestAccNetworkManagementConnectivityTest_networkManagementConnectivityTestInstancesExample|TestAccLoggingBillingAccountExclusion|TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline|TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccNetworkConnectivitySpoke_RouterApplianceHandWritten|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccMonitoringUptimeCheckConfig_update|TestAccPrivatecaCaPoolIamMemberAllAuthenticatedUsersCasing|TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample|TestAccPrivatecaCaPool_privatecaCapoolBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentFullExample|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample|TestAccMonitoringSlo_windowBasedMetricSumRangeSlis|TestAccMonitoringSlo_windowBasedMetricMeanRangeSlis|TestAccSecurityScannerScanConfig_scanConfigUpdate|TestAccDNSManagedZone_privateUpdate|TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccDNSManagedZone_dnsManagedZoneServiceDirectoryExample|TestAccProject_deleteDefaultNetwork|TestAccDNSManagedZone_dnsManagedZonePrivatePeeringExample|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccDNSManagedZone_dnsManagedZoneQuickstartExample|TestAccContainerCluster_backend|TestAccDNSResponsePolicy_update|TestAccDNSResponsePolicyRule_update|TestAccDNSResponsePolicyRule_dnsResponsePolicyRuleBasicExample|TestAccDNSResponsePolicy_dnsResponsePolicyBasicExample|TestAccGKEHubMembership_gkehubMembershipIssuerExample|TestAccGKEHubMembership_gkehubMembershipBasicExample|TestAccContainerNodePool_basic|TestAccContainerCluster_withDNSConfig|TestAccContainerCluster_withMasterAuthorizedNetworksDisabled|TestAccContainerCluster_withEnableKubernetesAlpha|TestAccContainerCluster_withResourceUsageExportConfig|TestAccContainerCluster_withAdvancedDatapath|TestAccDNSPolicy_update|TestAccContainerNodePool_compactPlacement|TestAccDNSPolicy_dnsPolicyBasicExample|TestAccContainerNodePool_gvnic|TestAccContainerCluster_withMasterAuthorizedNetworksConfig|TestAccContainerNodePool_gcfsConfig|TestAccContainerCluster_withTelemetryEnabled|TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccDNSManagedZone_reverseLookup|TestAccContainerNodePool_ephemeralStorageConfig|TestAccContainerCluster_withReleaseChannelEnabled|TestAccContainerNodePool_shieldedInstanceConfig|TestAccContainerCluster_withMaintenanceExclusionOptions|TestAccContainerCluster_withMaintenanceExclusionWindow|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccContainerCluster_withMasterAuthConfig_NoCert|TestAccComputeVpnTunnel_router|TestAccContainerNodePool_EmptyGuestAccelerator|TestAccContainerCluster_withILBSubsetting|TestAccComputeVpnTunnel_regionFromGateway|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_errorNoClusterCreated|TestAccComputeTargetPool_basic|TestAccDNSManagedZone_privateForwardingUpdate|TestAccContainerNodePool_012_ConfigModeAttr|TestAccContainerCluster_withNotificationConfig|TestAccContainerCluster_withAddons|TestAccComputeVpnTunnel_vpnTunnelBetaExample|TestAccContainerNodePool_regionalClusters|TestAccContainerCluster_errorCleanDanglingCluster|TestAccComputeTargetInstance_targetInstanceCustomNetworkExample|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccContainerCluster_withNetworkPolicyEnabled|TestAccComputeTargetInstance_targetInstanceBasicExample|TestAccContainerNodePool_version|TestAccContainerNodePool_resize|TestAccComputeVpnGateway_targetVpnGatewayBasicExample|TestAccCompu [...]

2022-06-01 00:13 UTC, modular-magician commented
The provider crashed while running the VCR tests in RECORDING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/e6a2aaa2-ad63-4ce7-b1bc-198b9465b0b1/build-log/recording_test.log)

2022-06-01 21:25 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 135 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 68 insertions(+), 132 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-01 22:02 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 135 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 62 insertions(+), 138 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-01 22:05 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/e8c32bf4-9d56-4648-b0cc-4cb863b40320/build-log/replaying_test.log)

2022-06-01 22:09 UTC, ScottSuarez commented
Let me know if you need any help trouble shooting anything here. Happy to help and provide any and all assistance

2022-06-01 23:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 135 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 62 insertions(+), 138 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-02 17:34 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 135 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 62 insertions(+), 138 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-02 17:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/8d6d016c-39bf-48ef-8dbd-04cb89e57e45/build-log/replaying_test.log)

2022-06-02 17:39 UTC, ScottSuarez requested changes
Take a look at dcl_client_creation

You'll likely need to source the new base path there.

https://github.com/GoogleCloudPlatform/magic-modules/blob/main/tpgtools/templates/provider_dcl_client_creation.go.tmpl#L45

2022-06-02 17:55 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 136 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 62 insertions(+), 139 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-02 17:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/14611bb0-de3c-4647-8c03-48516d027f83/build-log/replaying_test.log)

2022-06-02 23:24 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 136 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 63 insertions(+), 140 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-02 23:37 UTC, trodge commented
/gcbrun

2022-06-02 23:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 136 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 63 insertions(+), 140 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-02 23:52 UTC, ScottSuarez commented
Could you remove `serialization.go`? 

its been added to the `.gitignore` list

2022-06-02 23:54 UTC, trodge commented
> 

Done

2022-06-02 23:54 UTC, ScottSuarez commented on tpgtools/names.go
> +	if strings.HasPrefix(string(b), "gke") {
oh interesting.. nice find

2022-06-03 00:04 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 59 insertions(+), 136 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 63 insertions(+), 140 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-03 00:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2032` 
Passed tests `1717` 
Skipped tests: `226` 
Failed tests: `89` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccMonitoringAlertPolicy|TestAccContainerAzureNodePool_BetaBasicHandWritten|TestAccMonitoringMetricDescriptor_update|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withAddons|TestAccContainerCluster_withNotificationConfig|TestAccComputeFirewallPolicy_update|TestAccComputeFirewallPolicyRule_multipleRules|TestAccComputeFirewallPolicyAssociation_basic|TestAccBillingBudget_billingBudgetNotifyExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccPrivatecaCertificate_privatecaCertificateCsrExample|TestAccPrivatecaCaPool_updateCaOption|TestAccPrivatecaCaPool_privatecaCapoolEmptyPublishingOptions|TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate|TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccPrivatecaCertificateAuthority_subordinateCaCreatedInAwaitingUserActivation|TestAccPrivatecaCaPoolIamMemberAllAuthenticatedUsersCasing|TestAccPrivatecaCertificate_privatecaCertificateConfigExample|TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample|TestAccPrivatecaCertificateAuthority_rootCaCreatedInStaged|TestAccPrivatecaCaPool_privatecaCapoolBasicExample|TestAccPrivatecaCertificateAuthority_rootCaIsEnabledByDefault|TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState|TestAccMonitoringMetricDescriptor_monitoringMetricDescriptorAlertExample|TestAccMonitoringMetricDescriptor_monitoringMetricDescriptorBasicExample|TestAccMonitoringGroup_update|TestAccMonitoringGroup_monitoringGroupSubgroupExample|TestAccMonitoringGroup_monitoringGroupBasicExample|TestAccMonitoringDashboard_update|TestAccMonitoringDashboard_rowLayout|TestAccMonitoringDashboard_gridLayout|TestAccMonitoringDashboard_basic|TestAccPrivatecaCertificateTemplateIamPolicyGenerated_withCondition|TestAccPrivatecaCertificateTemplateIamMemberGenerated_withCondition|TestAccMonitoringService_monitoringServiceCustomExample|TestAccPrivatecaCertificateTemplateIamBindingGenerated_withCondition|TestAccPrivatecaCertificateTemplateIamMemberGenerated|TestAccPrivatecaCertificateTemplateIamPolicyGenerated|TestAccPrivatecaCaPoolIamPolicyGenerated_withCondition|TestAccPrivatecaCaPoolIamMemberGenerated_withCondition|TestAccPrivatecaCertificateTemplateIamBindingGenerated|TestAccContainerAzureNodePool_BasicHandWritten|TestAccPrivatecaCaPoolIamBindingGenerated_withCondition|TestAccContainerAzureCluster_BetaBasicHandWritten|TestAccPrivatecaCaPoolIamPolicyGenerated|TestAccContainerAzureCluster_BasicHandWritten|TestAccPrivatecaCaPoolIamMemberGenerated|TestAccPrivatecaCaPoolIamBindingGenerated|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerAwsNodePool_BasicHandWritten|TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccContainerAwsCluster_BasicHandWritten|TestAccMonitoringUptimeCheckConfig_uptimeCheckTcpExample|TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_update|TestAccMonitoringSlo_monitoringSloWindowsBasedRatioThresholdExample|TestAccFirebaserulesRelease_BasicRelease|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpsExample|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample|TestAccMonitoringSlo_monitoringSloAppengineExample|TestAccMonitoringSlo_monitoringSloWindowsBasedMetricSumExample|TestAccMonitoringSlo_monitoringSloWindowsBasedMetricMeanExample|TestAccMonitoringSlo_monitoringSloWindowsBasedGoodBadMetricFilterExample|TestAccMonitoringNotificationChannel_updateSensitiveLabels|TestAccMonitoringSlo_windowBasedMetricSumRangeSlis|TestAccMonitoringNotificationChannel_update|TestAccMonitoringNotificationChannel_notificationChannelBasicExample|TestAccMonitoringSlo_windowBasedMetricMeanRangeSlis|TestAccMonitoringMonitoredProject_BasicMonitoredProject|TestAccMonitoringSlo_windowBasedGoodTotalRatioThresholdSlis|TestAccMonitoringSlo_availabilitySli|TestAccMonitoringSlo_basic|TestAccMonitoringSlo_requestBased|TestAccMonitoringSlo_windowBased_updateSlis|TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccMonitoringSlo_monitoringSloRequestBasedExample|TestAccPrivatecaCertificate_privatecaCertificateUpdate </details>

2022-06-03 01:19 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withNotificationConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccContainerCluster_withNotificationConfig.log)]
`TestAccComputeFirewallPolicyAssociation_basic`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccComputeFirewallPolicyAssociation_basic.log)]
`TestAccComputeFirewallPolicy_update`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccComputeFirewallPolicy_update.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName.log)]
`TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel.log)]
`TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel.log)]
`TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType.log)]
`TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound.log)]
`TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique.log)]
`TestAccDataSourceMonitoringService_AppEngine`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourceMonitoringService_AppEngine.log)]
`TestAccMonitoringAlertPolicy`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccMonitoringAlertPolicy.log)]
`TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]
`TestAccMonitoringNotificationChannel_notificationChannelBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccMonitoringNotificationChannel_notificationChannelBasicExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificate_privatecaCertificateUpdate.log)]
`TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateCsrExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificate_privatecaCertificateCsrExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateConfigExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificate_privatecaCertificateConfigExample.log)]
`TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate.log)]
`TestAccPrivatecaCertificateAuthority_subordinateCaCreatedInAwaitingUserActivation`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_subordinateCaCreatedInAwaitingUserActivation.log)]
`TestAccPrivatecaCertificateAuthority_rootCaCreatedInStaged`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_rootCaCreatedInStaged.log)]
`TestAccPrivatecaCertificateAuthority_rootCaIsEnabledByDefault`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_rootCaIsEnabledByDefault.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]
`TestAccPrivatecaCaPool_updateCaOption`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCaPool_updateCaOption.log)]
`TestAccPrivatecaCaPool_privatecaCapoolEmptyPublishingOptions`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7-44da-42c1-90f7-d100591b7a63/recording/TestAccPrivatecaCaPool_privatecaCapoolEmptyPublishingOptions.log)]
`TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/592c38c7- [...]

2022-06-03 22:31 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 56 insertions(+), 145 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 57 insertions(+), 158 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 7 insertions(+), 21 deletions(-))

2022-06-03 23:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2034` 
Passed tests `1798` 
Skipped tests: `226` 
Failed tests: `10` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withAddons|TestAccContainerAzureNodePool_BetaBasicHandWritten|TestAccContainerAzureNodePool_BasicHandWritten|TestAccContainerAzureCluster_BetaBasicHandWritten|TestAccContainerAzureCluster_BasicHandWritten|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerAwsNodePool_BasicHandWritten|TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccContainerAwsCluster_BasicHandWritten </details>

2022-06-03 23:32 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccContainerAwsCluster_BasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAwsCluster_BasicHandWritten.log)]
`TestAccContainerAzureNodePool_BasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAzureNodePool_BasicHandWritten.log)]
`TestAccContainerCluster_withConfidentialNodes`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerCluster_withConfidentialNodes.log)]
`TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerAzureNodePool_BetaBasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAzureNodePool_BetaBasicHandWritten.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccContainerAzureCluster_BetaBasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAzureCluster_BetaBasicHandWritten.log)]
`TestAccContainerAzureCluster_BasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAzureCluster_BasicHandWritten.log)]
`TestAccContainerAwsNodePool_BasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAwsNodePool_BasicHandWritten.log)]
`TestAccContainerAwsCluster_BetaBasicHandWritten`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording/TestAccContainerAwsCluster_BetaBasicHandWritten.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/5ca42a63-5872-4f19-931c-3ea34783a040/recording) for each test

2022-06-06 16:45 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6038-old..auto-pr-6038) ( 3 files changed, 56 insertions(+), 157 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 57 insertions(+), 170 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6038-old..auto-pr-6038) ( 4 files changed, 11 insertions(+), 21 deletions(-))

2022-06-06 17:47 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/7aba3520-ecf1-4aa4-bc63-0a16e53cfed2/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerCluster_withConfidentialNodes`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/7aba3520-ecf1-4aa4-bc63-0a16e53cfed2/recording/TestAccContainerCluster_withConfidentialNodes.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/7aba3520-ecf1-4aa4-bc63-0a16e53cfed2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/7aba3520-ecf1-4aa4-bc63-0a16e53cfed2/recording) for each test

2022-06-06 18:18 UTC, ScottSuarez requested changes

2022-06-06 18:18 UTC, ScottSuarez commented on mmv1/third_party/terraform/utils/config.go.erb
>  	ContainerAzureBasePath string
Do you have context on why these entries need to be manually provided?

2022-06-06 18:18 UTC, ScottSuarez commented on tpgtools/templates/provider_dcl_endpoints.go.tmpl
> +func providerDCLConfigure(ctx context.Context, d *schema.ResourceData, p *schema.Provider, config *Config) (interface{}, diag.Diagnostics) {
```suggestion
func providerDCLConfigure(d *schema.ResourceData, config *Config) interface{} {
```
recommend not complicating the interface of this function to match the return parameters of the provider.go. If we have no need for diagnostics lets omit it from the return parameters. Same with the function parameters. If not needed, omit.

2022-06-06 20:25 UTC, ScottSuarez commented
looks like tests were failing for azure and aws because the data source tries to [index into the basepath](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/data_sources/data_source_google_container_azure_versions.go#L56) `ContainerAzureBasePath`. This basepath is traditionally set as a default in [config.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/utils/config.go.erb#L270-L271) in the default base paths map. Then it is initialized here https://github.com/GoogleCloudPlatform/magic-modules/blob/07f36b0b334afd02d5bfa057f09ec5907e33b4aa/mmv1/third_party/terraform/utils/provider_handwritten_endpoint.go.erb#L172 .. 

unfortunately without this we have no way to know what the endpoint would be for the api since the dcl doesn't expose this.. Ideally the dcl could expose this so we could inherit it.

2022-06-06 20:30 UTC, ScottSuarez commented on mmv1/third_party/terraform/utils/config.go.erb
>  	ContainerAzureBasePath string
looks like even though its dcl exclusive resource it needs a custom entry so the data source can have a default. It's a non-ideal behavior.

2022-06-06 20:54 UTC, ScottSuarez approved these changes
lgtm pending tests.

2022-06-06 21:05 UTC, trodge commented
/gcbrun

2022-06-06 22:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2037` 
Passed tests `1807` 
Skipped tests: `226` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withNotificationConfig|TestAccContainerCluster_withAddons </details>

2022-06-06 22:47 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withNotificationConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/recording/TestAccContainerCluster_withNotificationConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerCluster_withAddons`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerCluster_withConfidentialNodes`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/recording/TestAccContainerCluster_withConfidentialNodes.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6038/artifacts/f214f021-aa7f-4885-8ec5-47793ae29f6c/recording) for each test

2022-06-07 17:27 UTC, merged