Update sql_instance_iam_condition.tf.erb
GoogleCloudPlatform/magic-modules pull request #6044
Opened 2022-05-18 17:18 UTC by rlv2022

This change is based on feedback that Akhil provided for the documentation.

2022-05-18 17:18 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2022-05-18 17:33 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6044-old..auto-pr-6044) ( 3 files changed, 8 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6044-old..auto-pr-6044) ( 1 file changed, 2 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6044-old..auto-pr-6044) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-6044-old..auto-pr-6044) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2022-05-18 18:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2019` 
Passed tests `1792` 
Skipped tests: `226` 
Failed tests: `1` 

#### Action taken 
Triggering VCR tests in RECORDING mode for the following tests that failed during VCR: TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample

2022-05-18 18:18 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6044/artifacts/baebb434-603e-478d-ae09-c1df9dda8d8e/recording/TestAccCloudAssetFolderFeed_cloudAssetFolderFeedExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6044/artifacts/baebb434-603e-478d-ae09-c1df9dda8d8e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6044/artifacts/baebb434-603e-478d-ae09-c1df9dda8d8e/recording) for each test

2022-05-20 22:05 UTC, shuyama1 requested changes
Thanks for making the changes! 
Looks like we skip the test for this example and I tested it locally and it seems we are missing provider version in some of the resource configs in this example.
Would you mind adding `provider = google-beta` to the resources block that misses this line in this example?

2022-09-02 20:05 UTC, c2thorn commented
Hi @rlv2022, not sure if this is still a relevant change. MM no longer supports CGC samples. I believe the "terraform-on-cgc" internal documentation has just been updated with the new workflow, but essentially you'll be making PR's against https://github.com/terraform-google-modules/terraform-docs-samples directly

2022-09-02 20:05 UTC, closed without merging