Upgrade dcl version to 1.10
GoogleCloudPlatform/magic-modules pull request #6093
Opened 2022-05-31 21:13 UTC by louisjimenez

Upgrade the DCL version to v.1.10.0.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
clouddeploy: updated resource descriptions in documentation
```

2022-05-31 21:14 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @megan07, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-05-31 21:25 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6093-old..auto-pr-6093) ( 4 files changed, 7 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6093-old..auto-pr-6093) ( 5 files changed, 16 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6093-old..auto-pr-6093) ( 2 files changed, 5 insertions(+), 5 deletions(-))

2022-05-31 21:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2028` 
Passed tests `1722` 
Skipped tests: `226` 
Failed tests: `80` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerCluster_withBinaryAuthorization|TestAccContainerNodePool_withKubeletConfig|TestAccContainerNodePool_withSandboxConfig|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccContainerNodePool_maxPodsPerNode|TestAccContainerCluster_withVersion|TestAccContainerNodePool_nodeLocations|TestAccContainerCluster_withAutoscalingProfile|TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform|TestAccContainerNodePool_basicWithClusterId|TestAccContainerNodePool_withNodeConfig|TestAccContainerCluster_withLoggingConfig|TestAccContainerCluster_withIdentityServiceConfig|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withSoleTenantGroup|TestAccContainerCluster_withNodePoolBasic|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccContainerCluster_withWorkloadIdentityConfig|TestAccContainerNodePool_basic|TestAccContainerCluster_withMasterAuthConfig_NoCert|TestAccContainerCluster_withILBSubsetting|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_backend|TestAccContainerCluster_network|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerCluster_withNotificationConfig|TestAccContainerCluster_withDNSConfig|TestAccContainerCluster_withNodeConfigShieldedInstanceConfig|TestAccContainerCluster_misc|TestAccContainerCluster_withAddons|TestAccContainerCluster_errorAutopilotLocation|TestAccContainerCluster_withEnableKubernetesAlpha|TestAccContainerCluster_withNodeConfigScopeAlias|TestAccContainerCluster_withNodeConfig|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withShieldedNodes|TestAccContainerCluster_withMasterAuthorizedNetworksDisabled|TestAccContainerCluster_networkingModeRoutes|TestAccContainerCluster_updateVersion|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerNodePool_012_ConfigModeAttr|TestAccContainerCluster_basic|TestAccContainerCluster_withResourceUsageExportConfig|TestAccContainerCluster_withBootDiskKmsKey|TestAccContainerCluster_withIntraNodeVisibility|TestAccContainerCluster_withIPAllocationPolicy_specificSizes|TestAccContainerCluster_errorNoClusterCreated|TestAccContainerCluster_withAdvancedDatapath|TestAccContainerCluster_withPrivateClusterConfigMissingCidrBlock_withAutopilot|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_errorCleanDanglingCluster|TestAccContainerCluster_withPrivateClusterConfig|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_withTpu|TestAccContainerCluster_withFlexiblePodCIDR|TestAccContainerCluster_regionalWithNodePool|TestAccContainerCluster_withIPAllocationPolicy_specificIPRanges|TestAccContainerCluster_regional|TestAccContainerCluster_withMasterAuthorizedNetworksConfig|TestAccContainerCluster_withIPAllocationPolicy_existingSecondaryRanges|TestAccContainerCluster_deleteExclusionWindow|TestAccContainerCluster_withTelemetryEnabled|TestAccContainerCluster_updateMaintenanceExclusionOptions|TestAccContainerCluster_deleteMaintenanceExclusionOptions|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerCluster_withReleaseChannelEnabled|TestAccContainerCluster_withMaintenanceExclusionOptions|TestAccContainerCluster_withNetworkPolicyEnabled|TestAccContainerCluster_withMaintenanceExclusionWindow|TestAccContainerCluster_withRecurringMaintenanceWindow|TestAccContainerCluster_withMaintenanceWindow|TestAccContainerCluster_withNodePoolNodeConfig|TestAccContainerCluster_withNodePoolMultiple|TestAccContainerCluster_withNodePoolAutoscaling|TestAccContainerCluster_withNodePoolResize|TestAccComputeNetworkPeeringRoutesConfig_networkPeeringRoutesConfigGkeExample|TestAccContainerClusterDatasource_regional </details>

2022-05-31 23:13 UTC, shuyama1 commented
Looks like it also generate a new feature in `gke_hub_feature_membership.go`. Let me test it locally first.

2022-06-01 00:01 UTC, louisjimenez commented
Thank you for testing!

2022-06-01 00:04 UTC, shuyama1 requested changes
Looks like DCL version 1.10.0 also contains a `gke_hub_feature_membership` feature and we want to keep all added fields tested. Would you mind adding `prevent_drift = false` inside the `config_sync` block at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb#L392 and `prevent_drift = true` inside the  `config_sync` block at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb#L464?
And also change https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb#L391 and https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb#L463 to version `1.10.0`. So sorry about the extra work!

2022-06-01 00:19 UTC, louisjimenez commented
Ok, I've made the changes and rebased. Thanks!

2022-06-01 00:30 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6093-old..auto-pr-6093) ( 4 files changed, 7 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6093-old..auto-pr-6093) ( 6 files changed, 20 insertions(+), 7 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6093-old..auto-pr-6093) ( 2 files changed, 5 insertions(+), 5 deletions(-))

2022-06-01 00:30 UTC, shuyama1 requested changes

2022-06-01 00:30 UTC, shuyama1 commented on mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb
>        }
```suggestion
    config_sync {
      git {
        sync_repo = "https://github.com/hashicorp/terraform"
      }
      prevent_drift = false
```

2022-06-01 00:30 UTC, shuyama1 commented on mmv1/third_party/terraform/tests/resource_gke_hub_feature_membership_test.go.erb
>        }
```suggestion
      }
      prevent_drift = false
```

2022-06-01 00:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6093-old..auto-pr-6093) ( 4 files changed, 7 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6093-old..auto-pr-6093) ( 6 files changed, 20 insertions(+), 7 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6093-old..auto-pr-6093) ( 2 files changed, 5 insertions(+), 5 deletions(-))

2022-06-01 01:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2030` 
Passed tests `1723` 
Skipped tests: `226` 
Failed tests: `81` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withNodePoolBasic|TestAccContainerCluster_withBinaryAuthorization|TestAccContainerCluster_withAutoscalingProfile|TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform|TestAccContainerCluster_withSoleTenantGroup|TestAccContainerCluster_withLoggingConfig|TestAccContainerCluster_backend|TestAccContainerCluster_withAddons|TestAccContainerCluster_misc|TestAccContainerNodePool_withLinuxNodeConfig|TestAccContainerCluster_networkingModeRoutes|TestAccContainerCluster_network|TestAccContainerCluster_basic|TestAccContainerNodePool_withKubeletConfig|TestAccContainerCluster_withIdentityServiceConfig|TestAccContainerCluster_withSandboxConfig|TestAccContainerCluster_withWorkloadMetadataConfig|TestAccContainerCluster_withWorkloadIdentityConfig|TestAccContainerNodePool_withSandboxConfig|TestAccContainerCluster_errorAutopilotLocation|TestAccContainerCluster_withAutopilot|TestAccContainerCluster_withShieldedNodes|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerNodePool_withWorkloadIdentityConfig|TestAccContainerNodePool_withNodeConfig|TestAccContainerCluster_withNodeConfigShieldedInstanceConfig|TestAccContainerNodePool_maxPodsPerNode|TestAccContainerNodePool_nodeLocations|TestAccContainerCluster_withIPAllocationPolicy_specificSizes|TestAccContainerNodePool_basicWithClusterId|TestAccContainerCluster_withIPAllocationPolicy_specificIPRanges|TestAccContainerCluster_withIPAllocationPolicy_existingSecondaryRanges|TestAccContainerCluster_withNodeConfigScopeAlias|TestAccContainerCluster_deleteExclusionWindow|TestAccContainerCluster_withBootDiskKmsKey|TestAccContainerNodePool_basic|TestAccContainerCluster_updateMaintenanceExclusionOptions|TestAccContainerCluster_withDNSConfig|TestAccContainerCluster_withEnableKubernetesAlpha|TestAccContainerCluster_withNodeConfig|TestAccContainerCluster_withMasterAuthorizedNetworksDisabled|TestAccContainerCluster_deleteMaintenanceExclusionOptions|TestAccContainerCluster_withResourceUsageExportConfig|TestAccContainerCluster_withMaintenanceExclusionOptions|TestAccContainerCluster_withMaintenanceExclusionWindow|TestAccContainerCluster_withAdvancedDatapath|TestAccContainerCluster_withRecurringMaintenanceWindow|TestAccContainerCluster_errorNoClusterCreated|TestAccContainerCluster_withDatabaseEncryption|TestAccContainerCluster_withMaintenanceWindow|TestAccContainerCluster_errorCleanDanglingCluster|TestAccContainerCluster_withNodePoolNodeConfig|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerCluster_withNodePoolMultiple|TestAccContainerCluster_withFlexiblePodCIDR|TestAccContainerCluster_withNodePoolAutoscaling|TestAccContainerCluster_withNodePoolResize|TestAccContainerCluster_updateVersion|TestAccContainerCluster_withVersion|TestAccContainerCluster_withNodePoolUpdateVersion|TestAccContainerCluster_withIntraNodeVisibility|TestAccContainerCluster_withPrivateClusterConfigMissingCidrBlock_withAutopilot|TestAccContainerCluster_withPrivateClusterConfig|TestAccContainerCluster_withTpu|TestAccContainerCluster_regionalWithNodeLocations|TestAccContainerCluster_regionalWithNodePool|TestAccContainerCluster_regional|TestAccContainerCluster_withMasterAuthorizedNetworksConfig|TestAccContainerCluster_withTelemetryEnabled|TestAccComputeNetworkPeeringRoutesConfig_networkPeeringRoutesConfigGkeExample|TestAccContainerCluster_withReleaseChannelEnabledDefaultVersion|TestAccContainerNodePool_012_ConfigModeAttr|TestAccContainerCluster_withReleaseChannelEnabled|TestAccContainerCluster_withMasterAuthConfig_NoCert|TestAccContainerCluster_withAuthenticatorGroupsConfig|TestAccContainerCluster_withNetworkPolicyEnabled|TestAccContainerCluster_withILBSubsetting|TestAccContainerCluster_withConfidentialNodes|TestAccContainerCluster_withNotificationConfig|TestAccContainerClusterDatasource_regional </details>

2022-06-01 05:32 UTC, modular-magician commented
The provider crashed while running the VCR tests in RECORDING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6093/artifacts/2499b3d1-6616-45bf-9040-3919b313ec5e/build-log/recording_test.log)

2022-06-01 12:06 UTC, shuyama1 commented
looks like VCR test timed out. Running on TC now. https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstreamVcr/296878

2022-06-01 16:40 UTC, shuyama1 commented
Newly modified test `TestAccGkeHubFeatureMembership_gkehubFeatureAcmAllFields` skipped VCR test. Triggered an independent run: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/296891

2022-06-01 18:14 UTC, louisjimenez commented
That sounds good. And if any issues with merging the other PR come up, I'm happy to pick this back up and get the changes in for the next release.

2022-06-01 18:14 UTC, closed without merging