Storage transfer job: Add logging config block take 2
GoogleCloudPlatform/magic-modules pull request #6256
Opened 2022-07-12 21:57 UTC by geojaz

@amruthasingh I broke the rebase of last PR, let's try again...

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Adds logging config field to storage transfer job resource.
```

2022-07-12 21:58 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @c2thorn, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-07-13 19:32 UTC, c2thorn commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +	"google.golang.org/genproto/googleapis/cloud/aiplatform/v1beta1/schema"
why is this added?

2022-07-13 19:32 UTC, c2thorn commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +				Required: false,
```suggestion
				Optional: true,
```

2022-07-13 19:35 UTC, c2thorn commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +				Type:     schema.TypeList,
Can multiple logging configs be set? Otherwise we usually cap the number of items with
```
				MaxItems: 1,
```

2022-07-13 20:00 UTC, geojaz commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +			},
thanks for the guidance! I'm not in this repo often enough to remember all the pathways :)

2022-07-13 20:38 UTC, c2thorn commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +			},
We are working on adding more guides to our documentation. We're missing guidance on handwritten resources like this one, feel free to reach out if you have questions.

2022-07-14 05:07 UTC, geojaz commented
Will take another look at the test tomorrow

2022-07-21 19:00 UTC, DrFaust92 requested changes

2022-07-21 19:00 UTC, DrFaust92 commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +			"loggingConfig": {
logging_config

2022-07-21 20:05 UTC, closed without merging