Add support for Capacity Intelligence Autoscaling
GoogleCloudPlatform/magic-modules pull request #6370
Opened 2022-08-03 13:27 UTC by kisieland

[Location Policy](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#location_policy) is a GKE Autoscaling feature that allows users to specify VM distribution between zones. \
[Total Min and Max size](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-autoscaler#minimum_and_maximum_node_pool_size)  is a complementary GKE Autoscaling feature that allows users to specify total max and min sizes for nodepools (rather than current per zone limits).
Both features are in GA.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
container: Add support for GKE Autoscaling Location Policy
container: Add support for GKE Autoscaling Total Size
```

2022-08-03 13:28 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-08-03 13:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 5 files changed, 225 insertions(+), 24 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 5 files changed, 225 insertions(+), 24 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 54 insertions(+), 29 deletions(-))

2022-08-03 18:45 UTC, modular-magician commented
The provider crashed while running the VCR tests in RECORDING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/08a4c1f5-1270-48ce-9794-4c2dc3b23c34/build-log/recording_test.log)

2022-08-03 20:12 UTC, melinath commented
timed out - failures were probably related to a separate issue. rerunning /gcbrun

2022-08-03 20:13 UTC, melinath commented
oh - you'll actually need to fix the merge conflict before tests can rerun @kisieland

2022-08-03 22:53 UTC, melinath requested changes
marking changes requested - see above.

2022-08-04 09:42 UTC, kisieland commented
Rebased, but I still see the following errors, while running make test (that are also present on main):
```
go: finding module for package github.com/hashicorp/terraform-provider-clean-google/google
github.com/hashicorp/terraform-provider-google/scripts imports
        github.com/hashicorp/terraform-provider-clean-google/google: cannot find module providing package github.com/hashicorp/terraform-provider-clean-google/google: module github.com/hashicorp/terraform-provider-clean-google/google: git ls-remote -q origin in /usr/local/google/home/danielgutowski/.gvm/pkgsets/go1.18.3/global/pkg/mod/cache/vcs/8a09e4807c89e0e733077bc133bab61829d1c43ee508c409ab431169c786365f: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/hashicorp/terraform-provider-clean-google/' not found
```
this blocks running acceptance and unit tests

2022-08-04 09:44 UTC, kisieland commented
@melinath PTAL at the above comment

2022-08-04 20:58 UTC, melinath requested changes
This should be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/6376 - try rebasing on main one more time.

2022-08-05 13:46 UTC, kisieland commented
Yup, this fixed the main, I was able to rebase and fix some of mine misconfigurations and now both tests and lint are working!
@melinath Please take another look :)

2022-08-05 13:57 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 5 files changed, 232 insertions(+), 28 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 5 files changed, 232 insertions(+), 28 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 54 insertions(+), 29 deletions(-))

2022-08-05 14:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2127` 
Passed tests `1889` 
Skipped tests: `226` 
Failed tests: `12` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccContainerNodePool_regionalAutoscaling|TestAccComputeInstance_networkPerformanceConfig|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample|TestAccCloudFunctions2Function_fullUpdate|TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample|TestAccActiveDirectoryDomain_update|TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample </details>

2022-08-05 15:36 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample.log)]
`TestAccCloudFunctions2Function_fullUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccCloudFunctions2Function_fullUpdate.log)]
`TestAccContainerNodePool_regionalAutoscaling`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccContainerNodePool_regionalAutoscaling.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccComputeInstance_networkPerformanceConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccComputeInstance_networkPerformanceConfig.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccActiveDirectoryDomain_update`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccActiveDirectoryDomain_update.log)]
`TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording/TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/27881e26-3f27-463e-980c-adae3753663b/recording) for each test

2022-08-05 18:07 UTC, melinath commented
It looks like this maybe got recorded in a previous run and is now passing in VCR? But running a manual test just to be sure: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/322368 LGTM assuming that passes.

2022-08-05 18:13 UTC, melinath requested changes
@kisieland could you read through https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md and format your release notes accordingly? In particular - they should be marked as enhancements, so check out that section, and there should be one block per release note so that they get parsed correctly.

2022-08-22 09:46 UTC, kisieland commented
@melinath updated the release notes PTAL. 
I've also solved the merge conflict, but it seems that there is an issue on the main branch, because when I tried to re-run tests I received the following error (also on the main branch):
```
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
go test  -timeout=30s $(go list ./... | grep -v github.com/hashicorp/terraform-provider-google/scripts)
# github.com/hashicorp/terraform-provider-google/google [github.com/hashicorp/terraform-provider-google/google.test]
google/resource_active_directory_domain_update_test.go:87:6: testAccCheckActiveDirectoryDomainDestroyProducer redeclared in this block
        google/resource_active_directory_domain_generated_test.go:61:6: other declaration of testAccCheckActiveDirectoryDomainDestroyProducer
?       github.com/hashicorp/terraform-provider-google  [no test files]
FAIL    github.com/hashicorp/terraform-provider-google/google [build failed]
?       github.com/hashicorp/terraform-provider-google/version  [no test files]
FAIL
make: *** [GNUmakefile:11: test] Error 2
```

2022-08-22 09:50 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 3 files changed, 185 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 3 files changed, 185 insertions(+), 19 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-22 10:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2140` 
Passed tests `1900` 
Skipped tests: `228` 
Failed tests: `12` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccSqlUser_mysqlDisabled|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeInstance_networkPerformanceConfig|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudFunctions2Function_fullUpdate|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-08-22 11:40 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccSqlUser_mysqlDisabled`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccSqlUser_mysqlDisabled.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeClone`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeClone.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccCloudFunctions2Function_fullUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccCloudFunctions2Function_fullUpdate.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Tests failed during RECORDING mode:
 `TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccComputeInstance_networkPerformanceConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccComputeInstance_networkPerformanceConfig.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/6b8733d7-0e19-41f3-aec1-62e3bf042b2a/recording) for each test

2022-08-22 22:21 UTC, melinath commented
one more test run - https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/328776 just to be paranoid :-) It looks like this should be fine - no failures in the CI pipeline.

2022-08-22 22:24 UTC, melinath requested changes
Ah - I just realized that since this is changing `schemaNodePool`, you'll need to add tests & docs for container_cluster as well, since it reuses this variable. Apologies for not catching this sooner!

2022-08-26 12:08 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 296 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 296 insertions(+), 19 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-26 12:22 UTC, kisieland commented
I've added the test to container_cluster, but I did not see any mention of the nodepool autoscaling in the cluster documentation, so I did not add it there. 
There are mentions of the cluster level autoscaling, which are something different from the one I am changing.

I've re-run the tests and those seem to work correctly. @melinath PTAL :)

2022-08-26 12:23 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 299 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 299 insertions(+), 19 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-26 13:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2148` 
Passed tests `1903` 
Skipped tests: `232` 
Failed tests: `13` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_soleTenantNodeAffinities|TestAccContainerCluster_withNodePoolCIA|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudFunctions2Function_fullUpdate|TestAccCGCSnippet_eventarcWorkflowsExample|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccSqlUser_mysqlDisabled|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample </blockquote></details>

2022-08-26 13:26 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCloudFunctions2Function_fullUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccCloudFunctions2Function_fullUpdate.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccSqlUser_mysqlDisabled`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccSqlUser_mysqlDisabled.log)] 

Tests failed during RECORDING mode:
 `TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccContainerCluster_withNodePoolCIA`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccContainerCluster_withNodePoolCIA.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/425f3cf9-23f0-4640-a7bb-072fc0473b56/recording) for each test

2022-08-26 13:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 299 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 299 insertions(+), 19 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-26 14:47 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2148` 
Passed tests `1908` 
Skipped tests: `232` 
Failed tests: `8` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withNodePoolCIA|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange </blockquote></details>

2022-08-26 15:06 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 302 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6370-old..auto-pr-6370) ( 4 files changed, 302 insertions(+), 19 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6370-old..auto-pr-6370) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-26 15:37 UTC, kisieland commented
I had a  couple of hiccups with `TestAccContainerCluster_withNodePoolCIA` test, but it should pass now. \
Btw. Thanks for editing the release notes :)

2022-08-26 16:06 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2148` 
Passed tests `1908` 
Skipped tests: `232` 
Failed tests: `8` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withNodePoolCIA|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample </blockquote></details>

2022-08-26 16:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withNodePoolCIA`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccContainerCluster_withNodePoolCIA.log)] 

Tests failed during RECORDING mode:
 `TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6370/artifacts/3010b309-0dfa-4a67-bbb1-33f42e6a0597/recording) for each test

2022-08-29 21:04 UTC, melinath commented
This looks good - running new tests manually once out of paranoia: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/331626

2022-08-30 08:35 UTC, kisieland commented
np, take your time :)

2022-09-01 12:52 UTC, kisieland commented
@melinath Any progress? :)

2022-09-01 17:59 UTC, melinath approved these changes
sorry for the delay, looks like tests passed

2022-09-01 17:59 UTC, merged