add expiry_time to cloud_identity_group_membership
GoogleCloudPlatform/magic-modules pull request #6375
Opened 2022-08-04 15:38 UTC by MartinNowak

- fixes hashicorp/terraform-provider-google#10343
- premium feature

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudidentity: added `expiry_time` field to `google_cloud_identity_group_membership` resource
```

2022-08-04 15:39 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-08-04 15:53 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6375-old..auto-pr-6375) ( 2 files changed, 77 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6375-old..auto-pr-6375) ( 2 files changed, 77 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6375-old..auto-pr-6375) ( 3 files changed, 33 insertions(+), 3 deletions(-))

2022-08-04 16:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2126` 
Passed tests `1886` 
Skipped tests: `226` 
Failed tests: `14` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary> TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_networkPerformanceConfig|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample|TestAccCloudFunctions2Function_fullUpdate|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccCloudIdentityGroupMembership_update|TestAccCGCSnippet_eventarcWorkflowsExample|TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample|TestAccActiveDirectoryDomain_update|TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample </details>

2022-08-04 17:27 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccCloudFunctions2Function_fullUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCloudFunctions2Function_fullUpdate.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudIdentityGroupMembership_update`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCloudIdentityGroupMembership_update.log)]
`TestAccComputeInstance_networkPerformanceConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccComputeInstance_networkPerformanceConfig.log)]
`TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccActiveDirectoryPeering_activeDirectoryPeeringBasicExample.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccActiveDirectoryDomain_update`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccActiveDirectoryDomain_update.log)]
`TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording/TestAccActiveDirectoryDomain_activeDirectoryDomainBasicExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6375/artifacts/4f9e5927-39b8-4086-9653-3c511636a0f1/recording) for each test

2022-08-05 20:43 UTC, shuyama1 requested changes
Can we add a new test or modify an existing test to test this new field?

2022-08-05 20:43 UTC, shuyama1 commented on mmv1/products/cloudidentity/api.yaml
> +                  name: 'expireTime'
Would you mind marking this field as required? We tend to have at least one subfield of objects to be required to avoid users config an empty block.

2022-09-05 07:42 UTC, MartinNowak commented
Sorry, have no more stake in this PR.

2022-09-05 07:42 UTC, closed without merging