Gc policy read update
GoogleCloudPlatform/magic-modules pull request #6415
Opened 2022-08-16 18:02 UTC by hoangpham95

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2022-08-16 18:02 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-08-16 18:03 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-08-16 18:03 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @c2thorn, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-08-16 18:05 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-08-16 18:16 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6415-old..auto-pr-6415) ( 3 files changed, 46 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6415-old..auto-pr-6415) ( 3 files changed, 46 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6415-old..auto-pr-6415) ( 2 files changed, 60 insertions(+), 43 deletions(-))

2022-08-16 18:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6415/artifacts/59a64f98-08a7-4ffe-b013-068645a93be5/build-log/replaying_test.log)

2022-08-25 18:39 UTC, hoangpham95 commented on mmv1/third_party/terraform/resources/resource_bigtable_gc_policy.go
> +	if err := validateNestedPolicy(result, true); err != nil {
This is a recursive call so this needs to be considered.

2022-08-25 18:41 UTC, hoangpham95 commented on mmv1/third_party/terraform/resources/resource_bigtable_gc_policy.go
> +		version := gc.(bigtable.MaxVersionsGCPolicy)
cast MaxVersionGCPolicy as `float`, not `int`

2022-08-25 18:43 UTC, hoangpham95 commented on mmv1/third_party/terraform/resources/resource_bigtable_gc_policy.go
> +			gcRuleJsonString, err := json.Marshal(gcPolicyToGCRuleString(fi.FullGCPolicy))
json.Marshal is returning bytes, not string, need to be converted to string

2022-08-25 18:45 UTC, hoangpham95 commented on mmv1/third_party/terraform/resources/resource_bigtable_gc_policy.go
> +			gcRuleJsonString, err := json.Marshal(gcPolicyToGCRuleString(fi.FullGCPolicy))
Only set gc_rules when previous field is set too

2022-08-25 18:48 UTC, hoangpham95 commented on mmv1/third_party/terraform/tests/resource_bigtable_gc_policy_test.go
> +						resource.TestCheckResourceAttr("google_bigtable_gc_policy.policy", "gc_rules", ""),
Verify not just gc_rules, compare in string if the gc_rules matches with predefined string.

2022-09-06 22:52 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-09-06 22:56 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-09-06 23:29 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-09-06 23:30 UTC, hoangpham95 commented on mmv1/third_party/terraform/tests/resource_bigtable_gc_policy_test.go
> +					resource.TestCheckResourceAttr(
@kevinsi4508 I haven't found a way to force `Read` before checking this attribute. Does `resource` trigger Read automatically ?

2022-09-06 23:31 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-09-06 23:42 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6415-old..auto-pr-6415) ( 2 files changed, 141 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6415-old..auto-pr-6415) ( 2 files changed, 141 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6415-old..auto-pr-6415) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-06 23:43 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6415/artifacts/14dc1d0c-442a-4cbd-9701-28572833b923/build-log/replaying_test.log)

2022-09-07 18:39 UTC, c2thorn requested changes
Reviewing now that it has been marked as ready. Couple of things:
Looks like the provider build is failing due to 
```
google-beta/resource_bigtable_gc_policy_test.go:190:44: not enough arguments in call to resource.TestCheckResourceAttr
```
Before pushing your next commit, please read the release note guide and update your release note

2022-09-07 22:00 UTC, kevinsi4508 commented
This PR is not ready. @hoangpham95 , could you set it to draft mode? Thanks!

2022-09-08 17:16 UTC, kevinsi4508 commented
To be replaced be https://github.com/GoogleCloudPlatform/magic-modules/pull/6526.

2023-02-08 22:05 UTC, closed without merging