updated two defaults
GoogleCloudPlatform/magic-modules pull request #6478
Opened 2022-08-29 17:11 UTC by edwardmedia

Fixes https://github.com/hashicorp/terraform-provider-google/issues/12411

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
vpcaccess: updated defaults for `minThroughput` and `maxThroughput` on `google_vpc_access_connector`
```

2022-08-29 17:12 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-08-29 17:28 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 8 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 8 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-29 17:48 UTC, edwardmedia commented
@melinath Is it proper to update the valid range from 200-1000 to 500-1000 for the validation function here? What will happen to the existing ones below 500? Happy to remove the proposed change for the function to keep as is. Please let me know

2022-08-29 18:24 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2149` 
Passed tests `1899` 
Skipped tests: `233` 
Failed tests: `17` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample|TestAccVPCAccessConnector_vpcAccessConnectorThroughput|TestAccVPCAccessConnector_vpcAccessConnectorExample|TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccFirebaserulesRelease_BasicRelease|TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudFunctions2Function_fullUpdate|TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccCloudFunctionsFunction_vpcConnector|TestAccAppEngineStandardAppVersion_update </blockquote></details>

2022-08-29 18:39 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccVPCAccessConnector_vpcAccessConnectorExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccVPCAccessConnector_vpcAccessConnectorExample.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCloudFunctions2Function_fullUpdate`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccCloudFunctions2Function_fullUpdate.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccCloudfunctions2function_cloudfunctions2BasicAuditlogsExample.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccCloudFunctionsFunction_vpcConnector`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccCloudFunctionsFunction_vpcConnector.log)]
`TestAccAppEngineStandardAppVersion_update`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccAppEngineStandardAppVersion_update.log)] 

Tests failed during RECORDING mode:
 `TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorThroughput`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccVPCAccessConnector_vpcAccessConnectorThroughput.log)]
`TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/5e8afd82-47db-4c93-a2db-21a4e5983c87/recording) for each test

2022-08-29 18:50 UTC, edwardmedia commented
@melinath noticed that there is an existing validation function which currently allows the range from 200-1000. Due to the backward compatibility concern, decided to keep it as is (instead of change the range to 500-1000

2022-08-29 18:58 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 6 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 6 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-08-29 20:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2149` 
Passed tests `1906` 
Skipped tests: `233` 
Failed tests: `10` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccVPCAccessConnector_vpcAccessConnectorThroughput|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccCGCSnippet_eventarcWorkflowsExample|TestAccSqlDatabaseInstance_SqlServerAuditConfig </blockquote></details>

2022-08-29 20:15 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccVPCAccessConnector_vpcAccessConnectorThroughput`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccVPCAccessConnector_vpcAccessConnectorThroughput.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)]
`TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[view](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/14e0caf5-1ba4-41ad-8ddc-5a30fa489e5b/recording) for each test

2022-08-29 22:34 UTC, melinath commented
This would be a breaking change for existing users - unless they're already broken in all cases by using this default?

Alternately could we change these fields to default_from_api?

2022-08-29 22:48 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 7 insertions(+), 7 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6478-old..auto-pr-6478) ( 3 files changed, 8 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6478-old..auto-pr-6478) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-6478-old..auto-pr-6478) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2022-08-29 23:06 UTC, edwardmedia commented
added `default_from_api`

2022-08-29 23:15 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 9 insertions(+), 7 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6478-old..auto-pr-6478) ( 3 files changed, 10 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6478-old..auto-pr-6478) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Cloud Doc Samples: [Diff](https://github.com/modular-magician/terraform-docs-samples/compare/auto-pr-6478-old..auto-pr-6478) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2022-08-29 23:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2151` 
Passed tests `10` 
Skipped tests: `233` 
Failed tests: `1908` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataSourceCloudIdentityGroupMemberships_basic|TestAccDataSourceCloudIdentityGroups_basic|TestAccDataSourceComputeLbIpRanges_basic|TestAccDataSourceGoogleActiveFolder_default|TestAccDataSourceGoogleActiveFolder_space|TestAccDataSourceGoogleActiveFolder_dash|TestAccDataSourceGoogleBillingAccount_byFullName|TestAccDataSourceGoogleBillingAccount_byShortName|TestAccDataSourceGoogleBillingAccount_byFullNameClosed|TestAccDataSourceGoogleBillingAccount_byDisplayName|TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleFolderOrganizationPolicy_basic|TestAccDataSourceGoogleFolder_byFullName|TestAccDataSourceGoogleFolder_byShortName|TestAccDataSourceGoogleFolder_lookupOrganization|TestAccDataSourceGoogleFolder_byFullNameNotFound|TestAccDataSourceIAMRole|TestAccDataSourceGoogleKmsCryptoKey_basic|TestAccDataSourceGoogleKmsCryptoKeyVersion_basic|TestAccDataSourceGoogleKmsKeyRing_basic|TestAccDataSourceGoogleMonitoringUptimeCheckIps_basic|TestAccDataSourceGoogleNetblockIpRanges_basic|TestAccDataSourceGoogleOrganization_byFullName|TestAccDataSourceGoogleOrganization_byShortName|TestAccDataSourceGoogleOrganization_byDomain|TestAccDataSourceGoogleProjectOrganizationPolicy_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNoDisplayNameOrType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccDataSourceStorageBucketObjectContent_Basic|TestAccDataSourceGoogleTagsTagKey_default|TestAccDataSourceGoogleTagsTagKey_dot|TestAccDataSourceGoogleTagsTagValue_default|TestAccDataSourceGoogleTagsTagValue_dot|TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigqueryDataTransferConfig|TestAccComputeAddress_internal|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceFromTemplate_overrideMetadataDotStartupScript|TestAccComputeInstance_networkTier|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_withBackendAndIAP|TestAccComputeRoute_hopInstance|TestAccComputeSharedVpc_basic|TestAccComputeTargetSslProxy_update|TestAccDNSManagedZone_forceDestroy|TestAccOrganizationPolicy|TestAccProjectOrganizationPolicy|TestAccKmsKeyRing_basic|TestAccMonitoringAlertPolicy|TestAccNotebooksInstance_update|TestAccNotebooksRuntime_update|TestAccTags|TestAccComputeResourceUsageExportBucket|TestAccPubsubTopic_pubsubTopicGeoRestrictedExample|TestAccSpannerDatabase_versionRetentionPeriod|TestAccServiceUsageConsumerQuotaOverride_consumerQuotaOverrideCustomDimensionExample|TestAccSourceRepoRepository_basic|TestAccSpannerDatabaseIamPolicy|TestAccIapTunnelInstanceIamBindingGenerated|TestAccSpannerDatabase_basic|TestAccSpannerDatabaseIamBinding|TestAccSqlDatabaseInstance_basic_with_user_labels|TestAccSpannerDatabaseIamMember|TestAccSpannerInstanceIamMember|TestAccSqlDatabaseInstance_mysqlMajorVersionUpgrade|TestAccSourceRepoRepository_sourcerepoRepositoryFullExample|TestAccServiceUsageConsumerQuotaOverride_consumerQuotaOverrideZeroValueExample|TestAccSourceRepoRepository_update|TestAccServiceUsageConsumerQuotaOverride_regionConsumerQuotaOverrideExample|TestAccSpannerDatabase_postgres|TestAccSqlDatabaseInstance_SqlServerAuditConfig|TestAccIapTunnelInstanceIamMemberGenerated|TestAccServiceNetworkingConnection_update|TestAccSecretManagerSecretVersion_update|TestAccSourceRepoRepository_sourcerepoRepositoryBasicExample|TestAccSpannerInstanceIamBinding|TestAccDataSourceGameServicesGameServerDeploymentRollout_basic|TestAccServiceUsageConsumerQuotaOverride_consumerQuotaOverrideExample|TestAccSpannerInstanceIamPolicy|TestAccIapAppEngineVersionIamMemberGenerated_withCondition|TestAccIapAppEngineVersionIamMemberGenerated|TestAccIapAppEngineServiceIamMemberGenerated_withCondition|TestAccIapAppEngineVersionIamBindingGenerated|TestAccIapAppEngineServiceIamPolicyGenerated_withCondition|TestAccIapAppEngineServiceIamPolicyGenerated|TestAccIapAppEngineVersionIamBindingGenerated_withCondition|TestAccIapAppEngineVersionIamPolicyGenerated_withCondition|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentDailyMidnightExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentBasicExample|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentInstanceExample|TestAccIapAppEngineVersionIamPolicyGenerated|TestAccHealthcareConsentStoreIamMemberGenerated|TestAccOsConfigOsPolicyAssignment_FixedOsPolicyAssignment|TestAccOSConfigPatchDeployment_osConfigPatchDeploymentDailyExample|TestAccIapAppEngineServiceIamBindingGenerated_withCondition|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesPackagesExample|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesRecipesExample|TestAccOrgPolicyPolicy_ProjectPolicy|TestAccHealthcareConsentStoreIamPolicyGenerated|TestAccHealthcareConsentStoreIamBindingGenerated|TestAccOsConfigOsPolicyAssignment_PercentOsPolicyAssignment|TestAccIapAppEngineServiceIamBindingGenerated|TestAccOSConfigGuestPolicies_osConfigGuestPoliciesBasicExample|TestAccIapAppEngineServiceIamMemberGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccIapTunnelIamMemberGenerated_withCondition|TestAccIapTunnelIamPolicyGenerated|TestAccIapTunnelIamMemberGenerated|TestAccIapTunnelIamPolicyGenerated_withCondition|TestAccIapTunnelIamBindingGenerated|TestAccIapTunnelIamBindingGenerated_withCondition|TestAccGKEHubMembershipIamMemberGenerated|TestAccOrgPolicyPolicy_OrganizationPolicy|TestAccOrgPolicyPolicy_FolderPolicy|TestAccServiceManagementServiceIamBindingGenerated|TestAccMonitoringUptimeCheckConfig_uptimeCheckConfigHttpExample|TestAccNotebooksInstance_create_gpu|TestAccServiceManagementServiceIamMemberGenerated|TestAccGKEHubMembershipIamBindingGenerated|TestAccServiceManagementServiceIamPolicyGenerated|TestAccNotebooksRuntime_notebookRuntimeScriptExample|TestAccServiceManagementServiceConsumersIamPolicyGenerated|TestAccOrgPolicyPolicy_EnforcePolicy|TestAccNotebooksRuntime_notebookRuntimeKernelsExample|TestAccNotebooksRuntime_notebookRuntimeBasicExample|TestAccNotebooksRuntime_notebookRuntimeBasicContainerExample|TestAccNotebooksRuntime_notebookRuntimeBasicGpuExample|TestAccNotebooksInstance_notebookInstanceBasicExample|TestAccNotebooksInstance_notebookInstanceFullExample|TestAccServiceManagementServiceConsumersIamBindingGenerated|TestAccDataprocMetastoreServiceIamPolicyGenerated|TestAccNotebooksInstance_notebookInstanceBasicContainerExample|TestAccServiceManagementServiceConsumersIamMemberGenerated|TestAccDataprocMetastoreServiceIamMemberGenerated|TestAccNotebooksInstance_create_vm_image|TestAccNotebooksInstance_notebookInstanceBasicGpuExample|TestAccNotebooksInstance_create_container|TestAccDataprocMetastoreServiceIamBindingGenerated|TestAccNetworkServicesEdgeCacheService_updateAndImport|TestAccNotebooksEnvironment_notebookEnvironmentBasicExample|TestAccDataprocMetastoreFederationIamPolicyGenerated|TestAccNotebooksEnvironment_create|TestAccDataprocMetastoreFederationIamMemberGenerated|TestAccNetworkServicesEdgeCacheOrigin_networkServicesEdgeCacheOriginAdvancedExample|TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceBasicExample|TestAccNetworkServicesEdgeCacheService_networkServicesEdgeCacheServiceAdvancedExample|TestAccNetworkServicesEdgeCacheOrigin_updateAndImport|TestAccNetworkServicesEdgeCacheOrigin_networkServicesEdgeCacheOriginBasicExample|TestAccDataprocAutoscalingPolicyIamPolicyGenerated [...]

2022-09-01 18:41 UTC, melinath requested changes

2022-09-01 18:41 UTC, melinath commented on mmv1/products/vpcaccess/api.yaml
> +        default_value: 500
We need to remove the defaults in addition to setting optional + computed. It's fine to update the docstrings though.

```suggestion
```

2022-09-01 18:41 UTC, melinath commented on mmv1/products/vpcaccess/api.yaml
> +        default_value: 1000
```suggestion
```

2022-09-03 22:29 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 7 insertions(+), 7 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6478-old..auto-pr-6478) ( 3 files changed, 8 insertions(+), 8 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6478-old..auto-pr-6478) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6478-old..auto-pr-6478) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2022-09-03 23:34 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2156` 
Passed tests `1910` 
Skipped tests: `234` 
Failed tests: `12` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccVPCAccessConnector_vpcAccessConnectorExample|TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample|TestAccVPCAccessConnector_vpcAccessConnectorThroughput|TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample|TestAccComputeInstance_soleTenantNodeAffinities|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccAppEngineStandardAppVersion_update|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccSqlDatabaseInstance_SqlServerAuditConfig </blockquote></details>

2022-09-03 23:43 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccVPCAccessConnector_vpcAccessConnectorThroughput`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccVPCAccessConnector_vpcAccessConnectorThroughput.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthoritySubordinateExample.log)] 

Tests failed during RECORDING mode:
 `TestAccVPCAccessConnector_vpcAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccVPCAccessConnector_vpcAccessConnectorExample.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample.log)]
`TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccComputeGlobalForwardingRule_internalLoadBalancing_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccCloudFunctionsFunction_vpcConnector`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccCloudFunctionsFunction_vpcConnector_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccCloudFunctionsFunction_vpcConnector.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccCloudRunService_cloudRunServiceStaticOutboundExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange.log)]
`TestAccSqlDatabaseInstance_SqlServerAuditConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_build/TestAccSqlDatabaseInstance_SqlServerAuditConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording/TestAccSqlDatabaseInstance_SqlServerAuditConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6478/artifacts/bf0afc4e-1811-4623-be12-75e8ce27aa95/recording) for each test

2022-09-12 21:03 UTC, melinath approved these changes
LGTM

2022-09-12 21:04 UTC, merged