Added overwrite_when attribute in storage_transfer_job
GoogleCloudPlatform/magic-modules pull request #6544
Opened 2022-09-13 09:09 UTC by AlfatahB

Added overwrite_when attribute in google_storage_transfer_job resource. 

fixes https://github.com/hashicorp/terraform-provider-google/issues/11854

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
storage: added support for `overwriteWhen` option to `transfer_options` in `google_storage_transfer_job`
```

2022-09-13 09:10 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-09-13 09:21 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 119 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 119 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 09:37 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/f69aa321-3de3-4cd7-8a4d-614cf0a977a7/build-log/replaying_test.log)

2022-09-13 10:05 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 119 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 119 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 10:34 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/6ebf87a0-14ec-4a29-b7f6-ea3501a8d39a/build-log/replaying_test.log)

2022-09-13 11:17 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 20 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 20 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 11:49 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/2fe7ef06-746a-4a79-93bc-12469b8cf388/build-log/replaying_test.log)

2022-09-13 12:18 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 20 insertions(+), 11 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 20 insertions(+), 11 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 12:34 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/7206101d-7a9b-4f25-ad91-e1b62ce73273/build-log/replaying_test.log)

2022-09-13 12:50 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 10 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 10 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 14:01 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2171` 
Passed tests `1924` 
Skipped tests: `238` 
Failed tests: `9` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccStorageTransferJob_transferOptions|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCloudFunctionsFunction_vpcConnector|TestAccCloudRunService_cloudRunServiceStaticOutboundExample|TestAccAppEngineStandardAppVersion_update|TestAccVPCAccessConnector_vpcAccessConnectorExample|TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample|TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample </blockquote></details>

2022-09-13 14:07 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccStorageTransferJob_transferOptions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccStorageTransferJob_transferOptions.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCloudFunctionsFunction_vpcConnector`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccCloudFunctionsFunction_vpcConnector_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccCloudFunctionsFunction_vpcConnector.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccCloudRunService_cloudRunServiceStaticOutboundExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccVPCAccessConnector_vpcAccessConnectorExample.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample.log)]
`TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_build/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d31160e0-9f5f-447e-8a6c-243c3b22900b/recording) for each test

2022-09-13 15:16 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-13 16:13 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCloudFunctionsFunction_vpcConnector`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccCloudFunctionsFunction_vpcConnector_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccCloudFunctionsFunction_vpcConnector.log)]
`TestAccCloudRunService_cloudRunServiceStaticOutboundExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccCloudRunService_cloudRunServiceStaticOutboundExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccCloudRunService_cloudRunServiceStaticOutboundExample.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)]
`TestAccAppEngineStandardAppVersion_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccAppEngineStandardAppVersion_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccVPCAccessConnector_vpcAccessConnectorSharedVPCExample.log)]
`TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccVPCAccessConnector_cloudrunVPCAccessConnectorExample.log)]
`TestAccVPCAccessConnector_vpcAccessConnectorExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_build/TestAccVPCAccessConnector_vpcAccessConnectorExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording/TestAccVPCAccessConnector_vpcAccessConnectorExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/d6487ae0-c55f-4571-afcd-32a3e7e2e71b/recording) for each test

2022-09-15 12:04 UTC, AlfatahB commented
@shuyama1 Could you please review this PR?

2022-09-15 17:27 UTC, shuyama1 requested changes
LGTM in general! Just one nitpick.

2022-09-15 18:04 UTC, AlfatahB commented on mmv1/third_party/terraform/website/docs/r/storage_transfer_job.html.markdown
> +* `overwrite_when` - (Optional) When to overwrite objects that already exist in the sink. If not set, overwrite behavior is determined by `overwriteObjectsAlreadyExistingInSink`. Possible values: ALW
Sure, I've made the changes in this [commit](https://github.com/GoogleCloudPlatform/magic-modules/pull/6544/commits/acd9494595755572493d18eaf1a05a0128fc8bd7)

2022-09-15 18:14 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6544-old..auto-pr-6544) ( 3 files changed, 19 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6544-old..auto-pr-6544) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-15 19:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2172` 
Passed tests `1931` 
Skipped tests: `238` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-09-15 19:09 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6544/artifacts/dab5a5d0-2b71-4425-aaf9-2bc0a308e694/recording) for each test

2022-09-15 20:05 UTC, shuyama1 approved these changes
LGTM! Thank you!

2022-09-15 20:05 UTC, merged