Fixed : Failing test(s): TestAccDataflowJobWithAdditionalExperiments permadiff on google_dataflow_job.labels
GoogleCloudPlatform/magic-modules pull request #6602
Opened 2022-09-26 07:25 UTC by AarshDhokai

Fixed the issue : [Failing test(s): TestAccDataflowJobWithAdditionalExperiments permadiff on google_dataflow_job.labels #12525](https://github.com/hashicorp/terraform-provider-google/issues/12525)

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: Fixed permadiff on `additional_experiments` for `resource_dataflow_job`

```

2022-09-26 07:26 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-09-26 07:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 16 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 16 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-26 08:30 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2179` 
Passed tests `1939` 
Skipped tests: `238` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-09-26 08:35 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/dbebf481-b59b-44fa-9fd3-0301c07ee410/recording) for each test

2022-09-28 09:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 16 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 16 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-28 10:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2183` 
Passed tests `1942` 
Skipped tests: `238` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataflowJobWithAdditionalExperiments|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-09-28 10:32 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataflowJobWithAdditionalExperiments`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/recording/TestAccDataflowJobWithAdditionalExperiments.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/47d68e6a-66bf-4cb7-903b-2642712a9475/recording) for each test

2022-09-29 11:54 UTC, mitj04 commented
LGTM

2022-10-03 18:27 UTC, melinath commented
So just to have a record here of what's going on.

The test is only trying to set two additional_experiments: https://github.com/hashicorp/terraform-provider-google/blob/21c447bf4b721018eed51bf1b75c2f073136d004/google/resource_dataflow_job_test.go#L324

But after the resource is created, there's an additional experiment added by the API. The resource is create-only, so one option is to ignore any experiments that look like they were added by the API - i.e. that are not in the configuration. The problem with that is that it does make the resource less "accurate" since we won't be able to detect all kinds of drift on the field.

Creating a job happens with https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.templates/create

But reading a job happens with https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs/get

So this is not a situation where a single API is returning a different value than was provided - we're creating the resource with a separate API than we're using to read it. Still, this would probably be best resolved by the API returning the additional_experiments field as part of the job resource.

2022-11-10 23:43 UTC, melinath requested changes
coming back to this after some time - since this field is being set on one resource but then read from another, let's just ignore the result from the API altogether. It's not ideal but I think it'll be what's best for this resource.

2022-11-18 17:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 17 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 17 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-18 18:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2275` 
Passed tests `2029` 
Skipped tests: `243` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeForwardingRule_update </blockquote></details>

2022-11-18 18:17 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/8a4c9d7e-f573-4654-98c9-7af40bf6fdb1/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/8a4c9d7e-f573-4654-98c9-7af40bf6fdb1/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/8a4c9d7e-f573-4654-98c9-7af40bf6fdb1/recording/TestAccComputeForwardingRule_update.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/8a4c9d7e-f573-4654-98c9-7af40bf6fdb1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/8a4c9d7e-f573-4654-98c9-7af40bf6fdb1/recording) for each test

2022-11-18 18:39 UTC, melinath requested changes

2022-11-18 18:39 UTC, melinath commented on mmv1/third_party/terraform/tests/resource_dataflow_job_test.go.erb
> +	//skipIfVcr(t)
```suggestion
	skipIfVcr(t)
```

2022-11-18 18:39 UTC, melinath commented on mmv1/third_party/terraform/resources/resource_dataflow_job.go.erb
> +	if addExper, ok := d.GetOk("additional_experiments"); ok {
I'd like to suggest removing this section altogether and just not setting this field on read at all.

2022-11-21 05:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 2 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 2 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-21 06:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2277` 
Passed tests `2025` 
Skipped tests: `243` 
Failed tests: `9` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample|TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample|TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample|TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample </blockquote></details>

2022-11-21 06:29 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccComputeGlobalForwardingRule_internalLoadBalancing`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeGlobalForwardingRule_internalLoadBalancing.log)]
`TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample.log)]
`TestAccComputeForwardingRule_forwardingRuleHttpLbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeForwardingRule_forwardingRuleHttpLbExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample.log)]
`TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample.log)]
`TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/01e5867a-1502-4124-9690-0fc7dd5632ae/recording) for each test

2022-11-28 21:34 UTC, melinath requested changes

2022-11-28 21:34 UTC, melinath commented on mmv1/third_party/terraform/tests/resource_dataflow_job_test.go.erb
> +	// skipIfVcr(t)
```suggestion
	skipIfVcr(t)
```

2022-11-29 05:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 1 insertion(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 1 insertion(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-29 06:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2302` 
Passed tests `2048` 
Skipped tests: `244` 
Failed tests: `10` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataFusionInstance_dataFusionInstanceZoneExample|TestAccDataFusionInstance_dataFusionInstanceEventExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccVertexAIIndex_updated|TestAccVertexAIIndex_vertexAiIndexStreamingExample|TestAccVertexAIIndex_vertexAiIndexExample|TestAccDataFusionInstanceIamMemberGenerated|TestAccDataFusionInstanceIamPolicyGenerated|TestAccDataFusionInstanceIamBindingGenerated|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-11-29 07:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataFusionInstance_dataFusionInstanceZoneExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstance_dataFusionInstanceZoneExample.log)]
`TestAccDataFusionInstance_dataFusionInstanceEventExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstance_dataFusionInstanceEventExample.log)]
`TestAccDataFusionInstance_dataFusionInstanceFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstance_dataFusionInstanceFullExample.log)]
`TestAccVertexAIIndex_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccVertexAIIndex_updated.log)]
`TestAccVertexAIIndex_vertexAiIndexStreamingExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccVertexAIIndex_vertexAiIndexStreamingExample.log)]
`TestAccVertexAIIndex_vertexAiIndexExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccVertexAIIndex_vertexAiIndexExample.log)]
`TestAccDataFusionInstanceIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstanceIamPolicyGenerated.log)]
`TestAccDataFusionInstanceIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstanceIamBindingGenerated.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

Tests failed during RECORDING mode:
 `TestAccDataFusionInstanceIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/build-log/recording_build/TestAccDataFusionInstanceIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording/TestAccDataFusionInstanceIamMemberGenerated.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/911e3f83-f797-4626-b646-2a6eba96345a/recording) for each test

2022-11-29 09:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 1 insertion(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 1 insertion(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6602-old..auto-pr-6602) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-29 10:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2302` 
Passed tests `2055` 
Skipped tests: `244` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccDataFusionInstanceIamMemberGenerated|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-11-29 10:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/19dc0c7b-813e-4219-8a83-9f05da3a9265/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccDataFusionInstanceIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/19dc0c7b-813e-4219-8a83-9f05da3a9265/recording/TestAccDataFusionInstanceIamMemberGenerated.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/19dc0c7b-813e-4219-8a83-9f05da3a9265/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/19dc0c7b-813e-4219-8a83-9f05da3a9265/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6602/artifacts/19dc0c7b-813e-4219-8a83-9f05da3a9265/recording) for each test

2022-11-29 19:40 UTC, melinath approved these changes

2022-11-29 19:40 UTC, merged