Adding data source support for google_compute_region_network_endpoint_group
GoogleCloudPlatform/magic-modules pull request #6606
Opened 2022-09-27 19:16 UTC by googlerjk

Adding support for data source to `google_compute_region_network_endpoint_group` resource

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource

compute: added support for `data` source to `google_compute_region_network_endpoint_group` resource.

```

2022-09-27 19:28 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6606-old..auto-pr-6606) ( 4 files changed, 227 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6606-old..auto-pr-6606) ( 4 files changed, 227 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6606-old..auto-pr-6606) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-09-27 20:42 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccPrivatecaCaPoolIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccPrivatecaCaPoolIamPolicyGenerated_withCondition.log)]
`TestAccStorageTransferJob_transferOptions`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccStorageTransferJob_transferOptions.log)]
`TestAccComputeRegionBackendServiceIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccComputeRegionBackendServiceIamPolicyGenerated_withCondition.log)]
`TestAccComputeMachineImageIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccComputeMachineImageIamPolicyGenerated_withCondition.log)]
`TestAccComputeInstanceIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccComputeInstanceIamPolicyGenerated_withCondition.log)]
`TestAccComputeBackendServiceIamPolicyGenerated_withCondition`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccComputeBackendServiceIamPolicyGenerated_withCondition.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/868dc87c-70ef-4c2b-babf-bd60bc118773/recording) for each test

2022-09-27 22:34 UTC, ScottSuarez commented
Hi @googlerjk,

Check the [release-notes guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md#:~:text=New%20Resources%20And%20Datasources%3A%20(note%20no%20service%20name%20or%20New%20Resource%20tag)) for guidance on notations for new datasources. I notice there are two reviewers, not sure who the intended reviewer is ^^.

2022-09-28 00:15 UTC, googlerjk commented
updated, thanks!

2022-10-03 06:41 UTC, googlerjk commented
https://github.com/hashicorp/terraform-provider-google/issues/10989

2022-10-03 22:18 UTC, c2thorn requested changes

2022-10-03 22:18 UTC, c2thorn commented on mmv1/third_party/terraform/utils/provider.go.erb
> +			"google_compute_region_network_endpoint_group":		dataSourceGoogleComputeRegionNetworkEndpointGroup(),
I believe this list is roughly alphabetized, making this line appear below the next ("google_compute_region_instance_group")

2022-10-03 22:18 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/d/compute_region_network_endpoint_group.markdown
> +resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
Since this isn't the example used in the test, how was this tested? did you manually run it?

2022-10-03 22:18 UTC, c2thorn commented on mmv1/third_party/terraform/data_sources/data_source_compute_region_network_endpoint_group.go.erb
> +	return &schema.Resource{
I think this should follow the same formula as the non-region counterpart: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/data_sources/data_source_compute_network_endpoint_group.go#L12

As of right now, this data source only supports fields for `name`,`region`,`project`, and `self_link` and none of the other attributes from the resource version defined in the Attributes Reference

2022-10-03 22:18 UTC, c2thorn commented on mmv1/third_party/terraform/tests/data_source_google_compute_region_network_endpoint_group_test.go.erb
> +					resource.TestCheckResourceAttr("data.google_compute_region_network_endpoint_group.data_source", "name", rnegName),
we should check other resource attributes like `network_endpoint_type`

2022-10-03 22:18 UTC, c2thorn commented on mmv1/third_party/terraform/data_sources/data_source_compute_region_network_endpoint_group.go.erb
> +<% autogen_exception -%>
These files have no ruby injected into them, so we should make them `.go` files instead of `.go.erb` files and remove this autogen exception line

2022-10-05 05:12 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6606-old..auto-pr-6606) ( 4 files changed, 228 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6606-old..auto-pr-6606) ( 4 files changed, 228 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6606-old..auto-pr-6606) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-05 06:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2201` 
Passed tests `1957` 
Skipped tests: `241` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-10-05 06:06 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6606/artifacts/e7c690d2-161f-4077-ae71-b23a4111c395/recording) for each test

2022-10-06 16:43 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/d/compute_region_network_endpoint_group.markdown
> +resource "google_compute_region_network_endpoint_group" "cloudrun_neg" {
@googlerjk this question still applies

2022-10-06 16:44 UTC, c2thorn commented on mmv1/third_party/terraform/tests/data_source_google_compute_region_network_endpoint_group_test.go.erb
> +					resource.TestCheckResourceAttr("data.google_compute_region_network_endpoint_group.data_source", "name", rnegName),
@googlerjk this comment still applies

2022-10-06 21:32 UTC, closed without merging