Add support for disk config on the GKE Node Auto provisioning
GoogleCloudPlatform/magic-modules pull request #6649
Opened 2022-10-05 15:17 UTC by mrvarmazyar

In this PR, I've added the feature to pass the `disk_size` and `disk_type` on the GKE node auto provisioning defaults to specify and change the default values on the provisioned nodes by NAP. 

Related Configurations on the Google API: [Link](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#autoprovisioningnodepooldefaults) 
Related issue: https://github.com/hashicorp/terraform-provider-google/issues/12722

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: Added support for the Disk type and size configuration on the GKE Node Auto-provisioning
```

2022-10-05 15:56 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-10-05 22:21 UTC, shuyama1 commented
/gcbrun

2022-10-05 22:32 UTC, shuyama1 commented on mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown
> +
```suggestion
* `disk_size` - (Optional) Size of the disk attached to each node, specified in GB. The smallest allowed disk size is 10GB. Defaults to `100`

* `disk_type` - (Optional) Type of the disk attached to each node (e.g. 'pd-standard', 'pd-ssd' or 'pd-balanced'). Defaults to `pd-standard`
```
Nit: let's also include the default in the doc.

2022-10-05 22:32 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +										Default:     "100",
```suggestion
										Default:     100,
```
Since the type of this field is Int. We also need to modify them in the tests.

2022-10-06 18:17 UTC, shuyama1 requested changes
The build failed due to error:
`google/resource_container_cluster.go:3138:19: cannot use config["disk_size"].(int) (comma, ok expression of type int) as type int64 in struct literal`
Therefore, proposed following changes.

2022-10-06 18:17 UTC, shuyama1 commented on mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
> +		DiskSizeGbCfg = `disk_size = "120"`
```suggestion
		DiskSizeGbCfg = `disk_size = 120`
```

2022-10-06 18:17 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +		DiskSizeGb:     config["disk_size"].(int),
```suggestion
		DiskSizeGb:     int64(config["disk_size"].(int)),
```

2022-10-06 19:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2208` 
Passed tests `1960` 
Skipped tests: `240` 
Failed tests: `8` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb|TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-10-06 19:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_nodeAutoprovisioningDefaults`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaults.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/build-log/recording_build/TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/build-log/recording_build/TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType.log)]
`TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/099d0c42-6ddd-4111-9ca6-d9a5b40d4368/recording) for each test

2022-10-07 19:24 UTC, shuyama1 commented
Related tests failed due to error:
```
provider_test.go:315: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=54) {
         (string) (len=11) "node_pool.#": (string) (len=1) "2",
         (string) (len=13) "node_pool.1.%": (string) (len=2) "15",
         (string) (len=25) "node_pool.1.autoscaling.#": (string) (len=1) "1",
         (string) (len=27) "node_pool.1.autoscaling.0.%": (string) (len=1) "5",
         (string) (len=41) "node_pool.1.autoscaling.0.location_policy": (string) "",
         (string) (len=40) "node_pool.1.autoscaling.0.max_node_count": (string) (len=4) "1000",
         (string) (len=40) "node_pool.1.autoscaling.0.min_node_count": (string) (len=1) "0",
         (string) (len=46) "node_pool.1.autoscaling.0.total_max_node_count": (string) (len=1) "0",
         (string) (len=46) "node_pool.1.autoscaling.0.total_min_node_count": (string) (len=1) "0",
         (string) (len=30) "node_pool.1.initial_node_count": (string) (len=1) "0",
         (string) (len=33) "node_pool.1.instance_group_urls.#": (string) (len=1) "1",
         (string) (len=33) "node_pool.1.instance_group_urls.0": (string) (len=162) "https://www.googleapis.com/compute/v1/projects/ci-test-project-188019/zones/us-central1-a/instanceGroupManagers/gke-tf-test-cluster--nap-e2-medium-1v-ea9d0b6c-grp",
         (string) (len=41) "node_pool.1.managed_instance_group_urls.#": (string) (len=1) "1",
         (string) (len=41) "node_pool.1.managed_instance_group_urls.0": (string) (len=157) "https://www.googleapis.com/compute/beta/projects/ci-test-project-188019/zones/us-central1-a/instanceGroups/gke-tf-test-cluster--nap-e2-medium-1v-ea9d0b6c-grp",
         (string) (len=24) "node_pool.1.management.#": (string) (len=1) "1",
         (string) (len=26) "node_pool.1.management.0.%": (string) (len=1) "2",
         (string) (len=36) "node_pool.1.management.0.auto_repair": (string) (len=4) "true",
         (string) (len=37) "node_pool.1.management.0.auto_upgrade": (string) (len=4) "true",
         (string) (len=29) "node_pool.1.max_pods_per_node": (string) (len=1) "0",
         (string) (len=16) "node_pool.1.name": (string) (len=22) "nap-e2-medium-1vp52gpm",
         (string) (len=23) "node_pool.1.name_prefix": (string) "",
         (string) (len=25) "node_pool.1.node_config.#": (string) (len=1) "1",
         (string) (len=27) "node_pool.1.node_config.0.%": (string) (len=2) "26",
         (string) (len=43) "node_pool.1.node_config.0.boot_disk_kms_key": (string) "",
         (string) (len=38) "node_pool.1.node_config.0.disk_size_gb": (string) (len=3) "100",
         (string) (len=35) "node_pool.1.node_config.0.disk_type": (string) (len=11) "pd-standard",
         (string) (len=36) "node_pool.1.node_config.0.image_type": (string) (len=14) "COS_CONTAINERD",
         (string) (len=41) "node_pool.1.node_config.0.local_ssd_count": (string) (len=1) "0",
         (string) (len=38) "node_pool.1.node_config.0.machine_type": (string) (len=9) "e2-medium",
         (string) (len=36) "node_pool.1.node_config.0.metadata.%": (string) (len=1) "1",
         (string) (len=59) "node_pool.1.node_config.0.metadata.disable-legacy-endpoints": (string) (len=4) "true",
         (string) (len=42) "node_pool.1.node_config.0.min_cpu_platform": (string) "",
         (string) (len=36) "node_pool.1.node_config.0.node_group": (string) "",
         (string) (len=40) "node_pool.1.node_config.0.oauth_scopes.#": (string) (len=1) "2",
         (string) (len=40) "node_pool.1.node_config.0.oauth_scopes.0": (string) (len=46) "https://www.googleapis.com/auth/cloud-platform",
         (string) (len=40) "node_pool.1.node_config.0.oauth_scopes.1": (string) (len=46) "https://www.googleapis.com/auth/userinfo.email",
         (string) (len=37) "node_pool.1.node_config.0.preemptible": (string) (len=5) "false",
         (string) (len=41) "node_pool.1.node_config.0.service_account": (string) (len=7) "default",
         (string) (len=52) "node_pool.1.node_config.0.shielded_instance_config.#": (string) (len=1) "1",
         (string) (len=54) "node_pool.1.node_config.0.shielded_instance_config.0.%": (string) (len=1) "2",
         (string) (len=80) "node_pool.1.node_config.0.shielded_instance_config.0.enable_integrity_monitoring": (string) (len=4) "true",
         (string) (len=71) "node_pool.1.node_config.0.shielded_instance_config.0.enable_secure_boot": (string) (len=5) "false",
         (string) (len=30) "node_pool.1.node_config.0.spot": (string) (len=5) "false",
         (string) (len=22) "node_pool.1.node_count": (string) (len=1) "0",
         (string) (len=28) "node_pool.1.node_locations.#": (string) (len=1) "1",
         (string) (len=28) "node_pool.1.node_locations.0": (string) (len=13) "us-central1-a",
         (string) (len=30) "node_pool.1.placement_policy.#": (string) (len=1) "1",
         (string) (len=32) "node_pool.1.placement_policy.0.%": (string) (len=1) "1",
         (string) (len=35) "node_pool.1.placement_policy.0.type": (string) "",
         (string) (len=30) "node_pool.1.upgrade_settings.#": (string) (len=1) "1",
         (string) (len=32) "node_pool.1.upgrade_settings.0.%": (string) (len=1) "2",
         (string) (len=40) "node_pool.1.upgrade_settings.0.max_surge": (string) (len=1) "1",
         (string) (len=46) "node_pool.1.upgrade_settings.0.max_unavailable": (string) (len=1) "0",
         (string) (len=19) "node_pool.1.version": (string) (len=14) "1.24.4-gke.800"
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=11) "node_pool.#": (string) (len=1) "1"
        }
```

2022-10-07 21:26 UTC, mrvarmazyar commented
@shuyama1 Thanks, since the API accepts the disk size as an integer and on the other hand I don't see the full test log, should I change the `disk_size_gb` to string? 

> Related tests failed due to error:
> 
> ```
> provider_test.go:315: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
>         
>         (map[string]string) (len=54) {
.
.
>          (string) (len=38) "node_pool.1.node_config.0.disk_size_gb": (string) (len=3) "100",
>          (string) (len=35) "node_pool.1.node_config.0.disk_type": (string) (len=11) "pd-standard",
.
.
> ```

2022-10-11 16:09 UTC, shuyama1 commented
/gcbrun

2022-10-11 16:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6649-old..auto-pr-6649) ( 3 files changed, 152 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6649-old..auto-pr-6649) ( 3 files changed, 152 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6649-old..auto-pr-6649) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-11 17:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2218` 
Passed tests `1973` 
Skipped tests: `240` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform|TestAccComputeInstance_soleTenantNodeAffinities|TestAccCGCSnippet_eventarcWorkflowsExample </blockquote></details>

2022-10-11 17:11 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsMinCpuPlatform.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)]
`TestAccCGCSnippet_eventarcWorkflowsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/build-log/recording_build/TestAccCGCSnippet_eventarcWorkflowsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording/TestAccCGCSnippet_eventarcWorkflowsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6649/artifacts/1e503119-a8c1-4836-aa53-258de59f82f1/recording) for each test

2022-10-13 17:57 UTC, shuyama1 approved these changes
LGTM! Thanks!

2022-10-13 17:58 UTC, merged