Adds `liveness_probe` field to `google_cloud_run_service` resource for beta
GoogleCloudPlatform/magic-modules pull request #6677
Opened 2022-10-11 01:15 UTC by yanweiguo

Part of https://github.com/hashicorp/terraform-provider-google/issues/12532.

Adds `liveness_probe` field to `google_cloud_run_service` resource for google beta provider.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudrun: added field `liveness_probe` to resource `google_cloud_run_service` (beta)
```

2022-10-11 01:17 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-10-11 01:30 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6677-old..auto-pr-6677) ( 1 file changed, 62 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6677-old..auto-pr-6677) ( 4 files changed, 450 insertions(+), 15 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6677-old..auto-pr-6677) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-11 02:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2215` 
Passed tests `1971` 
Skipped tests: `240` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccComputeInstance_soleTenantNodeAffinities|TestAccCloudRunService_cloudRunServiceProbesExample|TestAccCloudRunService_probes|TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2022-10-11 02:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccCloudRunService_cloudRunServiceProbesExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/recording/TestAccCloudRunService_cloudRunServiceProbesExample.log)]
`TestAccCloudRunService_probes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/recording/TestAccCloudRunService_probes.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeInstance_soleTenantNodeAffinities`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/build-log/recording_build/TestAccComputeInstance_soleTenantNodeAffinities_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/recording/TestAccComputeInstance_soleTenantNodeAffinities.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/7ce954e8-2374-46f8-a15e-3c9b0e13bb54/recording) for each test

2022-10-13 20:05 UTC, melinath requested changes
Looking good; a few questions.

It looks like successThreshold is currently omitted - I'm guessing because it's not meaningful at the moment?

tcpSocket and grpc are currently omitted - are they supported by Cloud Run?

2022-10-13 20:11 UTC, yanweiguo commented on mmv1/products/cloudrun/api.yaml
> +              min_version: beta
Yeah probe it's a Cloud Run beta feature.

2022-10-13 20:17 UTC, yanweiguo commented
> Looking good; a few questions.
> 
> It looks like successThreshold is currently omitted - I'm guessing because it's not meaningful at the moment?
> 
> tcpSocket and grpc are currently omitted - are they supported by Cloud Run?

Cloud Run shares the same API with [knative](https://knative.dev/docs/) based on k8s. Some fields are defined by knative/k8s but not supported by Cloud Run. `successThreshold`, `tcpSocket` and `grpc` are such fields currently. It might change in the future. (grpc support is coming soon)

2022-10-13 20:18 UTC, yanweiguo commented on mmv1/products/cloudrun/api.yaml
> +                    Defaults to 1 second. Minimum value is 1. Maximum value is 3600.
Ack. I would prefer avoid a new place to keep the allowed values in sync.

2022-10-13 20:23 UTC, yanweiguo commented on mmv1/third_party/terraform/tests/resource_cloud_run_service_test.go.erb
> +          http_get {}
done

2022-10-13 20:37 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6677-old..auto-pr-6677) ( 1 file changed, 65 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6677-old..auto-pr-6677) ( 4 files changed, 471 insertions(+), 24 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6677-old..auto-pr-6677) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-13 21:03 UTC, melinath commented on mmv1/products/cloudrun/api.yaml
> +                    Defaults to 1 second. Minimum value is 1. Maximum value is 3600.
sounds good. that's generally our approach as well.

2022-10-13 21:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2186` 
Passed tests `1946` 
Skipped tests: `239` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2022-10-13 21:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/6bb6fdc4-d7d7-4765-932d-2d5a8c7ee9d5/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/6bb6fdc4-d7d7-4765-932d-2d5a8c7ee9d5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6677/artifacts/6bb6fdc4-d7d7-4765-932d-2d5a8c7ee9d5/recording) for each test

2022-10-13 22:31 UTC, melinath commented
I'm running a manual set of tests out of an abundance of caution, but it's probably fine. https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloudBeta_ProviderGoogleCloudBetaMmUpstream/345139

2022-10-14 22:55 UTC, melinath approved these changes

2022-10-14 22:55 UTC, merged