feat(transfer): add `logging_config` to `google_storage_transfer_job`
GoogleCloudPlatform/magic-modules pull request #6703
Opened 2022-10-17 15:08 UTC by AntoineDao

This PR adds the `logging_config` field to the `google_storage_transfer_job` resources. I'm not sure I could find an issue for this here but I did raise one in https://github.com/hashicorp/terraform-provider-google/issues/12802 and an associate PR (which should probably be closed) here: https://github.com/hashicorp/terraform-provider-google/pull/12803

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
transfer: added `logging_config` to `google_storage_transfer_job`
```

2022-10-17 15:09 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-10-17 15:17 UTC, AntoineDao commented
Hope you don't mind reviewing the code while I sort out CLA on my end 😄

2022-10-17 15:22 UTC, modular-magician commented
Hi!  I'm the modular magician.  Your PR generated some diffs in downstreams - here they are.
# Diff report:


Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 121 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 121 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6703-old..auto-pr-6703) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-17 15:26 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2191` 
Passed tests `10` 
Skipped tests: `239` 
Failed tests: `1942` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataSourceCloudIdentityGroupMemberships_basic|TestAccDataSourceCloudIdentityGroups_basic|TestAccDataSourceComputeLbIpRanges_basic|TestAccDataSourceGoogleActiveFolder_default|TestAccDataSourceGoogleActiveFolder_space|TestAccDataSourceGoogleActiveFolder_dash|TestAccDataSourceGoogleBillingAccount_byFullName|TestAccDataSourceGoogleBillingAccount_byShortName|TestAccDataSourceGoogleBillingAccount_byFullNameClosed|TestAccDataSourceGoogleBillingAccount_byDisplayName|TestAccDataSourceComputeInstanceSerialPort_basic|TestAccDataSourceGoogleFolderOrganizationPolicy_basic|TestAccDataSourceGoogleFolder_byFullName|TestAccDataSourceGoogleFolder_byShortName|TestAccDataSourceGoogleFolder_lookupOrganization|TestAccDataSourceGoogleFolder_byFullNameNotFound|TestAccDataSourceIAMRole|TestAccDataSourceGoogleKmsCryptoKey_basic|TestAccDataSourceGoogleKmsCryptoKeyVersion_basic|TestAccDataSourceGoogleKmsKeyRing_basic|TestAccDataSourceGoogleMonitoringUptimeCheckIps_basic|TestAccDataSourceGoogleNetblockIpRanges_basic|TestAccDataSourceGoogleOrganization_byFullName|TestAccDataSourceGoogleOrganization_byShortName|TestAccDataSourceGoogleOrganization_byDomain|TestAccDataSourceGoogleProjectOrganizationPolicy_basic|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayName|TestAccDataSourceGoogleMonitoringNotificationChannel_byTypeAndLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_UserLabel|TestAccDataSourceGoogleMonitoringNotificationChannel_byDisplayNameAndType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNoDisplayNameOrType|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotFound|TestAccDataSourceGoogleMonitoringNotificationChannel_ErrorNotUnique|TestAccDataSourceMonitoringService_AppEngine|TestAccDataSourceStorageBucketObjectContent_Basic|TestAccDataSourceGoogleTagsTagKey_default|TestAccDataSourceGoogleTagsTagKey_dot|TestAccDataSourceGoogleTagsTagValue_default|TestAccDataSourceGoogleTagsTagValue_dot|TestAccAccessApprovalSettings|TestAccAccessContextManager|TestAccBigqueryDataTransferConfig|TestAccComputeAddress_internal|TestAccComputeBackendService_withBackendAndMaxUtilization|TestAccComputeBackendService_withBackendAndIAP|TestAccComputeInstanceFromTemplate_overrideMetadataDotStartupScript|TestAccComputeInstance_networkTier|TestAccComputeRegionAutoscaler_update|TestAccComputeRegionBackendService_withBackendAndIAP|TestAccComputeRoute_hopInstance|TestAccComputeSharedVpc_basic|TestAccComputeTargetSslProxy_update|TestAccDNSManagedZone_forceDestroy|TestAccOrganizationPolicy|TestAccProjectOrganizationPolicy|TestAccKmsKeyRing_basic|TestAccMonitoringAlertPolicy|TestAccNotebooksInstance_update|TestAccNotebooksRuntime_update|TestAccTags|TestAccComputeResourceUsageExportBucket|TestAccRecaptchaEnterpriseKey_WebKey|TestAccKmsCryptoKey_importOnly|TestAccSpannerInstanceIamMember|TestAccCloudRunServiceIamMemberGenerated|TestAccCloudTasksQueueIamMemberGenerated|TestAccSqlDatabase_basic|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccMonitoringUptimeCheckConfig_update|TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccSqlDatabaseInstance_sqlMysqlInstancePvpExample|TestAccRecaptchaEnterpriseKey_WebScoreKey|TestAccCloudRunServiceIamBindingGenerated|TestAccBigQueryTableIamPolicyGenerated_withCondition|TestAccLoggingProjectSink_described|TestAccRecaptchaEnterpriseKey_MinimalKey|TestAccCloudTasksQueueIamBindingGenerated|TestAccSqlDatabaseInstance_encryptionKey_replicaInDifferentRegion|TestAccCloudRunServiceIamPolicyGenerated|TestAccRedisInstance_redisInstanceFullExample|TestAccSqlDatabaseInstance_encryptionKey|TestAccRedisInstance_redisInstanceBasicExample|TestAccFolder_rename|TestAccSpannerDatabase_versionRetentionPeriod|TestAccBinaryAuthorizationAttestorIamMemberGenerated|TestAccDataSourceGameServicesGameServerDeploymentRollout_basic|TestAccSecurityScannerScanConfig_scanConfigUpdate|TestAccBinaryAuthorizationAttestorIamPolicyGenerated|TestAccSpannerDatabase_postgres|TestAccHealthcareHl7V2Store_healthcareHl7V2StoreUnschematizedExample|TestAccSpannerInstanceIamBinding|TestAccRedisInstance_redisInstanceFullWithPersistenceConfigExample|TestAccBinaryAuthorizationAttestorIamBindingGenerated|TestAccHealthcareHl7V2Store_healthcareHl7V2StoreParserConfigExample|TestAccHealthcareFhirStore_healthcareFhirStoreBasicExample|TestAccHealthcareFhirStoreIamPolicy|TestAccHealthcareFhirStore_basic|TestAccHealthcareDicomStoreIamMember|TestAccHealthcareFhirStore_healthcareFhirStoreStreamingConfigExample|TestAccHealthcareFhirStoreIamMember|TestAccHealthcareDicomStoreIamBinding|TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigExample|TestAccHealthcareFhirStoreIamBinding|TestAccHealthcareDataset_healthcareDatasetBasicExample|TestAccHealthcareDatasetIamBinding|TestAccServiceAccountKey_fromEmail|TestAccServiceAccount_basic|TestAccHealthcareDicomStore_healthcareDicomStoreBqStreamExample|TestAccHealthcareDicomStore_basic|TestAccHealthcareConsentStore_healthcareConsentStoreBasicExample|TestAccServiceAccountIamBinding_federatedIdentity|TestAccHealthcareDicomStoreIamPolicy|TestAccHealthcareDicomStore_healthcareDicomStoreBasicExample|TestAccServiceUsageConsumerQuotaOverride_consumerQuotaOverrideCustomIncorrectLimitFormat|TestAccHealthcareDataset_basic|TestAccHealthcareHl7V2Store_healthcareHl7V2StoreBasicExample|TestAccServiceAccount_Disabled|TestAccHealthcareDatasetIamPolicy|TestAccServiceAccountIamPolicy_federatedIdentity|TestAccHealthcareConsentStore_healthcareConsentStoreFullExample|TestAccHealthcareConsentStore_healthcareConsentStoreIamExample|TestAccServiceAccountKey_fromCertificate|TestAccHealthcareDatasetIamMember|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccServiceAccountKey_basic|TestAccServiceAccountIamMember_federatedIdentity|TestAccFilestoreInstance_reservedIpRange_update|TestAccServiceAccountIamPolicy_withCondition|TestAccServiceAccountIamMember|TestAccServiceAccountIamPolicy|TestAccServiceAccountIamMember_withCondition|TestAccDNSManagedZone_dnsManagedZonePrivateExample|TestAccFilestoreInstance_filestoreInstanceFullExample|TestAccEssentialContactsContact_update|TestAccServiceAccountIamBinding_withCondition|TestAccEssentialContactsContact_essentialContactExample|TestAccFilestoreInstance_update|TestAccFilestoreInstance_filestoreInstanceBasicExample|TestAccDNSManagedZone_dnsRecordSetBasicExample|TestAccDialogflowCXVersion_update|TestAccEventarcTrigger_BasicHandWritten|TestAccDNSManagedZone_dnsManagedZoneQuickstartExample|TestAccDocumentAIProcessorDefaultVersion_documentaiDefaultVersionExample|TestAccDNSResponsePolicyRule_update|TestAccDNSResponsePolicyRuleBehavior_update|TestAccDocumentAIProcessor_documentaiProcessorExample|TestAccDocumentAIProcessor_documentaiProcessorEuExample|TestAccDNSResponsePolicyRule_dnsResponsePolicyRuleBasicExample|TestAccDNSResponsePolicy_update|TestAccDialogflowCXIntent_update|TestAccEndpointsService_grpc|TestAccDNSRecordSet_interpolated|TestAccDialogflowCXWebhook_update|TestAccServiceAccountIamBinding|TestAccDNSResponsePolicy_dnsResponsePolicyBasicExample|TestAccDialogflowCXPage_update|TestAccDNSRecordSet_changeRouting|TestAccDialogflowCXEnvironment_update|TestAccDialogflowCXFlow_update|TestAccDNSRecordSet_routingPolicy|TestAccDNSRecordSet_uppercaseMX|TestAccDialogflowCXEntityType_update|TestAccDNSRecordSet_secondaryNS|TestAccDialogflowIntent_dialogflowIntentFullExample|TestAccDialogflowCXAgent_update|TestAccDialogflowIntent_basic|TestAccDialogflowFulfillment_update|TestAccDNSRecordSet_Update|TestAccDialogflowIntent_update|TestAccDNSRecordSet_changeType|TestAccDNSPolicy_update|TestAccDNSRecordSet_nestedNS|TestAccDNSRecordSet_quotedTXT|TestAccDialogflowCXWebhook_dialogflowcxWebhookFullExample|TestAccDNSRecordSet_basic|TestAccDialogflo [...]

2022-10-20 15:17 UTC, AntoineDao commented
Hi @shuyama1, I could do with a bit of help understanding what is broken with my changes as I don't have access to the CloudBuild logs... 

I tried following the instructions to run tests locally by generating the terraform provider with the following command:
> ./scripts/make-in-container.sh terraform VERSION=ga OUTPUT_PATH="$GOPATH/src/github.com/hashicorp/terraform-provider-google" however so many of the tests have been marked as failing that I'm not sure which one to start with 😓

2022-10-20 16:38 UTC, shuyama1 requested changes
I think the format of `ConflictsWith` is a bit off. Modifying it should get the test run. I'll start reviewing the rest of the code after I see the test results.

2022-10-20 16:38 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +							ConflictsWith: []string{"logging_config.log_actions,logging_config.log_action_states"},
```suggestion
							ConflictsWith: []string{"logging_config.0.log_actions", "logging_config.0.log_action_states"},
```

2022-10-20 16:38 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +							ConflictsWith: []string{"logging_config.enable_on_prem_gcs_transfer_logs"},
```suggestion
							ConflictsWith: []string{"logging_config.0.enable_on_prem_gcs_transfer_logs"},
```

2022-10-20 16:38 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +							ConflictsWith: []string{"logging_config.enable_on_prem_gcs_transfer_logs"},
```suggestion
							ConflictsWith: []string{"logging_config.0.enable_on_prem_gcs_transfer_logs"},
```

2022-10-21 10:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 121 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 121 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6703-old..auto-pr-6703) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-21 11:24 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6703/artifacts/b4ffda31-6d72-4601-af2d-e988f092ae30/build-log/replaying_test.log)

2022-10-21 15:33 UTC, AntoineDao commented
Good catch on the `ConflictsWith` bug! Looks like the tests are all passing, except for the VRC (not sure what it is 😅 ) and the CLA one which I'm still chasing with my employer. Overall are there any changes you think we should include in this PR?

2022-10-21 17:46 UTC, shuyama1 commented
VCR test is the one we run all the acceptance tests against your PR change, and it looks like the provider crashed while running the tests due to the error:
```
panic: interface conversion: interface {} is []interface {}, not []string

goroutine 1455835 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta.expandTransferJobLoggingConfig({0xc0060e0190?, 0x3520c45?, 0x3d85040?})
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/resource_storage_transfer_job.go:1215 +0x234
github.com/hashicorp/terraform-provider-google-beta/google-beta.resourceStorageTransferJobCreate(0x0?, {0x34e3c20?, 0xc003034400})
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/resource_storage_transfer_job.go:577 +0x2ed
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x3d7ecd0?, {0x3d7ecd0?, 0xc0145f9680?}, 0xd?, {0x34e3c20?, 0xc003034400?})
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc01d561c00, {0x3d7ecd0, 0xc0145f9680}, 0xc00acaca90, 0xc0034bd980, {0x34e3c20, 0xc003034400})
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0121ca000, {0x3d7ecd0?, 0xc0145f9620?}, 0xc021bdc910)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc008d841e0, {0x3d7ecd0?, 0xc0145f9080?}, 0xc002aa9f80)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x346dec0?, 0xc008d841e0}, {0x3d7ecd0, 0xc0145f9080}, 0xc002aa9f10, 0x0)
	/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc005a9c1e0, {0x3d85100, 0xc01c814b60}, 0xc0179e4d80, 0xc01f493a10, 0x538d580, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb0b
google.golang.org/grpc.(*Server).handleStream(0xc005a9c1e0, {0x3d85100, 0xc01c814b60}, 0xc0179e4d80, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta	1700.465s
FAIL
```

2022-10-21 21:06 UTC, AntoineDao commented
Great thanks for expediting the logs my way. I'll aim to fix it over the next few days and ping you once it's ready for review 😄

2022-10-28 14:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 133 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 133 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6703-old..auto-pr-6703) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-28 15:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2210` 
Passed tests `1965` 
Skipped tests: `239` 
Failed tests: `6` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccStorageTransferJob_notificationConfig|TestAccStorageTransferJob_transferOptions|TestAccStorageTransferJob_posixSink|TestAccStorageTransferJob_posixSource|TestAccStorageTransferJob_basic </blockquote></details>

2022-10-30 21:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 137 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 137 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6703-old..auto-pr-6703) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-30 22:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2210` 
Passed tests `1970` 
Skipped tests: `239` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccStorageTransferJob_posixSink </blockquote></details>

2022-10-30 22:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccStorageTransferJob_posixSink`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6703/artifacts/93f68ba3-aca4-4b94-9af9-5a243c0c5f76/recording/TestAccStorageTransferJob_posixSink.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6703/artifacts/93f68ba3-aca4-4b94-9af9-5a243c0c5f76/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6703/artifacts/93f68ba3-aca4-4b94-9af9-5a243c0c5f76/recording) for each test

2022-10-31 08:20 UTC, AntoineDao commented
Hi @shuyama1, I think this if *finally* ready for review 😄

2022-10-31 19:01 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_storage_transfer_job.go
> +	}
This looks good, but for simplicity, we can just use `convertStringArr`, such as 
```suggestion
	var apiData = &storagetransfer.LoggingConfig{
		LogActions:                  convertStringArr(loggingConfig["log_actions"].([]interface{})),
		LogActionStates:             convertStringArr(loggingConfig["log_action_states"].([]interface{})),
		EnableOnpremGcsTransferLogs: loggingConfig["enable_on_prem_gcs_transfer_logs"].(bool),
	}
```

2022-11-01 23:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 124 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6703-old..auto-pr-6703) ( 3 files changed, 124 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6703-old..auto-pr-6703) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-02 00:15 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2210` 
Passed tests `1971` 
Skipped tests: `239` 
Failed tests: `0` 

All tests passed in REPLAYING mode
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6703/artifacts/29bc801b-bcfd-4e37-9822-e8c694481199/build-log/replaying_test.log)

2022-11-03 08:42 UTC, AntoineDao commented
@shuyama1 I think that should be all of your comments addressed 😄

2022-11-07 06:04 UTC, shuyama1 requested changes

2024-06-06 06:52 UTC, michellepolte-optimizely commented
Hey, are there any updates to this feature? The logging configuration whould be important for us.

2024-06-12 09:42 UTC, closed without merging