Add SOA to root-level record deletion exception
GoogleCloudPlatform/magic-modules pull request #6724
Opened 2022-10-19 20:45 UTC by rtokarek-fastly

Added SOA to the google_dns_record_set types that are faux-deleted.

When trying to delete record-sets that are managed by terraform, some types can't actually be deleted by DNS and API restrictions. The code previously only pretended deletes for root-level NS records. This change adds SOA to that behavior so that terraform delete/destroy can function properly when SOA is explicitly managed. 

(It doesn't make sense to delete the Start Of Authority (SOA) or root-level NS records by themselves as they're fundamental to the zone construct – their value can be changed, but they must exist for the zone itself to exist.)

This problem would only manifest when managing SOA as a google_dns_record_set resource in terraform with custom values. If left unspecified/implied (default) as part of the zone resource, the zone resource already correctly bypasses deletion of the SOA record on deletion.

See issue https://github.com/hashicorp/terraform-provider-google/issues/12827

This PR is for Terraform, and I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests. **See below**
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests). 
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know). **Tests not run successfully. I'm not sure if there is a better branch to choose from that would have succeeded. 
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

I did build the terraform-provider-google successfully, but `make test` and `lint` in the resultant provider failed due to `google/resource_compute_subnetwork.go:39:22: undefined: cidr` issues (not any code I touched). `main` (without my change) `make test` fails for me (possibly, my dev environment is not correct). I reached a limit with how much I was willing to pursue tests on my own given the 2 line of code proposed change. 

I have not run acceptance tests as earlier tests failed. I'm willing to give it another go. 
 
**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
dns: Fixed deletion of managed SOA `google_dns_record_set` resources to match the short-circuited delete behavior of root-level NS records. 
```

2022-10-19 20:46 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-10-19 20:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6724-old..auto-pr-6724) ( 1 file changed, 8 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6724-old..auto-pr-6724) ( 1 file changed, 8 insertions(+), 9 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6724-old..auto-pr-6724) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-10-19 21:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2196` 
Passed tests `1952` 
Skipped tests: `239` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccBigQueryDataTable_bigtable </blockquote></details>

2022-10-19 21:38 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording/TestAccBigQueryDataTable_bigtable.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/6da8ac3e-5901-4587-9021-ead54240f478/recording) for each test

2022-11-10 22:11 UTC, melinath requested changes
Confirmed via the product docs that this behavior is the same for NS and SOA records: https://cloud.google.com/dns/docs/records#remove_a_record

Could you please add a test for SOA behavior that would've caught this? Probably similar to TestAccDNSRecordSet_secondaryNS

2022-11-10 22:11 UTC, melinath commented on mmv1/third_party/terraform/resources/resource_dns_record_set.go
> +			log.Printf("[DEBUG] root-level %s records can't be deleted due to API restrictions, so they're being left in place. See https://www.terraform.io/docs/providers/google/r/dns_record_set.html for mor
It looks like the docs URL is out of date.

```suggestion
			log.Printf("[DEBUG] root-level %s records can't be deleted due to API restrictions, so they're being left in place. See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/dns_record_set for more information.", d.Get("type").(string))
```

The relevant documentation probably also needs to be updated.

2022-11-10 22:42 UTC, melinath requested changes
re-marking as changes requested since there's still more work to do from the previous review.

2022-11-10 22:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6724-old..auto-pr-6724) ( 1 file changed, 8 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6724-old..auto-pr-6724) ( 1 file changed, 8 insertions(+), 9 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6724-old..auto-pr-6724) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-10 23:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2240` 
Passed tests `1999` 
Skipped tests: `241` 
Failed tests: `0` 

All tests passed in REPLAYING mode
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6724/artifacts/4ee52465-16e4-4728-b692-a33a5e604787/build-log/replaying_test.log)

2024-04-29 15:41 UTC, niklas-dah-gcx commented
Hi @melinath, since this PR is stale:
Would a PR which fixes this issue be welcome if the corresponding tests and docs are added/changed?

2024-04-29 16:19 UTC, melinath commented
yep!

2024-04-29 16:19 UTC, melinath commented
assuming this is still an issue.

2024-04-29 17:06 UTC, mario-steinhoff-gcx commented
> assuming this is still an issue.

@melinath yeah, we just ran into it :D

2024-04-30 14:05 UTC, NiklasDah commented
This has been merged in #10559, thus this PR can be closed, right?

Thanks for the smooth and straight forward process @SarahFrench!

2024-04-30 16:05 UTC, melinath commented
seems like it!

2024-04-30 16:05 UTC, closed without merging