Add support for Beyondcorp AppConnector resource
GoogleCloudPlatform/magic-modules pull request #6801
Opened 2022-11-09 01:05 UTC by palramanathan

Add terraform support for BeyondCorp AppConnector resources (https://cloud.google.com/beyondcorp/docs/reference/rest/v1/projects.locations.appConnectors). Adding API and Terraforms yamls and couple of examples.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_beyondcorp_app_connector`
```

2022-11-09 01:06 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-11-09 01:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6801-old..auto-pr-6801) ( 10 files changed, 1728 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6801-old..auto-pr-6801) ( 10 files changed, 1728 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6801-old..auto-pr-6801) ( 7 files changed, 494 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6801-old..auto-pr-6801) ( 8 files changed, 234 insertions(+))

2022-11-09 02:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2237` 
Passed tests `1991` 
Skipped tests: `241` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample|TestAccBeyondcorpAppConnectorIamPolicyGenerated|TestAccBeyondcorpAppConnectorIamMemberGenerated|TestAccBeyondcorpAppConnectorIamBindingGenerated </blockquote></details>

2022-11-09 02:18 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_build/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_build/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample.log)]
`TestAccBeyondcorpAppConnectorIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_build/TestAccBeyondcorpAppConnectorIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording/TestAccBeyondcorpAppConnectorIamPolicyGenerated.log)]
`TestAccBeyondcorpAppConnectorIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_build/TestAccBeyondcorpAppConnectorIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording/TestAccBeyondcorpAppConnectorIamMemberGenerated.log)]
`TestAccBeyondcorpAppConnectorIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_build/TestAccBeyondcorpAppConnectorIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording/TestAccBeyondcorpAppConnectorIamBindingGenerated.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/1c730fac-7d7f-4e2c-8a8c-f1c2a01a41de/recording) for each test

2022-11-09 03:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6801-old..auto-pr-6801) ( 7 files changed, 1093 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6801-old..auto-pr-6801) ( 7 files changed, 1093 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6801-old..auto-pr-6801) ( 4 files changed, 145 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6801-old..auto-pr-6801) ( 8 files changed, 234 insertions(+))

2022-11-09 04:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2234` 
Passed tests `1989` 
Skipped tests: `241` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccComputeForwardingRule_update|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample </blockquote></details>

2022-11-09 04:46 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/recording/TestAccComputeForwardingRule_update.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/cabaad62-10c3-4eba-8d34-09425ebec5e3/recording) for each test

2022-11-10 03:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6801-old..auto-pr-6801) ( 11 files changed, 2078 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6801-old..auto-pr-6801) ( 11 files changed, 2078 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6801-old..auto-pr-6801) ( 5 files changed, 255 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6801-old..auto-pr-6801) ( 16 files changed, 453 insertions(+))

2022-11-10 04:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2239` 
Passed tests `1996` 
Skipped tests: `241` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample|TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample </blockquote></details>

2022-11-10 04:16 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/f10d8c03-bdbc-4ecd-85f5-e0fe0b24d436/recording/TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample.log)]
`TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/f10d8c03-bdbc-4ecd-85f5-e0fe0b24d436/recording/TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/f10d8c03-bdbc-4ecd-85f5-e0fe0b24d436/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/f10d8c03-bdbc-4ecd-85f5-e0fe0b24d436/recording) for each test

2022-11-10 17:34 UTC, slevenick requested changes
Overall looks reasonable, just some notes on cleaning up the api.yaml file

Additionally, you've included info on using PATCH and an update mask to update the resources, can you add a handwritten update test to make sure this works correctly?

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +    delete_url: projects/{{project}}/locations/{{region}}/appConnectors/{{name}}
delete & update URL should be redundant, they can generally be derived from self_link & base_url as long as they are standard (which these are)

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +        input: true
If you mark this url_param_only this won't be sent in the request body or read from the response body, removing the need for the custom expand/flatteners. Usually this is what we want as the `name` field is almost always ignored in request bodies, and can't change so it doesn't matter if we read it back

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +            name: 'serviceAccount'
Should this be required as well?

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +                name: 'email'
Same as above, required?

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +        name: 'createTime'
Are these output only fields useful? We try to omit them when we don't expect any user to use them, like create & update time

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +    # iam_policy: !ruby/object:Api::Resource::IamPolicy
You can delete these

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +    min_version: ga
Unneeded, GA is the "highest" version

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +        'Official Documentation': 'https://cloud.google.com/beyondcorp-enterprise/docs/enable-app-connector'
Should this link to an app gateways doc?

2022-11-10 17:34 UTC, slevenick commented on mmv1/products/beyondcorp/api.yaml
> +        required: true
Same as the note on name above

2022-11-10 19:22 UTC, palramanathan reviewed
Thanks for the review! I will address the comments and update the PR.

2022-11-10 21:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6801-old..auto-pr-6801) ( 12 files changed, 1926 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6801-old..auto-pr-6801) ( 12 files changed, 1926 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6801-old..auto-pr-6801) ( 5 files changed, 235 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-6801-old..auto-pr-6801) ( 16 files changed, 453 insertions(+))

2022-11-10 22:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2240` 
Passed tests `1994` 
Skipped tests: `241` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample|TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorUpdateExample|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample|TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample </blockquote></details>

2022-11-10 22:15 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording/TestAccBeyondcorpAppGateway_beyondcorpAppGatewayFullExample.log)]
`TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording/TestAccBeyondcorpAppGateway_beyondcorpAppGatewayBasicExample.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorUpdateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorUpdateExample.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorBasicExample.log)]
`TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording/TestAccBeyondcorpAppConnector_beyondcorpAppConnectorFullExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6801/artifacts/e80f3262-357e-4b8c-a7d1-6fbbd6e524ac/recording) for each test

2022-11-10 22:23 UTC, slevenick approved these changes
Thanks looks good!

2022-11-10 22:23 UTC, merged