Add max_run_duration to instance and instance template on Beta
GoogleCloudPlatform/magic-modules pull request #6812
Opened 2022-11-10 22:57 UTC by andrewyz

Add max_run_duration support that will set a deadline for running VM (Beta).

https://pkg.go.dev/google.golang.org/api@v0.103.0/compute/v0.beta#Duration

***Testing disclaimer***: I verified the 

provider_test.go:307: Failed state verification, resource with ID projects/debian-cloud/global/images/debian-11-bullseye-v20221102 not found
All the tests are passing with ImportStateVerify set to false, but I wasn't able to get the state verification to work.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `max_run_duration` field to `google_compute_instance` resource (beta)
```

```release-note:enhancement
compute: added `max_run_duration` field to `google_compute_instance_template ` resource (beta)
```

2022-11-10 23:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 7 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 164 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-10 23:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2240` 
Passed tests `1996` 
Skipped tests: `241` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccComputeInstance_spotVM|TestAccComputeInstance_spotVM_update|TestAccComputeInstanceTemplate_spot </blockquote></details>

2022-11-10 23:58 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeInstance_spotVM`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/eaa7b83e-e331-4f6d-a366-fb2b07e5a02f/recording/TestAccComputeInstance_spotVM.log)]
`TestAccComputeInstance_spotVM_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/eaa7b83e-e331-4f6d-a366-fb2b07e5a02f/recording/TestAccComputeInstance_spotVM_update.log)]
`TestAccComputeInstanceTemplate_spot`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/eaa7b83e-e331-4f6d-a366-fb2b07e5a02f/recording/TestAccComputeInstanceTemplate_spot.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/eaa7b83e-e331-4f6d-a366-fb2b07e5a02f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/eaa7b83e-e331-4f6d-a366-fb2b07e5a02f/recording) for each test

2022-11-18 17:47 UTC, shuyama1 requested changes

2022-11-18 17:47 UTC, shuyama1 commented on mmv1/third_party/terraform/tests/resource_compute_instance_test.go.erb
> +					testAccCheckComputeInstanceMaxRunDuration(&instance, expectedMaxRunDuration),
Why do we want to check this explicitly? I think the test should already check this if the API returs the correct values?

2022-11-21 22:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 7 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 164 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-21 22:51 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2278` 
Passed tests `2033` 
Skipped tests: `244` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-11-21 22:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/c70e0933-ae51-4c1c-b092-8a9c2ae95ec8/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/c70e0933-ae51-4c1c-b092-8a9c2ae95ec8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/c70e0933-ae51-4c1c-b092-8a9c2ae95ec8/recording) for each test

2022-11-28 21:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 7 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 164 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-11-28 22:26 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2288` 
Passed tests `2042` 
Skipped tests: `244` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-11-28 22:27 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/4c42e45e-d87f-4ee9-8b35-aa98fa033080/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/4c42e45e-d87f-4ee9-8b35-aa98fa033080/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/4c42e45e-d87f-4ee9-8b35-aa98fa033080/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/4c42e45e-d87f-4ee9-8b35-aa98fa033080/recording) for each test

2022-12-28 19:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 101 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 353 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-28 20:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2382` 
Passed tests `2126` 
Skipped tests: `248` 
Failed tests: `8` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccComputeInstance_spotVM_maxRunDuration_update|TestAccComputeInstance_spotVM_maxRunDration|TestAccComputeInstance_spotVM|TestAccComputeInstance_spotVM_update|TestAccComputeInstanceTemplate_spot_maxRunDuration|TestAccComputeInstanceTemplate_spot </blockquote></details>

2022-12-28 20:13 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccComputeInstance_spotVM_maxRunDuration_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstance_spotVM_maxRunDuration_update.log)]
`TestAccComputeInstance_spotVM_maxRunDration`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstance_spotVM_maxRunDration.log)]
`TestAccComputeInstance_spotVM`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstance_spotVM.log)]
`TestAccComputeInstance_spotVM_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstance_spotVM_update.log)]
`TestAccComputeInstanceTemplate_spot_maxRunDuration`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstanceTemplate_spot_maxRunDuration.log)]
`TestAccComputeInstanceTemplate_spot`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording/TestAccComputeInstanceTemplate_spot.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b2d67061-989f-4447-b47c-ad126aeb43ff/recording) for each test

2023-01-11 20:59 UTC, andrewyz commented on mmv1/third_party/terraform/utils/compute_instance_helpers.go.erb
> +		scheduling.ForceSendFields = append(scheduling.ForceSendFields, "MaxRunDuration")
IIRC, the scheduling can not expand/flatten automatically, so we have a manual step to do so, and set up the field explicitly. ForceSendFields seems become a standard to adding thing in scheduling

2023-01-11 21:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 101 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 355 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-11 21:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 101 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 359 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-11 22:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2407` 
Passed tests `2152` 
Skipped tests: `251` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccRegionInstanceGroupManager_stateful </blockquote></details>

2023-01-11 22:24 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/build-log/recording_build/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccRegionInstanceGroupManager_stateful`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/build-log/recording_build/TestAccRegionInstanceGroupManager_stateful_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/recording/TestAccRegionInstanceGroupManager_stateful.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/b71b49b6-1cb0-4e86-b77e-14977f8bce28/recording) for each test

2023-01-12 20:47 UTC, shuyama1 commented
/gcbrun

2023-01-12 21:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6812-old..auto-pr-6812) ( 4 files changed, 101 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6812-old..auto-pr-6812) ( 7 files changed, 359 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6812-old..auto-pr-6812) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-12 21:50 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2410` 
Passed tests `2159` 
Skipped tests: `251` 
Failed tests: `0` 

All tests passed in REPLAYING mode
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6812/artifacts/d35479e2-c889-477b-840d-2c5534f6688f/build-log/replaying_test.log)

2023-01-13 18:03 UTC, shuyama1 approved these changes
LGTM! Thank you!

2023-01-13 18:17 UTC, merged