Add two outputs for dlp job trigger: outputting to SCC and DataCatalog
GoogleCloudPlatform/magic-modules pull request #6855
Opened 2022-11-21 19:57 UTC by Wallace99

Add in outputting results of DLP job to SCC and DataCatalog. Also fix description of `saveFindings` block and remove unnecessary restriction on only one output.

Fixes https://github.com/hashicorp/terraform-provider-google/issues/11861

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement New outputs for DLP inspection trigger

```

2022-11-21 19:58 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* enhancement New outputs for DLP inspection trigger

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-11-21 19:58 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-11-28 09:22 UTC, shuyama1 reviewed
@Wallace99 Thanks for making the change! The build failed due to
```
bundler: failed to load command: compiler (compiler)
RuntimeError: Field 'publish_summary_to_cscc' properties are nil!
```
Looks like `publishSummaryToCscc` and `publishFindingsToCloudDataCatalog` are added as nested object without subfields which will cause the build fail. Maybe consider adding some virtual subfields such as boolean field `enable` to make sure nested object are non-empty?

2022-11-28 19:51 UTC, Wallace99 commented
> @Wallace99 Thanks for making the change! The build failed due to
> 
> ```
> bundler: failed to load command: compiler (compiler)
> RuntimeError: Field 'publish_summary_to_cscc' properties are nil!
> ```
> 
> Looks like `publishSummaryToCscc` and `publishFindingsToCloudDataCatalog` are added as nested object without subfields which will cause the build fail. Maybe consider adding some virtual subfields such as boolean field `enable` to make sure nested object are non-empty?

Ah thanks, will update that shortly!

2022-12-10 07:24 UTC, Wallace99 commented
Hi @shuyama1, sorry for the delay. Do you know of elsewhere in the repo I could reference for adding virtual subfields? Would some custom logic also be needed? To configure a DLP inspection job to output to SCC an empty JSON object called `publishSummaryToCscc` is added to the `actions` array, and if it's not there it doesn't send to SCC (likewise for Data Catalog). If we add a virtual field called `enabled` for example, will the empty JSON object still be added if `enabled` is set to false by the user? Perhaps I'm misunderstanding what virtual subfields are?

2022-12-12 03:42 UTC, shuyama1 commented
Hi @Wallace99, it seems that we may be able handle empty block schema by adding `properties: []` to the nested field in the `api.yaml`, for example https://github.com/GoogleCloudPlatform/magic-modules/blame/main/mmv1/products/vertexai/api.yaml#L938. Would you mind trying that first and see if it works?

2022-12-13 05:28 UTC, shuyama1 commented
/gcbrun

2022-12-13 05:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 100 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 100 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 47 insertions(+), 3 deletions(-))

2022-12-13 06:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2340` 
Passed tests `2091` 
Skipped tests: `244` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccDataLossPreventionJobTrigger_dlpJobTriggerUpdateExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBasicExample </blockquote></details>

2022-12-13 06:57 UTC, shuyama1 requested changes

2022-12-13 06:57 UTC, shuyama1 commented on mmv1/templates/terraform/examples/dlp_job_trigger_bigquery_row_limit.tf.erb
> +			publishSummaryToCscc {
```suggestion
			publish_summary_to_cscc {
```
It needs to be snake case in resource configuration

2022-12-13 06:57 UTC, shuyama1 commented on mmv1/templates/terraform/examples/dlp_job_trigger_bigquery_row_limit_percentage.tf.erb
> +			publishFindingsToCloudDataCatalog {
```suggestion
			publish_findings_to_cloud_data_catalog {
```
same here

2022-12-13 20:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 100 insertions(+), 6 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 100 insertions(+), 6 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 47 insertions(+), 3 deletions(-))

2022-12-13 21:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2344` 
Passed tests `2094` 
Skipped tests: `246` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample|TestAccLoggingBucketConfigProject_cmekSettings|TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2022-12-13 21:34 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/build-log/recording_build/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample.log)]
`TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/build-log/recording_build/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/e24fe58a-9844-436d-891c-0f10eb10a720/recording) for each test

2022-12-13 21:48 UTC, shuyama1 requested changes
Looks like only one of the fields in `actions` can be specified. Therefore, I propose we add back `exactly_one_of` and also include the newly added two fields. Plus, we need to use indexed path for `exactly_one_of` (`save_findings` -> `inspect_job.0.actions.0.save_findings`). 

Would you mind testing it locally first to make sure the test passed? It will be faster to see tests result running locally as our CI need to run the PR against the whole test suite.

2022-12-13 22:31 UTC, Wallace99 commented
The docs for the DLP rest api do say only one action can be specified, but I believe they're incorrect as I can create an inspection trigger with multiple actions both through the rest api and through the console. That's why I removed `exactly_one_of` as it's unnecessarily restrictive - there's no reason I can think of why someone shouldn't be able to output their results to SCC as well as to BigQuery for example. I left feedback on the DLP docs page, but I might try and contact them directly to get them to correct the docs or clarify whether it's actually intended to be able to only output to one place.

But yes, sorry I will locally test first! I've been having issues getting the tests to run locally so hoped this would be a trivial change that passed first try 😄

2022-12-15 19:29 UTC, shuyama1 commented
@Wallace99 Thanks for the explanation! Please let me know when you hear back from the API team, as based on the current error for the failed test, it seems that it still does not allow multiple actions to be set at the same time:
```
    provider_test.go:315: Step 1/2 error: Error running apply: exit status 1
        
        Error: Error creating JobTrigger: googleapi: Error 400: Invalid value at 'job_trigger.inspect_job.actions[0]' (oneof), oneof field 'action' is already set. Cannot set 'saveFindings'
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.BadRequest",
            "fieldViolations": [
              {
                "description": "Invalid value at 'job_trigger.inspect_job.actions[0]' (oneof), oneof field 'action' is already set. Cannot set 'saveFindings'",
                "field": "job_trigger.inspect_job.actions[0]"
              }
            ]
          }
        ]
        
          with google_data_loss_prevention_job_trigger.bigquery_row_limit,
          on terraform_plugin_test.tf line 3, in resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit":
           3: resource "google_data_loss_prevention_job_trigger" "bigquery_row_limit" {
        
--- FAIL: TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample (2.12s)
```

2022-12-20 20:38 UTC, Wallace99 commented
Hi @shuyama1, my mistake - I meant to say the DLP Python client rather than the REST api. Just now I verified that I can create an inspection job trigger with two actions using the Python client which from a quick look appears to be calling the RPCs [here](https://cloud.google.com/dlp/docs/reference/rpc/google.privacy.dlp.v2). I'm confused as to why then the test would be failing with the message above. I opened a support case seeking clarification, but they said that it's intentional that the REST api (and RPCs) only allow one action and that there's an internal request for this to be changed, but there's no timeline for when it will be done.

I'm happy in the meantime to put back in `exactly_one_of` for actions to allow this PR and revisit it at a future point.

2022-12-27 22:41 UTC, shuyama1 commented
@Wallace99 Thanks for the explanation. I'd propose to bring back `exactly_one_of` since the REST api only allows one action at this moment. We can drop the restriction when the API behavior is changed in the future. Thanks!

2023-01-15 19:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6855-old..auto-pr-6855) ( 2 files changed, 94 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6855-old..auto-pr-6855) ( 2 files changed, 94 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 47 insertions(+), 3 deletions(-))

2023-01-15 20:44 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2419` 
Passed tests `2163` 
Skipped tests: `252` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccDataLossPreventionJobTrigger_dlpJobTriggerUpdateExample2|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample </blockquote></details>

2023-01-15 20:45 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccDataLossPreventionJobTrigger_dlpJobTriggerUpdateExample2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerUpdateExample2.log)]
`TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitPercentageExample.log)]
`TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerBigqueryRowLimitExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/acb97fa6-7ada-44ed-86db-03e141c8fa2e/recording) for each test

2023-01-17 20:28 UTC, shuyama1 approved these changes
LGTM! Only some nit-picks. Thank you for the work!

2023-01-17 20:28 UTC, shuyama1 commented on mmv1/templates/terraform/examples/dlp_job_trigger_data_catalog_output.tf.erb
> +}
nit: spacing is a bit off here - we use spaces instead of tabs for resource configuration for tests

2023-01-17 20:28 UTC, shuyama1 commented on mmv1/templates/terraform/examples/dlp_job_trigger_scc_output.tf.erb
> +}
nit: spacing here

2023-01-19 20:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2425` 
Passed tests `2170` 
Skipped tests: `253` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccRegionInstanceGroupManager_stateful|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample </blockquote></details>

2023-01-19 20:51 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccRegionInstanceGroupManager_stateful`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/build-log/recording_build/TestAccRegionInstanceGroupManager_stateful_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/recording/TestAccRegionInstanceGroupManager_stateful.log)]
`TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/build-log/recording_build/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/80d73a3c-eea4-40e9-8181-77b362d3be8b/recording) for each test

2023-01-19 23:22 UTC, shuyama1 approved these changes
Failing tests are unrelated! Thank you for the work!

2023-01-19 23:30 UTC, shuyama1 requested changes
Whoops, I just realize that we didn't include the newly added examples to the `terraform.yaml` file, so no tests or doc examples is generated. Sorry for missing this earlier! I thought I saw related tests passed at some point but I guess those were only existing ones. Some examples of how to refer test/doc examples in the `terraform.yaml` file at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/dlp/terraform.yaml#L76
Plus, I think we can fairly skip generating these two examples in the web docs by adding `skip_docs: true` in the `terraform.yaml` file. Please let me know if you have any question generating the tests. Thanks!

2023-01-22 20:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 216 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 216 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6855-old..auto-pr-6855) ( 3 files changed, 47 insertions(+), 3 deletions(-))

2023-01-22 21:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2425` 
Passed tests `2169` 
Skipped tests: `253` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataLossPreventionJobTrigger_dlpJobTriggerSccOutputExample|TestAccDataLossPreventionJobTrigger_dlpJobTriggerDataCatalogOutputExample|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample </blockquote></details>

2023-01-22 21:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataLossPreventionJobTrigger_dlpJobTriggerSccOutputExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerSccOutputExample.log)]
`TestAccDataLossPreventionJobTrigger_dlpJobTriggerDataCatalogOutputExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerDataCatalogOutputExample.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/build-log/recording_build/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6855/artifacts/64fc8237-7410-42ba-a2be-031b08878673/recording) for each test

2023-01-24 17:19 UTC, shuyama1 approved these changes
Thank you!

2023-01-24 17:20 UTC, merged