add enterprise_config_resource_name to resource google_cloudbuild_trigger (#9956)
GoogleCloudPlatform/magic-modules pull request #6871
Opened 2022-11-24 11:33 UTC by wilsonfv

fixes https://github.com/hashicorp/terraform-provider-google/issues/9956

Cloud Build offers [integration with Private Github Enterprise](https://cloud.google.com/build/docs/automating-builds/github/connect-host-github-enterprise) 

The steps from initial configuration setup to a build trigger are like 
1. create [host connection](https://cloud.google.com/build/docs/automating-builds/github/connect-host-github-enterprise) with private Github Enterprise 
2. [connect to repository](https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github-enterprise) on private Github Enterprise 
3. [create build trigger](https://cloud.google.com/build/docs/automating-builds/github/build-repos-from-github-enterprise) on repository  

As of now, step 1 and 2 could only done manually as described on this ticket https://github.com/integrations/terraform-provider-github/issues/509

Assuming step 1 and 2 have been completed, existing resource google_cloudbuild_trigger ([terraform-google-provider v4.44.1](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger)) does not support  [GitHubEnterpriseConfig](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.githubEnterpriseConfigs) while current [Cloud Build Trigger Rest API ](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger) does support [enterpriseConfigResourceName](https://cloud.google.com/build/docs/api/reference/rest/v1/projects.locations.triggers#BuildTrigger.GitHubEventsConfig), so this PR is to address the gap between terraform resource and Cloud Build API.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
cloudbuild: added support for `"enterpriseConfigResourceName"` in `google_cloudbuild_trigger`
```

2022-11-24 11:34 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2022-11-24 11:34 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @roaks3, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-11-24 11:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6871-old..auto-pr-6871) ( 2 files changed, 28 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6871-old..auto-pr-6871) ( 2 files changed, 28 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6871-old..auto-pr-6871) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2022-11-24 12:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2281` 
Passed tests `2035` 
Skipped tests: `244` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2022-11-24 12:29 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/45c8bb5b-5038-4639-9d47-53fc26b65366/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/45c8bb5b-5038-4639-9d47-53fc26b65366/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/45c8bb5b-5038-4639-9d47-53fc26b65366/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/45c8bb5b-5038-4639-9d47-53fc26b65366/recording) for each test

2022-11-24 13:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6871-old..auto-pr-6871) ( 2 files changed, 28 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6871-old..auto-pr-6871) ( 2 files changed, 28 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6871-old..auto-pr-6871) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2022-11-24 14:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2281` 
Passed tests `2036` 
Skipped tests: `244` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-11-24 14:19 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/9fe8e52a-224c-4a67-91bc-67c126cc1447/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/9fe8e52a-224c-4a67-91bc-67c126cc1447/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6871/artifacts/9fe8e52a-224c-4a67-91bc-67c126cc1447/recording) for each test

2022-12-01 18:35 UTC, roaks3 requested changes
LGTM, but could you add this field to a test in `mmv1/third_party/terraform/tests/resource_cloudbuild_trigger_test.go`? Specifically, I think we'd like this to be tested with an update scenario, because if the field is immutable, the test would fail and `input: true` would be needed.

2022-12-06 04:08 UTC, wilsonfv commented
> LGTM, but could you add this field to a test in `mmv1/third_party/terraform/tests/resource_cloudbuild_trigger_test.go`? Specifically, I think we'd like this to be tested with an update scenario, because if the field is immutable, the test would fail and `input: true` would be needed.

Hi @roaks3 
I dont think I could write any test against this changes.

Reason being: 

[enterpriseConfigResourceName](https://github.com/GoogleCloudPlatform/magic-modules/pull/6871/files#diff-7e0b566730a093b03df81b8326e0a4a1895f5dacde1c51650a2c760c4581fa2cR288) is a mutable property inside Cloud Build Trigger. i.e. during a terraform provision of  resource google_cloudbuild_trigger, we can update / remove enterprise_config_resource_name. That being said, changing value of enterprise_config_resource_name in google_cloudbuild_trigger will re-point the trigger to another self-hosted github enterprise while removing enterprise_config_resource_name from google_cloudbuild_trigger will re-point the trigger from self-hosted github enterprise to the public github.com.

existing terraform github example [cloudbuild_trigger_github.tf.erb](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/templates/terraform/examples/cloudbuild_trigger_github.tf.erb) does not have any acceptance test (see [terraform.yaml](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/products/cloudbuild/terraform.yaml#L29-L51) and [resource_cloudbuild_trigger_test.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_cloudbuild_trigger_test.go)). I believe it's because Cloud Build Trigger acceptance test with github will require dependency on public github.com or self-hosted github enterprise which are not possible to implement

Let me know your thoughts

2023-02-17 00:35 UTC, roaks3 commented
@wilsonfv I had been waiting on Riley's comment https://github.com/GoogleCloudPlatform/magic-modules/pull/6563#pullrequestreview-1112957755 to see where we landed on testing this, but it looks like we've relaxed that requirement. https://github.com/GoogleCloudPlatform/magic-modules/pull/7236 was merged recently, which is essentially the same change that you had suggested.

Sorry for the delay on this, and that this PR ended up being superseded.

Closing as the underlying issue is now resolved.

2023-02-17 00:35 UTC, closed without merging