[#12620] Allow gke nodepool labels to be updated
GoogleCloudPlatform/magic-modules pull request #6941
Opened 2022-12-11 18:07 UTC by LucaPrete

Allow GKE nodepool labels to be updated without causing nodepools disruption.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:enhancement
container: enhancement allow `labels` update without nodepools disruption for `resource_container_node_pool`
```

2022-12-11 18:08 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-12-11 18:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6941-old..auto-pr-6941) ( 3 files changed, 60 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6941-old..auto-pr-6941) ( 3 files changed, 60 insertions(+), 14 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6941-old..auto-pr-6941) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-11 19:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2339` 
Passed tests `2086` 
Skipped tests: `244` 
Failed tests: `9` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccSqlUser_postgresAbandon|TestAccSqlUser_postgresIAM|TestAccSqlUser_postgres|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withSandboxConfig|TestAccContainerNodePool_withNodeConfig|TestAccComputeForwardingRule_update|TestAccDataSourceSqlDatabaseInstance_basic </blockquote></details>

2022-12-12 23:01 UTC, shuyama1 commented
/gcbrun

2022-12-12 23:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6941-old..auto-pr-6941) ( 3 files changed, 60 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6941-old..auto-pr-6941) ( 3 files changed, 60 insertions(+), 14 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6941-old..auto-pr-6941) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-13 00:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2340` 
Passed tests `2092` 
Skipped tests: `244` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withSandboxConfig|TestAccComputeForwardingRule_update|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-12-13 00:13 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/recording/TestAccComputeForwardingRule_update.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerCluster_withSandboxConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/build-log/recording_build/TestAccContainerCluster_withSandboxConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/recording/TestAccContainerCluster_withSandboxConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/9cfdead1-952b-41f3-9470-5ed874b1891f/recording) for each test

2022-12-14 12:28 UTC, LucaPrete commented
Hi @shuyama1 !

I seems one of the old container cluster tests is failing because labels don't get updated correctly (more precisely, the label we add to the cluster doesn't gets added...)

I think this is because it uses as well the node pool code. I tried to look for methods in the go lib to update labels (as it happens for tags or resource labels), but I haven't found anything.

Any suggestion?

Thanks!

2022-12-14 21:14 UTC, shuyama1 commented
Do we know if cluster labels (node_config.labels? I assume) can be updated? If not, we should add the labels field to `forceNewClusterNodeConfigFields` at https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/resources/resource_container_cluster.go.erb#L93

2022-12-15 10:34 UTC, LucaPrete commented
@shuyama1 makes sense. I don't have visibility (but I can try to contact some SWEs) to say labels can be updated at cluster level....At least I don't see anything obvious in the APIs. As such, for now I'll try to add the field to forceNewClusterNodeConfigFields. Let's see how it goes...fingers crossed!

2022-12-15 10:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6941-old..auto-pr-6941) ( 4 files changed, 61 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6941-old..auto-pr-6941) ( 5 files changed, 62 insertions(+), 15 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6941-old..auto-pr-6941) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-15 11:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6941-old..auto-pr-6941) ( 4 files changed, 61 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6941-old..auto-pr-6941) ( 5 files changed, 62 insertions(+), 15 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6941-old..auto-pr-6941) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-15 11:52 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2348` 
Passed tests `2093` 
Skipped tests: `246` 
Failed tests: `9` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccContainerCluster_withSandboxConfig|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withNatIpsAndDrainNatIps|TestAccComputeRouterNat_removeLogConfig|TestAccComputeRouterNat_update </blockquote></details>

2022-12-15 12:03 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccComputeRouterNat_withNatRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccComputeRouterNat_withNatRules.log)]
`TestAccComputeRouterNat_withPortAllocationMethods`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccComputeRouterNat_withPortAllocationMethods.log)]
`TestAccComputeRouterNat_withNatIpsAndDrainNatIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccComputeRouterNat_withNatIpsAndDrainNatIps.log)]
`TestAccComputeRouterNat_removeLogConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccComputeRouterNat_removeLogConfig.log)]
`TestAccComputeRouterNat_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccComputeRouterNat_update.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerCluster_withSandboxConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/build-log/recording_build/TestAccContainerCluster_withSandboxConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording/TestAccContainerCluster_withSandboxConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/0d7d94bd-d28c-44d9-bd9b-2a3be922ae2c/recording) for each test

2022-12-15 14:32 UTC, LucaPrete commented
@shuyama1 it seems adding `node_config.0.labels` (which is what the error is complaining about) to `forceNewClusterNodeConfigFields` doesn't help..still getting the same error. In the meantime, verifying with SWEs about the chance to update all the cluster labels

2022-12-16 09:23 UTC, LucaPrete commented
@shuyama1 FYI I confirmed with SWEs that an API to update labels at cluster level is not currently available / in plan.

2022-12-16 18:36 UTC, shuyama1 requested changes
Thanks for confirming that updating labels at cluster level is not currently available. Then I think adding `labels` to `forceNewClusterNodeConfigFields` in `resource_container_cluster` should do the trick.

2022-12-16 18:36 UTC, shuyama1 commented on mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
> +		"node_config.0.labels",
```suggestion
		"labels",
```
We don't need the full path here, since it's used inside the node_config schema

2022-12-18 20:16 UTC, LucaPrete commented
I think I tried this and it didn't work either, but let's see...

2022-12-18 20:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-6941-old..auto-pr-6941) ( 4 files changed, 61 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-6941-old..auto-pr-6941) ( 5 files changed, 62 insertions(+), 15 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-6941-old..auto-pr-6941) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-18 21:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2354` 
Passed tests `2102` 
Skipped tests: `247` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccComputeForwardingRule_update|TestAccBillingSubaccount_basic|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-12-18 21:15 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording/TestAccComputeForwardingRule_update.log)]
`TestAccBillingSubaccount_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording/TestAccBillingSubaccount_basic.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-6941/artifacts/43372989-40c4-4f0c-b731-61a59d999152/recording) for each test

2022-12-19 14:57 UTC, shuyama1 approved these changes

2022-12-19 14:59 UTC, merged

2022-12-22 13:51 UTC, olegeech-me commented
awesome! thank you guys, I was waiting a lot for this to be implemented!