support SPOT for secondary worker.
GoogleCloudPlatform/magic-modules pull request #7000
Opened 2022-12-19 22:54 UTC by duqDarren

Support 'SPOT' under preemptibility for secondary worker.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dataproc: added support for `SPOT` option for `preemptibility` in `google_dataproc_cluster`
```

2022-12-19 22:55 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @trodge, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-12-19 22:59 UTC, melinath commented
we will not be able to merge this as-is because it adds the field to the GA provider.

2022-12-19 23:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7000-old..auto-pr-7000) ( 1 file changed, 1 insertion(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7000-old..auto-pr-7000) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-20 16:24 UTC, melinath commented
yep

2022-12-21 18:27 UTC, duqDarren commented
@trodge @melinath 
https://github.com/GoogleCloudPlatform/magic-modules/pull/7002 deprecated the v1beta2. 
I also removed the version guard from this PR.

2022-12-21 18:31 UTC, melinath commented
Great! @trodge feel free to assign me as a secondary reviewer when you're done.

2022-12-21 18:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7000-old..auto-pr-7000) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-21 19:25 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2368` 
Passed tests `2118` 
Skipped tests: `247` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccDataprocCluster_spotSecondary|TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-12-21 19:38 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

Tests failed during RECORDING mode:
 `TestAccDataprocCluster_spotSecondary`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/build-log/recording_build/TestAccDataprocCluster_spotSecondary_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/recording/TestAccDataprocCluster_spotSecondary.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/bff5143a-3687-4faf-a5f3-fd5995ef13b1/recording) for each test

2022-12-21 19:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7000-old..auto-pr-7000) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-21 20:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2371` 
Passed tests `2121` 
Skipped tests: `247` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccDataprocCluster_spotSecondary|TestAccContainerCluster_withInvalidGatewayApiConfigChannel </blockquote></details>

2022-12-21 20:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/ca8ba89b-48fb-4879-a885-2a2a63069e55/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccDataprocCluster_spotSecondary`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/ca8ba89b-48fb-4879-a885-2a2a63069e55/recording/TestAccDataprocCluster_spotSecondary.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/ca8ba89b-48fb-4879-a885-2a2a63069e55/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/ca8ba89b-48fb-4879-a885-2a2a63069e55/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/ca8ba89b-48fb-4879-a885-2a2a63069e55/recording) for each test

2022-12-22 18:52 UTC, trodge requested changes

2022-12-22 18:56 UTC, duqDarren commented on mmv1/third_party/terraform/resources/resource_dataproc_cluster.go.erb
> +										ValidateFunc: validation.StringInSlice([]string{"PREEMPTIBILITY_UNSPECIFIED", "NON_PREEMPTIBLE", "PREEMPTIBLE", "SPOT"}, false),
Oh, right, just removed it.

2022-12-22 19:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7000-old..auto-pr-7000) ( 3 files changed, 58 insertions(+), 1 deletion(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7000-old..auto-pr-7000) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-22 19:35 UTC, trodge reviewed
LGTM, added @melinath as a secondary reviewer.

2022-12-22 20:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2374` 
Passed tests `2123` 
Skipped tests: `248` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withInvalidGatewayApiConfigChannel </blockquote></details>

2022-12-22 20:04 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/629e8144-0763-47ff-b622-4ff4f970b97d/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/629e8144-0763-47ff-b622-4ff4f970b97d/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/629e8144-0763-47ff-b622-4ff4f970b97d/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/629e8144-0763-47ff-b622-4ff4f970b97d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7000/artifacts/629e8144-0763-47ff-b622-4ff4f970b97d/recording) for each test

2022-12-22 22:33 UTC, melinath approved these changes
This seems extremely straightforward.

2022-12-22 22:33 UTC, merged