Data Source for google_compute_security_policy
GoogleCloudPlatform/magic-modules pull request #7014
Opened 2022-12-21 11:54 UTC by AarshDhokai

Fixes the issue : [add google_compute_security_policy data source](https://github.com/hashicorp/terraform-provider-google/issues/3321)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
google_compute_security_policy
```

2022-12-21 11:55 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-12-21 12:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7014-old..auto-pr-7014) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-21 13:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2368` 
Passed tests `2117` 
Skipped tests: `247` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccLoggingBucketConfigProject_cmekSettings|TestAccDataSourceGoogleComputeSecurityPolicy_basic </blockquote></details>

2022-12-21 13:01 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccDataSourceGoogleComputeSecurityPolicy_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/recording/TestAccDataSourceGoogleComputeSecurityPolicy_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/8027b96f-22b3-4098-bff3-a49660fdc53e/recording) for each test

2022-12-22 11:52 UTC, mitj04 commented
LGTM

2022-12-22 19:29 UTC, melinath requested changes
In general looks good, just a couple changes to request.

2022-12-22 19:29 UTC, melinath commented on mmv1/third_party/terraform/website/docs/d/compute_security_policy.html.markdown
> +To get more information about Snapshot, see:
```suggestion
To get more information about Google Compute Security Policy, see:
```

2022-12-22 19:29 UTC, melinath commented on mmv1/third_party/terraform/data_sources/data_source_google_compute_security_policy.go
> +func dataSourceComputeecurityPolicyRead(d *schema.ResourceData, meta interface{}) error {
```suggestion
func dataSourceComputeSecurityPolicyRead(d *schema.ResourceData, meta interface{}) error {
```

2022-12-22 19:29 UTC, melinath commented on mmv1/third_party/terraform/data_sources/data_source_google_compute_security_policy.go
> +		Read:   dataSourceComputeecurityPolicyRead,
```suggestion
		Read:   dataSourceComputeSecurityPolicyRead,
```

2022-12-23 05:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7014-old..auto-pr-7014) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-23 06:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2380` 
Passed tests `2130` 
Skipped tests: `248` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccLoggingBucketConfigProject_cmekSettings </blockquote></details>

2022-12-23 06:20 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/4279ad54-7488-43c8-ac44-0de042303775/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/4279ad54-7488-43c8-ac44-0de042303775/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/4279ad54-7488-43c8-ac44-0de042303775/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/4279ad54-7488-43c8-ac44-0de042303775/recording) for each test

2022-12-29 05:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7014-old..auto-pr-7014) ( 4 files changed, 196 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7014-old..auto-pr-7014) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-29 06:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2380` 
Passed tests `2130` 
Skipped tests: `248` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerCluster_withInvalidGatewayApiConfigChannel </blockquote></details>

2022-12-29 06:23 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/1e293448-8d43-4efe-a7dc-b27dd82e71cc/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/1e293448-8d43-4efe-a7dc-b27dd82e71cc/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/1e293448-8d43-4efe-a7dc-b27dd82e71cc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7014/artifacts/1e293448-8d43-4efe-a7dc-b27dd82e71cc/recording) for each test

2023-01-26 17:51 UTC, melinath commented
closing stale PR

2023-01-26 17:51 UTC, closed without merging