fix: google_container_cluster management correct default values
GoogleCloudPlatform/magic-modules pull request #7041
Opened 2022-12-23 11:45 UTC by renescheepers

Default the auto_upgrade & auto_repair to true. 

```tf
resource "google_container_cluster" "primary" {
  provider   = google-beta

  name     = "testing-rene-nap-default-2"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1

  cluster_autoscaling {
    enabled             = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 1
      maximum       = 100
    }

    resource_limits {
      resource_type = "memory"
      minimum       = 1
      maximum       = 100
    }
    auto_provisioning_defaults {

    }
  }
}
```

```tf
resource "google_container_cluster" "primary" {
  provider   = google-beta

  name     = "testing-rene-nap-default-2"
  location = "us-central1"

  remove_default_node_pool = true
  initial_node_count       = 1

  cluster_autoscaling {
    enabled             = true
    resource_limits {
      resource_type = "cpu"
      minimum       = 1
      maximum       = 100
    }

    resource_limits {
      resource_type = "memory"
      minimum       = 1
      maximum       = 100
    }
    auto_provisioning_defaults {
      management {
      }
    }
  }
}
```

Fixes https://github.com/hashicorp/terraform-provider-google/issues/13341

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
fix: default `google_container_cluster.cluster_autoscaling.auto_provisioning_defaults.management` auto_repair & auto_upgrade to true
```

2022-12-23 11:46 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @trodge, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2022-12-23 11:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change(s) Detected
The following breaking change(s) were detected within your pull request.

* field-changing-default-value - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-changing-default-value)
* field-changing-default-value - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-changing-default-value)
* field-oc-to-c - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-oc-to-c)
* field-oc-to-c - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-oc-to-c)


If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7041-old..auto-pr-7041) ( 1 file changed, 3 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7041-old..auto-pr-7041) ( 1 file changed, 3 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7041-old..auto-pr-7041) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2022-12-23 12:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2379` 
Passed tests `2121` 
Skipped tests: `248` 
Failed tests: `10` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccContainerCluster_withInvalidGatewayApiConfigChannel|TestAccContainerCluster_autoprovisioningDefaultsUpgradeSettings|TestAccContainerCluster_nodeAutoprovisioningDefaults|TestAccContainerCluster_nodeAutoprovisioning|TestAccContainerCluster_nodeAutoprovisioningDefaultsShieldedInstance|TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType|TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType|TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb|TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey|TestAccContainerClusterCustomServiceAccount_withAutopilot </blockquote></details>

2022-12-23 12:56 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_withInvalidGatewayApiConfigChannel`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_withInvalidGatewayApiConfigChannel.log)]
`TestAccContainerCluster_autoprovisioningDefaultsUpgradeSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_autoprovisioningDefaultsUpgradeSettings.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaults`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaults.log)]
`TestAccContainerCluster_nodeAutoprovisioning`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioning.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsShieldedInstance`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsShieldedInstance.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsImageType.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskType.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsDiskSizeGb.log)]
`TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerCluster_nodeAutoprovisioningDefaultsBootDiskKmsKey.log)]
`TestAccContainerClusterCustomServiceAccount_withAutopilot`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording/TestAccContainerClusterCustomServiceAccount_withAutopilot.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7041/artifacts/14f59864-1454-4dc6-9676-184880f4df03/recording) for each test

2023-01-03 22:20 UTC, trodge commented
Changing these fields from being Optional + Computed to having default values would be a breaking change due to the way terraform will perform the plan step after users update to the latest version.

What is the use case for this change?

2023-01-05 12:21 UTC, renescheepers commented
> Changing these fields from being Optional + Computed to having default values would be a breaking change due to the way terraform will perform the plan step after users update to the latest version.
> 
> What is the use case for this change?

At the moment this is already the default behaviour in GCP Console itself when creating a cluster. At the moment when the cluster is enrolled in a release channel the auto upgrade must be set to true, else it will cause some issues on the cluster when trying to provision the node pools. 
We could also consider changing the default value only when the cluster is enrolled into a release channel. Since this is definitely causing issues.

2023-01-06 17:59 UTC, trodge commented
> > Changing these fields from being Optional + Computed to having default values would be a breaking change due to the way terraform will perform the plan step after users update to the latest version.
> > What is the use case for this change?
> 
> At the moment auto_upgrade & auto_repair is already enabled when omitting `auto_provisioning_defaults` in `google_container_cluster`, so at the moment the behaviour is very weird. The values should remain the same when it isn't explicitly set. `auto_repair` & `auto_upgrade` should also be enabled by default. Especially `auto_upgrade` when enrolled in a release channel since else NAP will be entirely broken on the cluster.

Don't the values already default to true when not explicitly set?

2023-01-06 18:14 UTC, renescheepers commented
> > > Changing these fields from being Optional + Computed to having default values would be a breaking change due to the way terraform will perform the plan step after users update to the latest version.
> > > What is the use case for this change?
> > 
> > 
> > At the moment auto_upgrade & auto_repair is already enabled when omitting `auto_provisioning_defaults` in `google_container_cluster`, so at the moment the behaviour is very weird. The values should remain the same when it isn't explicitly set. `auto_repair` & `auto_upgrade` should also be enabled by default. Especially `auto_upgrade` when enrolled in a release channel since else NAP will be entirely broken on the cluster.
> 
> Don't the values already default to true when not explicitly set?

Yes, it defaults to true when you omit ```auto_provisioning_defaults``` entirely, but if you don't they default to false.

2023-01-06 21:28 UTC, trodge commented
The issue is that when users upgrade their provider to a version with this change and have an existing container cluster with your second config, they will get the following output from `terraform plan`:

```
Terraform will perform the following actions:                                                                                                                                                 
                                                                                                                                                                                              
  # google_container_cluster.primary will be updated in-place                                                                                                                                 
  ~ resource "google_container_cluster" "primary" {                                                                                                                                           
        id                          = "projects/tjr-dm-test-6/locations/us-central1/clusters/testing-rene-nap-default-2"                                            
        name                        = "testing-rene-nap-default-2"                             
        # (26 unchanged attributes hidden)                                                                                                                                                    

                                               

      ~ cluster_autoscaling {                                                                                                                                                                 
            # (2 unchanged attributes hidden)  
                                                                                               
          ~ auto_provisioning_defaults {                                                       
                # (5 unchanged attributes hidden)                                                                                                                                             
                                                                                               
              ~ management {            
                  ~ auto_repair     = false -> true                                            
                  ~ auto_upgrade    = false -> true                                            
                    # (1 unchanged attribute hidden)                                           
                }                              

                # (1 unchanged block hidden)   
            }                                  

            # (2 unchanged blocks hidden)      
        }
```

This would constitute a breaking change and we are not able to make breaking changes until the next major release.

2023-01-11 10:51 UTC, renescheepers commented
> The issue is that when users upgrade their provider to a version with this change and have an existing container cluster with your second config, they will get the following output from `terraform plan`:
> 
> ```
> Terraform will perform the following actions:                                                                                                                                                 
>                                                                                                                                                                                               
>   # google_container_cluster.primary will be updated in-place                                                                                                                                 
>   ~ resource "google_container_cluster" "primary" {                                                                                                                                           
>         id                          = "projects/tjr-dm-test-6/locations/us-central1/clusters/testing-rene-nap-default-2"                                            
>         name                        = "testing-rene-nap-default-2"                             
>         # (26 unchanged attributes hidden)                                                                                                                                                    
> 
>                                                
> 
>       ~ cluster_autoscaling {                                                                                                                                                                 
>             # (2 unchanged attributes hidden)  
>                                                                                                
>           ~ auto_provisioning_defaults {                                                       
>                 # (5 unchanged attributes hidden)                                                                                                                                             
>                                                                                                
>               ~ management {            
>                   ~ auto_repair     = false -> true                                            
>                   ~ auto_upgrade    = false -> true                                            
>                     # (1 unchanged attribute hidden)                                           
>                 }                              
> 
>                 # (1 unchanged block hidden)   
>             }                                  
> 
>             # (2 unchanged blocks hidden)      
>         }
> ```
> 
> This would constitute a breaking change and we are not able to make breaking changes until the next major release.

Do you have any idea when a major release is planned? I assume not anytime soon.

2023-01-20 01:38 UTC, maqiuyujoyce commented
Not sure if I've understood it correctly, but it seems that `auto_upgrade` and `auto_repair` need to have conditional default values: when release channel is set, the defaults are `true`; otherwise, they stay `false`?

2023-01-21 01:04 UTC, rileykarson requested changes
See comment in https://github.com/hashicorp/terraform-provider-google/issues/13341#issuecomment-1399110442, this appears to be an issue with GKE itself.  I'm not 100% certain on that, so I'll request changes rather than close this for now.

2023-01-24 10:23 UTC, renescheepers commented
> Not sure if I've understood it correctly, but it seems that `auto_upgrade` and `auto_repair` need to have conditional default values: when release channel is set, the defaults are `true`; otherwise, they stay `false`?

It would be best if the values for auto_upgrade, auto_repair would remain the same for all these snippets, but at the moment they are different. 
```tf
cluster_autoscaling {
    auto_provisioning_defaults {
      management {
      }
    }
  }
# auto upgrade *& repair would be FALSE here
```

or
```tf
cluster_autoscaling {
    auto_provisioning_defaults {
      management {
      }
    }
  }
# auto upgrade *& repair would be FALSE here
```

```tf
cluster_autoscaling {
}
# auto upgrade *& repair would be TRUE here
``` 

This is especially a problem when also using a release channel since then the NAP node pool won't be able to scale at all.

2023-10-26 17:13 UTC, trodge commented
Closing this for now as adding a default value would be a breaking change. https://github.com/hashicorp/terraform-provider-google/issues/13341 has been linked to an internal ticket for the GKE team.

2023-10-26 17:13 UTC, closed without merging