Introducing replica promotion support on terraform provider
GoogleCloudPlatform/magic-modules pull request #7138
Opened 2023-01-18 11:13 UTC by isaurabhuttam

This change is regarding following [feature ask #10486](https://github.com/hashicorp/terraform-provider-google/issues/10486)
Introducing replica promotion support on terraform provider. This change will allow users to promote read replica as stand alone primary instance. To promote read replica as primary instance following steps are required:
- User sets `instance_type` property as `CLOUD_SQL_INSTANCE`
- User removes `master_instance_name` and `replica_configuration` properties from replica terraform script.
- User runs `terraform apply`

Appropriate terraform provider level validation are introduces:
- In case of promote replica request, replica instance can not have `master_instance_name` and `replica_configuration` set.
- This validation will be performed at the time of `terraform plan` and `terraform apply`

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```
Introducing replica promotion support on terraform provider. This change will allow users to promote read replica as stand alone primary instance. To promote read replica as primary following steps are required:

- User sets `instance_type` property as `CLOUD_SQL_INSTANCE`
- User removes `master_instance_name` and `replica_configuration` properties from replica terraform script.
- User runs `terraform apply`

```

2023-01-18 11:13 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2023-01-18 11:14 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-01-18 11:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 503 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 503 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-18 12:29 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2428` 
Passed tests `2170` 
Skipped tests: `252` 
Failed tests: `6` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent|TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent|TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful </blockquote></details>

2023-01-18 12:44 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNameAndReplicaConfigurationPresent.log)]
`TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithMasterInstanceNamePresent.log)]
`TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccSqlDatabaseInstance_ReplicaPromoteFailedWithReplicaConfigurationPresent.log)]
`TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccSqlDatabaseInstance_ReplicaPromoteSuccessful.log)] 

Tests failed during RECORDING mode:
 `TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/build-log/recording_build/TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording/TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/9b206f78-bfb4-4e47-a303-a99e7aab39b9/recording) for each test

2023-01-19 06:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 502 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 502 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-19 07:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2429` 
Passed tests `2172` 
Skipped tests: `253` 
Failed tests: `4` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccVertexAIIndex_updated|TestAccLoggingBucketConfigProject_cmekSettings|TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent </blockquote></details>

2023-01-19 08:23 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccVertexAIIndex_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/recording/TestAccVertexAIIndex_updated.log)]
`TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/build-log/recording_build/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)]
`TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/build-log/recording_build/TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/recording/TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/b66f47e3-4700-42e1-9768-df8aa8fea83a/recording) for each test

2023-01-23 06:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 503 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 503 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-23 07:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2428` 
Passed tests `2173` 
Skipped tests: `253` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample|TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent </blockquote></details>

2023-01-23 07:50 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/c2854b68-2646-4b90-8059-37324a97901e/recording/TestAccSqlDatabaseInstance_ReplicaPromoteSkippedWithNoMasterInstanceNameAndNoReplicaConfigurationPresent.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/c2854b68-2646-4b90-8059-37324a97901e/build-log/recording_build/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/c2854b68-2646-4b90-8059-37324a97901e/recording/TestAccCloudfunctions2function_cloudfunctions2BasicGcsExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/c2854b68-2646-4b90-8059-37324a97901e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/c2854b68-2646-4b90-8059-37324a97901e/recording) for each test

2023-01-23 17:23 UTC, slevenick commented
@c2thorn can you take a look at this? I think you're more familiar with replicas and promotion via TF

2023-01-24 18:29 UTC, c2thorn requested changes
Hi @isaurabhuttam 
We'll need to revise the documentation for sql database instance to include this behavior in `instance_type` here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/sql_database_instance.html.markdown

Also, it does not seem like we have checks for invalid `instance_type` updates. Should `isReplicaPromoteRequested` be a generic update check for `instance_type`?

2023-01-26 17:53 UTC, isaurabhuttam commented
> Hi @isaurabhuttam We'll need to revise the documentation for sql database instance to include this behavior in `instance_type` here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/sql_database_instance.html.markdown
> 
> Also, it does not seem like we have checks for invalid `instance_type` updates. Should `isReplicaPromoteRequested` be a generic update check for `instance_type`?

Sure, let me update the documentation. 
I did not added the invalid `instance_type` check because Cloud SQL api supports the `instance_type` value check and invalid value will fail the API call. I did not understand the second part of question (Should `isReplicaPromoteRequested` be a generic update check for `instance_type`?), can you please elaborate this.

2023-01-26 18:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7138-old..auto-pr-7138) ( 3 files changed, 507 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7138-old..auto-pr-7138) ( 3 files changed, 507 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7138-old..auto-pr-7138) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-01-26 19:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2435` 
Passed tests `2180` 
Skipped tests: `254` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccContainerCluster_failedCreation </blockquote></details>

2023-01-26 19:55 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccContainerCluster_failedCreation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/16a3dc92-3eec-4a5d-aee6-0ac147640cfd/recording/TestAccContainerCluster_failedCreation.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/16a3dc92-3eec-4a5d-aee6-0ac147640cfd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7138/artifacts/16a3dc92-3eec-4a5d-aee6-0ac147640cfd/recording) for each test

2023-01-26 23:45 UTC, c2thorn approved these changes

2023-01-26 23:45 UTC, merged