Fix taglocation waiter
GoogleCloudPlatform/magic-modules pull request #7206
Opened 2023-02-02 18:18 UTC by ghabian

This PR fixes a bug in tags_location_tag_binding resource for zonal parent resources.

For resources that return an operation ID on create/destory. We need to read the location and update the basepath in the created waiters.

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/11448

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
add support for zonal parent resources for the tags_location_tag_binding resource

```

2023-02-02 18:19 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @zli82016, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-02-02 18:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 78 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 78 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-02 19:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2445` 
Passed tests `2190` 
Skipped tests: `255` 
Failed tests: `0` 

All tests passed in REPLAYING mode
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/34ddf264-7f6c-4d64-b8aa-a7023296d8f4/build-log/replaying_test.log)

2023-02-03 20:33 UTC, hao-nan-li commented
Hey, can you help us to identify which resource(s) are affected, and which tests are covering the change? Thanks in advance.

2023-02-07 16:50 UTC, ghabian commented
the resource impacted is `tags_location_tag_binding` already has tests written for it. I'm fixing a bug when using the resource in a way not covered by the existing tests.

Should I write tests specifically covering this scenario and add them as part of the PR?

2023-02-07 18:20 UTC, hao-nan-li commented
> the resource impacted is `tags_location_tag_binding` already has tests written for it. I'm fixing a bug when using the resource in a way not covered by the existing tests.
> 
> Should I write tests specifically covering this scenario and add them as part of the PR?

Yeah, I think it's a good idea to add tests that cover the scenario you've mentioned.

2023-02-14 22:28 UTC, hao-nan-li requested changes
Any update so far? You might also need to do a rebase on the main branch in order to run builds on git in the future.

2023-02-17 00:40 UTC, hao-nan-li commented
/gcbrun

2023-02-17 00:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 78 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 78 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-17 01:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2467` 
Passed tests `2211` 
Skipped tests: `256` 
Failed tests: `0` 

All tests passed in REPLAYING mode
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/a9d85e94-a652-413f-9316-922021056f9d/build-log/replaying_test.log)

2023-02-17 04:02 UTC, ghabian commented
@hao-nan-li added a test to do zonal bindings which passes in my local build. `testAccTagsLocationTagBinding_locationTagBindingzonal`

2023-02-17 04:05 UTC, ghabian commented
/gcbrun

2023-02-17 20:25 UTC, hao-nan-li commented
/gcbrun

2023-02-17 20:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-17 21:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2467` 
Passed tests `2210` 
Skipped tests: `256` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccTags </blockquote></details>

2023-02-17 21:37 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/eb38241f-540e-40bd-a4d1-80fec8c6fef2/build-log/recording_build/TestAccTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/eb38241f-540e-40bd-a4d1-80fec8c6fef2/recording/TestAccTags.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/eb38241f-540e-40bd-a4d1-80fec8c6fef2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/eb38241f-540e-40bd-a4d1-80fec8c6fef2/recording) for each test

2023-02-17 21:39 UTC, hao-nan-li commented
/gcbrun

2023-02-17 21:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-17 22:39 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2467` 
Passed tests `2210` 
Skipped tests: `256` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2023-02-17 22:40 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/e3c2ad92-ab50-43a2-bc65-f8ec4a86e51b/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/e3c2ad92-ab50-43a2-bc65-f8ec4a86e51b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/e3c2ad92-ab50-43a2-bc65-f8ec4a86e51b/recording) for each test

2023-02-17 23:06 UTC, hao-nan-li requested changes
It looks like the PR has some linting problem. Could you run `go vet` locally to double-check?

When i had the same issue previously, I had to add an extra line at the end the files that has the lint alert.

2023-02-17 23:06 UTC, hao-nan-li commented on mmv1/third_party/terraform/tests/resource_tags_test.go
> +func testAccTagsLocationTagBinding_locationTagBindingzonal(t *testing.T) {
Thanks for adding the tests, can you make the first letter capital case? 
`TestAccTagsLocationTagBinding_locationTagBindingzonal`

2023-02-21 16:30 UTC, ghabian commented
> It looks like the PR has some linting problem. Could you run `go vet` locally to double-check?
> 
> When i had the same issue previously, I had to add an extra line at the end the files that has the lint alert.

`go vet` shows me nothing even after I sync/pull from the main branch. for both ga and beta providers.

2023-02-21 17:29 UTC, hao-nan-li commented
/gcbrun

2023-02-21 17:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 152 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-21 17:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Failed tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/9045751d-e977-445f-9800-f1e3a58d8784/build-log/replaying_test.log)

2023-02-21 17:50 UTC, hao-nan-li requested changes
Looks like the lint errors are still there. Can you add an extra line at the end of each file that does not have an empty line?

2023-02-21 22:46 UTC, hao-nan-li commented
/gcbrun

2023-02-21 23:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 145 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 145 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 15 insertions(+), 3 deletions(-))

2023-02-21 23:47 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2463` 
Passed tests `2207` 
Skipped tests: `255` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccTagsLocationTagBinding_locationTagBindingzonal </blockquote></details>

2023-02-21 23:48 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccTagsLocationTagBinding_locationTagBindingzonal`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/b4d5ee8c-6cbb-4b09-a5f4-8b6cbc819fc3/recording/TestAccTagsLocationTagBinding_locationTagBindingzonal.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/b4d5ee8c-6cbb-4b09-a5f4-8b6cbc819fc3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/b4d5ee8c-6cbb-4b09-a5f4-8b6cbc819fc3/recording) for each test

2023-02-21 23:55 UTC, hao-nan-li requested changes
Looks like there are more lint problems to work on.

I created a branch with your commits and did the following:

haonan@haonan-macbookpro terraform-provider-google % **make lint**
sh -c "'/Users/haonan/go/src/github.com/hashicorp/terraform-provider-google/scripts/gofmtcheck.sh'"
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
**./google/tagslocation_operation.go
./google/resource_tags_test.go
./google/self_link_helpers.go**
You can use the command: `make fmt` to reformat code.

2023-02-22 02:23 UTC, ghabian commented
> Looks like there are more lint problems to work on.
> 
> I created a branch with your commits and did the following:
> 
> haonan@haonan-macbookpro terraform-provider-google % **make lint** sh -c "'/Users/haonan/go/src/github.com/hashicorp/terraform-provider-google/scripts/gofmtcheck.sh'" ==> Checking that code complies with gofmt requirements... gofmt needs running on the following files: **./google/tagslocation_operation.go ./google/resource_tags_test.go ./google/self_link_helpers.go** You can use the command: `make fmt` to reformat code.

thanks, latest commit fixes those

2023-02-22 17:03 UTC, hao-nan-li commented
/gcbrun

2023-02-22 17:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 142 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 4 files changed, 142 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 14 insertions(+), 3 deletions(-))

2023-02-22 18:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2463` 
Passed tests `2207` 
Skipped tests: `255` 
Failed tests: `1` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease </blockquote></details>

2023-02-22 18:03 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/500f2aea-58a4-4930-8f78-c42ac266a98a/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/500f2aea-58a4-4930-8f78-c42ac266a98a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/500f2aea-58a4-4930-8f78-c42ac266a98a/recording) for each test

2023-02-22 18:05 UTC, hao-nan-li approved these changes
LGTM, waiting on @zli82016 to sign off.

Just a quick note to change the release message following the release note guide.

2023-02-22 20:38 UTC, ghabian commented
> LGTM, waiting on @zli82016 to sign off.
Thanks!

> Just a quick note to change the release message following the release note guide.
Updated, PTAL

2023-02-23 20:02 UTC, zli82016 commented on mmv1/third_party/terraform/utils/self_link_helpers.go
> +func GetLocationFromOpName(opName string) string {
Can you please move this function to the file tagslocation_operation.go, as it is only used there for now?

2023-02-23 20:03 UTC, zli82016 commented on mmv1/third_party/terraform/utils/tagslocation_operation.go
> +package google
Can you please rename this file to tags_location_operation.go to follow the convention?

2023-02-23 20:03 UTC, zli82016 commented on mmv1/third_party/terraform/utils/tagslocation_operation.go
> +// nolint: deadcode,unused
Can you please remove this line, as the function tagsLocationOperationWaitTimeWithResponse is used?

2023-02-28 19:26 UTC, zli82016 commented
@ghabian , any update? Thanks.

2023-03-01 01:51 UTC, ghabian commented
> @ghabian , any update? Thanks.

Done, PTAL

2023-03-01 17:24 UTC, zli82016 commented
/gcbrun

2023-03-01 17:28 UTC, zli82016 commented
Hello, @ghabian, can you please rebase main branch? Recently, ruby is upgraded to 3.2.0.

2023-03-01 17:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 142 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 142 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-03-01 17:56 UTC, ghabian commented
rebased just now

2023-03-01 18:05 UTC, hao-nan-li commented
/gcbrun

2023-03-01 18:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 142 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7206-old..auto-pr-7206) ( 3 files changed, 142 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7206-old..auto-pr-7206) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-03-01 19:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2483` 
Passed tests `2225` 
Skipped tests: `255` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccComputeForwardingRule_update|TestAccSqlDatabaseInstance_Timezone|TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample </blockquote></details>

2023-03-01 20:19 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/recording/TestAccComputeForwardingRule_update.log)]
`TestAccSqlDatabaseInstance_Timezone`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/recording/TestAccSqlDatabaseInstance_Timezone.log)] 

Tests failed during RECORDING mode:
 `TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/build-log/recording_build/TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/recording/TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7206/artifacts/c9d088cf-6b43-4966-bb12-dd39dd1feb21/recording) for each test

2023-03-01 20:32 UTC, zli82016 approved these changes
LGTM

2023-03-01 20:33 UTC, merged