feat(google_container_node_pool): support `node_config.kubelet_config.pod_pids_limit`
GoogleCloudPlatform/magic-modules pull request #7227
Opened 2023-02-06 08:53 UTC by renescheepers

Adds support for setting the [Pod PIDs limit on the Kubelet](https://cloud.google.com/sdk/gcloud/reference/beta/container/node-pools/create#--system-config-from-file:~:text=e.g.%2C%20%27100ms%27)-,podPidsLimit,-integer%20(The%20value).

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
feat(google_container_node_pool): support `node_config.kubelet_config.pod_pids_limit`
```

2023-02-06 08:54 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-02-06 09:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7227-old..auto-pr-7227) ( 1 file changed, 9 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7227-old..auto-pr-7227) ( 1 file changed, 9 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-06 09:33 UTC, modular-magician commented
The provider crashed while running the VCR tests in REPLAYING mode
Please fix it to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/eec5bc83-124e-4d8f-8e95-c56ca1f7daaa/build-log/replaying_test.log)

2023-02-06 14:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7227-old..auto-pr-7227) ( 1 file changed, 9 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7227-old..auto-pr-7227) ( 1 file changed, 9 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-06 14:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2453` 
Passed tests `2195` 
Skipped tests: `255` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccRegionInstanceGroupManager_stateful|TestAccFrameworkProviderMeta_setModuleName|TestAccDataSourceDnsRecordSet_basic </blockquote></details>

2023-02-06 15:00 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFrameworkProviderMeta_setModuleName`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/recording/TestAccFrameworkProviderMeta_setModuleName.log)]
`TestAccDataSourceDnsRecordSet_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/recording/TestAccDataSourceDnsRecordSet_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccRegionInstanceGroupManager_stateful`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/build-log/recording_build/TestAccRegionInstanceGroupManager_stateful_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/recording/TestAccRegionInstanceGroupManager_stateful.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/6df515f2-7b6f-407e-addd-5eadfa7ef802/recording) for each test

2023-02-06 17:49 UTC, slevenick requested changes
Can you add this field to an existing test case for the container node pool resource? 

There are a range of tests here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/resource_container_node_pool_test.go.erb

Can you find one in there where specifying this field makes sense and add it in?

2023-02-07 15:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 17 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 17 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-07 16:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2454` 
Passed tests `2192` 
Skipped tests: `255` 
Failed tests: `7` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerNodePool_withKubeletConfig|TestAccRegionInstanceGroupManager_stateful|TestAccApigeeAddonsConfig_apigeeAddonsTestExample|TestAccFrameworkProviderMeta_setModuleName|TestAccDataSourceDnsRecordSet_basic|TestAccDataSourceDnsManagedZone_basic </blockquote></details>

2023-02-07 16:16 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerNodePool_withKubeletConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccApigeeAddonsConfig_apigeeAddonsTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccApigeeAddonsConfig_apigeeAddonsTestExample.log)]
`TestAccFrameworkProviderMeta_setModuleName`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccFrameworkProviderMeta_setModuleName.log)]
`TestAccDataSourceDnsRecordSet_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccDataSourceDnsRecordSet_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccRegionInstanceGroupManager_stateful`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/build-log/recording_build/TestAccRegionInstanceGroupManager_stateful_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccRegionInstanceGroupManager_stateful.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/9da2afa3-c95a-47f4-bfc2-2b9705f05260/recording) for each test

2023-02-13 08:16 UTC, renescheepers commented
@slevenick I've added the pod PID limit to an existing test. Can I get another review?

2023-02-13 17:34 UTC, slevenick requested changes
Looking good, thanks! One last thing, can you add this field to the documentation for node_config?

It should be here: https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown

2023-02-14 17:36 UTC, slevenick commented
/gcbrun

2023-02-14 17:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7227-old..auto-pr-7227) ( 3 files changed, 20 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7227-old..auto-pr-7227) ( 3 files changed, 20 insertions(+), 5 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7227-old..auto-pr-7227) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-14 18:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2470` 
Passed tests `2209` 
Skipped tests: `256` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccApigeeAddonsConfig_apigeeAddonsTestExample|TestAccFrameworkProviderMeta_setModuleName|TestAccDataSourceDnsRecordSet_basic|TestAccDataSourceDnsManagedZone_basic </blockquote></details>

2023-02-14 18:43 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccApigeeAddonsConfig_apigeeAddonsTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording/TestAccApigeeAddonsConfig_apigeeAddonsTestExample.log)]
`TestAccFrameworkProviderMeta_setModuleName`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording/TestAccFrameworkProviderMeta_setModuleName.log)]
`TestAccDataSourceDnsRecordSet_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording/TestAccDataSourceDnsRecordSet_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7227/artifacts/ed2e9099-5115-425e-8607-11dc13b24dfa/recording) for each test

2023-02-16 00:51 UTC, slevenick approved these changes

2023-02-16 00:51 UTC, merged