Fix kms `externalProtectionLevelOptions` shown as read only and within `attestation`
GoogleCloudPlatform/magic-modules pull request #7245
Opened 2023-02-07 16:12 UTC by echaouchna

`externalProtectionLevelOptions` is defined within `attestation`, and the whole `attestation` is flagged as output only, which makes it impossible to modify the `externalKeyUri` attribute for example.
However, according to the documentation : https://cloud.google.com/kms/docs/reference/rest/v1/projects.locations.keyRings.cryptoKeys.cryptoKeyVersions#CryptoKeyVersion, externalProtectionLevelOptions is on its own, and it's not flagged as output only.

this will fix the following issue https://github.com/hashicorp/terraform-provider-google/issues/11500

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] [Generated Terraform](https://github.com/GoogleCloudPlatform/magic-modules#generating-the-terraform-providers), and ran `make test` and `make lint` to ensure it passes unit and linter tests.
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Ran](https://github.com/hashicorp/terraform-provider-google/blob/main/.github/CONTRIBUTING.md#tests) relevant acceptance tests (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
kms: Moved externalProtectionLevelOptions to be on its own and not under attestation in the google_kms_crypto_key_versions resource

```

2023-02-07 16:13 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-02-07 16:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change(s) Detected
The following breaking change(s) were detected within your pull request.

* Field `attestation.external_protection_level_options.ekm_connection_key_path` within resource `google_kms_crypto_key_version` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `attestation.external_protection_level_options.external_key_uri` within resource `google_kms_crypto_key_version` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `attestation.external_protection_level_options` within resource `google_kms_crypto_key_version` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)


If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7245-old..auto-pr-7245) ( 2 files changed, 93 insertions(+), 42 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7245-old..auto-pr-7245) ( 2 files changed, 93 insertions(+), 42 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7245-old..auto-pr-7245) ( 3 files changed, 43 insertions(+), 3 deletions(-))

2023-02-07 17:06 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2454` 
Passed tests `2194` 
Skipped tests: `255` 
Failed tests: `5` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccRegionInstanceGroupManager_stateful|TestAccApigeeAddonsConfig_apigeeAddonsTestExample|TestAccFrameworkProviderMeta_setModuleName|TestAccDataSourceDnsRecordSet_basic|TestAccDataSourceDnsManagedZone_basic </blockquote></details>

2023-02-07 17:18 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccApigeeAddonsConfig_apigeeAddonsTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording/TestAccApigeeAddonsConfig_apigeeAddonsTestExample.log)]
`TestAccFrameworkProviderMeta_setModuleName`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording/TestAccFrameworkProviderMeta_setModuleName.log)]
`TestAccDataSourceDnsRecordSet_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording/TestAccDataSourceDnsRecordSet_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccRegionInstanceGroupManager_stateful`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/build-log/recording_build/TestAccRegionInstanceGroupManager_stateful_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording/TestAccRegionInstanceGroupManager_stateful.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/e77477f7-69ce-4fd6-bed5-02ad80de3e1d/recording) for each test

2023-02-16 01:04 UTC, slevenick requested changes
Unfortunately I don't believe we can do this in place as noted by the breaking change detector. We may be able to introduce new fields to allow setting these values though. Can you add these fields without removing the old ones?

2023-02-16 09:29 UTC, echaouchna commented
Sure I will do that

2023-02-16 18:55 UTC, echaouchna commented
Changes applied

2023-02-16 20:21 UTC, slevenick requested changes
Can you also add a test that sets this field so we can ensure it's being correctly set?

2023-02-17 01:14 UTC, echaouchna commented
I added a test for externalKeyUri, not sure if should do the same for ekmConnectionKeyPath

2023-02-17 20:11 UTC, slevenick commented
/gcbrun

2023-02-17 20:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7245-old..auto-pr-7245) ( 3 files changed, 176 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7245-old..auto-pr-7245) ( 3 files changed, 176 insertions(+))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7245-old..auto-pr-7245) ( 3 files changed, 43 insertions(+), 3 deletions(-))

2023-02-17 21:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2468` 
Passed tests `2209` 
Skipped tests: `256` 
Failed tests: `3` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccKmsCryptoKeyVersion_externalKeyUri|TestAccFirebaserulesRelease_BasicRelease|TestAccApigeeAddonsConfig_apigeeAddonsTestExample </blockquote></details>

2023-02-17 21:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccApigeeAddonsConfig_apigeeAddonsTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/recording/TestAccApigeeAddonsConfig_apigeeAddonsTestExample.log)] 

Tests failed during RECORDING mode:
 `TestAccKmsCryptoKeyVersion_externalKeyUri`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/build-log/recording_build/TestAccKmsCryptoKeyVersion_externalKeyUri_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/recording/TestAccKmsCryptoKeyVersion_externalKeyUri.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7245/artifacts/376a4c62-9740-4423-8a6b-5083b1dfac57/recording) for each test

2023-02-17 21:34 UTC, slevenick commented
Failing with: 
        Error: Error creating CryptoKeyVersion: googleapi: Error 400: external_protection_level_options is only valid for keys with the EXTERNAL or EXTERNAL_VPC protection level.

2023-02-17 21:35 UTC, echaouchna commented
Thank you I will check this asap

2023-02-17 22:57 UTC, echaouchna commented
The issue is fixed
Now I'm having another one 
```shell
❯ make testacc TEST=./google TESTARGS='-run=TestAccKmsCryptoKeyVersion_externalKeyUri'
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccKmsCryptoKeyVersion_externalKeyUri -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccKmsCryptoKeyVersion_externalKeyUri
=== PAUSE TestAccKmsCryptoKeyVersion_externalKeyUri
=== CONT  TestAccKmsCryptoKeyVersion_externalKeyUri
    provider_test.go:307: Step 1/2 error: Error running apply: exit status 1

        Error: Error creating CryptoKeyVersion: googleapi: Error 400: External key error: The key URI has an invalid protocol. Verify the key URI and try again. Key URI: http://keys-provider.external/tdln080pa92jnysubjiz.
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.PreconditionFailure",
            "violations": [
              {
                "subject": "projects/datafusion-svpc-2b2a/locations/us-central1/keyRings/tf-test-6kuuy9jvox/cryptoKeys/tf-test-4ptoz73ja7/cryptoKeyVersions/1",
                "type": "KEY_UNREACHABLE"
              },
              {
                "subject": "http://keys-provider.external/tdln080pa92jnysubjiz",
                "type": "EXTERNAL_KEY_URI_INVALID"
              }
            ]
          }
        ]

          with google_kms_crypto_key_version.crypto_key_version,
          on terraform_plugin_test.tf line 34, in resource "google_kms_crypto_key_version" "crypto_key_version":
          34: resource "google_kms_crypto_key_version" "crypto_key_version" {

--- FAIL: TestAccKmsCryptoKeyVersion_externalKeyUri (21.32s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google/google	21.353s
FAIL
make: *** [GNUmakefile:15: testacc] Error 1
make testacc TEST=./google   83,80s user 6,66s system 159% cpu 56,670 total
```

I may need some help here, since we are referncing an external key uri, and I don't really know how to mock that

2023-02-17 23:02 UTC, slevenick commented
Hmmm and it seems to actually try to reach the key. Do you know how this is supposed to be set up? Are there docs or guides written about using this feature?

2023-02-17 23:04 UTC, echaouchna commented
Yes https://cloud.google.com/kms/docs/ekm

2024-02-22 18:07 UTC, tdbhacks commented
Just noticed this PR, quick FYI that we have a more recent PR doing pretty much the same thing and we're trying to get the automated test working internally. See https://github.com/GoogleCloudPlatform/magic-modules/pull/9931.

2024-02-22 18:41 UTC, slevenick commented
I'd vote to close this in favor of https://github.com/GoogleCloudPlatform/magic-modules/pull/9931 if they accomplish the same thing. That PR is owned by a service team member who will know more about how to set up the resources than I do!

2024-02-22 20:06 UTC, echaouchna commented
I think we can close this one

2024-02-22 20:10 UTC, closed without merging