Remove artifact repository beta URL, fixup handwritten tests
GoogleCloudPlatform/magic-modules pull request #7345
Opened 2023-02-23 22:14 UTC by rileykarson

Seems like this service declined to update its beta API, meaning the invariant that beta APIs are a superset of GAs is broken. The test configuration here succeeds on the GA provider but fails on the beta one:

```
│ Error: Error creating Repository: googleapi: Error 400: Invalid value at 'repository.format' (type.googleapis.com/google.devtools.artifactregistry.v1beta2.Repository.Format), "KFP"
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.BadRequest",
│     "fieldViolations": [
│       {
│         "description": "Invalid value at 'repository.format' (type.googleapis.com/google.devtools.artifactregistry.v1beta2.Repository.Format), \"KFP\"",
│         "field": "repository.format"
│       }
│     ]
│   }
│ ]
│
│   on main.tf line 1, in resource "google_artifact_registry_repository" "my-repo":
│    1: resource "google_artifact_registry_repository" "my-repo" {
```

Also rename some tests to match standard format, un-guard the handwritten test file.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
artifactregistry: fixed an issue where `google-beta` used an outdated beta API rather than the GA service API. New format values like "KFP" will now be accepted by both providers.
```

2023-02-23 23:41 UTC, slevenick requested changes
Failing TFV build, may need a rebase?

2023-02-23 23:48 UTC, rileykarson commented
Yeah, had to pull in https://github.com/GoogleCloudPlatform/magic-modules/pull/7346

2023-02-24 00:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7345-old..auto-pr-7345) ( 1 file changed, 160 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7345-old..auto-pr-7345) ( 3 files changed, 44 insertions(+), 17 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7345-old..auto-pr-7345) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-24 00:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2464` 
Passed tests `2194` 
Skipped tests: `255` 
Failed tests: `15` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccCloudFunctionsFunction_cmek|TestAccCloudFunctionsFunction_dockerRepository|TestAccComputeForwardingRule_update|TestAccCloudFunctionsFunction_update|TestAccArtifactRegistryRepository_artifactRegistryRepositoryBasicExample|TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample|TestAccArtifactRegistryRepositoryIamPolicyGenerated|TestAccArtifactRegistryRepositoryIamMemberGenerated|TestAccArtifactRegistryRepositoryIamBindingGenerated|TestAccArtifactRegistryRepository_createMvnSnapshot|TestAccArtifactRegistryRepository_createMvnRelease|TestAccArtifactRegistryRepository_kfp|TestAccArtifactRegistryRepository_update|TestAccDataSourceGoogleArtifactRegistryRepositoryConfig </blockquote></details>

2023-02-24 00:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCloudFunctionsFunction_dockerRepository`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccCloudFunctionsFunction_dockerRepository.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccComputeForwardingRule_update.log)]
`TestAccCloudFunctionsFunction_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccCloudFunctionsFunction_update.log)]
`TestAccArtifactRegistryRepository_artifactRegistryRepositoryBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_artifactRegistryRepositoryBasicExample.log)]
`TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_artifactRegistryRepositoryCmekExample.log)]
`TestAccArtifactRegistryRepositoryIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepositoryIamPolicyGenerated.log)]
`TestAccArtifactRegistryRepositoryIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepositoryIamMemberGenerated.log)]
`TestAccArtifactRegistryRepositoryIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepositoryIamBindingGenerated.log)]
`TestAccArtifactRegistryRepository_createMvnSnapshot`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_createMvnSnapshot.log)]
`TestAccArtifactRegistryRepository_createMvnRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_createMvnRelease.log)]
`TestAccArtifactRegistryRepository_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_update.log)]
`TestAccDataSourceGoogleArtifactRegistryRepositoryConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccDataSourceGoogleArtifactRegistryRepositoryConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccCloudFunctionsFunction_cmek`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/build-log/recording_build/TestAccCloudFunctionsFunction_cmek_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccCloudFunctionsFunction_cmek.log)]
`TestAccArtifactRegistryRepository_kfp`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/build-log/recording_build/TestAccArtifactRegistryRepository_kfp_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording/TestAccArtifactRegistryRepository_kfp.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/f1550bd1-6c71-4b5a-b31b-b36a8bde9cc4/recording) for each test

2023-02-24 01:58 UTC, rileykarson commented on mmv1/third_party/terraform/tests/resource_artifact_registry_repository_test.go.erb
> +  description = "my-kfp-repository""
```suggestion
  description = "my-kfp-repository"
```

2023-02-24 02:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7345-old..auto-pr-7345) ( 1 file changed, 160 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7345-old..auto-pr-7345) ( 3 files changed, 44 insertions(+), 17 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7345-old..auto-pr-7345) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-02-24 02:59 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2464` 
Passed tests `2207` 
Skipped tests: `255` 
Failed tests: `2` 

#### Action taken 
<details> <summary>Triggering VCR tests in RECORDING mode for the tests that failed during VCR. Click here to see the failed tests</summary><blockquote>TestAccCloudFunctionsFunction_cmek|TestAccArtifactRegistryRepository_kfp </blockquote></details>

2023-02-24 03:00 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccCloudFunctionsFunction_cmek`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/e0a6b094-76c8-458f-8bd5-93dcd999abbb/recording/TestAccCloudFunctionsFunction_cmek.log)]
`TestAccArtifactRegistryRepository_kfp`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/e0a6b094-76c8-458f-8bd5-93dcd999abbb/recording/TestAccArtifactRegistryRepository_kfp.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/e0a6b094-76c8-458f-8bd5-93dcd999abbb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7345/artifacts/e0a6b094-76c8-458f-8bd5-93dcd999abbb/recording) for each test

2023-02-24 17:08 UTC, slevenick approved these changes

2023-02-24 17:32 UTC, merged