Update http_target uri of scheduler_job_http_tf
GoogleCloudPlatform/magic-modules pull request #7401
Opened 2023-03-03 11:36 UTC by makrandbhonde

The http_target uri https://example.com/ping which is present in the given code gives an 404 error for a POST request. Hence I changed this uri to https://example.com/ which works fine. I know that this is just for user understanding and user can enter uri of his choice but still confusing since most of the people directly run this resource for testing purposes and since the uri gives an error the scheduler status on gcp spots as failed.

![image](https://user-images.githubusercontent.com/60532803/222710640-9759ca3a-05bd-43d4-a76b-a30ce46f0915.png)

2023-03-03 11:37 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2023-03-03 16:48 UTC, hao-nan-li commented
/gcbrun

2023-03-03 16:48 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2023-03-03 17:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 2 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 2 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7401-old..auto-pr-7401) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-03-03 17:49 UTC, hao-nan-li requested changes
Looks like it's your first time contributing to the project. Could you sign the CLA as mentioned in the comment?

2023-03-06 17:10 UTC, hao-nan-li commented
/gcbrun

2023-03-06 17:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 2 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 2 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7401-old..auto-pr-7401) ( 2 files changed, 3 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7401-old..auto-pr-7401) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-03-06 18:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2487` 
Passed tests `2226` 
Skipped tests: `258` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample|TestAccFirebaserulesRelease_BasicRelease|TestAccCloudSchedulerJob_schedulerJobHttpExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-06 19:05 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccCloudSchedulerJob_schedulerJobHttpExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/recording/TestAccCloudSchedulerJob_schedulerJobHttpExample.log)] 

Tests failed during RECORDING mode:
 `TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/build-log/recording_build/TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/recording/TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7401/artifacts/8aa56625-0ebd-4105-aa59-4f623ab6bfa3/recording) for each test

2023-03-06 20:53 UTC, hao-nan-li commented
Thanks for signing CLA. 
1) Is there a git ticket associated to your fix?
2) You can ignore the failed test as it's a known flaky test.

2023-03-08 05:46 UTC, makrandbhonde commented
> Thanks for signing CLA.
> 
> 1. Is there a git ticket associated to your fix?
> 2. You can ignore the failed test as it's a known flaky test.

No @hao-nan-li It is not associated with any ticket. You can guide me with it if it is required. Thanks!

2023-03-16 09:45 UTC, makrandbhonde commented
Hello @hao-nan-li Can you please give any updates related to my PR or any further steps I need to follow ?

2023-03-16 15:55 UTC, hao-nan-li approved these changes
Thanks for the reminder. LGTM.

Just need to edit the release note based on https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md

2023-03-21 17:38 UTC, merged

2023-03-22 13:16 UTC, makrandbhonde commented
Sure! Thank you @hao-nan-li