specs out the additional fields for nmve_ssd
GoogleCloudPlatform/magic-modules pull request #7427
Opened 2023-03-09 03:37 UTC by geojaz

Adds `local_nvme_ssd_block` to `node_config` block in the `google_container_node_pool`.

Also I needed to update the go.sum and go.mod and wasn't really clear on the right process.
Does this look right? Is there a "right" way to do it? Mine was really hacky :)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**
```release-note:enhancement
container: Adds `local_nvme_ssd_block` to `node_config` block in the `google_container_node_pool`.
```

2023-03-10 22:28 UTC, shuyama1 commented
/gcbrun

2023-03-10 22:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 3 files changed, 334 insertions(+), 84 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 444 insertions(+), 111 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 59 insertions(+), 49 deletions(-))

2023-03-10 22:50 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Affected tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/4b725ba3-e65d-44ff-bb8b-d4bcc4ced345/build-log/replaying_test.log)

2023-03-11 00:15 UTC, geojaz commented
I can't see the logs for the failures, but i think it might have something to do with updating the deps for `google.golang.org/api v0.111.0`.
I'll have to take a closer look to the tests on my side unless you can share some additional details- feel free to ping me on gchat @ehole

2023-03-13 05:59 UTC, geojaz commented
oops..

2023-03-13 17:17 UTC, shuyama1 commented
/gcbrun

2023-03-13 17:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 3 files changed, 335 insertions(+), 85 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 445 insertions(+), 112 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-13 18:00 UTC, shuyama1 commented
Tests failed due to:
```
go: bitbucket.org/creachadair/stringset@v0.0.8: missing go.sum entry; to add it:
	go mod download bitbucket.org/creachadair/stringset
make: *** [vet] Error 1
GNUmakefile:26: recipe for target 'vet' failed
make: *** No rule to make target 'tools'.  Stop.
==> Checking that code complies with gofmt requirements...
go vet
go: bitbucket.org/creachadair/stringset@v0.0.8: missing go.sum entry; to add it:
	go mod download bitbucket.org/creachadair/stringset
make: *** [vet] Error 1
GNUmakefile:26: recipe for target 'vet' failed
==> Checking that code complies with gofmt requirements...
go vet
go: bitbucket.org/creachadair/stringset@v0.0.8: missing go.sum entry; to add it:
	go mod download bitbucket.org/creachadair/stringset
make: *** [vet] Error 1
```

2023-03-13 19:30 UTC, shuyama1 commented
/gcbrun

2023-03-13 19:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 3 files changed, 356 insertions(+), 35 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 466 insertions(+), 62 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-13 20:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2497` 
Passed tests `2218` 
Skipped tests: `262` 
Affected tests: `17` 

#### Action taken 
<details> <summary>Found 17 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPrivatecaCaPool_updateCaOption|TestAccPrivatecaCertificate_privatecaCertificateUpdate|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccPrivatecaCertificate_privatecaCertificateCsrExample|TestAccPrivatecaCertificate_privatecaCertificateConfigExample|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate|TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerNodePool_localNvmeSsdBlockConfig|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample|TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-13 21:02 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccPrivatecaCaPool_updateCaOption`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCaPool_updateCaOption.log)]
`TestAccPrivatecaCertificate_privatecaCertificateUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificate_privatecaCertificateUpdate.log)]
`TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateCsrExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificate_privatecaCertificateCsrExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificate_privatecaCertificateConfigExample.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate.log)]
`TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline.log)]
`TestAccPrivatecaCaPool_privatecaCapoolUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCaPool_privatecaCapoolUpdate.log)]
`TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample.log)]
`TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerNodePool_localNvmeSsdBlockConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/build-log/recording_build/TestAccContainerNodePool_localNvmeSsdBlockConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccContainerNodePool_localNvmeSsdBlockConfig.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/244362d2-203d-4b03-861c-11bc2ea7408b/recording) for each test

2023-03-13 23:17 UTC, geojaz commented
/gcbrun

2023-03-13 23:21 UTC, shuyama1 commented
/gcbrun

2023-03-13 23:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 3 files changed, 357 insertions(+), 35 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 475 insertions(+), 62 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-14 00:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2497` 
Passed tests `2231` 
Skipped tests: `262` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_update|TestAccFirebaserulesRelease_BasicRelease|TestAccContainerNodePool_localNvmeSsdBlockConfig|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-14 00:24 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/recording/TestAccComputeForwardingRule_update.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerNodePool_localNvmeSsdBlockConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/build-log/recording_build/TestAccContainerNodePool_localNvmeSsdBlockConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/recording/TestAccContainerNodePool_localNvmeSsdBlockConfig.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/96e5bf16-089b-4f9a-a9c4-f174c5fb7a88/recording) for each test

2023-03-14 05:30 UTC, shuyama1 commented
/gcbrun

2023-03-14 06:16 UTC, geojaz commented
I think this works finally, sorry for all the iterations. It's such a slow feedback loop and switching between the provider and magic modules was at least for me introducing errors 🤦 
```
==> Checking that code complies with gofmt requirements...
go vet
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google-beta -v -run=TestAccContainerNodePool_localNvmeSsdBlockConfig -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google-beta/version.ProviderVersion=acc"
=== RUN   TestAccContainerNodePool_localNvmeSsdBlockConfig
=== PAUSE TestAccContainerNodePool_localNvmeSsdBlockConfig
=== CONT  TestAccContainerNodePool_localNvmeSsdBlockConfig
--- PASS: TestAccContainerNodePool_localNvmeSsdBlockConfig (727.63s)
PASS
ok      github.com/hashicorp/terraform-provider-google-beta/google-beta 728.579s
```

2023-03-14 06:21 UTC, shuyama1 commented
/gcbrun

2023-03-14 06:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 3 files changed, 357 insertions(+), 35 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 474 insertions(+), 62 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-14 07:22 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2497` 
Passed tests `2232` 
Skipped tests: `262` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccContainerNodePool_localNvmeSsdBlockConfig|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-14 07:34 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccContainerNodePool_localNvmeSsdBlockConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/recording/TestAccContainerNodePool_localNvmeSsdBlockConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fb3e48c7-e3e3-46de-81ab-e126b0e819a6/recording) for each test

2023-03-14 18:10 UTC, shuyama1 reviewed
LGTM! only some small comments. Plus, any reason we add in beta provider exclusively? I do see this field is supported in V1 API though.

2023-03-14 19:52 UTC, geojaz commented
> LGTM! only some small comments. Plus, any reason we add in beta provider exclusively? I do see this field is supported in V1 API though.
Good call- I'll push it to GA. I effectively just copied the implementation of `ephemeral_storage_config`- looks like this should also graduate... I won't include that here.

2023-03-14 23:40 UTC, geojaz commented
Pushed with your suggestions, I couldn't get the tests on generated GA provider to run on my system- there were lots of seemingly unrelated errors. Not sure what's up

2023-03-15 04:00 UTC, samos123 commented
/gcbrun

2023-03-15 04:08 UTC, shuyama1 commented
/gcbrun

2023-03-15 04:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 460 insertions(+), 60 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 468 insertions(+), 62 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-15 05:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2500` 
Passed tests `2233` 
Skipped tests: `262` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccComputeForwardingRule_update|TestAccApigeeAddonsConfig_apigeeAddonsTestExample|TestAccDataSourceDnsManagedZone_basic|TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-15 06:00 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording/TestAccComputeForwardingRule_update.log)]
`TestAccApigeeAddonsConfig_apigeeAddonsTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording/TestAccApigeeAddonsConfig_apigeeAddonsTestExample.log)]
`TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording/TestAccWorkstationsWorkstationConfig_workstationConfigEncryptionKeyExample.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/fe2693fb-bc9f-4ba3-96e3-61d2f94a30e5/recording) for each test

2023-03-15 16:08 UTC, shuyama1 requested changes
GA test failed on TC: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/383054
It's probably due to one of the beta flags not removed

2023-03-15 16:08 UTC, shuyama1 commented on mmv1/third_party/terraform/utils/node_config.go.erb
> +<% end -%>
```suggestion
	if v, ok := nodeConfig["local_nvme_ssd_block_config"]; ok && len(v.([]interface{})) > 0 {
		conf := v.([]interface{})[0].(map[string]interface{})
		nc.LocalNvmeSsdBlockConfig = &container.LocalNvmeSsdBlockConfig{
			LocalSsdCount: int64(conf["local_ssd_count"].(int)),
		}
	}
```
we also need to remove the flag here

2023-03-15 16:57 UTC, shuyama1 commented
/gcbrun

2023-03-15 17:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 467 insertions(+), 60 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7427-old..auto-pr-7427) ( 5 files changed, 468 insertions(+), 62 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7427-old..auto-pr-7427) ( 2 files changed, 63 insertions(+), 53 deletions(-))

2023-03-15 18:01 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2501` 
Passed tests `2237` 
Skipped tests: `263` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-15 18:01 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/ab401031-ea21-406f-8639-cb6800fb149b/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/ab401031-ea21-406f-8639-cb6800fb149b/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/ab401031-ea21-406f-8639-cb6800fb149b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7427/artifacts/ab401031-ea21-406f-8639-cb6800fb149b/recording) for each test

2023-03-15 20:42 UTC, shuyama1 commented
GA test passed: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/383064

2023-03-15 20:42 UTC, shuyama1 approved these changes
LGTM!

2023-03-15 20:43 UTC, merged