Adding IAM resources for Dataplex Lake, Zone and Asset
GoogleCloudPlatform/magic-modules pull request #7436
Opened 2023-03-09 23:11 UTC by dbjnbnrj

Adding get/setIAMPolicy support for Dataplex Lake, Zone and Asset
Lake, Zone and Asset resources were generated via DCL. Followed guide https://googlecloudplatform.github.io/magic-modules/docs/how-to/add-mmv1-iam/#adding-iam-support-to-nonexistent-resources to add the IAM resources.
(part of https://github.com/hashicorp/terraform-provider-google/issues/11648)

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
`google_dataplex_lake_iam_binding`
`google_dataplex_zone_iam_binding`
`google_dataplex_asset_iam_binding`
```

2023-03-09 23:14 UTC, shuyama1 commented
@dbjnbnrj Thanks for making the PR. Would you mind rebasing your PR to kick in a recent CI change? Thanks

2023-03-10 22:26 UTC, shuyama1 commented
/gcbrun

2023-03-10 22:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7436-old..auto-pr-7436) ( 12 files changed, 2311 insertions(+), 2 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7436-old..auto-pr-7436) ( 11 files changed, 1109 insertions(+), 3 deletions(-))

2023-03-10 23:35 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2505` 
Passed tests `2220` 
Skipped tests: `262` 
Affected tests: `23` 

#### Action taken 
<details> <summary>Found 23 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate|TestAccDataplexZoneIamPolicyGenerated|TestAccDataplexLakeIamBindingGenerated|TestAccDataplexZoneIamMemberGenerated|TestAccDataplexZoneIamBindingGenerated|TestAccDataplexLakeIamPolicyGenerated|TestAccDataplexAssetIamPolicyGenerated|TestAccDataplexLakeIamMemberGenerated|TestAccDataplexAssetIamMemberGenerated|TestAccDataplexAssetIamBindingGenerated|TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccPrivatecaCertificate_privatecaCertificateUpdate|TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample|TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample|TestAccPrivatecaCertificate_privatecaCertificateCsrExample|TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample|TestAccPrivatecaCertificate_privatecaCertificateConfigExample|TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState|TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample|TestAccPrivatecaCaPool_updateCaOption|TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline|TestAccPrivatecaCaPool_privatecaCapoolUpdate|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-10 23:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityUpdate.log)]
`TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataSourcePrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificate_privatecaCertificateUpdate.log)]
`TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificate_privatecaCertificateNoAuthorityExample.log)]
`TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCaPool_privatecaCapoolAllFieldsExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateCsrExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificate_privatecaCertificateCsrExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificate_privatecaCertificateWithTemplateExample.log)]
`TestAccPrivatecaCertificate_privatecaCertificateConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificate_privatecaCertificateConfigExample.log)]
`TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificateAuthority_rootCaManageDesiredState.log)]
`TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityBasicExample.log)]
`TestAccPrivatecaCaPool_updateCaOption`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCaPool_updateCaOption.log)]
`TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCaPool_privatecaCapoolEmptyBaseline.log)]
`TestAccPrivatecaCaPool_privatecaCapoolUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccPrivatecaCaPool_privatecaCapoolUpdate.log)] 

Tests failed during RECORDING mode:
 `TestAccDataplexZoneIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexZoneIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexZoneIamPolicyGenerated.log)]
`TestAccDataplexLakeIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexLakeIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexLakeIamBindingGenerated.log)]
`TestAccDataplexZoneIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexZoneIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexZoneIamMemberGenerated.log)]
`TestAccDataplexZoneIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexZoneIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexZoneIamBindingGenerated.log)]
`TestAccDataplexLakeIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexLakeIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexLakeIamPolicyGenerated.log)]
`TestAccDataplexAssetIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexAssetIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexAssetIamPolicyGenerated.log)]
`TestAccDataplexLakeIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexLakeIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexLakeIamMemberGenerated.log)]
`TestAccDataplexAssetIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexAssetIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexAssetIamMemberGenerated.log)]
`TestAccDataplexAssetIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataplexAssetIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/recording/TestAccDataplexAssetIamBindingGenerated.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/3e930349-1802-44be-a62e-83c4e7b8ad46/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://st [...]

2023-03-11 16:42 UTC, dbjnbnrj commented
Hi @shuyama1, 

Can you help me debug the VCRTest run? I'm unusure what the root cause is and my local runs have been successful - 

```
        Error: Error setting IAM policy for dataplex zone "projects/ci-test-project-188019/locations/us-central1/lakes/tf-test-lakeesn7g39rdj/zones/tf-test-zoneesn7g39rdj": Post "projects/ci-test-project-188019/locations/us-central1/lakes/tf-test-lakeesn7g39rdj/zones/tf-test-zoneesn7g39rdj:setIamPolicy?alt=json": unsupported protocol scheme ""
```

2023-03-15 00:03 UTC, shuyama1 reviewed
Would you mind splitting the `api.yaml file` into individual file for each resource. Sorry we recently did the file split and now product level file `api.yaml` should no longer be added

2023-03-15 19:48 UTC, dbjnbnrj commented on tpgtools/overrides/dataplex/tpgtools_product.yaml
> +## product level overrides
Thanks for the suggestion. Updated this.

2023-03-15 20:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7436-old..auto-pr-7436) ( 11 files changed, 1109 insertions(+), 3 deletions(-))

2023-03-15 21:25 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2509` 
Passed tests `2234` 
Skipped tests: `263` 
Affected tests: `12` 

#### Action taken 
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccComposerEnvironment_withEncryptionConfigComposer1|TestAccDataplexAssetIamPolicyGenerated|TestAccDataplexZoneIamBindingGenerated|TestAccDataplexZoneIamPolicyGenerated|TestAccDataplexAssetIamMemberGenerated|TestAccDataplexAssetIamBindingGenerated|TestAccDataplexZoneIamMemberGenerated|TestAccDataplexLakeIamPolicyGenerated|TestAccDataplexLakeIamMemberGenerated|TestAccDataplexLakeIamBindingGenerated|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-15 22:11 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComposerEnvironment_withEncryptionConfigComposer1`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccComposerEnvironment_withEncryptionConfigComposer1.log)]
`TestAccDataplexAssetIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexAssetIamPolicyGenerated.log)]
`TestAccDataplexZoneIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexZoneIamBindingGenerated.log)]
`TestAccDataplexZoneIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexZoneIamPolicyGenerated.log)]
`TestAccDataplexAssetIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexAssetIamMemberGenerated.log)]
`TestAccDataplexAssetIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexAssetIamBindingGenerated.log)]
`TestAccDataplexZoneIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexZoneIamMemberGenerated.log)]
`TestAccDataplexLakeIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexLakeIamPolicyGenerated.log)]
`TestAccDataplexLakeIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexLakeIamMemberGenerated.log)]
`TestAccDataplexLakeIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataplexLakeIamBindingGenerated.log)] 

Tests failed during RECORDING mode:
 `TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/98d8ca99-2f7d-445b-a530-36a55ac1dbaf/recording) for each test

2023-03-15 22:31 UTC, dbjnbnrj commented
Hi @shuyama1  looks like the two tests that failed are unrelated to my change
TestAccComposerEnvironment_withEncryptionConfigComposer2 
TestAccDataSourceDnsManagedZone_basic

2023-03-16 15:53 UTC, shuyama1 commented
> Hi @shuyama1 looks like the two tests that failed are unrelated to my change TestAccComposerEnvironment_withEncryptionConfigComposer2 TestAccDataSourceDnsManagedZone_basic

Those failures are unrelated. Don't worry about them! Sorry for the noise.

2023-03-16 16:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7436-old..auto-pr-7436) ( 11 files changed, 1109 insertions(+), 3 deletions(-))

2023-03-16 16:56 UTC, modular-magician commented
Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/34a1edda-5ed4-4b0a-96c5-d14417ce7e03/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/34a1edda-5ed4-4b0a-96c5-d14417ce7e03/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/34a1edda-5ed4-4b0a-96c5-d14417ce7e03/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/34a1edda-5ed4-4b0a-96c5-d14417ce7e03/recording) for each test

2023-03-16 19:36 UTC, dbjnbnrj commented
Hi @shuyama1 looks like there was one failure, merged from main. Let me know if you can help! Thanks :)

2023-03-17 17:34 UTC, dbjnbnrj commented
friendly ping @shuyama1

2023-03-17 18:45 UTC, shuyama1 commented
Thank you for the ping! Overall LGTM with only a restructure work needed! Sorry that looks like we have another provider rework PR that removed the terraform.yaml got merged recently. Would you mind copying the `iam_policy` code block from terraform.yaml to each resource.yaml file. Really apologize for the extra work. I think the PR should be good to go after. Also don't worry about the unrelated test failure. That's a known flaky test and should not block the merge of this PR.

2023-03-17 20:59 UTC, dbjnbnrj commented
> Thank you for the ping! Overall LGTM with only a restructure work needed! Sorry that looks like we have another provider rework PR that removed the terraform.yaml got merged recently. Would you mind copying the `iam_policy` code block from terraform.yaml to each resource.yaml file. Really apologize for the extra work. I think the PR should be good to go after. Also don't worry about the unrelated test failure. That's a known flaky test and should not block the merge of this PR.

Sure no worries, should I also include the iam_policy in the terraform.yaml file as well? Thanks!

2023-03-17 21:33 UTC, shuyama1 commented
> > Thank you for the ping! Overall LGTM with only a restructure work needed! Sorry that looks like we have another provider rework PR that removed the terraform.yaml got merged recently. Would you mind copying the `iam_policy` code block from terraform.yaml to each resource.yaml file. Really apologize for the extra work. I think the PR should be good to go after. Also don't worry about the unrelated test failure. That's a known flaky test and should not block the merge of this PR.
> 
> Sure no worries, should I also include the iam_policy in the terraform.yaml file as well? Thanks!

No, the terraform.yaml file should be removed. Sorry, I should've used the word `move` instead of `copy`. Sorry for the confusion

2023-03-17 22:06 UTC, dbjnbnrj commented
Thanks, removed terraform.yaml

2023-03-17 22:53 UTC, shuyama1 commented
/gcbrun

2023-03-20 03:24 UTC, dbjnbnrj commented
Hi @shuyama1 looks like workflow is waiting for approval from maintainer. Let me know if you can help

2023-03-20 19:32 UTC, shuyama1 commented
/gcbrun

2023-03-20 21:45 UTC, shuyama1 commented
/gcbrun

2023-03-20 22:04 UTC, shuyama1 commented
tests failed due to:
```
google-beta/iam_dataplex_asset.go:48:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_asset.go:61:2: lake redeclared
	google-beta/iam_dataplex_asset.go:59:2: other declaration of lake
google-beta/iam_dataplex_asset.go:110:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_asset.go:161:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:43:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_zone.go:55:2: lake redeclared
	google-beta/iam_dataplex_zone.go:54:2: other declaration of lake
google-beta/iam_dataplex_zone.go:99:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:146:7: duplicate field name lake in struct literal
make: *** [vet] Error 2
GNUmakefile:26: recipe for target 'vet' failed
make: *** No rule to make target 'tools'.  Stop.
==> Checking that code complies with gofmt requirements...
go vet
# github.com/hashicorp/terraform-provider-google-beta/google-beta
google-beta/iam_dataplex_asset.go:48:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_asset.go:61:2: lake redeclared
	google-beta/iam_dataplex_asset.go:59:2: other declaration of lake
google-beta/iam_dataplex_asset.go:110:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_asset.go:161:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:43:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_zone.go:55:2: lake redeclared
	google-beta/iam_dataplex_zone.go:54:2: other declaration of lake
google-beta/iam_dataplex_zone.go:99:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:146:7: duplicate field name lake in struct literal
make: *** [vet] Error 2
GNUmakefile:26: recipe for target 'vet' failed
==> Checking that code complies with gofmt requirements...
go vet
# github.com/hashicorp/terraform-provider-google-beta/google-beta
google-beta/iam_dataplex_asset.go:48:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_asset.go:61:2: lake redeclared
	google-beta/iam_dataplex_asset.go:59:2: other declaration of lake
google-beta/iam_dataplex_asset.go:110:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_asset.go:161:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:43:2: duplicate key "lake" in map literal
google-beta/iam_dataplex_zone.go:55:2: lake redeclared
	google-beta/iam_dataplex_zone.go:54:2: other declaration of lake
google-beta/iam_dataplex_zone.go:99:7: duplicate field name lake in struct literal
google-beta/iam_dataplex_zone.go:146:7: duplicate field name lake in struct literal
GNUmakefile:26: recipe for target 'vet' failed
make: *** [vet] Error 2
```

Looking into the issue

2023-03-20 22:10 UTC, shuyama1 requested changes

2023-03-20 22:10 UTC, shuyama1 commented on mmv1/products/dataplex/Zone.yaml
> +  import_format: ["projects/{{project}}/locations/{{location}}/lakes/{{name}}", "{{name}}"]
Also here

2023-03-20 22:11 UTC, shuyama1 commented
Looks like you've already resolved it. Thanks for the quick fix.
/gcbrun

2023-03-20 22:25 UTC, dbjnbnrj commented
Unsure why this is still failing, think the issue should be resolved now. Is the diff by any chance picking up the previous version?

2023-03-20 22:38 UTC, shuyama1 commented
Looks like the provider tests passed which means the issue should be resolved, but the validator tests failed. Let me rerun the tests and also I'll grab someone who knows the validator better to take a look.
/gcbrun

2023-03-20 23:22 UTC, shuyama1 commented
/gcbrun

2023-03-20 23:38 UTC, shuyama1 commented
Looks like it got past the previous failure point.

Thanks for taking a look @melinath!

2023-03-20 23:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7436-old..auto-pr-7436) ( 13 files changed, 2311 insertions(+), 14 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7436-old..auto-pr-7436) ( 11 files changed, 1109 insertions(+), 3 deletions(-))

2023-03-21 00:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2513` 
Passed tests `2247` 
Skipped tests: `263` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccLoggingBucketConfigProject_analyticsEnabled|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-21 00:31 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccLoggingBucketConfigProject_analyticsEnabled`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/recording/TestAccLoggingBucketConfigProject_analyticsEnabled.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7436/artifacts/96ee3138-efc0-442e-8178-e32749839ffc/recording) for each test

2023-03-21 00:51 UTC, shuyama1 approved these changes
Thank you!

2023-03-21 00:52 UTC, merged

2023-03-21 02:53 UTC, dbjnbnrj commented
Thank you so much for your help @shuyama1!! Thanks @melinath for helping with the failures :D