fix(tfv): Fix missing zone in compute instance
GoogleCloudPlatform/magic-modules pull request #7466
Opened 2023-03-16 16:20 UTC by iyabchen

For compute instance resource, the zone field is not converted. 

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-03-16 16:21 UTC, iyabchen commented
/gcbrun

2023-03-16 19:01 UTC, melinath commented
/gcbrun

2023-03-16 20:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2501` 
Passed tests `2235` 
Skipped tests: `263` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-16 20:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/recording/TestAccFirebaserulesRelease_BasicRelease.log)] 

Tests failed during RECORDING mode:
 `TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/build-log/recording_build/TestAccComposerEnvironment_withEncryptionConfigComposer2_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/c4110f01-36d3-4878-bd75-b04c08676225/recording) for each test

2023-03-17 18:02 UTC, melinath commented
this is the flipside of https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/816

2023-03-21 19:02 UTC, roaks3 commented
/gcbrun

2023-03-21 19:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7466-old..auto-pr-7466) ( 2 files changed, 6 insertions(+), 3 deletions(-))

2023-03-21 20:06 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2517` 
Passed tests `2251` 
Skipped tests: `263` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceDnsManagedZone_basic|TestAccComposerEnvironment_withEncryptionConfigComposer2|TestAccNetworkServicesGateway_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-21 20:35 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComposerEnvironment_withEncryptionConfigComposer2`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/recording/TestAccComposerEnvironment_withEncryptionConfigComposer2.log)]
`TestAccNetworkServicesGateway_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/recording/TestAccNetworkServicesGateway_update.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/bb144b4b-f442-42b9-bb06-187363ecfc99/recording) for each test

2023-03-21 20:47 UTC, roaks3 approved these changes
LGTM

2023-03-21 20:49 UTC, roaks3 requested changes
Whoops, I approved that too quickly after only looking at the code and VCR. It looks like there are still errors with the validator tests.

2023-03-21 20:54 UTC, iyabchen commented
The log does not tell which test it is failing?

2023-03-21 21:08 UTC, roaks3 commented
Here's what I'm seeing (in case you don't have access): https://paste.googleplex.com/6671133569974272

2023-03-22 00:04 UTC, roaks3 commented
/gcbrun

2023-03-22 00:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7466-old..auto-pr-7466) ( 5 files changed, 12 insertions(+), 6 deletions(-))

2023-03-22 01:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2517` 
Passed tests `2252` 
Skipped tests: `263` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccNetworkServicesGateway_update|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-22 01:09 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccNetworkServicesGateway_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/719b8fce-8e64-4520-b933-3cc793813ce2/recording/TestAccNetworkServicesGateway_update.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/719b8fce-8e64-4520-b933-3cc793813ce2/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/719b8fce-8e64-4520-b933-3cc793813ce2/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/719b8fce-8e64-4520-b933-3cc793813ce2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/719b8fce-8e64-4520-b933-3cc793813ce2/recording) for each test

2023-03-22 14:42 UTC, iyabchen commented
/gcbrun

2023-03-22 16:14 UTC, roaks3 commented
/gcbrun

2023-03-22 17:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2521` 
Passed tests `2254` 
Skipped tests: `264` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccNetworkServicesGateway_update|TestAccDataSourceDnsManagedZone_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-03-22 17:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccNetworkServicesGateway_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/recording/TestAccNetworkServicesGateway_update.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceDnsManagedZone_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/build-log/recording_build/TestAccDataSourceDnsManagedZone_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/recording/TestAccDataSourceDnsManagedZone_basic.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7466/artifacts/a4e04d75-e3ee-442a-a387-2b4e35944a58/recording) for each test

2023-03-22 18:13 UTC, iyabchen commented
/gcbrun

2023-03-22 18:16 UTC, roaks3 commented
/gcbrun

2023-03-22 18:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7466-old..auto-pr-7466) ( 7 files changed, 16 insertions(+), 8 deletions(-))

2023-03-22 20:27 UTC, iyabchen commented
The tests finally passed, thanks a lot for rerunning!

2023-03-22 20:56 UTC, roaks3 approved these changes
No problem, all looks good to me now!

2023-03-22 22:34 UTC, roaks3 commented
Just want to confirm, is this change good to be merged now?

2023-03-22 23:00 UTC, iyabchen commented
Yes, as long as the tests pass, there should be no issues to merge.

2023-03-22 23:16 UTC, merged