Compute forwarding rule mmv1
GoogleCloudPlatform/magic-modules pull request #7625
Opened 2023-04-04 20:46 UTC by trodge

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

2023-04-04 21:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change(s) Detected
The following breaking change(s) were detected within your pull request.

* Field `label_fingerprint` within resource `google_compute_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `label_fingerprint` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `labels` within resource `google_compute_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `labels` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `network` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `psc_connection_id` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `psc_connection_status` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `service_directory_registrations.namespace` transitioned from optional+computed to optional `google_compute_forwarding_rule` - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#field-oc-to-c)


If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 1434 insertions(+), 830 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 1703 insertions(+), 805 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-04 22:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2550` 
Passed tests `2229` 
Skipped tests: `275` 
Affected tests: `46` 

#### Action taken 
<details> <summary>Found 46 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDNSRecordSet_routingPolicy|TestAccComputeVpnTunnel_defaultTrafficSelectors|TestAccComputeVpnTunnel_regionFromGateway|TestAccComputeVpnTunnel_vpnTunnelBetaExample|TestAccComputeVpnTunnel_vpnTunnelBasicExample|TestAccComputeVpnGateway_targetVpnGatewayBasicExample|TestAccComputeRoute_routeIlbVipExample|TestAccComputeRoute_routeIlbExample|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupPscServiceAttachmentExample|TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample|TestAccComputeRouterInterface_basic|TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate|TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample|TestAccComputeGlobalForwardingRule_updateTarget|TestAccComputeServiceAttachment_serviceAttachmentBasicExample|TestAccComputePacketMirroring_computePacketMirroringFullExample|TestAccComputeForwardingRule_forwardingRuleBasicExample|TestAccComputeForwardingRule_forwardingRuleGlobalInternallbExample|TestAccComputeForwardingRule_forwardingRuleExternallbExample|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample|TestAccComputeGlobalForwardingRule_privateServiceConnectGoogleApisExample|TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleHybridExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleExternalManagedExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample|TestAccComputeGlobalForwardingRule_globalForwardingRuleHttpExample|TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample|TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample|TestAccComputeForwardingRule_serviceDirectoryRegistrations|TestAccComputeForwardingRule_networkTier|TestAccComputeForwardingRule_ip|TestAccComputeForwardingRule_update|TestAccComputeForwardingRule_forwardingRuleVpcPscExample|TestAccComputeForwardingRule_forwardingRuleRegionalHttpXlbExample|TestAccComputeForwardingRule_forwardingRuleHttpLbExample|TestAccComputeBackendBucket_externalCdnLbWithBackendBucketExample|TestAccComputeForwardingRule_forwardingRuleInternallbExample|TestAccComputeForwardingRule_forwardingRuleL3DefaultExample|TestAccComputeGlobalForwardingRule_internalLoadBalancing|TestAccComputeGlobalForwardingRule_labels|TestAccComputeGlobalForwardingRule_ipv6|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example|TestAccDataSourceGoogleGlobalForwardingRule|TestAccDataSourceGoogleForwardingRule|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-04 22:22 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDNSRecordSet_routingPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccDNSRecordSet_routingPolicy.log)]
`TestAccComputeVpnTunnel_defaultTrafficSelectors`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeVpnTunnel_defaultTrafficSelectors.log)]
`TestAccComputeVpnTunnel_regionFromGateway`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeVpnTunnel_regionFromGateway.log)]
`TestAccComputeVpnTunnel_vpnTunnelBetaExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeVpnTunnel_vpnTunnelBetaExample.log)]
`TestAccComputeVpnTunnel_vpnTunnelBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeVpnTunnel_vpnTunnelBasicExample.log)]
`TestAccComputeVpnGateway_targetVpnGatewayBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeVpnGateway_targetVpnGatewayBasicExample.log)]
`TestAccComputeRoute_routeIlbVipExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeRoute_routeIlbVipExample.log)]
`TestAccComputeRoute_routeIlbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeRoute_routeIlbExample.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupPscServiceAttachmentExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupPscServiceAttachmentExample.log)]
`TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeManagedSslCertificate_managedSslCertificateBasicExample.log)]
`TestAccComputeRouterInterface_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeRouterInterface_basic.log)]
`TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeServiceAttachment_serviceAttachmentBasicExampleUpdate.log)]
`TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeServiceAttachment_serviceAttachmentExplicitProjectsExample.log)]
`TestAccComputeGlobalForwardingRule_updateTarget`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_updateTarget.log)]
`TestAccComputeServiceAttachment_serviceAttachmentBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeServiceAttachment_serviceAttachmentBasicExample.log)]
`TestAccComputePacketMirroring_computePacketMirroringFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputePacketMirroring_computePacketMirroringFullExample.log)]
`TestAccComputeForwardingRule_forwardingRuleBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_forwardingRuleBasicExample.log)]
`TestAccComputeForwardingRule_forwardingRuleGlobalInternallbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_forwardingRuleGlobalInternallbExample.log)]
`TestAccComputeForwardingRule_forwardingRuleExternallbExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_forwardingRuleExternallbExample.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_privateServiceConnectGoogleApisExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_privateServiceConnectGoogleApisExample.log)]
`TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_internalHttpLbWithMigBackendExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleHybridExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleHybridExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleExternalManagedExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleExternalManagedExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleInternalExample.log)]
`TestAccComputeGlobalForwardingRule_globalForwardingRuleHttpExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_globalForwardingRuleHttpExample.log)]
`TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample.log)]
`TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample.log)]
`TestAccComputeForwardingRule_serviceDirectoryRegistrations`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/156ed6cb-f529-4163-8e06-318283dfa0f3/recording/TestAccComputeForwardingRule_serviceDirectoryRegistrations.log)]
`TestAccComputeForwardingRule_networkTier`[[Debug log](https://storage.cloud.google.com/ci-vcr-l [...]

2023-04-05 20:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change(s) Detected
The following breaking change(s) were detected within your pull request.

* Field `label_fingerprint` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `labels` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `network` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `psc_connection_id` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `psc_connection_status` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)


If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 1556 insertions(+), 823 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 1705 insertions(+), 807 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 3 files changed, 30 insertions(+), 3 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 3 files changed, 30 insertions(+), 3 deletions(-))

2023-04-05 21:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2559` 
Passed tests `2280` 
Skipped tests: `275` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-05 21:23 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/recording/TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/498acd5e-e590-47fc-93f7-cda5d2ef44ce/recording) for each test

2023-04-05 21:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 1731 insertions(+), 804 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 6 files changed, 1728 insertions(+), 801 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))

2023-04-05 22:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2559` 
Passed tests `2280` 
Skipped tests: `275` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccFirebaserulesRelease_BasicRelease|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-05 23:02 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/recording/TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d59978c5-df05-4881-85d7-7bfbe0b992e1/recording) for each test

2023-04-06 01:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 1789 insertions(+), 823 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 6 files changed, 1786 insertions(+), 820 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))

2023-04-06 02:07 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2559` 
Passed tests `2280` 
Skipped tests: `275` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-06 02:21 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/recording/TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/3ef16df4-a924-44c7-b8e6-f588f7788968/recording) for each test

2023-04-07 21:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 2100 insertions(+), 951 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 6 files changed, 2097 insertions(+), 948 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))

2023-04-07 22:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2562` 
Passed tests `2283` 
Skipped tests: `275` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-07 22:50 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/recording/TestAccApigeeEnvKeystoreAliasPkcs12_apigeeEnvKeystoreAliasPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/31c1ad43-e119-48a3-b61c-db3847d5bcb0/recording) for each test

2023-04-14 23:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 2157 insertions(+), 958 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 2182 insertions(+), 959 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 1 file changed, 8 insertions(+), 7 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_forwarding_rule` (36 total tests)
Untested fields: `source_ip_ranges`

Please add acceptance tests which include these fields.

2023-04-15 00:35 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2622` 
Passed tests `2341` 
Skipped tests: `277` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_forwardingRuleVpcPscExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-15 00:49 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeForwardingRule_forwardingRuleVpcPscExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/recording/TestAccComputeForwardingRule_forwardingRuleVpcPscExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/7c27afc7-0819-4249-8942-ac5bd7eb3c65/recording) for each test

2023-04-17 21:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2254 insertions(+), 962 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 7 files changed, 2279 insertions(+), 967 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 137 insertions(+), 11 deletions(-))

2023-04-17 22:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2626` 
Passed tests `2332` 
Skipped tests: `277` 
Affected tests: `17` 

#### Action taken 
<details> <summary>Found 17 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccSqlDatabaseInstance_activationPolicy|TestAccSqlDatabaseInstance_updateReadReplicaWithBinaryLogEnabled|TestAccSqlDatabaseInstance_settings_basic|TestAccSqlDatabaseInstance_authNets|TestAccSqlDatabaseInstance_settingsDowngrade|TestAccSqlDatabaseInstance_settings_deletionProtectionEnabled|TestAccSqlDatabaseInstance_PointInTimeRecoveryEnabled|TestAccSqlDatabaseInstance_basic_with_user_labels|TestAccSqlDatabaseInstance_settings_deletionProtection|TestAccSqlDatabaseInstance_settings_upgrade|TestAccSqlDatabaseInstance_settings_secondary|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-17 23:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2528 insertions(+), 963 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2490 insertions(+), 969 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 138 insertions(+), 12 deletions(-))

2023-04-18 00:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2633` 
Passed tests `2347` 
Skipped tests: `277` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExampleUpdate|TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate|TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExample|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-18 01:00 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExampleUpdate.log)]
`TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccComputeForwardingRule_forwardingRuleRegionalSteeringExample.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccAlloydbCluster_missingLocation.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/build-log/recording_build/TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording/TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/65e2d8cd-bc99-490d-9845-7103a8ed1e70/recording) for each test

2023-04-18 21:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2528 insertions(+), 963 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2490 insertions(+), 969 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 138 insertions(+), 12 deletions(-))

2023-04-18 22:50 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2632` 
Passed tests `2348` 
Skipped tests: `277` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccTPUNode_tpuNodeFullExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-19 17:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2636` 
Passed tests `2340` 
Skipped tests: `277` 
Affected tests: `19` 

#### Action taken 
<details> <summary>Found 19 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSqlDatabaseInstance_activationPolicy|TestAccFirebaserulesRelease_BasicRelease|TestAccComputeRouterInterface_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccAlloydbBackup_missingLocation|TestAccSqlDatabaseInstance_settings_deletionProtection|TestAccSqlDatabaseInstance_settings_secondary|TestAccSqlDatabaseInstance_settings_basic|TestAccSqlDatabaseInstance_authNets|TestAccSqlDatabaseInstance_PointInTimeRecoveryEnabled|TestAccSqlDatabaseInstance_settingsDowngrade|TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange|TestAccSqlDatabaseInstance_settings_deletionProtectionEnabled|TestAccDataSourceAlloydbLocations_basic|TestAccSqlDatabaseInstance_basic_with_user_labels|TestAccSqlDatabaseInstance_settings_upgrade </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-19 17:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2386 insertions(+), 963 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2490 insertions(+), 969 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 5 files changed, 138 insertions(+), 12 deletions(-))

2023-04-19 18:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2643` 
Passed tests `2357` 
Skipped tests: `277` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccComputeRouterInterface_basic|TestAccAlloydbCluster_missingLocation|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-19 19:07 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccComputeRouterInterface_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccComputeRouterInterface_basic.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/build-log/recording_build/TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording/TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/889c94e2-ea00-42b2-94b4-3763e6bb64c0/recording) for each test

2023-04-20 21:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change(s) Detected
The following breaking change(s) were detected within your pull request.

* Field `base_forwarding_rule` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)
* Field `source_ip_ranges` within resource `google_compute_global_forwarding_rule` was either removed or renamed - [reference](https://github.com/hashicorp/terraform-provider-google-beta/blob/main/.github/BREAKING_CHANGES.md#resource-schema-field-removal-or-rename)


If you believe this detection to be incorrect please raise the concern with your reviewer. If you intend to make this change you will need to wait for a [major release](https://www.terraform.io/plugin/sdkv2/best-practices/versioning#example-major-number-increments) window. An `override-breaking-change` label can be added to allow merging.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2351 insertions(+), 1029 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2446 insertions(+), 1096 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 85 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 25 insertions(+), 43 deletions(-))

2023-04-20 21:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Affected tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/849b3490-d846-4364-9aa2-07e82c05b926/build-log/replaying_test.log)

2023-04-20 22:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2391 insertions(+), 1025 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2476 insertions(+), 1088 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 95 insertions(+), 4 deletions(-))
TF Validator: [Diff](https://github.com/modular-magician/terraform-validator/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 75 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 25 insertions(+), 43 deletions(-))

2023-04-20 23:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2649` 
Passed tests `2366` 
Skipped tests: `277` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbBackup_missingLocation|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-20 23:29 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/4e1051e0-3177-46b3-ac95-e1c6f54957c9/recording) for each test

2023-04-26 23:53 UTC, slevenick requested changes
I'm seeing a permadiff when using this example: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#example-usage---internal-tcp-udp-lb-with-mig-backend

and trying to update allow_global_access
```
# forwarding rule
resource "google_compute_forwarding_rule" "google_compute_forwarding_rule" {
  name                  = "l4-ilb-forwarding-rule"
  backend_service       = google_compute_region_backend_service.default.id
  provider              = google-beta
  region                = "europe-west1"
  ip_protocol           = "TCP"
  load_balancing_scheme = "INTERNAL"
  all_ports             = true
  allow_global_access   = true
  network               = google_compute_network.ilb_network.id
  subnetwork            = google_compute_subnetwork.ilb_subnet.id
}
```
to 
```
# forwarding rule
resource "google_compute_forwarding_rule" "google_compute_forwarding_rule" {
  name                  = "l4-ilb-forwarding-rule"
  backend_service       = google_compute_region_backend_service.default.id
  provider              = google-beta
  region                = "europe-west1"
  ip_protocol           = "TCP"
  load_balancing_scheme = "INTERNAL"
  all_ports             = true
  allow_global_access   = false
  network               = google_compute_network.ilb_network.id
  subnetwork            = google_compute_subnetwork.ilb_subnet.id
}
```

2023-04-27 17:33 UTC, trodge commented
> I'm seeing a permadiff when using this example: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_forwarding_rule#example-usage---internal-tcp-udp-lb-with-mig-backend
> 
> and trying to update allow_global_access
> 
> ```
> # forwarding rule
> resource "google_compute_forwarding_rule" "google_compute_forwarding_rule" {
>   name                  = "l4-ilb-forwarding-rule"
>   backend_service       = google_compute_region_backend_service.default.id
>   provider              = google-beta
>   region                = "europe-west1"
>   ip_protocol           = "TCP"
>   load_balancing_scheme = "INTERNAL"
>   all_ports             = true
>   allow_global_access   = true
>   network               = google_compute_network.ilb_network.id
>   subnetwork            = google_compute_subnetwork.ilb_subnet.id
> }
> ```
> 
> to
> 
> ```
> # forwarding rule
> resource "google_compute_forwarding_rule" "google_compute_forwarding_rule" {
>   name                  = "l4-ilb-forwarding-rule"
>   backend_service       = google_compute_region_backend_service.default.id
>   provider              = google-beta
>   region                = "europe-west1"
>   ip_protocol           = "TCP"
>   load_balancing_scheme = "INTERNAL"
>   all_ports             = true
>   allow_global_access   = false
>   network               = google_compute_network.ilb_network.id
>   subnetwork            = google_compute_subnetwork.ilb_subnet.id
> }
> ```

Are you sure you weren't testing with the current provider rather than the one with this PR applied? The current provider will have a permadiff with this update but after the migration that should be fixed. I've added a test to demonstrate.

2023-04-27 17:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2608 insertions(+), 1029 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2693 insertions(+), 1092 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 92 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 25 insertions(+), 43 deletions(-))

2023-04-27 18:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2692` 
Passed tests `2405` 
Skipped tests: `279` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccFirebaserulesRelease_BasicRelease|TestAccDataSourceAlloydbLocations_basic|TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-27 18:54 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccComputeForwardingRule_internalTcpUdpLbWithMigBackendExampleUpdate.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccAlloydbCluster_missingLocation.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/cbae98ea-bf84-4875-9b74-2491df8aa63d/recording) for each test

2023-04-28 19:24 UTC, slevenick approved these changes
You're right I was using the DCL-based version. Glad this is getting fixed!

2023-04-28 22:09 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2598 insertions(+), 1023 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2683 insertions(+), 1086 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 92 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 25 insertions(+), 43 deletions(-))

2023-04-28 22:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7625-old..auto-pr-7625) ( 9 files changed, 2381 insertions(+), 1023 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7625-old..auto-pr-7625) ( 8 files changed, 2683 insertions(+), 1086 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7625-old..auto-pr-7625) ( 4 files changed, 92 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7625-old..auto-pr-7625) ( 2 files changed, 25 insertions(+), 43 deletions(-))

2023-04-28 23:25 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2696` 
Passed tests `2403` 
Skipped tests: `279` 
Affected tests: `14` 

#### Action taken 
<details> <summary>Found 14 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2JobIamMemberGenerated|TestAccCloudRunV2JobIamBindingGenerated|TestAccCloudRunV2JobIamPolicyGenerated|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic|TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate|TestAccCloudRunV2Job_cloudrunv2JobFullUpdate|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccCloudRunV2Job_cloudrunv2JobBasicExample|TestAccCloudRunV2Job_cloudrunv2JobSqlExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-28 23:43 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccCloudRunV2JobIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2JobIamMemberGenerated.log)]
`TestAccCloudRunV2JobIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2JobIamBindingGenerated.log)]
`TestAccCloudRunV2JobIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2JobIamPolicyGenerated.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccComputeForwardingRule_forwardingRuleVpcPscExampleUpdate.log)]
`TestAccCloudRunV2Job_cloudrunv2JobFullUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2Job_cloudrunv2JobVpcaccessExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccCloudRunV2Job_cloudrunv2JobBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2Job_cloudrunv2JobBasicExample.log)]
`TestAccCloudRunV2Job_cloudrunv2JobSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording/TestAccCloudRunV2Job_cloudrunv2JobSqlExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7625/artifacts/d6abca1d-13ea-4502-b987-8ae6e1bf23e7/recording) for each test

2023-05-01 17:12 UTC, merged