Added a new datasource for fetching the available alloydb locations
GoogleCloudPlatform/magic-modules pull request #7678
Opened 2023-04-10 12:56 UTC by ravisiddhu

This PR is for https://github.com/hashicorp/terraform-provider-google/issues/13812

A new datasource `google_alloydb_locations` for fetching the details of available alloydb locations. It receives `project`  as arguments and returns the details of all the available alloydb locations.

I have added documentation and tested this new data source with unit tests.

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

```release-note:new-datasource
A new datasource for fetching the details of available alloydb locations.
```

2023-04-10 13:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7678-old..auto-pr-7678) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-10 14:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2563` 
Passed tests `2284` 
Skipped tests: `275` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-10 14:14 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/3e1a2eb4-f558-4e8d-8a70-c6fd885a2b49/recording) for each test

2023-04-11 19:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7678-old..auto-pr-7678) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-11 20:38 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c5e2d848-249a-4eb1-9afa-3dcfce8a018c/recording) for each test

2023-04-12 03:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7678-old..auto-pr-7678) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-12 04:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2610` 
Passed tests `2328` 
Skipped tests: `277` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-12 04:42 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/cfc1bacf-665a-4691-88cf-2bbcdf8dcc6b/recording) for each test

2023-04-17 20:05 UTC, NickElliot requested changes

2023-04-18 05:59 UTC, ravisiddhu commented on mmv1/third_party/terraform/website/docs/d/alloydb_locations.html.markdown
> +Use this data source to get information about the available locations.
Done.

2023-04-18 06:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 254 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7678-old..auto-pr-7678) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-18 07:05 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2631` 
Passed tests `2348` 
Skipped tests: `277` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbCluster_missingLocation|TestAccAlloydbBackup_missingLocation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-18 07:19 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording/TestAccAlloydbBackup_missingLocation.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/200ffdf2-5d2f-4d97-8086-ea2d61f2f86c/recording) for each test

2023-04-18 17:13 UTC, NickElliot commented
LGTM! @zli82016 for final review

2023-04-18 17:21 UTC, zli82016 commented on mmv1/third_party/terraform/data_sources/data_source_alloydb_locations.go
> +	log.Printf("[ERROR] kanthara url : %s", url)
Is this log required?

2023-04-18 18:05 UTC, zli82016 commented
Overall LTGM.

2023-04-18 18:09 UTC, zli82016 approved these changes

2023-04-18 19:18 UTC, NickElliot approved these changes

2023-04-19 00:58 UTC, ravisiddhu commented on mmv1/third_party/terraform/data_sources/data_source_alloydb_locations.go
> +	log.Printf("[ERROR] kanthara url : %s", url)
It is not needed, I have removed it.

2023-04-19 01:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 252 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7678-old..auto-pr-7678) ( 4 files changed, 252 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7678-old..auto-pr-7678) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-19 02:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2630` 
Passed tests `2346` 
Skipped tests: `277` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic|TestAccTPUNode_tpuNodeFullExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-19 02:26 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccTPUNode_tpuNodeFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording/TestAccTPUNode_tpuNodeFullExample.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7678/artifacts/c64be452-e9cd-4560-b3b6-d5c13b16092d/recording) for each test

2023-04-19 15:10 UTC, merged