Add lifecycle hook and updated samples for firebaserules_release
GoogleCloudPlatform/magic-modules pull request #7779
Opened 2023-04-20 17:17 UTC by rainshen49

Update samples for Firebase Security Rules to address https://github.com/hashicorp/terraform-provider-google/issues/13235

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
Only test and documentation change
```

2023-04-20 17:18 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-04-20 18:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 56 insertions(+), 192 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 358 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-20 18:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2640` 
Passed tests `2355` 
Skipped tests: `277` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_update|TestAccCloudRunV2Service_cloudrunv2ServiceFullUpdate|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-20 21:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 53 insertions(+), 189 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 358 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-20 21:56 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2645` 
Passed tests `2361` 
Skipped tests: `277` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccComputeForwardingRule_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-20 22:10 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording/TestAccComputeForwardingRule_update.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/73198879-7f56-4278-a6a9-5db8a8b26257/recording) for each test

2023-04-24 10:15 UTC, shuyama1 commented
Sorry, I didn't have to time to review this last Friday. Reassigning a new reviewer as I'll be out for ~2 weeks. Thanks @ScottSuarez!

2023-04-26 19:27 UTC, ScottSuarez requested changes

2023-04-26 19:44 UTC, rainshen49 commented on output.log
Oops. Done.

2023-04-26 22:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 53 insertions(+), 189 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 359 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-26 23:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2686` 
Passed tests `2401` 
Skipped tests: `279` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccAlloydbCluster_missingLocation|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-27 00:01 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/51448c15-cfa1-4415-9138-726b568de93a/recording) for each test

2023-05-01 14:34 UTC, rainshen49 commented
Ping @ScottSuarez this is ready for review!

2023-05-01 21:01 UTC, ScottSuarez commented
Could join the GoogleCloudOrganization so our CI can detect you? Join [GoogleCloudPlatform org](https://github.com/GoogleCloudPlatform) through go/github/orgs

[github.com/orgs/GoogleCloudPlatform/people?query=rainshen49](https://github.com/orgs/GoogleCloudPlatform/people?query=rainshen49)

2023-05-01 21:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 53 insertions(+), 189 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 361 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-01 22:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2698` 
Passed tests `2411` 
Skipped tests: `279` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_update|TestAccBigQueryDataTable_bigtable|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-01 22:24 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeForwardingRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccComputeForwardingRule_update.log)]
`TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccBigQueryDataTable_bigtable.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/6368524b-2f6d-441c-9cf4-36f2fde45291/recording) for each test

2023-05-02 00:33 UTC, ScottSuarez commented
Looks like in the generated diff the samples are getting completely deleted.

https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779

I'm guessing this is because you relocated the samples to the release subdirectory. Wondering what the intention is there?

2023-05-03 14:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 93 insertions(+), 75 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 93 insertions(+), 75 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-03 15:03 UTC, rainshen49 commented
🤔 That wasn't intentional. Is it better now?

2023-05-03 15:56 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2709` 
Passed tests `2418` 
Skipped tests: `279` 
Affected tests: `12` 

#### Action taken 
<details> <summary>Found 12 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_StorageReleaseHandWritten|TestAccFirebaserulesRelease_FirestoreReleaseHandWritten|TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten|TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten|TestAccComputeFirewallPolicyRule_update|TestAccComputeFirewallPolicyRule_multipleRules|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-03 16:09 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccComputeRegionNetworkFirewallPolicyRule_RegionalHandWritten.log)]
`TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccComputeNetworkFirewallPolicyRule_GlobalHandWritten.log)]
`TestAccComputeFirewallPolicyRule_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccComputeFirewallPolicyRule_update.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccFirebaserulesRelease_StorageReleaseHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/build-log/recording_build/TestAccFirebaserulesRelease_StorageReleaseHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccFirebaserulesRelease_StorageReleaseHandWritten.log)]
`TestAccFirebaserulesRelease_FirestoreReleaseHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/build-log/recording_build/TestAccFirebaserulesRelease_FirestoreReleaseHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccFirebaserulesRelease_FirestoreReleaseHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/50bf45b2-9e17-46b2-8491-db62a245ae30/recording) for each test

2023-05-03 21:02 UTC, ScottSuarez commented
Looks like they weren't running before and are now thanks to 

https://github.com/GoogleCloudPlatform/magic-modules/pull/7779/commits/687743aaaafb331c7071b0003c74abd9fe1a99d3

Running them is the right move.. The error is because our version of terraform doesn't support this hook.
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/containers/gcb-terraform-vcr-tester/Dockerfile#L15-L16

`replace_triggered_by` was introduced in `1.2.

2023-05-03 21:09 UTC, rainshen49 commented
Why are tests in 1.1.8 when the latest version is 1.4.6? I also found that the registry documentation says we work with Terraform 0.13+ https://registry.terraform.io/providers/hashicorp/google-beta/latest 🤦 , so I'm absolutely clueless here.

2023-05-03 21:11 UTC, ScottSuarez commented
> Why are tests in 1.1.8 when the latest version is 1.4.6? I also found that the registry documentation says we work with Terraform 0.13+ [registry.terraform.io/providers/hashicorp/google-beta/latest](https://registry.terraform.io/providers/hashicorp/google-beta/latest) 🤦 , so I'm absolutely clueless here.

Upgrading the terraform version in our repository is a significant effort. Tests can fail due to changes in terraform core. Could you omit usage of `replace_triggered_by` ? Is there an alternative behavior recommended?

2023-05-03 21:17 UTC, rainshen49 commented
tl;dr: we've tried many things in https://github.com/hashicorp/terraform-provider-google/issues/13235, and `replace_triggered_by` was the only solution that doesn't require any manual steps or breaking change in the provider.

The alternative is to make ruleset_name an immutable field, thus forcing a replacement, but this is worse because
1. It's a breaking change
2. It isn't how the underlying API works. The underlying API allows updates, and some users still want that behavior.

2023-05-08 20:59 UTC, rainshen49 commented
Done. I'd like to get rid of this tech debt when the version gets upgraded since the tests run are not exactly the same as the docs. Is there a way to add this item to the list of things to track for an upcoming upgrade?

On a separate note, what's the established schedule for updating the Terraform binary in tests? 1.1.8 feels quite far from 1.4.6. If the tests break as a result of the upgrade, doesn't that mean users out there are viewing outdated/non-functional samples?

2023-05-08 21:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 82 insertions(+), 71 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 82 insertions(+), 71 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-08 22:08 UTC, ScottSuarez commented
After talking with our team, could you revert to your previous state of change. I'm going to update our internal version to 1.2.5

2023-05-08 22:18 UTC, ScottSuarez commented
https://github.com/GoogleCloudPlatform/magic-modules/pull/7899

2023-05-08 22:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2719` 
Passed tests `2431` 
Skipped tests: `279` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_StorageReleaseTestHandWritten|TestAccFirebaserulesRelease_FirestoreReleaseTestHandWritten|TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccAlloydbBackup_missingLocation|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-08 22:28 UTC, ScottSuarez commented
okay ! checked in. Could you force-push us back to`687743aaaafb331c7071b0003c74abd9fe1a99d3` ?

2023-05-08 22:32 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_StorageReleaseTestHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccFirebaserulesRelease_StorageReleaseTestHandWritten.log)]
`TestAccFirebaserulesRelease_FirestoreReleaseTestHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccFirebaserulesRelease_FirestoreReleaseTestHandWritten.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/72058f36-22a7-43ff-be27-78b89e5b9703/recording) for each test

2023-05-09 13:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 93 insertions(+), 75 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 93 insertions(+), 75 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7779-old..auto-pr-7779) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-09 14:23 UTC, rainshen49 commented
OK, done. Thanks for updating!

2023-05-09 14:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2719` 
Passed tests `2431` 
Skipped tests: `279` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_StorageReleaseHandWritten|TestAccFirebaserulesRelease_FirestoreReleaseHandWritten|TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-09 14:54 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_StorageReleaseHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccFirebaserulesRelease_StorageReleaseHandWritten.log)]
`TestAccFirebaserulesRelease_FirestoreReleaseHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccFirebaserulesRelease_FirestoreReleaseHandWritten.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7779/artifacts/9e56c209-4414-4a17-ba70-4e98b27d0f20/recording) for each test

2023-05-09 18:57 UTC, ScottSuarez approved these changes

2023-05-09 18:57 UTC, merged