tgc build on tpg-beta
GoogleCloudPlatform/magic-modules pull request #7797
Opened 2023-04-21 14:29 UTC by iyabchen

terraform-google-conversion switch to tpg beta

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-04-28 20:49 UTC, melinath reviewed
could you pull the formatting changes into a separate PR?

2023-06-15 22:43 UTC, melinath commented
allowed ci runs /gcbrun

2023-06-16 00:15 UTC, melinath requested changes
I think you might need to make additional changes as described in b/275715832

2023-06-23 17:45 UTC, melinath requested changes
could you split the downstream-builder changes into a separate PR & also make changes to https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/gcb-push-downstream.yml to use beta for TGC

2023-06-28 16:37 UTC, melinath commented
/gcbrun

2023-06-29 15:35 UTC, iyabchen commented
tgc-base fails because HEAD~ is still ga, not beta. Not sure how to make this work? @melinath

2023-07-12 23:18 UTC, melinath commented
testing this will be tricky since it modifies so many files. We'll need to test thoroughly to make sure everything works in the downstream code. I'm seeing some errors when I generate based on this (and switch over to beta) - is everything working fine for you?

2023-07-14 17:51 UTC, melinath commented on .ci/gcb-generate-diffs-new.yml
> -          - 'ga'
we should temporarily switch this to GA so that the tests can run (even though they'll fail)

2023-07-14 18:43 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7797-old..auto-pr-7797) ( 209 files changed, 19437 insertions(+), 284 deletions(-))

2023-07-14 20:25 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2854` 
Passed tests `2555` 
Skipped tests: `297` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-14 20:28 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7797/artifacts/986be140-cdd7-40bb-b138-9fc010c742f7/recording) for each test

2023-07-14 21:04 UTC, melinath requested changes
This looks good - my one concern is that it will break older PRs, since the generation will happen with GA set as the version (but downstream uses beta). However, the code that's used for the generation will all be based on the head of the main branch.

In terms of how to work around this - my initial thought is that we could alter the downstream image to always use beta and then deal with any fallout in the ten minutes it takes the image to rebuild manually.

What do you think?

2023-07-20 17:32 UTC, melinath commented
@iyabchen could you resolve the conflicts

2023-07-20 21:46 UTC, melinath approved these changes

2023-07-20 21:46 UTC, merged