fix(dataproc_cluster): dataproc cluster nil pointer access when using custom gke cluster
GoogleCloudPlatform/magic-modules pull request #7811
Opened 2023-04-22 21:41 UTC by srevinsaju

while configuring a custom GKE cluster using virtual_cluster_config and kubernetes_cluster_config, gke_cluster_config is defined to be optional on the terraform docs, but panics with segmentation error while trying to access properties on undefined gkeClusterConfig. this has been solved by adding a safe check to the flatten function to check if the gke cluster config has been passed by the user

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
dataproc: fixes nil pointer exception while using custom kubernetes cluster
```

2023-04-22 21:41 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-04-24 19:45 UTC, srevinsaju commented
g'day! let me know if I need to make any changes on this, thanks! cc @melinath

2023-04-28 18:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7811-old..auto-pr-7811) ( 1 file changed, 6 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7811-old..auto-pr-7811) ( 1 file changed, 6 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7811-old..auto-pr-7811) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-28 18:42 UTC, melinath reviewed
It looks like we have a test called [TestAccDataprocVirtualCluster_basic](https://github.com/hashicorp/terraform-provider-google/blob/7d2f95669ad0db1fca79c388bfc88c53762f7098/google/resource_dataproc_cluster_test.go#L219) that covers exactly the case describe in this PR: configuring a dataproc cluster with virtual_cluster_config.kubernetes_cluster_config.gke_cluster_config, and leaving cluster_config.gce_cluster_config unspecified.

That test is currently passing in our nightly builds.

Additionally, the proposed change is to a flatten function, which is used to convert an API response to the corresponding Terraform resource data structure - so it would change the behavior based on what the API returns, not what the user provides.

I don't see a corresponding issue related to this problem in our issue tracker. Could you share a configuration that would trigger this bug - or better yet, file a [bug ticket](https://github.com/hashicorp/terraform-provider-google/issues/new/choose) with full details - so that I can confirm the fix?

2023-04-28 19:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2693` 
Passed tests `2407` 
Skipped tests: `279` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbCluster_missingLocation|TestAccDataSourceAlloydbLocations_basic|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-28 19:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7811/artifacts/3c1cdfe2-eecf-4ebf-80fc-4d732e93f786/recording) for each test

2023-04-29 06:54 UTC, srevinsaju commented
@melinath, thanks for looking into this PR. I have created https://github.com/hashicorp/terraform-provider-google/issues/14457

2023-05-04 23:21 UTC, melinath requested changes
I believe the issue is actually at https://github.com/hashicorp/terraform-provider-google/blob/main/google/resource_dataproc_cluster.go#L2091 - the object returned by the client library is not a nil pointer, so it tries to get processed. We (ideally) wouldn't even be trying to process it. Fixing that processing to not error would suppress the error, but it wouldn't fix the problem completely; if this PR is merged, the VirtualClusterConfig returned by the API would still not be getting flattened, which should result in the Terraform state for `virtual_cluster_config` not being updated properly.

In addition to fixing the code to properly decide which struct to flatten & store in state, you'll need to update the tests to make sure that this field is actually being handled properly. Since the tests are handwritten you may want to take a look at https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/teststep

2023-05-04 23:36 UTC, melinath commented
Actually after thinking about this some more, I'm not sure how we would make sure we're testing for this case since I'm still not sure why it's failing in the first place. :-/ I'll look into it some more - let me know if you have any ideas about that.

2023-05-05 18:54 UTC, melinath commented
(marking as review requested so that I don't forget to look into the test issue, but the requested changes still hold :-) )

2023-05-08 15:42 UTC, srevinsaju commented
@melinath thanks for looking at this, I did some deeper debugging, but there are some parts which I am going off track:
* `cluster.Config.SoftwareConfig` in my case was not `null`
* Similarly `cluster.Config.WorkerConfig = &dataproc.InstanceGroupConfig` was set in the code, and some other examples as well

Maybe `cluster.Config` could never be null. Nevertheless, functions like `flattenInstanceGroupConfig` and a few other flatten functions check if the values is null before flattening. Probably I'm on the wrong track :(

2023-05-08 17:03 UTC, melinath commented
@srevinsaju here's the [`spew`](https://github.com/davecgh/go-spew) dump of cluster.Config I see:

```
(*dataproc.ClusterConfig)(0xc0006ac1e0)({
 AutoscalingConfig: (*dataproc.AutoscalingConfig)(<nil>),
 AuxiliaryNodeGroups: ([]*dataproc.AuxiliaryNodeGroup) <nil>,
 ConfigBucket: (string) "",
 DataprocMetricConfig: (*dataproc.DataprocMetricConfig)(<nil>),
 EncryptionConfig: (*dataproc.EncryptionConfig)(<nil>),
 EndpointConfig: (*dataproc.EndpointConfig)(<nil>),
 GceClusterConfig: (*dataproc.GceClusterConfig)(<nil>),
 GkeClusterConfig: (*dataproc.GkeClusterConfig)(<nil>),
 InitializationActions: ([]*dataproc.NodeInitializationAction) <nil>,
 LifecycleConfig: (*dataproc.LifecycleConfig)(<nil>),
 MasterConfig: (*dataproc.InstanceGroupConfig)(<nil>),
 MetastoreConfig: (*dataproc.MetastoreConfig)(<nil>),
 SecondaryWorkerConfig: (*dataproc.InstanceGroupConfig)(<nil>),
 SecurityConfig: (*dataproc.SecurityConfig)(<nil>),
 SoftwareConfig: (*dataproc.SoftwareConfig)(0xc0023712c0)({
  ImageVersion: (string) "",
  OptionalComponents: ([]string) <nil>,
  Properties: (map[string]string) <nil>,
  ForceSendFields: ([]string) <nil>,
  NullFields: ([]string) <nil>
 }),
 TempBucket: (string) "",
 WorkerConfig: (*dataproc.InstanceGroupConfig)(<nil>),
 ForceSendFields: ([]string) <nil>,
 NullFields: ([]string) <nil>
})
```

So although SoftwareConfig isn't null, it also doesn't contain any meaningful values. Any chance that's the case for you as well?

> Nevertheless, functions like flattenInstanceGroupConfig and a few other flatten functions check if the values is null before flattening.

yes, that may work in some cases - for example, in the output above, `WorkerConfig` is a nil pointer to an InstanceGroupConfig. That might be a valid state _even if_ the user is using cluster.Config instead of cluster.VirtualClusterConfig

However, even though cluster.Config is essentially "empty", it's not a nil pointer, so checking if `cluster.Config != nil` is not a useful check.

---

The flipside of this is that because the `cluster.Config != nil` block is getting run, the `else` block, which is actually _supposed_ to be getting run, is not. So the flattening of `cluster.VirtualClusterConfig` _never happens_ - we're essentially ignoring values returned by the API, which means that we can't do things like detect drift between the TF config and the API on those fields.

2023-05-08 17:21 UTC, srevinsaju commented
Ahh, makes sense. I missed the expanded view of `SoftwareConfig`, and you are right. I will get to debugging this. Thanks for the pointer.

2023-05-26 15:43 UTC, melinath commented
For my own reference: b/282232967 (I'm having some trouble reproducing things locally :-/ but that isn't necessarily a blocker for a fix.)

@srevinsaju as a heads up it looks like there are some merge conflicts that you'll need to address as well.

2023-06-12 16:33 UTC, melinath commented
Closing this PR for now since the issue has been resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7917 as far as I can tell.

2023-06-12 16:33 UTC, closed without merging

2023-06-12 16:58 UTC, srevinsaju commented
Thank you!