Create draft to run tpg unit tests in github actions
GoogleCloudPlatform/magic-modules pull request #7837
Opened 2023-04-26 20:46 UTC by ScottSuarez

This is a test to see whether its possible to trigger unit and build tests directly on github ui... More work to follow after sequential testing is done

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-04-28 18:08 UTC, melinath requested changes
This looks pretty sweet. I have a couple small change requests; could you also go through go/github-actions and go/github-docs/security-recommendations to double-check that we're following any applicable recommendations?

2023-04-28 18:08 UTC, melinath commented on .github/workflows/test-tpg.yml
> +name: Build and Unit Test GA Provider
go/github-docs/security-recommendations#toolssettings-9

```suggestion
name: Build and Unit Test GA Provider

permissions: read-all
```

2023-05-02 18:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-05-02 19:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2706` 
Passed tests `2421` 
Skipped tests: `279` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-02 19:31 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7837/artifacts/3e709f39-1b82-42af-8d98-f14f126821ff/recording) for each test

2023-05-02 21:28 UTC, ScottSuarez commented
@melinath I've reviewed the policies and see no blockers from the links. There are some best practices I'll implement in the future, but I don't want to invest more energy in this at the moment since its simply a POC. I am not sure if it will even work and it needs further testing to validate the UX

2023-05-02 21:54 UTC, melinath approved these changes

2023-05-03 00:16 UTC, merged