Migrate os config os policy assignment to handwritten
GoogleCloudPlatform/magic-modules pull request #7842
Opened 2023-04-27 18:11 UTC by trodge

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-04-27 18:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4686 insertions(+), 3205 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 8 files changed, 4684 insertions(+), 3280 deletions(-))

2023-04-27 18:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4672 insertions(+), 3205 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 8 files changed, 4670 insertions(+), 3280 deletions(-))

2023-04-27 19:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4671 insertions(+), 3204 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 8 files changed, 4670 insertions(+), 3280 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7842-old..auto-pr-7842) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-04-27 20:29 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2689` 
Passed tests `2403` 
Skipped tests: `279` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccOSConfigOSPolicyAssignment_basic|TestAccAlloydbBackup_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-04-27 20:42 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccOSConfigOSPolicyAssignment_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccOSConfigOSPolicyAssignment_basic.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/618d2b38-d635-40f5-adfa-d973ea234466/recording) for each test

2023-05-02 19:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4671 insertions(+), 3204 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 8 files changed, 4670 insertions(+), 3281 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7842-old..auto-pr-7842) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-02 19:58 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2706` 
Passed tests `2420` 
Skipped tests: `279` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFirebaserulesRelease_BasicRelease|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-02 20:11 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccFirebaserulesRelease_BasicRelease`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccFirebaserulesRelease_BasicRelease.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

All tests passed
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/7cb8f4b7-9657-4b0b-9578-2f2467e2e490/recording) for each test

2023-05-15 22:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4668 insertions(+), 3202 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4667 insertions(+), 3206 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7842-old..auto-pr-7842) ( 472 files changed, 15510 insertions(+), 17468 deletions(-))

2023-05-15 22:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Affected tests: `0` 

Errors occurred during REPLAYING mode. Please fix them to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/81fc08de-9af0-4c66-913c-4e9f3358d6df/build-log/replaying_test.log)

2023-05-24 00:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4709 insertions(+), 3200 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4708 insertions(+), 3204 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7842-old..auto-pr-7842) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-05-24 01:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2747` 
Passed tests `2457` 
Skipped tests: `283` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeFirewallPolicyRule_multipleRules|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-24 01:28 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/1423b3c4-01e9-4b5a-bcd6-0f64ee8c703f/recording) for each test

2023-06-08 18:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2781` 
Passed tests `2482` 
Skipped tests: `292` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccLoggingBucketConfigProject_cmekSettings|TestAccBigQueryDataTable_bigtable|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccComputeFirewallPolicyRule_multipleRules|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-08 18:58 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccLoggingBucketConfigProject_cmekSettings`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccLoggingBucketConfigProject_cmekSettings.log)]
`TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccBigQueryDataTable_bigtable.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/5d6d8896-91b4-4c29-a72e-657692cbe4db/recording) for each test

2023-06-08 22:15 UTC, c2thorn requested changes
couple of

2023-06-21 23:53 UTC, trodge commented on mmv1/third_party/terraform/resources/resource_os_config_os_policy_assignment.go
> +							ValidateFunc: validateEnum([]string{"MODE_UNSPECIFIED", "VALIDATION", "ENFORCEMENT"}),
The enums were being validated internally in the DCL.

2023-06-21 23:54 UTC, trodge commented on mmv1/third_party/terraform/resources/resource_os_config_os_policy_assignment.go
> +				ForceNew: true,
This diff suppress func was not actually responsible for that behavior. The DCL was simply truncating long form project ids before constructing urls. I have added similar functionality to this handwritten resource, but we may need to add functionality to the generator in order to handle mmv1-based migrations.

2023-06-22 17:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4744 insertions(+), 3203 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7842-old..auto-pr-7842) ( 7 files changed, 4743 insertions(+), 3207 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7842-old..auto-pr-7842) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-22 19:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2810` 
Passed tests `2507` 
Skipped tests: `301` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeNetworkEndpoints_networkEndpointsBasic|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-22 19:27 UTC, c2thorn approved these changes

2023-06-22 19:41 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeNetworkEndpoints_networkEndpointsBasic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/fe393a3b-200f-44c3-856d-1fec19ce3d08/recording/TestAccComputeNetworkEndpoints_networkEndpointsBasic.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/fe393a3b-200f-44c3-856d-1fec19ce3d08/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/fe393a3b-200f-44c3-856d-1fec19ce3d08/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/fe393a3b-200f-44c3-856d-1fec19ce3d08/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-7842/artifacts/fe393a3b-200f-44c3-856d-1fec19ce3d08/recording) for each test

2023-06-23 02:28 UTC, merged