feat: add IAM resources for Vertex AI Endpoints
GoogleCloudPlatform/magic-modules pull request #7965
Opened 2023-05-17 09:49 UTC by browningjp-datatonic

Fixes https://github.com/hashicorp/terraform-provider-google/issues/14630

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
vertexai: Added IAM resources for google_vertex_ai_endpoint
```

2023-05-17 09:50 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-05-19 18:00 UTC, browningjp-datatonic commented
hi @slevenick! I have now run the unit tests for `vertexai` and `make lint` successfully. Not sure what acceptance tests to run - are there specific ones to check for new IAM resources? Thanks

2023-08-02 10:20 UTC, browningjp-datatonic commented
@slevenick would you be able to take a look at this?

2023-08-02 15:28 UTC, slevenick commented
Sorry I must have missed this originally. Can you rebase this from current main? Our CI is having trouble running it as it's too old

2023-08-02 15:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7965-old..auto-pr-7965) ( 3 files changed, 219 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7965-old..auto-pr-7965) ( 4 files changed, 468 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7965-old..auto-pr-7965) ( 5 files changed, 377 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_endpoint_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  endpoint = # value needed
  location = # value needed
  members  = # value needed
  role     = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  endpoint = # value needed
  location = # value needed
  member   = # value needed
  role     = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_policy" "primary" {
  endpoint    = # value needed
  location    = # value needed
  policy_data = # value needed
}

```

2023-08-02 15:58 UTC, slevenick commented
Tests seem not to be generating. Looks like it's because we skip the only test in the vertex AI endpoints resource.

Can we unmark the test as skip_test to see if that will generate the IAM resource tests?

2023-08-02 17:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2917` 
Passed tests `2615` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7965/artifacts/f86744dd-de80-4789-ae64-76290a3a70f2/build-log/replaying_test.log)

2023-08-04 12:05 UTC, browningjp-datatonic commented
@slevenick done!

2023-08-04 22:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7965-old..auto-pr-7965) ( 5 files changed, 367 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7965-old..auto-pr-7965) ( 7 files changed, 1037 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7965-old..auto-pr-7965) ( 5 files changed, 377 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-7965-old..auto-pr-7965) ( 1 file changed, 2 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_endpoint_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  location = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  location = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_policy` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_policy" "primary" {
  location = # value needed
}

```

2023-08-04 22:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `13` 
Passed tests `13` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-7965/artifacts/5f975aae-3931-45e9-95c9-36dc7621d093/build-log/replaying_test.log)

2023-08-04 23:00 UTC, slevenick commented
/gcbrun
Huh... I'm not super sure why this failed

I'll try kicking it off again

2023-08-04 23:03 UTC, slevenick commented
Oh no, I see it: 

google/resource_vertex_ai_endpoint_test.go:150:6: testAccCheckVertexAIEndpointDestroyProducer redeclared in this block

We may need to go back to skipping the test and hand-writing a test for the IAM resources specifically. You can use the generated test in the previous diff as a starting place for that, because it should do all of what we need

2023-08-09 10:58 UTC, browningjp-datatonic commented
@slevenick is this what you had in mind for the handwritten test?

2023-08-16 13:43 UTC, browningjp-datatonic commented
@slevenick is anything more needed for this PR?

2023-08-16 14:11 UTC, slevenick requested changes
Sorry, there were some folder changes recently, you may need to rebase and move the handwritten file.

CONFLICT (file location): mmv1/third_party/terraform/tests/iam_vertex_endpoint_test.go.erb added in head/feat/vertex_endpoint_iam inside a directory that was renamed in HEAD, suggesting it should perhaps be moved to mmv1/third_party/terraform/services/compute/iam_vertex_endpoint_test.go.erb.

2023-08-16 14:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7965-old..auto-pr-7965) ( 4 files changed, 232 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7965-old..auto-pr-7965) ( 5 files changed, 874 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7965-old..auto-pr-7965) ( 3 files changed, 374 insertions(+))

2023-08-16 21:46 UTC, slevenick requested changes

2023-08-16 21:46 UTC, slevenick commented on mmv1/third_party/terraform/services/vertexai/iam_vertex_endpoint_test.go.erb
> +package google
I think the package is different now to match vertexai

2023-08-17 13:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-7965-old..auto-pr-7965) ( 4 files changed, 232 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-7965-old..auto-pr-7965) ( 5 files changed, 874 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-7965-old..auto-pr-7965) ( 3 files changed, 374 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_endpoint_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  location = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  location = # value needed
}

```
Resource: `google_vertex_ai_endpoint_iam_policy` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_endpoint_iam_policy" "primary" {
  location = # value needed
}

```

2024-05-29 15:25 UTC, closed without merging