Added info_type_transformations field in record_transformations to the google_data_loss_prevention_deidentify_template resource
GoogleCloudPlatform/magic-modules pull request #8035
Opened 2023-05-30 05:36 UTC by abheda-crest

Added `info_type_transformations` block in `record_transformations` field to the `google_data_loss_prevention_deidentify_template` resource.
fixes https://github.com/hashicorp/terraform-provider-google/issues/9836

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dlp: added `info_type_transformations` block in the `record_transformations` field to `google_data_loss_prevention_deidentify_template` resource.
```

2023-05-30 05:37 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @NickElliot, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-05-30 21:53 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2761` 
Passed tests `2469` 
Skipped tests: `283` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBillingSubaccount_basic|TestAccBillingSubaccount_renameOnDestroy|TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-30 22:06 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccBillingSubaccount_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/build-log/recording_build/TestAccBillingSubaccount_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccBillingSubaccount_basic.log)]
`TestAccBillingSubaccount_renameOnDestroy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/build-log/recording_build/TestAccBillingSubaccount_renameOnDestroy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccBillingSubaccount_renameOnDestroy.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/007c7a97-8287-40f7-8d4c-edaaf694fce5/recording) for each test

2023-05-31 17:36 UTC, NickElliot submitted a review, later dismissed
From an initial passover, this is the main config change that needs to be made that I can see at this time. The extremely thorough test coverage looks good!

2023-05-31 19:08 UTC, abheda-crest commented on mmv1/products/dlp/DeidentifyTemplate.yaml
>                    description: |
I agree with the point of adding `exactly_one_of` block but the `primitiveTransformations` and `infoTypeTranformations` subfields are a part of an array field [`fieldTransformations`](https://cloud.google.com/dlp/docs/reference/rest/v2/projects.deidentifyTemplates#fieldtransformation). Currently, `ConflictsWith`, `ExactlyOneOf` or `AtLeastOneOf` are set at the attribute level, which means we can't set it on a list if we have a list of objects, and each object has a list of attributes that's `ExactlyOneOf`. We don't know the length of the list and there is no way to differentiate object[0] from object[1] with what is conflicting. Hence, the use of the above mentioned functions when the attributes are part of array won't work. The issue addressing this limitation can be found [here](https://github.com/hashicorp/terraform-plugin-sdk/issues/470).

2023-05-31 19:09 UTC, abheda-crest commented on mmv1/products/dlp/DeidentifyTemplate.yaml
> +                  description: |
Same as above.

2023-05-31 19:10 UTC, abheda-crest commented on mmv1/products/dlp/DeidentifyTemplate.yaml
>                    description: |
I've added the note to provide only one of these field in the description though.

2023-05-31 21:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2765` 
Passed tests `2473` 
Skipped tests: `283` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBillingSubaccount_basic|TestAccBillingSubaccount_renameOnDestroy|TestAccComputeFirewallPolicyRule_multipleRules|TestAccAlloydbBackup_missingLocation|TestAccAlloydbCluster_missingLocation|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-05-31 21:45 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccAlloydbBackup_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccAlloydbBackup_missingLocation.log)]
`TestAccAlloydbCluster_missingLocation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccAlloydbCluster_missingLocation.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)] 

Tests failed during RECORDING mode:
 `TestAccBillingSubaccount_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/build-log/recording_build/TestAccBillingSubaccount_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccBillingSubaccount_basic.log)]
`TestAccBillingSubaccount_renameOnDestroy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/build-log/recording_build/TestAccBillingSubaccount_renameOnDestroy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccBillingSubaccount_renameOnDestroy.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/dd678b3b-6ecc-496b-9da8-4263e0657c1b/recording) for each test

2023-06-05 08:29 UTC, abheda-crest commented
@NickElliot I've resolved the merge conflict. Could you please review this PR?

2023-06-05 20:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 14087 insertions(+), 5665 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 14087 insertions(+), 5665 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 2048 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_data_loss_prevention_deidentify_template` (48 total tests)
Untested fields: `deidentify_config.record_transformations.field_transformations.info_type_transformations.transformations.info_types.version`

Please add acceptance tests which include these fields.

2023-06-05 20:40 UTC, NickElliot commented
LGTM! to @c2thorn for final review

2023-06-05 21:31 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2778` 
Passed tests `2488` 
Skipped tests: `285` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccComputeFirewallPolicyRule_multipleRules|TestAccDataSourceAlloydbLocations_basic|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-05 21:44 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/d5f76723-f765-4934-b0cc-b023fdfb3331/recording) for each test

2023-06-05 22:09 UTC, c2thorn requested changes
have concerns about two fields

2023-06-06 06:14 UTC, abheda-crest commented on mmv1/products/dlp/DeidentifyTemplate.yaml
> +                                          description: |
Thanks for pointing that out. I've added `sensitive: true` to four `unwrapped.key` fields.

2023-06-06 06:35 UTC, abheda-crest commented on mmv1/products/dlp/DeidentifyTemplate.yaml
> +                                    such as ZIP code or credit card number. This string must have a length of 1. If not supplied, this value defaults to * for
I've added the description as per the [API docs](https://cloud.google.com/dlp/docs/reference/rest/v2/projects.deidentifyTemplates#charactermaskconfig). But, when I tried creating the resource without passing the `maskingCharacter`, the API didn't return its default value. Hence, I've not added `default_from_api: true`.
Following are the request and response of the API call:
```
POST /v2/projects/{project_id}/deidentifyTemplates?alt=json HTTP/1.1
---[ REQUEST ]---------------------------------------
{
 "deidentifyTemplate": {
  "deidentifyConfig": {
   "recordTransformations": {
    "fieldTransformations": [
     {
      "fields": [
       {
        "name": "unconditionally-char-masked-field"
       }
      ],
      "infoTypeTransformations": {
       "transformations": [
        {
         "infoTypes": [
          {
           "name": "EMAIL_ADDRESS"
          },
          {
           "name": "LAST_NAME"
          }
         ],
         "primitiveTransformation": {
          "characterMaskConfig": {
           "charactersToIgnore": [
            {
             "charactersToSkip": "-"
            }
           ],
           "numberToMask": 8,
           "reverseOrder": true
          },
          "redactConfig": null,
          "replaceWithInfoTypeConfig": null
         }
        }
       ]
      }
     }
    ],
    "recordSuppressions": [
     {
      "condition": {
       "expressions": {
        "conditions": {
         "conditions": [
          {
           "field": {
            "name": "field3"
           },
           "operator": "EQUAL_TO",
           "value": {
            "stringValue": "FOO-BAR"
           }
          },
          {
           "field": {
            "name": "field2"
           },
           "operator": "EQUAL_TO",
           "value": {
            "stringValue": "foobar"
           }
          },
          {
           "field": {
            "name": "field1"
           },
           "operator": "EQUAL_TO",
           "value": {
            "stringValue": "fizzbuzz"
           }
          }
         ]
        },
        "logicalOperator": "AND"
       }
      }
     }
    ]
   }
  },
  "description": "Description",
  "displayName": "Displayname"
 }
}
```
```
---[ RESPONSE ]--------------------------------------
{
  "name": "projects/{project_id}/deidentifyTemplates/1539292205506838093",
  "displayName": "Displayname",
  "description": "Description",
  "createTime": "2023-06-06T05:23:19.684737Z",
  "updateTime": "2023-06-06T05:23:19.684737Z",
  "deidentifyConfig": {
    "recordTransformations": {
      "fieldTransformations": [
        {
          "fields": [
            {
              "name": "unconditionally-char-masked-field"
            }
          ],
          "infoTypeTransformations": {
            "transformations": [
              {
                "infoTypes": [
                  {
                    "name": "EMAIL_ADDRESS"
                  },
                  {
                    "name": "LAST_NAME"
                  }
                ],
                "primitiveTransformation": {
                  "characterMaskConfig": {
                    "numberToMask": 8,
                    "reverseOrder": true,
                    "charactersToIgnore": [
                      {
                        "charactersToSkip": "-"
                      }
                    ]
                  }
                }
              }
            ]
          }
        }
      ],
      "recordSuppressions": [
        {
          "condition": {
            "expressions": {
              "logicalOperator": "AND",
              "conditions": {
                "conditions": [
                  {
                    "field": {
                      "name": "field3"
                    },
                    "operator": "EQUAL_TO",
                    "value": {
                      "stringValue": "FOO-BAR"
                    }
                  },
                  {
                    "field": {
                      "name": "field2"
                    },
                    "operator": "EQUAL_TO",
                    "value": {
                      "stringValue": "foobar"
                    }
                  },
                  {
                    "field": {
                      "name": "field1"
                    },
                    "operator": "EQUAL_TO",
                    "value": {
                      "stringValue": "fizzbuzz"
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
```

2023-06-06 16:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 14105 insertions(+), 5665 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 14105 insertions(+), 5665 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8035-old..auto-pr-8035) ( 3 files changed, 2048 insertions(+), 3 deletions(-))

2023-06-06 17:07 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2781` 
Passed tests `2491` 
Skipped tests: `285` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataSourceAlloydbLocations_basic|TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-06 17:20 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording/TestAccDataSourceAlloydbLocations_basic.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8035/artifacts/5c29389f-98cc-4182-8ec3-6ceab22db84c/recording) for each test

2023-06-06 18:17 UTC, c2thorn commented
Running tests in our CI

2023-06-06 19:13 UTC, c2thorn approved these changes

2023-06-06 19:15 UTC, merged