added cryptoHashConfig to deidentifyTemplate
GoogleCloudPlatform/magic-modules pull request #8084
Opened 2023-06-05 09:41 UTC by JayS-crest

added `crypto_hash_config` to `primitive_transformation` in `info_type_transformation` for resource `google_data_loss_prevention_deidentify_template`

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
dlp: added `crypto_hash_config` to `google_data_loss_prevention_deidentify_template`
```

2023-06-05 09:42 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @melinath, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-06-05 22:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 468 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 468 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 142 insertions(+), 3 deletions(-))

2023-06-05 23:39 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2770` 
Passed tests `2479` 
Skipped tests: `285` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations|TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-05 23:52 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/build-log/recording_build/TestAccDataSourceGoogleFirebaseAndroidAppConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/addbf25b-5f03-434f-8342-eb5f6de72f2d/recording) for each test

2023-06-06 06:08 UTC, JayS-crest commented
I've checked the `pre-build-validation` failure, and that is due to several files. Checking the logs, I've found `Deidentify.yaml` has one error of trailing spaces from already available code. I've removed that and I guess the `pre-build-validation` won't have issues due to this resource file.

2023-06-06 16:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 468 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 468 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 142 insertions(+), 3 deletions(-))

2023-06-06 17:06 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2774` 
Passed tests `2484` 
Skipped tests: `285` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeFirewallPolicyRule_multipleRules|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccDataSourceAlloydbLocations_basic|TestAccDataSourceGoogleFirebaseAndroidAppConfig </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-07 18:07 UTC, melinath requested changes
LGTM overall - it looks like the lint errors in the DeidentifyTemplate.yaml file might be resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/8098 so you could rebase after that's merged to see if it helps.

2023-06-07 18:07 UTC, melinath commented on mmv1/third_party/terraform/tests/resource_data_loss_prevention_deidentify_template_test.go
> +                key = "VVdWVWFGZHRXbkUwZERkM0lYb2xRdz09"
Just want to double-check that this & the transformation below are intentionally not changing the values?

2023-06-08 13:20 UTC, JayS-crest commented
I've updated the tests and rebased as well so I guess the linting error will be resolved.

2023-06-08 21:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 435 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 435 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8084-old..auto-pr-8084) ( 3 files changed, 142 insertions(+), 3 deletions(-))

2023-06-08 22:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2780` 
Passed tests `2482` 
Skipped tests: `292` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations|TestAccComputeFirewallPolicyRule_multipleRules|TestAccDataSourceGoogleFirebaseAndroidAppConfig|TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example|TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample|TestAccDataSourceAlloydbLocations_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-08 22:37 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccDataLossPreventionDeidentifyTemplate_dlpDeidentifyTemplate_infoTypeTransformations_primitiveTransformations.log)]
`TestAccDataSourceGoogleFirebaseAndroidAppConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccDataSourceGoogleFirebaseAndroidAppConfig.log)]
`TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccApigeeKeystoresAliasesPkcs12_ApigeeKeystoresAliasesPkcs12Example.log)]
`TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccApigeeKeystoresAliasesKeyCertFile_apigeeKeystoresAliasesKeyCertFileTestExample.log)]
`TestAccDataSourceAlloydbLocations_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccDataSourceAlloydbLocations_basic.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8084/artifacts/02a4a682-5de8-4b30-8af0-2ccf359d1a53/recording) for each test

2023-06-09 16:28 UTC, melinath commented on mmv1/third_party/terraform/tests/resource_data_loss_prevention_deidentify_template_test.go
> +                key = "VVdWVWFGZHRXbkUwZERkM0lYb2xRdz09"
I'm okay with merging this as-is, just wanted to make sure it's intentional. Note that this means that we're not specifically testing that this field being updated works, but we still have good coverage overall.

2023-06-09 16:28 UTC, melinath approved these changes
LGTM - failing tests are unrelated

2023-06-09 16:28 UTC, merged