Add example of disabling fleet logging feature
GoogleCloudPlatform/magic-modules pull request #8173
Opened 2023-06-19 14:33 UTC by JeffLuoo

Add example of disabling fleet logging feature

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
gkehub: added example of disabling fleet logging feature (beta)
```

2023-06-19 14:36 UTC, courageJ approved these changes

2023-06-19 14:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 23 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 23 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-20 17:57 UTC, JeffLuoo commented
@slevenick Could you please help take a look of the PR? Thanks!

2023-06-21 17:19 UTC, slevenick requested changes

2023-06-21 17:23 UTC, JeffLuoo commented on mmv1/templates/terraform/examples/disable_fleet_observability.tf.erb
> +  project = "jeffluoo-anthos-dev"
Updated to remove the project to match with existing examples.

2023-06-21 17:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-21 18:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 59 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-21 18:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 59 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-21 20:16 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2798` 
Passed tests `2495` 
Skipped tests: `301` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeFirewallPolicyRule_multipleRules|TestAccComputeNetworkEndpoints_networkEndpointsBasic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-21 20:39 UTC, JeffLuoo commented
I didn't touch the test `TestAccComputeFirewallPolicyRule_multipleRules`, do you happen to know why does it fail on my PR? @slevenick Thanks!

2023-06-22 16:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 59 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-22 16:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8173-old..auto-pr-8173) ( 1 file changed, 22 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 59 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8173-old..auto-pr-8173) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-06-22 17:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2810` 
Passed tests `2507` 
Skipped tests: `301` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeFirewallPolicyRule_multipleRules|TestAccComputeNetworkEndpoints_networkEndpointsBasic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-22 17:29 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2810` 
Passed tests `2507` 
Skipped tests: `301` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeNetworkEndpoints_networkEndpointsBasic|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-22 17:49 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeNetworkEndpoints_networkEndpointsBasic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8173/artifacts/571c0c18-e75b-42f1-8cf4-be92b6ef3aa4/recording/TestAccComputeNetworkEndpoints_networkEndpointsBasic.log)] 

Tests failed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8173/artifacts/571c0c18-e75b-42f1-8cf4-be92b6ef3aa4/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8173/artifacts/571c0c18-e75b-42f1-8cf4-be92b6ef3aa4/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8173/artifacts/571c0c18-e75b-42f1-8cf4-be92b6ef3aa4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8173/artifacts/571c0c18-e75b-42f1-8cf4-be92b6ef3aa4/recording) for each test

2023-06-22 18:26 UTC, slevenick requested changes
Looks like this test fails. Are you able to run it yourself?

2023-06-22 18:38 UTC, slevenick commented
Oh, no I mean the test that you added. TestAccGKEHubFeature_gkehubFeatureFleetObservability seems to fail now. It's skipped in VCR so you won't see it failing, but I ran it manually

2023-06-22 18:39 UTC, slevenick requested changes
See comment, TestAccGKEHubFeature_gkehubFeatureFleetObservability is failing

2023-06-22 21:10 UTC, JeffLuoo commented
May I ask for how do you run the test locally? I initially run the same config with tf and it worked so I just copied the existing test. I then followed https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/ to run the test locally but ran into bunch of errors like I don't have the permission to update the test project. I used
```
TF_LOG=TRACE make testacc TEST=./google-beta TESTARGS='-run=TestAccGKEHubFeature_gkehubFeatureFleetObservability'
```
to run the test locally.

2023-06-22 21:28 UTC, slevenick commented
> 

Yeah, that command works to run the test locally. You need to do some environment setup first, like setting up your credentials and setting up a project with the correct APIs enabled.

2023-06-23 15:46 UTC, JeffLuoo commented
What's the error you're seeing? When I ran the test locally I'm seeing either `ALREDY_EXIST` or `NOT_FOUND` error. But using the same terraform config and use the `terraform apply` doesn't return any error.

cc: @sahsagar-google

2023-06-23 16:01 UTC, slevenick commented
The error:

```

          # google_gke_hub_feature.feature will be updated in-place
          ~ resource "google_gke_hub_feature" "feature" {
                create_time    = "2023-06-22T17:54:53.927694691Z"
                id             = "projects/tf-test-hub/locations/global/features/fleetobservability"
                labels         = {}
                location       = "global"
                name           = "fleetobservability"
                project        = "tf-test-hub"
                resource_state = [
                    {
                        has_resources = false
                        state         = "ACTIVE"
                    },
                ]
                state          = []
                update_time    = "2023-06-22T17:56:18.856728173Z"
              ~ spec {
                  ~ fleetobservability {
                      ~ logging_config {
                          + default_config {
                              + mode = "MODE_UNSPECIFIED"
                            }
                          + fleet_scope_logs_config {
                              + mode = "MODE_UNSPECIFIED"
                            }
                        }
                    }
                }
            }
```

2023-06-23 16:41 UTC, JeffLuoo commented
Thank you for the update! @slevenick but I don't see any error messages from your comment.

2023-06-23 16:43 UTC, slevenick commented
> Thank you for the update! @slevenick but I don't see any error messages from your comment.

Ah, sorry it's:
```
=== CONT  TestAccGKEHubFeature_gkehubFeatureFleetObservability
    vcr_utils.go:148: Step 7/8 error: After applying this test step, the plan was not empty.
        stdout:
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
``` 
with the above config after that.

2024-06-12 09:42 UTC, closed without merging