Add eventarc trigger missing field event_data_content_type
GoogleCloudPlatform/magic-modules pull request #8235
Opened 2023-06-29 16:58 UTC by RileyHYZ

This PR upgrades dcl version to v.1.48.0 and adds a field event_data_content_type in eventarc trigger.

fixes https://github.com/hashicorp/terraform-provider-google/issues/14597

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
eventarc: added field `event_data_content_type` to `google_eventarc_trigger`
```

2023-06-29 16:58 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-06-29 17:02 UTC, slevenick commented on tpgtools/overrides/eventarc/samples/trigger/basic_update_json.tf.tmpl
> +	}s
Typo here may cause test failures

2023-06-29 18:47 UTC, slevenick commented
Can you try pushing a new commit? This got caught in the GitHub downtime

2023-06-29 18:55 UTC, slevenick commented
/gcbrun

2023-06-29 19:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2834` 
Passed tests `2526` 
Skipped tests: `295` 
Affected tests: `13` 

#### Action taken 
<details> <summary>Found 13 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccFilestoreSnapshot_filestoreSnapshotFullExample|TestAccFilestoreSnapshot_filestoreSnapshotBasicExample|TestAccFilestoreInstance_update|TestAccFilestoreInstance_filestoreInstanceFullExample|TestAccFilestoreInstance_filestoreInstanceBasicExample|TestAccFilestoreBackup_update|TestAccFilestoreBackup_filestoreBackupBasicExample|TestAccComputeFirewallPolicyRule_multipleRules|TestAccClouddeployDeliveryPipeline_VerifyDeliveryPipeline|TestAccClouddeployDeliveryPipeline_CanaryDeliveryPipeline|TestAccClouddeployDeliveryPipeline_DeliveryPipeline|TestAccClouddeployDeliveryPipeline_CanaryrunDeliveryPipeline|TestAccClouddeployDeliveryPipeline_CanaryServiceNetworkingDeliveryPipeline </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-06-29 19:53 UTC, modular-magician commented
Several tests got terminated during RECORDING mode.
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/ed8f07ac-7f2d-4da1-b4f9-9bd8207bee65/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/ed8f07ac-7f2d-4da1-b4f9-9bd8207bee65/recording) for each test

2023-06-30 15:34 UTC, slevenick commented
/gcbrun

2023-07-10 17:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-07-10 19:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2847` 
Passed tests `2548` 
Skipped tests: `295` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-10 19:07 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample.log)]
`TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/recording/TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/24786a07-6cb3-445a-bcb0-c97cc15870d6/recording) for each test

2023-07-31 07:35 UTC, adsko commented
@slevenick @RileyHYZ Hey! Nice job with this one, but is there any update about this one? Would be nice to have it.

2023-07-31 17:34 UTC, slevenick commented
The DCL was upgraded to 1.44.0 but this field doesn't seem to be present. I'm not sure why, as it exists in the YAML file for that resource in this release: https://github.com/GoogleCloudPlatform/declarative-resource-client-library/blame/main/services/google/eventarc/trigger.yaml

2023-07-31 17:49 UTC, slevenick commented
Ah I see what happened. It's present in GA but not beta, so things are a little weird. I'll ping someone to get this resolved

2023-07-31 17:56 UTC, RileyHYZ commented
The change is intended for GA but not beta and the issue should have been resolved with dcl version>1.42.0. I'll resolve the conflict and commit again.

2023-08-04 09:01 UTC, adsko commented
@slevenick

2023-08-04 18:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8235-old..auto-pr-8235) ( 7 files changed, 102 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8235-old..auto-pr-8235) ( 9 files changed, 457 insertions(+), 60 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8235-old..auto-pr-8235) ( 2 files changed, 6 insertions(+), 6 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          canary_deployment {
            postdeploy {
              actions = # value needed
            }
            predeploy {
              actions = # value needed
            }
          }
          custom_canary_deployment {
            phase_configs {
              postdeploy {
                actions = # value needed
              }
              predeploy {
                actions = # value needed
              }
            }
          }
          runtime_config {
            kubernetes {
              gateway_service_mesh {
                route_update_wait_time = # value needed
              }
            }
          }
        }
        standard {
          postdeploy {
            actions = # value needed
          }
          predeploy {
            actions = # value needed
          }
        }
      }
    }
  }
}

```
Resource: `google_dataplex_asset` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataplex_asset" "primary" {
  resource_spec {
    read_access_mode = # value needed
  }
}

```
Resource: `google_eventarc_trigger` (4 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_eventarc_trigger" "primary" {
  event_data_content_type = # value needed
}

```

2023-08-04 18:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8235-old..auto-pr-8235) ( 7 files changed, 102 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8235-old..auto-pr-8235) ( 9 files changed, 457 insertions(+), 60 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8235-old..auto-pr-8235) ( 2 files changed, 6 insertions(+), 6 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          canary_deployment {
            postdeploy {
              actions = # value needed
            }
            predeploy {
              actions = # value needed
            }
          }
          custom_canary_deployment {
            phase_configs {
              postdeploy {
                actions = # value needed
              }
              predeploy {
                actions = # value needed
              }
            }
          }
          runtime_config {
            kubernetes {
              gateway_service_mesh {
                route_update_wait_time = # value needed
              }
            }
          }
        }
        standard {
          postdeploy {
            actions = # value needed
          }
          predeploy {
            actions = # value needed
          }
        }
      }
    }
  }
}

```
Resource: `google_dataplex_asset` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataplex_asset" "primary" {
  resource_spec {
    read_access_mode = # value needed
  }
}

```
Resource: `google_eventarc_trigger` (4 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_eventarc_trigger" "primary" {
  event_data_content_type = # value needed
}

```

2023-08-04 20:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2930` 
Passed tests `2624` 
Skipped tests: `302` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataplexAsset_BasicAssetHandWritten|TestAccDataplexAssetIamBindingGenerated|TestAccDataplexAssetIamMemberGenerated|TestAccDataplexAssetIamPolicyGenerated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-04 20:15 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccDataplexAsset_BasicAssetHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/build-log/recording_build/TestAccDataplexAsset_BasicAssetHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/recording/TestAccDataplexAsset_BasicAssetHandWritten.log)]
`TestAccDataplexAssetIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/build-log/recording_build/TestAccDataplexAssetIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/recording/TestAccDataplexAssetIamBindingGenerated.log)]
`TestAccDataplexAssetIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/build-log/recording_build/TestAccDataplexAssetIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/recording/TestAccDataplexAssetIamMemberGenerated.log)]
`TestAccDataplexAssetIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/build-log/recording_build/TestAccDataplexAssetIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/recording/TestAccDataplexAssetIamPolicyGenerated.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/d7b916e7-b1ed-490d-a66b-8fea9abd2717/recording) for each test

2023-08-04 20:18 UTC, slevenick requested changes
Looks like updating the DCL has introduced an issue in dataplex asset. Several tests are failing due to large diffs. I'll need to reach out to some people to see what is going on there

2023-08-04 21:13 UTC, NickElliot commented
Update to resolve the issue on DCL's end is in review. Apologies for the complications!

2023-08-07 16:42 UTC, NickElliot commented
The DCL issue should be resolved now with the new release.

2023-08-08 13:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8235-old..auto-pr-8235) ( 7 files changed, 102 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8235-old..auto-pr-8235) ( 9 files changed, 457 insertions(+), 60 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          canary_deployment {
            postdeploy {
              actions = # value needed
            }
            predeploy {
              actions = # value needed
            }
          }
          custom_canary_deployment {
            phase_configs {
              postdeploy {
                actions = # value needed
              }
              predeploy {
                actions = # value needed
              }
            }
          }
          runtime_config {
            kubernetes {
              gateway_service_mesh {
                route_update_wait_time = # value needed
              }
            }
          }
        }
        standard {
          postdeploy {
            actions = # value needed
          }
          predeploy {
            actions = # value needed
          }
        }
      }
    }
  }
}

```
Resource: `google_dataplex_asset` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataplex_asset" "primary" {
  resource_spec {
    read_access_mode = # value needed
  }
}

```
Resource: `google_eventarc_trigger` (4 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_eventarc_trigger" "primary" {
  event_data_content_type = # value needed
}

```

2023-08-08 15:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2936` 
Passed tests `2630` 
Skipped tests: `302` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataplexAsset_BasicAssetHandWritten|TestAccDataplexAssetIamBindingGenerated|TestAccDataplexAssetIamPolicyGenerated|TestAccDataplexAssetIamMemberGenerated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-08 15:22 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccDataplexAsset_BasicAssetHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/build-log/recording_build/TestAccDataplexAsset_BasicAssetHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/recording/TestAccDataplexAsset_BasicAssetHandWritten.log)]
`TestAccDataplexAssetIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/build-log/recording_build/TestAccDataplexAssetIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/recording/TestAccDataplexAssetIamBindingGenerated.log)]
`TestAccDataplexAssetIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/build-log/recording_build/TestAccDataplexAssetIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/recording/TestAccDataplexAssetIamPolicyGenerated.log)]
`TestAccDataplexAssetIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/build-log/recording_build/TestAccDataplexAssetIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/recording/TestAccDataplexAssetIamMemberGenerated.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/53b95a8f-20ff-455d-84b3-d64a0366b833/recording) for each test

2023-08-08 16:51 UTC, slevenick requested changes

2023-08-08 18:08 UTC, RileyHYZ commented on mmv1/third_party/terraform/go.mod.erb
> +	github.com/GoogleCloudPlatform/declarative-resource-client-library v1.47.0
Sorry I didn't see the upgraded version earlier. Just updated it in the new commit. Thanks!

2023-08-08 18:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8235-old..auto-pr-8235) ( 7 files changed, 102 insertions(+), 14 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8235-old..auto-pr-8235) ( 9 files changed, 457 insertions(+), 61 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          canary_deployment {
            postdeploy {
              actions = # value needed
            }
            predeploy {
              actions = # value needed
            }
          }
          custom_canary_deployment {
            phase_configs {
              postdeploy {
                actions = # value needed
              }
              predeploy {
                actions = # value needed
              }
            }
          }
          runtime_config {
            kubernetes {
              gateway_service_mesh {
                route_update_wait_time = # value needed
              }
            }
          }
        }
        standard {
          postdeploy {
            actions = # value needed
          }
          predeploy {
            actions = # value needed
          }
        }
      }
    }
  }
}

```
Resource: `google_dataplex_asset` (7 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_dataplex_asset" "primary" {
  resource_spec {
    read_access_mode = # value needed
  }
}

```
Resource: `google_eventarc_trigger` (4 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_eventarc_trigger" "primary" {
  event_data_content_type = # value needed
}

```

2023-08-08 19:34 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2939` 
Passed tests `2637` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8235/artifacts/88f21a3e-6314-47e2-9ef5-774357fefe57/build-log/replaying_test.log)

2023-08-08 20:29 UTC, slevenick approved these changes
Thanks!

2023-08-08 20:29 UTC, merged