Bump address group ga
GoogleCloudPlatform/magic-modules pull request #8262
Opened 2023-07-03 20:21 UTC by felipegc

fixes:
https://github.com/hashicorp/terraform-provider-google/issues/15036

Adding security_policy field in google_compute_region_backend_service resource.
Bumping network_security_address_group to G.A and related tests under tpgtools

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
Compute: added `network_security_address_group` resource(ga)
```

2023-07-03 20:21 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @ScottSuarez, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-07-05 21:18 UTC, ScottSuarez requested changes
I notice some tests in tpgtools are removed. Is there a resason for this?

2023-07-06 12:57 UTC, felipegc commented
> I notice some tests in tpgtools are removed. Is there a resason for this?

The tests were separated because address group resource was not present in G.A version yet. The difference between the tests was only the address group usage. Since it is available on both versions "beta" and "ga" I manged to "merge" the tests(which was basically adding the address group resources and fields usage alongside the other resources).

It was created different tests under tpg tools to:
a) guarantee that only on beta version the address group would be tested
b) separate the documentation and examples in beta and ga

Bumping it to GA there is no necessity to have this separation anymore.

2023-07-06 22:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8262-old..auto-pr-8262) ( 21 files changed, 1023 insertions(+), 75 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8262-old..auto-pr-8262) ( 9 files changed, 29 insertions(+), 123 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8262-old..auto-pr-8262) ( 5 files changed, 128 insertions(+), 3 deletions(-))

2023-07-06 23:58 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2843` 
Passed tests `2501` 
Skipped tests: `295` 
Affected tests: `47` 

#### Action taken 
<details> <summary>Found 47 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeRegionInstanceTemplate_primaryAliasIpRange|TestAccComputeRegionInstanceTemplate_metadata_startup_script|TestAccComputeRegionInstanceTemplate_subnet_custom|TestAccComputeRegionInstanceTemplate_subnet_auto|TestAccComputeRegionInstanceTemplate_regionDisks|TestAccComputeRegionInstanceTemplate_withScratchDisk|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccComputeRegionInstanceTemplate_with18TbScratchDisk|TestAccContainerAwsNodePool_BasicHandWritten|TestAccComputeRegionAutoscaler_regionAutoscalerBasicExample|TestAccContainerAwsCluster_BasicHandWritten|TestAccComputeRegionInstanceTemplate_minCpuPlatform|TestAccComputeRegionInstanceTemplate_guestAcceleratorSkip|TestAccComputeRegionInstanceTemplate_guestAccelerator|TestAccComputeRegionInstanceTemplate_secondaryAliasIpRange|TestAccComputeInstanceFromTemplate_overrideAttachedDisk|TestAccComputeInstanceTemplate_minCpuPlatform|TestAccComputeInstanceTemplate_guestAcceleratorSkip|TestAccComputeInstanceTemplate_guestAccelerator|TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten|TestAccComputeInstanceFromTemplate_overrideBootDisk|TestAccComputeInstanceTemplate_secondaryAliasIpRange|TestAccComputeInstanceTemplate_primaryAliasIpRange|TestAccComputeInstanceFromRegionTemplate_basic|TestAccComputeInstanceFromTemplate_overrideScratchDisk|TestAccComputeInstanceFromTemplate_self_link_unique|TestAccComputeInstanceTemplate_metadata_startup_script|TestAccComputeInstanceTemplate_subnet_custom|TestAccComputeInstanceFromTemplate_basic|TestAccComputeInstanceTemplate_subnet_auto|TestAccComputeInstanceTemplate_regionDisks|TestAccComputeFirewallPolicyRule_multipleRules|TestAccComputeInstanceTemplate_disks|TestAccComputeInstanceTemplate_NetworkAttachment|TestAccComputeInstanceTemplate_with18TbScratchDisk|TestAccClouddeployDeliveryPipeline_DeliveryPipeline|TestAccClouddeployDeliveryPipeline_CanaryrunDeliveryPipeline|TestAccComputeInstanceTemplate_withScratchDisk|TestAccClouddeployDeliveryPipeline_CanaryServiceNetworkingDeliveryPipeline|TestAccCloudbuildv2Connection_GlePrivUpdateConnection|TestAccClouddeployDeliveryPipeline_CanaryDeliveryPipeline|TestAccCloudbuildv2Connection_GlePrivConnection|TestAccCloudbuildv2Connection_GleOldConnection|TestAccCloudbuildv2Connection_GleConnection|TestAccCloudbuildv2Connection_GitlabConnection|TestAccComputeInstanceFromTemplate_012_removableFields </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-07 20:58 UTC, ScottSuarez commented
/gcbrun

2023-07-07 21:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8262-old..auto-pr-8262) ( 21 files changed, 1023 insertions(+), 75 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8262-old..auto-pr-8262) ( 9 files changed, 29 insertions(+), 123 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8262-old..auto-pr-8262) ( 5 files changed, 128 insertions(+), 3 deletions(-))

2023-07-07 22:33 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2831` 
Passed tests `2533` 
Skipped tests: `295` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-07 22:36 UTC, modular-magician commented
Tests passed during RECORDING mode:
 `TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/recording/TestAccComputeFirewallPolicyRule_BasicFirSecRuleHandWritten.log)] 

Tests failed during RECORDING mode:
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

Please fix these to complete your PR
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8262/artifacts/82fd5e7f-dc01-473d-8adc-130209d140fe/recording) for each test

2023-07-10 17:18 UTC, ScottSuarez approved these changes

2023-07-10 17:19 UTC, merged