make uptime check period updatable
GoogleCloudPlatform/magic-modules pull request #8266
Opened 2023-07-05 14:57 UTC by DrFaust92

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2023-07-05 14:57 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-07-05 14:58 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @slevenick, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-07-05 15:41 UTC, slevenick commented on mmv1/third_party/terraform/tests/resource_monitoring_uptime_check_config_test.go
> +func testAccMonitoringUptimeCheckConfig_update(suffix, perdiod, path, pwd, project, host string) string {
```suggestion
func testAccMonitoringUptimeCheckConfig_update(suffix, period, path, pwd, project, host string) string {
```

2023-07-14 11:51 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick) gentle reminder

2023-07-14 17:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 17 insertions(+), 7 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 17 insertions(+), 7 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-14 17:47 UTC, modular-magician commented
#### Tests analytics 
Total tests: `13` 
Passed tests `13` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/0e763ed2-1686-41d8-bc5d-8accf0f6c139/build-log/replaying_test.log)

2023-07-14 17:58 UTC, slevenick requested changes
Failing with: 
`google-beta/resource_monitoring_uptime_check_config_test.go:120:9: fmt.Sprintf format %s reads arg #6, but call has 5 args`

2023-07-18 00:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 18 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 18 insertions(+), 8 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-18 01:56 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2863` 
Passed tests `2559` 
Skipped tests: `299` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_jsonPathUpdate|TestAccMonitoringUptimeCheckConfig_update|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-18 01:59 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccMonitoringUptimeCheckConfig_jsonPathUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording/TestAccMonitoringUptimeCheckConfig_jsonPathUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/build-log/recording_build/TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording/TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields.log)]
`TestAccMonitoringUptimeCheckConfig_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/build-log/recording_build/TestAccMonitoringUptimeCheckConfig_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording/TestAccMonitoringUptimeCheckConfig_update.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/b84e4819-5411-49bc-a436-978250f41a45/recording) for each test

2023-07-20 15:06 UTC, slevenick requested changes
I'm not entirely sure why but it looks like there is a syntax error in the produced config:

          on terraform_plugin_test.tf line 5, in resource "google_monitoring_uptime_check_config" "http":
           5:   period       = 60s

2023-07-27 11:07 UTC, DrFaust92 commented
[slevenick](https://github.com/slevenick) fixed but not able to test locally for some reason

2023-07-27 17:25 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 18 insertions(+), 8 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 18 insertions(+), 8 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8266-old..auto-pr-8266) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-27 19:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2889` 
Passed tests `2584` 
Skipped tests: `302` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields|TestAccMonitoringUptimeCheckConfig_update|TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-27 19:12 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/recording/TestAccMonitoringUptimeCheckConfig_changeNonUpdatableFields.log)]
`TestAccMonitoringUptimeCheckConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/recording/TestAccMonitoringUptimeCheckConfig_update.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8266/artifacts/845573a8-d390-4ac2-92b3-69187d8755d3/recording) for each test

2023-07-27 19:32 UTC, slevenick approved these changes
Thanks!

2023-07-27 19:32 UTC, merged