make  monitoring_config enable_components optional
GoogleCloudPlatform/magic-modules pull request #8299
Opened 2023-07-10 16:06 UTC by edwardmedia

Fixes https://github.com/hashicorp/terraform-provider-google/issues/15056

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
container: made `monitoring_config.enable_components` optional on `google_container_cluster`

```

2023-07-10 16:07 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @shuyama1, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-07-10 16:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8299-old..auto-pr-8299) ( 2 files changed, 27 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8299-old..auto-pr-8299) ( 2 files changed, 25 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8299-old..auto-pr-8299) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-10 18:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2847` 
Passed tests `2547` 
Skipped tests: `295` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerCluster_withMonitoringConfig|TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample|TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-10 18:47 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withMonitoringConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording/TestAccContainerCluster_withMonitoringConfig.log)]
`TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording/TestAccComputeTargetHttpsProxy_targetHttpsProxyHttpKeepAliveTimeoutExample.log)]
`TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording/TestAccComputeTargetHttpProxy_targetHttpProxyHttpKeepAliveTimeoutExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/16ff5e61-63c5-4692-8036-712e7fb1e415/recording) for each test

2023-07-10 19:59 UTC, shuyama1 requested changes
Looks like we made `monitoring_config.enable_components` to optional (ga-only, it's already optional in beta) and `logging_config.enable_components` to optional (both ga and beta). We may want to add a test on the latter on as well. Also release note needs to be modified to reflect it.

2023-07-10 21:05 UTC, edwardmedia commented
@shuyama1 I did not make change on `logging_config.enable_components` as it does not `managed_prometheus`. The behavior is different I guess. changing it to optional might be okay. If doing so, does it make sense if leaving logging_config empty?

2023-07-10 23:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8299-old..auto-pr-8299) ( 2 files changed, 26 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8299-old..auto-pr-8299) ( 1 file changed, 24 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8299-old..auto-pr-8299) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-11 00:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2848` 
Passed tests `2551` 
Skipped tests: `295` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-11 00:41 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8299/artifacts/7f2b1ac9-6b1c-47aa-9281-207fefd15455/recording) for each test

2023-07-11 08:25 UTC, shuyama1 commented
Running GA test on TC: https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/415343

@edwardmedia I've modified the changelog to reflect that this is a ga-only change. Please let me know if that's not the case.

2023-07-11 13:12 UTC, edwardmedia commented
Yes this is ga only. thanks @shuyama1

2023-07-11 17:34 UTC, merged