Add sendPreviousResourceOnDelete to fhir-notification-configs
GoogleCloudPlatform/magic-modules pull request #8361
Opened 2023-07-14 20:13 UTC by JosieLi-Google

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2023-07-14 20:13 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-07-14 21:52 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-07-14 21:52 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @roaks3, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-07-17 21:49 UTC, roaks3 requested changes
I found some typos, but otherwise seems fine after a first pass.

I'll run tests now, but also make sure you've gone through https://g3doc.corp.google.com/company/teams/terraform/users/resource-coverage/contribution-guide/index.md?cl=head to make sure you're in the appropriate groups to have the tests run without needing approval.

Lastly, it looks like you may need to update the PR description to get the release note formatted properly.

2023-07-17 21:49 UTC, roaks3 commented on mmv1/products/healthcare/FhirStore.yaml
> +            Whether to send full pervious FHIR resource to this Pub/Sub topic for Delete operation.
Typo: should be "previous"

2023-07-17 21:49 UTC, roaks3 commented on mmv1/products/healthcare/FhirStore.yaml
> +            it needs to fetch the full pervious resource as a separate operation.
Same as above with "previous"

2023-07-18 14:25 UTC, roaks3 commented
Build error is:
```
/usr/local/lib/ruby/3.1.0/psych.rb:455:in `parse': (<unknown>): found a tab character where an indentation space is expected while scanning a block scalar at line 284 column 24 (Psych::SyntaxError)
```

I'm assuming there is a tab somewhere in your yaml that is making something unhappy.

2023-08-23 20:23 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2023-08-23 20:33 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* Fhir PubSub Enhancement

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-08-24 17:05 UTC, roaks3 commented
Quick note while waiting for the tests: your `PRODUCT` in the release note would be `healthcare`

2023-08-24 17:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8361-old..auto-pr-8361) ( 2 files changed, 67 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8361-old..auto-pr-8361) ( 3 files changed, 11 insertions(+), 11 deletions(-))

2023-08-24 18:14 UTC, JosieLi-Google commented
Hi @roaks3 , to resolve the Diff report, should I simple `git rebase`?

2023-08-24 18:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2987` 
Passed tests `2689` 
Skipped tests: `296` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigsExample|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-24 18:26 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8361/artifacts/beafae9f-7355-43fc-98aa-1e59e4d4ee05/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigsExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8361/artifacts/beafae9f-7355-43fc-98aa-1e59e4d4ee05/build-log/recording_build/TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigsExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8361/artifacts/beafae9f-7355-43fc-98aa-1e59e4d4ee05/recording/TestAccHealthcareFhirStore_healthcareFhirStoreNotificationConfigsExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8361/artifacts/beafae9f-7355-43fc-98aa-1e59e4d4ee05/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8361/artifacts/beafae9f-7355-43fc-98aa-1e59e4d4ee05/recording) for each test

2023-08-24 19:57 UTC, roaks3 commented
@JosieLi-Google it looks like something strange has happened since your [first commit](https://github.com/GoogleCloudPlatform/magic-modules/pull/8361/commits/fc007a168b8ad73d9d3b2f06f9441a8a40bf661d) (maybe the merges?). The first commit appears to add a field, but if I look at the file changes for the PR currently, I'm only seeing changes to the description (and some other small tweaks).

I would suggest cleaning up the branch with something like this:
```
git rebase -i fc007a168b8ad73d9d3b2f06f9441a8a40bf661d
<remove merge commit lines from the file before saving>
```

Hopefully that cleans up whatever happened with the merges, and you can try:
```
git fetch origin main
git rebase origin/main
```

Which would catch up the branch, with your handful of commits on top.

If that doesn't work, you of course have other options, like `git reset` + `git cherry-pick`, or just starting fresh and copy-and-pasting.

2023-08-25 23:54 UTC, JosieLi-Google commented
> @JosieLi-Google it looks like something strange has happened since your [first commit](https://github.com/GoogleCloudPlatform/magic-modules/pull/8361/commits/fc007a168b8ad73d9d3b2f06f9441a8a40bf661d) (maybe the merges?). The first commit appears to add a field, but if I look at the file changes for the PR currently, I'm only seeing changes to the description (and some other small tweaks).
> 
> I would suggest cleaning up the branch with something like this:
> 
> ```
> git rebase -i fc007a168b8ad73d9d3b2f06f9441a8a40bf661d
> <remove merge commit lines from the file before saving>
> ```
> 
> Hopefully that cleans up whatever happened with the merges, and you can try:
> 
> ```
> git fetch origin main
> git rebase origin/main
> ```
> 
> Which would catch up the branch, with your handful of commits on top.
> 
> If that doesn't work, you of course have other options, like `git reset` + `git cherry-pick`, or just starting fresh and copy-and-pasting.

Hi @roak3, I think my changes are already submitted in https://github.com/GoogleCloudPlatform/magic-modules/pull/8507. I will double check if there is anything still missing, if not I will close the PR. Let me know if there is any concern. Thank you!

2023-08-29 14:42 UTC, roaks3 commented
Ah ok, that explains the strange diff after the merges. Thanks!

2023-11-14 14:15 UTC, roaks3 commented
@JosieLi-Google gentle ping on this. Since it has been sitting a while, we may just want to close this PR and come back if there is anything missing.

2023-11-21 19:49 UTC, closed without merging