add support for local ssd recovery timeout field to instance and instance template.
GoogleCloudPlatform/magic-modules pull request #8387
Opened 2023-07-19 12:02 UTC by muhammedkamal97

add support for local ssd recovery timeout field to instance and instance template.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
compute: added `local_ssd_recovery_timeout` field to `google_compute_instance` resource (beta)
compute: added `local_ssd_recovery_timeout` field to `google_compute_instance_template` resource (beta)
compute: added `local_ssd_recovery_timeout` field to `google_compute_regional_instance_template` resource (beta)
```

2023-07-19 12:02 UTC, modular-magician commented
Hello!  I am a robot who works on Magic Modules PRs.

I've detected that you're a community contributor. @trodge, a repository maintainer, has been assigned to assist you and help review your changes. 

<details>
  <summary>:question: First time contributing? Click here for more details</summary>

---

Your assigned reviewer will help review your code by: 
* Ensuring it's backwards compatible, covers common error cases, etc.
* Summarizing the change into a user-facing changelog note.
* Passes tests, either our "VCR" suite, a set of presubmit tests, or with manual test runs.

You can help make sure that review is quick by running local tests and ensuring they're passing in between each push you make to your PR's branch. Also, try to leave a comment with each push you make, as pushes generally don't generate emails.

If your reviewer doesn't get back to you within a week after your most recent change, please feel free to leave a comment on the issue asking them to take a look! In the absence of a dedicated review dashboard most maintainers manage their pending reviews through email, and those will sometimes get lost in their inbox.

---

</details>

2023-07-19 12:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 94 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 9 files changed, 369 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-19 12:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/eeb279ae-2b57-4ed3-b794-daae1dab0563/build-log/replaying_test.log)

2023-07-19 14:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 7 files changed, 124 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 480 insertions(+), 12 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 33 insertions(+), 33 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-19 16:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2868` 
Passed tests `2561` 
Skipped tests: `299` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeRegionInstanceTemplate_localSsdRecoveryTimeout|TestAccComputeInstance_localSsdRecoveryTimeout_update|TestAccComputeInstance_localSsdRecoveryTimeout|TestAccComputeFirewallPolicyRule_multipleRules|TestAccComputeInstanceTemplate_localSsdRecoveryTimeout|TestAccComputeInstance_minCpuPlatform|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-19 16:42 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in RECORDING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/0fb65cf1-9cbc-4056-baf4-149d2c91abff/build-log/recording_test.log)

2023-07-19 18:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 7 files changed, 124 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 480 insertions(+), 12 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 33 insertions(+), 33 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-19 18:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 7 files changed, 124 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 480 insertions(+), 12 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 33 insertions(+), 33 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-19 19:29 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/dafe54d5-76d3-4421-88c3-b8ed90d6a13d/build-log/replaying_test.log)

2023-07-19 19:30 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/38a8f76d-bd98-415c-823a-793f29f0fced/build-log/replaying_test.log)

2023-07-20 09:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 7 files changed, 273 insertions(+), 45 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 629 insertions(+), 45 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 188 insertions(+), 221 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-20 10:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `948` 
Passed tests `668` 
Skipped tests: `280` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/9ac996af-5ed7-4bf4-b065-37c2d7e27119/build-log/replaying_test.log)

2023-07-20 11:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 215 insertions(+), 45 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 635 insertions(+), 45 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 188 insertions(+), 221 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.nanos`, `scheduling.local_ssd_recovery_timeout.seconds`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.nanos`, `scheduling.local_ssd_recovery_timeout.seconds`

Please add acceptance tests which include these fields.

2023-07-20 12:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `915` 
Passed tests `635` 
Skipped tests: `280` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/cd243109-b846-4116-9304-80a854664981/build-log/replaying_test.log)

2023-07-20 17:52 UTC, trodge requested changes

2023-07-20 17:52 UTC, trodge commented on mmv1/third_party/terraform/go.mod.erb
Are all the changes here intentional?

2023-07-24 08:06 UTC, muhammedkamal97 commented on mmv1/third_party/terraform/go.mod.erb
yes updating the golang/api version since v132 is the newest version that contain that new field

2023-07-24 08:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 215 insertions(+), 45 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 12 files changed, 635 insertions(+), 45 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 241 insertions(+), 221 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (3 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (8 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-24 09:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1809` 
Passed tests `1513` 
Skipped tests: `295` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-24 09:04 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/2f179163-7b88-49f1-91fb-c7cda4d8763c/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/2f179163-7b88-49f1-91fb-c7cda4d8763c/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/2f179163-7b88-49f1-91fb-c7cda4d8763c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/2f179163-7b88-49f1-91fb-c7cda4d8763c/recording) for each test

2023-07-24 17:58 UTC, trodge commented on mmv1/third_party/terraform/go.mod.erb
Do all of these packages need to be updated as well?

2023-07-24 18:06 UTC, trodge commented
It looks like this change would also add these fields to the `google_compute_instance_from_machine_image` and `google_compute_instance_from_template` resources. Would it be possible to add tests for the fields in these resources as well?

2023-07-25 13:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 215 insertions(+), 45 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 14 files changed, 830 insertions(+), 45 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 241 insertions(+), 221 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (4 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.nanos`, `scheduling.local_ssd_recovery_timeout.seconds`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (9 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-25 13:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1003` 
Passed tests `722` 
Skipped tests: `281` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/5bbf4393-3319-45bf-b01f-1248320674b1/build-log/replaying_test.log)

2023-07-26 09:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 215 insertions(+), 45 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 14 files changed, 830 insertions(+), 45 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 241 insertions(+), 221 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (4 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (9 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.nanos`, `scheduling.local_ssd_recovery_timeout.seconds`

Please add acceptance tests which include these fields.

2023-07-26 10:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1124` 
Passed tests `840` 
Skipped tests: `284` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/e6104862-4bc8-47fb-a72e-2daf09629f43/build-log/replaying_test.log)

2023-07-26 11:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 5 files changed, 66 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 14 files changed, 681 insertions(+), 12 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 86 insertions(+), 33 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (4 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.
Resource: `google_compute_instance_from_template` (9 total tests)
Untested fields: `scheduling.local_ssd_recovery_timeout.seconds`, `scheduling.local_ssd_recovery_timeout.nanos`

Please add acceptance tests which include these fields.

2023-07-26 11:53 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/197d72c7-77eb-47d4-9373-43974070a07e/build-log/replaying_test.log)

2023-07-27 14:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 4 files changed, 37 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 13 files changed, 652 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 56 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_instance_from_machine_image` (4 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_machine_image" "primary" {
  scheduling {
    local_ssd_recovery_timeout {
      nanos   = # value needed
      seconds = # value needed
    }
  }
}

```
Resource: `google_compute_instance_from_template` (9 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_instance_from_template" "primary" {
  scheduling {
    local_ssd_recovery_timeout {
      nanos   = # value needed
      seconds = # value needed
    }
  }
}

```

2023-07-27 14:55 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/a04dddff-5d04-40b2-98f7-b0c3a0e27d71/build-log/replaying_test.log)

2023-07-28 08:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 4 files changed, 37 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 13 files changed, 847 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 56 insertions(+), 3 deletions(-))

2023-07-28 09:28 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/b72c5636-db50-4293-904f-ef11af425a85/build-log/replaying_test.log)

2023-07-28 09:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 4 files changed, 37 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 13 files changed, 847 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 56 insertions(+), 3 deletions(-))

2023-07-28 10:48 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/f30b6f4a-bde6-4959-9045-3f6fdb82de72/build-log/replaying_test.log)

2023-07-28 11:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 4 files changed, 37 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 13 files changed, 848 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 56 insertions(+), 3 deletions(-))

2023-07-28 12:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2898` 
Passed tests `2590` 
Skipped tests: `302` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout|TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout|TestAccComputeInstanceFromTemplateWithOverride_localSsdRecoveryTimeout|TestAccComputeInstanceTemplate_localSsdRecoveryTimeout|TestAccComputeInstanceFromTemplate_localSsdRecoveryTimeout </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 12:46 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeInstanceFromTemplateWithOverride_localSsdRecoveryTimeout`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccComputeInstanceFromTemplateWithOverride_localSsdRecoveryTimeout.log)]
`TestAccComputeInstanceTemplate_localSsdRecoveryTimeout`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccComputeInstanceTemplate_localSsdRecoveryTimeout.log)]
`TestAccComputeInstanceFromTemplate_localSsdRecoveryTimeout`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccComputeInstanceFromTemplate_localSsdRecoveryTimeout.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/build-log/recording_build/TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout.log)]
`TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/build-log/recording_build/TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording/TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/51f899f1-28c9-4e1c-988c-2f542bb7d2ff/recording) for each test

2023-07-28 13:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8387-old..auto-pr-8387) ( 4 files changed, 37 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8387-old..auto-pr-8387) ( 13 files changed, 844 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 3 files changed, 56 insertions(+), 3 deletions(-))

2023-07-28 14:58 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2898` 
Passed tests `2593` 
Skipped tests: `302` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout|TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 15:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/recording/TestAccComputeInstanceFromMachineImage_localSsdRecoveryTimeout.log)]
`TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/recording/TestAccComputeInstanceFromMachineImageWithOverride_localSsdRecoveryTimeout.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/efe63260-267d-437f-9c7c-1d998e10fc78/recording) for each test

2023-07-28 17:52 UTC, trodge approved these changes

2023-07-28 17:52 UTC, merged

2023-07-28 18:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8387-old..auto-pr-8387) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-28 20:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2908` 
Passed tests `2605` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 20:01 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/e17df5ca-441f-470a-825e-de5e83455415/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/e17df5ca-441f-470a-825e-de5e83455415/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/e17df5ca-441f-470a-825e-de5e83455415/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8387/artifacts/e17df5ca-441f-470a-825e-de5e83455415/recording) for each test