Adding Terraform resources for Tenancy APIs in GKEHub
GoogleCloudPlatform/magic-modules pull request #8396
Opened 2023-07-19 19:05 UTC by sahsagar-google

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2023-07-19 19:05 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* REPLACEME

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-07-19 19:05 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @NickElliot, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-07-19 19:58 UTC, sahsagar-google commented
```release-note:enhancement
gkehub: added `Namespace`, `Scope`, `MembershipBinding`, `MembershipRBACRoleBinding`, `ScopeRBACRoleBinding` resources
```

2023-07-19 21:53 UTC, NickElliot commented
/gcbrun

2023-07-19 22:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 10 files changed, 778 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (1 total tests)
Untested fields: `scope`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_membership_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Untested fields: `condition.description`, `condition.expression`, `condition.title`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.

2023-07-19 23:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2879` 
Passed tests `2570` 
Skipped tests: `299` 
Affected tests: `10` 

#### Action taken 
<details> <summary>Found 10 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Scope_gkehubScopeBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules|TestAccGKEHub2ScopeIamMemberGenerated|TestAccGKEHub2ScopeIamBindingGenerated|TestAccGKEHub2ScopeIamPolicyGenerated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-20 00:09 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHub2Scope_gkehubScopeBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2Scope_gkehubScopeBasicExample.log)]
`TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample.log)]
`TestAccGKEHub2ScopeIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2ScopeIamMemberGenerated.log)]
`TestAccGKEHub2ScopeIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2ScopeIamBindingGenerated.log)]
`TestAccGKEHub2ScopeIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2ScopeIamPolicyGenerated.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_build/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5bb1e67-c75d-4dcd-b0c7-bc247de21bb0/recording) for each test

2023-07-20 20:45 UTC, NickElliot reviewed
Hey! I've added one small comment that was causing a lint error, but wanted to ask if you could break this PR up into smaller layered ones for each individual resource (or if there are interdependent ones, just those that have to exist together). A five resource review ends up being somewhat unsustainable and likely to result in more review passes than them being separate, resulting it taking longer to reach the provider.

2023-07-20 20:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 10 files changed, 778 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (1 total tests)
Untested fields: `scope`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_membership_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Untested fields: `condition.description`, `condition.expression`, `condition.title`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.

2023-07-20 22:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2881` 
Passed tests `2577` 
Skipped tests: `299` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccComputeFirewallPolicyRule_multipleRules|TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-20 22:21 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_build/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/4f163aa5-de6a-4631-9ae6-c1f947e94708/recording) for each test

2023-07-24 20:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 10 files changed, 778 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (1 total tests)
Untested fields: `scope`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_membership_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.

2023-07-24 20:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 4510 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 10 files changed, 778 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (1 total tests)
Untested fields: `scope`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_membership_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.

2023-07-24 21:59 UTC, NickElliot reviewed
In case you missed the previous comment: https://github.com/GoogleCloudPlatform/magic-modules/pull/8396#pullrequestreview-1538109275

Thanks!

2023-07-24 22:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2882` 
Passed tests `2578` 
Skipped tests: `299` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-24 22:19 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeFirewallPolicyRule_multipleRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/build-log/recording_build/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/0216a795-935f-49d2-ae01-fab0eb582fd0/recording) for each test

2023-07-24 22:25 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2882` 
Passed tests `2576` 
Skipped tests: `299` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample|TestAccSpannerDatabaseIamPolicy|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules|TestAccBigQueryDataTable_bigtable </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-24 22:42 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSpannerDatabaseIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccSpannerDatabaseIamPolicy.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)]
`TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccBigQueryDataTable_bigtable.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/build-log/recording_build/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccGKEHub2MembershipRBACRoleBinding_gkehubMembershipRbacRoleBindingBasicExample.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ffd08f40-eab5-4aac-833d-4e8cfaf14c8b/recording) for each test

2023-07-24 23:00 UTC, sahsagar-google commented on mmv1/products/gkehub2/Scope.yaml
> +autogen_async: true
Hey Thanks for the comment. I made the change suggested. Also, segregated separate resources and added two more PRs 
https://github.com/GoogleCloudPlatform/magic-modules/pull/8440
https://github.com/GoogleCloudPlatform/magic-modules/pull/8437
Please let me know if this looks better now, Thank you.

2023-07-24 23:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 8 files changed, 593 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Untested fields: `condition.title`, `condition.description`, `condition.expression`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Untested fields: `condition.expression`, `condition.title`, `condition.description`

Please add acceptance tests which include these fields.
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Untested fields: `group`

Please add acceptance tests which include these fields.

2023-07-25 00:51 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2876` 
Passed tests `2574` 
Skipped tests: `299` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-25 00:52 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6448038-5592-4588-8032-06f253a068fc/recording) for each test

2023-07-26 22:54 UTC, NickElliot requested changes
Starting from the top, the namespace test appears to be failing with a 404 which at a glance appears to be due to the URL not being accurate based on what I'm seeing on the documentation. Is there a page I'm not seeing? Or if what I linked in the comment is correct, could you try updating that and running the test locally to see if it passes? Thanks!

2023-07-26 22:54 UTC, NickElliot commented on mmv1/products/gkehub2/Namespace.yaml
> +base_url: 'projects/{{project}}/locations/global/scopes/{{scope_id}}/namespaces'
Is this the correct URL location? The API documentation I can find at https://cloud.google.com/anthos/fleet-management/docs/reference/rest/v1beta/projects.locations.namespaces seems to be referencing this without the scopes sub directory.

2023-07-26 22:54 UTC, NickElliot commented on mmv1/products/gkehub2/Namespace.yaml
> +  api: 'https://cloud.google.com/anthos/fleet-management/docs/reference/rest/v1/projects.locations.scopes'
This needs to reference the API for specifically this resource, the page you linked has no reference to the Namespace resource.

2023-08-03 19:44 UTC, NickElliot reviewed
still pending requested changes

2023-08-10 21:30 UTC, sahsagar-google commented
> Starting from the top, the namespace test appears to be failing with a 404 which at a glance appears to be due to the URL not being accurate based on what I'm seeing on the documentation. Is there a page I'm not seeing? Or if what I linked in the comment is correct, could you try updating that and running the test locally to see if it passes? Thanks!

I updated with the correct documentation. 
The tests were passing locally, but they might have failed because the APIs were still becoming visible at the time but they should be fully visible now, so I am hoping they must pass now. Please lmk if that is not the case. Thank you for bearing with this.

2023-08-10 21:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 6 files changed, 590 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-10 22:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 6 files changed, 590 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-10 22:20 UTC, sahsagar-google commented
> still pending requested changes

I am rather new to Magic modules. Please let me know if there are more changes required. Thank you

2023-08-10 22:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 6 files changed, 590 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-10 23:14 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2945` 
Passed tests `2641` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-10 23:17 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/15b9ceba-d0b1-4f87-92f1-a8a0b367528c/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/15b9ceba-d0b1-4f87-92f1-a8a0b367528c/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/15b9ceba-d0b1-4f87-92f1-a8a0b367528c/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/15b9ceba-d0b1-4f87-92f1-a8a0b367528c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/15b9ceba-d0b1-4f87-92f1-a8a0b367528c/recording) for each test

2023-08-10 23:26 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2945` 
Passed tests `2641` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-10 23:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a00e6f06-ab03-4746-9452-b92bbc0be3ec/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a00e6f06-ab03-4746-9452-b92bbc0be3ec/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a00e6f06-ab03-4746-9452-b92bbc0be3ec/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a00e6f06-ab03-4746-9452-b92bbc0be3ec/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a00e6f06-ab03-4746-9452-b92bbc0be3ec/recording) for each test

2023-08-11 17:22 UTC, NickElliot requested changes
The failing test appears to be the result of the API returning a value using the project id number rather than just its id, which is causing a permadiff. To resolve this a DiffSupressFunc ([example usage](https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fmagic-modules+diff_suppress_func+language%3AYAML&type=code&l=YAML)) will be needed for the field, but thankfully in this case we have a standard one that should hopefully resolve the issue (https://github.com/GoogleCloudPlatform/magic-modules/blob/7aca11d48dee22c24432a4a03455de3bacd79a73/mmv1/third_party/terraform/tpgresource/common_diff_suppress.go.erb#L240C1-L250C2), but if it doesn't a more custom one will be needed.

2023-08-11 20:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 6 files changed, 590 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_namespace` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_namespace" "primary" {
  scope              = # value needed
  scope_id           = # value needed
  scope_namespace_id = # value needed
}

```
Resource: `google_gke_hub_scope` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope" "primary" {
  all_memberships = # value needed
  scope_id        = # value needed
}

```
Resource: `google_gke_hub_scope_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  members  = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  member   = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_policy" "primary" {
  policy_data = # value needed
  scope_id    = # value needed
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
  role {
    predefined_role = # value needed
  }
  scope_id                   = # value needed
  scope_rbac_role_binding_id = # value needed
  user                       = # value needed
}

```

2023-08-11 21:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2950` 
Passed tests `2647` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2Namespace_gkehubNamespaceBasicExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-11 21:20 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/25e23067-0bad-4f7d-96bc-4188925a3ffb/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/25e23067-0bad-4f7d-96bc-4188925a3ffb/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/25e23067-0bad-4f7d-96bc-4188925a3ffb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/25e23067-0bad-4f7d-96bc-4188925a3ffb/recording) for each test

2023-08-11 22:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 14 files changed, 2861 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 6 files changed, 590 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_namespace` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_namespace" "primary" {
  scope              = # value needed
  scope_id           = # value needed
  scope_namespace_id = # value needed
}

```
Resource: `google_gke_hub_scope` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope" "primary" {
  all_memberships = # value needed
  scope_id        = # value needed
}

```
Resource: `google_gke_hub_scope_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  members  = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  member   = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_policy" "primary" {
  policy_data = # value needed
  scope_id    = # value needed
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
  role {
    predefined_role = # value needed
  }
  scope_id                   = # value needed
  scope_rbac_role_binding_id = # value needed
  user                       = # value needed
}

```

2023-08-11 23:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3616 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3616 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 658 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_membership_binding" "primary" {
  location              = # value needed
  membership_binding_id = # value needed
  membership_id         = # value needed
  scope                 = # value needed
}

```
Resource: `google_gke_hub_namespace` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_namespace" "primary" {
  scope              = # value needed
  scope_id           = # value needed
  scope_namespace_id = # value needed
}

```
Resource: `google_gke_hub_scope` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope" "primary" {
  all_memberships = # value needed
  scope_id        = # value needed
}

```
Resource: `google_gke_hub_scope_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  members  = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  member   = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_policy" "primary" {
  policy_data = # value needed
  scope_id    = # value needed
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
  role {
    predefined_role = # value needed
  }
  scope_id                   = # value needed
  scope_rbac_role_binding_id = # value needed
  user                       = # value needed
}

```

2023-08-12 00:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3527 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3527 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 658 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_membership_binding" "primary" {
  location              = # value needed
  membership_binding_id = # value needed
  membership_id         = # value needed
  scope                 = # value needed
}

```
Resource: `google_gke_hub_namespace` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_namespace" "primary" {
  scope              = # value needed
  scope_id           = # value needed
  scope_namespace_id = # value needed
}

```
Resource: `google_gke_hub_scope` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope" "primary" {
  all_memberships = # value needed
  scope_id        = # value needed
}

```
Resource: `google_gke_hub_scope_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  members  = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  member   = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_policy" "primary" {
  policy_data = # value needed
  scope_id    = # value needed
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
  role {
    predefined_role = # value needed
  }
  scope_id                   = # value needed
  scope_rbac_role_binding_id = # value needed
  user                       = # value needed
}

```

2023-08-12 01:49 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2952` 
Passed tests `2642` 
Skipped tests: `302` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample|TestAccDataSourceGoogleServiceAccountJwt|TestAccSpannerDatabaseIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-12 02:13 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample.log)]
`TestAccDataSourceGoogleServiceAccountJwt`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccDataSourceGoogleServiceAccountJwt.log)]
`TestAccSpannerDatabaseIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording/TestAccSpannerDatabaseIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/ac1bd5bf-c4a3-4329-ac93-09b641de7694/recording) for each test

2023-08-14 19:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3527 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 17 files changed, 3527 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 658 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_membership_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_membership_binding" "primary" {
  location              = # value needed
  membership_binding_id = # value needed
  membership_id         = # value needed
  scope                 = # value needed
}

```
Resource: `google_gke_hub_namespace` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_namespace" "primary" {
  scope              = # value needed
  scope_id           = # value needed
  scope_namespace_id = # value needed
}

```
Resource: `google_gke_hub_scope` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope" "primary" {
  all_memberships = # value needed
  scope_id        = # value needed
}

```
Resource: `google_gke_hub_scope_iam_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  members  = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_member` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
  member   = # value needed
  role     = # value needed
  scope_id = # value needed
}

```
Resource: `google_gke_hub_scope_iam_policy` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_policy" "primary" {
  policy_data = # value needed
  scope_id    = # value needed
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
  role {
    predefined_role = # value needed
  }
  scope_id                   = # value needed
  scope_rbac_role_binding_id = # value needed
  user                       = # value needed
}

```

2023-08-14 20:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2956` 
Passed tests `2652` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccHealthcareDatasetIamPolicy|TestAccProjectIamPolicy_invalidMembers </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-14 20:58 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a4f9745d-f0cf-49ba-b909-4693d6fbb476/recording/TestAccHealthcareDatasetIamPolicy.log)]
`TestAccProjectIamPolicy_invalidMembers`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a4f9745d-f0cf-49ba-b909-4693d6fbb476/recording/TestAccProjectIamPolicy_invalidMembers.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a4f9745d-f0cf-49ba-b909-4693d6fbb476/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a4f9745d-f0cf-49ba-b909-4693d6fbb476/recording) for each test

2023-08-15 22:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 658 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-15 23:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 658 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-16 16:23 UTC, melinath commented
Reassigning review to @ScottSuarez since @NickElliot is not available.

2023-08-16 18:31 UTC, melinath commented
Reassigning to @roaks3

2023-08-22 18:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3691 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-22 20:52 UTC, NickElliot requested changes
The unit tests are failing due to the following: `resource google_gke_hub_namespace: All fields are ForceNew or Computed w/out Optional, Update is superfluous`

i.e. it is suggesting the update_url and related attributes be removed from Namespace.yaml as they server no purpose with the current implementation here -- should "namespaceLabels" or "labels" which are updateable api fields be included in this resource?

2023-08-22 21:01 UTC, sahsagar-google commented
> The unit tests are failing due to the following: `resource google_gke_hub_namespace: All fields are ForceNew or Computed w/out Optional, Update is superfluous`
> 
> i.e. it is suggesting the update_url and related attributes be removed from Namespace.yaml as they server no purpose with the current implementation here -- should "namespaceLabels" or "labels" which are updateable api fields be included in this resource?

@NickElliot I plan to update all the resources with labels in a new PR since this is a new change in the proto for me. And since, there is nothing to update in the Namespace, I asked the team that it's okay to make it immutable for now. Please let me know if the tests work now. Thanks!

2023-08-22 21:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-22 22:22 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2992` 
Passed tests `2693` 
Skipped tests: `295` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-22 22:30 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/2a47fd9d-a6ef-49ad-a072-3bd90fe5f80b/recording) for each test

2023-08-24 20:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-24 21:28 UTC, NickElliot requested changes
Could the update test for RBACRoleBinding perform the swap between User and Group? 

Otherwise, a couple changes I'm still seeing needed are:
an update test for Scope, because even though only 'all_memberships' is updateable, the terraform in-place update functionality needs to be verified. Same situation for MembershipBinding with 'scope'.

2023-08-24 21:31 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2995` 
Passed tests `2697` 
Skipped tests: `296` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-24 21:33 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/build-log/recording_build/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/build-log/recording_build/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/d5792e97-6b61-49c6-a487-8f296dfc72cd/recording) for each test

2023-08-25 22:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 18 files changed, 3624 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_rbac_role_binding` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_rbac_role_binding" "primary" {
  group = # value needed
}

```

2023-08-25 22:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 3809 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 3809 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```

2023-08-26 00:02 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2999` 
Passed tests `2700` 
Skipped tests: `296` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update|TestAccGKEHub2Scope_gkehubScopeBasicExample_update|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-26 00:18 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2Scope_gkehubScopeBasicExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/build-log/recording_build/TestAccGKEHub2Scope_gkehubScopeBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2Scope_gkehubScopeBasicExample_update.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording) for each test

2023-08-28 19:33 UTC, sahsagar-google commented
> Tests passed during RECORDING mode: `TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update.log)] `TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update.log)]
> 
> ##### Rerun these tests in REPLAYING mode to catch issues
> No issues found for passed tests after REPLAYING rerun.
> 
> Tests failed during RECORDING mode: `TestAccGKEHub2Scope_gkehubScopeBasicExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/build-log/recording_build/TestAccGKEHub2Scope_gkehubScopeBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording/TestAccGKEHub2Scope_gkehubScopeBasicExample_update.log)]
> 
> Please fix these to complete your PR. View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/b6981a32-9e85-4d66-8004-c87c9293a1b3/recording) for each test

@NickElliot Could you pinpoint the exact error of the Scope update test(TestAccGKEHub2Scope_gkehubScopeBasicExample_update) to me please? 
I looked through the Debug log, but not able to figure out why it failed.

2023-08-28 19:53 UTC, NickElliot reviewed
Sorry for the delay, review was sitting in progress before lunch.

`TestAccGKEHub2Scope_gkehubScopeBasicExample_update` is having a failure due to `all_memberships` not maintaining the `true` value when it attempts to refresh the plan, despite returning a success on the PATCH with the true value. It would appear to be a case of go/dont-break-terraform#new-values-returned-for-old-fields causing a permadiff, but if the field is actually immutable or output only then the YAML needs to be changed to match. As you're more familiar with it being on the service team in question, the intended API behavior needs to be clarified.

2023-08-28 20:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 3809 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 20 files changed, 3809 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 662 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```

2023-08-28 20:58 UTC, sahsagar-google commented
> Sorry for the delay, review was sitting in progress before lunch.
> 
> `TestAccGKEHub2Scope_gkehubScopeBasicExample_update` is having a permadiff failure due to `all_memberships` not maintaining the `true` value when it attempts to refresh the plan (with the API saying it currently is `false`), despite returning a success on the PATCH with the `true` value. It would appear to be a case of go/dont-break-terraform#new-values-returned-for-old-fields, but if the field is actually immutable or output only then the YAML needs to be changed to match. As you're more familiar with it being on the service team in question, the intended API behavior needs to be clarified.

Thank you for sharing that error. I talked to the team and we feel it should be removed at this point. Sorry for the confusion.

2023-08-28 21:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 19 files changed, 3634 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 19 files changed, 3634 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 650 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```

2023-08-28 22:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3004` 
Passed tests `2701` 
Skipped tests: `296` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHub2Namespace_gkehubNamespaceBasicExample|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update|TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample|TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample|TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update|TestAccDataSourceGoogleServiceAccountJwt|TestAccDataSourceGoogleServiceAccountAccessToken_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-28 22:26 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountJwt`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccDataSourceGoogleServiceAccountJwt.log)]
`TestAccDataSourceGoogleServiceAccountAccessToken_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccDataSourceGoogleServiceAccountAccessToken_basic.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHub2Namespace_gkehubNamespaceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_build/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccGKEHub2Namespace_gkehubNamespaceBasicExample.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_update.log)]
`TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_build/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccGKEHub2ScopeRBACRoleBinding_gkehubScopeRbacRoleBindingBasicExample.log)]
`TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_build/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample.log)]
`TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_build/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording/TestAccGKEHub2MembershipBinding_gkehubMembershipBindingBasicExample_update.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/01b7c357-b06a-4ea1-9aa6-524f2b71b773/recording) for each test

2023-08-29 20:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8396-old..auto-pr-8396) ( 19 files changed, 3624 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8396-old..auto-pr-8396) ( 19 files changed, 3624 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8396-old..auto-pr-8396) ( 7 files changed, 650 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_scope_iam_binding` (2 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_binding" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```
Resource: `google_gke_hub_scope_iam_member` (1 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_scope_iam_member" "primary" {
  condition {
    description = # value needed
    expression  = # value needed
    title       = # value needed
  }
}

```

2023-08-29 21:18 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3006` 
Passed tests `2708` 
Skipped tests: `296` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAppEngineStandardAppVersion_update|TestAccVPCAccessConnectorDatasource_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-29 21:36 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccAppEngineStandardAppVersion_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a65a2834-482a-4313-8610-80405e337895/recording/TestAccAppEngineStandardAppVersion_update.log)]
`TestAccVPCAccessConnectorDatasource_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a65a2834-482a-4313-8610-80405e337895/recording/TestAccVPCAccessConnectorDatasource_basic.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a65a2834-482a-4313-8610-80405e337895/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8396/artifacts/a65a2834-482a-4313-8610-80405e337895/recording) for each test

2023-08-29 22:22 UTC, NickElliot approved these changes
LGTM!

2023-08-29 22:24 UTC, merged