Add BlockingFunctionsConfig, RecaptchaConfig and QuotaConfig fields to identityplatform config
GoogleCloudPlatform/magic-modules pull request #8402
Opened 2023-07-20 12:46 UTC by mraouffouad

Add BlockingFunctionsConfig, AuthorizedDomains and QuotaConfig fields to identityplatform config

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read the [Release Notes Guide](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/RELEASE_NOTES_GUIDE.md) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement

```

2023-07-20 12:46 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @slevenick, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-07-20 13:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 563 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 563 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_identity_platform_config` (1 total tests)
Untested fields: `quota.sign_up_quota_config.quota_duration`, `quota.sign_up_quota_config.start_time`

Please add acceptance tests which include these fields.

2023-07-20 13:29 UTC, mraouffouad commented
@slevenick This is a redo of [PR/8064](https://github.com/GoogleCloudPlatform/magic-modules/pull/8064) after addressing @roaks3 's comments.

2023-07-20 14:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2871` 
Passed tests `2570` 
Skipped tests: `299` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-20 14:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 563 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 563 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_identity_platform_config` (1 total tests)
Untested fields: `quota.sign_up_quota_config.quota_duration`, `quota.sign_up_quota_config.start_time`

Please add acceptance tests which include these fields.

2023-07-20 16:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2871` 
Passed tests `2570` 
Skipped tests: `298` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-20 16:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/build-log/recording_build/TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/recording/TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/a3a03352-56b6-4975-9060-e6ebf02af4a0/recording) for each test

2023-07-20 16:40 UTC, slevenick requested changes
googleapi: Error 400: INVALID_CONFIG : SignUp quota must start between now and 365 days from now.

2023-07-20 17:07 UTC, rainshen49 commented on mmv1/products/identityplatform/Config.yaml
> +            description: |
Should we also add an example of how to structure the duration string? E.g. https://github.com/GoogleCloudPlatform/magic-modules/blob/31547b00e1e93da8fd198d133a17df4264d4eb4d/mmv1/products/alloydb/Cluster.yaml#L171

2023-07-23 19:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 570 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 570 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_identity_platform_config` (1 total tests)
Untested fields: `quota.sign_up_quota_config.quota_duration`

Please add acceptance tests which include these fields.

2023-07-23 20:44 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2874` 
Passed tests `2573` 
Skipped tests: `299` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-23 20:46 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/f60f4170-b92c-4a94-acab-44d9d8d87ff8/recording) for each test

2023-07-24 03:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 570 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 570 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_identity_platform_config` (1 total tests)
Untested fields: `quota.sign_up_quota_config.quota_duration`

Please add acceptance tests which include these fields.

2023-07-24 04:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2874` 
Passed tests `2573` 
Skipped tests: `299` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccComputeFirewallPolicyRule_multipleRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-24 04:48 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccComputeFirewallPolicyRule_multipleRules`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/build-log/recording_build/TestAccComputeFirewallPolicyRule_multipleRules_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/recording/TestAccComputeFirewallPolicyRule_multipleRules.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/7c518b1f-d43f-4b37-b7f5-66301d1e6474/recording) for each test

2023-07-24 16:49 UTC, slevenick requested changes
Fails with:
Field 'startTime', Illegal timestamp format; timestamps must end with 'Z' or have a valid timezone offset."

Are you able to run the test yourself?

2023-07-24 17:20 UTC, mraouffouad commented
> Fails with: Field 'startTime', Illegal timestamp format; timestamps must end with 'Z' or have a valid timezone offset."
> 
> Are you able to run the test yourself?

I got that error locally before I added the call to UTC(), which I assumed would fix the problem. I'll try a further fix locally and update the PR once it passes.

2023-07-26 03:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))

2023-07-26 04:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2882` 
Passed tests `2580` 
Skipped tests: `301` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-26 04:49 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/21260f81-6c3a-4530-b7b3-f12ace825e14/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/21260f81-6c3a-4530-b7b3-f12ace825e14/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/21260f81-6c3a-4530-b7b3-f12ace825e14/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/21260f81-6c3a-4530-b7b3-f12ace825e14/recording) for each test

2023-07-26 14:31 UTC, mraouffouad commented
@slevenick Running the test locally passes all the field validation steps but produces the error below at the end. Perhaps it had to do with my env settings. Github is not showing the test on the list failed tests. Can you confirm?

Error:
====
    vcr_utils.go:152: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # google_identity_platform_config.default will be updated in-place
          ~ resource "google_identity_platform_config" "default" {
                id                         = "projects/terraform-gcip-6/config"
                name                       = "projects/365025219842/config"
                # (3 unchanged attributes hidden)
        
              ~ quota {
                  ~ sign_up_quota_config {
                      ~ start_time     = "2023-07-27T02:55:00Z" -> "2023-07-26T22:55:00-04:00"
                        # (2 unchanged attributes hidden)
                    }
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.

2023-07-26 16:08 UTC, slevenick commented
The test is skipped in VCR, so I have to run it myself. I think your local failure indicates a problem with how the resource works. I'm not sure exactly why though.

2023-07-26 16:17 UTC, mraouffouad commented
> 

I see. I enabled VCR, let's see what the logs will reveal.

2023-07-26 16:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 4 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))

2023-07-26 17:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2882` 
Passed tests `2580` 
Skipped tests: `300` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample|TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-26 17:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/recording/TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/build-log/replaying_build_after_recording/TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/replaying_after_recording/TestAccIdentityPlatformConfig_identityPlatformConfigBasicExample.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/445ae3d8-ee12-4e76-aea1-0cb2256da7b3/recording) for each test

2023-07-26 18:06 UTC, mraouffouad commented
> 
Error: Error updating Config "projects/tf-test-my-projectt1rb1914oe/config": Patch "https://identitytoolkit.googleapis.com/v2/projects/tf-test-my-projectt1rb1914oe/config?alt=json&updateMask=autodeleteAnonymousUsers%2CblockingFunctions%2Cquota%2CauthorizedDomains": Requested interaction not found

Ah, I guess this is why VCR was skipped in the first place: https://github.com/hashicorp/terraform-provider-google/issues/14158

It leaves me with no options other than tying to run the test locally. @slevenick I would appreciate it if you do the same.

2023-07-26 18:28 UTC, mraouffouad commented
> > 
> 
> Error: Error updating Config "projects/tf-test-my-projectt1rb1914oe/config": Patch "https://identitytoolkit.googleapis.com/v2/projects/tf-test-my-projectt1rb1914oe/config?alt=json&updateMask=autodeleteAnonymousUsers%2CblockingFunctions%2Cquota%2CauthorizedDomains": Requested interaction not found
> 
> Ah, I guess this is why VCR was skipped in the first place: [hashicorp/terraform-provider-google#14158](https://github.com/hashicorp/terraform-provider-google/issues/14158)
> 
> It leaves me with no options other than tying to run the test locally. @slevenick I would appreciate it if you do the same.

However, FWIW the test passed during recording mode.

2023-07-28 02:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 572 insertions(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8402-old..auto-pr-8402) ( 3 files changed, 202 insertions(+), 3 deletions(-))

2023-07-28 03:43 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2890` 
Passed tests `2587` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 03:43 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/952a5978-5375-428a-844b-db7a3eecdd86/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/952a5978-5375-428a-844b-db7a3eecdd86/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/952a5978-5375-428a-844b-db7a3eecdd86/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8402/artifacts/952a5978-5375-428a-844b-db7a3eecdd86/recording) for each test

2023-07-28 15:26 UTC, merged