Move regional SSL policies to GA
GoogleCloudPlatform/magic-modules pull request #8443
Opened 2023-07-25 10:37 UTC by juliocc

Move `google_compute_region_ssl_policy` to GA.

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
Move `google_compute_region_ssl_policy` to GA.

```

2023-07-25 10:38 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @shuyama1, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-07-25 10:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8443-old..auto-pr-8443) ( 4 files changed, 724 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8443-old..auto-pr-8443) ( 1 file changed, 1 insertion(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8443-old..auto-pr-8443) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-25 17:25 UTC, shuyama1 requested changes
Looks like the tests of this resource are handwritten, would you mind also bumping them to GA? The tests are located at mmv1/third_party/terraform/tests/resource_compute_region_ssl_policy_test.go.erb
Please see https://googlecloudplatform.github.io/magic-modules/develop/promote-to-ga/ for details on how to promote handwritten resources/tests to GA.
Thank you!

2023-07-25 18:06 UTC, juliocc commented
> Looks like the tests of this resource are handwritten, would you mind also bumping them to GA? The tests are located at mmv1/third_party/terraform/tests/resource_compute_region_ssl_policy_test.go.erb Please see https://googlecloudplatform.github.io/magic-modules/develop/promote-to-ga/ for details on how to promote handwritten resources/tests to GA. Thank you!

Done. I believe it was just a matter of removing the outermost conditional but let me know if I missed anything.

2023-07-25 18:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8443-old..auto-pr-8443) ( 5 files changed, 949 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8443-old..auto-pr-8443) ( 1 file changed, 1 insertion(+), 3 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8443-old..auto-pr-8443) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-25 20:39 UTC, shuyama1 commented
No VCR test triggered since there's no go file changes in beta. 
Running GA tests at https://ci-oss.hashicorp.engineering/buildConfiguration/GoogleCloud_ProviderGoogleCloudMmUpstream/420077

2023-07-26 18:50 UTC, juliocc commented
I don't have access to teamcity. Is there anything else I need to do?

2023-07-26 19:00 UTC, shuyama1 commented
> I don't have access to teamcity. Is there anything else I need to do?

GA tests passed. It's good to go. I'll approve and merge the PR. Thank you!

2023-07-26 19:01 UTC, shuyama1 approved these changes

2023-07-26 19:01 UTC, merged