Add no_wrapper field on pubsub push subscription
GoogleCloudPlatform/magic-modules pull request #8462
Opened 2023-07-27 13:23 UTC by oshiro3

Add push_config.nowrapper field to unwrap pubsub payload
ref: https://cloud.google.com/pubsub/docs/payload-unwrapping

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
PUBSUB: added `push_config.no_wrapper` field to `PUBSUB` resource
```

2023-07-27 13:23 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @zli82016, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-07-27 17:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 143 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 143 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 38 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_pubsub_subscription` (15 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_pubsub_subscription" "primary" {
  push_config {
    no_wrapper {
      write_metadata = # value needed
    }
  }
}

```

2023-07-27 19:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2890` 
Passed tests `2584` 
Skipped tests: `302` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPubsubSubscription_pubsubSubscriptionPushExample|TestAccPubsubSubscription_nowrap|TestAccPubsubSubscription_push|TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-27 19:23 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pubsubSubscriptionPushExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/recording/TestAccPubsubSubscription_pubsubSubscriptionPushExample.log)]
`TestAccPubsubSubscription_push`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/recording/TestAccPubsubSubscription_push.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_nowrap`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/build-log/recording_build/TestAccPubsubSubscription_nowrap_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/recording/TestAccPubsubSubscription_nowrap.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/3a0712a9-93bb-4c76-b47e-6ccc1d821350/recording) for each test

2023-07-28 16:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 143 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 143 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8462-old..auto-pr-8462) ( 3 files changed, 38 insertions(+), 3 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_pubsub_subscription` (15 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_pubsub_subscription" "primary" {
  push_config {
    no_wrapper {
      write_metadata = # value needed
    }
  }
}

```

2023-07-28 16:55 UTC, zli82016 requested changes

2023-07-28 16:55 UTC, zli82016 commented on mmv1/templates/terraform/examples/pubsub_subscription_push_payload_nowrapping.tf.erb
> +resource "google_pubsub_topic" "<%= ctx[:primary_resource_id] %>" {
Can you please add this file to the list of examples in Subscription.yaml file? https://github.com/GoogleCloudPlatform/magic-modules/blob/2e6fe277dbc85e997ee8a86db87ee69bc801138a/mmv1/products/pubsub/Subscription.yaml#L32

2023-07-28 16:55 UTC, zli82016 commented on mmv1/third_party/terraform/tests/resource_pubsub_subscription_test.go
> +			},
Can you please add more steps to test updating the filed `write_metadata` from true to false? Thanks.

2023-07-28 18:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2901` 
Passed tests `2597` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccPubsubSubscription_noWrap </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 18:09 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccPubsubSubscription_noWrap`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/build-log/recording_build/TestAccPubsubSubscription_noWrap_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/recording/TestAccPubsubSubscription_noWrap.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8462/artifacts/f6c7f56f-aa5e-4e7e-82ae-80be5d2562eb/recording) for each test

2023-07-29 01:52 UTC, oshiro3 commented
Thanks for reviewing the P/R.
I have implemented the corrections based on your comments and would like you to review them again.

2023-07-29 01:56 UTC, oshiro3 commented
@zli82016 
I closed it because the same content had already been merged in a later P/R.
Thanks for your help!

https://github.com/GoogleCloudPlatform/magic-modules/pull/8464

2023-07-29 01:57 UTC, closed without merging