Remove tgc build from downstream builder
GoogleCloudPlatform/magic-modules pull request #8472
Opened 2023-07-27 20:17 UTC by trodge

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-07-27 20:41 UTC, trodge commented
/gcbrun

2023-07-27 22:29 UTC, trodge commented
/gcbrun

2023-07-27 22:38 UTC, ScottSuarez commented
/gcbrun

2023-07-28 18:12 UTC, ScottSuarez commented on .ci/containers/downstream-builder/generate_downstream.sh
> -      go get -d github.com/hashicorp/terraform-provider-google-beta@$BASE_BRANCH
This line will need to stay, otherwise the downstream branch won't update terraform-provider-google-beta to latest in the `go.sum`

2023-07-28 18:15 UTC, ScottSuarez commented
Thankfully we probably can retain the old behavior.
https://github.com/GoogleCloudPlatform/magic-modules/blob/07720f6bfdcc21d083d325774f693e79bfff6411/.ci/gcb-push-downstream.yml#L107-L130

Looks like this is where the downstreams are built. We need to update the `wait_for` to be dependent on tpgb
https://github.com/GoogleCloudPlatform/magic-modules/blob/main/.ci/gcb-push-downstream.yml#L110

2023-07-28 18:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-07-28 18:24 UTC, trodge commented
> -d github.com/hashicorp/terraform-provider-google-beta@$BASE_BRANCH

If we're retaining the old behavior doesn't it already wait on everything it needs to wait on?

2023-07-28 18:57 UTC, ScottSuarez commented
we changed it to rely on tpgb but this line was never updated. I think its a mishap.

2023-07-28 19:35 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2908` 
Passed tests `2604` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 19:36 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/3af1cf3b-8f93-41b1-b4ee-37768be8a615/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/3af1cf3b-8f93-41b1-b4ee-37768be8a615/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/3af1cf3b-8f93-41b1-b4ee-37768be8a615/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/3af1cf3b-8f93-41b1-b4ee-37768be8a615/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/3af1cf3b-8f93-41b1-b4ee-37768be8a615/recording) for each test

2023-07-28 20:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-07-28 22:07 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2909` 
Passed tests `2606` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-07-28 22:07 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/8f27b957-35fc-4220-9bab-1c367674a849/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/8f27b957-35fc-4220-9bab-1c367674a849/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/8f27b957-35fc-4220-9bab-1c367674a849/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8472/artifacts/8f27b957-35fc-4220-9bab-1c367674a849/recording) for each test

2023-07-28 22:12 UTC, ScottSuarez commented
Looks like all the terraform google conversion tests are failing status on the PR

2023-07-28 22:18 UTC, ScottSuarez commented
Ah this is probably because you didn't update their container. Could you also update their containers remotely. Want to make sure everything is green before landing it.

2023-08-03 20:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-08-04 17:47 UTC, ScottSuarez requested changes

2023-08-04 17:47 UTC, ScottSuarez commented on .ci/scripts/go-plus/terraform-validator-tester/test_terraform_validator.sh
> +
I'm curious what will happen now if there is a build failure here?

Will we still send the message for terraform-validator build and unit test failure? Could you test this scenario? Just want to make sure we aren't inadvertently breaking this part of the pipeline.

The UX we expect is `terraform-validator-build-and-unit-test` (or similar) should be send if there is a build failure for validator.

2023-08-04 19:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8472-old..auto-pr-8472) ( 1 file changed, 1 insertion(+))

2023-08-04 20:06 UTC, ScottSuarez commented
Looks good !! Thanks so much, one last flow I would like to see. Could you make a small change to tgc so the code compiles and tests run without being skipped. Then I think we are good to check this in !

2023-08-04 20:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8472-old..auto-pr-8472) ( 1 file changed, 2 insertions(+))

2023-08-04 21:12 UTC, ScottSuarez approved these changes
Looks good to me. Could you revert the changes to the mmv1 directory. Thanks for testing!!

2023-08-04 21:33 UTC, merged