fixed update_policy.maxUnavailable
GoogleCloudPlatform/magic-modules pull request #8481
Opened 2023-07-28 21:32 UTC by edwardmedia

Fixes https://github.com/hashicorp/terraform-provider-google/issues/15202

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed the error when neither `update_policy. max_surge_fixed` and `update_policy. max_surge_max_surge_percent` is provided for creation on `google_compute_instance_group_manager` and `google_compute_region_instance_group_manager`
```

2023-07-28 21:33 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @ScottSuarez, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-07-28 21:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8481-old..auto-pr-8481) ( 3 files changed, 159 insertions(+), 12 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8481-old..auto-pr-8481) ( 3 files changed, 159 insertions(+), 12 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8481-old..auto-pr-8481) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-07-28 21:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `13` 
Passed tests `13` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/d214ec8e-e179-42b4-8b15-a0f5481238e3/build-log/replaying_test.log)

2023-07-28 22:26 UTC, ScottSuarez requested changes

2023-07-28 22:26 UTC, ScottSuarez commented on mmv1/third_party/terraform/services/compute/resource_compute_instance_group_manager.go.erb
> +func EmptyOrAllowedListSuppress(vals []string) schema.SchemaDiffSuppressFunc {
Could you add unit tests for this function ?

2023-07-28 22:26 UTC, ScottSuarez commented on mmv1/third_party/terraform/services/compute/resource_compute_instance_group_manager.go.erb
> +							},
Can this be declared outside of the schema and unit tests be added for it?

2023-07-31 18:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/build-log/recording_build/TestAccContainerAwsNodePool_BetaBasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccInstanceGroupManager_waitForStatus`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/build-log/recording_build/TestAccInstanceGroupManager_waitForStatus_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/recording/TestAccInstanceGroupManager_waitForStatus.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8481/artifacts/c5056b64-683f-49e5-b6a4-45ca7d3d669b/recording) for each test

2023-07-31 23:48 UTC, ScottSuarez approved these changes

2023-08-01 18:18 UTC, edwardmedia commented
There is still one test failing. This PR needs to be put on hold. Below api rules are discovered

1)  when both max_surge_percent and max_surge_fixed are not given, max_surge_fixed will be set 1.  
2)  max_surge_percent and max_surge_fixed can't be set 1 at the same time. 
3)  max_surge_fixed = 0 and max_surge_percent = "" is valid
4)  max_surge_fixed must to set to 0 when replacement_method is set RECREATE
5)  maxSurge and maxUnavailable cannot both be 0

2023-08-01 21:52 UTC, ScottSuarez commented
What is the intention of the change and UX we expect. This is only an issue with updating the resource correct?

2023-08-03 13:25 UTC, closed without merging