feat: add new data source: google_dataproc_cluster
GoogleCloudPlatform/magic-modules pull request #8527
Opened 2023-08-02 20:57 UTC by bschaatsbergen

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-datasource
google_dataproc_cluster
```

2023-08-02 20:58 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @melinath, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-08-04 21:59 UTC, melinath requested changes
Please add tests similar to [mmv1/third_party/terraform/tests/data_source_pubsub_subscription_test.go](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/mmv1/third_party/terraform/tests/data_source_pubsub_subscription_test.go)

2023-08-04 22:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8527-old..auto-pr-8527) ( 3 files changed, 89 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8527-old..auto-pr-8527) ( 3 files changed, 89 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8527-old..auto-pr-8527) ( 2 files changed, 3 insertions(+), 3 deletions(-))

2023-08-04 22:06 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in REPLAYING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8527/artifacts/63d74a05-3c82-4998-817b-4993a84143a8/build-log/replaying_test.log)

2023-08-04 22:23 UTC, melinath commented
Tests fail to compile:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x12 pc=0x2951679]

goroutine 1 [running]:
github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource.FixDatasourceSchemaFlags(...)
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource/datasource_helpers.go:63
github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource.AddRequiredFieldsToSchema(...)
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource/datasource_helpers.go:70
github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataproc.DataSourceDataprocCluster()
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/services/dataproc/data_source_dataproc_cluster.go:18 +0xb9
github.com/hashicorp/terraform-provider-google-beta/google-beta/provider.DatasourceMapWithErrors()
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/provider.go:899 +0x459f
github.com/hashicorp/terraform-provider-google-beta/google-beta/provider.DatasourceMap(...)
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/provider.go:823
github.com/hashicorp/terraform-provider-google-beta/google-beta/provider.Provider()
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/provider/provider.go:809 +0x3e2a
github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest.init.0()
	/go/src/github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest/provider_test_utils.go:110 +0x8d
```

2023-09-04 13:30 UTC, bschaatsbergen commented
Hey @melinath, was out for a bit. I'll fix this in the coming week.

2023-12-26 22:25 UTC, closed without merging