Bitbucket Trigger support for Manual, Pub/Sub and Webhook triggers
GoogleCloudPlatform/magic-modules pull request #8544
Opened 2023-08-03 17:53 UTC by mariomachado94

Adds field bitbucket_server_config to Trigger.git_file_source and Trigger.source_to_build, supporting manual, pub/sub and webhook triggers.

Also fixes TestAccCloudBuildTrigger_basic_bitbucket test.

fixes https://github.com/hashicorp/terraform-provider-google/issues/15079

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
cloudbuild: added `git_file_source.bitbucket_server_config` and `source_to_build.bitbucket_server_config` fields to `google_cloudbuild_trigger` resource
```

2023-08-03 17:53 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @hao-nan-li, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-08-03 18:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 137 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 137 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8544-old..auto-pr-8544) ( 3 files changed, 25 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 119 insertions(+))

2023-08-03 19:26 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2925` 
Passed tests `2616` 
Skipped tests: `302` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample|TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample|TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample|TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample|TestAccCloudBuildTrigger_cloudbuildTriggerManualExample|TestAccCloudBuildTrigger_basic_bitbucket|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-03 19:30 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_cloudbuildTriggerPubsubWithRepoExample.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_cloudbuildTriggerWebhookConfigExample.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_cloudbuildTriggerPubsubConfigExample.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerManualExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerManualExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_cloudbuildTriggerManualExample.log)]
`TestAccCloudBuildTrigger_basic_bitbucket`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_build/TestAccCloudBuildTrigger_basic_bitbucket_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording/TestAccCloudBuildTrigger_basic_bitbucket.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e46a4887-85b1-4df8-81ae-7f1047a6d73b/recording) for each test

2023-08-03 22:30 UTC, hao-nan-li requested changes
Looks like this introduced couple new failing tests, could you take a look into it?

2023-08-08 21:53 UTC, mariomachado94 commented
I expect the 2 Bitbucket tests to still fail:
TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample
TestAccCloudBuildTrigger_basic_bitbucket

Our api has the required feature for these tests behind an experiment. When we are close to launch I will allowlist the test projects and rerun the tests

2023-08-08 22:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 133 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 133 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8544-old..auto-pr-8544) ( 3 files changed, 25 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 119 insertions(+))

2023-08-08 23:34 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2940` 
Passed tests `2636` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudBuildTrigger_basic_bitbucket|TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-08 23:35 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccCloudBuildTrigger_basic_bitbucket`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/build-log/recording_build/TestAccCloudBuildTrigger_basic_bitbucket_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/recording/TestAccCloudBuildTrigger_basic_bitbucket.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/build-log/recording_build/TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/recording/TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/595ccb9c-6047-44e4-953c-16d4ec958b75/recording) for each test

2023-08-09 16:37 UTC, hao-nan-li commented
> I expect the 2 Bitbucket tests to still fail: TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample TestAccCloudBuildTrigger_basic_bitbucket
> 
> Our api has the required feature for these tests behind an experiment. When we are close to launch I will allowlist the test projects and rerun the tests

Thanks for the explanation. Do you plan to get your change merged and released anytime soon? Could we wait until these tests can get fixed before merging?

2023-08-10 14:18 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 133 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 133 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8544-old..auto-pr-8544) ( 3 files changed, 25 insertions(+), 3 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8544-old..auto-pr-8544) ( 4 files changed, 119 insertions(+))

2023-08-10 15:59 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2940` 
Passed tests `2636` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudBuildTrigger_basic_bitbucket|TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-10 16:01 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccCloudBuildTrigger_basic_bitbucket`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e16290a8-a3f0-47ad-a166-56aade89ecea/recording/TestAccCloudBuildTrigger_basic_bitbucket.log)]
`TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e16290a8-a3f0-47ad-a166-56aade89ecea/recording/TestAccCloudBuildTrigger_cloudbuildTriggerManualBitbucketServerExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e16290a8-a3f0-47ad-a166-56aade89ecea/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8544/artifacts/e16290a8-a3f0-47ad-a166-56aade89ecea/recording) for each test

2023-08-11 14:58 UTC, merged