Added support for versionAliases field in google_secret_manager_secret resource
GoogleCloudPlatform/magic-modules pull request #8555
Opened 2023-08-04 05:32 UTC by abheda-crest

Added support for `version_aliases` field in `google_secret_manager_secret` resource.

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [x] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [x] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [x] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
secretmanager: added `version_aliases` field to `google_secret_manager_secret` resource
```

2023-08-04 05:33 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a community contributor. @NickElliot, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-08-04 21:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 276 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 276 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 20 insertions(+), 3 deletions(-))

2023-08-04 23:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2932` 
Passed tests `2628` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSecretManagerSecret_versionAliasesUpdate|TestAccBigQueryDataTable_bigtable </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-04 23:16 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSecretManagerSecret_versionAliasesUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/fc6550be-d835-4cf1-8529-6579975a87e9/recording/TestAccSecretManagerSecret_versionAliasesUpdate.log)]
`TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/fc6550be-d835-4cf1-8529-6579975a87e9/recording/TestAccBigQueryDataTable_bigtable.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}} 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/fc6550be-d835-4cf1-8529-6579975a87e9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/fc6550be-d835-4cf1-8529-6579975a87e9/recording) for each test

2023-08-07 23:14 UTC, NickElliot reviewed
Looks good, but I want to clarify: is there a scenario you're trying to test for with the 5-step update test? The situation I assume of "you can add aliases and remove them" could be covered by a simpler 3-step test like there is for [annotations.](https://github.com/GoogleCloudPlatform/magic-modules/blob/c67a67923b62c07ffd8421eebb69369621870d5a/mmv1/third_party/terraform/tests/resource_secret_manager_secret_test.go.erb#L67)

2023-08-08 04:53 UTC, abheda-crest commented
> Looks good, but I want to clarify: is there a scenario you're trying to test for with the 5-step update test? The situation I assume of "you can add aliases and remove them" could be covered by a simpler 3-step test like there is for [annotations.](https://github.com/GoogleCloudPlatform/magic-modules/blob/c67a67923b62c07ffd8421eebb69369621870d5a/mmv1/third_party/terraform/tests/resource_secret_manager_secret_test.go.erb#L67)

Unlike the `annotations` field, we cannot provide the versionAliases field while creating the secret because the version alias can only be mapped to existing versions. Hence, the first step creates a secret without this field and multiple secret versions. The second step adds this field to the resource while the subsequent steps check various update scenarios such as updating keys, updating values, updating key-value pair, adding key-value pair, and removing key-value pair. The last step removes the entire `version_aliases` field from the resource.

2023-08-09 22:02 UTC, NickElliot requested changes
I see, thank you for the explanation! In that case, would it be possible to remove just the 4th step, as repeating the testAccSecretManagerSecret_versionAliasesBasic version is not testing any functionality not tested via the original Basic-Updated version? I.e. step 3 is doing a key update, value update, removal, and addition, while step 4 repeats the same four operation tests.

Because of how TPG creates API requests, the ordering of the fields in a list is irrelevant (they all get sent in alphabetical order of the keys), so there is not a scenario being tested via adding a KVP in the middle of the list vs the end (which appears to be the only distinction between the basic->updated and updated->basic scenarios).

2023-08-09 22:02 UTC, NickElliot commented on mmv1/third_party/terraform/tests/resource_secret_manager_secret_test.go.erb
> +				Config: testAccSecretManagerSecret_versionAliasesBasic(context),
```suggestion
```

2023-08-10 05:07 UTC, abheda-crest commented on mmv1/third_party/terraform/tests/resource_secret_manager_secret_test.go.erb
> +				Config: testAccSecretManagerSecret_versionAliasesBasic(context),
Okay, I've removed step 4 of this test.

2023-08-11 06:39 UTC, abheda-crest commented
@NickElliot Could you please start the tests as it is awaiting your approval and merge this PR?

2023-08-11 17:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 267 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 267 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8555-old..auto-pr-8555) ( 1 file changed, 17 insertions(+))

2023-08-11 18:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2944` 
Passed tests `2641` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSecretManagerSecret_versionAliasesUpdate </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-11 18:30 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSecretManagerSecret_versionAliasesUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/0928a421-33a2-4b7b-bc1b-b877b6754127/recording/TestAccSecretManagerSecret_versionAliasesUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/0928a421-33a2-4b7b-bc1b-b877b6754127/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/0928a421-33a2-4b7b-bc1b-b877b6754127/recording) for each test

2023-08-11 18:48 UTC, NickElliot approved these changes
LGTM!

2023-08-11 18:49 UTC, NickElliot commented
However it needs the merge conflict resolved now, sorry for the delay that caused that

2023-08-11 19:04 UTC, abheda-crest commented
> However it needs the merge conflict resolved now, sorry for the delay that caused that

No problem, I've resolved the merge conflict. Could you please trigger the tests again and merge this PR?

2023-08-11 19:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 267 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8555-old..auto-pr-8555) ( 3 files changed, 267 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8555-old..auto-pr-8555) ( 1 file changed, 17 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_secret_manager_secret` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_secret_manager_secret" "primary" {
  version_aliases = # value needed
}

```

2023-08-11 21:01 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2945` 
Passed tests `2643` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8555/artifacts/af297986-3199-4c35-b147-9f21d5920c9e/build-log/replaying_test.log)

2023-08-11 23:23 UTC, merged

2024-03-22 09:24 UTC, henry-chew-partior commented
> > Looks good, but I want to clarify: is there a scenario you're trying to test for with the 5-step update test? The situation I assume of "you can add aliases and remove them" could be covered by a simpler 3-step test like there is for [annotations.](https://github.com/GoogleCloudPlatform/magic-modules/blob/c67a67923b62c07ffd8421eebb69369621870d5a/mmv1/third_party/terraform/tests/resource_secret_manager_secret_test.go.erb#L67)
> 
> Unlike the `annotations` field, we cannot provide the versionAliases field while creating the secret because the version alias can only be mapped to existing versions. Hence, the first step creates a secret without this field and multiple secret versions. The second step adds this field to the resource while the subsequent steps check various update scenarios such as updating keys, updating values, updating key-value pair, adding key-value pair, and removing key-value pair. The last step removes the entire `version_aliases` field from the resource.

If version_alias can't be set during secrets creation, does it make more sense that the version_alias field should be implemented during creation of the secret version resource then?