Add provider default labels
GoogleCloudPlatform/magic-modules pull request #8670
Opened 2023-08-16 19:09 UTC by zli82016

If this PR is for Terraform, I acknowledge that I have:

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-08-16 19:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 21 files changed, 429 insertions(+), 95 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 24 files changed, 847 insertions(+), 198 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-16 20:43 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2599` 
Skipped tests: `307` 
Affected tests: `41` 

#### Action taken 
<details> <summary>Found 41 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccTags|TestAccEventarcTrigger_channel|TestAccEventarcTrigger_BasicHandWritten|TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample|TestAccComputeVpnTunnel_vpnTunnelBetaExample|TestAccComputeAddress_withProviderDefaultLabels|TestAccComputeForwardingRule_update|TestAccCloudRunService_foregroundDeletion|TestAccCloudRunService_cloudRunServiceCreateHasStatus|TestAccCloudRunService_cloudRunServiceUpdate|TestAccCloudRunService_cloudRunServiceMulticontainerExample|TestAccCloudRunService_secretVolume|TestAccCloudRunService_cloudRunServiceProbesExample|TestAccComputeGlobalForwardingRule_labels|TestAccCloudRunService_cloudRunServiceSecretVolumesExample|TestAccBigQueryDataset_bigqueryDatasetDefaultCollationSetExample|TestAccBigQueryDataset_bigqueryDatasetCaseInsensitiveNamesExample|TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample|TestAccBigQueryDataset_storageBillModel|TestAccBigQueryDataset_bigqueryDatasetAuthorizedDatasetExample|TestAccCloudRunService_cloudRunServiceMultipleEnvironmentVariablesExample|TestAccCloudRunService_cloudRunServiceNoauthExample|TestAccCloudRunService_cloudRunServiceSqlExample|TestAccCloudRunService_cloudRunServiceBasicExample|TestAccBigQueryDataset_bigqueryDatasetWithMaxTimeTravelHoursExample|TestAccCloudRunDomainMapping_foregroundDeletion|TestAccCloudRunDomainMapping_cloudRunDomainMappingBasicExample|TestAccComputeBackendService_regionNegBackend|TestAccBigQueryDataset_regionalLocation|TestAccBigQueryDataset_access|TestAccBigQueryDataset_datasetWithContents|TestAccBigQueryDataset_basic|TestAccCloudRunService_probes|TestAccCloudRunService_secretEnvironmentVariable|TestAccBigQueryDataset_bigqueryDatasetBasicExample|TestAccCloudRunServiceIamPolicyGenerated|TestAccCloudRunServiceIamMemberGenerated|TestAccCloudRunServiceIamBindingGenerated|TestAccDataSourceGoogleCloudRunService_basic|TestAccDataSourceRegionNetworkEndpointGroup_basic|TestAccDataSourceGoogleCloudRunService_optionalProject </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-16 21:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccTags.log)]
`TestAccEventarcTrigger_channel`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccEventarcTrigger_channel_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccEventarcTrigger_channel.log)]
`TestAccEventarcTrigger_BasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccEventarcTrigger_BasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccEventarcTrigger_BasicHandWritten.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample.log)]
`TestAccComputeVpnTunnel_vpnTunnelBetaExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccComputeVpnTunnel_vpnTunnelBetaExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccComputeVpnTunnel_vpnTunnelBetaExample.log)]
`TestAccComputeAddress_withProviderDefaultLabels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccComputeAddress_withProviderDefaultLabels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccComputeAddress_withProviderDefaultLabels.log)]
`TestAccComputeForwardingRule_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccComputeForwardingRule_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccComputeForwardingRule_update.log)]
`TestAccCloudRunService_foregroundDeletion`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_foregroundDeletion_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_foregroundDeletion.log)]
`TestAccCloudRunService_cloudRunServiceCreateHasStatus`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_cloudRunServiceCreateHasStatus_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_cloudRunServiceCreateHasStatus.log)]
`TestAccCloudRunService_cloudRunServiceUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_cloudRunServiceUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_cloudRunServiceUpdate.log)]
`TestAccCloudRunService_cloudRunServiceMulticontainerExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_cloudRunServiceMulticontainerExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_cloudRunServiceMulticontainerExample.log)]
`TestAccCloudRunService_secretVolume`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_secretVolume_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_secretVolume.log)]
`TestAccCloudRunService_cloudRunServiceProbesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_cloudRunServiceProbesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_cloudRunServiceProbesExample.log)]
`TestAccComputeGlobalForwardingRule_labels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccComputeGlobalForwardingRule_labels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccComputeGlobalForwardingRule_labels.log)]
`TestAccCloudRunService_cloudRunServiceSecretVolumesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccCloudRunService_cloudRunServiceSecretVolumesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccCloudRunService_cloudRunServiceSecretVolumesExample.log)]
`TestAccBigQueryDataset_bigqueryDatasetDefaultCollationSetExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccBigQueryDataset_bigqueryDatasetDefaultCollationSetExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/recording/TestAccBigQueryDataset_bigqueryDatasetDefaultCollationSetExample.log)]
`TestAccBigQueryDataset_bigqueryDatasetCaseInsensitiveNamesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/455e4f55-c353-45ac-b9bf-7ff1cb388ee2/build-log/recording_build/TestAccBigQueryDataset_bigqueryDatasetCaseInsensitiveNamesExample_recording_t [...]

2023-08-17 05:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 334 insertions(+), 101 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 682 insertions(+), 218 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 1 insertion(+), 102 deletions(-))

2023-08-17 05:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/546be0e0-5f6d-4347-9334-49387fc3545e/build-log/replaying_test.log)

2023-08-17 16:41 UTC, zli82016 commented
/gcbrun

2023-08-17 16:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 334 insertions(+), 101 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 682 insertions(+), 218 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 1 insertion(+), 102 deletions(-))

2023-08-17 16:51 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/cc0932ac-61dd-457f-a46d-b17b32c83c82/build-log/replaying_test.log)

2023-08-17 21:54 UTC, c2thorn commented
Noting that this fixes https://github.com/hashicorp/terraform-provider-google/issues/7325

2023-08-18 04:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 391 insertions(+), 101 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 784 insertions(+), 212 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-18 05:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 409 insertions(+), 119 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 802 insertions(+), 230 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 8 files changed, 115 insertions(+), 114 deletions(-))

2023-08-18 06:38 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccTags`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccTags_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccTags.log)]
`TestAccEventarcTrigger_channel`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccEventarcTrigger_channel_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccEventarcTrigger_channel.log)]
`TestAccEventarcTrigger_BasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccEventarcTrigger_BasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccEventarcTrigger_BasicHandWritten.log)]
`TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccComputeRegionNetworkEndpointGroup_regionNetworkEndpointGroupCloudrunExample.log)]
`TestAccComputeAddress_withProviderDefaultLabels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccComputeAddress_withProviderDefaultLabels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccComputeAddress_withProviderDefaultLabels.log)]
`TestAccCloudRunService_cloudRunServiceMulticontainerExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceMulticontainerExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceMulticontainerExample.log)]
`TestAccCloudRunService_probes`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_probes_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_probes.log)]
`TestAccCloudRunService_secretEnvironmentVariable`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_secretEnvironmentVariable_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_secretEnvironmentVariable.log)]
`TestAccCloudRunService_secretVolume`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_secretVolume_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_secretVolume.log)]
`TestAccCloudRunService_foregroundDeletion`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_foregroundDeletion_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_foregroundDeletion.log)]
`TestAccCloudRunService_cloudRunServiceCreateHasStatus`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceCreateHasStatus_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceCreateHasStatus.log)]
`TestAccCloudRunService_cloudRunServiceProbesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceProbesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceProbesExample.log)]
`TestAccCloudRunService_cloudRunServiceUpdate`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceUpdate_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceUpdate.log)]
`TestAccCloudRunService_cloudRunServiceSecretVolumesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceSecretVolumesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceSecretVolumesExample.log)]
`TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceSecretEnvironmentVariablesExample.log)]
`TestAccCloudRunService_cloudRunServiceMultipleEnvironmentVariablesExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build-log/recording_build/TestAccCloudRunService_cloudRunServiceMultipleEnvironmentVariablesExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/recording/TestAccCloudRunService_cloudRunServiceMultipleEnvironmentVariablesExample.log)]
`TestAccCloudRunService_cloudRunServiceNoauthExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/7ade7ad2-791b-479b-9a9b-d498307c2a9c/build- [...]

2023-08-18 23:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 20 files changed, 384 insertions(+), 97 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 25 files changed, 807 insertions(+), 205 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-19 00:59 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2633` 
Skipped tests: `307` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeForwardingRule_update|TestAccComputeAddress_withProviderDefaultLabels|TestAccBigQueryDataset_datasetWithContents|TestAccBigQueryDataset_basic|TestAccBigQueryDataset_storageBillModel|TestAccBigQueryDataset_regionalLocation|TestAccBigQueryDataset_access </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-19 01:02 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeForwardingRule_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccComputeForwardingRule_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccComputeForwardingRule_update.log)]
`TestAccComputeAddress_withProviderDefaultLabels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccComputeAddress_withProviderDefaultLabels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccComputeAddress_withProviderDefaultLabels.log)]
`TestAccBigQueryDataset_datasetWithContents`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccBigQueryDataset_datasetWithContents_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccBigQueryDataset_datasetWithContents.log)]
`TestAccBigQueryDataset_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccBigQueryDataset_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccBigQueryDataset_basic.log)]
`TestAccBigQueryDataset_storageBillModel`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccBigQueryDataset_storageBillModel_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccBigQueryDataset_storageBillModel.log)]
`TestAccBigQueryDataset_regionalLocation`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccBigQueryDataset_regionalLocation_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccBigQueryDataset_regionalLocation.log)]
`TestAccBigQueryDataset_access`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_build/TestAccBigQueryDataset_access_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording/TestAccBigQueryDataset_access.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3a35fbeb-9c8f-4cd6-b5ad-17ab6b278bfe/recording) for each test

2023-08-21 22:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 402 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 825 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-22 00:27 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2639` 
Skipped tests: `307` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAddress_withProviderDefaultLabels </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-22 00:29 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeAddress_withProviderDefaultLabels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/9941f740-cb93-462c-b0e8-7780742a9d27/build-log/recording_build/TestAccComputeAddress_withProviderDefaultLabels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/9941f740-cb93-462c-b0e8-7780742a9d27/recording/TestAccComputeAddress_withProviderDefaultLabels.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/9941f740-cb93-462c-b0e8-7780742a9d27/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/9941f740-cb93-462c-b0e8-7780742a9d27/recording) for each test

2023-08-22 15:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 406 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 829 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-22 16:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2639` 
Skipped tests: `307` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAddress_withProviderDefaultLabels </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-22 20:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 410 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 833 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-22 21:59 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2639` 
Skipped tests: `307` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeAddress_withProviderDefaultLabels </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-22 22:00 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeAddress_withProviderDefaultLabels`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/705307c9-5afd-471d-a1bd-4ceca67c01ba/build-log/recording_build/TestAccComputeAddress_withProviderDefaultLabels_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/705307c9-5afd-471d-a1bd-4ceca67c01ba/recording/TestAccComputeAddress_withProviderDefaultLabels.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/705307c9-5afd-471d-a1bd-4ceca67c01ba/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/705307c9-5afd-471d-a1bd-4ceca67c01ba/recording) for each test

2023-08-22 22:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 403 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 829 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-23 00:09 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2639` 
Skipped tests: `308` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/db12abd0-5c3f-4213-bda2-a4f153cf7176/build-log/replaying_test.log)

2023-08-23 17:00 UTC, rileykarson approved these changes

2023-08-23 17:34 UTC, zli82016 commented on mmv1/third_party/terraform/fwprovider/framework_provider.go.erb
> +				Optional:    true,
Good catch.

2023-08-23 17:35 UTC, melinath requested changes
Regarding the TGC failures - it looks like this PR renames `labels` fields to `terraform_labels`; if that's correct, I believe the fix here would be to modify the [TGC test files for impacted resources](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/tgc/tests/data) so that:

- the `.tf` file uses `terraform_labels`
- the `.tfplan.json` file reflects the `terraform_labels` name as well. This should just be a string replacement but you could copy the .tf file to a new directory and run `terraform plan` to verify if there are any issues.

Once you've made those changes, the expander should be able to automatically convert the `terraform_labels` value to a `labels` value in the CAI resource (which means it should match the existing expected CAI output.)

2023-08-23 17:49 UTC, zli82016 commented
> Regarding the TGC failures - it looks like this PR renames `labels` fields to `terraform_labels`; if that's correct, I believe the fix here would be to modify the [TGC test files for impacted resources](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/tgc/tests/data) so that:
> 
> * the `.tf` file uses `terraform_labels`
> * the `.tfplan.json` file reflects the `terraform_labels` name as well. This should just be a string replacement but you could copy the .tf file to a new directory and run `terraform plan` to verify if there are any issues.
> 
> Once you've made those changes, the expander should be able to automatically convert the `terraform_labels` value to a `labels` value in the CAI resource (which means it should match the existing expected CAI output.)

For the users, only `labels` field is provided in the configuration. `terraform_labels` will be added to the terraform plan by the provider.

2023-08-23 17:57 UTC, melinath commented
hm, in that case the configurations should stay the same. It would be good to see what you get when you generate the `tfplan.json` files - the process for generating that file is described at https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/main/docs/contributing/add_new_resource.md#2-adding-new-tests

2023-08-23 17:58 UTC, melinath commented
Hopefully the `tfplan.json` files will automatically have `terraform_labels` present; if not, this will be more complex to fix and I'll need to take a closer look.

2023-08-23 18:38 UTC, zli82016 commented
I haven't try the process in the link https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/main/docs/contributing/add_new_resource.md#2-adding-new-tests

But when I generate tgc locally with the command `make tgc OUTPUT_PATH=~/Documents/workspace/terraform-google-conversion/tfplan2cai`. There are not `terraform_labels` field in [tfplan.json](https://paste.googleplex.com/4546126521827328) file.

2023-08-23 18:44 UTC, melinath commented
please try the process I linked to update the files in Magic Modules - that needs to happen for downstream generation to work properly.

2023-08-23 18:45 UTC, zli82016 commented on mmv1/templates/terraform/examples/base_configs/test_file.go.erb
> +      .select{|p| p.url_param_only || p.ignore_read || p.is_a?(Api::Type::ResourceRef) || p.is_a?(Api::Type::KeyValueLabels) || p.is_a?(Api::Type::KeyValueAnnotations) || p.name == 'terraformLabels'}
Yeah, the new type is better. I will add a new type `KeyValueTerraformLabels `

2023-08-23 20:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 403 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 829 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-23 21:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2947` 
Passed tests `2639` 
Skipped tests: `308` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/deaa5498-34f4-4ca1-a4c8-ecbfda369a7c/build-log/replaying_test.log)

2023-08-24 17:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 28 files changed, 533 insertions(+), 154 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 33 files changed, 963 insertions(+), 263 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 10 files changed, 247 insertions(+), 222 deletions(-))

2023-08-24 17:22 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/8a6efefb-6b02-4023-af1d-af71ba7ad5ae/build-log/replaying_test.log)

2023-08-24 17:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 26 files changed, 501 insertions(+), 150 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 31 files changed, 931 insertions(+), 259 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 9 files changed, 246 insertions(+), 218 deletions(-))

2023-08-24 17:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `1` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/4484a92f-da08-47dc-b9ae-210cdff7b35a/build-log/replaying_test.log)

2023-08-24 18:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 403 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 829 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 7 files changed, 97 insertions(+), 96 deletions(-))

2023-08-24 18:17 UTC, zli82016 commented
Rebased the 5.0.0 branch to address conflicts.

2023-08-24 19:38 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2995` 
Passed tests `2691` 
Skipped tests: `302` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataLossPreventionJobTrigger_dlpJobTriggerInspectCustomInfoTypes|TestAccProjectIamPolicy_invalidMembers </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-24 19:44 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataLossPreventionJobTrigger_dlpJobTriggerInspectCustomInfoTypes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/4d0b9aa1-6fef-4ebf-a34e-19d46fdb5175/recording/TestAccDataLossPreventionJobTrigger_dlpJobTriggerInspectCustomInfoTypes.log)]
`TestAccProjectIamPolicy_invalidMembers`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/4d0b9aa1-6fef-4ebf-a34e-19d46fdb5175/recording/TestAccProjectIamPolicy_invalidMembers.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/4d0b9aa1-6fef-4ebf-a34e-19d46fdb5175/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/4d0b9aa1-6fef-4ebf-a34e-19d46fdb5175/recording) for each test

2023-08-24 20:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 403 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 829 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 6 files changed, 96 insertions(+), 96 deletions(-))

2023-08-24 20:44 UTC, rileykarson commented
Is the issue with `terraform_labels` or with `labels`? I see the TGC failures looking for a `labels` value and not finding it.

2023-08-24 20:57 UTC, zli82016 commented
> Is the issue with `terraform_labels` or with `labels`? I see the TGC failures looking for a `labels` value and not finding it.



> Is the issue with `terraform_labels` or with `labels`? I see the TGC failures looking for a `labels` value and not finding it.

This is the new generated bigquery dataset converter file. https://github.com/modular-magician/terraform-google-conversion/blob/9b1045201b1d732ab4740388ace5844fb210efb7/tfplan2cai/converters/google/resources/services/bigquery/bigquery_dataset.go#L159

The value `labels` is from expanding `terraform_labels`. Based on my understanding, the schema in the google-beta provider used in tgc doesn't have `terraform_labels` field yet, so the generated fake resource data (d) doesn't have `terraform_labels` field.

This issue could be fixed after merged back to the main branch.

2023-08-24 21:26 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2995` 
Passed tests `2693` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/c754002a-d5bf-4ba1-a9a5-aec999a3f6d7/build-log/replaying_test.log)

2023-08-24 21:36 UTC, zli82016 commented
I can remove the `labels` field from the testdata files to not break tgc. And then check if the issue still persists after merging back to the main branch.

2023-08-25 18:24 UTC, melinath requested changes
I've looked into this a little more closely & tried to regenerate the test files to see if that resolves the issue. The test generation docs are woefully out of date and need to be updated.

However, I was able to confirm that:

1. `terraform_labels` should be set in the tfplan.json files
2. If `terraform_labels` is set in the tfplan.json files, the converted CAI will include the correct `labels` value.

So the fix here is: For all [`*.tfplan.json` files for impacted resources](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/tgc/tests/data), duplicate the existing `labels` value as `terraform_labels`. That should resolve the issue.

2023-09-05 20:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 379 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 805 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 10 files changed, 124 insertions(+), 96 deletions(-))

2023-09-05 21:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3003` 
Passed tests `2701` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/0efcd5c3-1fb4-4073-a2ac-5248b8fb5b52/build-log/replaying_test.log)

2023-09-05 21:21 UTC, zli82016 commented
> Details

Hello, @melinath , thanks for the comments. I think that is what I tried before. `terraform-google-conversion-test-integration-0.12.31` and  `terraform-google-conversion-test-integration-0.13.7` still failed.

2023-09-05 21:54 UTC, zli82016 commented
I think  [the previous comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/8670#issuecomment-1692396646) could be reason.

2023-09-05 23:11 UTC, melinath commented
It looks to me like this ought to be passing at this point. The unit tests are passing; if this were a fundamental issue then I would expect them to also be failing. I'm going to try rerunning tests to see if that resolves the issue.

/gcbrun

2023-09-05 23:22 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 23 files changed, 379 insertions(+), 118 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 28 files changed, 810 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 10 files changed, 124 insertions(+), 96 deletions(-))

2023-09-06 00:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3003` 
Passed tests `2700` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSpannerInstanceIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-06 00:35 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSpannerInstanceIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3739b2bf-bb7a-4b2f-b8c7-13776c0b0e18/recording/TestAccSpannerInstanceIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3739b2bf-bb7a-4b2f-b8c7-13776c0b0e18/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/3739b2bf-bb7a-4b2f-b8c7-13776c0b0e18/recording) for each test

2023-09-06 00:39 UTC, zli82016 commented
terraform-google-conversion-test-integration-0.12.31 and terraform-google-conversion-test-integration-0.13.7 still failed. Close and reopen this PR to see if the tests will pass.

2023-09-06 00:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 379 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 805 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 10 files changed, 124 insertions(+), 96 deletions(-))

2023-09-06 02:01 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3003` 
Passed tests `2701` 
Skipped tests: `302` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/236d2e50-eb7e-43bd-9a4b-4c86d090518d/build-log/replaying_test.log)

2023-09-06 16:49 UTC, melinath approved these changes

2023-09-06 16:53 UTC, rileykarson requested changes
Marking requested as I'll make a final pass after some of the changes

2023-09-06 16:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8670-old..auto-pr-8670) ( 22 files changed, 379 insertions(+), 113 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8670-old..auto-pr-8670) ( 27 files changed, 805 insertions(+), 221 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8670-old..auto-pr-8670) ( 10 files changed, 124 insertions(+), 96 deletions(-))

2023-09-06 18:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3003` 
Passed tests `2700` 
Skipped tests: `302` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocJobIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-06 18:21 UTC, rileykarson approved these changes

2023-09-06 18:24 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocJobIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/6d527eba-b0f6-4a94-8294-834fa083564e/recording/TestAccDataprocJobIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/6d527eba-b0f6-4a94-8294-834fa083564e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8670/artifacts/6d527eba-b0f6-4a94-8294-834fa083564e/recording) for each test

2023-09-06 18:41 UTC, merged