Fix issue #15555: Set `send_empty_value` for noWrapper.writeMetadata
GoogleCloudPlatform/magic-modules pull request #8739
Opened 2023-08-22 21:16 UTC by ORabbit

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
pubsub: fixed the ability to set noWrapper.writeMetadata to false not being propagated to the API.
```

2023-08-22 21:17 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@ScottSuarez, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-08-22 21:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-08-22 21:38 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 65 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 65 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-08-22 22:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2985` 
Passed tests `2685` 
Skipped tests: `295` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigQueryDataTable_bigtable|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample|TestAccPubsubSubscription_pushNoWrapperEmpty </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-22 22:58 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording/TestAccBigQueryDataTable_bigtable.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pushNoWrapperEmpty`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/build-log/recording_build/TestAccPubsubSubscription_pushNoWrapperEmpty_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording/TestAccPubsubSubscription_pushNoWrapperEmpty.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/ced13365-7790-42f4-8931-bce3b58c36bb/recording) for each test

2023-08-23 16:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 66 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 66 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 2 insertions(+), 2 deletions(-))

2023-08-23 17:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 65 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 65 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-08-23 17:41 UTC, ORabbit commented
> Waiting on acceptance tests. In the meantime is there an existing bug or issues associated with this ?
> 
> Concept seems fine

b/296582112 / https://github.com/hashicorp/terraform-provider-google/issues/15555

2023-08-23 18:13 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2988` 
Passed tests `2686` 
Skipped tests: `296` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccBigQueryDataTable_bigtable|TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample|TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample|TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample|TestAccDataprocClusterIamPolicy|TestAccPubsubSubscription_pushNoWrapperEmpty </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-23 18:25 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigQueryDataTable_bigtable.log)]
`TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)]
`TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)]
`TestAccDataprocClusterIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccDataprocClusterIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pushNoWrapperEmpty`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/build-log/recording_build/TestAccPubsubSubscription_pushNoWrapperEmpty_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccPubsubSubscription_pushNoWrapperEmpty.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording) for each test

2023-08-23 19:29 UTC, ScottSuarez commented
> Tests passed during RECORDING mode: `TestAccBigQueryDataTable_bigtable`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigQueryDataTable_bigtable.log)] `TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileAnyclusterExample.log)] `TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileSingleclusterExample.log)] `TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccBigtableAppProfile_bigtableAppProfileMulticlusterExample.log)] `TestAccDataprocClusterIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccDataprocClusterIamPolicy.log)]
> 
> ##### Rerun these tests in REPLAYING mode to catch issues
> No issues found for passed tests after REPLAYING rerun.
> 
> Tests failed during RECORDING mode: `TestAccPubsubSubscription_pushNoWrapperEmpty`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/build-log/recording_build/TestAccPubsubSubscription_pushNoWrapperEmpty_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording/TestAccPubsubSubscription_pushNoWrapperEmpty.log)]
> 
> Please fix these to complete your PR. View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cd593b8c-57ae-4791-a77d-e48bdbea5fcd/recording) for each test



Looks like this is an API issue. We are setting the value and the API isn't returning it. We won't be able to resolve this without changes in the API.

2023-08-23 19:29 UTC, ScottSuarez requested changes
Need API changes to support

2023-08-25 16:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change Detection Failed
The breaking change detector crashed during execution. This is usually due to the downstream provider(s) failing to compile. Please investigate or follow up with your reviewer.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-08-25 16:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change Detection Failed
The breaking change detector crashed during execution. This is usually due to the downstream provider(s) failing to compile. Please investigate or follow up with your reviewer.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-08-25 19:07 UTC, ScottSuarez commented
Let me know if there is anything I can help with

2023-09-01 19:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change Detection Failed
The breaking change detector crashed during execution. This is usually due to the downstream provider(s) failing to compile. Please investigate or follow up with your reviewer.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 69 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-01 19:25 UTC, ScottSuarez commented
Looks like a compilation issue, Let me know if you need any help

2023-09-05 21:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Breaking Change Detection Failed
The breaking change detector crashed during execution. This is usually due to the downstream provider(s) failing to compile. Please investigate or follow up with your reviewer.

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 68 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 68 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-05 22:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 68 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 68 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-05 22:33 UTC, ScottSuarez commented
Could you pull the latest changes from main? Not clear why TGC is failing

2023-09-05 23:24 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3009` 
Passed tests `2711` 
Skipped tests: `296` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccProjectIamPolicy_invalidMembers </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-05 23:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccProjectIamPolicy_invalidMembers`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/77614227-3f7a-475b-86f3-2bbd2980f903/recording/TestAccProjectIamPolicy_invalidMembers.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pushNoWrapperEmpty`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/77614227-3f7a-475b-86f3-2bbd2980f903/build-log/recording_build/TestAccPubsubSubscription_pushNoWrapperEmpty_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/77614227-3f7a-475b-86f3-2bbd2980f903/recording/TestAccPubsubSubscription_pushNoWrapperEmpty.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/77614227-3f7a-475b-86f3-2bbd2980f903/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/77614227-3f7a-475b-86f3-2bbd2980f903/recording) for each test

2023-09-06 17:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3012` 
Passed tests `2713` 
Skipped tests: `296` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccPubsubSubscription_pushNoWrapper|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-06 17:03 UTC, modular-magician commented
$\textcolor{red}{\textsf{The provider crashed while running the VCR tests in RECORDING mode}}$ 
$\textcolor{red}{\textsf{Please fix it to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/59f05d90-f6d7-4a5b-8bc9-b034ff35a134/build-log/recording_test.log)

2023-09-06 18:32 UTC, ScottSuarez commented
panic crash from the VCR

```
panic: Invalid address to set: []string{"push_config", "0", "no_wrapper", "0", "writeMetadata"}
```

2023-09-06 18:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 71 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 71 insertions(+), 9 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-06 20:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3015` 
Passed tests `2717` 
Skipped tests: `296` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccPubsubSubscription_pushNoWrapperEmpty|TestAccPubsubSubscription_pushNoWrapper </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-06 20:13 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pushNoWrapperEmpty`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/25597761-dca7-474d-830e-0d49b112b2e3/recording/TestAccPubsubSubscription_pushNoWrapperEmpty.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccPubsubSubscription_pushNoWrapper`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/25597761-dca7-474d-830e-0d49b112b2e3/build-log/recording_build/TestAccPubsubSubscription_pushNoWrapper_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/25597761-dca7-474d-830e-0d49b112b2e3/recording/TestAccPubsubSubscription_pushNoWrapper.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/25597761-dca7-474d-830e-0d49b112b2e3/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/25597761-dca7-474d-830e-0d49b112b2e3/recording) for each test

2023-09-06 21:45 UTC, ScottSuarez requested changes

2023-09-06 21:45 UTC, ScottSuarez commented on mmv1/templates/terraform/custom_flatten/pubsub_no_wrapper_write_metadata_flatten.go.erb
> +	}
```suggestion
	if original["writeMetadata"] == nil {
		transformed["write_metadata"] = false
	} else {
		transformed["write_metadata"] =  original["writeMetadata"]
	}
```

Looks like the value isn't getting set now in the case of true. This should fix it.

2023-09-07 14:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-07 14:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-07 15:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8739-old..auto-pr-8739) ( 2 files changed, 73 insertions(+), 9 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8739-old..auto-pr-8739) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-09-07 17:03 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3018` 
Passed tests `2721` 
Skipped tests: `297` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8739/artifacts/cfbe9d10-e3b6-4acb-bb34-fd3ad302e625/build-log/replaying_test.log)

2023-09-07 17:37 UTC, ScottSuarez approved these changes

2023-09-07 17:38 UTC, merged