Fix TestAccDataformRepositoryReleaseConfig_dataformRepositoryReleaseC
GoogleCloudPlatform/magic-modules pull request #8764
Opened 2023-08-25 00:44 UTC by ScottSuarez

fixes two tests TestAccDataformRepositoryReleaseConfig_dataformRepositoryReleaseConfigExample

test error

```
        Error: Error creating Secret: googleapi: Error 409: Secret [projects/****/secrets/secret] already exists.
          with google_secret_manager_secret.secret,
          on terraform_plugin_test.tf line 7, in resource "google_secret_manager_secret" "secret":
           7: resource "google_secret_manager_secret" "secret" {

```
**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-08-25 00:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8764-old..auto-pr-8764) ( 2 files changed, 2 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8764-old..auto-pr-8764) ( 4 files changed, 4 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8764-old..auto-pr-8764) ( 2 files changed, 2 insertions(+), 2 deletions(-))

2023-08-25 02:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2988` 
Passed tests `2689` 
Skipped tests: `296` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataformRepositoryReleaseConfig_dataformRepositoryReleaseConfigExample|TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample|TestAccFolderIamPolicy_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-25 02:09 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataformRepositoryReleaseConfig_dataformRepositoryReleaseConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/recording/TestAccDataformRepositoryReleaseConfig_dataformRepositoryReleaseConfigExample.log)]
`TestAccFolderIamPolicy_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/recording/TestAccFolderIamPolicy_basic.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/build-log/recording_build/TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/recording/TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/ac64df83-7620-4010-8773-4b8ddf86cff6/recording) for each test

2023-08-25 21:00 UTC, melinath approved these changes

2023-08-25 21:02 UTC, melinath requested changes

2023-08-25 21:02 UTC, melinath commented on mmv1/templates/terraform/examples/dataform_repository_workflow_config.tf.erb
> +  secret_id = "<%= ctx[:vars]['my_secret'] %>"
```suggestion
  secret_id = "<%= ctx[:vars]['secret_name'] %>"
```

2023-08-25 23:43 UTC, ScottSuarez commented on mmv1/templates/terraform/examples/dataform_repository_workflow_config.tf.erb
> +  secret_id = "<%= ctx[:vars]['my_secret'] %>"
Ah thanks for this !

2023-08-25 23:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8764-old..auto-pr-8764) ( 2 files changed, 2 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8764-old..auto-pr-8764) ( 4 files changed, 4 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-8764-old..auto-pr-8764) ( 2 files changed, 2 insertions(+), 2 deletions(-))

2023-08-26 01:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2990` 
Passed tests `2693` 
Skipped tests: `296` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-08-26 01:06 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/a73a0b4f-bdb2-4752-a06d-3ffc576a1cf8/recording/TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/a73a0b4f-bdb2-4752-a06d-3ffc576a1cf8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8764/artifacts/a73a0b4f-bdb2-4752-a06d-3ffc576a1cf8/recording) for each test

2023-08-28 16:18 UTC, melinath approved these changes
lgtm

2023-08-28 20:57 UTC, merged