Transfer tgc/cai2hcl ownership to magic-modules
GoogleCloudPlatform/magic-modules pull request #8824
Opened 2023-08-31 17:38 UTC by amirkaromashkin

This change moves tgc/cai2hcl management to magic-modules/mmv1 using new provider, which will then be used for generated cai2hcl converters.

```release-note:note
terraform-google-conversion/cai2hcl folder is now managed from GCP/magic-modules
```

2023-08-31 17:38 UTC, modular-magician commented
Oops! It looks like no changelog entry is attached to this PR. Please include a release note block in the PR body, as described in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md:

~~~
```release-note:TYPE
Release note
```
~~~

2023-08-31 17:39 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@roaks3, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-08-31 17:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-08-31 18:04 UTC, modular-magician commented
Oops! It looks like you're using an unknown release-note type in your changelog entries:
* TYPE

Please only use the types listed in https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/RELEASE_NOTES_GUIDE.md.

2023-08-31 18:57 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3008` 
Passed tests `2712` 
Skipped tests: `296` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/c1594c3d-03e0-4aa6-9c5f-0c0184c96bdb/build-log/replaying_test.log)

2023-09-03 14:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8824-old..auto-pr-8824) ( 24 files changed, 801 insertions(+), 272 deletions(-))

2023-09-03 15:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3008` 
Passed tests `2709` 
Skipped tests: `296` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocJobIamPolicy|TestAccHealthcareDatasetIamPolicy|TestAccSpannerDatabaseIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-03 16:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocJobIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/9eb43c21-b6f7-4bc1-9ef9-37b4a85999fb/recording/TestAccDataprocJobIamPolicy.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/9eb43c21-b6f7-4bc1-9ef9-37b4a85999fb/recording/TestAccHealthcareDatasetIamPolicy.log)]
`TestAccSpannerDatabaseIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/9eb43c21-b6f7-4bc1-9ef9-37b4a85999fb/recording/TestAccSpannerDatabaseIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/9eb43c21-b6f7-4bc1-9ef9-37b4a85999fb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/9eb43c21-b6f7-4bc1-9ef9-37b4a85999fb/recording) for each test

2023-09-06 11:46 UTC, roaks3 commented
@amirkaromashkin I'm a little surprised by this change, but I may be missing context. Do you have an internal issue tracking this work, or have you been working with a member of our team on this?

2023-09-07 18:32 UTC, melinath commented
@roaks3 I've been talking with Amir about this change - this PR should make MM take over management of cai2hcl with no diffs - other changes would ideally be in other PRs (but I believe some of these changes were necessary here as part of bringing the files under managment.)

2023-09-08 14:23 UTC, roaks3 reviewed
Ok, got it, and I reviewed the internal doc. I took a first pass and things looked good, but to help with review, am I correct in assuming that `mmv1/third_party/cai2hcl` files are copied verbatim from somewhere?

2023-09-08 14:23 UTC, roaks3 commented on mmv1/provider/terraform_tgc_cai2hcl.rb
> +# Copyright 2017 Google Inc.
Nit: 2023

2023-09-08 16:23 UTC, amirkaromashkin commented
> Ok, got it, and I reviewed the internal doc. I took a first pass and things looked good, but to help with review, am I correct in assuming that `mmv1/third_party/cai2hcl` files are copied verbatim from somewhere?

Its not completely verbatim. Its a slightly refactored version of https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/main/cai2hcl: converters themselves were not changed, I changed packages/folder structure and helper methods like convert.go.

Testdata files copied from https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/main/testdata as is.

2023-09-08 16:50 UTC, amirkaromashkin commented on mmv1/provider/terraform_tgc_cai2hcl.rb
> +# Copyright 2017 Google Inc.
Done

2023-09-08 16:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8824-old..auto-pr-8824) ( 23 files changed, 709 insertions(+), 219 deletions(-))

2023-09-08 17:30 UTC, edisonhuang-google commented
LGTM

2023-09-08 20:53 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8824-old..auto-pr-8824) ( 22 files changed, 667 insertions(+), 177 deletions(-))

2023-09-08 22:04 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3020` 
Passed tests `2723` 
Skipped tests: `297` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8824/artifacts/f0fec2f3-ff8d-425d-8476-9aa3b1424810/build-log/replaying_test.log)

2023-09-11 23:34 UTC, roaks3 commented
I just tried to take another look here and this is very hard to review with the assumption that everything is newly written (you mentioned that some refactoring happened). Could you please provide some more context on what was changed (and perhaps why)? Where should I be looking for changes to the previous behavior vs. parts that are copy-and-pasted?

2023-09-12 10:33 UTC, amirkaromashkin commented
> I just tried to take another look here and this is very hard to review with the assumption that everything is newly written (you mentioned that some refactoring happened). Could you please provide some more context on what was changed (and perhaps why)? Where should I be looking for changes to the previous behavior vs. parts that are copy-and-pasted?

I guess there are 2 ways to handle it:
1. I give the broad explanation of all the changes and refactoring I made to the https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/main/cai2hcl
2. I first manually update the target repo, get it merged and then this migration will be verbatim (I'll need to give explanations there, but this will be less complicated)

I guess the 2nd option looks better. WDYT? @roaks3

2023-09-12 15:19 UTC, amirkaromashkin commented
> > I just tried to take another look here and this is very hard to review with the assumption that everything is newly written (you mentioned that some refactoring happened). Could you please provide some more context on what was changed (and perhaps why)? Where should I be looking for changes to the previous behavior vs. parts that are copy-and-pasted?
> 
> I guess there are 2 ways to handle it:
> 
> 1. I give the broad explanation of all the changes and refactoring I made to the https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/main/cai2hcl
> 2. I first manually update the target repo, get it merged and then this migration will be verbatim (I'll need to give explanations there, but this will be less complicated)
> 
> I guess the 2nd option looks better. WDYT? @roaks3

I have just found a slight bug in a folder structure when started to implement the Option2. So I believe its  a better approach. On it.

2023-09-12 15:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8824-old..auto-pr-8824) ( 22 files changed, 667 insertions(+), 177 deletions(-))

2023-09-12 16:15 UTC, roaks3 commented
Yea, I think the second option would be ideal here. Thanks!

2023-09-12 19:35 UTC, roaks3 commented
Passing over to @melinath as I will likely be on PTO when this is ready for another look

2023-09-13 18:13 UTC, melinath commented
https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/1416 is the PR to refactor TGC first.

2023-09-19 16:19 UTC, melinath requested changes
Refactor of TGC is complete - marking this as reviewed pending updates to match the final structure we settled on.

2023-09-22 13:36 UTC, amirkaromashkin commented
> Refactor of TGC is complete - marking this as reviewed pending updates to match the final structure we settled on.

Done. Now it should produce zero diff

2023-09-22 13:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-09-26 17:00 UTC, melinath approved these changes
LGTM

2023-09-26 17:01 UTC, merged