add google_logging_metric to version 5 upgrade doc for #8780
GoogleCloudPlatform/magic-modules pull request #8836
Opened 2023-09-01 03:45 UTC by pengq-google

If this PR is for Terraform, I acknowledge that I have:

- [X] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [X] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [X] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [X] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [X] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:note
add google_logging_metric to version 5 upgrade doc for #8780
```

2023-09-01 03:46 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@SarahFrench, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-09-01 03:50 UTC, pengq-google commented
@c2thorn This is the major release doc change for #8780 
Thanks for your help along the way!

2023-09-01 03:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8836-old..auto-pr-8836) ( 1 file changed, 14 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8836-old..auto-pr-8836) ( 1 file changed, 14 insertions(+))

2023-09-06 15:15 UTC, c2thorn requested changes

2023-09-06 15:15 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/guides/version_5_upgrade.html.markdown
> +### Additional fields are now required metrics with `value_type = "DISTRIBUTION"`
```suggestion
### Additional `bucket_options` subfields are now properly required
```

2023-09-06 15:15 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/guides/version_5_upgrade.html.markdown
> +### Additional fields are now required metrics with `value_type = "DISTRIBUTION"`
as the PR is written, the `value_type` does not determine if the fields are required.

2023-09-06 15:15 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/guides/version_5_upgrade.html.markdown
> +For log-based metrics with `value_type = "DISTRIBUTION"`, additional fields are now required depending on the `bucket_options` block:
```suggestion
When setting the `bucket_options` block, the following fields may be required:
```

2023-09-06 15:15 UTC, c2thorn commented on mmv1/third_party/terraform/website/docs/guides/version_5_upgrade.html.markdown
> +* `bounds` is now required when `bucket_options` is set to be `explicit_buckets`.
```suggestion
* `num_finite_buckets`, `width`, and `offset` are now required when `bucket_options.linear_buckets` is set.

* `num_finite_buckets`, `growth_factor`, and `scale` are now required when `bucket_options.exponential_buckets` is set.
```
the `bounds` requirement was not added in the 5.0.0 PR?

2023-09-06 17:03 UTC, c2thorn commented
I believe this has failed because there are now conflicts @pengq-google

2023-09-07 16:40 UTC, pengq-google commented
replaced by https://github.com/GoogleCloudPlatform/magic-modules/pull/8886

2023-09-07 16:40 UTC, closed without merging