Enabling Membership resource to be regionalized with global as default value
GoogleCloudPlatform/magic-modules pull request #8994
Opened 2023-09-19 00:08 UTC by sahsagar-google

https://github.com/hashicorp/terraform-provider-google/issues/15882

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
GKEHub: added `location` field to `google_gke_hub_membership` resource
```

2023-09-19 00:10 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@melinath, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-09-19 00:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 139 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 139 insertions(+), 19 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8994-old..auto-pr-8994) ( 3 files changed, 30 insertions(+), 3 deletions(-))

2023-09-19 01:32 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3070` 
Passed tests `2766` 
Skipped tests: `299` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubMembership_gkehubMembershipRegionalExample|TestAccGKEHubMembershipIamPolicyGenerated|TestAccGKEHubMembershipIamBindingGenerated|TestAccGKEHubMembershipIamMemberGenerated|TestAccHealthcareDatasetIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-19 01:48 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHubMembership_gkehubMembershipRegionalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording/TestAccGKEHubMembership_gkehubMembershipRegionalExample.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording/TestAccHealthcareDatasetIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubMembershipIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/build-log/recording_build/TestAccGKEHubMembershipIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording/TestAccGKEHubMembershipIamPolicyGenerated.log)]
`TestAccGKEHubMembershipIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/build-log/recording_build/TestAccGKEHubMembershipIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording/TestAccGKEHubMembershipIamBindingGenerated.log)]
`TestAccGKEHubMembershipIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/build-log/recording_build/TestAccGKEHubMembershipIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording/TestAccGKEHubMembershipIamMemberGenerated.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/aa6bcc97-354f-4e88-b8d7-5daf73696538/recording) for each test

2023-09-19 18:34 UTC, melinath requested changes
It looks like this might be a breaking change for the IAM resources; if so, fixing it will require adding `schema_version` / `state_upgraders`, which are not currently supported by iam resources. I'll need to investigate some more.

2023-09-19 18:44 UTC, sahsagar-google commented on mmv1/products/gkehub/Membership.yaml
> +    name: 'gkehub_membership_regional'
Ah, I see. Please let me know if the new changes work. Thank you.

2023-09-19 18:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 150 insertions(+), 19 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 150 insertions(+), 19 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8994-old..auto-pr-8994) ( 3 files changed, 30 insertions(+), 3 deletions(-))

2023-09-19 20:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3070` 
Passed tests `2768` 
Skipped tests: `299` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubMembershipIamBindingGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccGKEHubMembershipIamMemberGenerated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-19 20:27 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHubMembershipIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/75983991-025e-4409-ba7a-97f3d99a02fb/recording/TestAccGKEHubMembershipIamBindingGenerated.log)]
`TestAccGKEHubMembershipIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/75983991-025e-4409-ba7a-97f3d99a02fb/recording/TestAccGKEHubMembershipIamPolicyGenerated.log)]
`TestAccGKEHubMembershipIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/75983991-025e-4409-ba7a-97f3d99a02fb/recording/TestAccGKEHubMembershipIamMemberGenerated.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/75983991-025e-4409-ba7a-97f3d99a02fb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/75983991-025e-4409-ba7a-97f3d99a02fb/recording) for each test

2023-09-19 22:53 UTC, melinath commented
confirmed this is a breaking change for the IAM resources. Error:

```
Error when reading or editing GKEHubMembership "projects/project-id/locations/global/memberships/basic": googleapi: Error 400: Malformed name: 'projects/project-id/locations//memberships/basic
```

2023-09-19 22:54 UTC, melinath commented
I'll work on a workaround.

2023-09-20 23:40 UTC, melinath commented
I have a tentative implementation at https://github.com/GoogleCloudPlatform/magic-modules/pull/9035 but it's not quite working yet. I'll be able to look into it more next week. Apologies for the delay.

2023-09-27 16:19 UTC, melinath requested changes
Update: it looks like a state upgrader is not actually required for the IAM resources. However, you will need to add a state upgrader for the GKEHubMembership resource - that means adding a couple lines to Membership.yaml and a state migration file like https://github.com/GoogleCloudPlatform/magic-modules/pull/9035/files#diff-a9abd9e5a363f02593a71489617efd5fc180e880bf3c360c22eca093c5836585

You can test that this works by doing [manual tests](https://googlecloudplatform.github.io/magic-modules/develop/run-tests/#run-manual-tests) to create a membership with this PR's main branch base commit, then generating the provider using this PR, building it, and trying to run a `terraform plan`. Sample config:

```
resource "google_container_cluster" "primary" {
  name               = "basiccluster"
  location           = "us-central1-a"
  initial_node_count = 1
}

resource "google_gke_hub_membership" "membership" {
  membership_id = "basic"
  # location = "%{location}"
  endpoint {
    gke_cluster {
      resource_link = "//container.googleapis.com/${google_container_cluster.primary.id}"
    }
  }
}
```

2023-09-27 16:19 UTC, melinath commented on mmv1/products/gkehub/Membership.yaml
>  autogen_async: true
```suggestion
autogen_async: true
schema_version: 1
state_upgraders: true
```

2023-09-28 17:42 UTC, melinath requested changes
Failure is:

```
No such file or directory @ rb_sysopen - /mm-terraform-ga-head/mmv1/templates/terraform/state_migrations/gke_hub_membership.go.erb
```

This is due to needing a state upgrader - I think the file at https://github.com/GoogleCloudPlatform/magic-modules/pull/9035/files#diff-a9abd9e5a363f02593a71489617efd5fc180e880bf3c360c22eca093c5836585 should work for you.

2023-09-29 18:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 258 insertions(+), 53 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 258 insertions(+), 53 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8994-old..auto-pr-8994) ( 3 files changed, 30 insertions(+), 3 deletions(-))

2023-09-29 19:34 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3109` 
Passed tests `2784` 
Skipped tests: `314` 
Affected tests: `11` 

#### Action taken 
<details> <summary>Found 11 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withKubeletConfig|TestAccContainerNodePool_withUpgradeSettings|TestAccContainerCluster_withAddons|TestAccContainerCluster_withDeletionProtection|TestAccDataprocClusterIamPolicy|TestAccGKEHubMembershipIamMemberGenerated|TestAccGKEHubMembership_gkehubMembershipRegionalExample|TestAccGKEHubMembershipIamBindingGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccSpannerDatabaseIamPolicy|TestAccWorkstationsWorkstationConfig_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-29 20:27 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSpannerDatabaseIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccSpannerDatabaseIamPolicy.log)]
`TestAccWorkstationsWorkstationConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccWorkstationsWorkstationConfig_update.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccContainerNodePool_withUpgradeSettings.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerCluster_withDeletionProtection`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccContainerCluster_withDeletionProtection_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccContainerCluster_withDeletionProtection.log)]
`TestAccDataprocClusterIamPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccDataprocClusterIamPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccDataprocClusterIamPolicy.log)]
`TestAccGKEHubMembershipIamMemberGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccGKEHubMembershipIamMemberGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccGKEHubMembershipIamMemberGenerated.log)]
`TestAccGKEHubMembership_gkehubMembershipRegionalExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccGKEHubMembership_gkehubMembershipRegionalExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccGKEHubMembership_gkehubMembershipRegionalExample.log)]
`TestAccGKEHubMembershipIamBindingGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccGKEHubMembershipIamBindingGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccGKEHubMembershipIamBindingGenerated.log)]
`TestAccGKEHubMembershipIamPolicyGenerated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_build/TestAccGKEHubMembershipIamPolicyGenerated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording/TestAccGKEHubMembershipIamPolicyGenerated.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/444b5ae0-c34c-4505-88dd-4096968ede2a/recording) for each test

2023-10-03 16:24 UTC, melinath requested changes
LGTM overall - state migrations seem to work as expected & resolve the upgrade issue. I think the tgc integration test failures could be resolved by merging the main branch into this PR (or rebasing.) Most of the VCR failures seem unrelated - added a note below about resolving the remainder.

2023-10-03 16:24 UTC, melinath commented on mmv1/templates/terraform/examples/gkehub_membership_regional.tf.erb
> +  initial_node_count = 1
In 5.0.0, google_container_cluster.deletion_protection started [defaulting to `true`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_5_upgrade#cluster-deletion-now-prevented-by-default-with-deletion_protection) so we need to explicitly set it to `false` here.

If you don't want to include this in the docs, you could use a var to set the value.

```suggestion
  initial_node_count = 1
  deletion_protection = false
```

2023-10-03 18:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 265 insertions(+), 53 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8994-old..auto-pr-8994) ( 7 files changed, 265 insertions(+), 53 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-8994-old..auto-pr-8994) ( 3 files changed, 30 insertions(+), 3 deletions(-))

2023-10-03 19:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3113` 
Passed tests `2791` 
Skipped tests: `314` 
Affected tests: `8` 

#### Action taken 
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withUpgradeSettings|TestAccContainerNodePool_withKubeletConfig|TestAccContainerCluster_withAddons|TestAccGKEHubMembership_gkehubMembershipRegionalExample|TestAccGKEHubMembershipIamBindingGenerated|TestAccGKEHubMembershipIamMemberGenerated|TestAccGKEHubMembershipIamPolicyGenerated|TestAccSpannerInstanceIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-03 20:19 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHubMembership_gkehubMembershipRegionalExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccGKEHubMembership_gkehubMembershipRegionalExample.log)]
`TestAccGKEHubMembershipIamBindingGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccGKEHubMembershipIamBindingGenerated.log)]
`TestAccGKEHubMembershipIamMemberGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccGKEHubMembershipIamMemberGenerated.log)]
`TestAccGKEHubMembershipIamPolicyGenerated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccGKEHubMembershipIamPolicyGenerated.log)]
`TestAccSpannerInstanceIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccSpannerInstanceIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccContainerNodePool_withUpgradeSettings.log)]
`TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording/TestAccContainerCluster_withAddons.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8994/artifacts/775d9a95-a1c5-4e9b-9939-fc1869dbd2b2/recording) for each test

2023-10-03 22:46 UTC, melinath approved these changes
LGTM

2023-10-03 22:46 UTC, melinath commented
TGC failures seem unrelated - I believe they have been resolved on main.

2023-10-03 22:46 UTC, merged