feat(container_node_pool): support cgroup mode
GoogleCloudPlatform/magic-modules pull request #8997
Opened 2023-09-19 07:46 UTC by toVersus

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/15656

This PR added support for setting cgroup version to the google_container_node_pool resource. This allows users to switch to use cgroup v2 for their existing node pools. See [Linux cgroup mode configuration option](https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#cgroup-mode-options) and corresponding [REST API doc](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#CgroupMode).

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: added `node_config.linux_node_config.cgroup_mode` field to `google_container_node_pool`
```

2023-09-19 07:48 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@melinath, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-09-19 16:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 120 insertions(+), 21 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 120 insertions(+), 21 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (248 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      cgroup_mode = # value needed
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        cgroup_mode = # value needed
      }
    }
  }
}

```

2023-09-19 17:43 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3070` 
Passed tests `2770` 
Skipped tests: `299` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withCgroupMode </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-19 18:01 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withCgroupMode`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/41e984e8-77fb-45a3-9990-de2d5f52a4f8/recording/TestAccContainerNodePool_withCgroupMode.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/41e984e8-77fb-45a3-9990-de2d5f52a4f8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/41e984e8-77fb-45a3-9990-de2d5f52a4f8/recording) for each test

2023-09-21 00:30 UTC, melinath commented
Reassigning review due to OOO.

2023-09-25 21:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 88 insertions(+), 21 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 88 insertions(+), 21 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (246 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      cgroup_mode = # value needed
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        cgroup_mode = # value needed
      }
    }
  }
}

```
Resource: `google_container_node_pool` (54 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_node_pool" "primary" {
  node_config {
    linux_node_config {
      cgroup_mode = # value needed
    }
  }
}

```

2023-09-25 22:41 UTC, NickElliot requested changes
Sorry I took so long to get to this review! Has been a busy week.

It looks like when you rebased you accidentally removed your "testAccContainerNodePool_withCgroupMode" case -- only the larger test function that calls that smaller one is in the file right now.

2023-09-25 22:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2919` 
Passed tests `2630` 
Skipped tests: `289` 
Affected tests: `0` 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/4a204c5a-ee59-4ee7-8ab6-c7f43d76178b/build-log/replaying_test.log)

2023-09-26 05:22 UTC, toVersus commented
> Sorry I took so long to get to this review! Has been a busy week.

No problem! Thanks for making the time.

> It looks like when you rebased you accidentally removed your "testAccContainerNodePool_withCgroupMode" case -- only the larger test function that calls that smaller one is in the file right now.

My bad. Fixed!

2023-09-29 01:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 120 insertions(+), 21 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-8997-old..auto-pr-8997) ( 3 files changed, 120 insertions(+), 21 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (246 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    linux_node_config {
      cgroup_mode = # value needed
    }
  }
  node_pool {
    node_config {
      linux_node_config {
        cgroup_mode = # value needed
      }
    }
  }
}

```

2023-09-29 02:24 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3102` 
Passed tests `2782` 
Skipped tests: `313` 
Affected tests: `7` 

#### Action taken 
<details> <summary>Found 7 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withKubeletConfig|TestAccContainerNodePool_withCgroupMode|TestAccContainerNodePool_withUpgradeSettings|TestAccContainerCluster_withAddons|TestAccDataSourceGoogleServiceAccountIdToken_impersonation|TestAccDataSourceGoogleServiceAccountJwt|TestAccProjectIamPolicy_invalidMembers </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-09-29 03:06 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountJwt`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccDataSourceGoogleServiceAccountJwt.log)]
`TestAccProjectIamPolicy_invalidMembers`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccProjectIamPolicy_invalidMembers.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccContainerNodePool_withCgroupMode`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_build/TestAccContainerNodePool_withCgroupMode_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccContainerNodePool_withCgroupMode.log)]
`TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccContainerNodePool_withUpgradeSettings.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccContainerCluster_withAddons.log)]
`TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_build/TestAccDataSourceGoogleServiceAccountIdToken_impersonation_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/f1531ec8-870d-47bd-bcd2-9966aa959f52/recording) for each test

2023-10-02 22:37 UTC, NickElliot requested changes
`TestAccContainerNodePool_withCgroupMode` is failing with a "Error: Cannot destroy cluster because deletion_protection is set to true. Set it to false to proceed with instance deletion.", and presumably needs to have that configured to be false.

2023-10-03 05:15 UTC, toVersus commented
Thanks for the pointer! I think this change (https://github.com/GoogleCloudPlatform/magic-modules/pull/9013) is introducing the requirement to explicitly set `deletion_protection = false` on the `google_container_cluster` resource when deleting clusters in tests. Fixed.

2023-10-03 18:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3113` 
Passed tests `2794` 
Skipped tests: `314` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withUpgradeSettings|TestAccContainerNodePool_withCgroupMode|TestAccContainerCluster_withAddons|TestAccContainerNodePool_withKubeletConfig|TestAccDataprocClusterIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-03 19:08 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withCgroupMode`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording/TestAccContainerNodePool_withCgroupMode.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording/TestAccContainerNodePool_withUpgradeSettings.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccDataprocClusterIamPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/build-log/recording_build/TestAccDataprocClusterIamPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording/TestAccDataprocClusterIamPolicy.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-8997/artifacts/658e9416-6ed7-40e0-b9a8-6d64aae1708e/recording) for each test

2023-10-03 19:45 UTC, NickElliot approved these changes
LGTM 🙂

2023-10-03 19:50 UTC, merged