add PREMIUM for Global external IP addresses
GoogleCloudPlatform/magic-modules pull request #9089
Opened 2023-09-26 15:51 UTC by edwardmedia

Fixes https://github.com/hashicorp/terraform-provider-google/issues/15982

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
compute: fixed `google_compute_global_address` can't be created when default_network_tier set to STANDARD
```

2023-09-26 15:54 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@c2thorn, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-09-26 16:02 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9089-old..auto-pr-9089) ( 1 file changed, 2 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9089-old..auto-pr-9089) ( 1 file changed, 2 insertions(+))

2023-09-26 17:14 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3092` 
Passed tests `2737` 
Skipped tests: `299` 
Affected tests: `56` 

#### Action taken 
<details> <summary>Found 56 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_withNetworkConfigAndAllocatedIPRange|TestAccAlloydbBackup_alloydbBackupFullExample|TestAccAlloydbInstance_createInstanceWithMandatoryFields|TestAccAlloydbBackup_alloydbBackupBasicExample|TestAccAlloydbBackup_update|TestAccAlloydbCluster_restore|TestAccAlloydbBackup_createBackupWithMandatoryFields|TestAccAlloydbInstance_createPrimaryAndReadPoolInstance|TestAccAlloydbInstance_alloydbInstanceBasicExample|TestAccAlloydbInstance_update|TestAccAlloydbBackup_usingCMEK|TestAccApigeeEnvReferences_apigeeEnvironmentReferenceTestExample|TestAccApigeeAddonsConfig_apigeeAddonsTestExample|TestAccApigeeTargetServer_apigeeTargetServerTestExample|TestAccApigeeEnvKeystore_apigeeEnvironmentKeystoreTestExample|TestAccApigeeTargetServer_apigeeTargetServerTest_update|TestAccApigeeEnvironmentIamBindingGenerated|TestAccApigeeEnvironmentIamPolicyGenerated|TestAccApigeeEnvironmentIamMemberGenerated|TestAccBackupDRManagementServer_backupDrManagementServerExample|TestAccCloudbuildWorkerPool_withNetwork|TestAccCloudBuildBitbucketServerConfig_cloudbuildBitbucketServerConfigPeeredNetworkExample|TestAccCloudIdsEndpoint_basic|TestAccDataSourceComputeGlobalAddress|TestAccComputeBackendBucket_externalCdnLbWithBackendBucketExample|TestAccComputeGlobalAddress_ipv6|TestAccComputeGlobalAddress_internal|TestAccComputeGlobalAddress_globalAddressPrivateServicesConnectExample|TestAccComputeGlobalAddress_globalAddressBasicExample|TestAccComputeGlobalForwardingRule_externalHttpLbMigBackendCustomHeaderExample|TestAccComputeGlobalForwardingRule_externalTcpProxyLbMigBackendExample|TestAccComputeGlobalForwardingRule_privateServiceConnectGoogleApisNoAutomateDnsExample|TestAccComputeGlobalForwardingRule_privateServiceConnectGoogleApisExample|TestAccDatabaseMigrationServiceConnectionProfile_databaseMigrationServiceConnectionProfileAlloydbExample|TestAccDataFusionInstance_dataFusionInstanceFullExample|TestAccDataprocClusterIamPolicy|TestAccLookerInstance_lookerInstanceEnterpriseFullExample|TestAccMemcacheInstance_memcacheInstanceBasicExample|TestAccMemcacheInstance_update|TestAccRedisInstance_redisInstancePrivateServiceExample|TestAccDataSourceGoogleServiceAccountJwt|TestAccDataSourceGoogleServiceAccountAccessToken_basic|TestAccServiceNetworkingConnection_update|TestAccServiceNetworkingConnection_create|TestAccDatasourceGoogleServiceNetworkingPeeredDnsDomain_basic|TestAccServiceNetworkingPeeredDNSDomain_basic|TestAccSqlDatabaseInstance_deleteDefaultUserBeforeSubsequentApiCalls|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeReplica|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRangeClone|TestAccSqlDatabaseInstance_withPrivateNetwork_withoutAllocatedIpRange|TestAccSqlDatabaseInstance_withPrivateNetwork_withAllocatedIpRange|TestAccTPUNode_tpuNodeFullExample|TestAccVertexAIIndexEndpoint_vertexAiIndexEndpointExample|TestAccVertexAIIndexEndpoint_updated|TestAccVertexAIEndpoint_vertexAiEndpointNetwork </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-02 18:51 UTC, c2thorn commented
Seems fine based on documentation, but I want to know why current implementations are not failing without this? @edwardmedia 
Is this just a specific use case?

2023-10-02 18:57 UTC, glimberg commented
@c2thorn See https://github.com/hashicorp/terraform-provider-google/issues/15982

This does currently fail when a GCP project's default network tier is set to STANDARD rather than PREMIUM.  The documentation states that the GCP's REST API will assume PREMIUM for any global address.  In practice, this isn't the case, and I've verified it via cURL as well

```bash
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://compute.googleapis.com/compute/v1/projects/${PROJECT_ID}/global/addresses?alt=json" --data '{"name":"${GLOBAL_IP_ADDRESS_NAME}"}'
{
  "error": {
    "code": 400,
    "message": "STANDARD network tier (the project's default network tier) is not supported: STANDARD network tier is not supported for global address.",
    "errors": [
      {
        "message": "STANDARD network tier (the project's default network tier) is not supported: STANDARD network tier is not supported for global address.",
        "domain": "global",
        "reason": "badRequest"
      }
    ]
  }
}
```


```bash
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $(gcloud auth print-access-token)" "https://compute.googleapis.com/compute/v1/projects/${PROJECT_ID}/global/addresses?alt=json" --data '{"name":"${GLOBAL_IP_ADDRESS_NAME}","networkTier":"PREMIUM"}'
{
  "kind": "compute#operation",
  "id": "760793188359971737",
  "name": "operation-1695948149954-60674b3091944-8bdbeb1a-b7b58b8c",
  "operationType": "insert",
  "targetLink": "https://www.googleapis.com/compute/v1/projects/<project id recacted>/global/addresses/<ip address name redacted>",
  "targetId": "408497069976429465",
  "status": "RUNNING",
  "user": "<email address redadted>",
  "progress": 0,
  "insertTime": "2023-09-28T17:42:30.350-07:00",
  "startTime": "2023-09-28T17:42:30.361-07:00",
  "selfLink": "https://www.googleapis.com/compute/v1/projects/<project id redacted>/global/operations/operation-1695948149954-60674b3091944-8bdbeb1a-b7b58b8c"
}

2023-10-02 20:30 UTC, c2thorn approved these changes
thanks @glimberg for the context

2023-10-02 20:33 UTC, c2thorn requested changes
Looks like tests are failing from this:
```
 Error: Error creating GlobalAddress: googleapi: Error 400: Invalid value for field 'resource.networkTier': 'PREMIUM'. An address with type INTERNAL cannot have a network tier., invalid
 ```
We need to get the logic right or just add the field. I'd prefer to just add the field.

2023-10-03 01:15 UTC, glimberg commented
I finally was able to get on a call with GCP support on the API's behavior vs. the documentation for the globalAddress endpoint.  According to support, the documentation is wrong.  When the `networkTier` field is not specified, it does NOT assume PREMIUM tier.  Instead it follows the project's default network tier setting.  In my case with the default network tier set to STANDARD, `networkTier` when not specified defaults to STANDARD.  

Adding the field to the `google_compute_global_address` is probably the best way forward here.

2023-10-03 18:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9089-old..auto-pr-9089) ( 1 file changed, 5 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9089-old..auto-pr-9089) ( 1 file changed, 5 insertions(+))

2023-10-03 20:12 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3112` 
Passed tests `2795` 
Skipped tests: `314` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withKubeletConfig|TestAccContainerCluster_withAddons|TestAccContainerNodePool_withUpgradeSettings </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-03 20:51 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/recording/TestAccContainerNodePool_withKubeletConfig.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/recording/TestAccContainerNodePool_withUpgradeSettings.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9089/artifacts/88f54443-1f4c-4506-999a-e3decd22c73f/recording) for each test

2023-10-05 22:13 UTC, c2thorn approved these changes

2023-10-05 22:17 UTC, merged