Add support for enable_confidential_storage flag
GoogleCloudPlatform/magic-modules pull request #9122
Opened 2023-09-28 19:43 UTC by Sneha-at

Adds support for new parameter "enable_confidential_storage" while creating cluster and node-pool. This flag does not support update operations.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
Adds support for enable_confidential_storage parameter for node-pool creation
```

2023-09-28 19:45 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@shuyama1, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-09-28 19:49 UTC, shuyama1 commented
@Sneha-at thanks for making the change. Would you mind rebasing your PR to resolve the conflicts? Plus, please check the internal contribution page on how to get the tests automatically run for your PR so that you'll be able to see test results faster

2023-09-29 21:54 UTC, sunnylovestiramisu commented
/hold

Until prod fix is out, but please review the change ahead to save some time.

2023-10-02 19:21 UTC, shuyama1 reviewed
Code looks good to me. Please add a test coverage on negative value `enable_confidential_storage = false`. Just want to make sure that the API will send the value back if we explicitly send it, otherwise it will cause a drift in TF. Thanks

2023-10-02 19:21 UTC, shuyama1 commented on mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.erb
> +	disk_type = "hyperdisk-balanced"
only nit: should be spaces instead of tabs here for spacing

2023-10-02 19:21 UTC, shuyama1 commented on mmv1/third_party/terraform/services/container/resource_container_node_pool_test.go.erb
> +  	disk_type = "hyperdisk-balanced"
nit: spcing

2023-10-03 18:02 UTC, shuyama1 commented
@Sneha-at I see this PR is still in draft mode. Let me know when it's ready to review or if you need me to trigger build and tests for it. Also please see https://github.com/GoogleCloudPlatform/magic-modules/pull/9122#issuecomment-1739913980 to get your GitHub account join in the right org so the tests will automatically triggered for your PR.

2023-10-03 21:19 UTC, Sneha-at commented
Thanks @shuyama1 I have joined "GoogleCloudPlatform" org, how do I trigger the tests?

2023-10-03 21:31 UTC, shuyama1 commented
/gcbrun

2023-10-03 21:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 43 insertions(+), 37 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 5 files changed, 268 insertions(+), 37 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (250 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_pool {
    node_config {
      enable_confidential_storage = # value needed
    }
  }
}

```

2023-10-03 21:50 UTC, Sneha-at commented
I have a test which uses this flag in node_config (not node_pool{node_config}), is this deprecated now? Or is is necessary to have test with "primary" tag -- `"google_container_cluster""primary"`?
```
func testAccContainerCluster_withConfidentialBootDisk(clusterName, kmsKeyName string) string {
	return fmt.Sprintf(`
resource "google_container_cluster" "with_confidential_boot_disk" {
.....
  	node_config {
	enable_confidential_storage = true
 }
}
```

2023-10-03 22:29 UTC, Sneha-at commented
/gcbrun

2023-10-03 22:30 UTC, Sneha-at commented
/gcbrun

2023-10-03 22:34 UTC, shuyama1 commented
@Sneha-at I think the tests will automatically triggered when there's a new action to the PR, like new commits or merge/rebase of main. You don't need to manually comment the command :) Plus, I think the comment for rerun probably only works for the maintainers of the repo

2023-10-03 22:39 UTC, Sneha-at commented
Ahh, thanks!! Can you please help me understand whats missing in the tests, more in [comment](https://github.com/GoogleCloudPlatform/magic-modules/pull/9122#issuecomment-1745782305)

2023-10-03 22:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 43 insertions(+), 39 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 6 files changed, 268 insertions(+), 44 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (250 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_pool {
    node_config {
      enable_confidential_storage = # value needed
    }
  }
}

```

2023-10-03 23:54 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3119` 
Passed tests `2797` 
Skipped tests: `316` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withConfidentialBootDisk|TestAccContainerNodePool_withUpgradeSettings|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withAddons|TestAccContainerNodePool_withKubeletConfig|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-04 00:35 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccContainerCluster_withConfidentialBootDisk.log)]
`TestAccContainerNodePool_withUpgradeSettings`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_build/TestAccContainerNodePool_withUpgradeSettings_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccContainerNodePool_withUpgradeSettings.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_build/TestAccContainerCluster_withoutConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withAddons`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_build/TestAccContainerCluster_withAddons_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccContainerCluster_withAddons.log)]
`TestAccContainerNodePool_withKubeletConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_build/TestAccContainerNodePool_withKubeletConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording/TestAccContainerNodePool_withKubeletConfig.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/bcec424c-66f1-49fa-a811-2ee629fb3db2/recording) for each test

2023-10-04 17:20 UTC, shuyama1 commented
> I have a test which uses this flag in node_config (not node_pool{node_config}), is this deprecated now? Or is is necessary to have test with "primary" tag -- `"google_container_cluster""primary"`?
> 
> ```
> func testAccContainerCluster_withConfidentialBootDisk(clusterName, kmsKeyName string) string {
> 	return fmt.Sprintf(`
> resource "google_container_cluster" "with_confidential_boot_disk" {
> .....
>   	node_config {
> 	enable_confidential_storage = true
>  }
> }
> ```

Sorry, haven't got time to do a full review, by only a quick glance though, I think what you read is correct, the missing test detector is complaining that there's no test coverage on the field `node_pool.node_config.enable_confidential_storage` in the `google_container_cluster` resource. I don't see that we have deprecated `node_pool`, also I couldn't find the deprecation massage on the API page https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters, but I am super familiar with the resource, is `node_pool.node_config.enable_confidential_storage` a valid resource configuration?

2023-10-04 18:45 UTC, Sneha-at commented
Yes `node_pool.node_config.enable_confidential_storage` is a valid resource. I see we use node_config only to set node_defaults in the cluster. So moving this to `node_pool.node_config` in tests.

2023-10-04 18:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 43 insertions(+), 39 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 5 files changed, 274 insertions(+), 39 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_container_cluster` (251 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_cluster" "primary" {
  node_config {
    enable_confidential_storage = # value needed
  }
}

```
Resource: `google_container_node_pool` (56 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_node_pool" "primary" {
  node_config {
    enable_confidential_storage = # value needed
  }
}

```

2023-10-04 18:55 UTC, Sneha-at commented
Looks like we need to have test cases for both ways to set the node_config

2023-10-04 20:05 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3123` 
Passed tests `2800` 
Skipped tests: `320` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDisk|TestAccWorkstationsWorkstationConfig_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-04 20:49 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccWorkstationsWorkstationConfig_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/recording/TestAccWorkstationsWorkstationConfig_update.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/build-log/recording_build/TestAccContainerCluster_withoutConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/recording/TestAccContainerCluster_withConfidentialBootDisk.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/a4e73aea-94b2-4757-8124-9e04f1c17b1d/recording) for each test

2023-10-04 21:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 43 insertions(+), 39 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 5 files changed, 389 insertions(+), 39 deletions(-))

2023-10-04 22:42 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3125` 
Passed tests `2801` 
Skipped tests: `321` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withConfidentialBootDisk </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-04 22:44 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/build-log/recording_build/TestAccContainerCluster_withoutConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withConfidentialBootDiskNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDiskNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/recording/TestAccContainerCluster_withConfidentialBootDiskNodeConfig.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/recording/TestAccContainerCluster_withConfidentialBootDisk.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/8aadadc7-8bdf-4732-be46-1d1e5bd66bc6/recording) for each test

2023-10-04 22:55 UTC, Sneha-at commented
The support for machine type mentioned in tests is getting rolled out and would take some time to be available. The presubmits should pass once we have that ready. Meanwhile, please let me know if everything else looks good.

2023-10-05 23:12 UTC, Sneha-at commented
Moving it to "review" to allow presubmits.

2023-10-05 23:19 UTC, Sneha-at commented
I wonder why only the Cluster tests are failing while the node_pool tests are passing, is there something else needed for those tests?

2023-10-05 23:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 348 insertions(+))

2023-10-06 00:39 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3131` 
Passed tests `2801` 
Skipped tests: `321` 
Affected tests: `9` 

#### Action taken 
<details> <summary>Found 9 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbUser_alloydbUserIamExample|TestAccAlloydbUser_updateRoles_IAM|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbUser_alloydbUserBuiltinExample|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withConfidentialBootDisk|TestAccDataSourceGoogleServiceAccountAccessToken_basic </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-06 00:57 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountAccessToken_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccDataSourceGoogleServiceAccountAccessToken_basic.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccAlloydbUser_alloydbUserIamExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccAlloydbUser_alloydbUserIamExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccAlloydbUser_alloydbUserIamExample.log)]
`TestAccAlloydbUser_updateRoles_IAM`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccAlloydbUser_updateRoles_IAM_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccAlloydbUser_updateRoles_IAM.log)]
`TestAccAlloydbUser_updateRoles_BuiltIn`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccAlloydbUser_updateRoles_BuiltIn_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccAlloydbUser_updateRoles_BuiltIn.log)]
`TestAccAlloydbUser_updatePassword_BuiltIn`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccAlloydbUser_updatePassword_BuiltIn_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccAlloydbUser_updatePassword_BuiltIn.log)]
`TestAccAlloydbUser_alloydbUserBuiltinExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccAlloydbUser_alloydbUserBuiltinExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccAlloydbUser_alloydbUserBuiltinExample.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccContainerCluster_withoutConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withConfidentialBootDiskNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDiskNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccContainerCluster_withConfidentialBootDiskNodeConfig.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording/TestAccContainerCluster_withConfidentialBootDisk.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/ef683f66-21c8-4cbd-aa47-eaf1b273d62b/recording) for each test

2023-10-06 01:08 UTC, Sneha-at commented
I don't see any tests for node_pool "TestAccContainerNodePool" in [VCR-test details](https://pantheon.corp.google.com/cloud-build/builds;region=global/ef683f66-21c8-4cbd-aa47-eaf1b273d62b;step=20?e=-13802955&mods=logs_tg_prod&project=graphite-docker-images) last step so assuming it is intended

2023-10-10 21:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 276 insertions(+))

2023-10-10 22:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3148` 
Passed tests `2799` 
Skipped tests: `316` 
Affected tests: `33` 

#### Action taken 
<details> <summary>Found 33 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbInstance_createInstanceWithMandatoryFields|TestAccAlloydbInstance_createPrimaryAndReadPoolInstance|TestAccAlloydbInstance_clientConnectionConfig_update|TestAccAlloydbInstance_clientConnectionConfig_sslModeDefault|TestAccAlloydbCluster_secondaryClusterMandatoryFields|TestAccAlloydbUser_updateRoles_IAM|TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary|TestAccAlloydbUser_alloydbUserBuiltinExample|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbUser_updatePassword_BuiltIn|TestAccAlloydbInstance_update|TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary|TestAccAlloydbUser_alloydbUserIamExample|TestAccAlloydbInstance_alloydbInstanceBasicExample|TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig|TestAccAlloydbCluster_secondaryClusterWithNetworkConfig|TestAccAlloydbCluster_secondaryClusterAddAutomatedBackupPolicy|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbBackup_alloydbBackupFullExample|TestAccAlloydbBackup_alloydbBackupBasicExample|TestAccAlloydbBackup_createBackupWithMandatoryFields|TestAccAlloydbCluster_restore|TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample|TestAccAlloydbBackup_update|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbBackup_usingCMEK|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDisk|TestAccContainerNodePool_withoutConfidentialBootDisk|TestAccContainerNodePool_withConfidentialBootDisk </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-11 00:29 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccAlloydbInstance_createInstanceWithMandatoryFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_createInstanceWithMandatoryFields.log)]
`TestAccAlloydbUser_updateRoles_IAM`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbUser_updateRoles_IAM.log)]
`TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary.log)]
`TestAccAlloydbUser_alloydbUserBuiltinExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbUser_alloydbUserBuiltinExample.log)]
`TestAccAlloydbUser_updateRoles_BuiltIn`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbUser_updateRoles_BuiltIn.log)]
`TestAccAlloydbUser_alloydbUserIamExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbUser_alloydbUserIamExample.log)]
`TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig.log)]
`TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange.log)]
`TestAccAlloydbCluster_secondaryClusterUsingCMEK`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterUsingCMEK.log)]
`TestAccAlloydbBackup_alloydbBackupFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbBackup_alloydbBackupFullExample.log)]
`TestAccAlloydbBackup_alloydbBackupBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbBackup_alloydbBackupBasicExample.log)]
`TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample.log)]
`TestAccAlloydbBackup_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbBackup_update.log)]
`TestAccAlloydbCluster_secondaryClusterUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccAlloydbInstance_createPrimaryAndReadPoolInstance`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbInstance_createPrimaryAndReadPoolInstance_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_createPrimaryAndReadPoolInstance.log)]
`TestAccAlloydbInstance_clientConnectionConfig_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbInstance_clientConnectionConfig_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_clientConnectionConfig_update.log)]
`TestAccAlloydbInstance_clientConnectionConfig_sslModeDefault`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbInstance_clientConnectionConfig_sslModeDefault_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_clientConnectionConfig_sslModeDefault.log)]
`TestAccAlloydbCluster_secondaryClusterMandatoryFields`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbCluster_secondaryClusterMandatoryFields_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterMandatoryFields.log)]
`TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange.log)]
`TestAccAlloydbUser_updatePassword_BuiltIn`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbUser_updatePassword_BuiltIn_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbUser_updatePassword_BuiltIn.log)]
`TestAccAlloydbInstance_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbInstance_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbInstance_update.log)]
`TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/build-log/recording_build/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d10b08f4-cc68-4eb9-8401-7fb761cb7fb9/recording/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary.log)]
`TestAccAlloydbInstance_alloydbInstanceBasicExample`[[Error message](https://storage.cloud.google.com/ci-vcr- [...]

2023-10-11 18:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 281 insertions(+))

2023-10-11 19:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3150` 
Passed tests `2804` 
Skipped tests: `316` 
Affected tests: `30` 

#### Action taken 
<details> <summary>Found 30 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbInstance_createInstanceWithMandatoryFields|TestAccAlloydbCluster_secondaryClusterAddAutomatedBackupPolicy|TestAccAlloydbCluster_secondaryClusterMandatoryFields|TestAccAlloydbInstance_createPrimaryAndReadPoolInstance|TestAccAlloydbUser_alloydbUserIamExample|TestAccAlloydbCluster_secondaryClusterUpdate|TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig|TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample|TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary|TestAccAlloydbUser_alloydbUserBuiltinExample|TestAccAlloydbUser_updateRoles_BuiltIn|TestAccAlloydbCluster_secondaryClusterUsingCMEK|TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange|TestAccAlloydbBackup_update|TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary|TestAccAlloydbUser_updateRoles_IAM|TestAccAlloydbCluster_restore|TestAccAlloydbInstance_update|TestAccAlloydbBackup_usingCMEK|TestAccAlloydbBackup_createBackupWithMandatoryFields|TestAccAlloydbInstance_alloydbInstanceBasicExample|TestAccAlloydbBackup_alloydbBackupBasicExample|TestAccAlloydbBackup_alloydbBackupFullExample|TestAccCloudRunService_cloudRunServiceSqlExample|TestAccContainerNodePool_withoutConfidentialBootDisk|TestAccContainerNodePool_withConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDisk </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-11 21:15 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccAlloydbInstance_createInstanceWithMandatoryFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbInstance_createInstanceWithMandatoryFields.log)]
`TestAccAlloydbCluster_secondaryClusterAddAutomatedBackupPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterAddAutomatedBackupPolicy.log)]
`TestAccAlloydbCluster_secondaryClusterMandatoryFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterMandatoryFields.log)]
`TestAccAlloydbInstance_createPrimaryAndReadPoolInstance`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbInstance_createPrimaryAndReadPoolInstance.log)]
`TestAccAlloydbUser_alloydbUserIamExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbUser_alloydbUserIamExample.log)]
`TestAccAlloydbCluster_secondaryClusterUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterUpdate.log)]
`TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterMissingSecondaryConfig.log)]
`TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_alloydbSecondaryClusterBasicExample.log)]
`TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterWithNetworkConfigAndAllocatedIPRange.log)]
`TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButMissingClusterTypeSecondary.log)]
`TestAccAlloydbUser_alloydbUserBuiltinExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbUser_alloydbUserBuiltinExample.log)]
`TestAccAlloydbUser_updateRoles_BuiltIn`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbUser_updateRoles_BuiltIn.log)]
`TestAccAlloydbCluster_secondaryClusterUsingCMEK`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterUsingCMEK.log)]
`TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbInstance_createInstanceWithNetworkConfigAndAllocatedIPRange.log)]
`TestAccAlloydbBackup_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbBackup_update.log)]
`TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary.log)]
`TestAccAlloydbUser_updateRoles_IAM`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbUser_updateRoles_IAM.log)]
`TestAccAlloydbCluster_restore`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbCluster_restore.log)]
`TestAccAlloydbInstance_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbInstance_update.log)]
`TestAccAlloydbBackup_usingCMEK`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbBackup_usingCMEK.log)]
`TestAccAlloydbBackup_createBackupWithMandatoryFields`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbBackup_createBackupWithMandatoryFields.log)]
`TestAccAlloydbInstance_alloydbInstanceBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbInstance_alloydbInstanceBasicExample.log)]
`TestAccAlloydbBackup_alloydbBackupBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbBackup_alloydbBackupBasicExample.log)]
`TestAccAlloydbBackup_alloydbBackupFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccAlloydbBackup_alloydbBackupFullExample.log)]
`TestAccContainerNodePool_withoutConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccContainerNodePool_withoutConfidentialBootDisk.log)]
`TestAccContainerNodePool_withConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccContainerNodePool_withConfidentialBootDisk.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccCloudRunService_cloudRunServiceSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/build-log/recording_build/TestAccCloudRunService_cloudRunServiceSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccCloudRunService_cloudRunServiceSqlExample.log)]
`TestAccContainerCluster_withConfidentialBootDiskNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDiskNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/329e9819-5e6e-464e-91c1-281d74bb76c9/recording/TestAccContainerCluster_withConfidentialBootDiskNodeConfig.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.c [...]

2023-10-11 21:25 UTC, Sneha-at commented
@shuyama1  All the tests are failing due to `deletion_protection` mismatch, are we expected to set this to `true` or `false`? I would want the resources to be cleaned up post execution.
Do I add `ImportStateVerifyIgnore: []string{"deletion_protection"}` ?
```
ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=1) {
         (string) (len=19) "deletion_protection": (string) (len=4) "true"
        }  
        (map[string]string) (len=1) {
         (string) (len=19) "deletion_protection": (string) (len=5) "false"
```

2023-10-12 16:15 UTC, sunnylovestiramisu commented
The feature enablement on the GKE side is completed, the tests should pass now. 

/gcbrun

2023-10-12 16:17 UTC, shuyama1 commented
/gcbrun

2023-10-12 16:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 281 insertions(+))

2023-10-12 16:54 UTC, Sneha-at commented
The tests are failing due to `deletion_protection` flag. @shuyama1 could you please help me with what changes are needed here? I added `deletion_protection: false` as we want to clean up clusters post test completion. But this is failing with error, I also tried adding `ImportStateVerifyIgnore: []string{"deletion_protection"},`but still got the same error
```
ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=1) {
         (string) (len=19) "deletion_protection": (string) (len=4) "true"
        }
        (map[string]string) (len=1) {
         (string) (len=19) "deletion_protection": (string) (len=5) "false"
        }
```

2023-10-12 17:40 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3149` 
Passed tests `2828` 
Skipped tests: `316` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunService_cloudRunServiceSqlExample|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withConfidentialBootDisk|TestAccHealthcareDatasetIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-12 17:55 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccCloudRunService_cloudRunServiceSqlExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording/TestAccCloudRunService_cloudRunServiceSqlExample.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording/TestAccHealthcareDatasetIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/build-log/recording_build/TestAccContainerCluster_withoutConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withConfidentialBootDiskNodeConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDiskNodeConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording/TestAccContainerCluster_withConfidentialBootDiskNodeConfig.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/build-log/recording_build/TestAccContainerCluster_withConfidentialBootDisk_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording/TestAccContainerCluster_withConfidentialBootDisk.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/23f701b8-dd01-4943-baaf-e640aa2b3da2/recording) for each test

2023-10-12 18:12 UTC, shuyama1 commented
@Sneha-at I believe adding `deletion_protection: false` to the config and `deletion_protection` to `ImportStateVerifyIgnore` should resolve the issue. Would you mind adding those in your PR so I can take a look at the debug log see what the issue might be? Thanks!

2023-10-12 18:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 281 insertions(+))

2023-10-12 19:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3150` 
Passed tests `2830` 
Skipped tests: `316` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbInstance_clientConnectionConfig|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccContainerCluster_withConfidentialBootDiskNodeConfig|TestAccContainerCluster_withConfidentialBootDisk </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-12 20:07 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccAlloydbInstance_clientConnectionConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/recording/TestAccAlloydbInstance_clientConnectionConfig.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccContainerCluster_withConfidentialBootDiskNodeConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/recording/TestAccContainerCluster_withConfidentialBootDiskNodeConfig.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/recording/TestAccContainerCluster_withConfidentialBootDisk.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/build-log/replaying_build_after_recording/TestAccContainerCluster_withConfidentialBootDisk_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/replaying_after_recording/TestAccContainerCluster_withConfidentialBootDisk.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/build-log/replaying_build_after_recording/TestAccContainerCluster_withoutConfidentialBootDisk_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/replaying_after_recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/3b3debce-72de-4040-8569-8bdf05c23f86/recording) for each test

2023-10-12 23:19 UTC, Sneha-at commented
The tests seems to be failing with error 
```
Error: Post "https://container.googleapis.com/v1beta1/projects/ci-test-project-188019/locations/us-central1-a/clusters?alt=json&prettyPrint=false": Requested interaction not found
```
Not sure if this is related to my changes or is an infra issue.

2023-10-13 18:29 UTC, Sneha-at commented
All the tests have passed during "Recording" mode but 2 tests failed during "Replaying" mode, do we have to worry about "Replaying" mode or are these failures temporary?

2023-10-13 20:00 UTC, shuyama1 commented
@Sneha-at Tests passed in recording but failed after in replaying usually due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made. We should also get the tests passed in replaying or skip them in VCR if they're not suitable for VCR. I am looking into the failures and will suggest the next step after I figured out why it failed in replaying.

2023-10-13 20:13 UTC, shuyama1 commented
/gcbrun

2023-10-13 20:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 281 insertions(+))

2023-10-13 21:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3147` 
Passed tests `2825` 
Skipped tests: `318` 
Affected tests: `4` 

#### Action taken 
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeBackendService_withCdnPolicy|TestAccContainerCluster_withConfidentialBootDisk|TestAccContainerCluster_withoutConfidentialBootDisk|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-13 21:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeBackendService_withCdnPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/recording/TestAccComputeBackendService_withCdnPolicy.log)]
`TestAccContainerCluster_withConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/recording/TestAccContainerCluster_withConfidentialBootDisk.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)]
`TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccContainerCluster_withConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/build-log/replaying_build_after_recording/TestAccContainerCluster_withConfidentialBootDisk_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/replaying_after_recording/TestAccContainerCluster_withConfidentialBootDisk.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/build-log/replaying_build_after_recording/TestAccContainerCluster_withoutConfidentialBootDisk_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/replaying_after_recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/19cbe231-d486-48f1-bf89-d3c77d96439d/recording) for each test

2023-10-16 22:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 287 insertions(+))

2023-10-16 23:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3154` 
Passed tests `2834` 
Skipped tests: `318` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerCluster_withConfidentialBootDisk|TestAccContainerCluster_withoutConfidentialBootDisk </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-17 00:03 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerCluster_withConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d45924da-0eed-4375-9917-aed16dd98b05/recording/TestAccContainerCluster_withConfidentialBootDisk.log)]
`TestAccContainerCluster_withoutConfidentialBootDisk`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d45924da-0eed-4375-9917-aed16dd98b05/recording/TestAccContainerCluster_withoutConfidentialBootDisk.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d45924da-0eed-4375-9917-aed16dd98b05/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d45924da-0eed-4375-9917-aed16dd98b05/recording) for each test

2023-10-17 16:26 UTC, shuyama1 commented on mmv1/third_party/terraform/services/container/resource_container_node_pool_test.go.erb
> +  	disk_type = "hyperdisk-balanced"
nit: spaces

2023-10-17 17:33 UTC, Sneha-at commented on mmv1/third_party/terraform/services/container/resource_container_cluster_test.go.erb
> +}
Updated all resource configurations. Please let me know if I missed any

2023-10-17 17:42 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 3 files changed, 287 insertions(+))

2023-10-17 18:56 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3153` 
Passed tests `2836` 
Skipped tests: `317` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/e93420e6-3b5d-406f-a7a4-8522ed31759a/build-log/replaying_test.log)

2023-10-17 22:59 UTC, shuyama1 requested changes
Sorry forgot that we still need to manually add documentation for handwritten resources. https://googlecloudplatform.github.io/magic-modules/develop/resource/#add-documentation
my apologies!

2023-10-17 23:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 1 file changed, 10 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 4 files changed, 297 insertions(+))

2023-10-18 00:12 UTC, shuyama1 commented on mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown
> +Enabling Confidential Storage will create boot disk with confidential mode. It is disabled by default, to enable it set `enable_confidential_storage=true` in  `node_config` in resource `google_contai
```suggestion
Enabling Confidential Storage will create boot disk with confidential mode. It is disabled by default.
```

2023-10-18 00:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 1 file changed, 3 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 4 files changed, 290 insertions(+))

2023-10-18 00:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9122-old..auto-pr-9122) ( 1 file changed, 3 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9122-old..auto-pr-9122) ( 4 files changed, 290 insertions(+))

2023-10-18 01:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3158` 
Passed tests `2839` 
Skipped tests: `318` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSpannerDatabaseIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-18 01:39 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccSpannerDatabaseIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d97062b2-9e82-4eeb-9151-1d5d2463cd70/recording/TestAccSpannerDatabaseIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d97062b2-9e82-4eeb-9151-1d5d2463cd70/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9122/artifacts/d97062b2-9e82-4eeb-9151-1d5d2463cd70/recording) for each test

2023-10-18 15:59 UTC, shuyama1 approved these changes
Thank you!

2023-10-18 16:04 UTC, merged