Add fleet_default_member_config field to google_gke_hub_feature resource
GoogleCloudPlatform/magic-modules pull request #9234
Opened 2023-10-11 20:05 UTC by sahsagar-google

Fixes https://github.com/hashicorp/terraform-provider-google/issues/16222

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
gkehub: added `fleet_default_member_config` field to `google_gke_hub_feature` resource
```

2023-10-11 20:07 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@slevenick, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-10-11 20:19 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 814 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 814 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 278 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      version {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-11 20:38 UTC, slevenick commented on mmv1/products/gkehub2/Feature.yaml
> +        name: configmanagement
Can you specify more of these fields in the tests? We try to have as many of the fields set and then changed as possible.

2023-10-11 20:51 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 840 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 840 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-11 22:06 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3146` 
Passed tests `2824` 
Skipped tests: `317` 
Affected tests: `5` 

#### Action taken 
<details> <summary>Found 5 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary|TestAccAlloydbBackup_usingCMEK|TestAccCloudRunService_cloudRunServiceSqlExample|TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-11 22:32 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording/TestAccAlloydbCluster_secondaryClusterDefinedSecondaryConfigButClusterTypeIsPrimary.log)]
`TestAccAlloydbBackup_usingCMEK`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording/TestAccAlloydbBackup_usingCMEK.log)]
`TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording/TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample.log)]
`TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccCloudRunService_cloudRunServiceSqlExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/build-log/recording_build/TestAccCloudRunService_cloudRunServiceSqlExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording/TestAccCloudRunService_cloudRunServiceSqlExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/e786ff12-6555-43e2-a762-9c0d674c5c83/recording) for each test

2023-10-16 21:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 840 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 840 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-16 22:47 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3145` 
Passed tests `2825` 
Skipped tests: `318` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample|TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-16 22:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/62fa9e2d-dcb1-4230-84ba-e0075207139a/recording/TestAccDataformRepositoryWorkflowConfig_dataformRepositoryWorkflowConfigExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/62fa9e2d-dcb1-4230-84ba-e0075207139a/build-log/recording_build/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/62fa9e2d-dcb1-4230-84ba-e0075207139a/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/62fa9e2d-dcb1-4230-84ba-e0075207139a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/62fa9e2d-dcb1-4230-84ba-e0075207139a/recording) for each test

2023-10-17 00:00 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-17 01:15 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3149` 
Passed tests `2830` 
Skipped tests: `317` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh|TestAccDataSourceGoogleServiceAccountIdToken_impersonation </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-17 01:20 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountIdToken_impersonation`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/3915101b-bcf9-4b11-a01d-d3e88019144c/recording/TestAccDataSourceGoogleServiceAccountIdToken_impersonation.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/3915101b-bcf9-4b11-a01d-d3e88019144c/build-log/recording_build/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/3915101b-bcf9-4b11-a01d-d3e88019144c/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/3915101b-bcf9-4b11-a01d-d3e88019144c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/3915101b-bcf9-4b11-a01d-d3e88019144c/recording) for each test

2023-10-17 12:59 UTC, slevenick commented
Looks like the mesh feature is not currently released

2023-10-17 19:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-17 20:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3151` 
Passed tests `2832` 
Skipped tests: `317` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh|TestAccSpannerDatabaseIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-17 20:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 830 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-17 21:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3151` 
Passed tests `2831` 
Skipped tests: `317` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleNetwork|TestAccDataSourceGoogleSubnetwork|TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-17 21:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleNetwork`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/recording/TestAccDataSourceGoogleNetwork.log)]
`TestAccDataSourceGoogleSubnetwork`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/recording/TestAccDataSourceGoogleSubnetwork.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/build-log/recording_build/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/a4c9a1e9-a3b8-4c0d-98e1-52947ecc5af6/recording) for each test

2023-10-18 20:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 832 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 832 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-18 21:51 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3159` 
Passed tests `2839` 
Skipped tests: `318` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh|TestAccHealthcareDatasetIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-18 21:56 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f0be7b00-d24a-4535-81f0-6e0bb2aa7c47/recording/TestAccHealthcareDatasetIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f0be7b00-d24a-4535-81f0-6e0bb2aa7c47/build-log/recording_build/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f0be7b00-d24a-4535-81f0-6e0bb2aa7c47/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f0be7b00-d24a-4535-81f0-6e0bb2aa7c47/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f0be7b00-d24a-4535-81f0-6e0bb2aa7c47/recording) for each test

2023-10-18 22:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 850 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 850 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-18 23:39 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3162` 
Passed tests `2843` 
Skipped tests: `318` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-18 23:45 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f9613ebe-6e0b-45d5-aa46-2641a50b5b2a/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f9613ebe-6e0b-45d5-aa46-2641a50b5b2a/build-log/replaying_build_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f9613ebe-6e0b-45d5-aa46-2641a50b5b2a/replaying_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f9613ebe-6e0b-45d5-aa46-2641a50b5b2a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f9613ebe-6e0b-45d5-aa46-2641a50b5b2a/recording) for each test

2023-10-19 00:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 894 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 894 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-19 01:17 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3162` 
Passed tests `2843` 
Skipped tests: `318` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-19 01:23 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2948d19b-b2a1-4754-9688-95810f629610/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2948d19b-b2a1-4754-9688-95810f629610/build-log/replaying_build_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2948d19b-b2a1-4754-9688-95810f629610/replaying_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2948d19b-b2a1-4754-9688-95810f629610/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2948d19b-b2a1-4754-9688-95810f629610/recording) for each test

2023-10-19 12:46 UTC, slevenick commented on mmv1/third_party/terraform/services/gkehub2/resource_gke_hub_feature_test.go.erb
> +resource "google_project_service" "test_gkehub" {
For this test to work in VCR REPLAYING mode you will need to chain all of these google_project_service resources together via depends_on.

2023-10-27 18:26 UTC, slevenick requested changes
Please fix VCR by chaining resources

2023-10-30 20:40 UTC, sahsagar-google commented
@slevenick fyi, I'm working on the comments and also adding more tests. Thank you

2023-10-31 18:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 826 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 826 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-10-31 19:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3187` 
Passed tests `2860` 
Skipped tests: `325` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh|TestAccHealthcareDatasetIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-10-31 19:50 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/9fe19e81-2155-47e2-8e4d-5472971245c7/recording/TestAccHealthcareDatasetIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/9fe19e81-2155-47e2-8e4d-5472971245c7/build-log/recording_build/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/9fe19e81-2155-47e2-8e4d-5472971245c7/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/9fe19e81-2155-47e2-8e4d-5472971245c7/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/9fe19e81-2155-47e2-8e4d-5472971245c7/recording) for each test

2023-10-31 19:55 UTC, slevenick requested changes
Test failing with: 
        Error: Error creating Feature: googleapi: Error 400: InvalidFieldError for field fleet_default_member_config: spec must be set


Are you able to run the test locally?

2023-11-01 18:54 UTC, sahsagar-google commented
> Test failing with: Error: Error creating Feature: googleapi: Error 400: InvalidFieldError for field fleet_default_member_config: spec must be set
> 
> Are you able to run the test locally?

Investigating this. I think the visibility flag removal for the field is not rolled out fully. Let me deep-dive and reply back with the latest update. Thank you

2023-11-01 21:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 926 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 926 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-11-01 22:43 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3197` 
Passed tests `2869` 
Skipped tests: `325` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocClusterIamPolicy|TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement|TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-01 22:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocClusterIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/recording/TestAccDataprocClusterIamPolicy.log)]
`TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement.log)]
`TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{red}{\textsf{Tests failed when rerunning REPLAYING mode:}}$ 
 `TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/build-log/replaying_build_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/replaying_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigConfigManagement.log)]
`TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/build-log/replaying_build_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh_replaying_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/replaying_after_recording/TestAccGKEHubFeature_FleetDefaultMemberConfigServiceMesh.log)] 

Tests failed due to non-determinism or randomness when the VCR replayed the response after the HTTP request was made.

Please fix these to complete your PR. If you believe these test failures to be incorrect or unrelated to your change, or if you have any questions, please raise the concern with your reviewer.

---
$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/4f590f36-d86f-4801-90d8-9a5aba4f4463/recording) for each test

2023-11-02 20:54 UTC, slevenick reviewed
Ah, looks like using gkeHubFeatureProjectSetupForGA in these tests messes with VCR, so I would re-add the skipIfVcr

2023-11-03 00:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 926 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 926 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-11-03 01:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3202` 
Passed tests `2873` 
Skipped tests: `327` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccLoggingBucketConfigProject_locked|TestAccLoggingProjectSink_updatePreservesCustomWriter </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-03 01:26 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccLoggingBucketConfigProject_locked`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/build-log/recording_build/TestAccLoggingBucketConfigProject_locked_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/recording/TestAccLoggingBucketConfigProject_locked.log)]
`TestAccLoggingProjectSink_updatePreservesCustomWriter`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/build-log/recording_build/TestAccLoggingProjectSink_updatePreservesCustomWriter_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/recording/TestAccLoggingProjectSink_updatePreservesCustomWriter.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/f2c4f92f-f29e-41b9-9b26-0fcc25d482eb/recording) for each test

2023-11-03 22:37 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 914 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 914 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-11-03 23:49 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3205` 
Passed tests `2877` 
Skipped tests: `325` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccContainerAwsCluster_BetaBasicEnumHandWritten|TestAccLoggingProjectSink_updatePreservesCustomWriter </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-03 23:54 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerAwsCluster_BetaBasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/recording/TestAccContainerAwsCluster_BetaBasicHandWritten.log)]
`TestAccContainerAwsCluster_BetaBasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/recording/TestAccContainerAwsCluster_BetaBasicEnumHandWritten.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccLoggingProjectSink_updatePreservesCustomWriter`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/build-log/recording_build/TestAccLoggingProjectSink_updatePreservesCustomWriter_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/recording/TestAccLoggingProjectSink_updatePreservesCustomWriter.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/8f6faec7-1ff3-4416-b3fc-c41ff41faa70/recording) for each test

2023-11-06 17:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 919 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 919 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-11-06 18:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 919 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9234-old..auto-pr-9234) ( 3 files changed, 919 insertions(+))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9234-old..auto-pr-9234) ( 1 file changed, 289 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_gke_hub_feature` (5 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature" "primary" {
  fleet_default_member_config {
    configmanagement {
      config_sync {
        git {
          gcp_service_account_email = # value needed
          https_proxy               = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_branch               = # value needed
          sync_repo                 = # value needed
          sync_rev                  = # value needed
          sync_wait_secs            = # value needed
        }
        oci {
          gcp_service_account_email = # value needed
          policy_dir                = # value needed
          secret_type               = # value needed
          sync_repo                 = # value needed
          sync_wait_secs            = # value needed
          version                   = # value needed
        }
        source_format = # value needed
      }
    }
    mesh {
      management = # value needed
    }
  }
}

```

2023-11-06 19:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3205` 
Passed tests `2879` 
Skipped tests: `325` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccLoggingProjectSink_updatePreservesCustomWriter </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-06 19:48 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccLoggingProjectSink_updatePreservesCustomWriter`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2ca5fe85-189d-42cd-9e8b-57a0558a9445/build-log/recording_build/TestAccLoggingProjectSink_updatePreservesCustomWriter_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2ca5fe85-189d-42cd-9e8b-57a0558a9445/recording/TestAccLoggingProjectSink_updatePreservesCustomWriter.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2ca5fe85-189d-42cd-9e8b-57a0558a9445/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9234/artifacts/2ca5fe85-189d-42cd-9e8b-57a0558a9445/recording) for each test

2023-11-06 22:05 UTC, slevenick approved these changes

2023-11-06 22:05 UTC, merged