add autoNetworkTier to Router NAT
GoogleCloudPlatform/magic-modules pull request #9379
Opened 2023-10-30 11:51 UTC by maxi-cit

Fixes: https://github.com/hashicorp/terraform-provider-google/issues/16139

It adds support to set the network tier to use when automatically reserving NAT IP Addresses

If this PR is for Terraform, I acknowledge that I have:

- [x] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [`make test` and `make lint`](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
- [] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/develop/run-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [x] Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhacement
compute: added `auto_network_tier` field to `google_compute_router_nat` resource
```

2023-10-30 11:52 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@trodge, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-10-30 20:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 2 files changed, 38 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 2 files changed, 38 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2023-10-30 21:56 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeRouterNat_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/build-log/recording_build/TestAccComputeRouterNat_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/recording/TestAccComputeRouterNat_update.log)]
`TestAccComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/build-log/recording_build/TestAccComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/recording/TestAccComputeRouterNat_basic.log)]
`TestAccComputeRouterNat_removeLogConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/build-log/recording_build/TestAccComputeRouterNat_removeLogConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/recording/TestAccComputeRouterNat_removeLogConfig.log)]
`TestAccDataSourceGoogleComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/build-log/recording_build/TestAccDataSourceGoogleComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/recording/TestAccDataSourceGoogleComputeRouterNat_basic.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/074405f8-11fb-48ac-af2a-8476f56ccef0/recording) for each test

2023-11-02 22:38 UTC, trodge commented on mmv1/products/compute/RouterNat.yaml
> +      - :STANDAR
```suggestion
      - :STANDARD
```

2023-11-02 22:57 UTC, trodge requested changes
We will need some way to handle the values the API returns for this field for existing resources.

The field value is derived from a setting on the project that the resource belongs to, so one option would be to try to look up that value and set it in an encoder when it's unspecified. However, I don't know of an easy way to get that information.

The alternative would be to use `default_from_api: true` on this field, but that would mean that deleting this field from the configuration would preserve whatever the last value was even if the project-level default changed.

2023-11-07 13:43 UTC, maxi-cit commented
Hello @trodge, I have been studying the first case and I think is somewhat doable.
However, could you explain about the latter case, please?

2023-11-13 19:56 UTC, maxi-cit commented on mmv1/products/compute/RouterNat.yaml
> +      - :STANDAR
done

2023-11-17 21:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 2 files changed, 38 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 2 files changed, 38 insertions(+))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (11 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2023-11-17 22:48 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeRouterNat_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/build-log/recording_build/TestAccComputeRouterNat_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/recording/TestAccComputeRouterNat_update.log)]
`TestAccComputeRouterNat_removeLogConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/build-log/recording_build/TestAccComputeRouterNat_removeLogConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/recording/TestAccComputeRouterNat_removeLogConfig.log)]
`TestAccComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/build-log/recording_build/TestAccComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/recording/TestAccComputeRouterNat_basic.log)]
`TestAccDataSourceGoogleComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/build-log/recording_build/TestAccDataSourceGoogleComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/recording/TestAccDataSourceGoogleComputeRouterNat_basic.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/70d98cb5-c9ff-455c-9598-15d077d89fe4/recording) for each test

2023-12-01 02:05 UTC, trodge commented
> Hello @trodge, I have been studying the first case and I think is somewhat doable. However, could you explain about the latter case, please?

Setting `default_from_api` will make the field `Optional` and `Computed` in the provider, which means that any value returned from the API will be treated as though it matches an empty value in the user's config.

2024-01-23 13:23 UTC, maxi-cit commented
Helllo @trodge I tried to implement your encoder fix so it will take the project default when empty. Could you take a look, please?

2024-02-16 23:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 2 files changed, 69 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 112 insertions(+), 5 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (17 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2024-02-16 23:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `887` 
Passed tests `802` 
Skipped tests: `72` 
Affected tests: `13` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 13 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_AutoNetworkTier|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withNatIpsAndDrainNatIps|TestAccDataSourceGoogleComputeRouterNat_basic|TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges|TestAccComputeRouterNat_update|TestAccComputeRouterNat_removeLogConfig|TestAccComputeRouterNat_withPrivateNatAndEmptyAction|TestAccComputeRouterNat_basic|TestAccComputeRouterNat_withPrivateNatAndRules </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-02-16 23:50 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccComputeRouterNat_withPrivateNat`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withPrivateNat.log)]
`TestAccComputeRouterNat_withManualIpAndSubnetConfiguration`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withManualIpAndSubnetConfiguration.log)]
`TestAccComputeRouterNat_withNatRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withNatRules.log)]
`TestAccComputeRouterNat_withPortAllocationMethods`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withPortAllocationMethods.log)]
`TestAccComputeRouterNat_withNatIpsAndDrainNatIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withNatIpsAndDrainNatIps.log)]
`TestAccComputeRouterNat_withPrivateNatAndRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withPrivateNatAndRules.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccComputeRouterNat_AutoNetworkTier`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_AutoNetworkTier_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_AutoNetworkTier.log)]
`TestAccDataSourceGoogleComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccDataSourceGoogleComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccDataSourceGoogleComputeRouterNat_basic.log)]
`TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withPrivateNatAndEmptyActionActiveRanges.log)]
`TestAccComputeRouterNat_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_update.log)]
`TestAccComputeRouterNat_removeLogConfig`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_removeLogConfig_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_removeLogConfig.log)]
`TestAccComputeRouterNat_withPrivateNatAndEmptyAction`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_withPrivateNatAndEmptyAction_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_withPrivateNatAndEmptyAction.log)]
`TestAccComputeRouterNat_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_build/TestAccComputeRouterNat_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording/TestAccComputeRouterNat_basic.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/564dedca-c30c-4ff5-a3d0-80efe9e43656/recording) for each test

2024-04-05 22:05 UTC, melinath commented
@maxi-cit is this PR still active?

2024-04-09 17:50 UTC, maxi-cit commented
Hello @melinath, sorry for the late reply. it is active but other products got higher prio. However I will comeback to this one later in the week.

2024-04-23 16:21 UTC, maxi-cit commented
Hello @trodge I updated this PR making this new field default_from_api. I tried the encoder fix but it does not seems that this field should be tied to the project level default changes. I believe that we can have this field 'immutable' so it gets recreated anytime the API returns a different network tier value.
do you think I should add a special note for this field?

2024-04-23 19:11 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 80 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 85 insertions(+), 5 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2024-04-23 19:33 UTC, modular-magician commented
#### Tests analytics
Total tests: `900`
Passed tests: `820`
Skipped tests: `72`
Affected tests: `8`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 8 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy|TestAccComputeRouterNat_AutoNetworkTier|TestAccComputeRouterNat_withManualIpAndSubnetConfiguration|TestAccComputeRouterNat_withNatIpsAndDrainNatIps|TestAccComputeRouterNat_withNatRules|TestAccComputeRouterNat_withPortAllocationMethods|TestAccComputeRouterNat_withPrivateNat|TestAccComputeRouterNat_withPrivateNatAndRules </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-04-23 19:42 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]
`TestAccComputeRouterNat_AutoNetworkTier`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_AutoNetworkTier.log)]
`TestAccComputeRouterNat_withManualIpAndSubnetConfiguration`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withManualIpAndSubnetConfiguration.log)]
`TestAccComputeRouterNat_withNatIpsAndDrainNatIps`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withNatIpsAndDrainNatIps.log)]
`TestAccComputeRouterNat_withNatRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withNatRules.log)]
`TestAccComputeRouterNat_withPortAllocationMethods`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withPortAllocationMethods.log)]
`TestAccComputeRouterNat_withPrivateNat`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withPrivateNat.log)]
`TestAccComputeRouterNat_withPrivateNatAndRules`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording/TestAccComputeRouterNat_withPrivateNatAndRules.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/b7c2b176-0708-42f8-bfda-a451d938cf9a/recording) for each test

2024-05-07 17:41 UTC, trodge commented
/gcbrun

2024-05-07 18:43 UTC, trodge requested changes
It looks like `testAccComputeRouterNatBaseResourcesWithPrivateNatSubnetworks` was moved inside `<% unless version == "ga" -%>` guards, making it beta only. To get this to compile you'll need to move that function outside the beta-only guard.

2024-05-07 18:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 80 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 85 insertions(+), 5 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2024-05-07 19:08 UTC, modular-magician commented
#### Tests analytics
Total tests: `907`
Passed tests: `834`
Skipped tests: `72`
Affected tests: `1`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

#### Action taken
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-05-07 19:15 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/1f4703c1-a10f-4d37-818b-913aa409c68c/recording/TestAccComputeRegionPerInstanceConfig_removeInstanceOnDestroy.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/1f4703c1-a10f-4d37-818b-913aa409c68c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/1f4703c1-a10f-4d37-818b-913aa409c68c/recording) for each test

2024-05-08 15:33 UTC, maxi-cit commented
Hello @trodge  thanks for the feedback. I applied your suggestions and moved the function. This should be fixing it, but if fails on the ga-provider I will make a separate one

2024-05-08 20:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 148 insertions(+))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9379-old..auto-pr-9379) ( 3 files changed, 122 insertions(+), 42 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_compute_router_nat` (21 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_compute_router_nat" "primary" {
  auto_network_tier = # value needed
}

```

2024-05-08 20:35 UTC, modular-magician commented
#### Tests analytics
Total tests: `914`
Passed tests: `842`
Skipped tests: `72`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9379/artifacts/bc60e9d5-4b1e-4356-8e90-84c8f8b247f3/build-log/replaying_test.log)

2024-05-08 20:36 UTC, trodge approved these changes

2024-05-08 20:36 UTC, merged