VCR split test
GoogleCloudPlatform/magic-modules pull request #9392
Opened 2023-11-02 00:10 UTC by shuyama1

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-11-02 00:20 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-11-02 00:34 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 1 file changed, 1 insertion(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 1 file changed, 1 insertion(+), 1 deletion(-))

2023-11-02 01:46 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3197` 
Passed tests `2871` 
Skipped tests: `325` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2Job_cloudrunv2JobFullUpdate </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-02 01:55 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccCloudRunV2Job_cloudrunv2JobFullUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/fc559995-0e11-4ccf-a280-0b7946ebee86/recording/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/fc559995-0e11-4ccf-a280-0b7946ebee86/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/fc559995-0e11-4ccf-a280-0b7946ebee86/recording) for each test

2023-11-02 02:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))

2023-11-02 02:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `24` 
Passed tests `22` 
Skipped tests: `2` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/34c6992f-8dbe-4d9c-9984-4a801f3ab0b7/build-log/replaying_test.log)

2023-11-02 02:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))

2023-11-02 02:53 UTC, modular-magician commented
#### Tests analytics 
Total tests: `111` 
Passed tests `101` 
Skipped tests: `7` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig|TestAccDataSourceGoogleCloudRunV2Job_basic|TestAccCloudRunV2Job_cloudrunv2JobFullUpdate </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-02 03:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/a5f56773-ac78-40f7-a0f7-7e12df9b8522/recording/TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig.log)]
`TestAccDataSourceGoogleCloudRunV2Job_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/a5f56773-ac78-40f7-a0f7-7e12df9b8522/recording/TestAccDataSourceGoogleCloudRunV2Job_basic.log)]
`TestAccCloudRunV2Job_cloudrunv2JobFullUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/a5f56773-ac78-40f7-a0f7-7e12df9b8522/recording/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/a5f56773-ac78-40f7-a0f7-7e12df9b8522/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/a5f56773-ac78-40f7-a0f7-7e12df9b8522/recording) for each test

2023-11-02 19:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))

2023-11-02 20:03 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))

2023-11-02 20:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `111` 
Passed tests `101` 
Skipped tests: `7` 
Affected tests: `3` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrun</li><li>dataproc</li><li>cloudrunv2</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig|TestAccDataSourceGoogleCloudRunV2Job_basic|TestAccCloudRunV2Job_cloudrunv2JobFullUpdate </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-02 20:21 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/337dba48-5ab6-4eb0-8810-d6b5670fe727/recording/TestAccDataprocCluster_withInternalIpOnlyTrueAndShieldedConfig.log)]
`TestAccDataSourceGoogleCloudRunV2Job_basic`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/337dba48-5ab6-4eb0-8810-d6b5670fe727/recording/TestAccDataSourceGoogleCloudRunV2Job_basic.log)]
`TestAccCloudRunV2Job_cloudrunv2JobFullUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/337dba48-5ab6-4eb0-8810-d6b5670fe727/recording/TestAccCloudRunV2Job_cloudrunv2JobFullUpdate.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/337dba48-5ab6-4eb0-8810-d6b5670fe727/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/337dba48-5ab6-4eb0-8810-d6b5670fe727/recording) for each test

2023-11-08 21:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9392-old..auto-pr-9392) ( 4 files changed, 4 insertions(+), 4 deletions(-))

2023-11-08 21:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `112` 
Passed tests `104` 
Skipped tests: `8` 
Affected tests: `0` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrun</li><li>dataproc</li><li>cloudrunv2</li></ul></blockquote></details> 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/01157e41-69af-46ac-a264-5671f14f7f57/build-log/replaying_test.log)

2023-12-18 17:19 UTC, modular-magician commented
#### Tests analytics 
Total tests: `115` 
Passed tests `107` 
Skipped tests: `8` 
Affected tests: `0` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>cloudrun</li><li>dataproc</li><li>cloudrunv2</li></ul></blockquote></details> 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9392/artifacts/f1af9065-6770-4ef5-be94-216f2d250fe6/build-log/replaying_test.log)

2023-12-18 17:46 UTC, shuyama1 commented
Added `affected service packages` in the test report. see https://github.com/GoogleCloudPlatform/magic-modules/pull/9392#issuecomment-1861110946

Already cleaned up the cassettes recorded for testing this PR change.

2023-12-18 21:00 UTC, trodge requested changes

2023-12-18 23:01 UTC, melinath approved these changes
LGTM overall

2023-12-19 20:41 UTC, shuyama1 commented on .ci/scripts/go-plus/gcb-terraform-vcr-tester/test_terraform_vcr.sh
> -counter=1
When VCR was initially set up in GCB, we used to run into replaying tests got terminated due to non-provider-related issues, so we rerun the tests if that error occurred (with max retry: 3) example: https://github.com/GoogleCloudPlatform/magic-modules/pull/5881#issuecomment-1086319609

The issue should be resolved after we pre-install Terraform, but we never removed the logic. I've never seen any VCR test rerun needed for replaying mode after https://github.com/GoogleCloudPlatform/magic-modules/pull/6034, so I think it should be safe to remove it.

I agree it's unrelated - I could keep it for now and remove it in a separate PR.

2023-12-19 21:18 UTC, melinath commented on .ci/scripts/go-plus/gcb-terraform-vcr-tester/test_terraform_vcr.sh
> -counter=1
I'm fine with keeping this in

2023-12-19 23:55 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2023-12-20 00:07 UTC, shuyama1 commented on .ci/scripts/go-plus/gcb-terraform-vcr-tester/test_terraform_vcr.sh
> +    affected_services[$(echo "$file" | awk -F / '{ print $3 }')]=1
Added. Let me know if any part is still unclear and needs more comments. Thanks:)

2023-12-21 00:17 UTC, trodge approved these changes

2023-12-21 00:40 UTC, merged