Upgrade DCL to 1.56.0
GoogleCloudPlatform/magic-modules pull request #9393
Opened 2023-11-02 17:48 UTC by zli82016

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2023-11-02 17:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9393-old..auto-pr-9393) ( 16 files changed, 1312 insertions(+), 122 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9393-old..auto-pr-9393) ( 15 files changed, 1016 insertions(+), 124 deletions(-))
## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_assured_workloads_workload` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_assured_workloads_workload" "primary" {
  enable_sovereign_controls = # value needed
  partner                   = # value needed
  partner_permissions {
    assured_workloads_monitoring = # value needed
    data_logs_viewer             = # value needed
    service_access_approver      = # value needed
  }
  resource_settings {
    display_name = # value needed
  }
  violation_notifications_enabled = # value needed
}

```
Resource: `google_container_aws_cluster` (16 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_aws_cluster" "primary" {
  authorization {
    admin_groups {
      group = # value needed
    }
  }
}

```
Resource: `google_container_azure_cluster` (10 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_container_azure_cluster" "primary" {
  authorization {
    admin_groups {
      group = # value needed
    }
  }
}

```
Resource: `google_gke_hub_feature_membership` (0 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_gke_hub_feature_membership" "primary" {
  configmanagement {
    config_sync {
      metrics_gcp_service_account_email = # value needed
    }
  }
}

```
Resource: `google_org_policy_policy` (8 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_org_policy_policy" "primary" {
  dry_run_spec {
    inherit_from_parent = # value needed
    reset               = # value needed
    rules {
      allow_all = # value needed
      condition {
        description = # value needed
        expression  = # value needed
        location    = # value needed
        title       = # value needed
      }
      deny_all = # value needed
      enforce  = # value needed
      values {
        allowed_values = # value needed
        denied_values  = # value needed
      }
    }
  }
}

```

2023-11-02 19:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3197` 
Passed tests `2857` 
Skipped tests: `325` 
Affected tests: `15` 

#### Action taken 
<details> <summary>Found 15 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccAssuredWorkloadsWorkload_BasicHandWritten|TestAccAssuredWorkloadsWorkload_FullHandWritten|TestAccContainerAwsCluster_BasicEnumHandWritten|TestAccContainerAwsCluster_BetaBasicEnumHandWritten|TestAccContainerAwsNodePool_BasicHandWritten|TestAccContainerAwsNodePool_BetaBasicEnumHandWritten|TestAccContainerAwsCluster_BetaBasicHandWritten|TestAccContainerAwsCluster_BasicHandWritten|TestAccContainerAwsNodePool_BasicEnumHandWritten|TestAccContainerAwsNodePool_BetaBasicHandWritten|TestAccContainerAzureCluster_BetaBasicHandWritten|TestAccContainerAzureCluster_BetaBasicEnumHandWritten|TestAccContainerAzureNodePool_BasicHandWritten|TestAccContainerAzureCluster_BasicHandWritten|TestAccContainerAzureNodePool_BetaBasicHandWritten </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-02 19:37 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerAwsCluster_BasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsCluster_BasicEnumHandWritten.log)]
`TestAccContainerAwsCluster_BetaBasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsCluster_BetaBasicEnumHandWritten.log)]
`TestAccContainerAwsNodePool_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsNodePool_BasicHandWritten.log)]
`TestAccContainerAwsNodePool_BetaBasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsNodePool_BetaBasicEnumHandWritten.log)]
`TestAccContainerAwsCluster_BetaBasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsCluster_BetaBasicHandWritten.log)]
`TestAccContainerAwsCluster_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsCluster_BasicHandWritten.log)]
`TestAccContainerAwsNodePool_BasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsNodePool_BasicEnumHandWritten.log)]
`TestAccContainerAwsNodePool_BetaBasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAwsNodePool_BetaBasicHandWritten.log)]
`TestAccContainerAzureCluster_BetaBasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAzureCluster_BetaBasicHandWritten.log)]
`TestAccContainerAzureCluster_BetaBasicEnumHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAzureCluster_BetaBasicEnumHandWritten.log)]
`TestAccContainerAzureNodePool_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAzureNodePool_BasicHandWritten.log)]
`TestAccContainerAzureCluster_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAzureCluster_BasicHandWritten.log)]
`TestAccContainerAzureNodePool_BetaBasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccContainerAzureNodePool_BetaBasicHandWritten.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccAssuredWorkloadsWorkload_BasicHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/build-log/recording_build/TestAccAssuredWorkloadsWorkload_BasicHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccAssuredWorkloadsWorkload_BasicHandWritten.log)]
`TestAccAssuredWorkloadsWorkload_FullHandWritten`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/build-log/recording_build/TestAccAssuredWorkloadsWorkload_FullHandWritten_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording/TestAccAssuredWorkloadsWorkload_FullHandWritten.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/e10ec349-7c45-46c7-a23e-169042dcc4c8/recording) for each test

2023-11-03 04:33 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9393-old..auto-pr-9393) ( 4 files changed, 305 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9393-old..auto-pr-9393) ( 3 files changed, 9 insertions(+), 11 deletions(-))

2023-11-03 05:45 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3200` 
Passed tests `2869` 
Skipped tests: `325` 
Affected tests: `6` 

#### Action taken 
<details> <summary>Found 6 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerAwsCluster_BasicHandWritten|TestAccContainerAzureCluster_BasicHandWritten|TestAccDataprocClusterIamPolicy|TestAccDataprocJobIamPolicy|TestAccLoggingBucketConfigProject_locked|TestAccLoggingProjectSink_updatePreservesCustomWriter </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-03 05:57 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerAwsCluster_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccContainerAwsCluster_BasicHandWritten.log)]
`TestAccContainerAzureCluster_BasicHandWritten`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccContainerAzureCluster_BasicHandWritten.log)]
`TestAccDataprocClusterIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccDataprocClusterIamPolicy.log)]
`TestAccDataprocJobIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccDataprocJobIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccLoggingBucketConfigProject_locked`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/build-log/recording_build/TestAccLoggingBucketConfigProject_locked_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccLoggingBucketConfigProject_locked.log)]
`TestAccLoggingProjectSink_updatePreservesCustomWriter`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/build-log/recording_build/TestAccLoggingProjectSink_updatePreservesCustomWriter_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording/TestAccLoggingProjectSink_updatePreservesCustomWriter.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9393/artifacts/77cf646b-8044-401d-85bb-ec1faf5f5d55/recording) for each test

2023-11-03 16:56 UTC, slevenick requested changes
Can you add release notes for the other changes included in this upgrade? It looks like several resources received new fields

2023-11-03 17:16 UTC, zli82016 commented
> Can you add release notes for the other changes included in this upgrade? It looks like several resources received new fields

The other resources are added by DCL 1.55.0 and covered in PR https://github.com/GoogleCloudPlatform/magic-modules/pull/9370. I already rebased the main branch for this PR and should be good.

2023-11-08 17:17 UTC, slevenick approved these changes

2023-11-08 17:18 UTC, merged