Iam group auth
GoogleCloudPlatform/magic-modules pull request #9505
Opened 2023-11-21 11:53 UTC by pratikgarg10

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME
sql: added support for additional ENUM values for the `type` field on `google_sql_user` to support IAM GROUP authentication
```

2023-11-21 11:55 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@NickElliot, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-11-21 12:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 23 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 23 insertions(+), 4 deletions(-))

2023-11-21 13:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3236` 
Passed tests `2905` 
Skipped tests: `330` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSqlUser_postgresIAM </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-21 13:32 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccSqlUser_postgresIAM`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/177b03ca-da32-4dc1-b407-a0bfb232c7af/build-log/recording_build/TestAccSqlUser_postgresIAM_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/177b03ca-da32-4dc1-b407-a0bfb232c7af/recording/TestAccSqlUser_postgresIAM.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/177b03ca-da32-4dc1-b407-a0bfb232c7af/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/177b03ca-da32-4dc1-b407-a0bfb232c7af/recording) for each test

2023-11-22 15:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 27 insertions(+), 5 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 27 insertions(+), 5 deletions(-))

2023-11-22 16:42 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3237` 
Passed tests `2906` 
Skipped tests: `330` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccSqlUser_postgresIAM </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-22 16:54 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccSqlUser_postgresIAM`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/2e7b506e-94e6-429b-a1c9-55056c4d521c/build-log/recording_build/TestAccSqlUser_postgresIAM_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/2e7b506e-94e6-429b-a1c9-55056c4d521c/recording/TestAccSqlUser_postgresIAM.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/2e7b506e-94e6-429b-a1c9-55056c4d521c/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/2e7b506e-94e6-429b-a1c9-55056c4d521c/recording) for each test

2023-11-22 19:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 17 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 17 insertions(+), 3 deletions(-))

2023-11-22 20:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3237` 
Passed tests `2907` 
Skipped tests: `330` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9505/artifacts/408d6b52-f9ae-42df-a3ef-dcacdf5b29b7/build-log/replaying_test.log)

2023-11-27 17:24 UTC, NickElliot requested changes
A couple formatting changes needed but also wanted to ask one thing for clarification:
the test case with "CLOUD_IAM_GROUP_USER" was removed after the test failure above saying it was not an allowed user type -- was that an issue with just that particular instance/permissions on the test project, or is there other necessary pre requisites for creating an IAM_GROUP_USER

2023-11-27 18:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 17 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9505-old..auto-pr-9505) ( 3 files changed, 17 insertions(+), 3 deletions(-))

2023-11-27 18:23 UTC, pratikgarg10 commented
> A couple formatting changes needed but also wanted to ask one thing for clarification: the test case with "CLOUD_IAM_GROUP_USER" was removed after the test failure above saying it was not an allowed user type -- was that an issue with just that particular instance/permissions on the test project, or is there other necessary pre requisites for creating an IAM_GROUP_USER

Updated formatting changes. The reverted test was for postgresql which is currently not supported.

2023-11-28 18:49 UTC, NickElliot approved these changes
Looks good to me then!

2023-11-28 18:53 UTC, merged