feat(vertexai): Support vertex_ai_feature_group
GoogleCloudPlatform/magic-modules pull request #9520
Opened 2023-11-25 16:17 UTC by shotarok

A part of https://github.com/hashicorp/terraform-provider-google/issues/16516

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
vertex_ai_feature_group
```

2023-11-25 16:18 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@NickElliot, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-11-28 19:00 UTC, shotarok commented
@NickElliot Hello 👋 Could you approve the cloud build jobs to run acceptance tests?

2023-11-28 19:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1310 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1310 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9520-old..auto-pr-9520) ( 1 file changed, 155 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9520-old..auto-pr-9520) ( 4 files changed, 149 insertions(+))

2023-11-29 21:25 UTC, NickElliot commented
/gcbrun

2023-11-29 21:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1310 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1310 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9520-old..auto-pr-9520) ( 1 file changed, 155 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9520-old..auto-pr-9520) ( 4 files changed, 149 insertions(+))

2023-11-29 22:48 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3244` 
Passed tests `2911` 
Skipped tests: `331` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccVertexAIFeatureGroup_updated|TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-11-29 22:52 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureGroup_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f3e1fff5-b0ac-4320-9c69-124cc2496f12/recording/TestAccVertexAIFeatureGroup_updated.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f3e1fff5-b0ac-4320-9c69-124cc2496f12/build-log/recording_build/TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f3e1fff5-b0ac-4320-9c69-124cc2496f12/recording/TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f3e1fff5-b0ac-4320-9c69-124cc2496f12/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f3e1fff5-b0ac-4320-9c69-124cc2496f12/recording) for each test

2023-11-29 23:11 UTC, shotarok commented
Because `TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample` should be a subset of `TestAccVertexAIFeatureGroup_updated`, I'm wondering why the only generated test failed. Could you tell me the error message? Or could you rerun the CI job?

2023-12-04 23:01 UTC, NickElliot requested changes
Hi! The tests are having issues due to a resource name conflict -- this is because both tests are using the static "sample_feature_group_movie_reviews" name. Could you update the generated sample to use a templated value for this name, the instructions located [here](https://googlecloudplatform.github.io/magic-modules/develop/test/) should show how to do that. Also ideally the tests should be as generic as possible -- can replace the name with something like "example_name" for the name field and "example_id" for the column label.

Thanks for the contributions!

2023-12-04 23:01 UTC, NickElliot commented on mmv1/third_party/terraform/services/vertexai/resource_vertex_ai_feature_group_test.go
> +        "name": "movie_id",
also needs genericizing, and is the review column needed for feature group to function? It could be removed from all the samples if not

2023-12-12 21:51 UTC, shotarok commented on mmv1/templates/terraform/examples/vertex_ai_feature_group.tf.erb
> +resource "google_bigquery_table" "sample_table" {
I updated column names as `feature_id` and `feautre_timestamp`!

2023-12-12 22:24 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1290 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1290 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9520-old..auto-pr-9520) ( 1 file changed, 155 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9520-old..auto-pr-9520) ( 4 files changed, 144 insertions(+))

2023-12-12 23:21 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3294` 
Passed tests `2954` 
Skipped tests: `338` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample|TestAccVertexAIFeatureGroup_updated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-12 23:26 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/4db6063b-8d27-453b-8b57-3d1530bf5ca9/recording/TestAccVertexAIFeatureGroup_vertexAiFeatureGroupExample.log)]
`TestAccVertexAIFeatureGroup_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/4db6063b-8d27-453b-8b57-3d1530bf5ca9/recording/TestAccVertexAIFeatureGroup_updated.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/4db6063b-8d27-453b-8b57-3d1530bf5ca9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/4db6063b-8d27-453b-8b57-3d1530bf5ca9/recording) for each test

2023-12-14 22:26 UTC, NickElliot requested changes
Last couple changes! Thanks for contributing

2023-12-14 22:27 UTC, NickElliot commented on mmv1/products/vertexai/FeatureGroup.yaml
> +  api: https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureGroups
```suggestion
references: !ruby/object:Api::Resource::ReferenceLinks
  guides: 
    'Creating a Feature Group': 'https://cloud.google.com/vertex-ai/docs/featurestore/latest/create-featuregroup'
  api: 'https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureGroups'
```

2023-12-14 22:28 UTC, NickElliot commented on mmv1/third_party/terraform/services/vertexai/resource_vertex_ai_feature_group_test.go
> +        # The source table must have a column named 'feature_timestamp' of type TIMESTAMP.
```suggestion
```
Can remove this explanatory comment from non-example tests

2023-12-14 22:28 UTC, NickElliot commented on mmv1/third_party/terraform/services/vertexai/resource_vertex_ai_feature_group_test.go
> +        # The source table must have a column named 'feature_timestamp' of type TIMESTAMP.
```suggestion
```
Can remove this explanatory comment from non-example tests

2023-12-14 22:33 UTC, shotarok reviewed
format yaml based on yamllint

2023-12-14 22:41 UTC, shotarok commented
@NickElliot Thank you for your reviews! I've applied your suggestions. Could you re-approve the cloud build jobs? Thanks!

2023-12-15 18:01 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9520-old..auto-pr-9520) ( 7 files changed, 1295 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9520-old..auto-pr-9520) ( 6 files changed, 1290 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9520-old..auto-pr-9520) ( 1 file changed, 155 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9520-old..auto-pr-9520) ( 4 files changed, 144 insertions(+))

2023-12-15 18:59 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3298` 
Passed tests `2961` 
Skipped tests: `337` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9520/artifacts/f7ebe843-ae5b-4ad7-aaab-e0a502419c58/build-log/replaying_test.log)

2023-12-19 20:17 UTC, shotarok commented
@NickElliot Hello, please let me know if there are additional action items. Thanks!

2023-12-19 21:56 UTC, NickElliot approved these changes
LGTM! Thanks for the contribution

2023-12-19 21:57 UTC, merged