Cloud Run v2 limits examples and docs
GoogleCloudPlatform/magic-modules pull request #9563
Opened 2023-12-01 19:27 UTC by wiktorn

Improve documentation for limits and provide examples how they can be used in Cloud Run Service and Job.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none
```

2023-12-01 19:28 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@roaks3, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-12-04 16:29 UTC, roaks3 requested changes
LGTM, just some clean-up comments

2023-12-04 17:32 UTC, wiktorn commented on mmv1/products/cloudrunv2/Job.yaml
> +    primary_resource_name: "fmt.Sprintf(\"tf-test-cloudrun-job%s\",
Removed, though I take those from other examples around, so there is an opportunity for a greater cleanup.

2023-12-04 17:33 UTC, wiktorn commented on mmv1/templates/terraform/decoders/artifact_registry.go.erb
> +<%# The license inside this block applies to this file.
Removed the file from the history. Indeed, that was leftover from some other testing.

2023-12-04 20:06 UTC, roaks3 commented on mmv1/products/cloudrunv2/Job.yaml
> +    primary_resource_name: "fmt.Sprintf(\"tf-test-cloudrun-job%s\",
Oh interesting, it's possible they were left behind from an earlier version of the generator. Thanks for flagging!

2023-12-04 20:15 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9563-old..auto-pr-9563) ( 6 files changed, 166 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9563-old..auto-pr-9563) ( 6 files changed, 166 insertions(+), 4 deletions(-))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9563-old..auto-pr-9563) ( 8 files changed, 243 insertions(+))

2023-12-04 21:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3260` 
Passed tests `2926` 
Skipped tests: `332` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccCloudRunV2Job_cloudrunv2JobLimitsExample|TestAccCloudRunV2Service_cloudrunv2ServiceLimitsExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-04 21:33 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccCloudRunV2Job_cloudrunv2JobLimitsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9563/artifacts/466923ab-021b-447d-b444-e6da136ae8da/recording/TestAccCloudRunV2Job_cloudrunv2JobLimitsExample.log)]
`TestAccCloudRunV2Service_cloudrunv2ServiceLimitsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9563/artifacts/466923ab-021b-447d-b444-e6da136ae8da/recording/TestAccCloudRunV2Service_cloudrunv2ServiceLimitsExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9563/artifacts/466923ab-021b-447d-b444-e6da136ae8da/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9563/artifacts/466923ab-021b-447d-b444-e6da136ae8da/recording) for each test

2023-12-04 21:49 UTC, roaks3 approved these changes
LGTM, and tests pass

2023-12-04 21:49 UTC, merged