Do not replace GKE's NodePool resource on machineType/diskType/diskSizeGb change
GoogleCloudPlatform/magic-modules pull request #9575
Opened 2023-12-03 22:43 UTC by same-id

This is not possible using the user interface in GCP yet, but according to API this can be done and does not requires a replace.

  https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters.nodePools/update

"Initiates an upgrade operation that migrates the nodes in the node pool to the specified [machine type/disk type/disk size]."

**Release Note Template for Downstream PRs (will be copied)**

```release-note:enhancement
container: changed `machineType`/`diskType`/`diskSizeGb` to `ForceNew: false` on `NodePool`
```

2023-12-06 11:40 UTC, same-id commented
Hey @c2thorn, bumping this

2023-12-06 22:15 UTC, c2thorn requested changes
Running tests now, if you wouldn't mind waiting for the build to finish (few hours) before pushing another commit for the minor change.

2023-12-06 22:15 UTC, c2thorn commented on mmv1/third_party/terraform/services/container/node_config.go.erb
> +					ForceNew:     false,
removing the line entirely is the same as a `false` value, and that would be preferable to keep it in line with most other resources.

2023-12-06 23:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3267` 
Passed tests `2930` 
Skipped tests: `334` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccContainerNodePool_withMachineAndDiskUpdate|TestAccGKEHub2Fleet_gkehubFleetBasicExample_update|TestAccHealthcareDatasetIamPolicy </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-07 00:10 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccContainerNodePool_withMachineAndDiskUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/8d9dad57-f53c-4db9-9a4d-5936df3c7ac5/recording/TestAccContainerNodePool_withMachineAndDiskUpdate.log)]
`TestAccGKEHub2Fleet_gkehubFleetBasicExample_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/8d9dad57-f53c-4db9-9a4d-5936df3c7ac5/recording/TestAccGKEHub2Fleet_gkehubFleetBasicExample_update.log)]
`TestAccHealthcareDatasetIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/8d9dad57-f53c-4db9-9a4d-5936df3c7ac5/recording/TestAccHealthcareDatasetIamPolicy.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/8d9dad57-f53c-4db9-9a4d-5936df3c7ac5/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/8d9dad57-f53c-4db9-9a4d-5936df3c7ac5/recording) for each test

2023-12-07 08:02 UTC, same-id commented
Seems like all tests passed, will change now

2023-12-07 09:29 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9575-old..auto-pr-9575) ( 3 files changed, 101 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9575-old..auto-pr-9575) ( 3 files changed, 101 insertions(+), 3 deletions(-))

2023-12-07 10:42 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3269` 
Passed tests `2935` 
Skipped tests: `334` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9575/artifacts/1c33f6c6-741f-43fd-a068-aa37fef8373d/build-log/replaying_test.log)

2023-12-07 17:00 UTC, c2thorn approved these changes
LGTM

2023-12-07 17:01 UTC, merged