Add default_from_api to gitIntegrationSettings
GoogleCloudPlatform/magic-modules pull request #9597
Opened 2023-12-07 01:40 UTC by trodge

Behavior of this field seems to have changed since https://github.com/GoogleCloudPlatform/magic-modules/pull/9078 was merged.

**Release Note Template for Downstream PRs (will be copied)**

```release-note:bug
diagflowcx: fixed a permadiff in the `git_integration_settings` field of `google_diagflow_cx_agent`
```

2023-12-07 01:52 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 1 insertion(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 1 insertion(+))

2023-12-07 03:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3268` 
Passed tests `2934` 
Skipped tests: `334` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9597/artifacts/e1bf3ea3-1a70-4f0e-964a-65d7913a2376/build-log/replaying_test.log)

2023-12-11 22:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 7 insertions(+), 30 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 7 insertions(+), 30 deletions(-))

2023-12-11 23:39 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3290` 
Passed tests `2952` 
Skipped tests: `337` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleServiceAccountJwt </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-11 23:42 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAccountJwt`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9597/artifacts/316ecdea-11f8-48ca-917f-1a3ee21d3fe9/recording/TestAccDataSourceGoogleServiceAccountJwt.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9597/artifacts/316ecdea-11f8-48ca-917f-1a3ee21d3fe9/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9597/artifacts/316ecdea-11f8-48ca-917f-1a3ee21d3fe9/recording) for each test

2023-12-12 00:24 UTC, trodge commented
The test passes locally. I'm not sure why it doesn't fail in VCR replaying mode.

2023-12-13 23:08 UTC, melinath requested changes
Small tweak to suggest to improve readability, otherwise LGTM & makes sense. I think VCR is probably still using the previous API response, so it still hasn't detected that this is broken. Attn @shuyama1 in terms of thinking about how we might be able to catch and/or re-record cases like this.

2023-12-13 23:08 UTC, melinath commented on mmv1/templates/terraform/custom_flatten/dialogflowcx_agent_git_integration_settings_github_settings.go.erb
> +	}
Looking at the nightly test failures - it looks like even if we don't set _anything_ for gitIntegrationSettings, the API will return a block like:

```
  "gitIntegrationSettings": {
    "githubSettings": {
      "accessToken": "REDACTED"
    }
  }
```

I'm a little concerned about checking just for `< 2` - if the API later _stops_ returning `accessToken: REDACTED` that could end up breaking things. It's also not immediately clear from the implementation _why_ we're using `< 2` - or more specifically, why this flatten function is behaving differently than the standard.

What would y'all think about instead explicitly removing accessToken and then going back to standard behavior - something like:

```suggestion
	// ignore access_token, which is always returned as REDACTED
	delete(original, "access_token");
	if len(original) == 0 {
		return nil
	}
```

2023-12-13 23:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report 
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 7 insertions(+), 29 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9597-old..auto-pr-9597) ( 1 file changed, 7 insertions(+), 29 deletions(-))

2023-12-14 00:20 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3292` 
Passed tests `2955` 
Skipped tests: `337` 
Affected tests: `0` 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9597/artifacts/05b77458-57eb-4683-9026-015ca5751dae/build-log/replaying_test.log)

2023-12-14 17:20 UTC, melinath approved these changes

2023-12-14 20:35 UTC, merged