Add support for creating a memcached instance that uses a specific IP address range
GoogleCloudPlatform/magic-modules pull request #9670
Opened 2023-12-18 19:23 UTC by kshitijjaiswal2

Add support for creating a memcached instance that uses a specific IP address range.
Github issue - [https://github.com/hashicorp/terraform-provider-google/issues/16819](https://www.google.com/url?q=https://github.com/hashicorp/terraform-provider-google/issues/16819&sa=D&source=buganizer&usg=AOvVaw0idc98DoPRr2rVXo0ACl0V)

2023-12-19 07:40 UTC, kshitijjaiswal2 commented
@roaks3 can you please review this?

2023-12-19 17:01 UTC, roaks3 requested changes
I had a few questions about the config, but once that is resolved, the field should be added to at least one test. In this case, that would most likely be `testAccMemcacheInstance_update()` or `testAccMemcacheInstance_update2()`.

2023-12-21 10:09 UTC, kshitijjaiswal2 commented on mmv1/products/memcache/Instance.yaml
> +    is_set: true
@roaks3 thanks for making things clear i have added the suggested changes we'll only keep ignore_read as the value is used for inital creation request only.

2023-12-21 15:00 UTC, roaks3 requested changes
Code LGTM, but could you also please add this to at least one test as mentioned in my previous comment?

2023-12-21 17:28 UTC, kshitijjaiswal2 commented on mmv1/products/memcache/Instance.yaml
> +    is_set: true
@roaks3 i have added the field to testAccMemcacheInstance_update().

2023-12-21 17:30 UTC, kshitijjaiswal2 commented
@roaks3 is it fine?

2023-12-21 18:59 UTC, roaks3 approved these changes
Yep, LGTM assuming tests pass

2023-12-22 16:43 UTC, kshitijjaiswal2 commented
@roaks3 can you please merge the code changes if they is fine?

2024-01-02 20:16 UTC, roaks3 commented
Hmm, I will have to check into this. It appears that for some reason the tests didn't run in CI (or they didn't report the results).

2024-01-02 21:45 UTC, roaks3 commented
Ah ok, this is due to an issue that was introduced at the end of December but has since been resolved.

@kshitijjaiswal2 could you please rebase this PR so that it is caught up with the latest changes from main? That should allow the automated tests to run (and hopefully pass so that we can merge)

2024-01-08 16:35 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 29 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 29 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9670-old..auto-pr-9670) ( 1 file changed, 10 insertions(+))

2024-01-08 16:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `1` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>memcache</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccMemcacheInstance_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-01-08 16:46 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccMemcacheInstance_update`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/640ef359-7e13-4a28-a71e-a2045cc8277f/build-log/recording_build/TestAccMemcacheInstance_update_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/640ef359-7e13-4a28-a71e-a2045cc8277f/recording/TestAccMemcacheInstance_update.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/640ef359-7e13-4a28-a71e-a2045cc8277f/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/640ef359-7e13-4a28-a71e-a2045cc8277f/recording) for each test

2024-01-09 16:17 UTC, roaks3 commented
It looks like the API is returning `"authorizedNetwork": "projects/ci-test-project-188019/global/networks/tf-bootstrap-net-memcache-instance-update-1"`, which doesn't match the request structure (`reservedIpRangeId: ...`), so it is not able to resolve state properly after that point.

This is non-standard API behavior that we tend to not encourage. To make this work, you may need to use `ignore_read: true` so that the API does not need to include `reservedIpRangeId` in the response, but this treats the field more like an initial setting only. I believe you can leave `authorizedNetwork` as-is, but it's possible you will need to do something to handle the new value being populated, with something like ignore_read or a diff suppress.

2024-01-15 21:54 UTC, kshitijjaiswal2 commented
@roaks3 could you please share the debug logs or error message with me, i don't have access to it, if possible can you grant me access to these logs?

2024-01-16 16:18 UTC, roaks3 commented
Sure, here are the relevant request/responses from the debug log:
```
---[ REQUEST ]---------------------------------------
POST /v1beta2/projects/ci-test-project-188019/locations/us-central1/instances?alt=json&instanceId=tf-test-6754803316342026879 HTTP/1.1
Host: memcache.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/acc
Content-Length: 356
Content-Type: application/json
Accept-Encoding: gzip

{
 "authorizedNetwork": "projects/ci-test-project-188019/global/networks/tf-bootstrap-net-memcache-instance-update-1",
 "memcacheVersion": "MEMCACHE_1_5",
 "nodeConfig": {
  "cpuCount": 1,
  "memorySizeMb": 1024
 },
 "nodeCount": 1,
 "parameters": {
  "params": {
   "listen-backlog": "2048",
   "max-item-size": "8388608"
  }
 },
 "reservedIpRangeId": [
  "tf-bootstrap-addr-memcache-instance-update-1"
 ]
}

-----------------------------------------------------
2024/01/08 16:37:52 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 08 Jan 2024 16:37:52 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/ci-test-project-188019/locations/us-central1/operations/operation-1704731872085-60e71d1ac4770-bfe4185a-e0e7bacc",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.memcache.v1beta2.OperationMetadata",
    "createTime": "2024-01-08T16:37:52.591934977Z",
    "target": "projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879",
    "verb": "create",
    "cancelRequested": false,
    "apiVersion": "v1beta2"
  },
  "done": false
}
...
---[ REQUEST ]---------------------------------------
GET /v1beta2/projects/ci-test-project-188019/locations/us-central1/operations/operation-1704731872085-60e71d1ac4770-bfe4185a-e0e7bacc?alt=json HTTP/1.1
Host: memcache.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2024/01/08 16:42:38 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 08 Jan 2024 16:42:38 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/ci-test-project-188019/locations/us-central1/operations/operation-1704731872085-60e71d1ac4770-bfe4185a-e0e7bacc",
  "metadata": {
    "@type": "type.googleapis.com/google.cloud.memcache.v1beta2.OperationMetadata",
    "createTime": "2024-01-08T16:37:52.591934977Z",
    "endTime": "2024-01-08T16:42:37.855701774Z",
    "target": "projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879",
    "verb": "create",
    "cancelRequested": false,
    "apiVersion": "v1beta2"
  },
  "done": true,
  "response": {
    "@type": "type.googleapis.com/google.cloud.memcache.v1beta2.Instance",
    "name": "projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879",
    "authorizedNetwork": "projects/ci-test-project-188019/global/networks/tf-bootstrap-net-memcache-instance-update-1",
    "zones": [
      "us-central1-a",
      "us-central1-b",
      "us-central1-c",
"us-central1-f"
    ],
    "nodeCount": 1,
    "nodeConfig": {
      "cpuCount": 1,
      "memorySizeMb": 1024
    },
    "memcacheVersion": "MEMCACHE_1_5",
    "parameters": {
      "id": "-1788763201",
      "params": {
        "listen-backlog": "2048",
        "max-item-size": "8388608"
      }
    },
    "memcacheNodes": [
      {
        "nodeId": "node-f-1",
        "zone": "us-central1-f",
        "state": "READY",
        "host": "10.236.0.4",
        "port": 11211,
        "parameters": {
          "id": "-1788763201",
          "params": {
            "listen-backlog": "2048",
            "max-item-size": "8388608"
          }
        },
        "memcacheVersion": "MEMCACHE_1_5",
        "memcacheFullVersion": "memcached-1.5.16"
      }
    ],
    "createTime": "2024-01-08T16:37:52.588213407Z",
    "updateTime": "2024-01-08T16:37:52.588213407Z",
    "state": "READY",
    "memcacheFullVersion": "memcached-1.5.16",
    "discoveryEndpoint": "10.236.0.3:11211"
  }
}

-----------------------------------------------------
2024/01/08 16:42:38 [DEBUG] Retry Transport: Stopping retries, last request was successful
2024/01/08 16:42:38 [DEBUG] Retry Transport: Returning after 1 attempts
2024/01/08 16:42:38 [DEBUG] Got done: true while polling for operation projects/ci-test-project-188019/locations/us-central1/operations/operation-1704731872085-60e71d1ac4770-bfe4185a-e0e7bacc's status
2024/01/08 16:42:38 [DEBUG] Finished creating Instance "projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879": map[string]interface {}{"done":false, "metadata":map[string]interface {}{"@type":"type.googleapis.com/google.cloud.memcache.v1beta2.OperationMetadata", "apiVersion":"v1beta2", "cancelRequested":false, "createTime":"2024-01-08T16:37:52.591934977Z", "target":"projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879", "verb":"create"}, "name":"projects/ci-test-project-188019/locations/us-central1/operations/operation-1704731872085-60e71d1ac4770-bfe4185a-e0e7bacc"}
2024/01/08 16:42:38 [DEBUG] Waiting for state to become: [success]
2024/01/08 16:42:38 [DEBUG] Retry Transport: starting RoundTrip retry loop
2024/01/08 16:42:38 [DEBUG] Retry Transport: request attempt 0
2024/01/08 16:42:38 [DEBUG] Google API Request Details:
---[ REQUEST ]---------------------------------------
GET /v1beta2/projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879?alt=json HTTP/1.1
Host: memcache.googleapis.com
User-Agent: Terraform/1.2.5 (+https://www.terraform.io) Terraform-Plugin-SDK/2.10.1 terraform-provider-google-beta/acc
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------
2024/01/08 16:42:38 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cache-Control: private
Content-Type: application/json; charset=UTF-8
Date: Mon, 08 Jan 2024 16:42:38 GMT
Server: ESF
Vary: Origin
Vary: X-Origin
Vary: Referer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 0

{
  "name": "projects/ci-test-project-188019/locations/us-central1/instances/tf-test-6754803316342026879",
  "authorizedNetwork": "projects/ci-test-project-188019/global/networks/tf-bootstrap-net-memcache-instance-update-1",
  "zones": [
    "us-central1-a",
    "us-central1-b",
    "us-central1-c",
"us-central1-f"
  ],
  "nodeCount": 1,
  "nodeConfig": {
    "cpuCount": 1,
    "memorySizeMb": 1024
  },
  "memcacheVersion": "MEMCACHE_1_5",
  "parameters": {
    "id": "-1788763201",
    "params": {
      "listen-backlog": "2048",
      "max-item-size": "8388608"
    }
  },
  "memcacheNodes": [
    {
      "nodeId": "node-f-1",
      "zone": "us-central1-f",
      "state": "READY",
      "host": "10.236.0.4",
      "port": 11211,
      "parameters": {
        "id": "-1788763201",
        "params": {
          "listen-backlog": "2048",
          "max-item-size": "8388608"
        }
      },
      "memcacheVersion": "MEMCACHE_1_5",
      "memcacheFullVersion": "memcached-1.5.16"
    }
  ],
  "createTime": "2024-01-08T16:37:52.588213407Z",
  "updateTime": "2024-01-08T16:42:37.878306603Z",
  "state": "READY",
  "memcacheFullVersion": "memcached-1.5.16",
  "discoveryEndpoint": "10.236.0.3:11211"
}
```

2024-01-16 16:20 UTC, roaks3 commented
And for reference, this is the error that is ultimately raised:
```
=== RUN   TestAccMemcacheInstance_update
=== PAUSE TestAccMemcacheInstance_update
=== CONT  TestAccMemcacheInstance_update
    vcr_utils.go:152: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=2) {
         (string) (len=22) "reserved_ip_range_id.#": (string) (len=1) "1",
         (string) (len=22) "reserved_ip_range_id.0": (string) (len=44) "tf-bootstrap-addr-memcache-instance-update-1"
        }
--- FAIL: TestAccMemcacheInstance_update (499.37s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-google-beta/google-beta/services/memcache	499.420s
FAIL
```

2024-01-23 10:39 UTC, kshitijjaiswal2 commented
@roaks3 updated with the recommended changes.

2024-01-23 18:28 UTC, roaks3 approved these changes
LGTM, will merge once the tests pass

2024-01-23 18:39 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 30 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 30 insertions(+), 1 deletion(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9670-old..auto-pr-9670) ( 1 file changed, 10 insertions(+))

2024-01-23 18:41 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2` 
Passed tests `1` 
Skipped tests: `0` 
Affected tests: `1` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>memcache</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccMemcacheInstance_update </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-01-23 18:58 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccMemcacheInstance_update`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/5e58b87b-f419-4b26-814f-ec8942791d18/recording/TestAccMemcacheInstance_update.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/5e58b87b-f419-4b26-814f-ec8942791d18/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/5e58b87b-f419-4b26-814f-ec8942791d18/recording) for each test

2024-01-23 19:56 UTC, roaks3 commented
This is failing during the lint step:
```
Run make lint
sh -c "'/home/runner/work/magic-modules/magic-modules/scripts/gofmtcheck.sh'"
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./google/services/memcache/resource_memcache_instance_test.go
You can use the command: `make fmt` to reformat code.
make: *** [GNUmakefile:2[6](https://github.com/GoogleCloudPlatform/magic-modules/actions/runs/7630287632/job/20785626737#step:10:7): fmtcheck] Error 1
Error: Process completed with exit code 2.
```

It looks like the indentation needs to be changed after adding `ImportStateVerifyIgnore`.

2024-01-25 10:19 UTC, kshitijjaiswal2 commented
@roaks3 can you trigger the test once again, or can you tell me how can i trigger the tests?

2024-01-25 14:57 UTC, roaks3 commented
Yep, kicking them off now. For security reasons, we don't allow contributors to run checks unless they are Google employees, so one of the downsides is that we have to manually click an approval button and pass along any error messages.

2024-01-25 15:08 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 33 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9670-old..auto-pr-9670) ( 4 files changed, 33 insertions(+), 4 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9670-old..auto-pr-9670) ( 1 file changed, 10 insertions(+))

2024-01-25 15:10 UTC, modular-magician commented
#### Tests analytics 
Total tests: `2` 
Passed tests `2` 
Skipped tests: `0` 
Affected tests: `0` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>memcache</li></ul></blockquote></details> 

$\textcolor{green}{\textsf{All tests passed in REPLAYING mode.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9670/artifacts/10261ffe-f172-4181-8d35-7f9a123d55dc/build-log/replaying_test.log)

2024-01-25 15:32 UTC, kshitijjaiswal2 commented
@roaks3 i am a google employee :)

2024-01-25 15:34 UTC, kshitijjaiswal2 commented
@roaks3 the checks have passed, can you merge the PR?

2024-01-25 15:52 UTC, roaks3 commented
Looks good, merging now. Note that I updated the PR description with the "fixes" keyword to make sure the issue is automatically closed.

Also, since you are a Google employee, make sure you've followed the steps at go/terraform-contribution-guide#before-you-begin to set up your org memberships. Once that is done, you should be able to see the checks automatically run on future PRs.

2024-01-25 15:52 UTC, merged