support vertexai featureonlinestore_featureview GA
GoogleCloudPlatform/magic-modules pull request #9686
Opened 2023-12-20 11:19 UTC by kkram01

This PR is to support vertexai [FeatureOnlineStore.Featureview](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureOnlineStores.featureViews#resource:-featureview) Resource with Terraform GA provider. 

**Release Note Template for Downstream PRs (will be copied)**

```release-note:new-resource
google_vertex_ai_feature_onlinestore_featureview
```

2023-12-20 11:20 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@slevenick, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2023-12-20 11:32 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1395 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1395 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9686-old..auto-pr-9686) ( 1 file changed, 216 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_feature_onlinestore_featureview` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_feature_onlinestore_featureview" "primary" {
  feature_registry_source {
    feature_groups {
      feature_group_id = # value needed
      feature_ids      = # value needed
    }
  }
  labels = # value needed
}

```

2023-12-20 12:37 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3312` 
Passed tests `2974` 
Skipped tests: `336` 
Affected tests: `2` 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated|TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-20 12:40 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/build-log/recording_build/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/recording/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated.log)]
`TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/build-log/recording_build/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/recording/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/8f0e2e55-294f-4ded-9944-b72bcc6c9b76/recording) for each test

2023-12-20 18:23 UTC, slevenick requested changes
Failing with:
        An argument named "force_destroy" is not expected here.

2023-12-20 19:54 UTC, kkram01 commented
> Failing with: An argument named "force_destroy" is not expected here.

Looks like the current version of featureonlinestore doesn't support force_destroy? I've a PR in for adding that and some beta fields to it. removed that field in the example for now.

2023-12-20 19:59 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1392 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1392 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9686-old..auto-pr-9686) ( 1 file changed, 216 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9686-old..auto-pr-9686) ( 4 files changed, 169 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_feature_onlinestore_featureview` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_feature_onlinestore_featureview" "primary" {
  feature_registry_source {
    feature_groups {
      feature_group_id = # value needed
      feature_ids      = # value needed
    }
  }
  labels = # value needed
}

```

2023-12-20 20:30 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1392 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1392 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9686-old..auto-pr-9686) ( 1 file changed, 216 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9686-old..auto-pr-9686) ( 4 files changed, 169 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_feature_onlinestore_featureview` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_feature_onlinestore_featureview" "primary" {
  feature_registry_source {
    feature_groups {
      feature_group_id = # value needed
      feature_ids      = # value needed
    }
  }
  labels = # value needed
}

```

2023-12-20 21:23 UTC, slevenick requested changes

2023-12-20 21:23 UTC, slevenick commented on mmv1/templates/terraform/encoders/vertex_ai_featureonlinestore_featureview.go.erb
> +		d.Set("region", parts[2])
Again, why region?

2023-12-20 21:28 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3314` 
Passed tests `2974` 
Skipped tests: `337` 
Affected tests: `3` 

#### Action taken 
<details> <summary>Found 3 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataprocClusterIamPolicy|TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated|TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-20 21:35 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataprocClusterIamPolicy`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/recording/TestAccDataprocClusterIamPolicy.log)]
`TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/recording/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureviewExample.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/build-log/recording_build/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/recording/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/44b98e24-b63b-4778-b547-7e1d476fd6ee/recording) for each test

2023-12-20 22:10 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1390 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9686-old..auto-pr-9686) ( 5 files changed, 1390 insertions(+), 2 deletions(-))
TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9686-old..auto-pr-9686) ( 1 file changed, 216 insertions(+))
TF OiCS: [Diff](https://github.com/modular-magician/docs-examples/compare/auto-pr-9686-old..auto-pr-9686) ( 4 files changed, 169 insertions(+))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_vertex_ai_feature_onlinestore_featureview` (3 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_vertex_ai_feature_onlinestore_featureview" "primary" {
  feature_registry_source {
    feature_groups {
      feature_group_id = # value needed
      feature_ids      = # value needed
    }
  }
  labels = # value needed
}

```

2023-12-20 22:17 UTC, shotarok commented on mmv1/templates/terraform/custom_import/vertex_ai_featureonlinestore_featureview.go.erb
> +	d.Set("region", parts[2])
Sorry for suddenly jumping into this PR. The VertexAI URL uses region in the host name.  

https://github.com/GoogleCloudPlatform/magic-modules/blob/4d160cb257e40ad9228a94766acfa3b77becb14e/mmv1/products/vertexai/product.yaml#L17-L23

Therefore, `google_vertex_ai_endpoint` started using `location`, but `region` was added later in my understanding. ref. https://github.com/hashicorp/terraform-provider-google/issues/16478

2023-12-20 23:08 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3314` 
Passed tests `2976` 
Skipped tests: `337` 
Affected tests: `1` 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2023-12-20 23:12 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/08d76884-a6ea-4f69-96e1-8e78bff30a73/recording/TestAccVertexAIFeatureOnlinestoreFeatureview_vertexAiFeatureonlinestoreFeatureview_updated.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/08d76884-a6ea-4f69-96e1-8e78bff30a73/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9686/artifacts/08d76884-a6ea-4f69-96e1-8e78bff30a73/recording) for each test

2023-12-21 09:20 UTC, kkram01 commented
@slevenick as discuused, raised this PR (https://github.com/GoogleCloudPlatform/magic-modules/pull/9696) as an alternate approach with the standard_url structure. pls review and share your thoughts on which would be the best way forward for this. Thanks!

2023-12-21 19:06 UTC, slevenick commented
> @slevenick as discuused, raised this PR (#9696) as an alternate approach with the standard_url structure. pls review and share your thoughts on which would be the best way forward for this. Thanks!

I think we should proceed with the alternate approach.

2023-12-21 19:23 UTC, kkram01 commented
> > @slevenick as discuused, raised this PR (#9696) as an alternate approach with the standard_url structure. pls review and share your thoughts on which would be the best way forward for this. Thanks!
> 
> I think we should proceed with the alternate approach.

Sure, Could you pls review that PR as well since you have the context related to this resource?

2024-01-05 00:47 UTC, melinath commented
Closing this PR per discussion above

2024-01-05 00:47 UTC, closed without merging