Adding google_compute_service_attachment data source
GoogleCloudPlatform/magic-modules pull request #9887
Opened 2024-01-27 06:08 UTC by sanmaym

This PR is for a new data resource that obtains the URI for a service attachment. Its based of this [google api ](https://cloud.google.com/compute/docs/reference/rest/v1/serviceAttachments/get)

**Release Note Template for Downstream PRs (will be copied)**

```release-note:This is for creating a data resource that will get the full URI for a compute service attachment resource

```

2024-01-27 06:09 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: Community Contributor ~Googler~ ~Core Contributor~. Tests will require approval to run.

@NickElliot, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2024-01-30 22:31 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 253 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 253 insertions(+))

2024-01-30 22:51 UTC, modular-magician commented
#### Tests analytics 
Total tests: `874` 
Passed tests `808` 
Skipped tests: `65` 
Affected tests: `1` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleServiceAttachment </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-01-30 22:52 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAttachment`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/3f1f884e-c2bc-47d4-8169-8e958968b45e/build-log/recording_build/TestAccDataSourceGoogleServiceAttachment_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/3f1f884e-c2bc-47d4-8169-8e958968b45e/recording/TestAccDataSourceGoogleServiceAttachment.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/3f1f884e-c2bc-47d4-8169-8e958968b45e/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/3f1f884e-c2bc-47d4-8169-8e958968b45e/recording) for each test

2024-02-01 21:47 UTC, NickElliot requested changes
Hi, the test is having an issue due to conflicting resource names. I suggested a broad formatting adjustment that should resolve this. Thanks!

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	t.Parallel()
```suggestion
	t.Parallel()
	
	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	serviceAttachmentName := fmt.Sprintf("tf-test-%s", acctest.RandString(t, 10))
```suggestion
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +				Config: testAccDataSourceGoogleServiceAttachmentConfig(serviceAttachmentName),
```suggestion
				Config: testAccDataSourceGoogleServiceAttachmentConfig(context),
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +func testAccDataSourceGoogleServiceAttachmentConfig(name string) string {
```suggestion
func testAccDataSourceGoogleServiceAttachmentConfig(context map[string]interface{}) string {
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	name = "producer-service-health-check"
```suggestion
	name = "producer-service-health-check%{random_suffix}"
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +`, name)
```suggestion
`, context)
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	return fmt.Sprintf(`
```suggestion
	return acctest.Nprintf(`
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	name   = "producer-forwarding-rule"
```suggestion
	name   = "producer-forwarding-rule%{random_suffix}"
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +  name                     = "%s"
```suggestion
  name                     = "tf-test%{random_suffix}"
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	name = "psc-ilb-network"
```suggestion
	name = "psc-ilb-network%{random_suffix}"
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	name   = "psc-ilb-producer-subnetwork"
```suggestion
	name   = "psc-ilb-producer-subnetwork%{random_suffix}"
```

2024-02-01 21:47 UTC, NickElliot commented on mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> +	name   = "psc-ilb-nat"
```suggestion
	name   = "psc-ilb-nat%{random_suffix}"
```

2024-02-01 22:01 UTC, sanmaym commented
Yes, I understood what i should do next. I was just busy with some other
work. I will make these changes
thank you so much.

*Sanmay Mishra*

Infrastructure Cloud Consultant

804-319-9657 <(804)%319-9657> Mobile




*“I choose to work flexibly & send emails outside normal office hours. **Please
do not feel obligated to respond out of your normal working hours."*


On Thu, Feb 1, 2024 at 1:48 PM Nick Elliot ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi, the test is having an issue due to conflicting resource names. I
> suggested a broad formatting adjustment that should resolve this. Thanks!
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475188471>
> :
>
> > +// Copyright (c) HashiCorp, Inc.
> +// SPDX-License-Identifier: MPL-2.0
> +package compute_test
> +
> +import (
> +	"fmt"
> +	"testing"
> +
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
> +	"github.com/hashicorp/terraform-provider-google/google/acctest"
> +	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
> +)
> +
> +func TestAccDataSourceGoogleServiceAttachment(t *testing.T) {
> +	t.Parallel()
>
> ⬇️ Suggested change
>
> -	t.Parallel()
> +	t.Parallel()
> +	
> +	context := map[string]interface{}{
> +		"random_suffix": acctest.RandString(t, 10),
> +	}
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475188707>
> :
>
> > +package compute_test
> +
> +import (
> +	"fmt"
> +	"testing"
> +
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
> +	"github.com/hashicorp/terraform-provider-google/google/acctest"
> +	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
> +)
> +
> +func TestAccDataSourceGoogleServiceAttachment(t *testing.T) {
> +	t.Parallel()
> +
> +	serviceAttachmentName := fmt.Sprintf("tf-test-%s", acctest.RandString(t, 10))
>
> ⬇️ Suggested change
>
> -	serviceAttachmentName := fmt.Sprintf("tf-test-%s", acctest.RandString(t, 10))
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475189371>
> :
>
> > +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
> +	"github.com/hashicorp/terraform-provider-google/google/acctest"
> +	"github.com/hashicorp/terraform-provider-google/google/tpgresource"
> +)
> +
> +func TestAccDataSourceGoogleServiceAttachment(t *testing.T) {
> +	t.Parallel()
> +
> +	serviceAttachmentName := fmt.Sprintf("tf-test-%s", acctest.RandString(t, 10))
> +	acctest.VcrTest(t, resource.TestCase{
> +		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
> +		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
> +		Steps: []resource.TestStep{
> +			{
> +				Config: testAccDataSourceGoogleServiceAttachmentConfig(serviceAttachmentName),
>
> ⬇️ Suggested change
>
> -				Config: testAccDataSourceGoogleServiceAttachmentConfig(serviceAttachmentName),
> +				Config: testAccDataSourceGoogleServiceAttachmentConfig(context),
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475189945>
> :
>
> > +					attr_to_check,
> +					ds_attr[attr_to_check],
> +					rs_attr[attr_to_check],
> +				)
> +			}
> +		}
> +
> +		if !tpgresource.CompareSelfLinkOrResourceName("", ds_attr["self_link"], rs_attr["self_link"], nil) && ds_attr["self_link"] != rs_attr["self_link"] {
> +			return fmt.Errorf("self link does not match: %s vs %s", ds_attr["self_link"], rs_attr["self_link"])
> +		}
> +
> +		return nil
> +	}
> +}
> +
> +func testAccDataSourceGoogleServiceAttachmentConfig(name string) string {
>
> ⬇️ Suggested change
>
> -func testAccDataSourceGoogleServiceAttachmentConfig(name string) string {
> +func testAccDataSourceGoogleServiceAttachmentConfig(context map[string]interface{}) string {
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475190315>
> :
>
> > +	load_balancing_scheme = "INTERNAL"
> +	backend_service       = google_compute_region_backend_service.producer_service_backend.id
> +	all_ports             = true
> +	network               = google_compute_network.psc_ilb_network.name
> +	subnetwork            = google_compute_subnetwork.psc_ilb_producer_subnetwork.name
> +  }
> +
> +  resource "google_compute_region_backend_service" "producer_service_backend" {
> +	name   = "producer-service"
> +	region = "us-west1"
> +
> +	health_checks = [google_compute_health_check.producer_service_health_check.id]
> +  }
> +
> +  resource "google_compute_health_check" "producer_service_health_check" {
> +	name = "producer-service-health-check"
>
> ⬇️ Suggested change
>
> -	name = "producer-service-health-check"
> +	name = "producer-service-health-check%{random_suffix}"
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475190423>
> :
>
> > +	ip_cidr_range = "10.0.0.0/16"
> +  }
> +
> +  resource "google_compute_subnetwork" "psc_ilb_nat" {
> +	name   = "psc-ilb-nat"
> +	region = "us-west1"
> +
> +	network       = google_compute_network.psc_ilb_network.id
> +	purpose       =  "PRIVATE_SERVICE_CONNECT"
> +	ip_cidr_range = "10.1.0.0/16"
> +  }
> +data "google_compute_service_attachment" "my_attachment" {
> +  name = google_compute_service_attachment.foobar.name
> +  region = google_compute_service_attachment.foobar.region
> +}
> +`, name)
>
> ⬇️ Suggested change
>
> -`, name)
> +`, context)
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475191052>
> :
>
> > +					ds_attr[attr_to_check],
> +					rs_attr[attr_to_check],
> +				)
> +			}
> +		}
> +
> +		if !tpgresource.CompareSelfLinkOrResourceName("", ds_attr["self_link"], rs_attr["self_link"], nil) && ds_attr["self_link"] != rs_attr["self_link"] {
> +			return fmt.Errorf("self link does not match: %s vs %s", ds_attr["self_link"], rs_attr["self_link"])
> +		}
> +
> +		return nil
> +	}
> +}
> +
> +func testAccDataSourceGoogleServiceAttachmentConfig(name string) string {
> +	return fmt.Sprintf(`
>
> ⬇️ Suggested change
>
> -	return fmt.Sprintf(`
> +	return acctest.Nprintf(`
>
> ------------------------------
>
> In
> mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go
> <https://github.com/GoogleCloudPlatform/magic-modules/pull/9887#discussion_r1475191676>
> :
>
> > +}
> +
> +func testAccDataSourceGoogleServiceAttachmentConfig(name string) string {
> +	return fmt.Sprintf(`
> +resource "google_compute_service_attachment" "foobar" {
> +  name                     = "%s"
> +  description              = "my-description"
> +  region                   = "us-west1"
> +  enable_proxy_protocol    = true
> +  connection_preference    = "ACCEPT_AUTOMATIC"
> +  nat_subnets              = [google_compute_subnetwork.psc_ilb_nat.id]
> +  target_service           = google_compute_forwarding_rule.psc_ilb_target_service.id
> +}
> +
> +resource "google_compute_forwarding_rule" "psc_ilb_target_service" {
>  [...]

2024-02-04 01:01 UTC, sanmaym commented
I accepted all your changes. Is there anything else remaining? It says that the community-checker step is queued

2024-02-05 22:21 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 256 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 256 insertions(+))

2024-02-05 22:23 UTC, modular-magician commented
#### Tests analytics 
Total tests: `0` 
Passed tests `0` 
Skipped tests: `0` 
Affected tests: `0` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details> 

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/dc7979ef-4f47-4d96-a17c-ebca966ea6e1/build-log/replaying_test.log)

2024-02-06 00:59 UTC, sanmaym reviewed
accepted all suggestions

2024-02-06 18:49 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 256 insertions(+))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9887-old..auto-pr-9887) ( 4 files changed, 256 insertions(+))

2024-02-06 19:11 UTC, modular-magician commented
#### Tests analytics 
Total tests: `886` 
Passed tests `812` 
Skipped tests: `73` 
Affected tests: `1` 

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>compute</li></ul></blockquote></details> 

#### Action taken 
<details> <summary>Found 1 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccDataSourceGoogleServiceAttachment </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-02-06 19:14 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccDataSourceGoogleServiceAttachment`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/20c28416-859a-4b80-bf66-630b5af7519a/recording/TestAccDataSourceGoogleServiceAttachment.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{green}{\textsf{All tests passed!}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/20c28416-859a-4b80-bf66-630b5af7519a/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9887/artifacts/20c28416-859a-4b80-bf66-630b5af7519a/recording) for each test

2024-02-07 15:59 UTC, sanmaym commented
@NickElliot can I get some guidance on this? it passed locally, but not sure where its failing. 
![Bwdisw363uNL2Pj](https://github.com/GoogleCloudPlatform/magic-modules/assets/101712230/34966e91-d950-4c11-b81c-ceb2190a46a7)

Also, every time I build the provider, I used to get this error message and always with these 2 resources/files . I would proceed to just replacing the file with the latest source code in github and then it would proceed with running the test case command. 

![KRmqkykYviok3Rh](https://github.com/GoogleCloudPlatform/magic-modules/assets/101712230/c3c8b5bf-8d73-4f48-a111-5eb8e5179582)

2024-02-07 21:29 UTC, NickElliot commented
@sanmaym there is almost certainly some conflict in your setup with your terraform/rebase -- often this sort of issue is resolved by doing the following:
clean your tpg/b folders, git pull
rebase your mmv1 branch on main
build mmv1

now you should be able to build the provider. if your tpg version gets out of date with your mmv1 version, it can end up causing funky build problems locally.

2024-02-07 21:30 UTC, NickElliot approved these changes
As is all looks good though! Just run the gofmt on the files and this PR will be ready to go.

2024-02-12 00:45 UTC, sanmaym commented
> @sanmaym there is almost certainly some conflict in your setup with your terraform versions -- often this sort of issue is resolved by doing the following: clean your tpg/b folders, git pull rebase your mmv1 branch on main build mmv1
> 
> now you should be able to build the provider. if your tpg version gets out of date with your mmv1 version, it can end up causing funky build problems locally even when nothing is wrong with the code (as seen by the CI passing your test)

@NickElliot I'm facing some challenges now. When I pull from upstream to get latest tpg updates, it didnt work. So, I just manually copied over the tpg directory from remote main to my local main. When I tried to build again, i'm seeing this error message

```
 for terraform
I, [2024-02-12T00:34:04.218685 #18239]  INFO -- : Compiling common files for terraform
make[1]: Leaving directory '/magic-modules'
make tpgtools
make[1]: Entering directory '/magic-modules'
make serialize
make[2]: Entering directory '/magic-modules'
cd tpgtools;\
        cp -f serialization.go.base serialization.go &&\
        go run . --path "api" --overrides "overrides" --mode "serialization" > temp.serial &&\
        mv -f temp.serial serialization.go
**go: cannot find main module, but found .git/config in /magic-modules**
        to create a module there, run:
        cd .. && go mod init
```
Any thoughts? 

Also , I have a second question about your comment here `Just run the gofmt on /google/services/compute/data_source_compute_service_attachment_test.go and this PR will be ready to go.`

This file is in the terraform provider that gets built right? As per my understanding, I only raise the PR from my magic modules repo. Then, what is the purpose of running the gofmt command there?

2024-02-13 15:08 UTC, sanmaym commented
any thoughts @NickElliot ?

2024-02-27 18:07 UTC, NickElliot commented
sorry for the delay, I went on PTO a couple days before your updates and didn't flag this PR to another reviewer, my bad!

2024-02-29 00:02 UTC, NickElliot reviewed
> build issue

Please do the following within your `/github.com/hashicorp/terraform-provider-google-beta/` directory
```
git checkout -- .
git clean -f google/ google-beta/ website/
git pull
```
this should allow you to clean up your provider and get the updates

then in your mmv1 folder while in your fork and branch for this pull request
```
git fetch upstream
git rebase upstream/main
```
then finish the rebase process

>gofmt

`mmv1/third_party/terraform/services/compute/data_source_compute_service_attachment_test.go` is a file you added in this pr, I'm asking you to run it on that file, not the downstream generated one.

2024-03-01 19:52 UTC, sanmaym commented
@NickElliot thanks for the detailed review.. does this look good now?

2024-03-04 20:14 UTC, NickElliot commented
/gcbrun

2024-03-04 22:15 UTC, NickElliot commented
please rebase again, sorry!

2024-04-11 21:51 UTC, NickElliot requested changes
see above

2024-06-12 09:41 UTC, closed without merging