Magician tgc integration
GoogleCloudPlatform/magic-modules pull request #9907
Opened 2024-02-01 21:06 UTC by trodge

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-02-01 21:16 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-02-01 23:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 1 insertion(+))

2024-02-05 19:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-02-05 22:40 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-02-06 18:07 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-02-06 21:47 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-02-07 00:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-02-07 01:41 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

TF Conversion: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-02-08 21:04 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-03-04 19:38 UTC, melinath requested changes
I think this needs some changes to account for the token split. Could you also trigger the test run? (Might require making a separate PR that's based on this branch, which might require making this a branch in the GCP mm repo?)

2024-03-04 22:31 UTC, trodge commented
> I think this needs some changes to account for the token split. Could you also trigger the test run? (Might require making a separate PR that's based on this branch, which might require making this a branch in the GCP mm repo?)

I have rebased off of https://github.com/GoogleCloudPlatform/magic-modules/pull/10114 , so that PR will need to be merged first.

2024-03-04 22:44 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-03-12 20:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR hasn't generated any diffs, but I'll let you know if a future commit does.

2024-03-14 21:33 UTC, melinath approved these changes
LGTM - the yml changes shouldn't cause any issues since people with the old yml will just call the old script (which isn't changing.) Could you force TGC integration tests to run on this PR before merging just to be safe?

2024-03-20 17:23 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9907-old..auto-pr-9907) ( 1 file changed, 2 insertions(+))

2024-03-20 18:22 UTC, merged

2024-03-20 18:27 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR hasn't generated any diffs, but I'll let you know if a future commit does.