Add sample for trigger using http_destination
GoogleCloudPlatform/magic-modules pull request #9941
Opened 2024-02-07 20:55 UTC by nlopezgi

Add sample for trigger using http_destination

- [ ] Searched through the [issue tracker](https://github.com/hashicorp/terraform-provider-google/issues) for an open issue that this either resolves or contributes to, commented on it to claim it, and written "fixes {url}" or "part of {url}" in this PR description. If there were no relevant open issues, I opened one and commented that I would like to work on it (not necessary for very small changes).
- [ ] Ensured that all new fields I added that can be set by a user appear in at least one [example](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples) (for generated resources) or [third_party test](https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/tests) (for handwritten resources or update tests).
- [ ] [Generated Terraform providers](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/generate-providers.md), and ran [make test and make lint](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/run-provider-tests/#run-unit-tests) in the generated providers to ensure it passes unit and linter tests.
 - [ ] [Ran](https://github.com/GoogleCloudPlatform/magic-modules/blob/main/docs/content/docs/getting-started/run-provider-tests.md) relevant acceptance tests using my own Google Cloud project and credentials (If the acceptance tests do not yet pass or you are unable to run them, please let your reviewer know).
- [ ]  Read [Write release notes](https://googlecloudplatform.github.io/magic-modules/contribute/release-notes/) before writing my release note below.

**Release Note Template for Downstream PRs (will be copied)**

```
release-note:enhancement: eventarc: added sample for field `http_destination` to `google_eventarc_trigger`

```

2024-02-07 20:57 UTC, modular-magician commented
Hello! I am a robot. It looks like you are a: ~Community Contributor~ Googler ~Core Contributor~. Tests will run automatically.

@shuyama1, a repository maintainer, has been assigned to review your changes. If you have not received review feedback within 2 business days, please leave a comment on this PR asking them to take a look.

You can help make sure that review is quick by [doing a self-review](https://googlecloudplatform.github.io/magic-modules/contribute/review-pr/) and by [running impacted tests locally](https://googlecloudplatform.github.io/magic-modules/get-started/run-provider-tests/).

2024-02-07 21:06 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9941-old..auto-pr-9941) ( 2 files changed, 65 insertions(+), 1 deletion(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9941-old..auto-pr-9941) ( 2 files changed, 65 insertions(+), 1 deletion(-))

2024-02-08 17:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9941-old..auto-pr-9941) ( 9 files changed, 245 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9941-old..auto-pr-9941) ( 9 files changed, 245 insertions(+), 13 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (19 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          runtime_config {
            cloud_run {
              canary_revision_tags = # value needed
              prior_revision_tags  = # value needed
              stable_revision_tags = # value needed
            }
            kubernetes {
              gateway_service_mesh {
                stable_cutback_duration = # value needed
              }
            }
          }
        }
      }
    }
  }
}

```

2024-02-08 19:00 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3423` 
Passed tests `3070` 
Skipped tests: `351` 
Affected tests: `2` 

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details> 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccClouddeployDeliveryPipeline_CanaryrunDeliveryPipeline|TestAccEventarcTrigger_HttpDest </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-02-08 19:04 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccClouddeployDeliveryPipeline_CanaryrunDeliveryPipeline`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/b70a1034-c6ff-4b05-b75a-5dca91669d16/recording/TestAccClouddeployDeliveryPipeline_CanaryrunDeliveryPipeline.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccEventarcTrigger_HttpDest`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/b70a1034-c6ff-4b05-b75a-5dca91669d16/build-log/recording_build/TestAccEventarcTrigger_HttpDest_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/b70a1034-c6ff-4b05-b75a-5dca91669d16/recording/TestAccEventarcTrigger_HttpDest.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/b70a1034-c6ff-4b05-b75a-5dca91669d16/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/b70a1034-c6ff-4b05-b75a-5dca91669d16/recording) for each test

2024-02-09 04:33 UTC, NickElliot requested changes
need this to be updated!

2024-02-09 04:33 UTC, NickElliot commented on mmv1/third_party/terraform/services/eventarc/resource_eventarc_trigger_test.go.erb
> +
```suggestion
                "network_attachment": fullFormNetworkAttachmentName,
                "random_suffix": acctest.RandString(t, 10),
```

2024-02-09 14:26 UTC, nlopezgi commented
> need this to be updated!
fixed

2024-02-09 14:36 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9941-old..auto-pr-9941) ( 9 files changed, 246 insertions(+), 13 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9941-old..auto-pr-9941) ( 9 files changed, 246 insertions(+), 13 deletions(-))

## Missing test report
Your PR includes resource fields which are not covered by any test.

Resource: `google_clouddeploy_delivery_pipeline` (19 total tests)
Please add an acceptance test which includes these fields. The test should include the following:

```hcl
resource "google_clouddeploy_delivery_pipeline" "primary" {
  serial_pipeline {
    stages {
      strategy {
        canary {
          runtime_config {
            cloud_run {
              canary_revision_tags = # value needed
              prior_revision_tags  = # value needed
              stable_revision_tags = # value needed
            }
            kubernetes {
              gateway_service_mesh {
                stable_cutback_duration = # value needed
              }
            }
          }
        }
      }
    }
  }
}

```

2024-02-09 15:36 UTC, modular-magician commented
#### Tests analytics 
Total tests: `3424` 
Passed tests `3071` 
Skipped tests: `351` 
Affected tests: `2` 

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details> 

#### Action taken 
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccEventarcTrigger_HttpDest|TestAccWorkstationsWorkstationConfig_updateHostDetails </blockquote></details> 

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-02-09 16:34 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$ 
 `TestAccEventarcTrigger_HttpDest`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/4d1ad7ca-9766-48e2-8028-0cad96e47625/recording/TestAccEventarcTrigger_HttpDest.log)] 

##### Rerun these tests in REPLAYING mode to catch issues 

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$ 

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$ 
 `TestAccWorkstationsWorkstationConfig_updateHostDetails`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/4d1ad7ca-9766-48e2-8028-0cad96e47625/build-log/recording_build/TestAccWorkstationsWorkstationConfig_updateHostDetails_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/4d1ad7ca-9766-48e2-8028-0cad96e47625/recording/TestAccWorkstationsWorkstationConfig_updateHostDetails.log)] 

$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$ 
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/4d1ad7ca-9766-48e2-8028-0cad96e47625/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9941/artifacts/4d1ad7ca-9766-48e2-8028-0cad96e47625/recording) for each test

2024-02-09 18:01 UTC, NickElliot approved these changes
Unrelated test failure, LGTM! Thanks for handling the long contribution process!

2024-02-09 18:08 UTC, merged