Add additional wait in TestAccFirestoreField_* tests
GoogleCloudPlatform/magic-modules pull request #9957
Opened 2024-02-09 16:45 UTC by SarahFrench

Adding an additional delay in TestAccFirestoreField_* tests to address an 100% error occurring since late Jan:

![Screenshot 2024-02-09 at 16 43 41](https://github.com/GoogleCloudPlatform/magic-modules/assets/15078782/d01b14fa-552c-4f20-a21f-c0163b26955a)

```
------- Stdout: -------
=== RUN   TestAccFirestoreField_firestoreFieldUpdateAddIndexExample
=== PAUSE TestAccFirestoreField_firestoreFieldUpdateAddIndexExample
=== CONT  TestAccFirestoreField_firestoreFieldUpdateAddIndexExample
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: googleapi: Error 403: Cloud Firestore API has not been used in project tf-test3abifux6ev before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=tf-test3abifux6ev then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
        Details:
        [
          {
            "@type": "type.googleapis.com/google.rpc.Help",
            "links": [
              {
                "description": "Google developers console API activation",
                "url": "https://console.developers.google.com/apis/api/firestore.googleapis.com/overview?project=tf-test3abifux6ev
              }
            ]
          },
          {
            "@type": "type.googleapis.com/google.rpc.ErrorInfo",
            "domain": "googleapis.com",
            "metadata": {
              "consumer": "projects/tf-test3abifux6ev",
              "service": "firestore.googleapis.com"
            },
            "reason": "SERVICE_DISABLED"
          }
        ]
--- FAIL: TestAccFirestoreField_firestoreFieldUpdateAddIndexExample (1163.75s)
FAIL
```

**Release Note Template for Downstream PRs (will be copied)**

```release-note:none

```

2024-02-09 16:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 11 insertions(+), 3 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 11 insertions(+), 3 deletions(-))

2024-02-09 17:01 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/a77159a0-dd6a-4925-973d-b41f6b01152b/build-log/replaying_test.log)

2024-02-09 21:02 UTC, SarahFrench commented
[Running a build against this PR in TeamCity here](https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_FIRESTORE/98992?mode=builds&buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true)

2024-02-12 21:40 UTC, melinath requested changes
Looks like the teamcity tests are still failing

2024-02-13 11:13 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 12 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 12 insertions(+), 4 deletions(-))

2024-02-13 11:28 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/5a7fb08f-ff3b-45b5-a80b-6f4d570f2787/build-log/replaying_test.log)

2024-02-13 12:25 UTC, SarahFrench commented
Ah, I just realised that this permission error is coming at the end of the test during cleanup. I had assumed the problem was enabling the service at the start of the test.

2024-02-13 12:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 4 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 4 insertions(+), 4 deletions(-))

2024-02-13 12:59 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/1a4468c7-d16d-4dba-9420-9e0a70a6ced6/build-log/replaying_test.log)

2024-02-13 17:18 UTC, SarahFrench commented
I'm re-running this test in TeamCity after each change but the test cleanup keeps deleting the project first. To my understanding, this shouldn't be happening as the project resource has dependant resources (via implicit and explicit dependencies). The destroy order should be the reverse of the create order, so I think I'm overlooking something

2024-02-13 17:26 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 8 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 1 file changed, 8 insertions(+), 4 deletions(-))

2024-02-13 17:30 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/1c21f94b-87e4-42a9-ac69-82f1a7214068/build-log/replaying_test.log)

2024-02-13 19:31 UTC, SarahFrench commented
Order of events in the test is:
- 'Deletion' of firestore field resource - it's not deletable but is altered via PATCH request
- Deletion of DB is skipped: "Firestore database "(default)" deletion_policy is not set to 'DELETE', skipping deletion"
- Firestore service is disabled
- Project is deleted
- Then, there's a random GET request for the firestore field that triggers the 403

The GET request makes sense if the field cannot be deleted and the data base also isn't deleted. Terraform presumably wants to refresh state.

2024-02-13 19:46 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 2 files changed, 10 insertions(+), 4 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 2 files changed, 10 insertions(+), 4 deletions(-))

2024-02-13 19:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/c612c4f6-94ab-403c-bcd2-f8574e858fed/build-log/replaying_test.log)

2024-02-14 14:26 UTC, SarahFrench commented
Ah the problem appears to be that the `CheckDestroy` for the test isn't well equipped for when the test creates a new separate project

2024-02-28 13:05 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 3 files changed, 19 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 3 files changed, 19 insertions(+), 2 deletions(-))

2024-02-28 13:09 UTC, modular-magician commented
#### Tests analytics
Total tests: `17`
Passed tests: `17`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote><ul><li>firestore</li></ul></blockquote></details>

$\textcolor{green}{\textsf{All tests passed!}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9957/artifacts/e6bc7197-65d4-4971-9746-e99c05d6bd54/build-log/replaying_test.log)

2024-02-28 13:12 UTC, SarahFrench commented
This build in TeamCity runs TestAccFirestoreField_firestoreFieldUpdateAddIndexExample against this PR: https://hashicorp.teamcity.com/buildConfiguration/TerraformProviders_GoogleCloud_GOOGLE_MMUPSTREAMTESTS_GOOGLE_PACKAGE_FIRESTORE/108307?mode=builds&buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false

2024-02-28 14:33 UTC, SarahFrench commented
Test passed!

2024-02-28 14:34 UTC, SarahFrench commented on mmv1/templates/terraform/custom_delete/firestore_field_delete.go.erb
> +d.SetId("") // Remove the resource from state
I'll remove this as, while it might be a legitimate thing to add, this PR isn't the correct place

2024-02-28 14:45 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report
Your PR generated some diffs in downstreams - here they are.

Terraform GA: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9957-old..auto-pr-9957) ( 2 files changed, 16 insertions(+), 2 deletions(-))
Terraform Beta: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9957-old..auto-pr-9957) ( 2 files changed, 16 insertions(+), 2 deletions(-))

2024-03-04 19:06 UTC, melinath approved these changes
LGTM - I think that this needs to be marked as fixing a few different test failure tickets before merge though

2024-03-05 11:14 UTC, merged