Move diff suppress funcs used by a single services into that service's package
GoogleCloudPlatform/magic-modules pull request #9962
Opened 2024-02-09 23:56 UTC by BBBmau

Fixes https://github.com/hashicorp/terraform-provider-google/issues/17114

**Release Note Template for Downstream PRs (will be copied)**

```release-note:REPLACEME

```

2024-02-10 00:31 UTC, BBBmau commented
left out `TimestampDiffSuppress` since it's used in 2 different services

2024-02-12 15:06 UTC, slevenick requested changes
Looks like it's not compiling due to import issues

2024-06-19 05:48 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 471 insertions(+), 613 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 473 insertions(+), 615 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-19 05:50 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/70b4a98a-0f79-49d4-bdf5-9ab9f641024b/build-log/replaying_test.log)

2024-06-19 05:56 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 471 insertions(+), 618 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 473 insertions(+), 625 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-19 05:58 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 471 insertions(+), 618 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 473 insertions(+), 625 deletions(-))



## Errors

`google` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-19 05:58 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/a6cb993d-cf2a-42e0-a79e-5c6242d9a60a/build-log/replaying_test.log)

2024-06-19 06:00 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/d66c3870-02c0-42fa-917e-f800d16b756a/build-log/replaying_test.log)

2024-06-19 11:12 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 664 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 671 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 7 files changed, 137 insertions(+))

2024-06-19 11:14 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 664 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 666 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 7 files changed, 137 insertions(+))



## Errors

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-19 11:14 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/34598b16-5092-4415-a0b3-609495ae9f32/build-log/replaying_test.log)

2024-06-19 11:16 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/896df9b2-52dd-436e-9735-7f6f500f9047/build-log/replaying_test.log)

2024-06-19 11:17 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 664 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 666 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 7 files changed, 137 insertions(+))



## Errors

`google-beta` provider:
- The diff processor failed to build. This is usually due to the downstream provider failing to compile.

2024-06-19 11:20 UTC, modular-magician commented
#### Tests analytics
Total tests: `0`
Passed tests: `0`
Skipped tests: `0`
Affected tests: `0`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap

$\textcolor{red}{\textsf{Errors occurred during REPLAYING mode. Please fix them to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/22fc04fb-8329-4e04-aa65-a419c002802d/build-log/replaying_test.log)

2024-06-20 02:28 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 32 files changed, 664 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 34 files changed, 671 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 8 files changed, 142 insertions(+))

2024-06-20 03:26 UTC, modular-magician commented
#### Tests analytics
Total tests: `3747`
Passed tests: `3366`
Skipped tests: `377`
Affected tests: `4`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitDataprocCluster_LocationDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap


#### Action taken
<details> <summary>Found 4 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccFirebaseAppCheckAppAttestConfig_firebaseAppCheckAppAttestConfigUpdate|TestAccFirestoreField_firestoreFieldUpdateAddTTLExample|TestAccLoggingBucketConfigOrganization_basic </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-20 03:50 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 31 files changed, 624 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 33 files changed, 631 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 8 files changed, 142 insertions(+))

2024-06-20 03:59 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccFirebaseAppCheckAppAttestConfig_firebaseAppCheckAppAttestConfigUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/recording/TestAccFirebaseAppCheckAppAttestConfig_firebaseAppCheckAppAttestConfigUpdate.log)]
`TestAccFirestoreField_firestoreFieldUpdateAddTTLExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/recording/TestAccFirestoreField_firestoreFieldUpdateAddTTLExample.log)]


$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/recording/TestAccLoggingBucketConfigOrganization_basic.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/dafe4751-10ed-4d36-97c7-afffe5455945/recording) for each test

2024-06-20 04:48 UTC, modular-magician commented
#### Tests analytics
Total tests: `3804`
Passed tests: `3420`
Skipped tests: `382`
Affected tests: `2`

<details><summary>Click here to see the affected service packages</summary><blockquote>all service packages are affected</blockquote></details>


#### Non-exercised tests

Tests were added that are skipped in VCR:

- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap


#### Action taken
<details> <summary>Found 2 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests</summary><blockquote>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy|TestAccLoggingBucketConfigOrganization_basic </blockquote></details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-20 05:17 UTC, modular-magician commented
$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]
`TestAccLoggingBucketConfigOrganization_basic`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/build-log/recording_build/TestAccLoggingBucketConfigOrganization_basic_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/recording/TestAccLoggingBucketConfigOrganization_basic.log)]


$\textcolor{red}{\textsf{Please fix these to complete your PR.}}$
View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/2ffcf0a9-e5c2-4e10-8fc3-d3d54c4ab340/recording) for each test

2024-06-22 00:54 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 31 files changed, 624 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 33 files changed, 631 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 8 files changed, 142 insertions(+))

2024-06-22 00:57 UTC, modular-magician commented
Hi there, I'm the Modular magician. I've detected the following information about your changes:

## Diff report

Your PR generated some diffs in downstreams - here they are.

`google` provider: [Diff](https://github.com/modular-magician/terraform-provider-google/compare/auto-pr-9962-old..auto-pr-9962) ( 31 files changed, 624 insertions(+), 656 deletions(-))
`google-beta` provider: [Diff](https://github.com/modular-magician/terraform-provider-google-beta/compare/auto-pr-9962-old..auto-pr-9962) ( 33 files changed, 631 insertions(+), 663 deletions(-))
`terraform-google-conversion`: [Diff](https://github.com/modular-magician/terraform-google-conversion/compare/auto-pr-9962-old..auto-pr-9962) ( 8 files changed, 142 insertions(+))

2024-06-22 01:52 UTC, modular-magician commented
#### Tests analytics
Total tests: 6858
Passed tests: 3424
Skipped tests: 376
Affected tests: 10

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap
#### Action taken
<details>
<summary>Found 10 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccComputeInstance_noServiceAccount</li>
<li>TestAccComputeInstance_serviceAccountEmail_0scopes</li>
<li>TestAccComputeInstance_serviceAccount_updated</li>
<li>TestAccComputeInstance_serviceAccount_updated0to1to0scopes</li>
<li>TestAccFirebaseHostingChannel_firebasehostingChannelUpdate</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteBasicExample</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteFullExample</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteUpdate</li>
<li>TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-22 01:55 UTC, modular-magician commented
#### Tests analytics
Total tests: 6858
Passed tests: 3424
Skipped tests: 376
Affected tests: 10

<details>
<summary>Click here to see the affected service packages</summary>
<blockquote>

All service packages are affected

</blockquote>
</details>
#### Non-exercised tests

Tests were added that are skipped in VCR:
- TestUnitCloudSchedulerJob_LastSlashDiffSuppress
- TestUnitComputeGlobalForwardingRule_InternalIpDiffSuppress
- TestUnitComputeGlobalForwardingRule_PortRangeDiffSuppress
- TestUnitComputeInstanceTemplate_IpCidrRangeDiffSuppress
- TestUnitComputeManagedSslCertificate_AbsoluteDomainSuppress
- TestUnitContainerCluster_Rfc3339TimeDiffSuppress
- TestUnitLoggingFolder_OptionalPrefixSuppress
- TestUnitLoggingSink_OptionalSurroundingSpacesSuppress
- TestUnitPubsubSubscription_IgnoreMissingKeyInMap
#### Action taken
<details>
<summary>Found 10 affected test(s) by replaying old test recordings. Starting RECORDING based on the most recent commit. Click here to see the affected tests
</summary>
<blockquote>
<ul>
<li>TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy</li>
<li>TestAccComputeInstance_noServiceAccount</li>
<li>TestAccComputeInstance_serviceAccountEmail_0scopes</li>
<li>TestAccComputeInstance_serviceAccount_updated</li>
<li>TestAccComputeInstance_serviceAccount_updated0to1to0scopes</li>
<li>TestAccFirebaseHostingChannel_firebasehostingChannelUpdate</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteBasicExample</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteFullExample</li>
<li>TestAccFirebaseHostingSite_firebasehostingSiteUpdate</li>
<li>TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample</li>

</ul>
</blockquote>
</details>

[Get to know how VCR tests work](https://googlecloudplatform.github.io/magic-modules/docs/getting-started/contributing/#general-contributing-steps)

2024-06-22 02:24 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_noServiceAccount`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccComputeInstance_noServiceAccount.log)]
`TestAccComputeInstance_serviceAccountEmail_0scopes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccComputeInstance_serviceAccountEmail_0scopes.log)]
`TestAccComputeInstance_serviceAccount_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccComputeInstance_serviceAccount_updated.log)]
`TestAccComputeInstance_serviceAccount_updated0to1to0scopes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccComputeInstance_serviceAccount_updated0to1to0scopes.log)]
`TestAccFirebaseHostingChannel_firebasehostingChannelUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccFirebaseHostingChannel_firebasehostingChannelUpdate.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccFirebaseHostingSite_firebasehostingSiteBasicExample.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccFirebaseHostingSite_firebasehostingSiteFullExample.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccFirebaseHostingSite_firebasehostingSiteUpdate.log)]
`TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/5b0deaa5-f367-4fbe-a481-26a3873bda35/recording) for each test

2024-06-22 02:25 UTC, modular-magician commented
$\textcolor{green}{\textsf{Tests passed during RECORDING mode:}}$
`TestAccComputeInstance_noServiceAccount`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccComputeInstance_noServiceAccount.log)]
`TestAccComputeInstance_serviceAccountEmail_0scopes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccComputeInstance_serviceAccountEmail_0scopes.log)]
`TestAccComputeInstance_serviceAccount_updated`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccComputeInstance_serviceAccount_updated.log)]
`TestAccComputeInstance_serviceAccount_updated0to1to0scopes`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccComputeInstance_serviceAccount_updated0to1to0scopes.log)]
`TestAccFirebaseHostingChannel_firebasehostingChannelUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccFirebaseHostingChannel_firebasehostingChannelUpdate.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteBasicExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccFirebaseHostingSite_firebasehostingSiteBasicExample.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteFullExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccFirebaseHostingSite_firebasehostingSiteFullExample.log)]
`TestAccFirebaseHostingSite_firebasehostingSiteUpdate`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccFirebaseHostingSite_firebasehostingSiteUpdate.log)]
`TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample`[[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccFirebaseHostingVersion_firebasehostingVersionCloudFunctionsExample.log)]

$\textcolor{green}{\textsf{No issues found for passed tests after REPLAYING rerun.}}$

---


$\textcolor{red}{\textsf{Tests failed during RECORDING mode:}}$
`TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy`[[Error message](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/build-log/recording_build/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy_recording_test.log)] [[Debug log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording/TestAccComputeInstanceNetworkIntefaceWithSecurityPolicy.log)]


$\textcolor{red}{\textsf{Errors occurred during RECORDING mode. Please fix them to complete your PR.}}$


View the [build log](https://storage.cloud.google.com/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/build-log/recording_test.log) or the [debug log](https://console.cloud.google.com/storage/browser/ci-vcr-logs/beta/refs/heads/auto-pr-9962/artifacts/3bc625db-5275-47f2-b675-955435f8d620/recording) for each test

2024-06-22 03:37 UTC, BBBmau commented
Requesting another review on this since the latest VCR run resulted in a failed test that doesn't look to be related to the changes in this PR:

```
    vcr_utils.go:152: Step 3/4 error: Error running apply: exit status 1
        
        Error: Error deleting old access_config: googleapi: Error 400: Invalid value for field 'accessConfig': 'external-nat'. Cannot delete an access config with a security policy set. Please remove the security policy first., invalid
        
          with google_compute_instance.foobar,
          on terraform_plugin_test.tf line 119, in resource "google_compute_instance" "foobar":
         119: resource "google_compute_instance" "foobar" {
```

2024-06-25 19:09 UTC, slevenick approved these changes

2024-06-25 19:58 UTC, merged